### ISSUE TITLE
langflow 0.5.3 start issue

### ISSUE THREAD

**Issue by chensi2017** [langflow-ai/langflow#1047]
[10/12/23 22:26:30] INFO     2023-10-12 22:26:30 - INFO     - logger - Log file: /Users/user/Library/Caches/langflow/langflow.log              logger.py:69
                    ERROR    2023-10-12 22:26:30 - ERROR    - manager - Missing column: user_id in table flow                                manager.py:109
                    INFO     2023-10-12 22:26:30 - INFO     - manager - Alembic not initialized                                              manager.py:138
                    INFO     2023-10-12 22:26:30 - INFO     - manager - Initializing alembic                                                 manager.py:119
                    INFO     2023-10-12 22:26:30 - INFO     - manager - Alembic initialized                                                  manager.py:124
                    INFO     2023-10-12 22:26:30 - INFO     - manager - Running DB migrations in                                             manager.py:147
                             /opt/homebrew/lib/python3.9/site-packages/langflow/alembic                                                                    
[10/12/23 22:26:31] ERROR    2023-10-12 22:26:31 - ERROR    - utils - Error migrating flows: (sqlite3.OperationalError) no such column:        utils.py:216
                             flow.user_id                                                                                                                  
                             [SQL: SELECT flow.data AS flow_data, flow.name AS flow_name, flow.description AS flow_description, flow.id AS                 
                             flow_id, flow.user_id AS flow_user_id                                                                                         
                             FROM flow                                                                                                                     
                             WHERE flow.user_id IS NULL]                                                                                                   
                             (Background on this error at: https://sqlalche.me/e/14/e3q8)

**Comment by 53X** [comment]
I have the same problem

**Comment by damhack** [comment]
Same.  Looks like the sqllite database from an older install of Langflow isn't being cleaned when uninstalling and reinstalling Langflow.  Help appreciated.

**Comment by damhack** [comment]
Solved.  Just delete the langflow.db file that will be stored wherever you ran langflow from previously.

E.g. `find ~ -name langflow.db`

should find it

**Comment by AlexeyDep** [comment]
Hey guys. I deleted langflow.db everywhere, but it's still an error.

**Comment by latslats** [comment]
Flowise works so much better, this is so buggy ...
