### ISSUE TITLE
BUG: list.flow not working

### ISSUE THREAD

**Issue by yamonkjd** [langflow-ai/langflow#1099]
![image](https://github.com/logspace-ai/langflow/assets/141118378/d8ab590a-cd15-41dc-ae3f-347815853cdb)

https://docs.langflow.org/examples/flow-runner

The flowrunner in the official example does not build properly. It outputs the following error:
```
Error building node CustomComponent: Session is invalid
```

**Comment by ogabrielluiz** [comment]
Hey @yamonkjd 

I'll take a look at this.

We are gearing up on some big changes, sorry for the delayed responses.

**Comment by matthias** [comment]
This is a very hacky fix:

```python
def build_config(self):
        self._user_id = "none"
        flows = self.list_flows()
        ...
``` 

But the core team should look into the original code of the `CustomComponent`

**Comment by liweifeng2022** [comment]
@ogabrielluiz Has this problem been solved?

**Comment by yamonkjd** [comment]
I hope this feature gets fixed soon. I've looked at the code, but I don't have the knowledge to make any modifications.
