### ISSUE TITLE
Error while trying to load custom component

### ISSUE THREAD

**Issue by DepressedSage** [langflow-ai/langflow#1127]
Hi, I'm experiencing the similar issue as [#1091](https://github.com/logspace-ai/langflow/issues/1091)

I followed the [tutorial/example](https://docs.langflow.org/guidelines/custom-component)

```export LANGFLOW_COMPONENTS_PATH='["/path/to/components"]'```

This line ran without any errors but when using the UI there were no custom components available.

And when using the alternative 

```langflow --components-path /path/to/components```
or 
```langflow run --components-path /path/to/components```

It returns with an error

```No such option: --components-path```

**Comment by fenss** [comment]
Same problem, it's really confused, hard to deploy, many wired problems....

**Comment by bifterciabata** [comment]
Is there any update on this?

**Comment by anovazzi1** [comment]
Hello,
Sorry for the delay. Did you try using the new version? Does the error still persist?

**Comment by carlosrcoelho** [comment]
@DepressedSage Hello!
Did you try using the new version? Does the error still persist?

**Comment by carlosrcoelho** [comment]
Hi @DepressedSage,

We hope you're doing well. Just a friendly reminder that if we do not hear back from you within the next 3 days, we will close this issue. If you need more time or further assistance, please let us know.

Thank you for your understanding!

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
