### ISSUE TITLE
Error building node FAISS: FAISS.__init__() got an unexpected keyword argument 'documents'

### ISSUE THREAD

**Issue by zchengzhong** [langflow-ai/langflow#1158]
Error building node FAISS: FAISS.__init__() got an unexpected keyword argument 'documents'

![图片](https://github.com/logspace-ai/langflow/assets/2253700/11197d9b-034b-4a06-9e40-30c837df1528)

**Comment by ogabrielluiz** [comment]
This might be a bug. 

I'll look into it tomorrow. Thanks!

**Comment by sampratha28** [comment]
@ogabrielluiz still the issue persists. Can you please provide some update on it?

**Comment by anovazzi1** [comment]
Hello,
Sorry for the delay. Did you try using the new version? Does the error still persist?

**Comment by carlosrcoelho** [comment]
@zchengzhong Hi there!

Have you tried using the new version? Does the error still persist?

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
