### ISSUE TITLE
Trouble Connecting Custom LLM to Agent

### ISSUE THREAD

**Issue by Jone8293** [langflow-ai/langflow#1220]
I am currently working with Langflow and have come across a challenge. I understand that Langflow supports custom components, but I am facing difficulties in connecting a custom Large Language Model (LLM) agent or chain to utilize a custom component as an LLM. I am seeking guidance or suggestions on how this integration could be achieved.

Objective:

To connect a custom LLM component within Langflow.
To use this custom LLM component for processing within an agent or chain.
Current Behavior:
When attempting to set up or integrate the custom LLM component within the Langflow framework, I am unable to establish a functional connection between the LLM component and the agent/chain.

Steps Taken:

I have attempted to integrate this component with an agent or chain in Langflow.
Encountered issues in making the component recognized or utilized as an LLM.

**Comment by ogabrielluiz** [comment]
@dosu-bot Hey, @Jone8293.


I've created the following component and was able to connect it to a ConversationChain. 
Is this what you are trying to achieve?

```python
from langflow import CustomComponent
from langflow.field_typing import BaseLanguageModel
from langchain.chat_models import ChatOpenAI

class Component(CustomComponent):

    def build_config(self):
        return {"param": {"display_name": "Parameter"}}

    def build(self) -> BaseLanguageModel:
        return ChatOpenAI()
```

**Comment by Jone8293** [comment]
@ogabrielluiz 

Thanks, i thnk so, i am trying to yse a custom model from Azure or Azure ai studio?
