### ISSUE TITLE
Community examples tab missing

### ISSUE THREAD

**Issue by davide445** [langflow-ai/langflow#1240]
**Describe the bug**
Installed 6.1 release and I got only the store, with way less flows than the community tab. Where is possible to get back also the community flows.

**Browser and Version**
 - Firefox
 - latest

**To Reproduce**
1. Upgrade from 5.12 to 6.1
2. See the home page, community tab is missing

**Comment by davidezari** [comment]
This is a screenshot of langflow 5.12 where there is still a tab with the community examples, was asking how to get it back
![image](https://github.com/logspace-ai/langflow/assets/128394413/4247d532-9680-423a-81c1-3b6b215b1e2a)

**Comment by davide445** [comment]
This is a screenshot of Langflow 0.5.12 where the Community examples tab is still available, was asking how to get it back in release > 6.1
![image](https://github.com/logspace-ai/langflow/assets/33984290/bf9a601d-8929-4caa-88f4-cf4f6cf3c0d2)

**Comment by davide445** [comment]
I have updated to latest release and there is still no community tab
Due the lack of useful examples that was available in the old Community tab, I have finally switched to flowise, that provide me what I need

**Comment by ogabrielluiz** [comment]
Hey @davide445 I'm sorry to read that.

We've been working really hard to put out the best replacement for the Community Tab and to make Langflow even better for you all. 

Have you got access to the Langflow Store? If you ping me your e-mail on discord I can get you off the waitlist. 

Also, what examples would you like to see? I'll build them in our next release for you.

**Comment by davide445** [comment]
@ogabrielluiz yes I have had access to the store, and there was the beginning of my disappointment due I didnt found anything useful on the contrary of the old community solution.
On flowise I was able on a couple of hours to create a RAG + prompt chat with memory using Anthropic Claude 3 LLM
Not telling this due I'm an evangelist or so - Im just a manager searching for a no code tool to prototype, showcase and eventually deliver innovative solutions, and will actually prefer Python than Node environment - but that worked.

**Comment by vertgo** [comment]
What happened to the community examples? Are they not in the store? ( still do not have access to the store, so I can only hope).  Does someone have a place to access these outside of langflow?

**Comment by ogabrielluiz** [comment]
Hey @davide445  and @vertgo 

Would you two mind trying out Langflow 1.0 alpha to tell us what you think about it? 

https://huggingface.co/spaces/Logspace/Langflow-Preview?duplicate=true

People seem to like it in our discord server. Here's the link if you all want to join: https://discord.gg/EqksyE2EX9

We have an alpha-feedback channel there too.

**Comment by vertgo** [comment]
Is there a build that I can pull?

**Comment by vertgo** [comment]
> Hey @davide445  and @vertgo 
> 
> Would you two mind trying out Langflow 1.0 alpha to tell us what you think about it? We are trying to remedy the lack of Community Examples in that version.
> 
> https://huggingface.co/spaces/Logspace/Langflow-Preview?duplicate=true
> 
> People seem to like it in our discord server. Here's the link if you all want to join: https://discord.gg/EqksyE2EX9
> 
> We have an alpha-feedback channel there too.

I tried it, and it still only has a store and no community tab. I haven't been able to get and API key for the store. Why lock away the previous community stuff?

**Comment by davide445** [comment]
Just want to point out my remark it's not about I need a thing called "community tab", just need useful nodes and examples, to prototype and deliver fast.

So far I'm working well with flowise and haven't had the time returning back to langflow, and tbh I'm starting to get annoyed with Python endless venv configuration problems.

Node.js is probably an inefficient mess, but so far is hiding a lot of work to get things done.

Just hope next time I will look at langflow will be straightforward like flowise/npx
