### ISSUE TITLE
The components panel is empty

### ISSUE THREAD

**Issue by khibinite** [langflow-ai/langflow#1245]
**Describe the bug**
Just installed the LangFlow onto my Windows 10 PC. Have got the empty components left sidebar. Emty work area even if I choose some preinstalled flows

**Browser and Version**
 - Browser Google Chrome
 - Version 120.0.6099.129

**To Reproduce**
I am not sure that it's possible to reproduce, looks like my local problem.

1. Go to the cmd
2. Typed "langflow run"
3. Got the instruction to open LF by the address http://127.0.0.1:7860 and opened it
4. The main page was loaded
5. Clicked New project
6. Have got the empty components sidebar and the workplace

**Screenshots**
![Screenshot_231](https://github.com/logspace-ai/langflow/assets/142720814/b6a08a39-a340-4a54-af6e-1eb071308c91)
![Screenshot_230](https://github.com/logspace-ai/langflow/assets/142720814/c9876ff1-d72d-44c8-a116-8b3974339a89)
![Screenshot_229](https://github.com/logspace-ai/langflow/assets/142720814/2151b6bb-ddb5-4928-b367-1420783f93b4)

**Comment by khibinite** [comment]
@dosu-bot

Thank you, this gave me a direction. But I have noticed that there is no API Key icon in my LF UI
![Screenshot_232](https://github.com/logspace-ai/langflow/assets/142720814/d78a7720-3e64-468b-9ad1-4c7a5bddadd8)

Looks like a problem. Is it possible to generate API key manually via CLI?

**Comment by khibinite** [comment]
This way doesn't allow to create a key using some special command - not run some code (I suppose it's Node.js?).

Nevertheless, there is not only API key issue but the profile section also.

**Comment by khibinite** [comment]
@dosu-bot is there any Python version requirement? I use 3.9. Should I update it to 3.12 to make the LF working properly?

**Comment by imfht** [comment]
I got the same issue, no components show in left sidebar, can I use langflow without a api key?

**Comment by imfht** [comment]
> I got the same issue, no components show in left sidebar, can I use langflow without a api key?

I downgrade  langflow to 0.6.2  and langchain to 0.0.345 then works well.
```
pip install langchain==0.0.345 langflow==0.6.2
```

**Comment by khibinite** [comment]
> > I got the same issue, no components show in left sidebar, can I use langflow without a api key?
> 
> I downgrade langflow to 0.6.2 and langchain to 0.0.345 then works well.
> 
> ```
> pip install langchain==0.0.345 langflow==0.6.2
> ```

Thank yo uvery much. Will try and report

**Comment by imfht** [comment]
@khibinite I'm not sure if it is affected by network issue. I've installed latest langflow on another windows10 pc. it works well.

My macbook can not access to internet, and i cann't see compents panel until i downgrade langflow to 0.6.2. after the downlgrade, the component panel still missing some components such as LLMChain.

**Comment by imfht** [comment]
> @khibinite I'm not sure if it is affected by network issue. I've installed latest langflow on another windows10 pc. it works well.
> 
> My macbook can not access to internet, and i cann't see compents panel until i downgrade langflow to 0.6.2. after the downlgrade, the component panel still missing some components such as LLMChain.

I believe it's caused by wrong python version. I downgrade python to python 3.10 and it works  very well.

**Comment by MiyazonoKaori** [comment]
same error, python3.10, downgrade langflow and langchain not work
![fg_17037600391569](https://github.com/logspace-ai/langflow/assets/15343318/35aff2cb-d696-4483-a44a-634cda94203e)

**Comment by Rupin817** [comment]
same problem here

**Comment by zagaria** [comment]
Had the same issue for 0.6.3 and 0.6.4

After a brief investigation, I found that the issue is related to ChromaDB component. The LangFlow UI API request for components failed due to an issue stating, 'Chroma requires SQLite > 3.35. If you encounter issues due to having a version of SQLite that is too low, please try the following.' 

Updating SQLite in system resolved the issue in my case.

**Comment by xmduhan** [comment]
@zagaria 
Exactly as you said, the problem was resolved after I upgraded SQLite. Thank you!

**Comment by khibinite** [comment]
> @zagaria Exactly as you said, the problem was resolved after I upgraded SQLite. Thank you!

@xmduhan how did you do that? I mean the SQLite upgrade

**Comment by Rupin817** [comment]
@zagaria and @xmduhan do you guys have problems when click into pre-defined flow, it is all empty but with components?
![2024-01-07 at 13 12](https://github.com/logspace-ai/langflow/assets/24668838/bd111252-7103-4616-bb52-49475dc724f5)

**Comment by xmduhan** [comment]
@Rupin817 
Yes, I tried everything I can do with. Only upgrade sqlite worked!

**Comment by xmduhan** [comment]
@khibinite 
download sqlite source from: https://www.sqlite.org/download.html
compile it and set PATH for new sqlite.

**Comment by anandpratapsingh25** [comment]
Yesterday i tried installing langflow with latest version i am also getting the same, I tried with lower version and Sqlite upgrade but didnt workout for me.
An alternative i tried is "Flowise" but i think available agents have limited capability.
Let me know what worked
Thanks in Advance

**Comment by Rupin817** [comment]
> @Rupin817 Yes, I tried everything I can do with. Only upgrade sqlite worked!

@xmduhan just to double confirm the components are back for you, but you also cannot see those pre-defined flow example when clicked in? So it is expected?

**Comment by khibinite** [comment]
> @khibinite download sqlite source from: https://www.sqlite.org/download.html compile it and set PATH for new sqlite.

@xmduhan thank you very much, will try

**Comment by khibinite** [comment]
> @khibinite Did you find a solution? I tried everything mentioned in this thread but nothing worked for me...I still can't see any component or flow.

Hi,
still no because the last one is not so trivial for me. If I were find some cloud LF service this would be a best solution.

**Comment by humble92** [comment]
System's Sqlite3 were upgraded to 3.44.2, but it still doesn't work for me. Langflow version is 0.6.4, the latest.

**Comment by mariuszkumor** [comment]
On my macOS Monterey 12.7.1,  Chrome Version 119.0.6045.199 (Official Build) (x86_64), python 3.10.13, langflow 0.6.4 I'm getting no toolbar. The view is like in the attached screenshot. Using Safari the same problem. Do you have any ideas, what can be wrong? Maybe it is related/the same issue as described above?
<img width="2560" alt="Screenshot 2024-01-14 at 11 45 09" src="https://github.com/logspace-ai/langflow/assets/10467382/15632529-97fa-4c28-94c5-d871458be924">

**Comment by jiarko** [comment]
@humble92 @khibinite @LauC07 I've solved the issue, take a look at my post https://github.com/logspace-ai/langflow/issues/1350#issuecomment-1896075120

hope this helps
ciao

**Comment by LauC07** [comment]
> @humble92 @khibinite @LauC07 I've solved the issue, take a look at my post [#1350 (comment)](https://github.com/logspace-ai/langflow/issues/1350#issuecomment-1896075120)
> 
> hope this helps ciao

Thank you very much! Your solution worked for me. I just have to add that in my case I also had to update the langchain-experimental package to make it work properly.
