### ISSUE TITLE
Integrate Criteria Evaluation with langflow

### ISSUE THREAD

**Issue by sampratha28** [langflow-ai/langflow#1281]
I want to make use of criteria evaluation in langflow to verify if the model's response is grounded to the vector store or not.
I see that there is already code available in the langchain repository. How to enable it?

I am using a Vector Store agent and also, note that i am creating a custom LLM component

**Comment by ogabrielluiz** [comment]
Hi @sampratha28 

How do you see that being implemented to make it useful? Could you share more details?

**Comment by sampratha28** [comment]
hey @ogabrielluiz 
this feature can be used to check how grounded the model's response is with respect to the given knowledge base. This can help in improving model response quality.
Please correct me if i am wrong, also feel free to give your suggestions for the same
