### ISSUE TITLE
Milvus Custom Component Issue.

### ISSUE THREAD

**Issue by bhaks12** [langflow-ai/langflow#1282]
We are trying to create the custom component to support the Milvus DB. Getting the below error while trying to run the component. I Installed celery and pymilvus packages.

**Error:** RPC error: [create_collection], <MilvusException: (code=1, message=field name should not be empty)>, <Time:{'RPC start': '2024-01-03 16:58:53.948301', 'RPC error': '2024-01-03 16:58:53.956297'}>
Failed to create collection: langflow_test error: <MilvusException: (code=1, message=field name should not be empty)>

**Code:** 
from langchain.document_loaders import TextLoader
from langchain.embeddings.openai import OpenAIEmbeddings
from langchain.text_splitter import CharacterTextSplitter
from langchain.vectorstores import Milvus
from langflow import CustomComponent
from langchain.schema import Document
from langchain.embeddings.base import Embeddings
import os
 
class MilvusCustComp(CustomComponent):
    display_name: str = "Milvus"
    description: str = "Milvus CustomComponent"
 
    def build_config(self):
        return { }
 
    def build(
        self,
        input_document: Document,
        embedding: Embeddings = None,
        milvus_host: str,
        milvus_port: int,
        milvus_collection: str,
        query: str,
        ) -> Document:
        
        os.environ["OPENAI_API_TYPE"] = embedding.openai_api_type
        os.environ["OPENAI_API_KEY"] = embedding.openai_api_key
        os.environ["OPENAI_API_BASE"] = embedding.openai_api_base
        os.environ["OPENAI_API_VERSION"] = embedding.openai_api_version
        
        embeddings = OpenAIEmbeddings()
        vector_db = Milvus.from_documents(
            input_document,
            embedding,
            connection_args={"host": milvus_host, "port": milvus_port, "db_name":"langflow"},
            # db_name="langflow",
            collection_name=milvus_collection
        )
        docs = vector_db.similarity_search(query)
        result = docs[0].page_content
        # Return the result as a Document
        return Document(page_content=str(result), milvus_ids=ids)
        
     **Reference:** 
     https://python.langchain.com/docs/integrations/vectorstores/milvus
     
     **Flow:**
    
![image](https://github.com/logspace-ai/langflow/assets/151496529/9aff0f68-c05e-4c04-9f4e-aa220b745c72)

**Comment by ogabrielluiz** [comment]
Hey @bhaks12 

The error suggests that the filed `name` is empty. Have you checked that?

**Comment by bhaks12** [comment]
> Hey @bhaks12
> 
> The error suggests that the filed `name` is empty. Have you checked that?

Where should I pass the filed name? 
Will the collection get created under the default database? If yes how we can configure the other database?

**Comment by bhaks12** [comment]
> _🤖_
> 
> Hello @bhaks12!
> 
> I'm [Dosu](https://dosu.dev), a friendly bot here to assist you while we wait for a human maintainer to join. I'm equipped to help you troubleshoot bugs, answer your questions, and guide you on your journey as a contributor. Let's get started!
> 
> Based on the error message you provided, it seems like the issue is related to the creation of a collection in Milvus. The error message "field name should not be empty" suggests that a field name is not being provided when trying to create a collection.
> 
> In your code, the collection is created in the `Milvus.from_documents` method. However, the error message suggests that the collection is not being created correctly. It's possible that the `input_document` or `embedding` parameters are not providing the necessary information to create the collection.
> 
> Here are a few things you can check:
> 
> 1. Ensure that the `input_document` parameter is a `Document` object and that it contains the necessary information to create a collection in Milvus.
> 2. Check that the `embedding` parameter is an `Embeddings` object and that it is correctly configured. The `Embeddings` object should contain the necessary information to create a collection in Milvus.
> 3. Verify that the `milvus_collection` parameter is a non-empty string. This parameter is used as the name of the collection in Milvus.
> 4. Check the connection to the Milvus server. The `connection_args` parameter should contain the correct host and port for the Milvus server.
> 
> If you've checked all of these and the issue persists, it would be helpful to have more information about the `input_document` and `embedding` parameters. Could you provide more details about these parameters? For example, what is the content of the `input_document` and how is the `embedding` object configured?
> 
> For more information about how to use the `Milvus.from_documents` method, you can refer to the [langchain documentation](https://python.langchain.com/docs/integrations/vectorstores/milvus).
> 
> I hope this helps! If you have any other questions, feel free to ask.
> 
> Best, [Dosu](https://dosu.dev)
> 
> ## Sources
> * [src/backend/langflow/interface/custom/utils.py](https://github.com/logspace-ai/langflow/blob/dev/src/backend/langflow/interface/custom/utils.py)
> * [src/backend/langflow/components/utilities/JSONDocumentBuilder.py](https://github.com/logspace-ai/langflow/blob/dev/src/backend/langflow/components/utilities/JSONDocumentBuilder.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

input_document contains the text data from the text file provided.
embeddings contains the configurations passed from the OpenAIEmbedding component. Please refer below for your reference.
client=<class 'openai.api_resources.embedding.Embedding'> model='value' deployment='value' openai_api_version='value' openai_api_base='value' openai_api_type='value' openai_proxy='' embedding_ctx_length=8191 openai_api_key='value' openai_organization='' allowed_special=set() disallowed_special='all' chunk_size=1000 max_retries=10 request_timeout=None headers=None tiktoken_model_name=None show_progress_bar=False model_kwargs={'deployment_id': 'value'} skip_empty=False

**Note:** Replaced the correct configurations with the word value in the above.

**Comment by bhaks12** [comment]
@ogabrielluiz, @dosu-bot,

I have this below working code. When I ran from the Pycharm, collection is newly creating If it is not available and insert the data.

from langchain.document_loaders import TextLoader
from langchain.text_splitter import CharacterTextSplitter
from langchain.vectorstores import Milvus
from langchain.embeddings.azure_openai import AzureOpenAIEmbeddings

embeddings = AzureOpenAIEmbeddings(deployment='embedding',
                                   openai_api_base="",
                                   openai_api_type="",
                                   openai_api_key="",
                                   openai_api_version="")

print(f"embeddings: {embeddings}")
loader = TextLoader("file_path")
documents = loader.load()
text_splitter = CharacterTextSplitter(chunk_size=1000, chunk_overlap=0)
docs = text_splitter.split_documents(documents)

print(f"docs: {docs}")
vector_db = Milvus.from_documents(
    docs,
    embeddings,
    connection_args={"host": "127.0.0.1", "port": 19530, "db_name": "db_name"},
    collection_name="collection_name",
    search_params={
        "metric_type": "L2",
        "params": {"nprobe": 2},
    }
)
print(f"vector_db: {vector_db}")
query = "User_query"
response = vector_db.similarity_search(query)
print(response[0])

Below is the Code I added in the custom component of the langflow component and it is not working properly. If the collection is available it is working fine else it is throwing the above error field name is not available. In the above working code also I am not giving any field name or the schema to create the collection. Can you please help me what is missing here.

from langchain.vectorstores import Milvus
from langflow import CustomComponent
from langchain.schema import Document
from langchain.embeddings.base import Embeddings
from loguru import logger
from langchain_community.embeddings.azure_openai import AzureOpenAIEmbeddings
 
class MilvusCustomComponent(CustomComponent):
    display_name: str = "Milvus"
    description: str = "Milvus CustomComponent"
 
    def build_config(self):
        return { }
 
    def build(
        self,
        input_document: Document,
        embedding: Embeddings = None,
        milvus_host: str=None,
        milvus_port: int=None,
        milvus_db: str=None,
        milvus_collection: str=None,
        metric_type: str="L2",
        nprobe: int=2,
        query: str=None,
        ) -> Document:

        embeddings = AzureOpenAIEmbeddings(deployment=embedding.deployment,
                                           openai_api_base=embedding.openai_api_base,
                                           openai_api_type=embedding.openai_api_type,
                                           openai_api_key=embedding.openai_api_key,
                                           openai_api_version=embedding.openai_api_version)
        vector_db = Milvus.from_documents(
            input_document,
            embeddings,
            connection_args={"host": milvus_host, "port": milvus_port, "db_name": milvus_db},
            collection_name=milvus_collection, 
            search_params={
                "metric_type": metric_type,
                "params": {"nprobe": nprobe},
            } 
        )
        docs = vector_db.similarity_search(query)
        result = docs[0]
        logger.info(f"Result: {result.page_content}")
        return Document(page_content=str(result.page_content))
        
        Please find the below flow for your reference:
        
![image](https://github.com/logspace-ai/langflow/assets/151496529/f20277c7-a6b7-497a-9643-19df52e71416)
