### ISSUE TITLE
AzureChatOpenAI LLM Component 

### ISSUE THREAD

**Issue by lucifertrj** [langflow-ai/langflow#1284]
**Describe the bug**
I tried using AzureChatOpenAI in one of my use cases and I got the error while running the flow. Thanks to the custom code, I renamed azure_endpoint to openai_base_url and it worked. Also the API version varies, thus it needs to be defined as str and should be entered by user once they get their Azure creds. I have raised PR for same #1283

**Comment by yassineselmi** [comment]
@lucifertrj can you paste the error that you had with the `azure_endpoint` instead of `openai_base_url` ?
And what  version `langchain` and `openai` version you are running?
