### ISSUE TITLE
When use redis Cache , can't pickle RetrievalQA component

### ISSUE THREAD

**Issue by Gnavy** [langflow-ai/langflow#1289]
When use redis Cache,can't pickle RetrievalQA component.

so in this cause, we cant use the RetrievalQA,when we want use redis cache.

does anyone have idea?

<img width="525" alt="image" src="https://github.com/logspace-ai/langflow/assets/21094902/d9f63568-cb00-4296-ace5-0b2341247667">

**Comment by Gnavy** [comment]
<img width="527" alt="image" src="https://github.com/logspace-ai/langflow/assets/21094902/23bde501-0519-450c-9502-6c684bef5e8d">
seems like this is a queue in the RetrievalQA Obj

**Comment by gourab-sinha** [comment]
@Gnavy there is a lock in the object because of which it is not able to pickle.
