### ISSUE TITLE
Question: Is it safe to save python code in an exported .json file?

### ISSUE THREAD

**Issue by JinXJinX** [langflow-ai/langflow#1305]
I saw the eval_function() in the validate.py . It used the buildtin exec() function with an empty global namespace.
If I get a flows.json file from someone. How can I ensure that file doesn't contain malicious Python code or not?

**Comment by JinXJinX** [comment]
in #775 , @ogabrielluiz mentioned that "_We are working on ways to try to mitigate this_". Any updates? Thanks

**Comment by anovazzi1** [comment]
Hello,
Sorry for the delay. You can now inspect all the code inside each component, allowing you to read and verify everything that will run inside your machine.

**Comment by carlosrcoelho** [comment]
Hi @JinXJinX , 

We hope you're doing well. Just a friendly reminder that if we do not hear back from you within the next 3 days, we will close this issue. If you need more time or further assistance, please let us know. 

Thank you for your understanding!

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
