### ISSUE TITLE
How to use Sequential Chains in LangFlow

### ISSUE THREAD

**Issue by surendransuri** [langflow-ai/langflow#1308]
How to use Sequential Chains in LangFlow

**Comment by victorpicaud** [comment]
[Chain Sequential COMBINATOR.json](https://github.com/logspace-ai/langflow/files/13873779/Chain.Sequential.COMBINATOR.json)
here is a custom component that does that but it needs a bit of imporvement (orders params)

**Comment by rashid-globallogic** [comment]
let suppose I have four component chatInput-->Prompts--->AzureOpenAI--->Chatoutput. I have import all component individually in Json file. In vs code i have load like this run_flow_from_json(flow="simple_new.json", input_value=query.question). 
how can I perform chaining on it
