### ISSUE TITLE
Serialization error for Document

### ISSUE THREAD

**Issue by sampratha28** [langflow-ai/langflow#1313]
i am using RetrievalQA chain with a vector store.

The error i am getting is:-

[2024-01-09 16:53:12 +0000] [2629637] [ERROR] Exception in ASGI application
  + Exception Group Traceback (most recent call last):
  |   File "/home/azureuser/langflow_rag/lib/python3.10/site-packages/starlette/_utils.py", line 82, in collapse_excgroups
  |     yield
  |   File "/home/azureuser/langflow_rag/lib/python3.10/site-packages/starlette/middleware/base.py", line 190, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "/home/azureuser/langflow_rag/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 678, in __aexit__
  |     raise BaseExceptionGroup(
  | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/home/azureuser/langflow_rag/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    |     result = await app(  # type: ignore[func-returns-value]
    |   File "/home/azureuser/langflow_rag/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    |     return await self.app(scope, receive, send)
    |   File "/home/azureuser/langflow_rag/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    |     await super().__call__(scope, receive, send)
    |   File "/home/azureuser/langflow_rag/lib/python3.10/site-packages/starlette/applications.py", line 116, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/home/azureuser/langflow_rag/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    |     raise exc
    |   File "/home/azureuser/langflow_rag/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    |     await self.app(scope, receive, _send)
    |   File "/home/azureuser/langflow_rag/lib/python3.10/site-packages/starlette/middleware/base.py", line 189, in __call__
    |     with collapse_excgroups():
    |   File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    |     self.gen.throw(typ, value, traceback)
    |   File "/home/azureuser/langflow_rag/lib/python3.10/site-packages/starlette/_utils.py", line 88, in collapse_excgroups
    |     raise exc
    |   File "/home/azureuser/langflow_rag/lib/python3.10/site-packages/starlette/middleware/base.py", line 191, in __call__
    |     response = await self.dispatch_func(request, call_next)
    |   File "/home/azureuser/langflow_rag/lib/python3.10/site-packages/langflow/main.py", line 50, in flatten_query_string_lists
    |     return await call_next(request)
    |   File "/home/azureuser/langflow_rag/lib/python3.10/site-packages/starlette/middleware/base.py", line 165, in call_next
    |     raise app_exc
    |   File "/home/azureuser/langflow_rag/lib/python3.10/site-packages/starlette/middleware/base.py", line 151, in coro
    |     await self.app(scope, receive_or_disconnect, send_no_error)
    |   File "/home/azureuser/langflow_rag/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
    |     await self.app(scope, receive, send)
    |   File "/home/azureuser/langflow_rag/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
    |   File "/home/azureuser/langflow_rag/lib/python3.10/site-packages/starlette/_exception_handler.py", line 55, in wrapped_app
    |     raise exc
    |   File "/home/azureuser/langflow_rag/lib/python3.10/site-packages/starlette/_exception_handler.py", line 44, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "/home/azureuser/langflow_rag/lib/python3.10/site-packages/starlette/routing.py", line 746, in __call__
    |     await route.handle(scope, receive, send)
    |   File "/home/azureuser/langflow_rag/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    |     await self.app(scope, receive, send)
    |   File "/home/azureuser/langflow_rag/lib/python3.10/site-packages/starlette/routing.py", line 75, in app
    |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
    |   File "/home/azureuser/langflow_rag/lib/python3.10/site-packages/starlette/_exception_handler.py", line 55, in wrapped_app
    |     raise exc
    |   File "/home/azureuser/langflow_rag/lib/python3.10/site-packages/starlette/_exception_handler.py", line 44, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "/home/azureuser/langflow_rag/lib/python3.10/site-packages/starlette/routing.py", line 70, in app
    |     response = await func(request)
    |   File "/home/azureuser/langflow_rag/lib/python3.10/site-packages/fastapi/routing.py", line 315, in app
    |     content = await serialize_response(
    |   File "/home/azureuser/langflow_rag/lib/python3.10/site-packages/fastapi/routing.py", line 160, in serialize_response
    |     return field.serialize(
    |   File "/home/azureuser/langflow_rag/lib/python3.10/site-packages/fastapi/_compat.py", line 147, in serialize
    |     return self._type_adapter.dump_python(
    |   File "/home/azureuser/langflow_rag/lib/python3.10/site-packages/pydantic/type_adapter.py", line 314, in dump_python
    |     return self.serializer.to_python(
    | pydantic_core._pydantic_core.PydanticSerializationError: Unable to serialize unknown type: <class 'langchain_core.documents.base.Document'>
    +------------------------------------

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/azureuser/langflow_rag/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/azureuser/langflow_rag/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/home/azureuser/langflow_rag/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/azureuser/langflow_rag/lib/python3.10/site-packages/starlette/applications.py", line 116, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/azureuser/langflow_rag/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/home/azureuser/langflow_rag/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/home/azureuser/langflow_rag/lib/python3.10/site-packages/starlette/middleware/base.py", line 189, in __call__
    with collapse_excgroups():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/azureuser/langflow_rag/lib/python3.10/site-packages/starlette/_utils.py", line 88, in collapse_excgroups
    raise exc
  File "/home/azureuser/langflow_rag/lib/python3.10/site-packages/starlette/middleware/base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/home/azureuser/langflow_rag/lib/python3.10/site-packages/langflow/main.py", line 50, in flatten_query_string_lists
    return await call_next(request)
  File "/home/azureuser/langflow_rag/lib/python3.10/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/home/azureuser/langflow_rag/lib/python3.10/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/home/azureuser/langflow_rag/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/home/azureuser/langflow_rag/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/azureuser/langflow_rag/lib/python3.10/site-packages/starlette/_exception_handler.py", line 55, in wrapped_app
    raise exc
  File "/home/azureuser/langflow_rag/lib/python3.10/site-packages/starlette/_exception_handler.py", line 44, in wrapped_app
    await app(scope, receive, sender)
  File "/home/azureuser/langflow_rag/lib/python3.10/site-packages/starlette/routing.py", line 746, in __call__
    await route.handle(scope, receive, send)
  File "/home/azureuser/langflow_rag/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/azureuser/langflow_rag/lib/python3.10/site-packages/starlette/routing.py", line 75, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/azureuser/langflow_rag/lib/python3.10/site-packages/starlette/_exception_handler.py", line 55, in wrapped_app
    raise exc
  File "/home/azureuser/langflow_rag/lib/python3.10/site-packages/starlette/_exception_handler.py", line 44, in wrapped_app
    await app(scope, receive, sender)
  File "/home/azureuser/langflow_rag/lib/python3.10/site-packages/starlette/routing.py", line 70, in app
    response = await func(request)
  File "/home/azureuser/langflow_rag/lib/python3.10/site-packages/fastapi/routing.py", line 315, in app
    content = await serialize_response(
  File "/home/azureuser/langflow_rag/lib/python3.10/site-packages/fastapi/routing.py", line 160, in serialize_response
    return field.serialize(
  File "/home/azureuser/langflow_rag/lib/python3.10/site-packages/fastapi/_compat.py", line 147, in serialize
    return self._type_adapter.dump_python(
  File "/home/azureuser/langflow_rag/lib/python3.10/site-packages/pydantic/type_adapter.py", line 314, in dump_python
    return self.serializer.to_python(
pydantic_core._pydantic_core.PydanticSerializationError: Unable to serialize unknown type: <class 'langchain_core.documents.base.Document'>

**Comment by sampratha28** [comment]
@dosu-bot. I am using multiquery retreiver along with retrievalqa chain. I am getting response from the chain but immediately encountering the above error in langflow

**Comment by sampratha28** [comment]
@dosu-bot.
below is the code for Document class. it indicates that it is serializable.

from __future__ import annotations

from typing import List, Literal

from langchain_core.load.serializable import Serializable
from langchain_core.pydantic_v1 import Field


class Document(Serializable):
    """Class for storing a piece of text and associated metadata."""

    page_content: str
    """String text."""
    metadata: dict = Field(default_factory=dict)
    """Arbitrary metadata about the page content (e.g., source, relationships to other
        documents, etc.).
    """
    type: Literal["Document"] = "Document"

    @classmethod
    def is_lc_serializable(cls) -> bool:
        """Return whether this class is serializable."""
        return True

    @classmethod
    def get_lc_namespace(cls) -> List[str]:
        """Get the namespace of the langchain object."""
        return ["langchain", "schema", "document"]

**Comment by Genuifx** [comment]
Get the same error, any pattern to workaround?

**Comment by songjinu** [comment]
I have same error like this.
```
pydantic_core._pydantic_core.PydanticSerializationError: Unable to serialize unknown type: <class 'langchain_core.documents.base.Document'>
```

**Comment by flyuuo9** [comment]
请问大家如何解决？

**Comment by ooooona** [comment]
Hi, I met the same issue when enable `return_source_documents` of `RetrievalQA`. After debugging with langflow, I found it's because enabling `return_source_documents` of `RetrievalQA` will return back `Document` (https://github.com/langchain-ai/langchain/blob/acaf214a4516a2ffbd2817f553f4d48e6a908695/libs/langchain/langchain/chains/retrieval_qa/base.py#L149-L152):

>         if self.return_source_documents:
            return {self.output_key: answer, "source_documents": docs}
        else:
            return {self.output_key: answer}

Hence, I suggest to disable `return_source_documents` of `RetrievalQA` in langflow, or special handling with  serialization of `Document` if the responses have.

**Comment by anovazzi1** [comment]
Hello,
Sorry for the delay. Did you try using the new version? Does the error still persist?

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.

**Comment by shayneoneill** [comment]
Did anyone ever manage to solve this? If not solved, maybe the sample templates need to be marked as non-functional? Cos I'm literally just putting a text file into the RAG demo and getting this. (Tested with both ChromaDB and PGVector)
