### ISSUE TITLE
Langflow UI not coming up

### ISSUE THREAD

**Issue by sampratha28** [langflow-ai/langflow#1318]
langflow UI is stuck in loading and not coming up.

tried in both chrome and firefox

**Comment by icekeg** [comment]
me too

**Comment by ruan-xb-63** [comment]
me too

**Comment by ruan-xb-63** [comment]
me too
I tried Google Chrome and Microsoft edge
![image](https://github.com/logspace-ai/langflow/assets/68852853/1a805eba-ee79-4ddc-b81e-d44af4f5094f)

**Comment by flefevre** [comment]
I have switched to version 0.6.7 and still the error with docker-compose

`FROM python:3.11-slim

RUN apt-get update && apt-get install gcc g++ git make -y && apt-get clean \
	&& rm -rf /var/lib/apt/lists/*
RUN useradd -m -u 1000 user

# Create the directory and set the permissions
RUN mkdir -p /home/langflow && chown user:user /home/langflow
USER user
ENV HOME=/home/user \
	PATH=/home/user/.local/bin:$PATH

WORKDIR $HOME/app

COPY --chown=user . $HOME/app

RUN pip install langflow>==0.6.7 -U --user

CMD ["python", "-m", "langflow", "run", "--host", "0.0.0.0", "--port", "7862", "--log-level","debug"]
`

any idea how to solve it directly in the docker image?

**Comment by anovazzi1** [comment]
I recommend trying Python 3.10. Additionally, you can find some solutions to this problem on our Discord channel:
https://discord.com/channels/1116803230643527710/1129415917445586974
