### ISSUE TITLE
How to add `search_kwargs` when using CustomComponent to create a vectorstore

### ISSUE THREAD

**Issue by wodadehencou** [langflow-ai/langflow#1323]
I want to add a custom vectorstore, like in `src/backend/langflow/components/vectorstores/Chroma.py` did.

build method return type is `Union[VectorStore, BaseRetriever]`, but the actual code is return a Chroma instance.

```python
return Chroma(persist_directory=persist_directory, client_settings=chroma_settings)
``` 

If the next component need a *Retrieval*, `.as_retrieval()` function is auto called when building the graph.

If I want to control the retrieval policy, like k or score, I need to add a `search_kwargs` parameter to `as_retrieval`. 

I want to config k or score parameter to my custom vectorstore, but I find it difficult to do it.

**Comment by wodadehencou** [comment]
[VectaraSelfQueryRetriver.py](https://github.com/logspace-ai/langflow/blob/dev/src/backend/langflow/components/retrievers/VectaraSelfQueryRetriver.py) is something like a converter to convert an exist VectorStore to Retrieval, it is like the earlier Langflow version did, every vectorstore has a corresponding
retrieval component.

But today, I think almost every vectorstore component can act as a `VectorStore` or `BaseRetriever`. And I want to control the policy of BaseRetrieval, but I can not pass search_kwargs to a component which actually a VectorStore instance.

**Comment by carlosrcoelho** [comment]
Hi @wodadehencou  , 

We hope you're doing well. Just a friendly reminder that if we do not hear back from you within the next 3 days, we will close this issue. If you need more time or further assistance, please let us know. 

Thank you for your understanding!

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
