### ISSUE TITLE
LLMChain build error：RedisCache only accepts values that can be pickled.

### ISSUE THREAD

**Issue by lsg328** [langflow-ai/langflow#1324]
**Describe the bug**
 Using ChatOpenAi/OpenAi to create LLMChain, an error occurs when compiling:
RedisCache only accepts values that can be pickled.
TypeError("cannot pickle '_thread.RLock' object")

**Version**
0.6.4

**Screenshots**
![image](https://github.com/logspace-ai/langflow/assets/24787621/94b99374-eb88-4fc2-a674-d080e2c28c86)

**Log**
[log.txt](https://github.com/logspace-ai/langflow/files/13903537/log.txt)

**Comment by lsg328** [comment]
I located the langchain_community.chat_models.openai.ChatOpenAI class and reported an error when pickled. This error does not occur in 0.5.12.
![image](https://github.com/logspace-ai/langflow/assets/24787621/35648caa-1a3c-4471-91d2-9b836ca0253c)

**Comment by ogabrielluiz** [comment]
Hey @lsg328 

Yeah.. this is a problem we encountered after on openai's package after 1.0 because there's a thread lock object that blocks the dump. This is definitely fixable but requires quite a bit of testing.

We need to implement how the Vertex object serializes.

**Comment by lsg328** [comment]
@ogabrielluiz Thank you for your reply, looking forward to your good news

**Comment by yamonkjd** [comment]
We are also facing the same issue. We kindly ask for your assistance.

**Comment by nhha1602** [comment]
Hi,

Do we have any workaround solution to fix this issue ?

Thanks.

**Comment by iam-dev0** [comment]
I'm facing the same issue. Any workaround or should I downgrade to 0.5.12?

**Comment by iam-dev0** [comment]
A workaround that worked is setting `LANGFLOW_CACHE_TYPE=memory` so the backend won't use redis.

**Comment by carlosrcoelho** [comment]
Hi @lsg328 , 

We hope you're doing well. Just a friendly reminder that if we do not hear back from you within the next 3 days, we will close this issue. If you need more time or further assistance, please let us know. 

Thank you for your understanding!

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
