### ISSUE TITLE
Problems with Docker Compose not being able to find the backend

### ISSUE THREAD

**Issue by RielKIM** [langflow-ai/langflow#1327]
**Describe the bug**
When using Docker Compose to run services, there is often an issue where the frontend starts before the backend, leading to the frontend not being able to find the backend and thus preventing components from loading.

**Browser and Version**
 - Browser [e.g. chrome, safari] : edge
 - Version [e.g. 22] : 120

**To Reproduce**
1. docker-compose up (Occasionally occurring)

**Screenshots**
![image](https://github.com/logspace-ai/langflow/assets/7589452/31e24be9-8cc2-40b2-baaf-b95475b6de9c)

**Additional context**

**Comment by anovazzi1** [comment]
@RielKIM it's working now?

**Comment by RielKIM** [comment]
Yes, it's working.

2024년 3월 22일 (금) 오전 12:27, anovazzi1 ***@***.***>님이 작성:
