### ISSUE TITLE
not getting response from API for first query

### ISSUE THREAD

**Issue by sampratha28** [langflow-ai/langflow#1330]
When i hit the API predict endpoint, i am able to see the response in terminal, but the response in API is still buffering.
But when i send request to the API again, i am able to get response

**Comment by sampratha28** [comment]
@dosu-bot how can i resolve this issue so that the response is returned quickly for the first query itself

**Comment by anovazzi1** [comment]
hey, did it work? if not can you export the flow for debugging?
