### ISSUE TITLE
Getting Role Field missing error in ChatMessagePromptTemplate

### ISSUE THREAD

**Issue by udit050500** [langflow-ai/langflow#1351]
Unable to validate the ChatMessagePromptTemplate. Getting role field missing error. Looking forward for help or any pointer to resolve the issue.

**Describe the bug**
Getting following error while using ChatMessagePromptTemplate:
**_ValueError: Error building node ChatMessagePromptTemplate: 1 validation error for ChatMessagePromptTemplate
                   role field required (type=value_error.missing)_**

**Browser and Version**
 - Langflow Version 0.5.3

**To Reproduce**
1. Drag and Drop ChatMessagePromptTemplate, ChatPromptTemplate, LLMChain and AzureChatOpenAI
2. Connect ChatMessagePromptTemplate to ChatPromptTemplate, ChatPromptTemplate to LLMChain and AzureChatOpenAI to LLMChain
3. In ChatMessagePromptTemplate, we passed role as Jedi and PromptMessage, passed as "May the {subject} be with you".
4. On clicking of Validation button, validation failed with following message - **_Error building node ChatMessagePromptTemplate: 1 validation error for ChatMessagePromptTemplate
role
field required (type=value_error.missing)_**

**Screenshots**
<img width="948" alt="1" src="https://github.com/logspace-ai/langflow/assets/57041421/93defc0e-75f3-4a6e-8566-3ae27b328da6">
![image](https://github.com/logspace-ai/langflow/assets/57041421/1e90f1dd-f72a-4393-91f8-88c37ad7fc07)

**Comment by Cristhianzl** [comment]
Hello @chenhongsheng, I trust all is going smoothly.
Could you kindly revisit once your PR has been merged?

**Comment by chenhongsheng** [comment]
@Cristhianzl yes, it had been merged

**Comment by Cristhianzl** [comment]
Was the issue you were experiencing resolved, @chenhongsheng?
