### ISSUE TITLE
how long do I need to wait in the waitlist 

### ISSUE THREAD

**Issue by honemle** [langflow-ai/langflow#1359]
When I'd like to register and login, it just said: 
<img width="191" alt="image" src="https://github.com/logspace-ai/langflow/assets/10102661/57a11c58-ee65-4d8f-bd16-1c043f0526e3">

so, my question is:
How long do I need to wait in the waitlist?

**Comment by honemle** [comment]
<img width="696" alt="image" src="https://github.com/logspace-ai/langflow/assets/10102661/8b829b45-6106-4b0b-97eb-8e1af7f16222">
I just registered an account and use the account to login in the langflow page, and the error happened. Could you please help to figure out the reason?

**Comment by honemle** [comment]
[image: image.png]
So, How long does it take when I am in the waitlist?

dosubot[bot] ***@***.***> 于2024年1月19日周五 16:55写道：

**Comment by Dolphinchan** [comment]
encountered the same problem. Do you have this issue solved afterwards?

**Comment by ogabrielluiz** [comment]
Hi! 
We are moving people off the waitlist every day while we scale our system.

**Comment by cornpo** [comment]
Good. I'm glad I wasted my time.

**Comment by ogabrielluiz** [comment]
Hey all. 

Just remember that the Langflow Store is an additional feature of Langflow and it is not required to run or use Langflow.

**Comment by vinz-deloitte** [comment]
Hey guys, i have the similar issue. but if its an additional feature, why am i not able to even fork the existing collections, because forking requires api key to be added , and api key can be added only if i login to langflow store. so it comes into a full circle for a new user. Could you help me with it if I'm missing something here or is there an other way to create an api key for using langflow?

**Comment by ogabrielluiz** [comment]
Hey 

I'm sorry if this is confusing. This is our fault for sure. 

We are working on getting the Store available to all soon which will likely mitigate the confusion around it. 

The gist is that we didn't know we could handle the traffic so we are getting people off the waitlist in (big) batches.
