### ISSUE TITLE
pip install langflow installs v0.0l78 instead of >==0.5.0 and has very few modules.

### ISSUE THREAD

**Issue by jeffhaskin** [langflow-ai/langflow#1363]
**Describe the bug**
pip install langflow installs v0.0.78 instead of >==0.5.0 and has very few modules.

**Browser and Version**
 - Safari

**To Reproduce**
1. Open terminal.
2. `pip install langflow`
3. Open `http://127.0.0.1:7860/` in a browser.
4. Note the version on the lower left.

**Screenshots**
<img width="2043" alt="Screenshot 2024-01-22 at 1 42 38 PM" src="https://github.com/logspace-ai/langflow/assets/60890286/96ac3deb-a68a-478f-8b08-737cf8cb3fa8">

**Additional context**
When I enter `langflow --help` in the terminal, it has only a few options and is missing many of the options that are on the github page.

**Comment by jeffhaskin** [comment]
I tried `pip install --no-cache-dir langflow` and it still installed v0.0.78

**Comment by sgjohnson1981** [comment]
@jeffhaskin I tried installing langflow[local] just now and it started at version 0.2.7 and kept going back looking for a [local] version and never found it. After examining what the python requirements were for older versions of langflow versus current versions it seems earlier versions had requirements that included python<3.12, while current langflow versions were python<3.11. I was trying 3.11, so after installing 3.10 and using the python.exe -m venv for 3.10 it finally installed the correct version of langflow. Not sure if that will resolve your issue, but thought I'd share.

**Comment by jeffhaskin** [comment]
> @jeffhaskin I tried installing langflow[local] just now and it started at version 0.2.7 and kept going back even further looking for a [local] version and never found it. After examining what the python requirements were for older versions of langflow versus current versions at pypi.org it seems earlier versions had requirements that included python<3.12, while current langflow versions were python<3.11. I was trying 3.11, so after installing 3.10 and using the python.exe -m venv for 3.10 it finally installed the correct version of langflow. Not sure if that will resolve your issue, but thought I'd share.

@sgjohnson1981 I'll try that. I think I was able to get that to happen with an earlier python version as well (3.9.13 or something like that), but then it didn't have any components in it. I'll try 3.10.
