### ISSUE TITLE
Running the program gets a blank page

### ISSUE THREAD

**Issue by ruan-xb-63** [langflow-ai/langflow#1367]
pip install langflow
open http://127.0.0.1:7860 
get error: Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.
I use python3.9 and I've tried versions 0.6.4, 0.2.0, 0.0.78 all with blank pages
![image](https://github.com/logspace-ai/langflow/assets/68852853/feb36194-f0c0-4be5-87aa-1e0ec4e0869e)

**Comment by anovazzi1** [comment]
I recommend trying Python 3.10. Additionally, you can find some solutions to this problem on our Discord channel:
https://discord.com/channels/1116803230643527710/1129415917445586974
