### ISSUE TITLE
langchain LLM IBM watsonx.ai is not found in langflow LLM tab

### ISSUE THREAD

**Issue by dove-young** [langflow-ai/langflow#1380]
**Describe the bug**
In langchain LLM components, there is `IBM watsonx.ai`,  https://python.langchain.com/docs/integrations/llms/watsonxllm, but this LLM is not found in langflow LLM tab

My env is 
```
ibm-watsonx-ai                             0.1.5
langchain                                  0.1.4
langchain-community                        0.0.16
langchain-core                             0.1.16
langchain-experimental                     0.0.47
langchain-google-genai                     0.0.2
langchainhub                               0.1.14
langdetect                                 1.0.9
langflow                                   0.6.4
langfuse                                   1.14.0
langsmith                                  0.0.84
```

**Screenshots**
![Screenshot 2024-01-29 at 13 34 47](https://github.com/logspace-ai/langflow/assets/606882/6333d5ba-a3f6-4d59-bd68-bb44778b433d)

**Additional context**

**Comment by ogabrielluiz** [comment]
Hey @dove-young 

To add a new component the easiest way is to create a CustomComponent.

The implementation should be very similar to [ChatOpenAI's](https://github.com/logspace-ai/langflow/blob/fd55d50b89373b7bd5434ac154e8b5f6f2e4e57b/src/backend/langflow/components/llms/ChatOpenAI.py#L10). 

You can create it in the repo or you could drop a CustomComponent on the canvas e adapt the code above with the correct parameters, imports, etc.
