### ISSUE TITLE
Langflow Store API Token

### ISSUE THREAD

**Issue by AliNaqvi110** [langflow-ai/langflow#1391]
Hi I hope you are doing well.
I have installed Langflow locally in my system. I can't see any components in that when I run the Langflow. I want to create Flow for which I need  components. It asks me to Put API Token Key for Langflow. when I register for API Token Key it put me in wait list. How long I have to wait. i need to complete the task by today. Suggest me how can I create flow using components.
!

**Comment by AliNaqvi110** [comment]
thanks, I need it badly, I need to create flows today, and I can't see any components to create flow

**Comment by Dolphinchan** [comment]
encountered the same problem. Do you have this issue solved afterwards?

**Comment by ogabrielluiz** [comment]
Hey, we are inviting new people every day. Soon y'all will get access to it too. 

Now, if you just want to use Langflow, all of it is accessible and all components can be created with the current release.
