### ISSUE TITLE
Error: cannot import name 'CreateTrace' from 'langfuse.callback' 

### ISSUE THREAD

**Issue by Jotte92** [langflow-ai/langflow#1409]
Having an issue getting a response back from GPT when using a basic ConversationChain. 

Terminal shows an error with langfuse being unable to import 'CreateTrace' from 'langfuse.callback'.

Can anyone help me on this one?

 - Browser [safari 17.2.1]
 - Python 3.10
 - Langflow 0.6.6
 - Langfuse 2.9.0

<img width="1397" alt="Screenshot 2024-02-08 at 8 37 31 am" src="https://github.com/logspace-ai/langflow/assets/157888831/b0a6c8be-1d54-495b-960e-b15c93a5fc96">
<img width="1052" alt="Screenshot 2024-02-08 at 8 37 42 am" src="https://github.com/logspace-ai/langflow/assets/157888831/ab53b84b-90b9-404f-b164-b8a2069b81c6">
<img width="666" alt="Screenshot 2024-02-08 at 8 39 07 am" src="https://github.com/logspace-ai/langflow/assets/157888831/17620707-e7ec-45ce-a4fe-fd369a25d3d0">

**Comment by Inkognitoo** [comment]
Same problem. But when I try to downgrade the langfuse version, I get an error:
`langflow 0.6.6 requires langfuse<3.0.0,>=2.9.0, but you have langfuse 1.8.0 which is incompatible.`

**Comment by Jotte92** [comment]
I got this error also however I was shocked to see it still installed. I uninstalled Langfuse and then reinstalled v1.8.0. I was also using terminal inside anaconda not sure if this makes a difference. Maybe check to see what version of langfuse you have after the error message.

**Comment by flefevre** [comment]
I have the same issue through a docker installation

**Comment by flefevre** [comment]
so iget into my docker

`ser@466e8085241e:~/app$ pip show langfuse
Name: langfuse
Version: 2.9.0
Summary: A client library for accessing langfuse
Home-page: 
Author: langfuse
Author-email: developers@langfuse.com
License: MIT
Location: /home/user/.local/lib/python3.10/site-packages
Requires: backoff, chevron, httpx, openai, pydantic, wrapt
Required-by: langflow
user@466e8085241e:~/app$ 
user@466e8085241e:~/app$ 
user@466e8085241e:~/app$ 
user@466e8085241e:~/app$ 
user@466e8085241e:~/app$ pip show langflow
Name: langflow
Version: 0.6.6
Summary: A Python package with a built-in web application
Home-page: https://github.com/logspace-ai/langflow
Author: Logspace
Author-email: contact@logspace.ai
License: MIT
Location: /home/user/.local/lib/python3.10/site-packages
Requires: alembic, anthropic, bcrypt, beautifulsoup4, boto3, cachetools, certifi, chromadb, cohere, docstring-parser, elasticsearch, extract-msg, faiss-cpu, fake-useragent, fastapi, fastavro, google-api-python-client, google-cloud-aiplatform, google-search-results, gunicorn, huggingface-hub, jina, jq, langchain, langchain-experimental, langchain-google-genai, langchain-openai, langfuse, llama-index, loguru, lxml, markupsafe, metal-sdk, metaphor-python, multiprocess, networkx, numexpr, openai, orjson, pandas, passlib, pgvector, pillow, pinecone-client, platformdirs, psycopg, psycopg-binary, psycopg2-binary, pyarrow, pyautogen, pydantic, pydantic-settings, pymongo, pypdf, pysrt, python-jose, python-multipart, pytube, qdrant-client, qianfan, rich, sqlmodel, supabase, tiktoken, typer, types-cachetools, unstructured, uvicorn, weaviate-client, websockets, wikipedia, zep-python
`

i have still the error

`Traceback (most recent call last):
langflow-1  |   File "/home/user/.local/lib/python3.10/site-packages/langflow/processing/base.py", line 81, in get_result_and_steps
langflow-1  |     callbacks = setup_callbacks(sync=True, trace_id=trace_id, **kwargs)
langflow-1  |   File "/home/user/.local/lib/python3.10/site-packages/langflow/processing/base.py", line 23, in setup_callbacks
langflow-1  |     plugin_callbacks = plugin_service.get_callbacks(_id=trace_id)
langflow-1  |   File "/home/user/.local/lib/python3.10/site-packages/langflow/services/plugins/service.py", line 63, in get_callbacks
langflow-1  |     callback = plugin.get_callback(_id=_id)
langflow-1  |   File "/home/user/.local/lib/python3.10/site-packages/langflow/services/plugins/langfuse_plugin.py", line 67, in get_callback
langflow-1  |     from langfuse.callback import CreateTrace  # type: ignore
langflow-1  | ImportError: cannot import name 'CreateTrace' from 'langfuse.callback' (/home/user/.local/lib/python3.10/site-packages/langfuse/callback.py)
`

any idea?

**Comment by prathigajd** [comment]
@Jotte92 which langchain and langflow version your using ?

**Comment by flefevre** [comment]
Hello,
personnaly i have tested several version of langflow/langfuse. sorry for my english, i am french...

please find here the minimum docker files to connect Ollama with LangFlow and WebUI with minimal configuration
-DockerFile.langflow
-docker-compose.yml
-.env
-one langflow flow to ollama

if you run "docker compose up"
you should be able to load a model in webui
connect to langflow with amin:123456
import the flow 
execute to see the error.

you can also verify:

- ollama server is working
- webui server is working
- chating from webui by calling model from ollama is working

but when calling from langflow, there is a problem of connexion...

hope it can hekp to detect where come the problem.
[langflow4cea2test.zip](https://github.com/logspace-ai/langflow/files/14388217/langflow4cea2test.zip)

**Comment by flefevre** [comment]
It seems to be related to https://github.com/logspace-ai/langflow/discussions/888
