### ISSUE TITLE
installed langflow in docker, langflow store registration and authentication are looping. 

### ISSUE THREAD

**Issue by bayeslearner** [langflow-ai/langflow#1412]
Just followed the instruction to run langflow locally using docker, but the registration for accessing community shared flow doesn't seem to be working at all.  
Tried all authentication methods github/google/discord.  None of them works.

**Comment by fenss** [comment]
Try this:

export LANGFLOW_SUPERUSER={your_su_name}
export LANGFLOW_SUPERUSER_PASSWORD={your_su_pwd}
export LANGFLOW_AUTO_LOGIN=False
