### ISSUE TITLE
CUSTOM COMPONENTS disappeared

### ISSUE THREAD

**Issue by fenss** [langflow-ai/langflow#1463]
**Describe the bug**

**Browser and Version**
 - Browser FireFox/Chrome
 - Version 6.6.7a2

**To Reproduce**
1. Writing codes, add 3 CUSTOM COMPONENTS, naming A/B/C.
2. Setting environment variable: ```export LANGFLOW_COMPONENTS_PATH='["{your_code_path}/langflow_custom_components/"]'```.
3. Run langflow, then see the COMPONENTS in the 'Other' menu bar, and build some flows successfully, so the COMPONENTS' codes are fine.
4. Continue adding COMPONENTS, we call it D, after re-run langflow, we can only find 3 COMPONENTS in the 'Other' menu card, for example B/C/D.
5. Add COMPONENTS E, and still fine 3, like B/D/E, seems like it only support 3 CUSTOM COMPONENTS?

**Screenshots**

Here's the menu look like:

![menu_bar](https://github.com/logspace-ai/langflow/assets/9426274/d23ccccc-6a37-4e5a-83bd-7d1b785aedd0)

Here's my project codes:

![project_structure](https://github.com/logspace-ai/langflow/assets/9426274/25444e7c-7c84-4d03-b26a-7f84d5bb34ec)

**Additional context**

**Comment by fenss** [comment]
> _🤖_
> 
> Hey @fenss, nice to see you around here again! How have things been since our last chat?
> 
> Thank you for providing a detailed description of the issue you're facing. Based on the information you've provided, it seems like you're experiencing an issue where only three custom components are being loaded at a time.
> 
> From the information available in the [langflow repository](https://github.com/logspace-ai/langflow), there doesn't appear to be a limit to the number of custom components that can be loaded. The `CustomComponent` class, which is used to handle custom components, doesn't seem to have any restrictions on the number of instances that can be created.
> 
> However, it's possible that there might be a bug or an unintended restriction somewhere in the code that's causing this issue. Without more information, it's difficult to say for sure what might be causing this.
> 
> To help troubleshoot this issue, could you please provide the following information:
> 
>     1. Are there any error messages being displayed in the console when you try to load more than three custom components?
> 
>     2. Could you provide the code for the custom components that you're trying to load? This could help identify if there's something specific in the code that's causing the issue.
> 
>     3. Could you provide more details about the environment you're running langflow in? For example, what operating system are you using, and what version of Node.js and npm are you using?
> 
> 
> This information could help identify what might be causing this issue. Once we have more information, we can look into this further and try to find a solution.
> 
> Please note that while I strive to provide accurate and helpful information, there may be a better answer that I wasn't able to find. If you have any further questions or need more help, please don't hesitate to ask.
> ## Sources
> 
>     * [tests/test_custom_component.py](https://github.com/logspace-ai/langflow/blob/dev/tests/test_custom_component.py)
> 
> 
> #### About Dosu
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

Sure.

1. Not any error messages. As I said, the component runs fine, I've tested, it just disappeared when I add more, It's strange.
2. Yes but can just provide one of them, It's quite simple, I just override the langchain LLM class, to output the prompt itself for debug purpose, here's my codes:

```python
# {custom_python_path}/langchain_custom_utils/llm_request_utils.py

from typing import Any, Dict, List, Mapping, Optional
from langchain.llms.base import LLM
from langchain_core.callbacks.manager import CallbackManagerForLLMRun

……

class ParrotLLM(LLM):
    tag: str
    @property
    def _llm_type(self) -> str:
        return 'ResponseAsParrot'
    @property
    def _identifying_params(self) -> Mapping[str, Any]:
        return {
            'tag': self.tag,
        }

    def _call(
        self,
        prompt: str,
        stop: Optional[List[str]] = None,
        run_manager: Optional[CallbackManagerForLLMRun] = None,
        **kwargs: Any,
    ) -> str:
        return prompt
```

```python
# {langflow_custom_components_path}/parrot_llm_component.py
from langchain.llms.base import LLM
from langflow import CustomComponent

from langchain_custom_utils.llm_request_utils import ParrotLLM


class ParrotLLMComponent(CustomComponent):
    display_name = 'Parrot LLM Component'
    description = 'Just repeat the prompt.'

    def build_config(self) -> dict:
        return {}

    def build(self, entry_point: str) -> LLM:
        llm = ParrotLLM(tag='parrot', cache=False)
        return llm

```

Before running langflow, I set ```export PYTHONPATH={custom_python_path}```, so the component can import the utils.

3. Just use the Docker Image:
FROM python:3.10.13-slim-bullseye

And ```pip install langflow==6.6.7a2```, then run it……
I think it's not relevant to the NPM?

**Comment by fenss** [comment]
> _🤖_
> 
> Based on the information you've provided, it seems like your code for the custom components is correct. The issue you're experiencing might be related to how Langflow discovers and loads custom components.
> 
> Langflow uses the `importlib` module in Python to dynamically load modules at runtime. It uses the `import_module` function to import the module and the `getattr` function to get the class from the module. This is done in the `import_class` function, which is called by the `import_custom_component` function with the fully qualified name of the `CustomComponent` class.
> 
> Here's the relevant code from Langflow:
> 
> ```python
> def import_module(module_path: str) -> Any:
>     """Import module from module path"""
>     if "from" not in module_path:
>         # Import the module using the module path
>         return importlib.import_module(module_path)
>     # Split the module path into its components
>     _, module_path, _, object_name = module_path.split()
> 
>     # Import the module using the module path
>     module = importlib.import_module(module_path)
> 
>     return getattr(module, object_name)
> 
> def import_class(class_path: str) -> Any:
>     """Import class from class path"""
>     module_path, class_name = class_path.rsplit(".", 1)
>     module = import_module(module_path)
>     return getattr(module, class_name)
> 
> def import_custom_component(custom_component: str) -> CustomComponent:
>     """Import custom component from custom component name"""
>     return import_class("langflow.interface.custom.custom_component.CustomComponent")
> ```
> 
> (Source: [src/backend/langflow/interface/importing/utils.py](https://github.com/logspace-ai/langflow/blob/dev/src/backend/langflow/interface/importing/utils.py))
> 
> Given this, there are a few things you could check:
> 
>     1. Make sure the `PYTHONPATH` environment variable is correctly set to include the path to your custom components. You can check this by running `echo $PYTHONPATH` in your terminal.
> 
>     2. Check if the fully qualified name of your `CustomComponent` class is correct. The fully qualified name should include the module path and the class name, separated by a dot. For example, in your case, it should be something like `{langflow_custom_components_path}.parrot_llm_component.ParrotLLMComponent`.
> 
>     3. Make sure the `CustomComponent` class is correctly imported in your custom component file. In your case, it should be `from langflow import CustomComponent`.
> 
> 
> If you've checked all of these and the issue still persists, it might be helpful to add some logging in the `import_class` and `import_custom_component` functions to see what's going wrong. For example, you could log the `module_path`, `class_name`, and the imported module and class.
> 
> I hope this helps! If you have any other questions or need further clarification, feel free to ask.
> ## Sources
> 
>     * [tests/test_custom_component.py](https://github.com/logspace-ai/langflow/blob/dev/tests/test_custom_component.py)
> 
>     * [src/backend/langflow/interface/importing/utils.py](https://github.com/logspace-ai/langflow/blob/dev/src/backend/langflow/interface/importing/utils.py)
> 
> 
> #### About Dosu

It's not helpful, the components have tested, for example A, B and C, I ran a flow using A+B+C, It's worked. Then I add D, one of A/B/C disappeared, and I can see D in the menu bar, it's not the codes problem or environment variables problem I think.

**Comment by fenss** [comment]
I found the reason:

While logging to the langflow UI, I checked the requests, found sth like ```{your_langchain_url}/api/v1/all```, the response contains the UI definition:

```json
response = requests.get(
    '{your_langflow_url}/api/v1/all',
    headers={
        'x-api-key': '{your_api_key}',
    },
)

print(response.json().keys())

# dict_keys(['chains', 'agents', 'prompts', 'llms', 'memories', 'tools', 'toolkits', 'wrappers', 'embeddings', 'documentloaders', 'textsplitters', 'utilities', 'output_parsers', 'langflow_custom_components', 'retrievers', 'custom_components', 'vectorstores'])
```

Pick some keys to see more:

```python
print(response.json()['chains'].keys())

# dict_keys(['ConversationalRetrievalChain', 'LLMCheckerChain', 'LLMMathChain', 'RetrievalQA', 'RetrievalQAWithSourcesChain', 'SQLDatabaseChain', 'CombineDocsChain', 'SeriesCharacterChain', 'MidJourneyPromptChain', 'TimeTravelGuideChain', 'Document', 'ConversationChain', 'BaseQAWithSourcesChain', 'LLMChain'])

print(response.json()['custom_components'].keys())
# dict_keys(['Data'])
```

We found that it use the component's return type to identify each component, in the upper cases, the official "custom_components" group contains only one component "CustomComponent", and the key is "Data", the return type of itself.

So if we create some components with the same return type, like LLM(langchain.llms.base), they overwrite each other(on the UI).

the temporary solution is wrap each CustomComponent's return value, but I think it's not a good way.

**Comment by nirvitarka** [comment]
I am facing the same issue. The custom component seem built successfully but it does not appear in the frontend UI anywhere.

Here is the command I am using to start langflow 

`python -m langflow run --env-file .env --components-path Customizations --log-level debug --log-file logs/langflow.log`

Here is my project folder structure, I am using python virtualenv named "myenv".

```
Customizations
      Workflow1
         MyComponentName.py
myenv

```

Langflow is installed via pip & I have not done any changes in the installed package files

While starting langflow using the above command, there are no errors printed in the console. 
I confirm the name of component is unique across all langflow files.

What I am missing.
As the component path is my custom folder, I cannot add any import for this inside the langflow/custom/__init__ files 

What I am missing here?
