### ISSUE TITLE
[OFFICIAL WEBSITE GITHUB SIGNIN ERROR]  An error has occurred. There was an error with your credentials, if you are using github, please check if your email is public.

### ISSUE THREAD

**Issue by HakaishinShwet** [langflow-ai/langflow#1467]
An error has occurred.
There was an error with your credentials, if you are using github, please check if your email is public.
While trying to signin with github getting this issue even tho i have authorized from my side, so is it github issue or issue from langflow server? Tried 3 times to signin got same issue so asking here :-))
Will try tomorrow too but if it is fault from langflow side then i hope it gets fixed soon

**Comment by HakaishinShwet** [comment]
Btw my email id is from google's gmail and is public, not using any personal email id or selfhosted mail server or temp email aliases.First time facing this issue so thought while signin with github so created issue

**Comment by anovazzi1** [comment]
check if your Github account email is set to public, by default it's not
