### ISSUE TITLE
Coroutine question

### ISSUE THREAD

**Issue by fenss** [langflow-ai/langflow#1486]
Hi langflow.

I noticed langflow provides the flow execution API: {langflow_host_and_port}/api/v1/process/{flow_id}

There's a param ```inputs```, actually is the LangChain input param.

Then I create a simple flow, contains one normal LLMChain, one simple PromptTemplate, and a custom LLM. This LLM is simply wrapper of a HTTP request, using requests package in python.

I parallelly call this API: {langflow_host_and_port}/api/v1/process/{flow_id}, using ```inputs``` as a ```dict```, found that it seems execute sequential, that means the requests block each others.

Follow the codes:

1. API endpoints(https://github.com/logspace-ai/langflow/blob/v0.6.7a5/src/backend/langflow/api/v1/endpoints.py):
```python
@router.post(
    "/predict/{flow_id}",
    response_model=ProcessResponse,
    dependencies=[Depends(api_key_security)],
)
@router.post(
    "/process/{flow_id}",
    response_model=ProcessResponse,
)
async def process(
    session: Annotated[Session, Depends(get_session)],
    flow_id: str,
    inputs: Optional[Union[List[dict], dict]] = None,
    tweaks: Optional[dict] = None,
    clear_cache: Annotated[bool, Body(embed=True)] = False,  # noqa: F821
    session_id: Annotated[Union[None, str], Body(embed=True)] = None,  # noqa: F821
    task_service: "TaskService" = Depends(get_task_service),
    api_key_user: User = Depends(api_key_security),
    sync: Annotated[bool, Body(embed=True)] = True,  # noqa: F821
    session_service: SessionService = Depends(get_session_service),
):
    """
    Endpoint to process an input with a given flow_id.
    """
```
2. Get flow graph from storage, and ready to set the session(https://github.com/logspace-ai/langflow/blob/v0.6.7a5/src/backend/langflow/api/v1/endpoints.py):
```python
async def process_graph_data(
    graph_data: dict,
    inputs: Optional[Union[List[dict], dict]] = None,
    tweaks: Optional[dict] = None,
    clear_cache: bool = False,
    session_id: Optional[str] = None,
    task_service: "TaskService" = Depends(get_task_service),
    sync: bool = True,
):
```
3. Parse flow graph(https://github.com/logspace-ai/langflow/blob/v0.6.7a5/src/backend/langflow/processing/process.py):
```python
async def process_graph_cached(
    data_graph: Dict[str, Any],
    inputs: Optional[Union[dict, List[dict]]] = None,
    clear_cache=False,
    session_id=None,
) -> Result:
```
4. Start generating result(https://github.com/logspace-ai/langflow/blob/v0.6.7a5/src/backend/langflow/processing/process.py):
```python
async def build_graph_and_generate_result(
    graph: "Graph",
    session_id: str,
    inputs: Optional[Union[dict, List[dict]]] = None,
    artifacts: Optional[Dict[str, Any]] = None,
    session_service: Optional[SessionService] = None,
):
```
5. It wraps the input, and EXECUTE the ```Runnable``` instance in the flow graph(https://github.com/logspace-ai/langflow/blob/v0.6.7a5/src/backend/langflow/processing/process.py):
```python
async def generate_result(built_object: Union[Chain, VectorStore, Runnable], inputs: Union[dict, List[dict]]):
    if isinstance(inputs, dict):
        result = await process_inputs_dict(built_object, inputs)
    elif isinstance(inputs, List) and isinstance(built_object, Runnable):
        result = await process_inputs_list(built_object, inputs)
    else:
        raise ValueError(f"Invalid inputs type: {type(inputs)}")

    if result is None:
        logger.warning(f"Unknown built_object type: {type(built_object)}")
        if isinstance(built_object, Coroutine):
            result = asyncio.run(built_object)
        result = built_object

    return result
```
6. My ```inputs``` is a dict, here we go, we focus on ```output = langchain_object(inputs, return_only_outputs=True)```:
```python
async def process_inputs_dict(built_object: Union[Chain, VectorStore, Runnable], inputs: dict):
    if isinstance(built_object, Chain):
        if inputs is None:
            raise ValueError("Inputs must be provided for a Chain")
        logger.debug("Generating result and thought")
        result = get_result_and_thought(built_object, inputs)

        logger.debug("Generated result and thought")

……
def get_result_and_thought(langchain_object: Any, inputs: dict):
    """Get result and thought from extracted json"""
……
        try:
            output = langchain_object(inputs, return_only_outputs=True)
……
```
7. It's just a plain ```__call__``` of Chain. If ```inputs``` is a dict wrapped in a list, It will call ```abatch``` or ```ainvoke```, and the requests will not block each others:
```python
async def process_inputs_list(built_object: Runnable, inputs: List[dict]):
    return await process_runnable(built_object, inputs)
……
async def process_runnable(runnable: Runnable, inputs: Union[dict, List[dict]]):
    if isinstance(inputs, List) and hasattr(runnable, "abatch"):
        result = await runnable.abatch(inputs)
    elif isinstance(inputs, dict) and hasattr(runnable, "ainvoke"):
        result = await runnable.ainvoke(inputs)
```

Is that necessary to ```output = langchain_object(inputs, return_only_outputs=True)```?

**Comment by songjinu** [comment]
I also need the process for non blocking.
What's the reason of blocking process at #get_result_and_thought like the analysis of @fenss ?
How about this I modified like this,  
```
       # result = get_result_and_thought(built_object, inputs)

        from fastapi.concurrency import run_in_threadpool
        result = await run_in_threadpool(get_result_and_thought, built_object, inputs)
```

**Comment by carlosrcoelho** [comment]
Hi @fenss , 

We hope you're doing well. Just a friendly reminder that if we do not hear back from you within the next 3 days, we will close this issue. If you need more time or further assistance, please let us know. 

Thank you for your understanding!

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
