### ISSUE TITLE
Rendering non-chat flows

### ISSUE THREAD

**Issue by kencheah** [langflow-ai/langflow#1492]
Hi Team, are there any plans to render the output of non-chat flows? Currently it seems the end node has to be some form of LLMChain in which the chat functionality can connect to. I currently have to export the json workflow into my local environment and execute there. Having this functionality on the frontend is possible would be great!

**Comment by yamonkjd** [comment]
We have also built and tested OpenAI's Whisper in a non-chat flow, directly calling it through an API as you mentioned. Indeed, there is a critical need for a feature that allows testing inputs and outputs in a flow that does not include the LLM chain.

**Comment by anovazzi1** [comment]
I completely agree. We're actively working on this and, to be honest, we're already in the testing phase. We anticipate it will be available in just a few weeks at most.
