### ISSUE TITLE
VectorStoreInfo Cannot connect to VectorStoreAgent

### ISSUE THREAD

**Issue by chuanran** [langflow-ai/langflow#1496]
**Describe the bug**
When I launch langflow (followed by "make init"; "make build_and_install" and "langflow run"), and try an example of pyPDFLoader, I found `VectorStoreInfo` cannot connect to `VectorStoreAgent`. 

**Browser and Version**
 - Browser: Chrome
 - Version:  118.0.5993.117

**To Reproduce**
1. clone the `dev` branch of langflow github repo
2. run "make init"; "make build_and_install" and "langflow run"
3. Create a project in langflow UI, drag "PyPDFLoader", "RecursiveCharacterTextSplitter", "OpenAIEmbeddings",  "Chroma", "ChatOpenAI", "VectorStoreInfo" and "VectorStoreAgent", connect those components as the screenshot below shows
4. Found that all other components can be connected successfully, except that `VectorStoreInfo` cannot connect to `VectorStoreAgent`.
**Screenshots**
![Screenshot 2024-03-05 at 4 17 38 PM](https://github.com/logspace-ai/langflow/assets/3916517/a06c2426-eb8f-4951-bfb7-463132895356)

**Additional context**

**Comment by sidedwards** [comment]
This is still an issue. It's not possible to connect VectorStoreInfo to VectorStoreAgent in the most recent version.

Related issues:
- #1429
- #1507

**Comment by rubrix** [comment]
Also related #https://github.com/langflow-ai/langflow/issues/1427

**Comment by RyanGitproj** [comment]
So what is the alternative to connect VectorStoreInfo to VectorStoreAgent because it's like a bug of the update.

**Comment by anovazzi1** [comment]
Hello, @RyanGitproj,
Sorry for the delay. What version are you using? Does the error still persist?

**Comment by carlosrcoelho** [comment]
Hi @chuanran and @RyanGitproj , 

We hope you're doing well. Just a friendly reminder that if we do not hear back from you within the next 3 days, we will close this issue. If you need more time or further assistance, please let us know. 

Thank you for your understanding!

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
