### ISSUE TITLE
Issue with Loading Custom Components in Langflow UI

### ISSUE THREAD

**Issue by adarshsingh2** [langflow-ai/langflow#1498]
**Describe the bug**
I'm encountering an issue where custom components in Langflow are not loading correctly due to conflicts in component identification. It seems that Langflow uses the return type of components to identify each component. However, if multiple components have the same return type, they overwrite each other on the UI.

**Browser and Version**
 - Browser  chrome
 - Version [0.6.9]

**To Reproduce**
1-Log in to the Langflow UI.
2-Check the requests made to {your_langchain_url}/api/v1/all.
3-Analyze the response to see the UI definition, particularly the custom_components section.
4-Notice that the return types of custom components are used as keys, potentially leading to conflicts.

**Additional context**
Suspected culprit - 
src\backend\langflow\interface\custom\directory_reader\directory_reader.py
```
            if validation_result:
                try:
                    **output_types = self.get_output_types_from_code(result_content)**
                except Exception as exc:
                    logger.exception(f"Error while getting output types from code: {str(exc)}")
                    output_types = [component_name_camelcase]
            else:
                output_types = [component_name_camelcase]
```

**Comment by adarshsingh2** [comment]
Adding unique name field didn't make any difference.

> Hey @adarshsingh2, great to see you back! Running into more adventures in the world of Langflow, I see. 🚀
> 
> To resolve the issue of custom components in Langflow not loading correctly due to conflicts in component identification, where multiple components with the same return type overwrite each other on the UI, you need to ensure that each component has a unique identifier. This can be achieved by adding a unique `name` attribute to each custom component class. The `name` attribute acts as a unique identifier for the component in the Langflow UI, preventing conflicts between components with the same return type.
> 
> Here's how you can modify your `CustomComponent.py` to include a unique `name` attribute:
> 
> ```python
> from langflow import CustomComponent
> from langflow.field_typing import Data
> 
> 
> class Component(CustomComponent):
>     name: str = "UniqueComponentName"  # Ensure this name is unique across all components
>     documentation: str = "http://docs.langflow.org/components/custom"
> 
>     def build_config(self):
>         return {"param": {"display_name": "Parameter"}}
> 
>     def build(self, param: Data) -> Data:
>         return param
> ```
> 
> In the modified code, the `name` attribute is set to `"UniqueComponentName"`. You should replace `"UniqueComponentName"` with an actual unique name that describes your component. This change will help Langflow to differentiate between multiple custom components, even if they have the same return type, thus resolving the issue of components overwriting each other on the UI.
> 
> As for how Langflow identifies and differentiates between custom components in the UI, it does so by wrapping and extending the functionality of the components provided by `@radix-ui/react-select`. Each custom component is defined by forwarding refs and spreading props to the base components from `@radix-ui/react-select`, allowing for additional customization and styling. The differentiation is achieved through the creation of distinct components such as `SelectTrigger`, `SelectContent`, `SelectLabel`, `SelectItem`, and `SelectSeparator`, each serving a specific purpose within the UI and being styled individually using the `cn` utility function for conditional class names. This approach enables the creation of a cohesive and customizable select UI component structure.
> 
> You can find more details in the source code:
> 
> * [CustomComponent.py](https://github.com/logspace-ai/langflow/blob/dev/src/backend/langflow/components/custom_components/CustomComponent.py)
> * [select-custom.tsx](https://github.com/logspace-ai/langflow/blob/dev/src/frontend/src/components/ui/select-custom.tsx)
> 
> I hope this helps! If you have any more questions or need further clarification, feel free to ask.
> 
> ## Sources
> * [src/backend/langflow/components/custom_components/CustomComponent.py](https://github.com/logspace-ai/langflow/blob/dev/src/backend/langflow/components/custom_components/CustomComponent.py)
> * [src/frontend/src/components/ui/select-custom.tsx](https://github.com/logspace-ai/langflow/blob/dev/src/frontend/src/components/ui/select-custom.tsx)
> 
> #### About Dosu
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

Adding unique name field didn't make any difference.

**Comment by pseudo-usama** [comment]
@adarshsingh2 Having the same problem. Did you find any solutions?

**Comment by adarshsingh2** [comment]
> @adarshsingh2 Having the same problem. Did you find any solutions?

Yes, made changes in build method return type like below - 
    def build(
        self,
        endpoint_url: str,
        repo_id: str,
        task: str,
        model_kwargs: Optional[Dict] = None,
    ) -> **Union[MyCustomLLM, BaseLLM]**:

**Comment by pseudo-usama** [comment]
They have fixed this issue in latest commit. As you can see here there is a function that determines component name [code link](https://github.com/langflow-ai/langflow/blob/c6b4101d6971ad8e86567f5993a1a53a0f86032e/src/backend/base/langflow/interface/custom/directory_reader/utils.py#L126).
