### ISSUE TITLE
LANGFLOW_REDIS_PASSWORD env does not work in flower

### ISSUE THREAD

**Issue by artemus717** [langflow-ai/langflow#1502]
**Describe the bug**
I run flower in Kubernetes , set these env in Kubernetes, but seemed only LANGFLOW_REDIS_HOST and LANGFLOW_REDIS_PORT will work. LANGFLOW_REDIS_PASSWORD does not appear in Broker: redis://10.62.174.33:6379/0
LANGFLOW_REDIS_DB : 6
LANGFLOW_REDIS_EXPIRE : 3600
LANGFLOW_REDIS_HOST : 10.62.174.33
LANGFLOW_REDIS_PASSWORD : xxxxx
LANGFLOW_REDIS_PORT : 6379

Version is 0.6.4

**Screenshots**
[I 240307 08:12:45 command:168] Visit me at http://0.0.0.0:5555
[I 240307 08:12:45 command:176] Broker: redis://10.62.174.33:6379/0
[I 240307 08:12:45 command:177] Registered tasks:
    ['celery.accumulate',
     'celery.backend_cleanup',
     'celery.chain',
     'celery.chord',
     'celery.chord_unlock',
     'celery.chunks',
     'celery.group',
     'celery.map',
     'celery.starmap',
     'langflow.worker.build_vertex',
     'langflow.worker.process_graph_cached_task',
     'langflow.worker.test_celery']
[E 240307 08:12:51 events:191] Failed to capture events: 'Authentication required.', trying again in 2 seconds.
[E 240307 08:12:51 base_events:1758] Future exception was never retrieved
    future: <Future finished exception=OperationalError('Authentication required.')>
    Traceback (most recent call last):
      File "/opt/pysetup/.venv/lib/python3.10/site-packages/kombu/transport/virtual/base.py", line 951, in create_channel
        return self._avail_channels.pop()
    IndexError: pop from empty list
    During handling of the above exception, another exception occurred:

**Comment by artemus717** [comment]
Seemed this file does not use LANGFLOW_REDIS_PASSWORD  etc
src/backend/langflow/core/celeryconfig.py

# celeryconfig.py
import os

langflow_redis_host = os.environ.get("LANGFLOW_REDIS_HOST")
langflow_redis_port = os.environ.get("LANGFLOW_REDIS_PORT")
# broker default user

if langflow_redis_host and langflow_redis_port:
    broker_url = f"redis://{langflow_redis_host}:{langflow_redis_port}/0"
    result_backend = f"redis://{langflow_redis_host}:{langflow_redis_port}/0"
else:
    # RabbitMQ
    mq_user = os.environ.get("RABBITMQ_DEFAULT_USER", "langflow")
    mq_password = os.environ.get("RABBITMQ_DEFAULT_PASS", "langflow")
    broker_url = os.environ.get("BROKER_URL", f"amqp://{mq_user}:{mq_password}@localhost:5672//")
    result_backend = os.environ.get("RESULT_BACKEND", "redis://localhost:6379/0")
# tasks should be json or pickle
accept_content = ["json", "pickle"]

**Comment by songjinu** [comment]
Hello, 
LANGFLOW_REDIS_PASSWORD does not work now.
you can set env directly like this. 
---- in .env , if use redis cache.
BROKER_URL=redis://:redis_pw@localhost:6379/0
RESULT_BACKEND=redis://:redis_pw@localhost:6379/0
----

**Comment by ogabrielluiz** [comment]
Hey, are you using the dev branch? 

We are still updating that part, feel free to contribute. 

Let us know if you need any help!

**Comment by artemus717** [comment]
I just use BROKER_URL directly now.
