### ISSUE TITLE
Foreign key constraint could not be located

### ISSUE THREAD

**Issue by marshall-at-corvee** [langflow-ai/langflow#1505]
**Describe the bug**
Receive multiple similar/same errors when running langflow or migrations, one for {flow,credential}

.
 /home/marshall/.local/lib/python3.9/site-packages/langflow/alembic                
/home/marshall/.local/lib/python3.9/site-packages/langflow/alembic/env.py:82: SAWarning: WARNING: SQL-parsed foreign key constraint '('user_id', 'user', 'id')' could not be located in PRAGMA foreign_keys for table flow

Fresh install using 
pip install langflow 
langflow run (note the docs say to just run 'langflow' but this gives the usage description)

**Browser and Version**
 - Browser Safari
 - Version 17.0 (19616.1.27.211.1)

**To Reproduce**
at a command prompt:
pip install langflow 
langflow run

I get the same error when installing into google cloud.
(side note... the pip install langflow command fails in google cloud unless 'pip install -U pip setuptools' is run first.  Don't know which fixed it.

**Screenshots**

**Additional context**
the error is identical whether locally an macOS or GCP 
╭───────────────────────────────────────────────────╮
│ Welcome to ⛓ Langflow                             │
│                                                   │
│ Access http://127.0.0.1:7860                      │
│ Collaborate, and contribute at our GitHub Repo 🚀 │
╰───────────────────────────────────────────────────╯
[2024-03-07 18:09:17 +0000] [128394] [INFO] Starting gunicorn 21.2.0
[2024-03-07 18:09:17 +0000] [128394] [INFO] Listening at: http://127.0.0.1:7860 (128394)
[2024-03-07 18:09:17 +0000] [128394] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2024-03-07 18:09:17 +0000] [128403] [INFO] Booting worker with pid: 128403
[2024-03-07 18:09:17 +0000] [128403] [INFO] Started server process [128403]
[2024-03-07 18:09:17 +0000] [128403] [INFO] Waiting for application startup.
[03/07/24 18:09:17] INFO     2024-03-07 18:09:17 - INFO     - service - Alembic already          service.py:142
                             initialized                                                                       
                    INFO     2024-03-07 18:09:17 - INFO     - service - Running DB migrations in service.py:150
                             /home/marshall/.local/lib/python3.9/site-packages/langflow/alembic                
/home/marshall/.local/lib/python3.9/site-packages/langflow/alembic/env.py:82: SAWarning: WARNING: SQL-parsed foreign key constraint '('user_id', 'user', 'id')' could not be located in PRAGMA foreign_keys for table flow
  context.run_migrations()
/home/marshall/.local/lib/python3.9/site-packages/langflow/alembic/env.py:82: SAWarning: WARNING: SQL-parsed foreign key constraint '('user_id', 'user', 'id')' could not be located in PRAGMA foreign_keys for table credential
  context.run_migrations()
No new upgrade operations detected.
/home/marshall/.local/lib/python3.9/site-packages/langflow/alembic/env.py:82: SAWarning: WARNING: SQL-parsed foreign key constraint '('user_id', 'user', 'id')' could not be located in PRAGMA foreign_keys for table flow
  context.run_migrations()
/home/marshall/.local/lib/python3.9/site-packages/langflow/alembic/env.py:82: SAWarning: WARNING: SQL-parsed foreign key constraint '('user_id', 'user', 'id')' could not be located in PRAGMA foreign_keys for table credential
  context.run_migrations()
No new upgrade operations detected.
                    INFO     2024-03-07 18:09:17 - INFO     - utils - No LLM cache set.             utils.py:88
[2024-03-07 18:09:17 +0000] [128403] [INFO] Application startup complete.

Let me know if I missed some critical information!

**Comment by bennizone** [comment]
Hello, 

I have the same issue here. 
To reproduce: 
Installed a fresh Proxmox Container with ubuntu-22.04-standard_22.04-1_amd64 template. 
alle as root: 
apt update, upgrade
apt install python3-pip
pip install langflow
langflow run --host 0.0.0.0

got the same error messages
Nothing migrated 
Nothing transfered
Just a clean fresh install of ubuntu. 
Cannot find a .db file

Any ideas?

**Comment by nickmitchko** [comment]
Same issue, migration --fix doesn't fix it either. Fresh ubuntu install, fresh venv, fresh everything. 🤔
