### ISSUE TITLE
An error has occurred while fetching types

### ISSUE THREAD

**Issue by bcmin1018** [langflow-ai/langflow#1508]
**Describe the bug**
when tring to run lanflow with docker-compose.yml the error shows up

**Browser and Version**
 - Browser chrome
 - Version 122.0.6261.112
 - Linux Ubuntu

**To Reproduce**
1. run docker with the command below
docker-compose up -d

2. enter the base url : [IP]:9080 (port changed)

3. you can see the error on browser

**Screenshots**

![image](https://github.com/logspace-ai/langflow/assets/101251439/aa9720d4-f7c7-43ce-ac73-21cfcc5dcf08)

403 Forbidden 
![image](https://github.com/logspace-ai/langflow/assets/101251439/4a9b5b6a-fd74-4911-8ff3-ad77c893460e)

**Additional context**

**Comment by marshall-at-corvee** [comment]
I'm getting the same thing with a mostly "vanilla" install and run using pip.  I did have to change to Postgres to avoid the weird sqlite foreign key thing but the run is unchanged other than that.  Any progress on this?  The login call is successful and returns an access and refresh token but the subsequent (whoami) call returns a 403:
{
    "detail": "An API key as query or header, or a JWT token must be passed"
}

seems to be coming from services/auth/utils.py, which implies that the token is not passed to that endpoint, but I haven't yet discovered why.

**Comment by marshall-at-corvee** [comment]
Any chance you're running this in Safari?  I've just tried Chrome and works fine :(

**Comment by bcmin1018** [comment]
I tried it in Safari but not works..
It is weired that it works in Window which is my local computer but not work in ubuntu server, AWS.

**Comment by 4wmarketplace** [comment]
When running on 127.0.0.1 (Ubuntu with pip) langflow is ok. Changing host get same errors (403 forbidden) after login on: GET /api/v1/users/whoami , GET /api/v1/store/check/api_key, GET /api/v1/all

**Comment by 4wmarketplace** [comment]
With 0.6.6 version langflow is running ok on both interfaces (127.0.0.1 or Lan ethernet)
Cannot use after update to 0.6.10

**Comment by 4wmarketplace** [comment]
Found the problem: the login page tried to write a cookie but since it has the secure attribute and langflow ran on http it didn't save it, therefore the subsequent call to whoami failed (403 forbidden) because the cookie was empty.
I solved it with an nginx reverse proxy that runs in https and with the generation of a local certificate.

**Comment by dalan2014** [comment]
1.Open Chrome and navigate to **chrome://flags** in the address bar.
2.Search for the flag titled **Insecure origins treated as secure**.
3.In the text box for this flag, **enter the URL** of your site.
4.**Enable** this setting.
5.**Restart** Chrome.
This trick really helped me out, hope it does the same for you!

**Comment by webtop** [comment]
I was running this on my Windows machine, but connecting to it via a browser on my Mac. Same network.
If I run it with the host as localhost (or default 127.0.0.1), it runs locally on the Windows machine without an issue.
If I run it with the host as the Windows machine IP, I can connect from both local and remote, but get this error.

So my thought would be: where does this error come from, and is it using a network hook to get these "types"

**Comment by anovazzi1** [comment]
Hello,
Sorry for the delay. Did you try using the new version? Does the error still persist?

**Comment by carlosrcoelho** [comment]
Hi @bcmin1018  , 

We hope you're doing well. Just a friendly reminder that if we do not hear back from you within the next 3 days, we will close this issue. If you need more time or further assistance, please let us know. 

Thank you for your understanding!

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.

**Comment by ErwanLorteau** [comment]
Fix it with this three steps :

1 - You have to install an Nginx reverse proxy from the deployement VM via SSH on GCP.
install & Configure nginx using the following, then restart it

Dont forget to replace your IP

server {
    listen 443 ssl;
    server_name YOUR_VM_EXTERNAL_IP; # <-- IMPORTANT: Replace with your VM's IP

    ssl_certificate /etc/ssl/certs/nginx-selfsigned.crt;
    ssl_certificate_key /etc/ssl/private/nginx-selfsigned.key;

    location / {
        proxy_pass http://127.0.0.1:7860;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # Support for WebSockets
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
2- Then create a firewale rule on GCP VPC & firewall allowing 0.0.0.0/0 on ingress for TCP 443

0.0.0.0/0 and NOT 0.0.0.0

finally create a self signed certificate inside the deployment VM

sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/nginx-selfsigned.key -out /etc/ssl/certs/nginx-selfsigned.crt
