### ISSUE TITLE
An error has occured while fetching types (VM instance GCP)

### ISSUE THREAD

**Issue by MS-Kinguin** [langflow-ai/langflow#1518]
**Describe the bug**
I've been attempting to deploy Langflow on a virtual machine following the guidelines outlined in the official GitHub documentation. Despite successfully reaching the stage where Langflow appears to be running, I encounter an error (as depicted in the attached screenshot) when trying to access the application via a web browser. The issue seems unrelated to external connections, as verified by the successful deployment and accessibility of a basic HTTP server on the same environment. This issue persists across various setups, including Ubuntu 22.04, Debian 11 and 12, and I've also experimented with different versions of Langflow. Could there be an underlying problem I'm missing, or are there any additional steps I could undertake to rectify this?

**Browser and Version**
 - Google Chrome
 - Version 122.0.6261.112

**To Reproduce**
1. Follow the deployment from Github:
https://github.com/logspace-ai/langflow/blob/dev/GCP_DEPLOYMENT.md
2. Open the browser and navigate to http://[VM's external IP]:7860.
3. The Langflow UI loads but displays an error message: "an error has occurred while fetching types."

**Screenshots**
![error_langflow](https://github.com/logspace-ai/langflow/assets/121661651/0077d696-21b7-4da3-964c-acef49282311)

**Additional context**

- Firewall settings have been checked and configured to allow traffic on the relevant ports (from the script).
- Port checks reveal that the Langflow service is listening on the intended port.
- I have also attempted running a simple Python HTTP server on the same VM, which worked correctly and was accessible, indicating that the VM and network settings are likely correct.

I think the deployment script is really outdated (last commit was 7 month ago) because, for example it's trying to launch lagflow with the following command:

`langflow --host 0.0.0.0 --port 7860`

**Comment by MS-Kinguin** [comment]
I've seen on discord that it's worth to mention @genome21 who was the GCP architect that implemented it.

**Comment by 4wmarketplace** [comment]
Same error here: https://github.com/logspace-ai/langflow/issues/1508#issuecomment-1992036412

**Comment by wasubire** [comment]
Getting the same error on a Proxmox VM running debian 12. Both LXC and VM returning the same error 


![image](https://github.com/logspace-ai/langflow/assets/79239953/30a00cad-6a7d-44d8-afc3-8b52b14ecd82)

**Comment by 4wmarketplace** [comment]
Found the problem: the login page tried to write a cookie but since it has the secure attribute and langflow ran on http it didn't save it, therefore the subsequent call to whoami failed (403 forbidden) because the cookie was empty.
I solved it with an nginx reverse proxy that runs in https and with the generation of a local certificate.

**Comment by vktinker** [comment]
i have the same error and the exact network out put. What steps did you follow with nginx to resolve this. I have nginx running , but unsure i have the right config.

I have allowed both http and https traffic onto my vm, but no luck. Any help deeply appreciated

**Comment by DharmikRawal** [comment]
@4wmarketplace Can you please share the steps that you have taken here? This will really help up to setup until this issue has been resolved by maintainer.

**Comment by vktinker** [comment]
I have managed to resolve this issue and will post the exact steps to
resolve this including Nginx config

**Comment by ErwanLorteau** [comment]
Fix it with this three steps : 

1 - You have to install an Nginx reverse proxy from the deployement VM via SSH on GCP.
install & Configure nginx using the following, then restart it

**Dont forget to replace your IP** 

```
server {
    listen 443 ssl;
    server_name YOUR_VM_EXTERNAL_IP; # <-- IMPORTANT: Replace with your VM's IP

    ssl_certificate /etc/ssl/certs/nginx-selfsigned.crt;
    ssl_certificate_key /etc/ssl/private/nginx-selfsigned.key;

    location / {
        proxy_pass http://127.0.0.1:7860;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # Support for WebSockets
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
```

2- Then create a firewale rule on GCP VPC & firewall allowing 0.0.0.0/0 on ingress for TCP 443

**0.0.0.0/0 and NOT 0.0.0.0**

finally create a self signed certificate inside the deployment VM

`sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/nginx-selfsigned.key -out /etc/ssl/certs/nginx-selfsigned.crt`
