### ISSUE TITLE
Langfuse does not have any records of flushes to the API.

### ISSUE THREAD

**Issue by yamonkjd** [langflow-ai/langflow#1529]
Conversations made in the Langflow UI are normally recorded in Langfuse, but if you call and operate the API, no logs are created in Langfuse. Does that feature exist? If not, how do I make it?

**Comment by songjinu** [comment]
We can not use the langfuse when call API (/process) ?

**Comment by yamonkjd** [comment]
> We can not use the langfuse when call API (/process) ? 
> 

네 아직 안돼여...
