### ISSUE TITLE
pip always encounters failures when installing LangFlow       

### ISSUE THREAD

**Issue by MeyerOlanduil** [langflow-ai/langflow#1530]
###  **pip always encounters failures when installing LangFlow**

I followed the code on the docs and typed pip install langflow into my windows command line tool, but I always got the following error. Have tried to reinstall several times and still haven't succeeded. The error screen is as follows:  

**Browser and Version**
 - Microsoft Edge, version 122.0.2365.80 (GA) (64-bit)
 - Python 3.12.2
 - Windows10

![image](https://github.com/logspace-ai/langflow/assets/162543658/fe5b0059-d1a9-4e79-ba28-94bcd3e43ca0)

**Comment by jimmcnulty41** [comment]
Try downgrading the python 

using [pyenv](https://github.com/pyenv/pyenv) or [pyenv-win on windows](https://github.com/pyenv-win/pyenv-win):
```
pyenv install 3.11.7
pyenv global 3.11.7
```

**Comment by anwarwin** [comment]
I had the same problem then I had to update my python and install rust (as also precise by the error code you have). Most probably it is a problem of environment configuration. Hopefully now I made a small step forward . But pyproject.tom1 is still not running successfully.
Here I am  now (image attached) but I start thinking that the version of python 3.12.2 is maybe the reason behind the failure. I will downgrade it and see.
![image](https://github.com/logspace-ai/langflow/assets/164271046/6613ca2f-a0d2-4f9e-90b4-0532ae8ed8a3)

**Comment by onurusluca** [comment]
@anwarwin How did it go? Did downgrading help? I am having the same problem.

**Comment by sarang-lvs** [comment]
Same problem, this Langflow pip installation is riddled with so many errors. This is just one of them:
![image](https://github.com/langflow-ai/langflow/assets/101888805/7a476593-478c-4e9a-b93c-33a3f8b9e04b)

I do have a Visual Studio 2022 installed btw, not sure why it is looking for VS2015!

Here is the final one:
![image](https://github.com/langflow-ai/langflow/assets/101888805/51864b98-0434-4702-9ee8-aad217c7ab68)

**Comment by SatyakiDe2019** [comment]
I'm facing issues with the following error even after successful installation on my Macbook - 

ModuleNotFoundError: No module named 'langflow.schema'

Mac OS - Soroma
RAM - 64 GB
Intel Graphics

My Python version is - 3.10.6

**Comment by anovazzi1** [comment]
Hello,
Sorry for the delay. Did you try using the new version? Does the error still persist?

**Comment by carlosrcoelho** [comment]
Hi @MeyerOlanduil  , 

We hope you're doing well. Just a friendly reminder that if we do not hear back from you within the next 3 days, we will close this issue. If you need more time or further assistance, please let us know. 

Thank you for your understanding!

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.

**Comment by MoonHawlk** [comment]
Just to clarify, i was having the same issue. 

I've tried use pipx instead, however, what works for my was installing:

1- pip install uv

and then:

2- uv pip install langflow

**Comment by caduguimaraes** [comment]
> Just to clarify, i was having the same issue.
> 
> I've tried use pipx instead, however, what works for my was installing:
> 
> 1- pip install uv
> 
> and then:
> 
> 2- uv pip install langflow

Thanks, works for me after trying PIP for a week.

**Comment by malinovskymax** [comment]
Still getting

>   × Failed to build `tiktoken==0.7.0`
>   ├─▶ The build backend returned an error
>   ╰─▶ Call to `setuptools.build_meta.build_wheel` failed (exit status: 1)
> 
>       [stdout]
>       running bdist_wheel
>       running build
>       running build_py
>       copying tiktoken/registry.py ->
>       build/lib.macosx-15.0-arm64-cpython-313/tiktoken
>       copying tiktoken/__init__.py ->
>       build/lib.macosx-15.0-arm64-cpython-313/tiktoken
>       copying tiktoken/core.py ->
>       build/lib.macosx-15.0-arm64-cpython-313/tiktoken
>       copying tiktoken/model.py ->
>       build/lib.macosx-15.0-arm64-cpython-313/tiktoken
>       copying tiktoken/load.py ->
>       build/lib.macosx-15.0-arm64-cpython-313/tiktoken
>       copying tiktoken/_educational.py ->
>       build/lib.macosx-15.0-arm64-cpython-313/tiktoken
>       copying tiktoken_ext/openai_public.py ->
>       build/lib.macosx-15.0-arm64-cpython-313/tiktoken_ext
>       running egg_info
>       writing tiktoken.egg-info/PKG-INFO
>       writing dependency_links to tiktoken.egg-info/dependency_links.txt
>       writing requirements to tiktoken.egg-info/requires.txt
>       writing top-level names to tiktoken.egg-info/top_level.txt
>       reading manifest file 'tiktoken.egg-info/SOURCES.txt'
>       reading manifest template 'MANIFEST.in'
>       adding license file 'LICENSE'
>       writing manifest file 'tiktoken.egg-info/SOURCES.txt'
>       copying tiktoken/py.typed ->
>       build/lib.macosx-15.0-arm64-cpython-313/tiktoken
>       running build_ext
>       running build_rust
> 
>       [stderr]
>       warning: no files found matching 'Makefile'
>       error: can't find Rust compiler

when running
`uv pip install langflow`

**Comment by Buddhilive** [comment]
> Just to clarify, i was having the same issue.
> 
> I've tried use pipx instead, however, what works for my was installing:
> 
> 1- pip install uv
> 
> and then:
> 
> 2- uv pip install langflow

This works like a magic. Using uv is recommended after all

**Comment by mariia-osipova** [comment]
> > Just to clarify, i was having the same issue.
> > I've tried use pipx instead, however, what works for my was installing:
> > 1- pip install uv
> > and then:
> > 2- uv pip install langflow
> 
> Thanks, works for me after trying PIP for a week.

thank you, works perfect!
