### ISSUE TITLE
 请问我们以本地源码方式启动，有相关说明文档？

### ISSUE THREAD

**Issue by huangbz2007** [langflow-ai/langflow#1556]
请问我们以本地源码方式启动，有相关说明文档？

**Comment by anovazzi1** [comment]
您好，
请查看 https://pre-release.langflow.org/ 上的文档。

**Comment by linfey90** [comment]
> 您好， 请查看 https://pre-release.langflow.org/ 上的文档。
But I'm getting a 404 error on this address, do you have any other local debugging documentation?
