### ISSUE TITLE
[Bug] Railway deployment failed

### ISSUE THREAD

**Issue by Decikingship** [langflow-ai/langflow#1558]
Description
Just click on the "Deploy on Railway" button in repo's frontpage and get a deployment error on Railway

**Screenshots**
![image](https://github.com/logspace-ai/langflow/assets/29721376/3e73efc5-cf17-40df-a397-a30193e93229)

**Additional context**
Have tried several times on different account, but all ends up failed

**Comment by anovazzi1** [comment]
Hello,
Sorry for the delay. Did you try using the new version? Does the error still persist?

**Comment by DazzlerLabs** [comment]
It persist on version v1.1 @anovazzi1 
![Screenshot 2024-11-18 at 13 01 17](https://github.com/user-attachments/assets/5c8cd3cd-eaf0-4e22-b4f8-c61a2caede24)
