### ISSUE TITLE
Prompt template not being saved

### ISSUE THREAD

**Issue by jaschahuisman** [langflow-ai/langflow#1561]
**Describe the bug**
When filling in the prompt template and pressing the `Check & Save` and then `Save Changes` button, it is not being saved well. When trying to adjust it later, all the values are gone from the field, even though the variables remain visible in the node.

**Browser and Version**
 - [Chrome 122 on macOS (Sonoma)](https://www.whatismybrowser.com/detect/what-version-of-chrome-do-i-have)

**To Reproduce**
1. Open http://localhost:7860/
2. Create flow
2. Drag and drop `PromptTemplate` node into view
3. Edit the `template` param of `PromptTemplate` with variables enclosed in curly braces.
4. Press `Check & Save`
5. Press `Save Changes`
6. Again, open the the `template` param of `PromptTemplate` in the edit menu
7. Initial template is gone... 💨 

**Screenshots**

https://github.com/logspace-ai/langflow/assets/39152972/0d817f79-3855-480d-893e-3cc6c595a7f6

**Comment by anovazzi1** [comment]
Hello,
Sorry for the delay. Did you try using the new version? Does the error still persist?

**Comment by jxz345** [comment]
I started playing with LangFlow recently. My current installation is 1.0.5 on localhost.

I also have the problem of not being able to save the prompt template. I could save the change in very occasions, and I haven't found a pattern yet. 

https://github.com/langflow-ai/langflow/assets/49407364/f165f36f-a7bf-4084-9136-401a939666e0

**Comment by jxz345** [comment]
I deployed langflow to railway, by clicking the button on the github readme page. Still got the same error.

**Comment by mnanjana2020** [comment]
Same here. After check/save, run the component and it errors out without saving the variables. 

[07/02/24 07:25:26] ERROR    2024-07-02 07:25:26 - ERROR    - base - base.py:627
                             expected str, got NoneType                         
                             Traceback (most recent call last):

**Comment by anovazzi1** [comment]
@jxz345 @jaschahuisman @mnanjana2020 
Thanks for the feedback! I'll take a look and fix it ASAP.
