### ISSUE TITLE
后端错误

### ISSUE THREAD

**Issue by huangbz2007** [langflow-ai/langflow#1574]
ERROR    2024-03-27 14:36:00 - ERROR    - directory_reader - Error while loading component: 400: {'error': 'Invalid type convertion. Please check your code and try     directory_reader.py:79
                             again.', 'traceback': 'Traceback (most recent call last):\n  File "/Users/space/work/langflow-main/src/backend/langflow/interface/custom/utils.py", line 311,                        
                             in build_custom_component_template\n    add_base_classes(frontend_node, custom_component.get_function_entrypoint_return_type)\n  File                                                
                             "/Users/space/work/langflow-main/src/backend/langflow/interface/custom/utils.py", line 75, in add_base_classes\n    base_classes =                                                   
                             get_base_classes(return_type_instance)\n  File "/Users/space/work/langflow-main/src/backend/langflow/utils/util.py", line 189, in get_base_classes\n    result                       
                             = \n  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/typing.py", line 701, in __getattr__\n                               
                             raise AttributeError(attr)\nAttributeError: __name__\n'}

**Comment by anovazzi1** [comment]
你好，
抱歉回复晚了。你试过使用新版本吗？错误还存在吗？
