### ISSUE TITLE
How do i add new components into the sidebar?

### ISSUE THREAD

**Issue by Warit314** [langflow-ai/langflow#1575]
Hi, i'm using one of my custom component a lot. and i'm tired of having to copy the components every time. So, Do you guys know how i add my own custom components into the side bar?

**Comment by Warit314** [comment]
Where is the COMPONENTS_PATH?

**Comment by ayubSubhaniya** [comment]
Are there any plans to make adding new type of agent/document loader etc config driven without doing code change? I was just thinking if this could be driven by config.yaml entirely

**Comment by anovazzi1** [comment]
You can save your components and access them from the saved components sidebar. We are working to expand this feature in the future.

**Comment by mohammadshahmeer024** [comment]
Please let me know how can i have my custom component in the sidebar of langflow? i have cloned the repo and its running locally using docker compose.
