### ISSUE TITLE
Error Occurring When Uploading PDF Files with 'directoryloader'

### ISSUE THREAD

**Issue by peterjacksonwonka** [langflow-ai/langflow#1577]
I am using the 'directoryloader' component in a flow, and when I try to upload a PDF file, I encounter an error. 

error message: partition_pdf is not available. Install the pdf dependencies with pip install "unstructured[pdf]

My version of 'unstructured' is 0.12.0. 
Langflow version is 0.6.7.
Out of curiosity, I downgraded to version 0.7.12, and while that specific error did not occur, the 'emoji' was deleted from my poetry.lock file. 
Consequently, when I attempt to start the server, it fails to start, and I get another error. 

ModuleNotFoundError: No module named 'emoji'

Therefore, it seems that downgrading the 'unstructured' version is not going to work. 
Is there another possible solution?

**Comment by peterjacksonwonka** [comment]
Is there no other way besides downgrading the 'unstructured' version? If I downgrade, not only 'emoji' but also many other changes occur in the poetry.lock file.

**Comment by peterjacksonwonka** [comment]
@dusubot Is there no other way besides downgrading the 'unstructured' version? If I downgrade, not only 'emoji' but also many other changes occur in the poetry.lock file.

**Comment by anovazzi1** [comment]
Hello,
Sorry for the delay. Did you try using the new version? Does the error still persist?

**Comment by carlosrcoelho** [comment]
Hi @peterjacksonwonka,

We hope you're doing well. Just a friendly reminder that if we do not hear back from you within the next 3 days, we will close this issue. If you need more time or further assistance, please let us know. 

Thank you for your understanding!

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
