### ISSUE TITLE
NLTK Error Occurring During Upload with 'directoryloader'

### ISSUE THREAD

**Issue by peterjacksonwonka** [langflow-ai/langflow#1578]
I am using the 'directoryloader' component in a flow, and I encounter an error whenever I attempt to upload. 
I have two questions. 
First, my NLTK version is 3.8.1. NLTK seems to be properly installed, but it appears I need to download additional data. 
Locally, the issue can be resolved by manually downloading the data. 
However, we are operating a server that will be used by many users. 
Is there a way to automatically download the required NLTK data during the Docker build process on the server? 
Can we include the download command in the pyproject.toml or Dockerfile? 

Second, is it necessary to both install NLTK and download additional data? 
Could there be a solution involving encoding or something similar during the upload process that might resolve this? 
Are there any other possible solutions?

**Comment by peterjacksonwonka** [comment]
How do I then apply this to the 'directoryloader' source code?

**Comment by peterjacksonwonka** [comment]
@dosubot How do I then apply this to the 'directoryloader' source code?
can I include the NLTK download command in the pyproject.toml file?

**Comment by anovazzi1** [comment]
Hello,
Sorry for the delay. Did you try using the new version? Does the error still persist?

**Comment by carlosrcoelho** [comment]
Hi @peterjacksonwonka 

We hope you're doing well. Just a friendly reminder that if we do not hear back from you within the next 3 days, we will close this issue. If you need more time or further assistance, please let us know. 

Thank you for your understanding!

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
