### ISSUE TITLE
ModuleNotFoundError: Module component.llms.kimi_llm not found

### ISSUE THREAD

**Issue by xianming90** [langflow-ai/langflow#1586]
**Describe the bug**
when i run my project , notice  """
  exec_globals = prepare_global_scope(code, module)\n  File                                                        
   "/home/xm/workspace/python/mflow/venv/lib/python3.10/site-packages/langflow/utils/validate.py", line 204, in                       
   prepare_global_scope\n    raise ModuleNotFoundError(f"Module {node.module} not found. Please install it and                        
   try again.") from e\nModuleNotFoundError: Module component.llms.kimi_llm not found. Please install it and                          
   try again.\n'}                          
"""

**Screenshots**
my project source strure

![image](https://github.com/logspace-ai/langflow/assets/2024998/ba6b166f-3b55-4821-8257-8232742fd6cb)

**Comment by xianming90** [comment]
使用包的方式引入langflow,然后启动项目，会找不到自定义的包。

**Comment by xianming90** [comment]
还没解决我的问题。

自定义包，还是无法加载。

**Comment by xianming90** [comment]
还没解决我的问题。

自定义包，还是无法加载。

**Comment by anovazzi1** [comment]
你好，
抱歉回复晚了。你试过使用新版本吗？错误还存在吗？

**Comment by carlosrcoelho** [comment]
Hi @xianming90 

We hope you're doing well. Just a friendly reminder that if we do not hear back from you within the next 3 days, we will close this issue. If you need more time or further assistance, please let us know. 

Thank you for your understanding!

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
