### ISSUE TITLE
Postgres migration error 

### ISSUE THREAD

**Issue by tejeshbhalla** [langflow-ai/langflow#1607]
**Describe the bug**
While setting up langflow locally on postgres i get error

`postgres-1  | 2024-04-04 17:09:20.050 UTC [69] ERROR:  duplicate key value violates unique constraint "ix_user_username"
postgres-1  | 2024-04-04 17:09:20.050 UTC [69] DETAIL:  Key (username)=(superuser) already exists.
postgres-1  | 2024-04-04 17:09:20.050 UTC [69] STATEMENT:  INSERT INTO "user" (id, username, password, profile_image, is_active, is_superuser, create_at, updated_at, last_login_at, store_api_key) VALUES ('d81401a3-4798-4f99-a30e-a01f678e7e75'::UUID, 'superuser', '$2b$12$0FNtcrd.0c70wZPXWu3Bdux1Tk82k07.gRd2Yfbq8zZcLIqYrZm92', NULL, true, true, '2024-04-04T17:09:20.048501'::timestamp, '2024-04-04T17:09:20.048504'::timestamp, NULL, NULL)
langflow-1  | No new upgrade operations detected.
langflow-1  | No new upgrade operations detected.
langflow-1  | [04/04/24 17:09:20] INFO     2024-04-04 17:09:20 - INFO     - utils  utils.py:84
langflow-1  |                              - LLM caching setup with SQLiteCache               
postgres-1  | 2024-04-04 17:09:20.076 UTC [70] ERROR:  duplicate key value violates unique constraint "ix_user_username"
postgres-1  | 2024-04-04 17:09:20.076 UTC [70] DETAIL:  Key (username)=(superuser) already exists.
postgres-1  | 2024-04-04 17:09:20.076 UTC [70] STATEMENT:  INSERT INTO "user" (id, username, password, profile_image, is_active, is_superuser, create_at, updated_at, last_login_at, store_api_key) VALUES ('7060f313-41da-4342-8149-b1b74bd5898a'::UUID, 'superuser', '$2b$12$CT1Bov9kd3MF/W6V55EbBeY.oDYyt8UxSIKmG8GCOvFkcUBAB7UP2', NULL, true, true, '2024-04-04T17:09:20.074609'::timestamp, '2024-04-04T17:09:20.074612'::timestamp, NULL, NULL)
langflow-1  | No new upgrade operations detected.`

**Screenshots**

**Additional context**

**Comment by anovazzi1** [comment]
Hello,
Sorry for the delay. Did you try using the new version? Does the error still persist?

**Comment by carlosrcoelho** [comment]
Hi @tejeshbhalla 

We hope you're doing well. Just a friendly reminder that if we do not hear back from you within the next 3 days, we will close this issue. If you need more time or further assistance, please let us know. 

Thank you for your understanding!

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
