### ISSUE TITLE
Custom component is not working in the Langflow 1.0 preview

### ISSUE THREAD

**Issue by oyasizaki** [langflow-ai/langflow#1637]
![image](https://github.com/logspace-ai/langflow/assets/118342512/e8f79914-a476-41af-88c1-c16f056572fe)
Is the Custom component option totally removed from the new version of langflow cause i neither found the custom node or could use it via save nodes?

**Comment by Alperemrehas** [comment]
I think it is working fine and exists. Can you decribe your issue with more detail to replicate it? Thank you.

**Comment by oyasizaki** [comment]
thank you for your response.
I mean the custom component like 
![image](https://github.com/logspace-ai/langflow/assets/118342512/da3b1c8c-edbc-4b5c-8d3d-bb2a6ac99241)
this one 
not the 
![image](https://github.com/logspace-ai/langflow/assets/118342512/da52f773-b80f-4f3e-b896-ba90425bb167)

in the new version
![image](https://github.com/logspace-ai/langflow/assets/118342512/e8ebb6fc-1a30-4d1a-9ad2-c36a3c94e34e)
as you can see the custom section is not available 
where as in the old version 0.6.12
![image](https://github.com/logspace-ai/langflow/assets/118342512/6aec9c25-4674-4dd0-a4e9-e69b69e49bf1)
it was there

**Comment by ogabrielluiz** [comment]
Hey all!
As @Alperemrehas wrote, it now is in the Helpers category. 

What happened for that error to appear? Did you try using a saved component and you encountered that error?

**Comment by Alperemrehas** [comment]
> thank you for your response.
> 
> I mean the custom component like ![image](https://private-user-images.githubusercontent.com/118342512/320537810-da3b1c8c-edbc-4b5c-8d3d-bb2a6ac99241.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1OTQ3NDksIm5iZiI6MTcxMjU5NDQ0OSwicGF0aCI6Ii8xMTgzNDI1MTIvMzIwNTM3ODEwLWRhM2IxYzhjLWVkYmMtNGI1Yy04ZDNkLWJiMmE2YWM5OTI0MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOFQxNjQwNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYjEzZTk5YWMyMDA4YjEyMjg4ZWQ0YmIyMDM2ODY5ODJmNTZjM2ZkMDk4NDZlZDg1YTcyODU2MTU1ZjZmMDgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AtFNbt3C825TE_-m45v6VTlCyYKDYu-pFg3jn9j_KJ8) this one
> 
> not the ![image](https://private-user-images.githubusercontent.com/118342512/320537944-da52f773-b80f-4f3e-b896-ba90425bb167.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1OTQ3NDksIm5iZiI6MTcxMjU5NDQ0OSwicGF0aCI6Ii8xMTgzNDI1MTIvMzIwNTM3OTQ0LWRhNTJmNzczLWI4MGYtNGYzZS1iODk2LWJhOTA0MjViYjE2Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOFQxNjQwNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYzViMzU3ODE0MzAzMzE2NmViZjcyZGJmYzk3M2Y1Y2U0YjJlNzk3NzNlMGJlNzNiYmI5YTY1ZjRmMmM1NTc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EFEhgX9xdEdLrXxIYl_6-sA8rBP5eGP4qmPEPVBN240)
> 
> in the new version ![image](https://private-user-images.githubusercontent.com/118342512/320538188-e8ebb6fc-1a30-4d1a-9ad2-c36a3c94e34e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1OTQ3NDksIm5iZiI6MTcxMjU5NDQ0OSwicGF0aCI6Ii8xMTgzNDI1MTIvMzIwNTM4MTg4LWU4ZWJiNmZjLTFhMzAtNGQxYS05YWQyLWMzNmEzYzk0ZTM0ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOFQxNjQwNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYzRhZmM4YWZjMDQ5OWE3ODI3N2RjM2MwOTA1NzMxMmExZmJhNzM1NzhmYjI1Njg0ODk4NjU5M2Q1MmNlNzYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LsW8imseqqGzRcaAJCUsSpyc253SMEcW03QNvSGX7ho) as you can see the custom section is not available where as in the old version 0.6.12 ![image](https://private-user-images.githubusercontent.com/118342512/320538519-6aec9c25-4674-4dd0-a4e9-e69b69e49bf1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1OTQ3NDksIm5iZiI6MTcxMjU5NDQ0OSwicGF0aCI6Ii8xMTgzNDI1MTIvMzIwNTM4NTE5LTZhZWM5YzI1LTQ2NzQtNGRkMC1hNGU5LWU2OWI2OWU0OWJmMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOFQxNjQwNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDhjNjhjYjFmYzgwOTM1ZGU3MzA5YzQxMDAzODA3NjA2MDMyMmE1NWVjMGU3Y2IwOWM4MDFlNTQ1YWY2OWYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vpvKlcmmb2sqD0q9NMaP-51F6T-EGTKqu-0Ei3PylhA) it was there
> 
> I am looking for it because i have some custom node which i created but cannot use them in the new version (lanflow 1.0) anymore.

Thank you for your respond, as you can see the image below the sidebar and sturcture has been changed. So it is natural not to find it under same sturucture but the custom component exist. I n order to use as it was. You can drag and drop the customcomponent and click on the <> symbol and create your own component. Later on you can easily save the component for further usage. 

![custom_component](https://github.com/logspace-ai/langflow/assets/37380232/544bb803-4244-4b91-9c96-28332ac794f2)

**Comment by oyasizaki** [comment]
Sorry if i am overlooking something
but where do i put my code? 
there seems to be no section for it.
![image](https://github.com/logspace-ai/langflow/assets/118342512/07df1305-125a-4457-ad8b-d1fd4f29716a)
where as i could put it in the code section
![image](https://github.com/logspace-ai/langflow/assets/118342512/f795aacd-37e9-4953-9547-03fb1c355817)

**Comment by oyasizaki** [comment]
> Hey all! As @Alperemrehas wrote, it now is in the Helpers category.
> 
> What happened for that error to appear? Did you try using a saved component and you encountered that error?

i just drag and dropped the saved custom node in the flow pane section
it occurs for all of my previous saved custom components

**Comment by oyasizaki** [comment]
To generate the error you can try drag and drop the custom node from the saved section into the flow pane 
![image](https://github.com/logspace-ai/langflow/assets/118342512/9fa6a1a3-6a02-474f-9110-aa7e8aee6982)
The second one 
![image](https://github.com/logspace-ai/langflow/assets/118342512/dd831b9d-43bd-4222-99b6-f74f05bd1e8a)

**Comment by Alperemrehas** [comment]
Actually what I see from your sharing you are going with the saved ones. So maybe clear the issue. Can you type Custom Component and drag and drop the one under "Helpers". Later on as I mentioned in my previous answer just click on the card there will appear a small tab on the card. On the left hand side there exist a button as "<>". Click on that and you can use your code to create your custom component. 
1. 
![1](https://github.com/logspace-ai/langflow/assets/37380232/38f018f6-c5ac-4f46-944f-b3c25c782707)
2.
![2](https://github.com/logspace-ai/langflow/assets/37380232/e0d6d1c2-b3c3-4d89-b9b0-eaaed7a03a34)
3.
![3](https://github.com/logspace-ai/langflow/assets/37380232/35f3ff28-042d-4bf6-b666-55fc594dc9ce)

**Comment by oyasizaki** [comment]
Thank you very much for explaining it
