### ISSUE TITLE
Connection to OpenAI API failed, is VPN proxy supported for setting?

### ISSUE THREAD

**Issue by uamyangel** [langflow-ai/langflow#1660]
When I am building a workflow and using OpenAI, it prompts that the connection to the OpenAI API failed. I understand that my network needs to use a VPN proxy. Where can I configure the proxy?

**Comment by carlosrcoelho** [comment]
Hi @uamyangel 

We hope you're doing well. Just a friendly reminder that if we do not hear back from you within the next 3 days, we will close this issue. If you need more time or further assistance, please let us know. 

Thank you for your understanding!

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
