### ISSUE TITLE
Installing pre-release and running langflow command produces error

### ISSUE THREAD

**Issue by radiantone** [langflow-ai/langflow#1663]
**Describe the bug**
Following the README and installing the pre-release, then trying to run the langflow command suggested in the README also produces an error

```bash
$ langflow
Traceback (most recent call last):
  File "...snipped.../venv/bin/langflow", line 5, in <module>
    from langflow.__main__ import main
ModuleNotFoundError: No module named 'langflow.__main__'
```

**Browser and Version**

**To Reproduce**

**Screenshots**

**Additional context**

**Comment by dongdaoguang** [comment]
+1

**Comment by FlorianMgs** [comment]
+1

**Comment by anovazzi1** [comment]
Hello,
Sorry for the delay. Did you try using the new version? Does the error still persist?

**Comment by carlosrcoelho** [comment]
Hi @radiantone 

We hope you're doing well. Just a friendly reminder that if we do not hear back from you within the next 3 days, we will close this issue. If you need more time or further assistance, please let us know. 

Thank you for your understanding!

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
