### ISSUE TITLE
Unable to use AstraDB VectorStore with Async Mode in a RetreivalQAChain

### ISSUE THREAD

**Issue by mukundha** [langflow-ai/langflow#1665]
**Describe the bug**
When trying to Use RetrievalQA Chain with AstraDB Vector Store, seeing the following error during the build of RetrievalQA chain (attached the export of the flow)
`
Error building vertex Retrieval QA: Asynchronous setup of the DB not finished. NB: AstraDB components sync methods shouldn't be called from the event loop. Consider using their async equivalents.
`

[RetrievalQA with Astra.json](https://github.com/langflow-ai/langflow/files/14932540/RetrievalQA.with.Astra.json)

**Browser and Version**
 - Browser: Chrome
 - Version: 123

**To Reproduce**
1. Import the attached flow or you can try to use RetreivalQA chain with AstraDB Vector store (add credentials as necessary)
2. Click on 'Run'
3. See error

**Screenshots**
<img width="1303" alt="Screenshot 2024-04-10 at 9 14 44 PM" src="https://github.com/langflow-ai/langflow/assets/1277515/9be24aca-10a0-47bc-80f7-25b75bb7f5d6">

**Additional context**
- I tried to create a custom component with the same code, except modify [here](https://github.com/langflow-ai/langflow/blob/dev/src/backend/base/langflow/components/chains/RetrievalQA.py#L56) to use async / await. It seemed to work, but need to confirm if it doesn't break anything else. Changes are highlighted in bold

```
    **async def build**(
        self,
        llm: BaseLanguageModel,
       ... <omitted >
    ) -> Text:
        chain_type = chain_type.lower().replace(" ", "_")
        runnable = RetrievalQA.from_chain_type(
            llm=llm,
            chain_type=chain_type,
            retriever=retriever,
            memory=memory,
            input_key=input_key,
            output_key=output_key,
            return_source_documents=return_source_documents,
        )
      ... <omitted>
        result = **runnable.ainvoke**({input_key: input_value})
```

**Comment by ogabrielluiz** [comment]
Hey @mukundha ! 

How are you? 

The Astra DB component has a setting to make it async. You can find it in the advanced parameters.
<img width="1053" alt="image" src="https://github.com/langflow-ai/langflow/assets/24829397/c379b153-2719-4de0-9ca1-1ac71e274d4e">


Either way, I'll give this a shot to see if I can find anything.

**Comment by mukundha** [comment]
Yep, I saw that.. the default is Async, so thats good. But I think the problem is with the RetrievalQA chain .. it uses sync method `invoke`

**Comment by mukundha** [comment]
thanks @ogabrielluiz, also for clarity, the issue is only with the default settings
for eg,
- AstraDB Vector store's default `Setup Mode` is `Async`, but RetrievalQA chain uses sync method `invoke` to run the chain. For this case, I need to update the code to use `ainvoke`

- If I configure AstraDB Vector store's `Setup Mode` to `Sync`, RetrievalQA works with default config

looks like `Setup Mode` is also AstraDB specific, I did not find this config for other vectorstores (shouldn't all have a async mode?)

**Comment by ogabrielluiz** [comment]
It is. I'll update it to use Sync Mode, for now. We can update that later on if that's not a good default.
