### ISSUE TITLE
Cannot use LLMChain. No compatible components found.

### ISSUE THREAD

**Issue by huu3301** [langflow-ai/langflow#1675]
**Describe the bug**
Cannot use LLMChain, cannot find prompt component.

**Browser and Version**
 - Browser chrome
 - Version 123.0.6312.106
 - langflow version: v0.6.15

**To Reproduce**
1. Create LLMChain
2. Prompt: No compatible components found.

**Screenshots**
![1](https://github.com/langflow-ai/langflow/assets/44219645/83febf7f-b4a6-49d3-ab4b-89768114bbeb)

**Comment by ogabrielluiz** [comment]
Hey @huu3301 

How are you?

Thanks for catching that! Are you sure you are running version 0.6.15? This seems like an alpha component.

**Comment by huu3301** [comment]
@ogabrielluiz 
I'm not sure whether the version is v0.6.15. I used the command "git pull origin dev" yesterday and found this issue.
