### ISSUE TITLE
the same flow run well in web page ,but not use api (branch ：dev)

### ISSUE THREAD

**Issue by xianming90** [langflow-ai/langflow#1677]
the same flow run well in web page ,but not use api。

**run in  web page:**

![屏幕截图 2024-04-11 143249](https://github.com/langflow-ai/langflow/assets/2024998/dff1ba11-2496-4323-9c95-788947ccfedc)

**run with api**
![屏幕截图 2024-04-11 143433](https://github.com/langflow-ai/langflow/assets/2024998/895dce51-12d1-4786-86f7-394cd8b17961)

![屏幕截图 2024-04-11 143540](https://github.com/langflow-ai/langflow/assets/2024998/bfde4047-d300-4818-b1a2-49c00810171b)

the same way test other flow , the same poplem.

**Comment by xianming90** [comment]
have sameone has the same proplem?

**Comment by anovazzi1** [comment]
Hello,
Sorry for the delay. Did you try using the new version? Does the error still persist?

**Comment by carlosrcoelho** [comment]
Hi @xianming90 

We hope you're doing well. Just a friendly reminder that if we do not hear back from you within the next 3 days, we will close this issue. If you need more time or further assistance, please let us know. 

Thank you for your understanding!

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
