### ISSUE TITLE
The app would not start

### ISSUE THREAD

**Issue by legaltextai** [langflow-ai/langflow#1681]
I keep getting this error and the app would not start. The circle would just go round and round. 
And I keep refreshing the page 

<img width="445" alt="Screenshot 2024-04-11 at 11 24 12 AM" src="https://github.com/langflow-ai/langflow/assets/144342123/62c9d567-e2b9-4300-a760-ea073a474215">

Ubuntu server 
Thanks!

**Comment by anovazzi1** [comment]
Hello,
Sorry for the delay. Did you try using the new version? Does the error still persist?

**Comment by carlosrcoelho** [comment]
Hi @legaltextai 

We hope you're doing well. Just a friendly reminder that if we do not hear back from you within the next 3 days, we will close this issue. If you need more time or further assistance, please let us know. 

Thank you for your understanding!
