### ISSUE TITLE
FR: remove runtime pypi requests, respect pip config

### ISSUE THREAD

**Issue by joshua-auchincloss** [langflow-ai/langflow#1685]
Noting in [__main__](https://github.com/langflow-ai/langflow/blob/dev/src/backend/base/langflow/__main__.py) that the app is fetching data from pypi... why though?

Some concerns with this, summarized below:
- Pip configuration & private indices are ignored
- Clients are not guaranteed internet connections at startup
- Hints at uncontrolled dependencies (even though we have `pyproject.toml`)

Imo arguably inappropriate to run `pip install` at server startup... At a min, there should be an option to disable the feature altogether or use an already installed version since the handling mechanism doesn't respect system level configurations (pip).

**Comment by ogabrielluiz** [comment]
Hey @joshua-auchincloss 
How are you? 

This happens only to check if there's a new version and build the banner when initializing Langflow.

**Comment by joshua-auchincloss** [comment]
> Hey @joshua-auchincloss 
> How are you? 
> 
> This happens only to check if there's a new version and build the banner when initializing Langflow.

hey @ogabrielluiz - great! how are you?

noted - i think the main concern is that in a securitized networking environment, langflow will not have access to main pypi instances to even check for a new version (much less update itself). imo, pip should be used to update the application as there may be e.g private indices / mirrors used which the app disregards

**Comment by vikiscience** [comment]
Hi All, any update on this issue? 
I'm trying to run Langflow in an environment with egress lockdown, and the container fails to start, due to the issue above. Is there any way to switch off these PYPI requests?
