### ISSUE TITLE
class 'NoneType' error for RetrievalQA

### ISSUE THREAD

**Issue by huu3301** [langflow-ai/langflow#1687]
**Describe the bug**
When I closed the button of "Return source Documents" on RetrievalQA component, the flow was successful but it raised error.

**Browser and Version**
 - Browser: chrome
 - Version: 123.0.6312.106
 - langflow version: the latest version of dev branch in github (probably v1.0.0a12 version)

**To Reproduce**
1. Create components: TextLoader -> Recursive Character Text splitter -> OpenAI Embeddings -> FAISS
2. Create components: Chat Input -> Prompt
3. Create components: ChatOpenAI -> RetrievalQA -> Chat Output
4. Close the button of "Return Source Documents" on RetrievalQA

**Screenshots**
When I opened the button of "Return source Documents", the flow was successful and I got the result.

![2](https://github.com/langflow-ai/langflow/assets/44219645/64e42ecb-b894-4906-9afb-121e9f1633c8)

But if I closed this button, it raised error:
Error building vertex Retrieval QA: Invalid data type: <class 'NoneType'>.

![3](https://github.com/langflow-ai/langflow/assets/44219645/dd171be6-5e72-4349-a1ec-9f9eb9fc8d97)

**Comment by huu3301** [comment]
I know where is the bug:
In RetrievalQA.py, if return_source_documents is false, the result.get("source_documents") is None, this causes a bug in self.to_records function.
![image](https://github.com/langflow-ai/langflow/assets/44219645/82ddd4af-c1ab-4d05-be95-2c2796886509)

**Comment by anovazzi1** [comment]
Hello,
Sorry for the delay. Did you try using the new version? Does the error still persist?

**Comment by carlosrcoelho** [comment]
Hi @huu3301 

We hope you're doing well. Just a friendly reminder that if we do not hear back from you within the next 3 days, we will close this issue. If you need more time or further assistance, please let us know. 

Thank you for your understanding!

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
