### ISSUE TITLE
LangFlow 0.6.15 - UI Fails to Load

### ISSUE THREAD

**Issue by taylor-schneider** [langflow-ai/langflow#1692]
**Describe the bug**
I am installing langflow 0.6.15 on a clean environment. The application successfully starts as shown here:

```
(langflow-3.10) [root@fedora ~]# langflow run --host 0.0.0.0
╭───────────────────────────────────────────────────╮
│ Welcome to ⛓ Langflow                             │
│                                                   │
│ Access http://0.0.0.0:7860                        │
│ Collaborate, and contribute at our GitHub Repo 🚀 │
╰───────────────────────────────────────────────────╯
[2024-04-12 14:04:51 -0500] [3249871] [INFO] Starting gunicorn 21.2.0
[2024-04-12 14:04:51 -0500] [3249871] [INFO] Listening at: http://0.0.0.0:7860 (3249871)
[2024-04-12 14:04:51 -0500] [3249871] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2024-04-12 14:04:51 -0500] [3249910] [INFO] Booting worker with pid: 3249910
[2024-04-12 14:04:51 -0500] [3249910] [INFO] Started server process [3249910]
[2024-04-12 14:04:51 -0500] [3249910] [INFO] Waiting for application startup.
[04/12/24 14:04:51] INFO     2024-04-12 14:04:51 - INFO     - service - Alembic already          service.py:142
                             initialized
                    INFO     2024-04-12 14:04:51 - INFO     - service - Running DB migrations in service.py:150
                             /root/miniconda3/envs/langflow-3.10/lib/python3.10/site-packages/la
                             ngflow/alembic
/root/miniconda3/envs/langflow-3.10/lib/python3.10/site-packages/langflow/alembic/env.py:82: SAWarning: WARNING: SQL-parsed foreign key constraint '('user_id', 'user', 'id')' could not be located in PRAGMA foreign_keys for table credential
  context.run_migrations()
/root/miniconda3/envs/langflow-3.10/lib/python3.10/site-packages/langflow/alembic/env.py:82: SAWarning: WARNING: SQL-parsed foreign key constraint '('user_id', 'user', 'id')' could not be located in PRAGMA foreign_keys for table flow
  context.run_migrations()
No new upgrade operations detected.
/root/miniconda3/envs/langflow-3.10/lib/python3.10/site-packages/langflow/alembic/env.py:82: SAWarning: WARNING: SQL-parsed foreign key constraint '('user_id', 'user', 'id')' could not be located in PRAGMA foreign_keys for table credential
  context.run_migrations()
/root/miniconda3/envs/langflow-3.10/lib/python3.10/site-packages/langflow/alembic/env.py:82: SAWarning: WARNING: SQL-parsed foreign key constraint '('user_id', 'user', 'id')' could not be located in PRAGMA foreign_keys for table flow
  context.run_migrations()
No new upgrade operations detected.
                    INFO     2024-04-12 14:04:51 - INFO     - utils - No LLM cache set.             utils.py:88
[2024-04-12 14:04:51 -0500] [3249910] [INFO] Application startup complete.
```
However, the UI shows a small pink box in the bottom of the screen:

```
An error has occurred while fetching types.
Please refresh the page.
```
The developer console of the chrome browser shows the following:

```
Uncaught SyntaxError: Unexpected token '<' (at ace.js:1:1)
index-606f96de.js:99 
        
        
       GET http://15.4.50.102:7860/api/v1/all 403 (Forbidden)
(anonymous) @ index-606f96de.js:99
xhr @ index-606f96de.js:99
dispatchRequest @ index-606f96de.js:101
Promise.then (async)
_request @ index-606f96de.js:102
request @ index-606f96de.js:101
Axios.<computed> @ index-606f96de.js:102
(anonymous) @ index-606f96de.js:97
getAll @ index-606f96de.js:123
(anonymous) @ index-606f96de.js:123
getTypes @ index-606f96de.js:123
(anonymous) @ index-606f96de.js:1699
Rj @ index-606f96de.js:40
Ik @ index-606f96de.js:40
(anonymous) @ index-606f96de.js:40
Mt @ index-606f96de.js:25
$t @ index-606f96de.js:25
index-606f96de.js:99 
        
        
       GET http://15.4.50.102:7860/api/v1/users/whoami 403 (Forbidden)
(anonymous) @ index-606f96de.js:99
xhr @ index-606f96de.js:99
dispatchRequest @ index-606f96de.js:101
Promise.then (async)
_request @ index-606f96de.js:102
request @ index-606f96de.js:101
Axios.<computed> @ index-606f96de.js:102
(anonymous) @ index-606f96de.js:97
getLoggedUser @ index-606f96de.js:123
Et @ index-606f96de.js:123
bt @ index-606f96de.js:123
(anonymous) @ index-606f96de.js:123
Promise.then (async)
(anonymous) @ index-606f96de.js:123
Rj @ index-606f96de.js:40
Ik @ index-606f96de.js:40
(anonymous) @ index-606f96de.js:40
Mt @ index-606f96de.js:25
$t @ index-606f96de.js:25
index-606f96de.js:123 auth context
index-606f96de.js:123 An error has occurred while fetching types.
(anonymous) @ index-606f96de.js:123
Promise.catch (async)
(anonymous) @ index-606f96de.js:123
getTypes @ index-606f96de.js:123
(anonymous) @ index-606f96de.js:1699
Rj @ index-606f96de.js:40
Ik @ index-606f96de.js:40
(anonymous) @ index-606f96de.js:40
Mt @ index-606f96de.js:25
$t @ index-606f96de.js:25
index-606f96de.js:123 AxiosError {message: 'Request failed with status code 403', name: 'AxiosError', code: 'ERR_BAD_REQUEST', config: {…}, request: XMLHttpRequest, …}
15.4.50.102/:1 Uncaught (in promise) undefined
Promise.then (async)
(anonymous) @ index-606f96de.js:1699
Rj @ index-606f96de.js:40
Ik @ index-606f96de.js:40
(anonymous) @ index-606f96de.js:40
Mt @ index-606f96de.js:25
$t @ index-606f96de.js:25
index-606f96de.js:99 
        
        
       GET http://15.4.50.102:7860/api/v1/store/check/api_key 403 (Forbidden)
(anonymous) @ index-606f96de.js:99
xhr @ index-606f96de.js:99
dispatchRequest @ index-606f96de.js:101
Promise.then (async)
_request @ index-606f96de.js:102
request @ index-606f96de.js:101
Axios.<computed> @ index-606f96de.js:102
(anonymous) @ index-606f96de.js:97
checkHasApiKey @ index-606f96de.js:123
fetchApiData @ index-606f96de.js:178
(anonymous) @ index-606f96de.js:1699
Rj @ index-606f96de.js:40
Ik @ index-606f96de.js:40
(anonymous) @ index-606f96de.js:40
Mt @ index-606f96de.js:25
$t @ index-606f96de.js:25
index-606f96de.js:178 AxiosError {message: 'Request failed with status code 403', name: 'AxiosError', code: 'ERR_BAD_REQUEST', config: {…}, request: XMLHttpRequest, …}
index-606f96de.js:99 
        
        
       GET http://15.4.50.102:7860/api/v1/users/whoami 403 (Forbidden)
(anonymous) @ index-606f96de.js:99
xhr @ index-606f96de.js:99
dispatchRequest @ index-606f96de.js:101
Promise.then (async)
_request @ index-606f96de.js:102
request @ index-606f96de.js:101
Axios.<computed> @ index-606f96de.js:102
(anonymous) @ index-606f96de.js:97
getLoggedUser @ index-606f96de.js:123
Et @ index-606f96de.js:123
bt @ index-606f96de.js:123
(anonymous) @ index-606f96de.js:123
Promise.then (async)
(anonymous) @ index-606f96de.js:123
Rj @ index-606f96de.js:40
Ik @ index-606f96de.js:40
(anonymous) @ index-606f96de.js:40
Mt @ index-606f96de.js:25
$t @ index-606f96de.js:25
index-606f96de.js:123 auth context
```

**Browser and Version**
 - Version 123.0.6312.122 (Official Build) (64-bit)
 - LangFlow 0.6.15

**To Reproduce**
1. Create new virtual environment
2. Pip install langflow
3. Load UI

**Screenshots**
![langflow-failure-to-load](https://github.com/langflow-ai/langflow/assets/67472065/610c28d1-508c-4035-9e1c-77003541d70b)

**Comment by wuyang630** [comment]
https://github.com/langflow-ai/langflow/issues/1508#issuecomment-2026470631

this really help

**Comment by taylor-schneider** [comment]
@wuyang630 the workaround you referenced allowed me to get past this issue.

> 1.Open Chrome and navigate to chrome://flags in the address bar.
2.Search for the flag titled Insecure origins treated as secure.
3.In the text box for this flag, enter the URL of your site.
4.Enable this setting.
5.Restart Chrome.

At this point, I am not sure if this is a bug or just a gap in the documentation. What do the developers think? Should I submit a PR for the README or something similar?

**Comment by anovazzi1** [comment]
It's unlikely to be a bug, but it depends on your environment. You could potentially fix it without altering Chrome flags by setting the cookie flags in the .env file within the Langflow folder or by setting the variables directly in the CLI. Feel free to submit a pull request to the docs about it.

**Comment by taylor-schneider** [comment]
> @taylor-schneider It's unlikely to be a bug, but it depends on your environment. You could potentially fix it without altering Chrome flags by setting the cookie flags in the .env file within the Langflow folder or by setting the variables directly in the CLI. Feel free to submit a pull request to the docs about it.

Which flags for the .env file or CLI are you referring to? I still do not understand what the rot issue is. It seems like certificate is having issues?

**Comment by pingyuan2016** [comment]
![image](https://github.com/langflow-ai/langflow/assets/25808622/78869d7e-3441-40c1-9271-9691cc9b6c22)
ssame problem

**Comment by pingyuan2016** [comment]
> [#1508 (comment)](https://github.com/langflow-ai/langflow/issues/1508#issuecomment-2026470631)
> 
> this really help

chrome set ,  It's not work

**Comment by anovazzi1** [comment]
@taylor-schneider 
These environment variables allow you to customize cookie settings based on your specific needs:

- **REFRESH_SAME_SITE**: Determines the SameSite attribute of the refresh token cookie. Options include "lax," "strict," and "none" (default).
  
- **REFRESH_SECURE**: Enables or disables the Secure attribute of the refresh token cookie (default is enabled).

- **REFRESH_HTTPONLY**: Enables or disables the HttpOnly attribute of the refresh token cookie (default is enabled).

- **ACCESS_SAME_SITE**: Sets the SameSite attribute of the access token cookie. Options are "lax" (default), "strict," and "none."

- **ACCESS_SECURE**: Enables or disables the Secure attribute of the access token cookie (default is disabled).

- **ACCESS_HTTPONLY**: Enables or disables the HttpOnly attribute of the access token cookie (default is disabled).

You may need to modify these variables depending on your environment and specific requirements.

**Comment by Pokora22** [comment]
@anovazzi1 I've tried setting up these to be most open:
ENV REFRESH_SAME_SITE=none
ENV REFRESH_SECURE=False
ENV REFRESH_HTTPONLY=True
ENV ACCESS_SAME_SITE=none
ENV ACCESS_SECURE=False
ENV ACCESS_HTTPONLY=False

Don't think that's really doing anything. I searched the repo code and these are not mentioned anywhere either. Setting up the browser to treat the origin as secure is not a good solution - it's only a bandaid. How do the cluster deployments of this work if we're all facing this issue?

**Comment by anovazzi1** [comment]
My bad. All Langflow environment variables start with `LANGFLOW_`, so the correct variable is `LANGFLOW_REFRESH_SECURE` instead of just `REFRESH_SECURE`. This naming convention applies to all Langflow environment variables. Please update the variable and let me know if you encounter any further issues. Thank you!

**Comment by carlosrcoelho** [comment]
Hi @taylor-schneider and @Pokora22 

We hope you're doing well. Just a friendly reminder that if we do not hear back from you within the next 3 days, we will close this issue. If you need more time or further assistance, please let us know. 

Thank you for your understanding!

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
