### ISSUE TITLE
OllamaEmbeddings Hardcode the model cannot change from llama2

### ISSUE THREAD

**Issue by mrabbah** [langflow-ai/langflow#1696]
**Describe the bug**
I used the OllamaEmbeddings in my Flow, and I changed the model to "mxbai-embed-large" when I compile the Flow I got the following error:

`ValueError: Error building node Qdrant(ID:Qdrant-hOQcv): Error raised  by inference API HTTP code: 404,  {"error":"model 'llama2' not found, try  pulling it first"} `  

Looking at the source code of the OllamaEmbeddings  node, I think it is hardcoded to use llama2

**Browser and Version**
 - Browser Microsoft Edge
 - Version 123.0.2420.81 (Official build) (64-bit)
[First Example RAG.json](https://github.com/langflow-ai/langflow/files/14967517/First.Example.RAG.json)

**To Reproduce**
1. Run ollama on your local machine
2. pull model mxbai-embed-large, (and as option mistral)
3. in Langflow ui, create new project,
4. import the following attached [First Example RAG.json](https://github.com/langflow-ai/langflow/files/14967522/First.Example.RAG.json)
5. Change the host and port of your ollama in OllamaEmbeddings node
6. Try to compile

**Screenshots**
![image](https://github.com/langflow-ai/langflow/assets/6692572/e26d8d05-ba57-4989-a793-188e9ffca25c)

**Additional context**
I run langflow throw Docker with the latest image version I pulled 04/13/2024

**Comment by yamonkjd** [comment]
Hey, this is the revised draft for the issue. You can paste it into a custom component and test it yourself. (Your version of langflow must be v1 or higher.)

https://github.com/langflow-ai/langflow/pull/1703

**Comment by anovazzi1** [comment]
Hello,
Sorry for the delay. Did you try using the new version? Does the error still persist?

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
