### ISSUE TITLE
UI isn't working

### ISSUE THREAD

**Issue by mohamed1249** [langflow-ai/langflow#1699]
**Describe the bug**
I created an new venv on my windows system and installed langflow and tried to run it but the UI is empty

**Browser and Version**
all my browsers

**Screenshots**

![image](https://github.com/langflow-ai/langflow/assets/98451595/b9aebb5a-79cd-4de4-b333-424d2e6bc620)

**Comment by anovazzi1** [comment]
maybe the solution is the same as #1182
