### ISSUE TITLE
Add support for ChatOpenAI

### ISSUE THREAD

**Issue by ogabrielluiz** [langflow-ai/langflow#17]
Implement and test Langchain's ChatOpenAI.

**Comment by websmyths** [comment]
Where in the code would you add that functionality?

**Comment by ibiscp** [comment]
I'm working on this, waiting for a PR on lanchain.

**Comment by ibiscp** [comment]
Added on version [0.0.44](https://github.com/logspace-ai/langflow/releases/tag/v0.0.44)
