### ISSUE TITLE
An error has occurred while fetching types when I open the page

### ISSUE THREAD

**Issue by Leekinxun** [langflow-ai/langflow#1708]
When I localize deployment, the log shows "Application startup complete", but when I open the page, it shows "An error has occurred while fetching types". How can I solve this problem

**Comment by qwaszaq** [comment]
I have the same using docker on portainer. Did you manage to solve it?

**Comment by ogabrielluiz** [comment]
Hey all

This could be related to the cookies settings. 

`LANGFLOW_ACCESS_SAME_SITE` and `LANGFLOW_ACCESS_SECURE` are the ones might need to change.

`LANGFLOW_ACCESS_SAME_SITE=lax` and `LANGFLOW_ACCESS_SECURE=false` might work.

**Comment by qwaszaq** [comment]
I use it as a docker under portainer, where can I change it?

**Comment by carlosrcoelho** [comment]
Hi @Leekinxun and @qwaszaq 

We hope you're doing well. Just a friendly reminder that if we do not hear back from you within the next 3 days, we will close this issue. If you need more time or further assistance, please let us know. 

Thank you for your understanding!

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
