### ISSUE TITLE
API: input_value is ignored and not passed to Chat Input

### ISSUE THREAD

**Issue by radek3911** [langflow-ai/langflow#1744]
**Describe the bug**
When calling API endpoint run/<flow_id> the input_value is suggested by code generator in Langflow UI, however after submitting request to the endpoint the input_value seems to be ignored and not passed into the Chat input node.

**Version**
 -  Langflow v1.0.0a23

**To Reproduce**
1. Use template for flow Document Q&A
![image](https://github.com/langflow-ai/langflow/assets/15276167/912bd930-0bb4-4770-b404-f09896d99a08)
2. Go to the API section that will give you example on how to call the API.
3. Observe that in cURL and Python API examples input_value is suggested to be filled for prompt.
![image](https://github.com/langflow-ai/langflow/assets/15276167/64af2de0-f654-44cd-bd74-81d85fa515ad)
4. Attempt to call the API with input_value:
![image](https://github.com/langflow-ai/langflow/assets/15276167/ed1e35f8-baf0-49d8-b7a1-a17dcf59e355)

Observe that the prompt gets ignored.

**Additional context**
When using tweak on chat input, the flow behaves correctly:
![image](https://github.com/langflow-ai/langflow/assets/15276167/2f068916-8b62-4885-8fbc-d7468431d47c)

**Comment by ogabrielluiz** [comment]
Hey @radek3911 

How are you? 

Definitely a bug. 

I'll get to it ASAP. 

Thanks!
