### ISSUE TITLE
PyPDF is no longer available on 1.0.x

### ISSUE THREAD

**Issue by pedrocassalpacheco** [langflow-ai/langflow#1753]
Gente - onde esta o PyPDF na versao 1.0.x?

**Comment by ogabrielluiz** [comment]
Oi, Pedro!

O componente File agora é o que carrega arquivos de texto. Ele está na
categoria Data.

EN: The File component is the one you should use to load text files. It is
in the Data category.

**Comment by pedrocassalpacheco** [comment]
Outra pergunta

import requests
from typing import Optional

BASE_API_URL = "http://127.0.0.1:7860/api/v1/run"
FLOW_ID = "5f693373-dcbc-4674-bef6-31a95e2bd42c"
# You can tweak the flow by adding a tweaks dictionary
# e.g {"OpenAI-XXXXX": {"model_name": "gpt-4"}}
TWEAKS = {
  "File-9Rf55": {},
  "OllamaEmbeddings-dkodo": {},
  "CharacterTextSplitter-goA0E": {},
  "AstraDB-LANwq": {}
}

def run_flow(message: str,
  flow_id: str,
  output_type: str = "chat",
  input_type: str = "chat",
  tweaks: Optional[dict] = None,
  api_key: Optional[str] = None) -> dict:
    """
    Run a flow with a given message and optional tweaks.

    :param message: The message to send to the flow
    :param flow_id: The ID of the flow to run
    :param tweaks: Optional tweaks to customize the flow
    :return: The JSON response from the flow
    """
    api_url = f"{BASE_API_URL}/{flow_id}"

    payload = {
        "input_value": message,
        "output_type": output_type,
        "input_type": input_type,
    }
    headers = None
    if tweaks:
        payload["tweaks"] = tweaks
    if api_key:
        headers = {"x-api-key": api_key}
    response = requests.post(api_url, json=payload, headers=headers)
    return response.json()

# Setup any tweaks you want to apply to the flow
message = "message"

print(run_flow(message=message, flow_id=FLOW_ID, tweaks=TWEAKS))

Esse codigo vem da interface

 /Users/pedropacheco/Projects/demos/langflow/run.py
{'detail': "Error running graph: Error building vertex AstraDB: Request URL is missing an 'http://' or 'https://' protocol."}

Onde e como eu coloco os parametros do meu flow?

O example usando a API nao funciona tbm
