### ISSUE TITLE
'function' object has no attribute  'split' 

### ISSUE THREAD

**Issue by xsser** [langflow-ai/langflow#1755]
Describe the Bug
During the attempt to build a node named GitLoader, the program threw a ValueError. The specific error message was: 'function' object has no attribute 'split'. This suggests that there might be an incorrect attempt in the code to call the split method on a function object, whereas split is typically a method used with strings.

### Browser and Version

    Browser: Firefox
    Version: 124.0.2 64-bit

### Steps to Reproduce

    Create a plugin named "github reader" in the interface.
    In the plugin configuration, add a node configuration including the use of LLMChain, PromptTemplate, CharacterTextSplitter, ConversationBufferMemory, and PostgresChatMessageHistory.
    Attempt to save or execute the configuration.
    Observe a ValueError reported in the system logs with a red error prompt.

### Screenshots
<img width="1102" alt="图片" src="https://github.com/langflow-ai/langflow/assets/1850771/0ad96579-5672-49f9-8c8d-2ab5ae42e91b">

### Additional Context
The error occurred during the node build process, particularly involving the GitLoader. Possible reasons include incorrect calls to object attributes or some variables expected to be strings being incorrectly passed as functions.

**Comment by anovazzi1** [comment]
Hello,
Sorry for the delay. Did you try using the new version? Does the error still persist?

**Comment by carlosrcoelho** [comment]
Hi @xsser 

We hope you're doing well. Just a friendly reminder that if we do not hear back from you within the next 3 days, we will close this issue. If you need more time or further assistance, please let us know. 

Thank you for your understanding!

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
