### ISSUE TITLE
All memory components are missing (pre-release)

### ISSUE THREAD

**Issue by Dakes** [langflow-ai/langflow#1758]
**Describe the bug**
All memory components are missing in the 1.0.0a24 build. Besides "Message History", but you can't connect that to Memory nodes.

**Version**
 - Version: 1.0.0a24  started via docker-compose

**To Reproduce**
1. Start the docker image with the tag "1.0-alpha" or "1.0.0a24"
2. Create a blank flow
3. Search for memory

**Screenshots**
![image](https://github.com/langflow-ai/langflow/assets/20887264/2a5ac7b5-178d-4aee-83ea-d6dfa65260fc)
![image](https://github.com/langflow-ai/langflow/assets/20887264/ef3d632a-aa7b-4c60-96ee-5d1bf30a2646)

**Comment by NeoVand** [comment]
I have the same issue!

**Comment by anovazzi1** [comment]
Hello,
Sorry for the delay. Did you try using the new version? Does the error still persist?
