### ISSUE TITLE
Cannot drag both on langflow and flowise at all.

### ISSUE THREAD

**Issue by LeoYelton** [langflow-ai/langflow#1762]
**Describe the bug**
Load on https://huggingface.co/spaces/Langflow/Langflow-Preview

cause the following error on console:

145Third-party cookie will be blocked. Learn more in the Issues tab.
 Dark Reader: unexpected error during message passing.
2translator.js:566  Uncaught TypeError: Cannot read properties of undefined (reading 'lastError')
    at HTMLDocument.mouseup (translator.js:566:32)

        [NEW] Explain Console errors by using Copilot in Edge: click 
         to explain an error. 
        Learn more
        Don't show again
Langflow-Preview:1  Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
11translator.js:566  Uncaught TypeError: Cannot read properties of undefined (reading 'lastError')
    at HTMLDocument.mouseup (translator.js:566:32)

and i cannot drag to add more not on paint board.

**Browser and Version**
 - Browser [EDGE]
 - Version [124.0.2478.51]

**To Reproduce**
1.go to this web , ceate a flow , try to drag node.

**Screenshots**
![image](https://github.com/langflow-ai/langflow/assets/29271141/51a28ad6-af36-4811-8618-ded3ec5900a9)

**Comment by LeoYelton** [comment]
Really strange question.

**Comment by yamonkjd** [comment]
Flowise is a JavaScript-based project, and Langflow is a Python-based project. The main contributors of these two projects are different, and the operational logic itself varies, making them incompatible with each other.

**Comment by ogabrielluiz** [comment]
Hey @LeoYelton 

Could you try it on a different browser?

**Comment by LeoYelton** [comment]
Almost try on all available browsers，wondering for it，I'm not sure Is that any relation between I just try to use symbol link to make my cdriver bigger and i move Most of file user local to driver d，And make link to them，I find some of application could not run so i moved them back to c driver again. And I'm not sure how the browser calls And interact to to user local file，I just cannot Drag any of the node，In ie chrome and Firefox.



---- Replied Message ----
| From | Gabriel Luiz Freitas ***@***.***> |
| Date | 04/27/2024 01:02 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [langflow-ai/langflow] Cannot drag both on langflow and flowise at all. (Issue #1762) |

Hey @LeoYelton

Could you try it on a different browser?

**Comment by vinosamari** [comment]
Try using it in Huggingface Spaces

**Comment by LeoYelton** [comment]
> Try using it in Huggingface Spaces

Really strange. I did not have access to the website 4days then i can drag now. Is it some js compiler bug caused by chromium?
