### ISSUE TITLE
Custom Component build error:   error build node data : "input"

### ISSUE THREAD

**Issue by yuanzhiwei** [langflow-ai/langflow#1767]
**Describe the bug**

**Browser and Version**
 - Browser [chrome]
 - Version [0.6]

**To Reproduce**
1. I created an Agent using a custom component and passed in a template
2. code show as below

**Screenshots**
![image](https://github.com/langflow-ai/langflow/assets/17841347/2c268d53-0614-44f7-83b1-fc68b402de64)
![image](https://github.com/langflow-ai/langflow/assets/17841347/1f04650c-05b9-4b27-841a-a5ee550e825a)

![image](https://github.com/langflow-ai/langflow/assets/17841347/c88e43a8-f0dc-4347-9761-f52b61db78e4)
![image](https://github.com/langflow-ai/langflow/assets/17841347/f0afd676-a53f-45c8-8152-75d2e4b65b27)

Please help to find out what the problem is, thanks

**Comment by yamonkjd** [comment]
From what I see, the code you provided doesn't seem to be the correct way to write an Agent for Langchain. An Agent should be a type that returns an Agent executor object, and it must be declared as a class derived from Base Agent to be usable as a Langchain Agent.

**Comment by yuanzhiwei** [comment]
> Like 喜欢
> 
> ```
> from typing import Callable, List, Optional, Union
> 
> from langchain.agents import AgentExecutor, AgentType, initialize_agent, types
> 
> from langflow.field_typing import BaseChatMemory, BaseLanguageModel, Tool
> from langflow.interface.custom.custom_component import CustomComponent
> 
> 
> class AgentInitializerComponent(CustomComponent):
>     display_name: str = "Agent Initializer"
>     description: str = "Initialize a Langchain Agent."
>     documentation: str = "https://python.langchain.com/docs/modules/agents/agent_types/"
> 
>     def build_config(self):
>         agents = list(types.AGENT_TO_CLASS.keys())
>         # field_type and required are optional
>         return {
>             "agent": {"options": agents, "value": agents[0], "display_name": "Agent Type"},
>             "max_iterations": {"display_name": "Max Iterations", "value": 10},
>             "memory": {"display_name": "Memory"},
>             "tools": {"display_name": "Tools"},
>             "llm": {"display_name": "Language Model"},
>             "code": {"advanced": True},
>         }
> 
>     def build(
>         self,
>         agent: str,
>         llm: BaseLanguageModel,
>         tools: List[Tool],
>         max_iterations: int,
>         memory: Optional[BaseChatMemory] = None,
>     ) -> Union[AgentExecutor, Callable]:
>         agent = AgentType(agent)
>         if memory:
>             return initialize_agent(
>                 tools=tools,
>                 llm=llm,
>                 agent=agent,
>                 memory=memory,
>                 return_intermediate_steps=True,
>                 handle_parsing_errors=True,
>                 max_iterations=max_iterations,
>             )
>         return initialize_agent(
>             tools=tools,
>             llm=llm,
>             agent=agent,
>             return_intermediate_steps=True,
>             handle_parsing_errors=True,
>             max_iterations=max_iterations,
>         )
> ```

Thank you for your reply. What if this custom component is a chain? You can see that this is actually a chain, but I named it as Agent. Is there any example?

**Comment by yamonkjd** [comment]
> > Like 喜欢
> > ```
> > from typing import Callable, List, Optional, Union
> > 
> > from langchain.agents import AgentExecutor, AgentType, initialize_agent, types
> > 
> > from langflow.field_typing import BaseChatMemory, BaseLanguageModel, Tool
> > from langflow.interface.custom.custom_component import CustomComponent
> > 
> > 
> > class AgentInitializerComponent(CustomComponent):
> >     display_name: str = "Agent Initializer"
> >     description: str = "Initialize a Langchain Agent."
> >     documentation: str = "https://python.langchain.com/docs/modules/agents/agent_types/"
> > 
> >     def build_config(self):
> >         agents = list(types.AGENT_TO_CLASS.keys())
> >         # field_type and required are optional
> >         return {
> >             "agent": {"options": agents, "value": agents[0], "display_name": "Agent Type"},
> >             "max_iterations": {"display_name": "Max Iterations", "value": 10},
> >             "memory": {"display_name": "Memory"},
> >             "tools": {"display_name": "Tools"},
> >             "llm": {"display_name": "Language Model"},
> >             "code": {"advanced": True},
> >         }
> > 
> >     def build(
> >         self,
> >         agent: str,
> >         llm: BaseLanguageModel,
> >         tools: List[Tool],
> >         max_iterations: int,
> >         memory: Optional[BaseChatMemory] = None,
> >     ) -> Union[AgentExecutor, Callable]:
> >         agent = AgentType(agent)
> >         if memory:
> >             return initialize_agent(
> >                 tools=tools,
> >                 llm=llm,
> >                 agent=agent,
> >                 memory=memory,
> >                 return_intermediate_steps=True,
> >                 handle_parsing_errors=True,
> >                 max_iterations=max_iterations,
> >             )
> >         return initialize_agent(
> >             tools=tools,
> >             llm=llm,
> >             agent=agent,
> >             return_intermediate_steps=True,
> >             handle_parsing_errors=True,
> >             max_iterations=max_iterations,
> >         )
> > ```
> 
> Thank you for your reply. What if this custom component is a chain? You can see that this is actually a chain, but I named it as Agent. Is there any example?

I think you are considering using custom chains or classes, and currently, this seems to be the best approach.

https://github.com/langflow-ai/langflow/issues/1634
https://github.com/langflow-ai/langflow/issues/867

**Comment by yamonkjd** [comment]
As you mentioned in your question, it is difficult to structure each chain as a pipeline and pass it on like in the official Langchain examples. In Langflow, since all components can be easily connected using the CustomComponent method, I do not recommend defining chains for serialization at the code level.

**Comment by anovazzi1** [comment]
Hello @yuanzhiwei,
Sorry for the delay. Did you try using the new version? Does the error still persist?

**Comment by carlosrcoelho** [comment]
Hi @yuanzhiwei 

We hope you're doing well. Just a friendly reminder that if we do not hear back from you within the next 3 days, we will close this issue. If you need more time or further assistance, please let us know. 

Thank you for your understanding!

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
