### ISSUE TITLE
 ValueError: Error building vertex Ollama

### ISSUE THREAD

**Issue by Chatelo** [langflow-ai/langflow#1769]
Running langflow on my Macbook Pro
here is the issue on my terminal:
<img width="1680" alt="Screenshot 2024-04-23 at 16 35 27" src="https://github.com/langflow-ai/langflow/assets/101531171/a61bef32-5a03-4908-89b5-09d98425875f">

I run into issue setting up the model. Actually I have llama3 in my machine which I have been using with [Webui](https://github.com/open-webui/open-webui) and I thought I should try out langflow after watching this [tutorial](https://www.youtube.com/watch?v=rz40ukZ3krQ&t=919s)

**Comment by yamonkjd** [comment]
It seems that the API endpoint was not provided to the Ollama component. You should check if the default values (localhost) and the port of the currently running Ollama are properly connected. Have you provided the same settings in the Ollama component as you used in the WebUI?

**Comment by Chatelo** [comment]
Thank you. I fixed with provided local url.

**Comment by Chatelo** [comment]
Thank you. I fixed with provided local url. Thank you @yamonkjd

**Comment by superdwayne** [comment]
Under advanced there is an option to enable the base URL input field 
![image](https://github.com/langflow-ai/langflow/assets/3473976/c5dfd86d-9ad1-429e-adfb-474128e45524)
