### ISSUE TITLE
ValueError: Error building vertex Astra DB Search: {"errors":[{"message":"Unknown namespace default_keyspace, you must create it first.","errorCode":"NAMESPACE_DOES_NOT_EXIST"}]}

### ISSUE THREAD

**Issue by msmygit** [langflow-ai/langflow#1770]
**Describe the bug**
Running `Langflow v1.0.0a24` version locally on `macOS Sonoma 14.4.1` and hitting the below error.

```
ValueError: Error building vertex Astra DB Search: {"errors":[{"message":"Unknown namespace default_keyspace, you must create it                                                        
                             first.","errorCode":"NAMESPACE_DOES_NOT_EXIST"}]}
```
<img width="1304" alt="image" src="https://github.com/langflow-ai/langflow/assets/19366623/88731bcc-a43f-4121-ae59-cb5d837e3e9e">

See the attached file for detailed console error. Follwed the following resources,

- https://pre-release.langflow.org/guides/rag-with-astradb

[langflow-rag-with-astra-a24-error-20240423.txt](https://github.com/langflow-ai/langflow/files/15079105/langflow-rag-with-astra-a24-error-20240423.txt)

**Browser and Version**
 - Browser [safari]
 - Version [Version 17.3 (19617.2.4.11.8)]

**To Reproduce**
1. Start following https://pre-release.langflow.org/guides/rag-with-astradb and then you hit this error at the below step,
2. 
<img width="1478" alt="image" src="https://github.com/langflow-ai/langflow/assets/19366623/b19b7eb1-200b-4f3b-9002-41eabb56cc47">
3. Validated Astra DB console and can ensure that `default_keyspace` namespace is also available. The token is of type `Organization Administrator` permission (https://docs.datastax.com/en/astra/astra-db-vector/administration/manage-database-access.html#organization-administrator-role) too.
<img width="266" alt="image" src="https://github.com/langflow-ai/langflow/assets/19366623/2c6e2d93-a6a4-4763-ad21-4c00c47792ca">

**Screenshots**
added all applicable details above.

**Additional context**
I'm only using the default Open AI embedding and unsure I'm receiving an error related to Google Vertex AI here. Thank you in advance!

**Comment by msmygit** [comment]
Error with `langflow-1.0.0a27` version is attached below for reference.
[v1.0.0a27-rag-with-astradb-error-20240429.txt](https://github.com/langflow-ai/langflow/files/15149643/v1.0.0a27-rag-with-astradb-error-20240429.txt)

**Comment by ogabrielluiz** [comment]
Hey @msmygit 

Thank you! 

Looking into it now.

**Comment by ogabrielluiz** [comment]
Could you try setting the `namespace` in the Advanced parameters of the component?

**Comment by msmygit** [comment]
Thank you @ogabrielluiz . FWIW, I also have `ASTRA_DB_NAMESPACE=default_keyspace` on the env file which didn't make a difference, but let me try the advanced section route.

**Comment by msmygit** [comment]
No luck,
<img width="639" alt="image" src="https://github.com/langflow-ai/langflow/assets/19366623/311726bb-a902-4a47-a75f-8611f2273165">

**Comment by ogabrielluiz** [comment]
Could it be that you are using the wrong credentials? 

I just tested it here and it is working.

**Comment by msmygit** [comment]
I tried with the `Organization Administrator` role and still the same result. Is there a place where I need to provide the [secure connect bundle](https://docs.datastax.com/en/astra/astra-db-vector/drivers/secure-connect-bundle.html#secure-connect-bundle-contents)?
<img width="646" alt="image" src="https://github.com/langflow-ai/langflow/assets/19366623/8d3f6fa1-6950-4d8d-8156-dfe50060f2db">

**Comment by msmygit** [comment]
fwiw, `logs/langflow.log` is empty too.

**Comment by anovazzi1** [comment]
Hello @msmygit,
Sorry for the delay. Did you try using the new version? Does the error still persist?

**Comment by carlosrcoelho** [comment]
Hi @msmygit 

We hope you're doing well. Just a friendly reminder that if we do not hear back from you within the next 3 days, we will close this issue. If you need more time or further assistance, please let us know. 

Thank you for your understanding!

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.

**Comment by 2stacks** [comment]
I'm having this same issue.  Should I post here or open a new issue?

```
ValueError: Error initializing AstraDBVectorStore: The provided keyspace does not exist:
                             Unknown keyspace 'default_keyspace', you must create it first
```

**Comment by 2stacks** [comment]
This looks to be a permissions issue with the token.  The "Database Administrator" role is not sufficient.  I temporarily created a token with all permissions "Organization Administrator" and now it works.
