### ISSUE TITLE
Code Button Giving Error

### ISSUE THREAD

**Issue by Zulelee** [langflow-ai/langflow#1780]
I have created a Flow and after building the flow when I click on the code button I get an error as shown in the image below. 

![image](https://github.com/langflow-ai/langflow/assets/106396856/bd10161d-3197-4905-8127-6e08f593f19c)

**Comment by ogabrielluiz** [comment]
Hi @Zulelee 
How are you ?

What version of Langflow are you using?

**Comment by Zulelee** [comment]
I have just clicked on "deploy to Render".  I guess it is the latest version?

**Comment by Zulelee** [comment]
This is my workflow. It builds successfully. 

![image](https://github.com/langflow-ai/langflow/assets/106396856/88ba400d-fbcc-4561-9bc3-cc563a9bed55)

**Comment by ogabrielluiz** [comment]
Thanks for the info, @Zulelee 

This might be a bug in the main version, then. 

Do you know how to check the browser console? 

When that error appears an error will be displayed in the browser console that could help us pinpoint the problem. 

Normally it opens if you press F12.

**Comment by Zulelee** [comment]
These are the errors in console
![image](https://github.com/langflow-ai/langflow/assets/106396856/0ede224c-20e7-4406-8fcf-1d81dd1401d4)

**Comment by TeamSuperChat** [comment]
Unfortunately this error is preventing us from deploying our MVP

**Comment by ogabrielluiz** [comment]
The image really helps. Thanks @Zulelee 

We'll work on a fix ASAP. 

Meanwhile, you should try using the 1.0 preview
