### ISSUE TITLE
Where are the community examples?

### ISSUE THREAD

**Issue by savager** [langflow-ai/langflow#1786]
**Describe the bug**
I used to be able to import community examples. Now it's just the LangFlow store. Is there another location to share the JSON files that I'm unaware of?

**Browser and Version**
all

**Comment by ogabrielluiz** [comment]
Hey @savager 

The Langflow Store replaces the Community Examples. 

We are working on expanding it, making it accessible and open as much as possible.

**Comment by savager** [comment]
That's unfortunate I thought this was an open source project. Thank you

**Comment by anovazzi1** [comment]
@savager, Langflow is an open-source project. Currently, the community examples serve became the basic examples, and the Langflow store provides a free space for the community to share flows and components freely.
