### ISSUE TITLE
when cookie is very large, websocket will fail

### ISSUE THREAD

**Issue by artemus717** [langflow-ai/langflow#1787]
**Describe the bug**
After build flow, when cookie is very large, websocket will fail.

[INFO] connection failed (400 Bad Request)

Langflow Version
0.6.17

**Screenshots**
![image](https://github.com/langflow-ai/langflow/assets/16465173/f4600f08-a0b3-47bc-9260-7ae46e37f46e)

**Comment by anovazzi1** [comment]
Hello,
Sorry for the delay. Did you try using the new version? Does the error still persist?

**Comment by carlosrcoelho** [comment]
Hi @artemus717 

We hope you're doing well. Just a friendly reminder that if we do not hear back from you within the next 3 days, we will close this issue. If you need more time or further assistance, please let us know. 

Thank you for your understanding!

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
