### ISSUE TITLE
api curl code not filled with tweaks

### ISSUE THREAD

**Issue by mountain15** [langflow-ai/langflow#1788]
**Describe the bug**
I have prefilled variables with a value in a component
I then click on API and see that in tweaks they are filled in
however in the curls code they are not filled
when I change the prefilled parameter that it copies the information 

**Browser and Version**
 - Browser chrome
 - Version Langflow 🤝 DataStax
⛓️ v1.0.0a24

**To Reproduce**
1. Go to 'component'
2. Click on 'api'
3. click on  'tweaks'
4. Change the variable default input
5. Go to "cURL
6. Now the variable are in the code

**Screenshots**
[tweaks-curl-not filled.webm](https://github.com/langflow-ai/langflow/assets/123085496/586d8737-30d5-454c-9a45-e108e29ec9a0)

See video

**Additional context**
I want brief the developer with the right information on the fields to that they know what the names are from the variables

**Comment by jaschahuisman** [comment]
I'm experiencing the same issue @Cristhianzl 

It would be nice if the API examples were filled in with default values for the inputs, now it's just empty json objects with abstract node id's, for where I don't know the input keys by heart.

<img width="639" alt="Screenshot 2024-05-04 at 18 06 30" src="https://github.com/langflow-ai/langflow/assets/39152972/51d36872-3cd1-41c1-8d28-8340c8bec9c2">

**Comment by Cristhianzl** [comment]
Hello @jaschahuisman @mountain15,

First of all, thank you for your report. 

Sorry for the delayed response; last week, we were working on new features, so I wasn't able to assist you with this issue. 

You can follow up on the status of this PR here: [https://github.com/langflow-ai/langflow/pull/1847] 
This PR will fix the issue you mentioned and will also enhance the performance of the application using tweaks.

Let me know if I can assist you with anything else.

Regards.
