### ISSUE TITLE
Question: Is there any built-in scheduler to start/trigger the agents?

### ISSUE THREAD

**Issue by selcukbeyhan** [langflow-ai/langflow#1798]
Hi,

I didnt see a possibility to start/schedule the agents to start with their assigned tasks.
Is it possible?

thanks.

**Comment by yamonkjd** [comment]
https://github.com/langflow-ai/langflow/issues/1732
https://github.com/langflow-ai/langflow/pull/1766

As suggested, the conditions for the starting trigger of the flow are currently being improved.

It is generally seen that integration with scheduling solutions like Trello or Jira through Webhooks could enhance it. (I believe it is better than implementing background tasks via polling.)

**Comment by ogabrielluiz** [comment]
We have first implementation of the webhook in a PR #1766 

It adds a component that will get the request and return it as a Record so you can then do whatever you plan with it.

**Comment by tobiasBora** [comment]
Why is it closed? Is it possible to have a scheduler node now without relying on an external tool that sends webhooks? Also, the current execution model seems way less powerful than, e.g., node-red, where each node can run asynchronously in parallel to send/receive messages. So it is for instance trivial to create a node that sends a new message every 10s, while I can't do this in langflow. Any idea if this is being planned?
