### ISSUE TITLE
[pre-release alpha bug] ERROR    - code_parser - cannot import name 'DocumentSearchHit' from 'langchain_core.documents'

### ISSUE THREAD

**Issue by msmygit** [langflow-ai/langflow#1806]
**Describe the bug**
When attempting to start langflow post upgrade to `Langflow v1.0.0a29` version, we get:
```
2024-04-30 12:51:20 - ERROR    - code_parser - cannot import name 'DocumentSearchHit' from 'langchain_core.documents'
```
Entire stacktrace is attached below,

[lf-a29-startup-bug_20240430.txt](https://github.com/langflow-ai/langflow/files/15168372/lf-a29-startup-bug_20240430.txt)

**To Reproduce**
1. Go to local langflow project virtual environment and perform `python -m pip install langflow --pre --force-reinstall -U`
2. Attempt to kick start the langflow using `python -m langflow run --env-file ~/langflow/.env` [env file is optional here]
3. See the great wall of error text

**Screenshots**
n/a

**Additional context**
Just attempting to start the langflow post upgrade.

**Comment by msmygit** [comment]
Attempted to perform `rm -rf /Users/username/Library/Caches/langflow` followed by starting it via `python -m langflow run --env-file ~/langflow/.env` which yielded the below,

```
% python -m langflow run --env-file ~/langflow/.env
/Users/username/.pyenv/versions/langflow/lib/python3.10/site-packages/langchain/_api/module_import.py:87: LangChainDeprecationWarning: Importing GuardrailsOutputParser from langchain.output_parsers is deprecated. Please replace the import with the following:
from langchain_community.output_parsers.rail_parser import GuardrailsOutputParser
  warnings.warn(
/Users/madhavansridharan/.pyenv/versions/langflow/lib/python3.10/site-packages/langchain/_api/module_import.py:87: LangChainDeprecationWarning: Importing JsonSpec from langchain.tools.json is deprecated. Please replace the import with the following:
from langchain_community.tools.json.tool import JsonSpec
  warnings.warn(
Starting Langflow v1.0.0a29...
╭───────────────────────────────────────────────────╮
│ Welcome to ⛓ Langflow                             │
│                                                   │
│                                                   │
│ Collaborate, and contribute at our GitHub Repo 🚀 │
│                                                   │
│ Access http://127.0.0.1:7860                      │
╰───────────────────────────────────────────────────╯
```

which unfortunately deleted all my local project/flows/components :-(

**Comment by anovazzi1** [comment]
Hello @msmygit,
Sorry for the delay. Did you try using the new version? Does the error still persist?

**Comment by carlosrcoelho** [comment]
Hi @msmygit 

We hope you're doing well. Just a friendly reminder that if we do not hear back from you within the next 3 days, we will close this issue. If you need more time or further assistance, please let us know. 

Thank you for your understanding!

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
