### ISSUE TITLE
Pinecone error

### ISSUE THREAD

**Issue by uiaiek32** [langflow-ai/langflow#1815]
I get this error when I try to connect the pinecone vector: 
Error building node Pinecone(ID:Pinecone-eKDBR): init is no longer a top-level attribute of the pinecone package. Please create an instance of the Pinecone class instead. Example: import os from pinecone import Pinecone, ServerlessSpec pc = Pinecone( api_key=os.environ.get("PINECONE_API_KEY") ) # Now do stuff if 'my_index' not in pc.list_indexes().names(): pc.create_index( name='my_index', dimension=1536, metric='euclidean', spec=ServerlessSpec( cloud='aws', region='us-west-2' ) )

![Capture1](https://github.com/langflow-ai/langflow/assets/158764295/90725986-986e-448d-92d9-9605e5a63dc4)
I click run and I get this error

**Comment by uiaiek32** [comment]
@dosu I still get the error, could you provide me with the correct code please?

**Comment by uiaiek32** [comment]
I get this error: Error building node Pinecone(ID:Pinecone-0mjWP): init is no longer a top-level attribute of the pinecone package. Please create an instance of the Pinecone class instead. Example: import os from pinecone import Pinecone, ServerlessSpec pc = Pinecone( api_key=os.environ.get("PINECONE_API_KEY") ) # Now do stuff if 'my_index' not in pc.list_indexes().names(): pc.create_index( name='my_index', dimension=1536, metric='euclidean', spec=ServerlessSpec( cloud='aws', region='us-west-2' ) )

**Comment by ogabrielluiz** [comment]
Hey @uiaiek32 

It seems this component is outdated. 

We'll get to it soon. 

Feel free to update it if you got the know-how and thanks for the heads up!

**Comment by uiaiek32** [comment]
Thanks for the response, I would like to ask how long this will take until
it is fixed.
Thank you very much.
George

**Comment by uiaiek32** [comment]
Hey, I am following up on the Pinecone outdated component. Would it be
possible to fix it?
Thanks,
George

**Comment by ogabrielluiz** [comment]
#1854 fixes it in the dev branch.

**Comment by uiaiek32** [comment]
Hello I am sorry to bother you but I still get the same error. 
I re-deploy langflow but I still get the same error message
This is the error message that I get. 
![unnamed](https://github.com/langflow-ai/langflow/assets/158764295/7ca68b98-88a8-4baf-be7b-0c9a07a6e697)

If you could help me that would be great!
Thanks a lot.
George

**Comment by anovazzi1** [comment]
Hello @uiaiek32,
Sorry for the delay. Did you try using the new version? Does the error still persist?

**Comment by carlosrcoelho** [comment]
Hi @uiaiek32 

We hope you're doing well. Just a friendly reminder that if we do not hear back from you within the next 3 days, we will close this issue. If you need more time or further assistance, please let us know. 

Thank you for your understanding!

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
