### ISSUE TITLE
`PromptRunner` does not support `AzureChatOpenAI` as an LLM input

### ISSUE THREAD

**Issue by tonydoesathing** [langflow-ai/langflow#1823]
Awesome project! Was playing around with the tool and hit a wall, since I only have access to Azure's OpenAI...

**Describe the bug**
`PromptRunner` does not support `AzureChatOpenAI` as an LLM input

**Browser and Version**
 - chrome
 - Version 124.0.6367.78 (Official Build) (64-bit)

**To Reproduce**
1. Go to 'New Project'
2. Under LLMs, drag out a new `AzureChatOpenAI`
3. Fill in the data required for the LLM
4. Under Chains, drag out a new `PromptRunner` chain
5. Try to connect the `BaseLanguageModel` output of the `AzureChatOpenAI` block to the `LLM` input on the `PromptRunner` block and struggle

**Expected Behavior**
I should be able to connect `AzureChatOpenAI`'s output to the `LLM` input on any block

**Comment by anovazzi1** [comment]
Hello,
Sorry for the delay. Did you try using the new version? Does the error still persist?

**Comment by carlosrcoelho** [comment]
Hi @tonydoesathing 

We hope you're doing well. Just a friendly reminder that if we do not hear back from you within the next 3 days, we will close this issue. If you need more time or further assistance, please let us know. 

Thank you for your understanding!

**Comment by carlosrcoelho** [comment]
Hi @tonydoesathing,

No worries at all, we totally understand! Take your time to get everything set up and test. We'll keep the issue open and look forward to your update.

Thanks for letting us know!

**Comment by tonydoesathing** [comment]
Thanks! You're the best! ^-^
Running the latest, looks like `AzureOpenAI` now has an LLM output exposed which connects to things 👌
