### ISSUE TITLE
Conditional Flow

### ISSUE THREAD

**Issue by puyuanOT** [langflow-ai/langflow#1857]
Is it possible to create a block that determines which flow to execute based on conditions? For example, execute different flows based on the user's intent.

<img width="853" alt="Screenshot 2024-05-07 at 7 31 46 PM" src="https://github.com/langflow-ai/langflow/assets/121119211/711e5cc6-939e-4cd6-b18e-c3eac2d6d1c9">

**Comment by yamonkjd** [comment]
It seems similar to the contents of this proposal: https://github.com/langflow-ai/langflow/issues/1731

It would be better to implement the function for an LLM to judge and select prompts directly using Langchain's prompt routing. Here is the relevant documentation: https://python.langchain.com/docs/expression_language/how_to/routing/

Implementing prompt routing directly within Langflow could enhance the block coding environment. However, due to the difficulty of fine-tuning, it might be better to utilize Langchain's techniques.

**Comment by puyuanOT** [comment]
> It seems similar to the contents of this proposal: #1731
> 
> It would be better to implement the function for an LLM to judge and select prompts directly using Langchain's prompt routing. Here is the relevant documentation: https://python.langchain.com/docs/expression_language/how_to/routing/
> 
> Implementing prompt routing directly within Langflow could enhance the block coding environment. However, due to the difficulty of fine-tuning, it might be better to utilize Langchain's techniques.

Thank you for your response. Is it possible to perform different actions based on various LLM outputs? For example, call `vector db` if the LLM output is `vector db` and call `calendar `if the LLM output is `calendar`. It would be fantastic if there were a way to explicitly execute a specific sequence of actions based on user inputs, like following a decision tree path. This would be especially helpful in scenarios where the action/decision tree is extensive and complex.
 
![image](https://github.com/langflow-ai/langflow/assets/121119211/cd6c2e63-3698-436e-895f-26ff9ce69fab)

**Comment by yamonkjd** [comment]
![image](https://github.com/langflow-ai/langflow/assets/141118378/0cc46676-c08c-479b-a928-bd41204ae0ba)

In my opinion, such a division could be adequately replaced by using Langflow's Flow as Tool component.

**Comment by ogabrielluiz** [comment]
Hey all

We have added a feature in the CustomComponent that can fulfill that role even if not ideal yet.

**Disclaimer: This is still experimental**

The CustomComponent now has a `stop` method. We have added the `TextOperator`  component that allows you to make a certain branch of your flow stop on its tracks.

The general gist of it is you'll create two branches in your flow one for each class and define the rest of the process for each one. The TextOperator (or whatever other component you define that calls `stop`) will test the condition and stop or let the flow run.

**Comment by puyuanOT** [comment]
> Hey all
> 
> We have added a feature in the CustomComponent that can fulfill that role even if not ideal yet.
> 
> **Disclaimer: This is still experimental**
> 
> The CustomComponent now has a `stop` method. We have added the `TextOperator` component that allows you to make a certain branch of your flow stop on its tracks.
> 
> The general gist of it is you'll create two branches in your flow one for each class and define the rest of the process for each one. The TextOperator (or whatever other component you define that calls `stop`) will test the condition and stop or let the flow run.

Wow this is great! I will try it out.

**Comment by ccollie** [comment]
> Implementing prompt routing directly within Langflow could enhance the block coding environment. However, due to the 
> difficulty of fine-tuning, it might be better to utilize Langchain's techniques.
Consider that there may be sophisticated but non-dev users of the platform. Specifically, in our product we want to offer a constrained version of LangFlow (with curated and custom task-specific components) to minimize cognitive load. 
For instance in a call center environment, the user may want to construct a dialog-tree like flow depending on Entity Recognition (did the agent mention a competitor ?), Sentiment Analysis (does the client think we suck ?).

There should be a component specialized to this scenario (choice among options) . LangFlow, stripped to its basics is really a workflow execution engine, and a branching node would seem fundamental.

**Comment by ccollie** [comment]
Prior art: https://rivet.ironcladapp.com/docs/node-reference/if-else

**Comment by anovazzi1** [comment]
Hello there,

This feature is now available in the current version. Please try updating to the latest version.

**Comment by Alex-Poon** [comment]
@anovazzi which component is it called exactly? I went through all of them and couldn't find it

**Comment by anovazzi1** [comment]
Hey @Alex-Poon,
There is a conditional router component, but you can also adapt any component you have. Now that you can create components with multiple outputs, you can set up conditional paths with them.
![image](https://github.com/langflow-ai/langflow/assets/70824914/3e527774-868d-4f65-9612-4b1ab92df4ec)

**Comment by MarceloNunesAlves** [comment]
Hi @httplups, I've had the same problem. Do you have a solution?

**Comment by httplups** [comment]
@MarceloNunesAlves I did not :(

**Comment by sancelot** [comment]
Hi, I don't really understand how we can use it....
I made a basic kind of classifier using it.
But it seems you can not connect multiple output to the chatbot input, then how can you watch the output ?


![Image](https://github.com/user-attachments/assets/adc7a7fd-b13d-4569-8c9b-0b222975ec82)

**Comment by aamdias** [comment]
+1 here! Is anyone using the "if-else" component to orchestrate llm calls?

**Comment by azhig** [comment]
> +1 here! Is anyone using the "if-else" component to orchestrate llm calls? 

I create conditional router component. You can check it here

https://github.com/langflow-ai/langflow/pull/9461


@MarceloNunesAlves 
@aamdias
@puyuanOT
