### ISSUE TITLE
Deploy langflow on aws instructions don't work

### ISSUE THREAD

**Issue by alexleventer** [langflow-ai/langflow#1860]
**Describe the bug**
- app is not deployed successfully after following aws deploy instructions: https://github.com/langflow-ai/langflow/tree/dev/scripts/aws

```
 Resource handler returned message: "Cannot find version 8.0.mysql_auror
```

**Browser and Version**

**To Reproduce**

**Screenshots**

**Additional context**

**Comment by mattbajorek** [comment]
@alexleventer I have created my own branch to fix the incorrect mysql version as well as out of sync dependencies that stopped the deployment: https://github.com/langflow-ai/langflow/pull/1893. Until it is merged, you can use my branch in the process rather than the current dev branch.
