### ISSUE TITLE
Python crashes while building a flow that includes Hugging Face Embeddings sentence_transformers

### ISSUE THREAD

**Issue by AlastairJarvis** [langflow-ai/langflow#1869]
**Describe the bug**
While building a flow using Hugging Face Embeddings component (model: sentence-transformers/all-mpnet-base-v2), Python crashes.

**Browser and Version**
 - Browser : Chrome 124.0.6367.119, Mac
 - Version 1.0.0a26

**To Reproduce**
1. Go to My Collection 
2. Select Vector Store RAG Flow added from Store
4. Replace OpenAI Embeddings with Hugging Face Embeddings
5. Build 
6. See error in Langflow interface

>       Error Building Component
>            Error building vertex Hugging Face Embeddings: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.

7. Install sentence-transformers
8. Attempt to build again.
9. See error in Terminal window      
> /usr/local/Cellar/python@3.10/3.10.14/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
>   warnings.warn('resource_tracker: There appear to be %d '
> çobjc[8054]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
> objc[8054]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
> [05/09/24 15:24:22] ERROR    2024-05-09 15:24:22 - ERROR    -    glogging.py:272
>                              glogging - Worker (pid:8054) was                   
>                              sent SIGABRT!   
>

**Comment by AlastairJarvis** [comment]
Let me know if you can't reproduce and I can send through the Problem Report for Python from the OS. 

I get this 100%, and happy to help debug if you're unable to repro it there.

**Comment by ogabrielluiz** [comment]
Hey @AlastairJarvis 

Do you know if this component accesses the HuggingFace API or if it loads the model locally? 

Running it locally will not work on the 1.0 alpha because it will load the model on every run.

**Comment by AlastairJarvis** [comment]
Aha.

When I first tried this component (HuggingFaceEmbeddings), LangFlow prompted me to download and install it, which leads me to believe it's trying to run it locally. 

I see HuggingFaceAPI Embeddings is a different component, but it looks like this is also pointing to localhost - so pointing to an API being served locally?

**Comment by carlosrcoelho** [comment]
Hi @AlastairJarvis 

We hope you're doing well. Just a friendly reminder that if we do not hear back from you within the next 3 days, we will close this issue. If you need more time or further assistance, please let us know. 

Thank you for your understanding!

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
