### ISSUE TITLE
What is the input value for vector store search when running as json flow? 

### ISSUE THREAD

**Issue by jordanrfrazier** [langflow-ai/langflow#1870]
**Summary**

Overall question: How do I know what is a valid input key and valid output component for my flows when exporting them to json to run? 

I have a simple flow, with an OpenAIEmbeddings component hooked up to an AstraDBSearch. I have no other values set in my flow when I export it to json. 

The given python code is:
```
from langflow.load import run_flow_from_json
TWEAKS = {
  "OpenAIEmbeddings-sSuTz": {},
  "AstraDBSearch-avH6c": {}
}

result = run_flow_from_json(flow="Untitled document (24).json",
                            input_value="message",
                            tweaks=TWEAKS)
```

Once I add in my API keys / endpoint, I still have an empty `input value`. That makes sense to me, as I imagine I can do:
```
result = run_flow_from_json(flow="Untitled document (24).json",
                            input_value="message", # I would hope that this `input_value` is used as the `input_value` to `AstraDBSearch`. 
                            tweaks=TWEAKS)
```

However, it fails to build, saying: 
```
ValueError: Error running graph: Error building vertex Astra DB Search: AstraDBSearchComponent.build() missing 1 required positional argument: 'input_value'
```

Now, just for the sake of the argument, I added it directly to the tweaks instead:
```
        "AstraDBSearch-avH6c": {
             ...
            "input_value": "<my search query>",
        },

    result = run_flow_from_json(flow=flow, input_value="<does it matter what goes here now>", tweaks=TWEAKS)
```

Now, I get the error:
```
AttributeError: 'RunOutputs' object has no attribute 'output'
```

So questions for that are:
1) What purpose does the `input_value` in `run_flow_from_json` serve in this context? 
2) What is the output error - is it telling me that the vector search component is not a valid output component? 

** Version ** 
 - latest dev branch
 - python 3.11.2

**To Reproduce**
create flow, export to json, try run as json

Thanks!

**Additional context**
![Screenshot 2024-05-09 at 11 59 03 AM](https://github.com/langflow-ai/langflow/assets/122494242/d98bc06d-a82d-4935-b200-89bce9e0cda5)

**Comment by jordanrfrazier** [comment]
I see -- that's my mistake. I didn't even need the `output_component` parameter. The `outputs` issue was on my end.

**Comment by jordanrfrazier** [comment]
@dosu thanks, the issue relating to the `output` was my mistake. 

However, I am still curious about how I can run the flow by using the `input_value` from the `run_flow_from_json` function as the input to the my `AstraDBSearch` component.

**Comment by carlosrcoelho** [comment]
Hi @jordanrfrazier 

Do you still need any support with this issue?

**Comment by jordanrfrazier** [comment]
Hi @carlosrcoelho, I haven't tried running json as a flow in a while, so unsure. We can probably close this and I'll open a new one if I run into issues in the newer versions.
