### ISSUE TITLE
AstraDB component won't build citing OpenAI quota issue. 

### ISSUE THREAD

**Issue by AlastairJarvis** [langflow-ai/langflow#1871]
**Describe the bug**
I ran out of Pay as You Go OpenAI credits (actually dipped into a negative balance). When building, failed on the AstraDB step giving the following error message:

> ValueError: Error building vertex Astra DB Search: Error code: 429 - {'error':             
>                              {'message': 'You exceeded your current quota, please check your plan and                   
>                              billing details. For more information on this error, read the docs:                        
>                              https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type':                  
>                              'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

I still have plenty of credits left in my AstraDB account. 

I have topped up my OpenAi account and have credit available. Error still occurs. 

I can't tell from the Error message in LangFlow if this is an AstraDB issue (fails is happening during this build step), an OpenAI balance issue (I had no more OpenAI credit when the build first failed in this way), or if I've exceeded a Rate limit (is this an embedding rate limit since it happens in the AstraDB step and I'm using OpenAI Embeddings?).

I managed to workaround by changing the model to gpt-4-turbo. gpt-3.5-turbo and gpt-4 have Requests per Day limits. gpt4-turbo does not. Maybe the requests per day quota is shared between 3.5 and 4 and I hit it.

At any rate, the error message is confusing.  

**Browser and Version**
 - Browser: chrome on mac
 - Version: 1.0.0a29

**Comment by nicoloboschi** [comment]
The error happens because Astra, in order to get the correct number of vector dimensions, perform a call to the embeddings (openAI). Since you don't have credits, it can't get the n. of dimensions and it fails.
