### ISSUE TITLE
Cannot edit Environment Variables for sign in and sign up

### ISSUE THREAD

**Issue by hts2008** [langflow-ai/langflow#1872]
**Describe the bug**
I follow the guide on https://docs.langflow.org/guidelines/login to create user and disable auto login.
When run the command "langflow run --env-file .env" it is running langflow automatically. So I can not run the next command to execute:
export LANGFLOW_AUTO_LOGIN=False
export LANGFLOW_SUPERUSER=admin
export LANGFLOW_SUPERUSER_PASSWORD=securepassword
....

**Browser and Version**
 - Browser [EDGE]
 - Version [v1.0.0a30]

**Screenshots**
![image](https://github.com/langflow-ai/langflow/assets/115854561/7bda97cd-8e2a-41e9-b3ea-55d2f8898677)

**Additional context**
How can I run these export command? or where can I edit these info?

Thank you

**Comment by hts2008** [comment]
Hi Teams,

Thanks for reply.

But I have some doubt that. How can I edit .env file?
Which command I need to execute?

I'm install it on Windows 11.

Thank you.

**Comment by hts2008** [comment]
Thank you dosu,

about the .env, where can I save it? which the location path to save?

Thank you.

**Comment by hts2008** [comment]
Hi dosu,

I try to create and save the .env file into root of langflow. But there are nothing happen.

**Comment by jtoy** [comment]
I have run into the same issue on ubuntu.  I dont think langflow can actually read from an env file.
