### ISSUE TITLE
Passing a new query in retrieval QA chain its building the entire flow.

### ISSUE THREAD

**Issue by baksh07** [langflow-ai/langflow#1881]
i have created a RAG pipeline using langflow, Where im using Huggingfacepipeline for llm, HuggingFaceEmbeddings for Embeddings and retrivalQA as chain and chat input and chat output for the same. So when i enter playground and send a query its builing the flow from start like documentloader, text splitters, embeddings.. and so on any suggestion will be of big help i will be attaching the image of my flow
![Screenshot 2024-05-13 094923](https://github.com/langflow-ai/langflow/assets/129616972/9312394d-5a9d-4ffb-9996-63563ae6ed05)

**Comment by anovazzi1** [comment]
Hello,
Sorry for the delay. Did you try using the new version? Does the error still persist with the new Freeze option?
example:
![image](https://github.com/langflow-ai/langflow/assets/70824914/b4408c6d-8ee9-4a83-a672-1b1e76a9f9f3)

**Comment by carlosrcoelho** [comment]
Hi @baksh07,

I hope you're doing well. Just a friendly reminder that if we do not hear back from you within the next 3 days, we will close this issue. If you need more time or further assistance, please let us know. 

Thank you for your understanding!

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
