### ISSUE TITLE
Langflow global variables are "unset" on UI refresh

### ISSUE THREAD

**Issue by SonicDMG** [langflow-ai/langflow#1886]
**Describe the bug**
Langflow [Version v1.0.0a32]
All global variables are unset from components any time the Langflow UI is refreshed.

Global variables are set and saved with the flow. These work properly when exiting the flow and running the flow via the playground. However, if the browser is refreshed at any point all global variable references in components will be unset.

**Browser and Version**
 - Brave
 - [Version 1.64.122 Chromium: 123.0.6312.122 (Official Build) (arm64)](https://brave.com/latest/)

**To Reproduce**
1. Open any flow
2. Set a global variable within a component
3. Refresh the UI
4. Any global variables set in components will then be unset

**Screenshots**
![2024-05-13 15 13 49](https://github.com/langflow-ai/langflow/assets/23346205/766c29b2-af51-4248-b5c1-8f4a0e536a7d)

**Additional context**
Even though the default setting for LANGFLOW_REMOVE_API_KEYS is no-remove-api-keys according to the README https://github.com/langflow-ai/langflow/blob/main/README.md I attempted to explicitly set this value to no effect.

**Comment by anovazzi1** [comment]
Hello,
Sorry for the delay. Did you try using the new version? Does the error still persist?

**Comment by carlosrcoelho** [comment]
Hi @SonicDMG ,

I hope you're doing well. Just a friendly reminder that if we do not hear back from you within the next 3 days, we will close this issue. If you need more time or further assistance, please let us know. 

Thank you for your understanding!

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.

**Comment by evolu8** [comment]
I'm still getting this bug. If it persists I will have to drop use of langflow I am losing many hours to this.
