### ISSUE TITLE
Wrong version

### ISSUE THREAD

**Issue by uiaiek32** [langflow-ai/langflow#1894]
The Deploy on Railway button on Langflow GitHub page deploys the last version and not the new version

**Comment by uiaiek32** [comment]
what verdion pf langflow is the deploy on railway button?

**Comment by uiaiek32** [comment]
how can i deploy the latest version? because I can deploy only 0.6.18

**Comment by anovazzi1** [comment]
This issue should not occur again after version 1.0.
