### ISSUE TITLE
Agent tools / function calling UX improvement

### ISSUE THREAD

**Issue by jaschahuisman** [langflow-ai/langflow#1898]
Is it (please) possible to make function calling (tools) easier and more understandable?

A good example is https://app.millis.ai/, which has an interface/form that makes you fill in function name, description and a webhook url (which is also a nice feature I would like to see back in langflow, so we can invoke external tools/do requests from within LF, but in langflow this could be ofcourse your custom code), and most importantly: the parameters: see image.

It would be nice to see this in some sort of node, that can be used by some sort of agent/LLM.

Overall I would like to see more improvements on these simple user experience things that could make langflow a lot better than it already is.

### Example of millis
<img width="531" alt="millis function calling" src="https://github.com/langflow-ai/langflow/assets/39152972/67639be6-c685-4183-867f-60fad54b4da4">

**Comment by yamonkjd** [comment]
I believe that the descriptions and values in the attached image are sufficiently provided by LF as well (such as description and format). The parameters can be adequately implemented using DICT or Nestdict to create the desired components.

However, it would be beneficial if there were a property that allows the URL field to be easily copied to the clipboard at the component level, as shown in the image.
https://github.com/langflow-ai/langflow/pull/1766

LF also has a unique data exchange type called Recode, so I am also considering suggestions for code naming and variable mapping. Below, I provide developer-friendly variable mapping in the style of POST MAN. It would be beneficial to have this kind of format. (Of course, even now, it is possible to handle data directly within custom components by replacing the value of an API endpoint with the input value of the component.)

![image](https://github.com/langflow-ai/langflow/assets/141118378/f2b65f17-86b6-4bf5-946d-5febf8fb12a7)

![image](https://github.com/langflow-ai/langflow/assets/141118378/0cb38261-abab-4ca8-b6d8-191648e87aa2)
