### ISSUE TITLE
ModuleNotFoundError: No module named 'langchain_experimental.agents'

### ISSUE THREAD

**Issue by mehulgit** [langflow-ai/langflow#1899]
Followed the following instructions:

python -m pip install langflow -U

python -m langflow run

Get the ModuleNotFoundError: No module named 'langchain_experimental.agents' error

Also installed langchain-experimental using 'pip install langchain-experimental'

**Comment by nicoloboschi** [comment]
@mehulgit could you retry with the latest version (1.0.5)?

**Comment by carlosrcoelho** [comment]
Hi @mehulgit, 

I hope you're doing well. Just a friendly reminder that if we do not hear back from you within the next 3 days, we will close this issue. If you need more time or further assistance, please let us know. 

Thank you for your understanding!

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
