### ISSUE TITLE
updating prompt template severs existing connections in flow

### ISSUE THREAD

**Issue by bettinaswynnerton** [langflow-ai/langflow#1903]
**Describe the bug**
Updating the prompt template severs all connections in the flow

**Browser and Version**
 - Chrome
 - Version [124]

**To Reproduce**
Steps to reproduce the behavior in prompt component
1. Go to 'template' field
2. update the prompt
3. Save
4. See error: all connections are severed, both inbound and outbound. 

**Additional context**
This happens the first time when updating a newly created prompt component. After recreating the connections and repeating these steps, those connections stay. We used the Vector Store RAG template

**Comment by anovazzi1** [comment]
Hello,
Sorry for the delay. Did you try using the new version? Does the error still persist?

**Comment by carlosrcoelho** [comment]
Hi @bettinaswynnerton 
 
I hope you're doing well. Just a friendly reminder that if we do not hear back from you within the next 3 days, we will close this issue. If you need more time or further assistance, please let us know. 

Thank you for your understanding!

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
