### ISSUE TITLE
Astra Connector needs a truncate operation

### ISSUE THREAD

**Issue by zznate** [langflow-ai/langflow#1904]
**Describe the bug**
When I use the Astra Connector widget, it would be great if it had an option in a submenu to "truncate" the collections.

Version: 
```Starting Langflow v1.0.0a33...```

When working back and forth with a flow that had an astra connection, the first couple of iterations usually end up with the wrong content stored in the DB. Astra supports a high-performance "delete everythign in a table" operation called `TRUNCATE` that can be used to clear out unwanted test data with a click. 

Obviously this should be in a sub-menu and include a "Are you sure?" confirmation dialog given the stakes of performing this operation.

**Comment by carlosrcoelho** [comment]
Hi @zznate 
Do you need any assistance with this case? If not, please let us know if this issue can be closed.

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
