### ISSUE TITLE
Astra UI component: Astra URL component is not validated on entry

### ISSUE THREAD

**Issue by zznate** [langflow-ai/langflow#1905]
The UI component for astra does not validate the connection URL on text entry. 

When pasted in, the dialog should check if it is a legal URL before trying anything else. I accedental pasted in a token, and did not realise it until the "run" phase even though it clearly was not a URL

Version:
```
Starting Langflow v1.0.0a33...
```

**Comment by carlosrcoelho** [comment]
Hey @zznate 

Have you tried the new version yet? Please check it out and let me know if the issue persists.

**Comment by carlosrcoelho** [comment]
@zznate 

Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
