### ISSUE TITLE
ERR by redis : RedisCache.upsert() got an unexpected keyword argument 'lock'

### ISSUE THREAD

**Issue by songjinu** [langflow-ai/langflow#1909]
**Describe the bug**
I got a error when use redis cache.
> RedisCache.upsert() got an unexpected keyword argument 'lock'
I setted env : LANGFLOW_CACHE_TYPE= redis

- tested tag : v1.0.0a32

```
Error checking build status: RedisCache.upsert() got an unexpected keyword argument 'lock'
```

**Comment by songjinu** [comment]
I used to LANGFLOW_CACHE_TYPE= redis on 0.6.17.
I am in 1.0.0a44 now. 
I have to use multi process (uvicone --worker) ,because I have many user.
I need to use independent cache like RedisCache.
please help~

**Comment by anovazzi1** [comment]
Hello,
Sorry for the delay. Did you try using the new version? Does the error still persist?

**Comment by carlosrcoelho** [comment]
Hi @songjinu, 

I hope you're doing well. Just a friendly reminder that if we do not hear back from you within the next 3 days, we will close this issue. If you need more time or further assistance, please let us know. 

Thank you for your understanding!

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
