### ISSUE TITLE
version

### ISSUE THREAD

**Issue by uiaiek32** [langflow-ai/langflow#1910]
I can't deploy the latest version of langflow on raylway

**Comment by uiaiek32** [comment]
i can't deploy the latest version

**Comment by anovazzi1** [comment]
This issue should not occur again after version 1.0.

**Comment by carlosrcoelho** [comment]
Hi @uiaiek32 , 

I hope you're doing well. Just a friendly reminder that if we do not hear back from you within the next 3 days, we will close this issue. If you need more time or further assistance, please let us know. 

Thank you for your understanding!

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
