### ISSUE TITLE
Delete Edge Not Working

### ISSUE THREAD

**Issue by satpalsr** [langflow-ai/langflow#1914]
**Describe the bug**
I'm on latest dev branch.

I am not able to delete an edge between two nodes.
I have check logs and see that edge id is empty when pressing delete button.
Also may be edge should glow up a bit when selected to show clear indication of it being selected.
or a (x) cross button can be added between edges to easily delete it.

**Browser and Version**
 - Chrome

**To Reproduce**
1. Connect two Nodes
2. Left click on edge (I do see cursor changing to hand icon)
3. Press delete.

**Comment by satpalsr** [comment]
@dosu When I select an edge, the edge id or info does not appear in lastselection
lastSelection: {"nodes":[],"edges":[]}

**Comment by satpalsr** [comment]
@dosu The edge is correctly shown here when selected
```
const onSelectionChange = useCallback(
  (flow: OnSelectionChangeParams): void => {
    setLastSelection(flow);
  },
  [],
);
```

However, the lastSelection is empty here
```
if (!isWrappedWithClass(event, "nodelete")) {
        if (
          (event.key === "Delete" || event.key === "Backspace") &&
          lastSelection
        ) {
          event.preventDefault();
          takeSnapshot();
          console.log(`lastSelection: ${JSON.stringify(lastSelection)}`);
          console.log(`DeleteNode ${lastSelection.nodes.map((node) => node.id)}`);
          deleteNode(lastSelection.nodes.map((node) => node.id));
          console.log(`DeleteEdge ${lastSelection.edges.map((edge) => edge.id)}`);
          deleteEdge(lastSelection.edges.map((edge) => edge.id));
        }
      }
    };
    ```
    
    However, If I hardcode the id here for deleteEdge then it works. So for sure the problem is that lastselection don't have the selected edge here before deleting it.

**Comment by anovazzi1** [comment]
Hello @satpalsr,
Sorry for the delay. Did you try using the new version? Does the error still persist?

**Comment by carlosrcoelho** [comment]
Hi @satpalsr, 

I hope you're doing well. Just a friendly reminder that if we do not hear back from you within the next 3 days, we will close this issue. If you need more time or further assistance, please let us know. 

Thank you for your understanding!

**Comment by satpalsr** [comment]
Resolved. Thanks.
