### ISSUE TITLE
I can't connect the new api on the langflow pre release

### ISSUE THREAD

**Issue by username5469** [langflow-ai/langflow#1924]
I can't connect the new api on the langflow pre release
something wrong with the body 

{"input_value": "message",
  "output_type": "chat",
  "input_type": "chat",
  "tweaks": [
  {
    "Prompt-fCVLk": {},
    "OpenAIModel-JxVwF": {},
    "ChatOutput-Hmqe8": {},
    "ChatInput-GH3N0": {}
  }
]
}

**Comment by username5469** [comment]
where do I find "Your output component identifier here" and "Your session ID here"?

**Comment by username5469** [comment]
I can't connect this body 

{"input_value": "message",
  "output_type": "chat",
  "input_type": "chat",
  "tweaks": [
  {
    "ChatInput-5sGZ2": {},
    "Prompt-M6Lnk": {},
    "OpenAIModel-OzdvL": {},
    "AstraDBSearch-aPVRb": {},
    "File-xdwIq": {},
    "RecursiveCharacterTextSplitter-yksdC": {},
    "AstraDB-RWIJY": {},
    "OpenAIEmbeddings-0K55b": {},
    "ChatOutput-Buvxl": {}
  }
]}

**Comment by anovazzi1** [comment]
Hello @username5469,
Sorry for the delay. Did you try using the new version? Does the error still persist?

**Comment by carlosrcoelho** [comment]
Hi @username5469 , 

I hope you're doing well. Just a friendly reminder that if we do not hear back from you within the next 3 days, we will close this issue. If you need more time or further assistance, please let us know. 

Thank you for your understanding!

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
