### ISSUE TITLE
I can't connect api to the new langflow pre release  this is the body

### ISSUE THREAD

**Issue by username5469** [langflow-ai/langflow#1925]
I can't connect api to the new langflow pre release  this is the body

{"input_value": "message",
"output_type": "chat",
"input_type": "chat",
"tweaks": [
{
"ChatInput-5sGZ2": {},
"Prompt-M6Lnk": {},
"OpenAIModel-OzdvL": {},
"AstraDBSearch-aPVRb": {},
"File-xdwIq": {},
"RecursiveCharacterTextSplitter-yksdC": {},
"AstraDB-RWIJY": {},
"OpenAIEmbeddings-0K55b": {},
"ChatOutput-Buvxl": {}
}
]}

**Comment by username5469** [comment]
where do I find flow_id and session_id and where sould I put them?

**Comment by carlosrcoelho** [comment]
Hi @username5469 ,
 
I hope you're doing well. Just a friendly reminder that if we do not hear back from you within the next 3 days, we will close this issue. If you need more time or further assistance, please let us know. 

Thank you for your understanding!

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
