### ISSUE TITLE
Error in API cURL option, JSON malformed and missing closing } on tweaks object

### ISSUE THREAD

**Issue by SonicDMG** [langflow-ai/langflow#1933]
**Describe the bug**
The tweaks object is missing its closing } which causes a JSON error rendering the cURL command inoperable

**Browser and Version**
 - Warp terminal
 - Version v0.2024.05.14.08.01.stable_04

**To Reproduce**
1. Create a working flow
2. Click on the API button in the lower right
3. Copy the cURL output and paste into terminal
4. Execute the command

**Screenshots**
https://www.loom.com/share/e4a72b81515c4776bd23408d8bf62d72?sid=f93c9b5e-253b-4180-a387-c2478f602c0f

![Screenshot 2024-05-20 at 3 23 51 PM](https://github.com/langflow-ai/langflow/assets/23346205/361c505e-d733-4a11-abb8-a7c7e05ee703)

**Additional context**

**Comment by anovazzi1** [comment]
fixed in  [a36](https://github.com/langflow-ai/langflow/releases/tag/v1.0.0a36)
