### ISSUE TITLE
Lock type inconsistency between set_cache and upsert methods

### ISSUE THREAD

**Issue by liuzh1516** [langflow-ai/langflow#1936]
**Describe the bug**
There is an inconsistency in the lock types used between the `set_cache` and `upsert` methods. This can potentially lead to runtime errors due to the mismatch of `asyncio.Lock` and `threading.Lock`.
The asyncio.Lock implements the __aenter__ method, which requires usage with async with lock, whereas threading.Lock implements the __enter__ method, which requires usage with with lock. In the upsert method, the line with lock or self._lock: only works correctly if lock is an instance of threading.Lock. When lock is an instance of asyncio.Lock, it will fail because asyncio.Lock does not implement the __enter__ method, resulting in an error as __enter__ cannot be found.

**Browser and Version**
 - chrome
 - 1.0.0a34
 - python 3.10

**To Reproduce**
1、Drag a Chat Input onto the canvas.
2、Click "Build" at the top right corner to validate status.
3、Observe the error message that appears at the bottom left corner.

**Screenshots**
![image](https://github.com/langflow-ai/langflow/assets/6716576/bcf6f941-7093-4271-a69a-f3ce16f4f312)

![image](https://github.com/langflow-ai/langflow/assets/6716576/eef3d57d-70a3-451c-91b5-eea680ceae71)

**Comment by tjroamer** [comment]
I encountered the same problem. The error was gone after I changed the value of `LANGFLOW_CACHE_TYPE` to `async` in the `.env` file. This is not documented, however. In the .env.example, only `memory` and `redis` are mentioned.

@dosu

**Comment by Alperemrehas** [comment]
> I encountered the same problem. The error was gone after I changed the value of `LANGFLOW_CACHE_TYPE` to `async` in the `.env` file. This is not documented, however. In the .env.example, only `memory` and `redis` are mentioned.
> 
> @dosu

Thank you for the information. It worked for me.

**Comment by songjinu** [comment]
I use 2 server. 
can I use the cache when i use LANGFLOW_CACHE_TYPE=async ?

**Comment by Alperemrehas** [comment]
> I use 2 server. can I use the cache when i use LANGFLOW_CACHE_TYPE=async ? How can i use RedisCache ?

Actually I am not sure this is working with deployed version on a server. Because lately I'm experiencing vertices build endpoint failure which I am connecting to the cache issue. After working several days this specific endpoint just stops. Maybe @ogabrielluiz have idea about this. This maybe a serious bug.

**Comment by anovazzi1** [comment]
Hello there,
Sorry for the delay. Did you try using the new version? Does the error still persist?

**Comment by carlosrcoelho** [comment]
Hi @liuzh1516 ,
 
I hope you're doing well. Just a friendly reminder that if we do not hear back from you within the next 3 days, we will close this issue. If you need more time or further assistance, please let us know. 

Thank you for your understanding!

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
