### ISSUE TITLE
poetry going in an infinite loop in installing spacy

### ISSUE THREAD

**Issue by shashj123** [langflow-ai/langflow#1944]
**Describe the bug**
Poetry installs several version of spacy

**Browser and Version**
 - Version [e.g. 22] 1.0.0.a0034

**Comment by shashj123** [comment]
I was just installing the pre release, it was working fine until now

**Comment by anovazzi1** [comment]
Hello @shashj123,
Sorry for the delay. Did you try using the new version? Does the error still persist?

**Comment by shashj123** [comment]
Did not upgrade yet, I will mark this as close since I saw a solution posted even for that version
