### ISSUE TITLE
 pre-release version Installation with pip failed and spacy install loop

### ISSUE THREAD

**Issue by liuzhanghello** [langflow-ai/langflow#1945]
**Describe the bug**
Install the pre-release version failed with command: 
python -m pip install langflow --pre --force-reinstall

**To Reproduce**
python:3.10.14
run command
python -m pip install langflow --pre --force-reinstall

logs:

 Using cached spacy-4.0.0.dev2-cp310-cp310-macosx_11_0_arm64.whl.metadata (27 kB)
  Using cached spacy-4.0.0.dev1-cp310-cp310-macosx_11_0_arm64.whl.metadata (19 kB)
  Using cached spacy-4.0.0.dev0-cp310-cp310-macosx_11_0_arm64.whl.metadata (25 kB)
Collecting spacy-legacy<3.1.0,>=3.0.11 (from spacy->llama-index-core<0.11.0,>=0.10.38->llama-index<0.11.0,>=0.10.13->langflow)
  Using cached spacy_legacy-3.0.12-py2.py3-none-any.whl.metadata (2.8 kB)
Collecting spacy (from llama-index-core<0.11.0,>=0.10.38->llama-index<0.11.0,>=0.10.13->langflow)
  Using cached spacy-3.7.4-cp310-cp310-macosx_11_0_arm64.whl.metadata (27 kB)
Collecting thinc<8.3.0,>=8.2.2 (from spacy->llama-index-core<0.11.0,>=0.10.38->llama-index<0.11.0,>=0.10.13->langflow)
  Using cached thinc-8.2.3-cp310-cp310-macosx_11_0_arm64.whl.metadata (15 kB)
Collecting spacy (from llama-index-core<0.11.0,>=0.10.38->llama-index<0.11.0,>=0.10.13->langflow)
  Using cached spacy-3.7.2-cp310-cp310-macosx_11_0_arm64.whl.metadata (25 kB)
  Using cached spacy-3.7.1-cp310-cp310-macosx_11_0_arm64.whl.metadata (25 kB)
  Using cached spacy-3.7.0-cp310-cp310-macosx_11_0_arm64.whl.metadata (25 kB)
INFO: pip is still looking at multiple versions of spacy to determine which version is compatible with other requirements. This could take a while.
  Using cached spacy-3.7.0.dev0-cp310-cp310-macosx_11_0_arm64.whl.metadata (19 kB)
Collecting thinc<8.2.0,>=8.1.8 (from spacy->llama-index-core<0.11.0,>=0.10.38->llama-index<0.11.0,>=0.10.13->langflow)
  Using cached thinc-8.1.12-cp310-cp310-macosx_11_0_arm64.whl.metadata (15 kB)
Collecting spacy (from llama-index-core<0.11.0,>=0.10.38->llama-index<0.11.0,>=0.10.13->langflow)
  Using cached spacy-3.6.1-cp310-cp310-macosx_11_0_arm64.whl.metadata (25 kB)
  Using cached spacy-3.6.0-cp310-cp310-macosx_11_0_arm64.whl.metadata (19 kB)
  Using cached spacy-3.6.0.dev1-cp310-cp310-macosx_11_0_arm64.whl.metadata (19 kB)
  Using cached spacy-3.6.0.dev0-cp310-cp310-macosx_11_0_arm64.whl.metadata (25 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
  Using cached spacy-3.5.4-cp310-cp310-macosx_11_0_arm64.whl.metadata (25 kB)
  Using cached spacy-3.5.3-cp310-cp310-macosx_11_0_arm64.whl.metadata (25 kB)
  Using cached spacy-3.5.2-cp310-cp310-macosx_11_0_arm64.whl.metadata (25 kB)
  Using cached spacy-3.5.1-cp310-cp310-macosx_11_0_arm64.whl.metadata (25 kB)
  Using cached spacy-3.5.0-cp310-cp310-macosx_11_0_arm64.whl.metadata (25 kB)
  Using cached spacy-3.4.4-cp310-cp310-macosx_11_0_arm64.whl.metadata (24 kB)
Collecting wasabi<1.1.0,>=0.9.1 (from spacy->llama-index-core<0.11.0,>=0.10.38->llama-index<0.11.0,>=0.10.13->langflow)
  Using cached wasabi-0.10.1-py3-none-any.whl.metadata (28 kB)
Collecting spacy (from llama-index-core<0.11.0,>=0.10.38->llama-index<0.11.0,>=0.10.13->langflow)
  Using cached spacy-3.4.3-cp310-cp310-macosx_11_0_arm64.whl.metadata (24 kB)
  Using cached spacy-3.4.2-cp310-cp310-macosx_11_0_arm64.whl.metadata (24 kB)
  Using cached spacy-3.4.1-cp310-cp310-macosx_11_0_arm64.whl.metadata (24 kB)
  Using cached spacy-3.4.0-cp310-cp310-macosx_11_0_arm64.whl.metadata (24 kB)
  Using cached spacy-3.3.3-cp310-cp310-macosx_11_0_arm64.whl.metadata (23 kB)
Collecting thinc<8.1.0,>=8.0.14 (from spacy->llama-index-core<0.11.0,>=0.10.38->llama-index<0.11.0,>=0.10.13->langflow)
  Using cached thinc-8.0.17-cp310-cp310-macosx_11_0_arm64.whl.metadata (14 kB)
Collecting blis<0.8.0,>=0.4.0 (from spacy->llama-index-core<0.11.0,>=0.10.38->llama-index<0.11.0,>=0.10.13->langflow)
  Using cached blis-0.7.11-cp310-cp310-macosx_11_0_arm64.whl.metadata (7.4 kB)
Collecting spacy (from llama-index-core<0.11.0,>=0.10.38->llama-index<0.11.0,>=0.10.13->langflow)
  Using cached spacy-3.3.2-cp310-cp310-macosx_11_0_arm64.whl.metadata (23 kB)
  Using cached spacy-3.3.1-cp310-cp310-macosx_11_0_arm64.whl.metadata (23 kB)
  Using cached spacy-3.3.0-cp310-cp310-macosx_11_0_arm64.whl.metadata (23 kB)
  Using cached spacy-3.3.0.dev0.tar.gz (1.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
...
Using cached spacy-3.0.6.tar.gz (7.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [164 lines of output]
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          int length
      
      
      cdef class Vocab:
          cdef Pool mem
          cpdef readonly StringStore strings
                ^
      ------------------------------------------------------------
      
      spacy/vocab.pxd:28:10: Variables cannot be declared with 'cpdef'. Use 'cdef' instead.
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      
      
      cdef class Vocab:
          cdef Pool mem
          cpdef readonly StringStore strings
          cpdef public Morphology morphology
                ^
      ------------------------------------------------------------
      
      spacy/vocab.pxd:29:10: Variables cannot be declared with 'cpdef'. Use 'cdef' instead.
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      
      cdef class Vocab:
          cdef Pool mem
          cpdef readonly StringStore strings
          cpdef public Morphology morphology
          cpdef public object vectors
                ^
      ------------------------------------------------------------
      
      spacy/vocab.pxd:30:10: Variables cannot be declared with 'cpdef'. Use 'cdef' instead.
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      cdef class Vocab:
          cdef Pool mem
          cpdef readonly StringStore strings
          cpdef public Morphology morphology
          cpdef public object vectors
          cpdef public object _lookups
                ^
      ------------------------------------------------------------
      
      spacy/vocab.pxd:31:10: Variables cannot be declared with 'cpdef'. Use 'cdef' instead.
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          cdef Pool mem
          cpdef readonly StringStore strings
          cpdef public Morphology morphology
          cpdef public object vectors
          cpdef public object _lookups
          cpdef public object writing_system
                ^
      ------------------------------------------------------------
      
      spacy/vocab.pxd:32:10: Variables cannot be declared with 'cpdef'. Use 'cdef' instead.
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          cpdef readonly StringStore strings
          cpdef public Morphology morphology
          cpdef public object vectors
          cpdef public object _lookups
          cpdef public object writing_system
          cpdef public object get_noun_chunks
                ^
      ------------------------------------------------------------
      
      spacy/vocab.pxd:33:10: Variables cannot be declared with 'cpdef'. Use 'cdef' instead.
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          cdef float prior_prob
      
      
      cdef class KnowledgeBase:
          cdef Pool mem
          cpdef readonly Vocab vocab
                ^
      ------------------------------------------------------------
      
      spacy/kb.pxd:31:10: Variables cannot be declared with 'cpdef'. Use 'cdef' instead.
      Copied /private/var/folders/7m/w6zcz4y51cq7f5m7gf7khbr8ylhvxl/T/pip-install-01vy4h3g/spacy_358c5b6f2bea4553b227705081fd4642/setup.cfg -> /private/var/folders/7m/w6zcz4y51cq7f5m7gf7khbr8ylhvxl/T/pip-install-01vy4h3g/spacy_358c5b6f2bea4553b227705081fd4642/spacy/tests/package
      Copied /private/var/folders/7m/w6zcz4y51cq7f5m7gf7khbr8ylhvxl/T/pip-install-01vy4h3g/spacy_358c5b6f2bea4553b227705081fd4642/pyproject.toml -> /private/var/folders/7m/w6zcz4y51cq7f5m7gf7khbr8ylhvxl/T/pip-install-01vy4h3g/spacy_358c5b6f2bea4553b227705081fd4642/spacy/tests/package
      Cythonizing sources
      Compiling spacy/training/example.pyx because it changed.
      Compiling spacy/parts_of_speech.pyx because it changed.
      Compiling spacy/strings.pyx because it changed.
      Compiling spacy/lexeme.pyx because it changed.
      Compiling spacy/vocab.pyx because it changed.
      Compiling spacy/attrs.pyx because it changed.
      Compiling spacy/kb.pyx because it changed.
      Compiling spacy/ml/parser_model.pyx because it changed.
      Compiling spacy/morphology.pyx because it changed.
      Compiling spacy/pipeline/dep_parser.pyx because it changed.
      Compiling spacy/pipeline/morphologizer.pyx because it changed.
      Compiling spacy/pipeline/multitask.pyx because it changed.
      Compiling spacy/pipeline/ner.pyx because it changed.
      Compiling spacy/pipeline/pipe.pyx because it changed.
      Compiling spacy/pipeline/trainable_pipe.pyx because it changed.
      Compiling spacy/pipeline/sentencizer.pyx because it changed.
      Compiling spacy/pipeline/senter.pyx because it changed.
      Compiling spacy/pipeline/tagger.pyx because it changed.
      Compiling spacy/pipeline/transition_parser.pyx because it changed.
      Compiling spacy/pipeline/_parser_internals/arc_eager.pyx because it changed.
      Compiling spacy/pipeline/_parser_internals/ner.pyx because it changed.
      Compiling spacy/pipeline/_parser_internals/nonproj.pyx because it changed.
      Compiling spacy/pipeline/_parser_internals/_state.pyx because it changed.
      Compiling spacy/pipeline/_parser_internals/stateclass.pyx because it changed.
      Compiling spacy/pipeline/_parser_internals/transition_system.pyx because it changed.
      Compiling spacy/pipeline/_parser_internals/_beam_utils.pyx because it changed.
      Compiling spacy/tokenizer.pyx because it changed.
      Compiling spacy/training/align.pyx because it changed.
      Compiling spacy/training/gold_io.pyx because it changed.
      Compiling spacy/tokens/doc.pyx because it changed.
      Compiling spacy/tokens/span.pyx because it changed.
      Compiling spacy/tokens/token.pyx because it changed.
      Compiling spacy/tokens/span_group.pyx because it changed.
      Compiling spacy/tokens/graph.pyx because it changed.
      Compiling spacy/tokens/morphanalysis.pyx because it changed.
      Compiling spacy/tokens/_retokenize.pyx because it changed.
      Compiling spacy/matcher/matcher.pyx because it changed.
      Compiling spacy/matcher/phrasematcher.pyx because it changed.
      Compiling spacy/matcher/dependencymatcher.pyx because it changed.
      Compiling spacy/symbols.pyx because it changed.
      Compiling spacy/vectors.pyx because it changed.
      [ 1/41] Cythonizing spacy/attrs.pyx
      [ 2/41] Cythonizing spacy/kb.pyx
      Traceback (most recent call last):
        File "/opt/anaconda3/envs/lanflow-pre-version/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/anaconda3/envs/lanflow-pre-version/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/opt/anaconda3/envs/lanflow-pre-version/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/7m/w6zcz4y51cq7f5m7gf7khbr8ylhvxl/T/pip-build-env-8ujas5r2/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/7m/w6zcz4y51cq7f5m7gf7khbr8ylhvxl/T/pip-build-env-8ujas5r2/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/7m/w6zcz4y51cq7f5m7gf7khbr8ylhvxl/T/pip-build-env-8ujas5r2/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 224, in <module>
        File "<string>", line 211, in setup_package
        File "/private/var/folders/7m/w6zcz4y51cq7f5m7gf7khbr8ylhvxl/T/pip-build-env-8ujas5r2/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
          cythonize_one(*args)
        File "/private/var/folders/7m/w6zcz4y51cq7f5m7gf7khbr8ylhvxl/T/pip-build-env-8ujas5r2/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: spacy/kb.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by liuzhanghello** [comment]
sorry, The above method does not work.

**Comment by ogabrielluiz** [comment]
Hey @liuzhanghello 

How are you? 

Could you try running `python -m pip install setuptools -U` and try installing langflow again? 

This seems to be a problem with spacy and 3.12. 

Let me know if it works, please.

**Comment by burakakca** [comment]
Hi, I have same, I have forked version of langflow and I'm trying to setup github actions and I'm getting same error on Langflow Pre-release

**Comment by liuzhanghello** [comment]
@ogabrielluiz Thanks! it worked for me.

**Comment by liuzhanghello** [comment]
> Hey @liuzhanghello
> 
> How are you?
> 
> Could you try running `python -m pip install setuptools -U` and try installing langflow again?
> 
> This seems to be a problem with spacy and 3.12.
> 
> Let me know if it works, please.

Thanks! it worked for me.
