### ISSUE TITLE
Database Connection Pool Settings

### ISSUE THREAD

**Issue by fenss** [langflow-ai/langflow#1953]
**Describe the bug**
I use MySQL as the storage by setting environment variables:
```shell
export LANGFLOW_DATABASE_URL=mysql+pymysql://{mysql_user}:{mysql_pwd}@{mysql_host}:{mysql_port}/langflow
```
But I can not find any pool settings in the [database service code](https://github.com/langflow-ai/langflow/blob/v0.6.19/src/backend/langflow/services/database/service.py), so dead session comes out sometime because the networks setting.

Can you offer some options to set the SQLAlchemy pool? Thanks.

**Comment by carlosrcoelho** [comment]
Hi @fenss ,
 
I hope you're doing well. Just a friendly reminder that if we do not hear back from you within the next 3 days, we will close this issue. If you need more time or further assistance, please let us know. 

Thank you for your understanding!

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.

**Comment by Ballajaisheel** [comment]
Hi @fenss im trying to integrate a database directly to the agent,actually iam trying to develop a customer support agent which it responds to the user queries which are related to user manual and also it must fetch the data from the given data base and respond with respect to the product number and give details from DB....

Can you please tell me whether can i use URL from flask API and give as tool to the agent or i need to give PGVector to it.

Thank you
