### ISSUE TITLE
Pinecone Search Component not returning records

### ISSUE THREAD

**Issue by adampatarino** [langflow-ai/langflow#1957]
**Describe the bug**
The pinecone search component connects and makes requests to Pinecone successfully, but does not return records through the record connector.

**Browser and Version**
 - Browser chrome
 - Version 1.0 preview

**To Reproduce**

1. Add pinecone search component and add API key
2. connect embedding connector to openai embedding with 003-small model.
3. connect record connector to a valid component such as Record to Text or Record Output
4. Connect that component to a valid output
5. No text or record will display, all outputs will be blank in playground

**Screenshots**
![CleanShot 2024-05-23 at 09 24 55@2x](https://github.com/langflow-ai/langflow/assets/4479915/2d4fdceb-cee3-4d88-a3d5-25459cda7ac4)

**Additional context**
I've used a LLM model in the middle, but was confused why it didn't seem to respond using context. So I simplified the workflow to identify that Pinecone was not returning any context.

**Comment by ogabrielluiz** [comment]
Hey @adampatarino 

How are you? 

The problem is the `namespace` field. It is set to `advanced` so you probably have not set it. 

I'll update the component to make that visible. 

Thanks for the heads up!
