### ISSUE TITLE
Langflow run | Migration Issue

### ISSUE THREAD

**Issue by edwinjosechittilappilly** [langflow-ai/langflow#1958]
**Describe the bug**
SAWarning: WARNING: SQL-parsed foreign key constraint '('user_id', 'user', 'id')' could not be located in PRAGMA foreign_keys for table flow
  context.run_migrations()
[05/23/24 09:56:47] ERROR    2024-05-23 09:56:47 - ERROR    - service - AutogenerateDiffsDetected: {exc}                                                                                            service.py:162
                    ERROR    2024-05-23 09:56:47 - ERROR    - utils - Something went wrong running migrations. Please, run `langflow migration --fix`                                                  utils.py:51
                    ERROR    2024-05-23 09:56:47 - ERROR    - utils - Something went wrong running migrations. Please, run `langflow migration --fix`     

**Browser and Version**
Chrome

**To Reproduce**
pip install langflow
langflow run

**Screenshots**

<img width="1719" alt="Screenshot 2024-05-23 at 10 02 42 AM" src="https://github.com/langflow-ai/langflow/assets/15969583/d9abe0d2-bbf0-4fbf-b873-de302479ca74">

**Additional context**
Python: Python 3.11.9
Langflow: langflow 0.6.19

**Comment by sedhasukhdeep** [comment]
python -m langflow migration --fix worked for me on Mac

**Comment by ogabrielluiz** [comment]
Hey all. 

This is in version 0.6.19, correct?

You can try running `python -m langflow migration --test` to see if you can get some info on what is not working.
