### ISSUE TITLE
Installation Issue in MacOS

### ISSUE THREAD

**Issue by judevjoseph** [langflow-ai/langflow#1972]
Tried both the stable and latest pre-release version. Stuck with below error

Starting Langflow v1.0.0a37...
objc[26936]: +[__NSPlaceholderSet initialize] may have been in progress in another thread when fork() was called.
objc[26936]: +[__NSPlaceholderSet initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
[05/25/24 09:38:34] ERROR    2024-05-25 09:38:34 - ERROR    - glogging - Worker (pid:26936) was sent SIGABRT!                                                    glogging.py:272

System: Mac OS, Monterey
Python version : 3.10.11
PIP version : 24.0

**Comment by ogabrielluiz** [comment]
Hey @judevjoseph 

How are you?

This is related to the variable `OBJC_DISABLE_INITIALIZE_FORK_SAFETY`. 

You should set this in your rc file (e.g ~/.zshrc) to make this error go away:
`export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES`

**Comment by judevjoseph** [comment]
Thanks @ogabrielluiz .

Setting this value worked. In my case, it was with ".zprofile". Thanks for the support.
