### ISSUE TITLE
The error - duplicate 'folder_id' in alembic

### ISSUE THREAD

**Issue by songjinu** [langflow-ai/langflow#1988]
**Describe the bug**
The error - duplicate 'folder_id' in alembic

at src/backend/base/langflow/alembic/versions/012fb73ac359_add_folder_table.py
```
    if "folder_id" not in inspector.get_columns("flow"):
        with op.batch_alter_table("flow", schema=None) as batch_op:
            batch_op.add_column(sa.Column("folder_id", sqlmodel.sql.sqltypes.GUID(), nullable=True))
            batch_op.create_foreign_key("flow_folder_id_fkey", "folder", ["folder_id"], ["id"])
            batch_op.drop_column("folder")
```
inspector.get_columns("flow") return List[Dict]
I modifed like this
```
    flow = inspector.get_columns("flow")
    if any('folder_id' in columns["name"] for columns in flow):
        with op.batch_alter_table("flow", schema=None) as batch_op:
            batch_op.create_foreign_key("flow_folder_id_fkey", "folder", ["folder_id"], ["id"])
            batch_op.drop_column("folder")
    else:
        with op.batch_alter_table("flow", schema=None) as batch_op:
            batch_op.add_column(sa.Column("folder_id", sqlmodel.sql.sqltypes.GUID(), nullable=True))
            batch_op.create_foreign_key("flow_folder_id_fkey", "folder", ["folder_id"], ["id"])
            batch_op.drop_column("folder")
```

**Browser and Version**
 - Browser [chrome]
 - Version [v1.0.0.a37]

**Comment by anovazzi1** [comment]
Hello,
Sorry for the delay. Did you try using the new version? Does the error still persist?

**Comment by carlosrcoelho** [comment]
Hi @songjinu ,
 
I hope you're doing well. Just a friendly reminder that if we do not hear back from you within the next 3 days, we will close this issue. If you need more time or further assistance, please let us know. 

Thank you for your understanding!

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
