### ISSUE TITLE
Unable to upload file to folder

### ISSUE THREAD

**Issue by jordanrfrazier** [langflow-ai/langflow#1995]
**Describe the bug**
Unable to upload file to folder due to key error when selecting `folder_name` from the `flow. I see that a recent commit has made it such that each flow will have a default folder name, if none exists, but this not backwards-compatible with existing flows made in <=v1.0.0a38. Also - I would have expected the payload to send _my_ folder that I want the flow created in, not for it to create a folder in my store. 

(EDIT: I see that that recent change was just for making sure the flow was _in_ a folder, but does not export that folder name in the json, so that's an invalid concern. Seems we just may need to pass the selected folder to the /folders/upload endpoint)

https://github.com/langflow-ai/langflow/blob/543e8d52afbb8e64ae22255909f4453484b2bb07/src/backend/base/langflow/api/v1/folders.py#L194

**Browser and Version**
 - Browser [e.g. chrome, safari] firefox
 - Version [e.g. 22] v1.0.0a38

**To Reproduce**
1. pip install 
2. run
3. create folder
4. upload a flow
5. see logs

**logs** 

```
                             │ langflow/.venv/lib/python3.11/site-packages/langflow/api/v1/folders.py:209 in upload_file                                  │                 
                             │                                                                                                                                                                                      │                 
                             │   206 │                                                                                                                                                                              │                 
                             │   207 │   folder_results = session.exec(                                                                                                                                             │                 
                             │   208 │   │   select(Folder).where(                                                                                                                                                  │                 
                             │ ❱ 209 │   │   │   Folder.name == data["folder_name"],                                                                                                                                │                 
                             │   210 │   │   │   Folder.user_id == current_user.id,                                                                                                                                 │                 
                             │   211 │   │   )                                                                                                                                                                      │                 
                             │   212 │   )                                                                                                                                                                          │                 
                             ╰──────────────────────────────────────────────────────────    
                             KeyError: 'folder_name'  
```

**Fix(?)** 
* Pass currently selected folder to payload when uploading
* Use that as the folder name in `/folders/upload` 
* Add test for `/folders/upload`

**Comment by jordanrfrazier** [comment]
I see. The upload button on the main page is specifically for uploading _folders_, not _flows_

**Comment by jordanrfrazier** [comment]
Is there a way to upload a Flow directly? I've been creating a blank project, then importing, but that doesn't update the Name or Description of the Flow. Can we have a direct "upload flow" option?

**Comment by nicoloboschi** [comment]
@jordanrfrazier to import a specific flow you need to create a new blank one, from the dropdown click "Import" and pass it the JSON file.

The "upload" button in the main page is for folders (I've sent this improvement https://github.com/langflow-ai/langflow/pull/2125)

**Comment by carlosrcoelho** [comment]
Hi @jordanrfrazier 

Do you need any assistance with this case? If not, please let us know if this issue can be closed.

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.

**Comment by maxpaynebupt** [comment]
> @jordanrfrazier to import a specific flow you need to create a new blank one, from the dropdown click "Import" and pass it the JSON file.
> 
> The "upload" button in the main page is for folders (I've sent this improvement #2125)

tried this, nothing imported.....
