### ISSUE TITLE
Langflow split text error

### ISSUE THREAD

**Issue by ssabn** [langflow-ai/langflow#1997]
Error when Split Text  the text file

![image](https://github.com/langflow-ai/langflow/assets/170921045/5cd5bbb5-4b05-4503-b31a-50aa1eeaa283)

Version V 1.0.0a38

**Comment by ogabrielluiz** [comment]
@dosu you should look into this file https://github.com/langflow-ai/langflow/blob/8f6b9d644367e0d958010f55b4484c912ed59002/src/backend/base/langflow/components/experimental/SplitText.py#L9
