### ISSUE TITLE
Feature Request: Increase length of Description field when sharing Flows

### ISSUE THREAD

**Issue by jordanrfrazier** [langflow-ai/langflow#2025]
**Summary**
Interested in an increase of the description field when sharing flows. Currently, I believe it's set to 200 chars. I'd like to be able to include lengthier descriptions - how to use it, common use cases, etc. 

Attempting to share a larger flow to the Store results in:
```
{'errors': [{'message': 'Value in collection "components" is too long.', 'extensions': {'code': 'VALUE_TOO_LONG', 'collection': 'components', 'field': None}}]}
```

Current version: v1.0.0a42

**Comment by anovazzi1** [comment]
This issue should not occur again after version 1.0.
