### ISSUE TITLE
vecs library for vector search 

### ISSUE THREAD

**Issue by legaltextai** [langflow-ai/langflow#2028]
i am using vecs library for vector search for its simplicity. but i can't figure out how to add it to langflow . should i add a custom component? thank you 
https://github.com/supabase/vecs

**Comment by anovazzi1** [comment]
Hi @legaltextai,
Creating a custom component is a great approach. Please take a look at the docs here: https://pre-release.langflow.org/

**Comment by carlosrcoelho** [comment]
Hi @legaltextai  ,
 
I hope you're doing well. Just a friendly reminder that if we do not hear back from you within the next 3 days, we will close this issue. If you need more time or further assistance, please let us know. 

Thank you for your understanding!

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
