### ISSUE TITLE
Langfuse doesn't compatible with Langflow version greater than 0.6.12 on Docker

### ISSUE THREAD

**Issue by laura-y7860** [langflow-ai/langflow#2031]
I misunderstood that Dockerfile inside of docker_example were using latest version of Docker but it was actually using one of the old tags in Docker Hub. As the title says, Integration with Langfuse doesn't seem to be working with the example on official Langfuse website if Langflow version is greater than 0.6.12(doesn't compatible with version 1.0.0a38 in my case)

**Comment by anovazzi1** [comment]
Hello,
Sorry for the delay. Did you try using the new version? Does the error still persist?

**Comment by marcochang1028** [comment]
I encounter the same problem, I just use langflowai/langflow:latest to build a container, and use the cmd below to test the connection, and return status 200.
docker exec -it langflow python -c "import requests, os; addr = os.environ.get('LANGFLOW_LANGFUSE_HOST'); print(addr); res = requests.get(addr, timeout=5); print(res.status_code)"

But I didn't see any logs write out to langfuse. 
Any suggestion?

**Comment by laura-y7860** [comment]
Thanks for your response @anovazzi1 

I've just tried it out with langflowai/langflow:1.0.5 but still its not capturing the log in Langfuse 🥲 only work in 0.6.12-ish

**Comment by anovazzi1** [comment]
@laura-y7860 @marcochang1028 
Thanks for the feedback! I'll take a look and fix it ASAP.

**Comment by carlosrcoelho** [comment]
A new Langfuse implementation is coming soon. We'll let you know as soon as we can.

**Comment by oranciog-bd** [comment]
@carlosrcoelho Any news about langfuse integration? Is it working with latest version of langfuse (2.79.0)?

**Comment by marcochang1028** [comment]
> @carlosrcoelho Any news about langfuse integration? Is it working with latest version of langfuse (2.79.0)?

I upgraded Langflow & Langfuse to the latest version last week, but I still can not make it work. Nothing logged into Langfuse.

**Comment by carlosrcoelho** [comment]
We’ve integrated with Langfuse starting from v1.0.17. Check out the link:
https://www.youtube.com/watch?v=SA9gGbzwNGU

**Comment by marcochang1028** [comment]
It works

> We’ve integrated with Langfuse starting from v1.0.17. Check out the link: https://www.youtube.com/watch?v=SA9gGbzwNGU

The setting steps in the video works.

The setting in the link below is out of date.
https://langfuse.com/docs/integrations/langflow

Thank you very much.
