### ISSUE TITLE
failing to load. Sorry, we found an unexpected error!

### ISSUE THREAD

**Issue by imaiimaiimaiimaiimaiimai** [langflow-ai/langflow#2040]
![image](https://github.com/langflow-ai/langflow/assets/168649859/65f0d75f-4161-4fd7-9d27-32b1d6e63ad2)

**Comment by nicoloboschi** [comment]
could you retry with the latest version? If the problem is still there, please re-open the issue.

**Comment by box9527** [comment]
I am still suffering this issue, version of langflow is 1.0.9
