### ISSUE TITLE
adding duckduckgo component in empty new project crashes the application...

### ISSUE THREAD

**Issue by aditya-altometa** [langflow-ai/langflow#2042]
javascript on browser console is showing following error, when duckduckgo component is added to the new project.

index-ef80b085.js:983 TypeError: Cannot read properties of undefined (reading 'template')
    at GenericNode.reactExports.useEffect.Gr (index-ef80b085.js:3655:11861)
    at Qj (index-ef80b085.js:983:26401)
    at Hk (index-ef80b085.js:983:46167)
    at Wk (index-ef80b085.js:983:44863)
    at Pk (index-ef80b085.js:983:43823)
    at Ek (index-ef80b085.js:983:40115)
    at jg (index-ef80b085.js:981:3468)
    at index-ef80b085.js:983:37247
overrideMethod @ console.js:273
Li @ index-ef80b085.js:983
Qi.ot.componentDidCatch.tt.callback @ index-ef80b085.js:983
sh @ index-ef80b085.js:981
kk @ index-ef80b085.js:983
ik @ index-ef80b085.js:983
hk @ index-ef80b085.js:983
Wk @ index-ef80b085.js:983
Pk @ index-ef80b085.js:983
Ek @ index-ef80b085.js:983
jg @ index-ef80b085.js:981
(anonymous) @ index-ef80b085.js:983
Show 1 more frame
Show less

**Comment by aditya-altometa** [comment]
@dosu, thank you for your quick response.
I was trying to just use the UI to build a simple usecase.
I am not sure where below code need to be added? can you help with that?

Regards,
Aditya
________________________________

**Comment by anovazzi1** [comment]
Hello,
Sorry for the delay. Did you try using the new version? Does the error still persist?

**Comment by carlosrcoelho** [comment]
Hi @aditya-altometa ,
 
I hope you're doing well. Just a friendly reminder that if we do not hear back from you within the next 3 days, we will close this issue. If you need more time or further assistance, please let us know. 

Thank you for your understanding!

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
