### ISSUE TITLE
Error building vertex Files: Module langflow.interface.custom.custom_component not found. Please install it and try again

### ISSUE THREAD

**Issue by brylie** [langflow-ai/langflow#2043]
When testing the default Document QA flow, I receive the following error after configuring the document and API key and sending a message in the playground:

> Error building vertex Files: Module langflow.interface.custom.custom_component not found. Please install it and try again

**Browser and Version**
 - Chrome Version 125.0.6422.114 (Official Build) (arm64)

**To Reproduce**
1. Go to My Collection
2. Click on New Project
3. Select "Document QA"
4. Choose a document in the "files" node
5. Configure an API key in the OpenAI node
6. Click "Playground"
7. Send a message
8. See error

**Comment by brylie** [comment]
@dosu, the following change to the code in the `Files` component in the "Document QA" example resolved the error:

```diff
---from langflow.interface.custom.custom_component import CustomComponent
+++from langflow import CustomComponent
```

**Comment by brylie** [comment]
@dosu, should I make a pull request so other people can avoid this issue? If so, what file(s) should I change?

**Comment by brylie** [comment]
@dosu, the import statement is located in Python code, but I can't find the source for the Python Files component in this repository. Perhaps it was uploaded to the Langflow Store?

**Comment by nicoloboschi** [comment]
could you retry with the latest version? If the problem is still there, please re-open the issue.
