### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by gamercoder153** [langflow-ai/langflow#2044]
I followed the installation instructions in the readme file 
First I ran this cmd in Windows `python -m pip install langflow -U`
and then I got this error in the terminal 
![lang (1)](https://github.com/langflow-ai/langflow/assets/168166085/7aa7c654-382b-4b51-bf92-96f16b45e030)
and after I ran this cmd `python -m langflow run`
then I got this error `No module named langflow.__main__; 'langflow' is a package and cannot be directly 
executed`

**Comment by nicoloboschi** [comment]
could you retry with the latest version? If the problem is still there, please re-open the issue.
