### ISSUE TITLE
unexpected error message when importing 0.6 ver export file in 1.0

### ISSUE THREAD

**Issue by DDT-scrip** [langflow-ai/langflow#2057]
I tried to import my 0.6 ver langflow json export file into 1.0 new project
then the unexpected error message pop up (giving me the link to create this issue)

simply go to the previous page won't refresh the page, the restart langflow button on the message won't work
have to go to the previous page and refresh manually to get rid of the error message

after the import whenever I click the new project, the error message will pop up
Having a fail to import safety will be much nicer

**Comment by nicoloboschi** [comment]
Have you tried with 1.0.x versions? If the error is still there, please add more details and reopen the issue.
