### ISSUE TITLE
Check unique_flow_name please.

### ISSUE THREAD

**Issue by songjinu** [langflow-ai/langflow#2059]
**Describe the bug**
Check unique_flow_name please.
I get error on 

>  batch_op.create_unique_constraint("unique_flow_name", ["user_id", "name"])

It seems to right 
> batch_op.create_unique_constraint("unique_flow_name", ["user_id", "folder_id", "name"])

**Browser and Version**
 - DB [mysql]
 - Version [a44]

**Comment by songjinu** [comment]
ok. 
I understand below is right.
> batch_op.create_unique_constraint("unique_flow_name", ["user_id", "name"])
I will be matching my data.
Thanks confirm .

**Comment by nicoloboschi** [comment]
please run `langflow migration run` and retry
