### ISSUE TITLE
Run Flow component fails to return output

### ISSUE THREAD

**Issue by rothnic** [langflow-ai/langflow#2061]
**Describe the bug**
Using the Run Flow component doesn't return any outputs from the flow that is ran.

**Browser and Version**
 - Browser: Arc Version 1.44.2 (50412), Chromium Engine Version 125.0.6422.112
 - Version: Langflow 1.0 a44 (docker)

**To Reproduce**
1. Build a simple flow that takes an input and returns an output
2. Save that flow
3. Build a new flow that takes a compatible input passes that to Run Flow configured to point to the previous flow created then returns an output
4. Execute the new parent flow that runs the child flow. It should execute fine, but the Run Flow component will show no outputs when hovering over the top right corner of the component
5. You will also see nothing go to the output component

**Screenshots**
![image](https://github.com/langflow-ai/langflow/assets/452052/7d710051-3e47-4824-ae4b-677966517078)
![image](https://github.com/langflow-ai/langflow/assets/452052/64532c57-6b53-4843-9598-d47b654cdb40)

**Additional context**

**Comment by rothnic** [comment]
* I also tested the sub flow component and confirmed the same problem.
* I dug around the code and without getting a full development environment setup, it was hard to tell much
* One thing i thought was odd was that the inputs into the run flow/sub flow component are passed as tweaks, rather than inputs. It seems like tweaks would be for constant values, not for more dynamic input values into a flow.

References:
* [run_flow](https://github.com/langflow-ai/langflow/blob/dev/src/backend/base/langflow/helpers/flow.py#L68) helper function
* [CustomComponent.run_flow method](https://github.com/langflow-ai/langflow/blob/dev/src/backend/base/langflow/custom/custom_component/custom_component.py#L438) - This is how the Sub Flow and Run Flow component calls the run_flow helper function
* Sub Flow Component Build method, [where it is building the inputs](https://github.com/langflow-ai/langflow/blob/dev/src/backend/base/langflow/components/experimental/SubFlow.py#L97) to call CustomComponent.run_flow

The suggestions by @dosu aren't relevant. The build method of the Sub Flow component isn't getting any results back from run_flow, which is the whole problem. The results are empty, which implies the sub flow isn't being called with the inputs correctly.

Here are some logs I found in the application, which might point to another issue, but can't tell if it is a consequence or cause of this issue. [Here is a link](https://github.com/langflow-ai/langflow/blob/82a3733ed7dbc017124a6fd8a0da269d1da39ef1/src/backend/base/langflow/services/monitor/schema.py#L11) to where this error is originating.

```
[06/04/24 18:29:18] ERROR    2024-06-04 18:29:18 - ERROR    - utils utils.py:200
                             - Error logging transaction: 4                     
                             validation errors for TransactionModel             
                             flow_id                                            
                               Field required                                   
                                 For further information visit                  
                             https://errors.pydantic.dev/2.7/v/miss             
                             ing                                                
                             source                                             
                               Field required                                   
                                 For further information visit                  
                             https://errors.pydantic.dev/2.7/v/miss             
                             ing                                                
                             target                                             
                               Field required                                   
                                 For further information visit                  
                             https://errors.pydantic.dev/2.7/v/miss             
                             ing                                                
                             target_args                                        
                               Field required                                   
                                 For further information visit                  
                             https://errors.pydantic.dev/2.7/v/miss             
                             ing
```

**Comment by rothnic** [comment]
Just updated and confirmed this issue still exists for v1.0.0a55.

**Comment by nicoloboschi** [comment]
@rothnic 1.0.x is way more stable. Can you give it a try and close the issue if it has been fixed?
