### ISSUE TITLE
Got error "Error Building Component

### ISSUE THREAD

**Issue by prateekvyas1996** [langflow-ai/langflow#2065]
Got error "Error Building Component
    Error building vertex Hugging Face API: Failed to resolve model_id:Could not find model id for inference server: https://api-inference.huggingface.co/models/mistralai/Mistral-7B-Instruct-v0.2Make sure that your Hugging Face token has access to the endpoint."

I put following arguments
Endpoint url: https://api-inference.huggingface.co/models/mistralai/Mistral-7B-Instruct-v0.2
Task - text-generation
API token: <My token freshly generated>
Still getting errors.

_Originally posted by @prateekvyas1996 in https://github.com/langflow-ai/langflow/discussions/1743#discussioncomment-9662722_

**Comment by anovazzi1** [comment]
Hello @prateekvyas1996,
Sorry for the delay. Did you try using the new version? Does the error still persist?

**Comment by carlosrcoelho** [comment]
Hi @prateekvyas1996  ,
 
I hope you're doing well. Just a friendly reminder that if we do not hear back from you within the next 3 days, we will close this issue. If you need more time or further assistance, please let us know. 

Thank you for your understanding!

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
