### ISSUE TITLE
deprecated imports while running langflow 

### ISSUE THREAD

**Issue by mindful-time** [langflow-ai/langflow#2070]
Getting the following deprecated imports issue in the langflow installation : 

.pyenv\pyenv-win\versions\3.11.3\Lib\site-packages\langchain\_api\module_import.py:120: LangChainDeprecationWarning: Importing RequestsWrapper from langchain is deprecated. Please replace deprecated imports:

>> from langchain import RequestsWrapper

with new imports of:

>> from langchain_community.utilities import RequestsWrapper

  warn_deprecated(

**Comment by nicoloboschi** [comment]
Most of them have been resolved with the latest langchain upgrade. If any other deprecations appear, please open a new ticket with the specific lines
