### ISSUE TITLE
[pre-release alpha bug] a46 with python 3.12.2 doesn't start up

### ISSUE THREAD

**Issue by msmygit** [langflow-ai/langflow#2086]
**Describe the bug**
alpha46 with python 3.12.2 doesn't even start up and won't bring up the ui too.

[langflow-a46-python-3-12-2-error.txt](https://github.com/user-attachments/files/15597994/langflow-a46-python-3-12-2-error.txt)

**Browser and Version**
n/a

**To Reproduce**
1. Install alpha46
2. try to start up

**Screenshots**

**Additional context**

**Comment by nicoloboschi** [comment]
Fixed. 1.0.x has support for python 3.12
