### ISSUE TITLE
Langflow show black screen on launch

### ISSUE THREAD

**Issue by denzo** [langflow-ai/langflow#2090]
**Describe the bug**
Langflow starts successfully and opens the browser but the browser just shows black screen. I can see a Javascript error in the console.

**Browser and Version**
 - Browser Chrome Version 125.0.6422.142 (Official Build) (arm64)
 - Langflow Version 1.0.0a46

**To Reproduce**
1. Install Langflow
2. Run Langflow

**Screenshots**

<img width="748" alt="image" src="https://github.com/langflow-ai/langflow/assets/1874772/d85e6ba0-bea7-463a-a948-043f23c3111f">

<img width="1431" alt="image" src="https://github.com/langflow-ai/langflow/assets/1874772/a6d360b4-6980-4e32-9edb-cb2c25fde1e3">

**Additional context**

**Comment by mikelmao** [comment]
I too am facing this issue @denzo

**Comment by msmygit** [comment]
I'm facing the same issue too!

**Comment by jvsmithjr** [comment]
I have the same problem. I installed it WSL and vmware machines. All new builds.

**Comment by qiaolb** [comment]
I encountered a similar problem
<img width="611" alt="image" src="https://github.com/langflow-ai/langflow/assets/8615816/be373f45-a5c4-4c0a-935c-a7e40e4d562a">

**Comment by anovazzi1** [comment]
This issue should not occur again after version 1.0.
