### ISSUE TITLE
feat: add Milvus components

### ISSUE THREAD

**Issue by hegdeashwin** [langflow-ai/langflow#2092]
I'm using Milvus as Vector store which is kind of missing here. 
Not sure if anyone working on this, Would like to contribute to build the Milvus component to the store.

Currently going over codebase. Is there any channel where we can reach out for guidance in case required?

**Comment by carlosrcoelho** [comment]
Hi @hegdeashwin ,

You can access Langflow's Discord (https://discord.com/invite/EqksyE2EX9) to get help.

Do you need any assistance with this case? If not, please let us know if this issue can be closed.

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
