### ISSUE TITLE
only getting first few letters of the output

### ISSUE THREAD

**Issue by aj2620** [langflow-ai/langflow#2094]
**Describe the bug**
I have tried langflow with mistral ai and in the output I'm getting only a few letters of the output

**Browser and Version**
 Google Chrome
 -Version 125.0.6422.142 

**To Reproduce**
1. Add chat input and chat output with mistral ai and mistral ai embeddings and a database attached to them
2. in the playground if I give any prompt only the first few letters of the output is being shown in the ui.

**Screenshots**
![Screenshot 2024-06-06 140703](https://github.com/langflow-ai/langflow/assets/97669418/29ec086e-fb1e-4b1f-8c99-953b4dba9bcc)
![Screenshot 2024-06-06 170318](https://github.com/langflow-ai/langflow/assets/97669418/74de7c01-e71a-45ce-8f58-83a67c029208)

**Additional context**
I have also attached a screen shot of the error showing in the terminal. Everything is working fine but the output is not being generated completely

**Comment by anovazzi1** [comment]
It looks like you selected the wrong field in the chatOutput component. Could you please provide a screenshot of your flow?

**Comment by carlosrcoelho** [comment]
Hi @aj2620  ,

Do you need any assistance with this case? If not, please let us know if this issue can be closed.

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
