### ISSUE TITLE
LANGFLOW black screen on launch 

### ISSUE THREAD

**Issue by nguyenlykhanhlinh** [langflow-ai/langflow#2106]
**help me this error:** 
I tried install langflow follow step-by-step in doc langflow and I also tried fixing the error according to the GitHub link provided ([https://github.com/langflow-ai/langflow/issues/2090]) but when i run cmd, screen still completely black. 

Does anyone know how to fix this issue? If you could help, I would be very grateful. Thank you so much.

![bug-3](https://github.com/langflow-ai/langflow/assets/77375001/2ab2022a-76d6-40f6-afe1-a24adf6b9c79)
![bug-2](https://github.com/langflow-ai/langflow/assets/77375001/40b3444d-a499-495f-a518-fa967cdaecd1)
![bug-1](https://github.com/langflow-ai/langflow/assets/77375001/23905213-4721-40b7-a6ad-77236f5d570a)
![bug-4](https://github.com/langflow-ai/langflow/assets/77375001/5de5906a-c828-4915-ac55-8fb9c0ce99ad)

**Comment by deitynoah** [comment]
@dosu the __init__.py file is empty

**Comment by anovazzi1** [comment]
This issue should not occur again after version 1.0.
