### ISSUE TITLE
JSON for Tool calling agent that invokes multiple Flows as Tool

### ISSUE THREAD

**Issue by edwinjosechittilappilly** [langflow-ai/langflow#2112]
How to deploy an agent that uses another flow as a tool.
How will the JSON output be ?
Error When running the JSON of the  Tool calling agent.

**Comment by edwinjosechittilappilly** [comment]
The doubt was regarding the JSON Filed export / Flow Export.

Scenario:
There are 3 flows:
Flow A: Task 1
Flow B: Task 2
Flow C: tool calling agent that used Flow A and Flow B as tools using Flow as tools component.

Now if I Export the JSON (Python code run as flow) of Flow C It doesn't work.

**Comment by anovazzi1** [comment]
Hi @edwinjosechittilappilly,
Try using these components in your flow:
![image](https://github.com/langflow-ai/langflow/assets/70824914/092a19bb-f43a-4cc5-ba74-604727efc241)

**Comment by carlosrcoelho** [comment]
Hi @edwinjosechittilappilly  ,
 
I hope you're doing well. Just a friendly reminder that if we do not hear back from you within the next 3 days, we will close this issue. If you need more time or further assistance, please let us know. 

Thank you for your understanding!

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
