### ISSUE TITLE
TypeError: RedisCache.upsert() got an unexpected keyword argument 'lock'

### ISSUE THREAD

**Issue by songjinu** [langflow-ai/langflow#2133]
**Describe the bug**
- TypeError: RedisCache.upsert() got an unexpected keyword argument 'lock'
- I need independent cache server, because I use multi process like uvicorn worker 10.
- How can i use redis cache.

**Browser and Version**
 - Browser [chrome]
 - Version [1.0.0a49]

**To Reproduce**
1. set redis cache in .env 
```
LANGFLOW_CACHE_TYPE=redis
LANGFLOW_REDIS_URL=redis://@localhost:6379/0
```
2. got error when i build flow.
```
TypeError: RedisCache.upsert() got an unexpected keyword argument 'lock'
```

**Comment by anovazzi1** [comment]
Hello @songjinu, 
Sorry for the delay. Did you try using the new version? Does the error still persist?

**Comment by songjinu** [comment]
> Hello @songjinu, Sorry for the delay. Did you try using the new version? Does the error still persist?

Thanks. 
I am in v1.0.6. 
but, I also get the errors about pickle : 
`PicklingError: Can't pickle <class 'passlib.handlers.bcrypt.<customized bcrypt hasher>'>: attribute lookup <customized bcrypt hasher> on
                             passlib.handlers.bcrypt failed`

**Comment by carlosrcoelho** [comment]
Hi @songjinu,

It seems that the error "TypeError: RedisCache.upsert() got an unexpected keyword argument 'lock'" is no longer occurring, correct? If that's the case, can we close this issue?

As for the problem with PicklingError, could you open another issue for discussion?

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
