### ISSUE TITLE
Error building node TextLoader

### ISSUE THREAD

**Issue by pp6699** [langflow-ai/langflow#2136]
Duration: 306 ms
Error building node TextLoader(ID:TextLoader-UilLV): Error loading C:\Users\施建樺\AppData\Local\langflow\langflow\Cache\54b89cd5-fbea-4ed8-9a5a-b3074bb276f0\c424c4864d77c6e969d1c6969a58f5efc38071c1b73626c7f4e8d615d4e93fc5.txt

**Comment by nicoloboschi** [comment]
Please add more info and re open the issue if you still have the problem
