### ISSUE TITLE
sqlite3.OperationalError: table _alembic_tmp_flow already exists during Langflow startup

### ISSUE THREAD

**Issue by NeoVand** [langflow-ai/langflow#2139]
Description:
When attempting to run Langflow (version v1.0.0a50), the application fails to start due to an error encountered during the database migration process. The specific error indicates that a temporary table (_alembic_tmp_flow) already exists in the SQLite database, causing a conflict and preventing the application from proceeding.

Steps to Reproduce:

Execute the command langflow run.
Observe the error during the startup process.
Expected Behavior:
Langflow should successfully run without encountering database migration errors.

Actual Behavior:
Langflow fails to start, logging the following error:

`~ % langflow run
Starting Langflow v1.0.0a50...
[06/11/24 11:59:19] ERROR    2024-06-11 11:59:19 - ERROR    - main -  main.py:59
                             (sqlite3.OperationalError) table                   
                             _alembic_tmp_flow already exists                   
                             [SQL:                                              
                             CREATE TABLE _alembic_tmp_flow (                   
                                     name VARCHAR NOT NULL,                     
                                     description VARCHAR,                       
                                     icon VARCHAR,                              
                                     icon_bg_color VARCHAR,                     
                                     is_component BOOLEAN,                      
                                     updated_at DATETIME,                       
                                     id CHAR(32) NOT NULL,                      
                                     data JSON,                                 
                                     user_id CHAR(32),                          
                                     folder_id CHAR(32),                        
                                     endpoint_name VARCHAR,                     
                                     PRIMARY KEY (id),                          
                                     CONSTRAINT flow_folder_id_fkey             
                             FOREIGN KEY(folder_id) REFERENCES folder           
                             (id),                                              
                                     CONSTRAINT fk_flow_user_id_user            
                             FOREIGN KEY(user_id) REFERENCES user               
                             (id),                                              
                                     CONSTRAINT                                 
                             unique_flow_endpoint_name UNIQUE                   
                             (user_id, endpoint_name),                          
                                     CONSTRAINT unique_flow_name                
                             UNIQUE (user_id, name),                            
                                     UNIQUE (id)                                
                             )                                                  
                                                                                
                             ]                                                  
                             (Background on this error at:                      
                             https://sqlalche.me/e/20/e3q8)                     
                    ERROR    2024-06-11 11:59:19 - ERROR    - on -     on.py:121
                             Traceback (most recent call last):                 
                               File                                             
                             "/opt/anaconda3/envs/langflow/lib/python3          
                             .10/site-packages/langflow/services/datab          
                             ase/service.py", line 171, in                      
                             run_migrations                                     
                                 command.check(alembic_cfg)                     
                               File                                             
                             "/opt/anaconda3/envs/langflow/lib/python3          
                             .10/site-packages/alembic/command.py",             
                             line 290, in check                                 
                                 script_directory.run_env()                     
                               File                                             
                             "/opt/anaconda3/envs/langflow/lib/python3          
                             .10/site-packages/alembic/script/base.py"          
                             , line 583, in run_env                             
                                 util.load_python_file(self.dir,                
                             "env.py")                                          
                               File                                             
                             "/opt/anaconda3/envs/langflow/lib/python3          
                             .10/site-packages/alembic/util/pyfiles.py          
                             ", line 95, in load_python_file                    
                                 module = load_module_py(module_id,             
                             path)                                              
                               File                                             
                             "/opt/anaconda3/envs/langflow/lib/python3          
                             .10/site-packages/alembic/util/pyfiles.py          
                             ", line 113, in load_module_py                     
                                 spec.loader.exec_module(module)  #             
                             type: ignore                                       
                               File "<frozen                                    
                             importlib._bootstrap_external>", line              
                             883, in exec_module                                
                               File "<frozen importlib._bootstrap>",            
                             line 241, in _call_with_frames_removed             
                               File                                             
                             "/opt/anaconda3/envs/langflow/lib/python3          
                             .10/site-packages/langflow/alembic/env.py          
                             ", line 97, in <module>                            
                                 run_migrations_online()                        
                               File                                             
                             "/opt/anaconda3/envs/langflow/lib/python3          
                             .10/site-packages/langflow/alembic/env.py          
                             ", line 91, in run_migrations_online               
                                 context.run_migrations()                       
                               File "<string>", line 8, in                      
                             run_migrations                                     
                               File                                             
                             "/opt/anaconda3/envs/langflow/lib/python3          
                             .10/site-packages/alembic/runtime/environ          
                             ment.py", line 948, in run_migrations              
                                 self.get_context().run_migrations(**k          
                             w)                                                 
                               File                                             
                             "/opt/anaconda3/envs/langflow/lib/python3          
                             .10/site-packages/alembic/runtime/migrati          
                             on.py", line 615, in run_migrations                
                                 for step in                                    
                             self._migrations_fn(heads, self):                  
                               File                                             
                             "/opt/anaconda3/envs/langflow/lib/python3          
                             .10/site-packages/alembic/command.py",             
                             line 279, in retrieve_migrations                   
                                 revision_context.run_autogenerate(rev          
                             , context)                                         
                               File                                             
                             "/opt/anaconda3/envs/langflow/lib/python3          
                             .10/site-packages/alembic/autogenerate/ap          
                             i.py", line 570, in run_autogenerate               
                                 self._run_environment(rev,                     
                             migration_context, True)                           
                               File                                             
                             "/opt/anaconda3/envs/langflow/lib/python3          
                             .10/site-packages/alembic/autogenerate/ap          
                             i.py", line 591, in _run_environment               
                                 raise util.CommandError("Target                
                             database is not up to date.")                      
                             alembic.util.exc.CommandError: Target              
                             database is not up to date.                        
                                                                                
                             During handling of the above exception,            
                             another exception occurred:                        
                                                                                
                             Traceback (most recent call last):                 
                               File                                             
                             "/opt/anaconda3/envs/langflow/lib/python3          
                             .10/site-packages/sqlalchemy/engine/base.          
                             py", line 1967, in _exec_single_context            
                                 self.dialect.do_execute(                       
                               File                                             
                             "/opt/anaconda3/envs/langflow/lib/python3          
                             .10/site-packages/sqlalchemy/engine/defau          
                             lt.py", line 924, in do_execute                    
                                 cursor.execute(statement, parameters)          
                             sqlite3.OperationalError: table                    
                             _alembic_tmp_flow already exists                   
                                                                                
                             The above exception was the direct cause           
                             of the following exception:                        
                                                                                
                             Traceback (most recent call last):                 
                               File                                             
                             "/opt/anaconda3/envs/langflow/lib/python3          
                             .10/site-packages/starlette/routing.py",           
                             line 732, in lifespan                              
                                 async with self.lifespan_context(app)          
                             as maybe_state:                                    
                               File                                             
                             "/opt/anaconda3/envs/langflow/lib/python3          
                             .10/contextlib.py", line 199, in                   
                             __aenter__                                         
                                 return await anext(self.gen)                   
                               File                                             
                             "/opt/anaconda3/envs/langflow/lib/python3          
                             .10/site-packages/langflow/main.py", line          
                             50, in lifespan                                    
                                 initialize_services(fix_migration=fix          
                             _migration,                                        
                             socketio_server=socketio_server)                   
                               File                                             
                             "/opt/anaconda3/envs/langflow/lib/python3          
                             .10/site-packages/langflow/services/utils          
                             .py", line 166, in initialize_services             
                                 raise exc                                      
                               File                                             
                             "/opt/anaconda3/envs/langflow/lib/python3          
                             .10/site-packages/langflow/services/utils          
                             .py", line 164, in initialize_services             
                                 initialize_database(fix_migration=fix          
                             _migration)                                        
                               File                                             
                             "/opt/anaconda3/envs/langflow/lib/python3          
                             .10/site-packages/langflow/services/datab          
                             ase/utils.py", line 52, in                         
                             initialize_database                                
                                 raise exc                                      
                               File                                             
                             "/opt/anaconda3/envs/langflow/lib/python3          
                             .10/site-packages/langflow/services/datab          
                             ase/utils.py", line 32, in                         
                             initialize_database                                
                                 database_service.run_migrations(fix=f          
                             ix_migration)                                      
                               File                                             
                             "/opt/anaconda3/envs/langflow/lib/python3          
                             .10/site-packages/langflow/services/datab          
                             ase/service.py", line 174, in                      
                             run_migrations                                     
                                 command.upgrade(alembic_cfg, "head")           
                               File                                             
                             "/opt/anaconda3/envs/langflow/lib/python3          
                             .10/site-packages/alembic/command.py",             
                             line 403, in upgrade                               
                                 script.run_env()                               
                               File                                             
                             "/opt/anaconda3/envs/langflow/lib/python3          
                             .10/site-packages/alembic/script/base.py"          
                             , line 583, in run_env                             
                                 util.load_python_file(self.dir,                
                             "env.py")                                          
                               File                                             
                             "/opt/anaconda3/envs/langflow/lib/python3          
                             .10/site-packages/alembic/util/pyfiles.py          
                             ", line 95, in load_python_file                    
                                 module = load_module_py(module_id,             
                             path)                                              
                               File                                             
                             "/opt/anaconda3/envs/langflow/lib/python3          
                             .10/site-packages/alembic/util/pyfiles.py          
                             ", line 113, in load_module_py                     
                                 spec.loader.exec_module(module)  #             
                             type: ignore                                       
                               File "<frozen                                    
                             importlib._bootstrap_external>", line              
                             883, in exec_module                                
                               File "<frozen importlib._bootstrap>",            
                             line 241, in _call_with_frames_removed             
                               File                                             
                             "/opt/anaconda3/envs/langflow/lib/python3          
                             .10/site-packages/langflow/alembic/env.py          
                             ", line 97, in <module>                            
                                 run_migrations_online()                        
                               File                                             
                             "/opt/anaconda3/envs/langflow/lib/python3          
                             .10/site-packages/langflow/alembic/env.py          
                             ", line 91, in run_migrations_online               
                                 context.run_migrations()                       
                               File "<string>", line 8, in                      
                             run_migrations                                     
                               File                                             
                             "/opt/anaconda3/envs/langflow/lib/python3          
                             .10/site-packages/alembic/runtime/environ          
                             ment.py", line 948, in run_migrations              
                                 self.get_context().run_migrations(**k          
                             w)                                                 
                               File                                             
                             "/opt/anaconda3/envs/langflow/lib/python3          
                             .10/site-packages/alembic/runtime/migrati          
                             on.py", line 627, in run_migrations                
                                 step.migration_fn(**kw)                        
                               File                                             
                             "/opt/anaconda3/envs/langflow/lib/python3          
                             .10/site-packages/langflow/alembic/versio          
                             ns/3bb0ddf32dfb_add_unique_constraints_pe          
                             r_user_in_flow_.py", line 27, in upgrade           
                                 with op.batch_alter_table("flow",              
                             schema=None) as batch_op:                          
                               File                                             
                             "/opt/anaconda3/envs/langflow/lib/python3          
                             .10/contextlib.py", line 142, in __exit__          
                                 next(self.gen)                                 
                               File                                             
                             "/opt/anaconda3/envs/langflow/lib/python3          
                             .10/site-packages/alembic/operations/base          
                             .py", line 398, in batch_alter_table               
                                 impl.flush()                                   
                               File                                             
                             "/opt/anaconda3/envs/langflow/lib/python3          
                             .10/site-packages/alembic/operations/batc          
                             h.py", line 164, in flush                          
                                 batch_impl._create(self.impl)                  
                               File                                             
                             "/opt/anaconda3/envs/langflow/lib/python3          
                             .10/site-packages/alembic/operations/batc          
                             h.py", line 448, in _create                        
                                 op_impl.create_table(self.new_table)           
                               File                                             
                             "/opt/anaconda3/envs/langflow/lib/python3          
                             .10/site-packages/alembic/ddl/impl.py",            
                             line 366, in create_table                          
                                 self._exec(schema.CreateTable(table))          
                               File                                             
                             "/opt/anaconda3/envs/langflow/lib/python3          
                             .10/site-packages/alembic/ddl/impl.py",            
                             line 207, in _exec                                 
                                 return conn.execute(construct,                 
                             multiparams)                                       
                               File                                             
                             "/opt/anaconda3/envs/langflow/lib/python3          
                             .10/site-packages/sqlalchemy/engine/base.          
                             py", line 1418, in execute                         
                                 return meth(                                   
                               File                                             
                             "/opt/anaconda3/envs/langflow/lib/python3          
                             .10/site-packages/sqlalchemy/sql/ddl.py",          
                              line 180, in _execute_on_connection               
                                 return connection._execute_ddl(                
                               File                                             
                             "/opt/anaconda3/envs/langflow/lib/python3          
                             .10/site-packages/sqlalchemy/engine/base.          
                             py", line 1529, in _execute_ddl                    
                                 ret = self._execute_context(                   
                               File                                             
                             "/opt/anaconda3/envs/langflow/lib/python3          
                             .10/site-packages/sqlalchemy/engine/base.          
                             py", line 1846, in _execute_context                
                                 return self._exec_single_context(              
                               File                                             
                             "/opt/anaconda3/envs/langflow/lib/python3          
                             .10/site-packages/sqlalchemy/engine/base.          
                             py", line 1986, in _exec_single_context            
                                 self._handle_dbapi_exception(                  
                               File                                             
                             "/opt/anaconda3/envs/langflow/lib/python3          
                             .10/site-packages/sqlalchemy/engine/base.          
                             py", line 2353, in                                 
                             _handle_dbapi_exception                            
                                 raise                                          
                             sqlalchemy_exception.with_traceback(exc_i          
                             nfo[2]) from e                                     
                               File                                             
                             "/opt/anaconda3/envs/langflow/lib/python3          
                             .10/site-packages/sqlalchemy/engine/base.          
                             py", line 1967, in _exec_single_context            
                                 self.dialect.do_execute(                       
                               File                                             
                             "/opt/anaconda3/envs/langflow/lib/python3          
                             .10/site-packages/sqlalchemy/engine/defau          
                             lt.py", line 924, in do_execute                    
                                 cursor.execute(statement, parameters)          
                             sqlalchemy.exc.OperationalError:                   
                             (sqlite3.OperationalError) table                   
                             _alembic_tmp_flow already exists                   
                             [SQL:                                              
                             CREATE TABLE _alembic_tmp_flow (                   
                                     name VARCHAR NOT NULL,                     
                                     description VARCHAR,                       
                                     icon VARCHAR,                              
                                     icon_bg_color VARCHAR,                     
                                     is_component BOOLEAN,                      
                                     updated_at DATETIME,                       
                                     id CHAR(32) NOT NULL,                      
                                     data JSON,                                 
                                     user_id CHAR(32),                          
                                     folder_id CHAR(32),                        
                                     endpoint_name VARCHAR,                     
                                     PRIMARY KEY (id),                          
                                     CONSTRAINT flow_folder_id_fkey             
                             FOREIGN KEY(folder_id) REFERENCES folder           
                             (id),                                              
                                     CONSTRAINT fk_flow_user_id_user            
                             FOREIGN KEY(user_id) REFERENCES user               
                             (id),                                              
                                     CONSTRAINT                                 
                             unique_flow_endpoint_name UNIQUE                   
                             (user_id, endpoint_name),                          
                                     CONSTRAINT unique_flow_name                
                             UNIQUE (user_id, name),                            
                                     UNIQUE (id)                                
                             )                                                  
                                                                                
                             ]                                                  
                             (Background on this error at:                      
                             https://sqlalche.me/e/20/e3q8)                     
                                                                                
                    ERROR    2024-06-11 11:59:19 - ERROR    - on -      on.py:59
                             Application startup failed. Exiting.               
[06/11/24 11:59:19] ERROR    2024-06-11 11:59:19 - ERROR    -    glogging.py:272
                             glogging - Worker (pid:1427) exited                
                             with code 3                                        
                    ERROR    2024-06-11 11:59:19 - ERROR    -    glogging.py:272
                             glogging - Shutting down: Master                   
                    ERROR    2024-06-11 11:59:19 - ERROR    -    glogging.py:272
                             glogging - Reason: Worker failed to                
                             boot.                                              

`

**Comment by AndrewSun1010** [comment]
you can delete langflow.db or langflow-pre.db
