### ISSUE TITLE
[Feature Request] A generic SecretService to support store secrets

### ISSUE THREAD

**Issue by zzzming** [langflow-ai/langflow#2151]
https://github.com/langflow-ai/langflow/issues/2150 outlines a feature request for Kubernetes secret store. There could be other implementations of secret store such as AWS secret manager, HashCorp Vault, and etc. We should support a generic service, SecretService, that have different backend implementation for the secret store. This can be connected to VariableService to store secrets.

**Comment by carlosrcoelho** [comment]
https://github.com/langflow-ai/langflow/pull/2231
