### ISSUE TITLE
Error code  422 Unprocessable Entity, When Running cURL Code for Langflow Flow with TWEAKS

### ISSUE THREAD

**Issue by edwinjosechittilappilly** [langflow-ai/langflow#2162]
**Describe the bug**
Error 422 Unprocessable Entity: No response when running the Flow using cURL or Python API. Even when trying to ping through the terminal, the server is not reachable and gives back “unknown host.” Requesting more documentation on the deployment of Langflow apps. The error occurred when tweaks were provided in the cURL request.

**Browser and Version**  
- Browser: Postman  

**To Reproduce**  
1. Generate any flow.
2. Click on the API.
3. Select the tweaks option.
4. Get the cURL code from the CURL tab.
5. Run the cURL code in Postman:
   ```bash
   curl -X POST \
   "http://127.0.0.1:7860/api/v1/run/test_endpoint?stream=false" \
   -H 'Content-Type: application/json' \
   -d '{
       "input_value": "message",
       "output_type": "chat",
       "input_type": "chat",
       "tweaks": {
           "OpenAIModel-NIWAF": {
               "input_value": "",
               "max_tokens": 3000,
               "model_kwargs": "{\"response_format\":{\"type\":\"json_object\"}}",
               "model_name": "gpt-3.5-turbo",
               "openai_api_key": "OPEN_AI_EJ_KEY",
               "stream": false,
               "temperature": 0.2
           },
           "ChatOutput-cctL9": {
               "record_template": "{text}",
               "return_record": false,
               "sender": "Machine",
               "sender_name": "AI"
           },
           "ChatInput-sQJ5q": {
               "input_value": "hi",
               "return_record": false,
               "sender": "User",
               "sender_name": "User"
           },
           "Prompt-uGsOk": {
               "template": "\nYou are a pirate:\nreply as json\n{user_input}\n",
               "user_input": ""
           },
           "TextOutput-9Nuat": {
               "input_value": "",
               "record_template": ""
           },
           "ChatOutput-dfQkZ": {
               "record_template": "{text}",
               "return_record": false,
               "sender": "Machine",
               "sender_name": "AI"
           }
       }
   }'
   ```

**Error**  
```json
{"detail":[{"type":"json_invalid","loc":["body",191],"msg":"JSON decode error","input":{},"ctx":{"error":"Expecting ',' delimiter"}}]}
```

**Screenshots**  
<img width="1059" alt="Screenshot 2024-06-13 at 2 28 09 PM" src="https://github.com/langflow-ai/langflow/assets/15969583/d0329a06-a14e-40ea-b318-92a12e5a8f42">

**Additional context**  
- The error occurred when tweaks were provided in the cURL request.
- Requesting more documentation on the deployment of Langflow apps.
- Python version: Python 3.11.9
- Langflow version: ragstack-ai-langflow 0.0.9

Sample file attached 
[Test.json](https://github.com/user-attachments/files/15827070/Test.json)
 for replicating the issue.

**Comment by anovazzi1** [comment]
Hello,
Sorry for the delay. Did you try using the new version? Does the error still persist?

**Comment by carlosrcoelho** [comment]
Hi @edwinjosechittilappilly  ,
 
I hope you're doing well. Just a friendly reminder that if we do not hear back from you within the next 3 days, we will close this issue. If you need more time or further assistance, please let us know. 

Thank you for your understanding!

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
