### ISSUE TITLE
Chroma and Astra DB Search components not allowing Chat Input

### ISSUE THREAD

**Issue by brylie** [langflow-ai/langflow#2174]
When adding a Chroma Search or Astra DB component, I am unable to connect a Chat Input component output to the Chroma Search or Astra DB component input.

Langflow: langflow==1.0.0a57

**To Reproduce**
1. Create a flow
2. Add a Chroma Search or Astra DB component
3. Add a Chat Input component
4. Attempt to connect the "message/text" of the Chat Input component to the input of the Chroma Search or Astra DB component

**Screenshots**

![Screenshot 2024-06-14 at 19 46 42](https://github.com/langflow-ai/langflow/assets/17307/8752a9ed-5267-4e8f-a684-a7dc4c32bbf1)

**Comment by brianhadaway** [comment]
The same issue is present when connecting Chat Input to Astra DB Search.

**Comment by brylie** [comment]
@dosu, for some reason, those instructions no longer work. There seems to be a bug in a recent revision of Langflow that has broken the AstraDB Search and Chroma Search components. The issue may also affect other vector search components, but we haven't tested. Can you find any recent commits that modified the vector search components which may have introduced a regression?

**Comment by ogabrielluiz** [comment]
Hey all.

We'll release a fix for this in a few minutes. Should be version 1.0.0a58

**Comment by brylie** [comment]
Was it related to this?

https://github.com/langflow-ai/langflow/commit/df575708526c57d8703832c10d70a7e8e217ac84

I was just getting familiar with the codebase, so was curious 😄

**Comment by ogabrielluiz** [comment]
> Was it related to this?
> 
> [df57570](https://github.com/langflow-ai/langflow/commit/df575708526c57d8703832c10d70a7e8e217ac84)
> 
> I was just getting familiar with the codebase, so was curious 😄

Yes.

For now ChatInput should output Message and Text so it can still connect to Text fields. This PR made it output only Message so it stopped working.

**Comment by brylie** [comment]
By the way, is there a way to improve the automated test coverage of the component interfaces? I don't see a CI process for test running/coverage analysis on PRs, for example. What is the current coverage percent? I've had a good experience with [Codecov](https://about.codecov.io/) both in open source projects and at work.

**Comment by cannuri** [comment]
> Hey all.
> 
> We'll release a fix for this in a few minutes. Should be version 1.0.0a58

Same validation error with Qdrant Search in v1.0.0a58

**Comment by cannuri** [comment]
> I can confirm that the Chroma Search component works correctly in v1.0.0a58.
> 
> However, perhaps this issue can remain open to track other vector search or similar regressions introduced in the recent refactoring?

yep, "Qdrant Search" still not working: https://github.com/langflow-ai/langflow/issues/2184

Workaround: turn off "Return Record" in "Chat Input" node.

**Comment by brianhadaway** [comment]
I updated to v1.0.0a58 and v1.0.0a59 and I still get the "Error building Chroma Search: Invalid inputs provided". If I disconnect Chat Input from ChromaSearch and hard code an input string the build succeeds (but the flow is useless because of hard-coded text.) Are there additional config changes in my Chat Input component source to consume the bug fix?

**Comment by sikaili99** [comment]
> I can confirm that the Chroma Search component works correctly in v1.0.0a58.
> 
> However, perhaps this issue can remain open to track other vector search or similar regressions introduced in the recent refactoring?

I updated to v1.0.0a58 and v1.0.0a59 both versions are giving the error:

`Error building Component Astra DB Search: Invalid inputs provided.`

**Comment by brianhadaway** [comment]
I confirmed that Chroma Search works in v1.0.0.a59 if you toggle off the Chat Input `Return Record` in Advanced Settings. 

<img width="1435" alt="Screenshot 2024-06-17 at 1 23 06 PM" src="https://github.com/langflow-ai/langflow/assets/838032/ab9d108a-49c9-49a8-9c43-42669d2c37f9">

**Comment by mkiiim** [comment]
Can confirm that @brianhadaway's suggestion works with AstraDB.
i.e., toggle off the Chat Input `Return Record` in Advanced Settings.

**Comment by cenit** [comment]
![image](https://github.com/langflow-ai/langflow/assets/721187/7cd2f0aa-543b-434f-b019-70ebe1820718)

sorry for the newbie's question, but i cannot find Return Record...

**Comment by cenit** [comment]
i cancelled the component and re-inserted and now the advanced settings dialog has it... sorry

**Comment by sikaili99** [comment]
> i cancelled the component and re-inserted and now the advanced settings dialog has it... sorry
> 
> ![image](https://github.com/langflow-ai/langflow/assets/721187/ca7e25e0-4e3b-41df-9fa3-6a15afe1f891)
> 
> still, i disabled Return Record but Chroma Search is still complaining that there is an issue building the component due to invalid inputs provided

You should try hard reload or re-run langflow

**Comment by brylie** [comment]
I've restarted Langflow, disabled Send Record, and updated to the latest 1.0.0a61 but both Astra and ChromaDB search fail when connected to to the output of the Chat Input component 🤔

**Comment by cenit** [comment]
I noticed that mine fail if the input is empty. Try with a predefined string to see if it helps :)

**Comment by brylie** [comment]
Congrats on the 1.0 release!

I'm trying to build a RAG flow with Langflow 1.0.4, following both the [Langflow RAG with Astra DB tutorial](https://docs.langflow.org/tutorials/rag-with-astradb) and [Quickstart for DataStax LangFlow](https://docs.datastax.com/en/langflow/quickstart.html#rag-flow). For some reason, the vector search components seem to be missing from the Langflow 1.0.4 release 🤔 

![Screenshot 2024-06-25 at 22 34 16](https://github.com/langflow-ai/langflow/assets/17307/88ed878a-e9de-48e3-8712-4d7efaceba4d)

**Comment by brylie** [comment]
Oops, I figured it out. I needed to connect the Vector DB (chroma in this case) to a data parser, pictured:
![Screenshot 2024-06-25 at 22 57 51](https://github.com/langflow-ai/langflow/assets/17307/3e939a40-61d7-4cc9-8186-06d14653f6bb)
