### ISSUE TITLE
[a58 bug] Azure OpenAI global variables passed via "--env-file" doesn't work correctly

### ISSUE THREAD

**Issue by msmygit** [langflow-ai/langflow#2183]
**Describe the bug**
When we pass the global variables via a file which is then passed as `python -m langflow run --env-file /path/to/.env` command doesn't work and gives the following error:
```
ValueError: Error building vertex Azure OpenAI Embeddings: Could not connect to AzureOpenAIEmbeddings API.
```

**Browser and Version**
n/a

**To Reproduce**
1. Choose the pre-built Vector Store RAG collection
2. Replace Open AI embedding/model to Azure OpenAI equivalents
3. Try to play and you should see errors.

FWIW, if you manually enter the Azure OpenAI values on the component, this works.

**Screenshots**
n/a

**Additional context**
n/a

**Comment by nicoloboschi** [comment]
Fixed by https://github.com/langflow-ai/langflow/pull/2336
