### ISSUE TITLE
Encountering error in building ASTRA DB Search node in the canvas. Error Building Component Error building Component Astra DB Search: Invalid inputs provided.

### ISSUE THREAD

**Issue by Developer-Atomic-Vishnu** [langflow-ai/langflow#2200]
This bug is currently occurring in latest version of 1.0-alpha.

The bug is if i build my flow in the langflow the node of the astra db search says, 

Error Building Component
Error building Component Astra DB Search: Invalid inputs provided.

The astra db node on the canvas is connected to the chat input and in that i give a simple message.

**Browser and Version**
 - Browser [chrome]
 - Version [22]

**To Reproduce**
1. Create new project and import the given json file. 
[Untitled document.json](https://github.com/user-attachments/files/15874603/Untitled.document.json)
3. Enter the required credentials from the astra db and azure openai
4. Send a message, saying anything and watch the components build.
5. Astra Db will through up the error saying,

Error Building Component
Error building Component Astra DB Search: Invalid inputs provided.

**Comment by qzg** [comment]
Workaround: in the Chat Input component's advanced settings, turn off "Return Record"

**Comment by saeidsm** [comment]
Hi, I had the same issue, I rolled back to the stable version and del and added new chat and Astra search components. in the new chat you can disable Return records.

**Comment by Developer-Atomic-Vishnu** [comment]
Thanks guys that worked very well.
