### ISSUE TITLE
API Request ERROR

### ISSUE THREAD

**Issue by alex-ge123** [langflow-ai/langflow#2203]
When there are multiple AzureopenAI modules, an error occurs when calling the api interface

![微信图片_20240618092148](https://github.com/langflow-ai/langflow/assets/71969995/64a07431-7f07-4064-bb80-f6e4e872a990)

**Comment by alex-ge123** [comment]
this is my  api  curl  

curl -X POST \
    "http://192.168.0.29:7860/api/v1/run/a912a0a3-a1b3-4dd8-80df-835016ea2dae?stream=false" \
    -H 'Content-Type: application/json'\
  -H 'x-api-key: <your api key>'\
    -d '{"input_value": "message",
    "output_type": "chat",
    "input_type": "chat",
    "tweaks": {
  "ChatInput-S3vqS": {},
  "ChatOutput-ZIsW5": {},
  "MemoryComponent-OfrPd": {},
  "IDGenerator-iGWjc": {},
  "Prompt-XzfNj": {},
  "Prompt-e7qUH": {},
  "TextOutput-no6Nj": {},
  "TextOperator-s3kmU": {},
  "TextOperator-zskCY": {},
  "Pass-CP7JO": {},
  "CombineText-CEx4H": {},
  "TextInput-dgFKO": {},
  "CombineText-Qr2bX": {},
  "APIRequest-jEuXi": {},
  "RecordsOutput-LgcE9": {},
  "RecordsToText-Ryeud": {},
  "Prompt-bum9a": {},
  "AzureOpenAIModel-Ae4b9": {},
  "TextInput-nmKuw": {},
  "TextInput-9Inko": {},
  "TextInput-d26Mx": {},
  "AzureOpenAIModel-4sLz7": {},
  "AzureOpenAIModel-xnHhY": {},
  "AzureOpenAIModel-SmZ8l": {},
  "TextInput-pmxV5": {},
  "Prompt-5i7dg": {},
  "CombineText-CJX2Q": {},
  "CreateRecord-YQSRu": {},
  "CreateRecord-4mspE": {},
  "TextInput-Wm08d": {},
  "TextInput-HxJ1a": {},
  "TextInput-AIu7U": {},
  "AzureOpenAIModel-YZawU": {},
  "Prompt-jcR0T": {},
  "TextInput-E07ke": {},
  "APIRequest-f1LJz": {},
  "TextOutput-FPSMu": {},
  "RecordsOutput-rfPmB": {}
}}'

My project has multiple Azure OpenAI components

**Comment by nicoloboschi** [comment]
Duplicated by https://github.com/langflow-ai/langflow/issues/2294
