### ISSUE TITLE
idea

### ISSUE THREAD

**Issue by Mariuxac** [langflow-ai/langflow#2211]
Why not use the boxes for smaller buildings?
and to configure, double click to generate the configuration tab, so that the boxes become smaller for viewing.

**Comment by anovazzi1** [comment]
Could you please explain it in more detail? I didn't fully understand what you were trying to say.

**Comment by carlosrcoelho** [comment]
Hi @Mariuxac  ,
 
I hope you're doing well. Just a friendly reminder that if we do not hear back from you within the next 3 days, we will close this issue. If you need more time or further assistance, please let us know. 

Thank you for your understanding!
