### ISSUE TITLE
[Request] Please add openrouter as LLM Model

### ISSUE THREAD

**Issue by xenstar** [langflow-ai/langflow#2212]
**Describe the bug**
https://openrouter.ai/ has more than 150+ different models at cheap prices. Please add it as a llm model so we can easily use it with langflow. 

**Additional context**
Also it would be great, if you add a project in https://pinokio.computer/, then we can easily install Langflow in desktop computer.

**Comment by OttoJireh1** [comment]
I second this! looking for openrouter was the first thing i did when opening it.

**Comment by carlosrcoelho** [comment]
Hi @xenstar ,

Do you need any assistance with this case? If not, please let us know if this issue can be closed.

**Comment by OttoJireh1** [comment]
I still haven't figured it out. There is a command to install openrouter wrapper but it doesn't work no matter what i try with editing nano files. pip install langchain_openrouter      : (

**Comment by jtoy** [comment]
please add official support

**Comment by lynxul25** [comment]
Also, please fetch the costs from openrouter, it will enable us to keep an eye on expenses. Feature would be greatly appreciated..
