### ISSUE TITLE
CommandError: Multiple head revisions are present for given argument 'head'; please specify a specific target revision, '<branchname>@head' to narrow to a specific head, or 'heads' for all heads

### ISSUE THREAD

**Issue by nguyenlykhanhlinh** [langflow-ai/langflow#2215]
**Describe the bug**
I encountered a bug when I installed using the following command: 
python -m pip install langflow==0.6.19 --force-reinstall
And I encountered an error as in the picture, how can I fix this error?

**Browser and Version**
 - Browser [chrome]
 - Version [Langflow==0.6.19]

**Screenshots**
![image](https://github.com/langflow-ai/langflow/assets/77375001/7cf5530d-147b-49eb-80c6-d94716f8ee4d)
![image](https://github.com/langflow-ai/langflow/assets/77375001/5e104874-7b0f-4b78-882a-c708bb7e6bce)

**Comment by nicoloboschi** [comment]
Are you getting the same with latest 1.0.5?

**Comment by carlosrcoelho** [comment]
Hi @nguyenlykhanhlinh,

Do you need any assistance with this case? If not, please let us know if this issue can be closed.

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
