### ISSUE TITLE
Questions about  Run Flow 

### ISSUE THREAD

**Issue by alex-ge123** [langflow-ai/langflow#2216]
runflow calls other processes. How do I get the return value

![微信图片_20240619155903](https://github.com/langflow-ai/langflow/assets/71969995/62c6c376-ac23-4b0b-ba91-95a5b82e17c3)

**Comment by anovazzi1** [comment]
Hi @alex-ge123,
Could you please explain it in more detail? I didn't fully understand what you were trying to say.

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
