### ISSUE TITLE
An error was thrown while using the groq component

### ISSUE THREAD

**Issue by medoer** [langflow-ai/langflow#2217]
**Describe the bug**
An error was thrown while using the groq component

**Browser and Version**
 - both chrome,safari 
 -  chrome(Version 125.0.6422.176 (Official Build) (x86_64))
**To Reproduce**
1. build groq component

**Screenshots**
<img width="1591" alt="image" src="https://github.com/langflow-ai/langflow/assets/20471718/c6b94cf9-7b8d-43a1-b621-fcdb80b44f92">

**Additional context**
<img width="1148" alt="image" src="https://github.com/langflow-ai/langflow/assets/20471718/ec4abfa1-0172-4b09-8ba0-b1d912fb81bd">

**Comment by anovazzi1** [comment]
Hello,
Sorry for the delay. Did you try using the new version? Does the error still persist?

**Comment by carlosrcoelho** [comment]
Hi @medoer  ,
 
I hope you're doing well. Just a friendly reminder that if we do not hear back from you within the next 3 days, we will close this issue. If you need more time or further assistance, please let us know. 

Thank you for your understanding!

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
