### ISSUE TITLE
Question: Hugging Face API

### ISSUE THREAD

**Issue by dyomed93** [langflow-ai/langflow#2229]
Hi,
I'm using Langflow to create a ChatBot based on Mistral 7B, but i can't find any documentation or example of the module "Hugging Face API" on Langflow, and what are the exact values to put in Endpoint URL or model.
Where can I find an example or some documentation about that?

Thank You in advance

**Comment by carlosrcoelho** [comment]
Hi @dyomed93  ,

Do you need any assistance with this case? If not, please let us know if this issue can be closed.
