### ISSUE TITLE
Question: Inquiry on Session Management and Parameter Passing in Langflow API

### ISSUE THREAD

**Issue by qiaolb** [langflow-ai/langflow#2234]
I have been successfully utilizing it to define AI flows. However, I have encountered some questions related to the API usage that I believe could benefit from community insights.

1. Session Management for Concurrent Users

When accessing Langflow flows via curl, ensuring that sessions remain distinct and isolated for each user is crucial. My question is:

How can we guarantee that multiple users can access the Langflow API simultaneously without their sessions getting mixed up? Is there a built-in mechanism or a recommended approach to maintain independent sessions for each user?

2. Passing Parameters to Flows via curl

Another aspect I am exploring is how to effectively pass custom parameters to a flow when accessing it through curl. My specific inquiry is:

What is the recommended method for passing parameters to a Langflow flow via curl? How can the flow be designed to accept and utilize these custom parameters?
These inquiries are aimed at enhancing the usability and flexibility of Langflow in scenarios involving multiple users and dynamic parameter inputs. I am looking forward to any suggestions, documentation, or examples that could guide me in resolving these concerns.

Thank you for your valuable time and support.

**Comment by qiaolb** [comment]
I have a simple flow that uses the chat input for entry. I would like to inquire about the difference between the input_value and the parameters of the Component when making an API call. Here is an example:

```bash
curl -X 'POST' \
  'http://<your_server>/run/{flow_id}' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'x-api-key: YOUR_API_KEY' \
  -d '{
        "input_value": "hello",
        "input_type": "chat",
        "output_type": "chat",
        "tweaks": {
            "ChatInput-tmTWU": {}
        },
        "session_id": "unique_session_id_for_user"
      }'
```

```bash
curl -X 'POST' \
  'http://<your_server>/run/{flow_id}' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'x-api-key: YOUR_API_KEY' \
  -d '{
        "input_value": "",
        "input_type": "chat",
        "output_type": "chat",
        "tweaks": {
            "ChatInput-tmTWU": {"input_value": "hello"}
        },
        "session_id": "unique_session_id_for_user"
      }'
```

**Comment by mmdsnb** [comment]
Not work

**Comment by qiaolb** [comment]
This problem has been resolved. Thanks!
