### ISSUE TITLE
Documentation to use Flow as Tool

### ISSUE THREAD

**Issue by sepa85** [langflow-ai/langflow#2237]
I'm trying to use the experimental Flow as Tool component (class FlowToolComponent). I have the Flow A with an agent with tools, connected to the experimental Flow as Tool. This tool uses the Flow B, which have a text input and a text output.

With these configuration, I get the error:
Error building Component Tool Calling Agent: 'message'

If I use chat input and chat output in Flow B, I get the same error:
Error building Component Tool Calling Agent: 'message'

If I use the experimental "Message" component as Flow B output, I got no error, but the response from the tool is empty. I used Machine as sender type and tool as sender name.

How must I build the Flow used as tool? Which are the correct input and output component type? Is there documentation on Flow as Tool usage, maybe with examples?

**Comment by sepa85** [comment]
What do you mean with Vertex, @dosu? The only components with Vertex in langflow are related to Google vertex AI. I just need to pass a string as input for Flow B, and get the string from the output of the Flow B.

**Comment by carlosrcoelho** [comment]
Hi @sepa85,

Do you need any assistance with this case? If not, please let us know if this issue can be closed.

**Comment by sepa85** [comment]
I don't use langflow anymore. You can close it, thank you.

**Comment by carlosrcoelho** [comment]
Hi @sepa85 

Thank you for letting us know. I'm sorry to hear that you are no longer using Langflow. If there's any specific reason or feedback you'd like to share, I would love to hear it as it helps us improve the project.

We hope you might consider using Langflow again in the future as we continuously work on new features and improvements. If you ever decide to give it another try or have any questions, feel free to reach out.

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
