### ISSUE TITLE
Qdrant Search when a clic on Advanced Settings

### ISSUE THREAD

**Issue by ari-64** [langflow-ai/langflow#2255]
Sorry, we found an unexpected error!

Please report errors with detailed tracebacks on the [GitHub Issues](https://github.com/langflow-ai/langflow/issues) page.
Thank you!

Restart Langflow
[Report On Github](https://github.com/langflow-ai/langflow/issues/new)

**Comment by lwkask8** [comment]
To com o mesmo problema

**Comment by nicoloboschi** [comment]
Could you elaborate more this problem?

**Comment by carlosrcoelho** [comment]
Hi @ari-64  ,
 
I hope you're doing well. Just a friendly reminder that if we do not hear back from you within the next 3 days, we will close this issue. If you need more time or further assistance, please let us know. 

Thank you for your understanding!

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
