### ISSUE TITLE
Error building Conditional Router Component

### ISSUE THREAD

**Issue by GordeyChernyy** [langflow-ai/langflow#2268]
Component Conditional Router failed to build with error "You must specify an output name to call stop"

**Version**
 - v1.0.0rc0

**To Reproduce**

1. Add Component Conditional Router
2. Build Component
3. You get the error message: "You must specify an output name to call stop"

**To Solve**

I added `if len(self.vertex.outputs) < 2` condition in custom_component.py 

https://github.com/langflow-ai/langflow/blob/a9b2f5f82e0e4ea849914c2f6e2e7082dbd54c61/src/backend/base/langflow/custom/custom_component/custom_component.py#L99

```
    def stop(self, output_name: str | None = None):
        if not output_name and self.vertex and len(self.vertex.outputs) == 1:
            output_name = self.vertex.outputs[0]["name"]
        else:
            if len(self.vertex.outputs) < 2:
                raise ValueError("You must specify an output name to call stop")
```

**Comment by lys791227** [comment]
Component Conditional Router failed to build with error "You must specify an output name to call stop"
Version：
v1.0.5
 ValueError: You must specify an output name to call stop
[06/27/24 16:23:20] ERROR    2024-06-27 16:23:20 - ERROR    - service - Error stopping tracing service: 'NoneType' object has no attribute 'cancel'

**Comment by bravelll** [comment]
> Component Conditional Router failed to build with error "You must specify an output name to call stop"
> Version：
> v1.0.5
> ValueError: You must specify an output name to call stop
> [06/27/24 16:23:20] ERROR 2024-06-27 16:23:20 - ERROR - service - Error stopping tracing service: 'NoneType' object has no attribute 'cancel'



> Component Conditional Router failed to build with error "You must specify an output name to call stop"
> 
> **Version**
> 
> * v1.0.0rc0
> 
> **To Reproduce**
> 
> 1. Add Component Conditional Router
> 2. Build Component
> 3. You get the error message: "You must specify an output name to call stop"
> 
> **To Solve**
> 
> I added `if len(self.vertex.outputs) < 2` condition in custom_component.py
> 
> https://github.com/langflow-ai/langflow/blob/a9b2f5f82e0e4ea849914c2f6e2e7082dbd54c61/src/backend/base/langflow/custom/custom_component/custom_component.py#L99
> 
> ```
>     def stop(self, output_name: str | None = None):
>         if not output_name and self.vertex and len(self.vertex.outputs) == 1:
>             output_name = self.vertex.outputs[0]["name"]
>         else:
>             if len(self.vertex.outputs) < 2:
>                 raise ValueError("You must specify an output name to call stop")
> ```

Component Conditional Router failed to build with error "You must specify an output name to call stop"
Version：
v1.0.5
ValueError: You must specify an output name to call stop
[06/27/24 16:23:20] ERROR 2024-06-27 16:23:20 - ERROR - service - Error stopping tracing service: 'NoneType' object has no attribute 'cancel'

**Comment by anovazzi1** [comment]
Hello,
Sorry for the delay. Did you try using the new version? Does the error still persist?

**Comment by Alex-Poon** [comment]
@anovazzi1 is this component the conditional routing you said was in the new version? Or is it another component? (i.e. route based on previous user's message)

**Comment by lys791227** [comment]
> v1.0.5

v1.0.5，thanks

**Comment by zhxsxuan** [comment]
> Component Conditional Router failed to build with error "You must specify an output name to call stop"
> 
> **Version**
> 
> * v1.0.0rc0
> 
> **To Reproduce**
> 
> 1. Add Component Conditional Router
> 2. Build Component
> 3. You get the error message: "You must specify an output name to call stop"
> 
> **To Solve**
> 
> I added `if len(self.vertex.outputs) < 2` condition in custom_component.py
> 
> https://github.com/langflow-ai/langflow/blob/a9b2f5f82e0e4ea849914c2f6e2e7082dbd54c61/src/backend/base/langflow/custom/custom_component/custom_component.py#L99
> 
> ```
>     def stop(self, output_name: str | None = None):
>         if not output_name and self.vertex and len(self.vertex.outputs) == 1:
>             output_name = self.vertex.outputs[0]["name"]
>         else:
>             if len(self.vertex.outputs) < 2:
>                 raise ValueError("You must specify an output name to call stop")
> ```

Tried adding `if len(self.vertex.outputs) < 2` condition in custom_component.py, still doesn't work.

**Comment by lys791227** [comment]
&nbsp;谢谢！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Hongxuan ***@***.***&gt;; 
发送时间: 2024年7月2日(星期二) 中午11:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [langflow-ai/langflow] Error building Conditional Router Component (Issue #2268)














  
Component Conditional Router failed to build with error "You must specify an output name to call stop"
 
Version
  
v1.0.0rc0
  
To Reproduce
  
Add Component Conditional Router
 
Build Component
 
You get the error message: "You must specify an output name to call stop"
  
To Solve
 
I added if len(self.vertex.outputs) < 2 condition in custom_component.py
 
https://github.com/langflow-ai/langflow/blob/a9b2f5f82e0e4ea849914c2f6e2e7082dbd54c61/src/backend/base/langflow/custom/custom_component/custom_component.py#L99
     def stop(self, output_name: str | None = None):         if not output_name and self.vertex and len(self.vertex.outputs) == 1:             output_name = self.vertex.outputs[0]["name"]         else:             if len(self.vertex.outputs) < 2:                 raise ValueError("You must specify an output name to call stop")   
Tried adding if len(self.vertex.outputs) < 2 condition in custom_component.py, still doesn't work.

**Comment by anovazzi1** [comment]
@Alex-Poon yes, it was, I'll take a look and fix it ASAP

**Comment by carlosrcoelho** [comment]
Hi @GordeyChernyy,
 
I hope you're doing well. Just a friendly reminder that if we do not hear back from you within the next 3 days, we will close this issue. If you need more time or further assistance, please let us know. 

Thank you for your understanding!

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
