### ISSUE TITLE
A process has multiple AzurOpenAI conversations

### ISSUE THREAD

**Issue by alex-ge123** [langflow-ai/langflow#2294]
When a process has multiple AzureOpenAI conversations and some AzureOpenAI is not required to be executed due to process reasons, "{"detail":"Error running graph:" is displayed when the APIrequest is called. No result found for vertex AzureOpenAIModel-jClhz"}" Is there any good way to solve this

![微信图片_20240624112452](https://github.com/langflow-ai/langflow/assets/71969995/b88577a5-009d-4bd8-ae29-565301ec49f4)
![微信图片_20240624112539](https://github.com/langflow-ai/langflow/assets/71969995/643f67af-a0c0-4f01-9d8c-c5fdddfd489a)

**Comment by carlosrcoelho** [comment]
Hi @alex-ge123 ,

Do you need any assistance with this case? If not, please let us know if this issue can be closed.
