### ISSUE TITLE
How does langflow store their global variable

### ISSUE THREAD

**Issue by Warit314** [langflow-ai/langflow#2296]
i want to add a look up table for flow id and their output, so i can look them up later and get the output from those flow , and i want to store the look up table as a global variable in langflow, how can i do that?

**Comment by nicoloboschi** [comment]
The output of the flows are not stored by langflow. 
The variables are stored in the SQLlite Database configured, by default. 

You can check the variable table from your local database (or you can configure an external one if you prefer)
