### ISSUE TITLE
RC1 : Python API : Circular API import

### ISSUE THREAD

**Issue by Arron-Clague** [langflow-ai/langflow#2308]
Hi there : 

Im using the 1.0.0.RC1 build : if I make a call to send a message I get : 

2024-06-24 14:17:20 - Error running graph: Error building Component Empty Prompt:

cannot import name 'process_prompt_template' from partially initialized module 'langflow.base.prompts.api_utils' (most likely due to a circular import) (/home/koni/.local/lib/python3.10/site-packages/langflow/base/prompts/api_utils.py)

Thanks,

Arron

**Comment by nicoloboschi** [comment]
This has been fixed in the latest releases. 1.0.5 doesn't have the problem

**Comment by yuchieh8968** [comment]
Hello, I am currently encountering this issue while using the latest release.

**Comment by nicoloboschi** [comment]
@yuchieh8968 @Nitewriter you need to remove and re-add all the broken components after the upgrade

**Comment by Nitewriter** [comment]
@nicoloboschi are you referring to components in the flow or python packages? I'm using the `Memory Chatbot` template as a simple example flow and attempting to run the exported JSON using the sample code provided in the UI.

```python
from langflow.load import run_flow_from_json
TWEAKS = {
  "Memory-hzITR": {},
  "Prompt-viXZL": {},
  "ChatInput-tgsUe": {},
  "OpenAIModel-J2hiT": {},
  "ChatOutput-LH91h": {}
}

result = run_flow_from_json(flow="Memory Chatbot.json",
                            input_value="message",
                            fallback_to_env_vars=True, # False by default
                            tweaks=TWEAKS)
```

**Comment by Nitewriter** [comment]
@nicoloboschi Oh shoot, ok I think I'm connecting the dots. The components have the imports that are causing the cycle and the template may have outdated components that I used as an example. I'll try recreating that flow from a blank template.

**Comment by Nitewriter** [comment]
[new-memory-chat.json](https://github.com/user-attachments/files/16071055/new-memory-chat.json)

@nicoloboschi Ok, I did try with a clean start on the flow. I'm still seeing the cycle issue. Let me know if there is anything I can provide to help track down the issue.
