### ISSUE TITLE
LANGFLOW_OPEN_BROWSER ignored in .env file

### ISSUE THREAD

**Issue by DevFyxt** [langflow-ai/langflow#2324]
The LANGFLOW_OPEN_BROWSER value is ignored in the .env file. You can set it to 'false' and langflow will still launch a server side browser instance (such as links).

**Comment by Cristhianzl** [comment]
Hi @DevFyxt,

The pull request addressing this issue has been merged into the dev branch. Could you please check the latest version of the dev branch to see if the error still occurs?

PR: [link](https://github.com/langflow-ai/langflow/pull/2336)

**Comment by carlosrcoelho** [comment]
Hi @DevFyxt ,
 
I hope you're doing well. Just a friendly reminder that if we do not hear back from you within the next 3 days, we will close this issue. If you need more time or further assistance, please let us know. 

Thank you for your understanding!

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
