### ISSUE TITLE
1.0.3 seems not working

### ISSUE THREAD

**Issue by yoursbest** [langflow-ai/langflow#2329]
**Describe the bug**
- I pulled the latest docker image and ran it locally.
- I duplicated the latest 1.0 version of the langflow space at HF.

In either scenario, I saw langflow started with the following messages.

```
Welcome to ⛓ Langflow                                             │
│                                                                   │
│                                                                   │
│ Collaborate, and contribute at our GitHub Repo 🌟                 │
│                                                                   │
│ We collect anonymous usage data to improve Langflow.              │
│ You can opt-out by setting DO_NOT_TRACK=true in your environment. │
│                                                                   │
│ Access http://0.0.0.0:7860
```

However, the application wasn't properly responding. 
- cannot create a new project 
- cannot create a folder
- cannot create an API key
- ...

**Comment by zhangziliang04** [comment]
I have the same question. I run it as 2 steps:
1. pip install langflow
2. langflow run 
then , I can open the webui, But can't create project , upload file (json)

**Comment by akhil20187** [comment]
I am facing the same issue. Installed but can't create the project.

**Comment by RambleRainbow** [comment]
I have the same error.
the api, "http://127.0.0.1:7860/api/v1/flows/", blocked.

**Comment by bruno-growthsales** [comment]
<img width="940" alt="Screenshot 2024-06-25 at 06 08 38" src="https://github.com/langflow-ai/langflow/assets/87706510/5d1cbdc2-2dbc-4d19-bf4c-6c19d3732254">

The same error here! With docker hub 1.0.4
