### ISSUE TITLE
when set custom component in V0.6.5，it is work。 but when start v1.0.0，it is not have custom menu。

### ISSUE THREAD

**Issue by junbin1011** [langflow-ai/langflow#2330]
when set custom component in V0.6.5，it is work。 but when start v1.0.0，it is not have custom menu, and I can not find my custom component.
<img width="540" alt="image" src="https://github.com/langflow-ai/langflow/assets/23181195/aa67424c-6188-485e-8710-f7d9d9f97b6f">
<img width="424" alt="image" src="https://github.com/langflow-ai/langflow/assets/23181195/d1460a87-028a-4370-997d-47445a32fdf2">

**Comment by czHero** [comment]
same problem。versions：1.0.5

**Comment by czHero** [comment]
> same problem。versions：1.0.5

the dir shoul like this:

├── custom_components
│   ├── __init__.py
│   ├── custom
│   │   ├── __init__.py
│   │   └── router1.py
│   └── router2.py
router1.py can be load, but router2.py can not.

**Comment by carlosrcoelho** [comment]
Hi @junbin1011 and @czHero 

Checkout new docs about Custom Component:
https://docs.langflow.org/components-custom-components

Try the new version 1.0.10.

Let me know if you need more assistance. If not, please let us know if this issue can be closed.

**Comment by carlosrcoelho** [comment]
Hey @junbin1011 

You can check out this link to see the new process for setting up the custom component: 

 https://lightning.ai/ogabrielluiz/studios/langflow-1-0-preview 

Let me know if you have any more questions, please.
