### ISSUE TITLE
Question about HuggingFace deployment

### ISSUE THREAD

**Issue by yoursbest** [langflow-ai/langflow#2367]
**Describe the bug**

- I duplicated Langflow/Langflow (1.0.5) to my own private HuggingFace space.
- I used the Models-OpenAI component and adjusted both openai_api_base and openai_api_key to my own OpenAI-compatible API.
- The flow doesn't work due to AuthenticationError (My OpenAI-compatible API responded but said the token was invalid.)
- I pull the 1.0.5 docker image and ran it locally. I did the same setup with the same api_base and api_key. The flow works.

My question: To deploy Langflow on HuggingFace, is there any special configurations needed to make it fully work?

Thank you! Great Project!

**Browser and Version**
 - Edge
 - Version 126.0.2592.68 (Official build) (arm64)

**Comment by nicoloboschi** [comment]
Nothing special. Maybe pasting the flow and the entire error here could help debugging more.

You might want to try DataStax hosting which provides a free hosted playground for LangFlow 
https://langflow.datastax.com/

**Comment by carlosrcoelho** [comment]
Hi @yoursbest
 
I hope you're doing well. Just a friendly reminder that if we do not hear back from you within the next 3 days, we will close this issue. If you need more time or further assistance, please let us know. 

Thank you for your understanding!

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
