### ISSUE TITLE
In Home page the alignment for github button is not correct 

### ISSUE THREAD

**Issue by mksahil** [langflow-ai/langflow#2399]
**Browser and Version**
 - Browser  chrome
 - Version  22

**To Reproduce**
1. Go to  https://www.langflow.org/
2. See the GitHub button alignment 

**Screenshots**
![Screenshot 2024-06-27 172900](https://github.com/langflow-ai/langflow/assets/86847852/7ab30e51-2a17-42b1-9a35-8586772109a7)

**Comment by nicoloboschi** [comment]
There's the Github logo there. A refresh should fix it.
