### ISSUE TITLE
Couldn't get the vector search option

### ISSUE THREAD

**Issue by aleem227** [langflow-ai/langflow#2401]
I am trying to build a RAG application, able to store the data in AstraDB but couldn't find the vector search option or Astro DB search to retrieve data from it.

How can I connect the existing Astra DB to my prompting context without vector search option?

 - Version 1.0.5

![Screenshot 2024-06-27 171820](https://github.com/langflow-ai/langflow/assets/100162716/de04dded-6bec-4a35-bd1f-ae9d543ee6d5)

![Screenshot 2024-06-27 173711](https://github.com/langflow-ai/langflow/assets/100162716/6a4acde9-15ba-4b48-ad39-6c040cda9952)

**Comment by aleem227** [comment]
I am trying to use the no-code solution for it

**Comment by nicoloboschi** [comment]
@aleem227 VectorSearch has been unified with the VectorStore interface. You can use the Search Results output in the vector store.

**Comment by ajai-jayakumar** [comment]
@nicoloboschi based on your suggestion, I tried to add the following flow, but the "search result" accepts the only following options shown in the popup and there is no text filed option available, hence I am unable to connect to my prompt(context) field. Highlighted here in red color.

Any solution for this?

![Screenshot 2024-06-28 at 11 44 34 AM](https://github.com/langflow-ai/langflow/assets/6812847/9b761752-6940-4be6-81ec-15a0828dccbc)

**Comment by aleem227** [comment]
@ajai-jayakumar Exactly the problem I am referencing to.

**Comment by nicoloboschi** [comment]
You can use the "Parse Data" component to transform Data into Text.
![Uploading Screenshot 2024-06-28 at 14.27.15.png…]()

**Comment by WesEngagem** [comment]
I've got the same problem as above. I used the AstraDB Vectore Store component and then used "Parse Data" component as a link between the Astra DB and the Prompt components. Worked perfectly!
