### ISSUE TITLE
Images Not Displaying Correctly in langflow (1.0.5) Docker Container Behind Traefik Proxy

### ISSUE THREAD

**Issue by edumelocmrj** [langflow-ai/langflow#2408]
I am trying to implement langflow (1.0.5) as a Docker container protected by the Traefik proxy and managed by Portainer. The installation worked well, and langflow is fully operational. However, the images and icons presented by the service exposed on the Internet refer to "http://localhost:7860/..." and, obviously, they cannot be displayed at end user's browser. Scouring the source code, I saw that the environment variable "BACKEND_URL" (e.g., <img src={${BACKEND_URL.slice(0, BACKEND_URL.length - 1,)}${BASE_URL_API}files/profile_pictures/${userData?.profile_image ?? "Space/046-rocket.svg"} ?? profileCircle} className="h-7 w-7 shrink-0 focus-visible:outline-0"/>) should provide the public URL for the responses coming from the server, but the container ignores this variable and always displays the images as src=localhost:7860...". Does anyone have any tips?

This is my stack entries in portainer
-----------

services:
  langflow:
    image: langflowai/langflow:latest
    ports:
      - "7860:7860"
    depends_on:
      - postgres
    environment:
      - LANGFLOW_DATABASE_URL=postgresql://langflow:langflow@postgres:5432/langflow
      #- LANGFLOW_CONFIG_DIR=/var/lib/langflow # If uncomment this line, langflow crashes---WHY???
      - LANGFLOW_SUPERUSER=<MY-LOGIN>
      - LANGFLOW_SUPERUSER_PASSWORD=<MY-PASS>
      - LANGFLOW_NEW_USER_IS_ACTIVE=true
      #- LANGFLOW_SECRET_KEY= # I prefer to fill from the application
      - LANGFLOW_AUTO_LOGIN=false
      - LANGFLOW_HOST=0.0.0.0
      - BACKEND_URL=<https://langflow.my-domain.com/> # Always put the slash '/' at the end
    
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.langflow.rule=Host(`<https://langflow.my-domain.com>`)" # My public FDN
      - "traefik.http.routers.langflow.entrypoints=web,websecure"
      - "traefik.http.routers.langflow.tls.certresolver=cloudflare"
      - "traefik.http.services.langflow.loadbalancer.server.port=7860"
 
    volumes:
      - langflow-data:/var/lib/langflow

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: langflow
      POSTGRES_PASSWORD: langflow
      POSTGRES_DB: langflow
    ports:
      - "5432:5432"
    volumes:
      - langflow-postgres:/var/lib/postgresql/data
  
volumes:
  langflow-postgres:
  langflow-data:

networks:
  default:
    name: langflow
    external: false

**Comment by edumelocmrj** [comment]
@Eliotdoesprogramming 

I am using it exactly as you suggested, but it doesn't work

**Comment by oriondesign2015** [comment]
Up
