### ISSUE TITLE
添加 store key 报错

### ISSUE THREAD

**Issue by java668** [langflow-ai/langflow#2421]
There was an error saving the API Key, please try again.
Fernet key must be 32 url-safe base64-encoded bytes

**Comment by lucaseduoli** [comment]
Hi @java668 ,

Could you please tell where did that bug happen, and what did you do to make it happen? I would like to check out this issue with you as soon as possible!

Thanks!

**Comment by java668** [comment]
> Hi @java668 ,
> 
> Could you please tell where did that bug happen, and what did you do to make it happen? I would like to check out this issue with you as soon as possible!
> 
> Thanks!

hello，here
![image](https://github.com/langflow-ai/langflow/assets/124699758/afd241e6-68b1-422c-9bba-75ade7cbaad2)

**Comment by zzleaning** [comment]
> > Hi @java668 ,
> > Could you please tell where did that bug happen, and what did you do to make it happen? I would like to check out this issue with you as soon as possible!
> > Thanks!
> 
> hello，here ![image](https://private-user-images.githubusercontent.com/124699758/345457054-afd241e6-68b1-422c-9bba-75ade7cbaad2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNjU0NDksIm5iZiI6MTcyMDE2NTE0OSwicGF0aCI6Ii8xMjQ2OTk3NTgvMzQ1NDU3MDU0LWFmZDI0MWU2LTY4YjEtNDIyYy05YmJhLTc1YWRlN2NiYWFkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNVQwNzM5MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00Yzc2ZTQ0ZWFhYjFiMjVkZDBkYzg1MjAxNDg4OWM0OTY3NTY3ZDE1M2Q3YjgzM2ZiYWViNTNlZTBiNDI5NDliJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jkrsNsgEsI6RoDwBWWwyKkwepQbwYF1Juhn2C_4mJR4)

你的API Key是根据指引，登录langflow.store后获取的吗？如果不是的话可以尝试使用登录langflow.store后获取的API Key来填写

**Comment by carlosrcoelho** [comment]
https://github.com/langflow-ai/langflow/issues/2458
