### ISSUE TITLE
An error occurred when adding the azureOpenAI component

### ISSUE THREAD

**Issue by alex-ge123** [langflow-ai/langflow#2448]
**Describe the bug**
Add the azureOpenAI component, enter a dialog, and report an error

**Browser and Version**
 - Browser [chrome,]
 - Version [v1.0.5]

**To Reproduce**
1. Add a chatinput  
2. add a AzureOpenAI 
3. add  chat output

**Screenshots**

**Additional context**
Error Building Component
Error building Component Azure OpenAI: build_model not found in AzureChatOpenAIComponent

**Comment by nicoloboschi** [comment]
Duplicates of #2331
