### ISSUE TITLE
How to use createDate to pass parameters to header and body in apiRuquest

### ISSUE THREAD

**Issue by alex-ge123** [langflow-ai/langflow#2449]
**Describe the bug**
How to use createDate to pass parameters to header and body in apiRuquest
![微信图片_20240701143954](https://github.com/langflow-ai/langflow/assets/71969995/0042dc31-86ce-43f7-ad1e-a8cfd63746f5)

**Browser and Version**
 - Browser [chrome, ]
 - Version [v1.0.5]

**To Reproduce**
1.  add a  apiRequest
2. add a createDate 

**Screenshots**

**Additional context**
![微信图片_20240701143754](https://github.com/langflow-ai/langflow/assets/71969995/8e19be55-6cfd-485b-981f-4517877af729)

**Comment by Cristhianzl** [comment]
Hello @alex-ge123,

Could you please review the status of this PR (https://github.com/langflow-ai/langflow/pull/2470) and confirm if the issue has been resolved on your end as well?

Thanks!

**Comment by carlosrcoelho** [comment]
Hi @alex-ge123 ,
 
I hope you're doing well. Just a friendly reminder that if we do not hear back from you within the next 3 days, we will close this issue. If you need more time or further assistance, please let us know. 

Thank you for your understanding!
