### ISSUE TITLE
dosu q&a thread

### ISSUE THREAD

**Issue by dsldsl** [langflow-ai/langflow#2466]
[closed]

**Comment by dsldsl** [comment]
@dosu the UI in langflow component has those fields filled in.  (in the UI, i manually type the inputs)  But i'm getting this error when i try to build / run.  What could that be?

**Comment by dsldsl** [comment]
@dosu can you explain how the stop() function works with reguards to multiple outputs and this error:

<img width="376" alt="image" src="https://github.com/langflow-ai/langflow/assets/50015/286826b0-8133-440d-b6b9-4acdaa70aff3">

**Comment by carlosrcoelho** [comment]
Hi @dsldsl  ,

Do you need any assistance with this case? If not, please let us know if this issue can be closed.
