### ISSUE TITLE
ChatOllama problem

### ISSUE THREAD

**Issue by alonsoir** [langflow-ai/langflow#2487]
I added the next component to my langflow:

ChatOllama
83
1193
by davidleconte | ⛓︎ v1.0.0a7
Local LLM for chat with Ollama.

i got this:

/Users/aironman/Library/Caches/pypoetry/virtualenvs/langflow-sample-OG1lJKTa-py3.11/lib/python3.11/site-packages/pydantic/main.py:1058: PydanticDeprecatedSince20: The `__fields__` attribute is deprecated, use `model_fields` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.8/migration/
  warnings.warn(

**Comment by nicoloboschi** [comment]
@alonsoir does it compromise the functionalities of the component? the pydantic warning is just a log message, shouldn't be problematic

**Comment by alonsoir** [comment]
In my opinion, the framework is almost broken, yesterday i tried to use an example from medium, you know, grab PyPDF, grab ChatOllama, grab Faiss, etc,...,connect everything, click run, you got everything. Well PyPDF component wasnt able to link with nothing, ChatOllama was not there, so it was impossible to do nothing. I know that the software is not stable yet, most components are not, probably i will have to go to official examples and let old Medium post for another day.
