### ISSUE TITLE
CSV Agent does not pass parameter to allow dangerous code (1.0.6)

### ISSUE THREAD

**Issue by Arron-Clague** [langflow-ai/langflow#2525]
CSV Agent does not pass parameter to allow dangerous code to langchain component, and throws an error. 

Suggested change to CSV Component : 

from langchain_experimental.agents.agent_toolkits.csv.base import create_csv_agent

from langflow.custom import CustomComponent
from langflow.field_typing import AgentExecutor, LanguageModel

class CSVAgentComponent(CustomComponent):
    display_name = "CSVAgent"
    description = "Construct a CSV agent from a CSV and tools - ADC."
    documentation = "https://python.langchain.com/docs/modules/agents/toolkits/csv"

    def build_config(self):
        return {
            "llm": {"display_name": "LLM", "type": LanguageModel},
            "path": {"display_name": "Path", "field_type": "file", "suffixes": [".csv"], "file_types": [".csv"]},
            "adc": {"display_name": "Allow Dangerous Code", "type": True,"advanced" : True},
            "handle_parsing_errors": {"display_name": "Handle Parse Errors", "advanced": True},
            "agent_type": {
                "display_name": "Agent Type",
                "options": ["zero-shot-react-description", "openai-functions", "openai-tools"],
                "advanced": True,
            },
        }

    def build(
        self, llm: LanguageModel, path: str, handle_parsing_errors: bool = True, agent_type: str = "openai-tools", adc: bool=True
    ) -> AgentExecutor:
        # Instantiate and return the CSV agent class with the provided llm and path
        return create_csv_agent(
            llm=llm,
            path=path,
            agent_type=agent_type,
            verbose=True,
            allow_dangerous_code=adc,
            agent_executor_kwargs=dict(handle_parsing_errors=handle_parsing_errors),
        )

**Comment by carlosrcoelho** [comment]
Hi @Arron-Clague  ,

Do you need any assistance with this case? If not, please let us know if this issue can be closed.

**Comment by Arron-Clague** [comment]
Hi there : great to ear from you ! 

Im good as fixed the issues in the component code as I described in my own flows : I would imagine it would be helpful though to update the component in the project code so others do not have the issue ? 

Thanks,

Arron

**Comment by carlosrcoelho** [comment]
@Arron-Clague,

Awesome to hear you got it fixed!

We'll check out the changes you mentioned and update the component in the project code so others won't run into the same issue. Thanks a ton for pointing that out!

We'll close this issue for now, but don't hesitate to reach out if you have more suggestions or need anything else.

Thanks again for your help!
