### ISSUE TITLE
 validation error for ChatOutputResponse sender_name

### ISSUE THREAD

**Issue by mnanjana2020** [langflow-ai/langflow#2546]
**Describe the bug**
A simple flow with latest langflow UI. 
Text Input has a Text (as Jim) --> Chat Input ( sender_name)
when I build these two components, I get validation error.
1 validation error for ChatOutputResponse
sender_name
  Input should be a valid string [type=string_type, input_value=Message(text_key='text', ...4743-9ae7-4b918d145efa'), input_type=Message]
    For further information visit https://errors.pydantic.dev/2.8/v/string_type

**Browser and Version**
 - Chrome - Version 126.0.6478.127 (Official Build) (x86_64)

**To Reproduce**
As explained above. 

**Screenshots**
 
![Screenshot 2024-07-04 at 9 55 54 PM](https://github.com/langflow-ai/langflow/assets/129682529/dd3596ef-92f4-4914-8d2f-b636281d914b)
![Screenshot 2024-07-04 at 9 56 19 PM](https://github.com/langflow-ai/langflow/assets/129682529/7a8df65b-5273-44ab-a5dd-d3450666311e)

**Additional context**
Post langflow installation, I had this pydantic error within the pydanitc module itself. ..but I did supress the warning messages since there was already known issue on this and it was no harm..

(langflow) mnanjana@MNANJANA-M-77J4 langflow % python3 run_langflow.py run
Starting Langflow v1.0.6...
╭───────────────────────────────────────────────────────────────────╮
│ Welcome to ⛓ Langflow                                             │
│                                                                   │
│                                                                   │
│ Collaborate, and contribute at our GitHub Repo 🌟                 │
│                                                                   │
│ We collect anonymous usage data to improve Langflow.              │
│ You can opt-out by setting DO_NOT_TRACK=true in your environment. │
│                                                                   │
│ Access http://127.0.0.1:7860                                      │
╰───────────────────────────────────────────────────────────────────╯
/Users/mnanjana/RAG/langflow/lib/python3.12/site-packages/pydantic/main.py:1059: PydanticDeprecatedSince20: The `__fields__` attribute is deprecated, use `model_fields` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.8/migration/
  warnings.warn(
/Users/mnanjana/RAG/langflow/lib/python3.12/site-packages/pydantic/main.py:1059: PydanticDeprecatedSince20: The `__fields__` attribute is deprecated, use `model_fields` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.8/migration/
  warnings.warn(
/Users/mnanjana/RAG/langflow/lib/python3.12/site-packages/pydantic/main.py:1059: PydanticDeprecatedSince20: The `__fields__` attribute is deprecated, use `model_fields` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.8/migration/

**Comment by carlosrcoelho** [comment]
Hi @mnanjana2020  ,

Do you need any assistance with this case? If not, please let us know if this issue can be closed.

Check out the latest version 1.0.10.
<img width="1653" alt="image" src="https://github.com/user-attachments/assets/adbaa8cd-e281-4445-b393-e62c9b8c0282">

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
