### ISSUE TITLE
erro bug na traduçao 

### ISSUE THREAD

**Issue by lefee1** [langflow-ai/langflow#2547]
quando vou traduzir para o portugues ele da erro ai tenho que voltar para o ingles

**Comment by carlosrcoelho** [comment]
@lefee1 tudo bem?

Poderia detalhar melhor o seu problema?

Caso não esteja com o problema, me avise para essa issue ser encerrada, por favor.

**Comment by carlosrcoelho** [comment]
Obrigado pela sua contribuição! Esta issue será fechada. Se você tiver qualquer dúvida ou encontrar outro problema, por favor, abra uma nova issue e estaremos prontos para ajudar.
