### ISSUE TITLE
Question About Chroma And Retrieval QA

### ISSUE THREAD

**Issue by zzleaning** [langflow-ai/langflow#2550]
I am a beginner and there are two questions that are bothering me. 
I built a Document QA using the components in the diagram and used a docx type file as the data source. 
![1](https://github.com/langflow-ai/langflow/assets/111033943/16a93fdc-dd9b-4c48-8ac9-e530c8043bfc)

Whenever I want to test this QA, even if I use the same data source, it takes a long time to build a vector database.Even if I set a local storage address, it still remains the same.  Is there any way to adjust components so that this vector database does not need to be repeatedly built?

 In addition, it may be that there is a problem with my settings. Sometimes the answer results are obtained based on text, but sometimes they are generated independently without relying on text. The returned data source file is always the same, and the required file is not returned based on the problem. Please tell me what adjustments should be made? thank you!

**Comment by carlosrcoelho** [comment]
Hi @zzleaning 

Do you need any assistance with this case? If not, please let us know if this issue can be closed.

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
