### ISSUE TITLE
AstraDB component Ingest all items twice

### ISSUE THREAD

**Issue by thomasbachet** [langflow-ai/langflow#2552]
As I run the flow to ingest data, it does it twice. So each item is captured twice in the AstraDB data collection. 

**Browser and Version**
- Langflow version 1.0.6 running on local a virtual environment

**To Reproduce**
- use the pre-built flow 'Vector Store RAG'
- use the existing flow to ingest any content

Does anyone that experience the same?

**Comment by nicoloboschi** [comment]
Hey @thomasbachet thanks for reporting. Yes it's a bug. I've fixed it in this PR #2573 
Meanwhile you could replace the entire astradb component with this content: https://raw.githubusercontent.com/langflow-ai/langflow/98beda5532b9029e016d966cfc81bca1722d4c5c/src/backend/base/langflow/components/vectorstores/AstraDB.py
