### ISSUE TITLE
ChromaDB 

### ISSUE THREAD

**Issue by AtmehEsraa** [langflow-ai/langflow#2575]
I try to link chroma DB, to the vector store and it doesnt work, could you help me in that 

![image](https://github.com/langflow-ai/langflow/assets/153764152/c250d031-21ba-46de-bbd4-fae7bd701b88)

**Comment by carlosrcoelho** [comment]
@hakeemsyd the VectorStore Retriever is outdated, thanks for sharing this. I'll let the team know about this and make an update soon.

**Comment by carlosrcoelho** [comment]
https://github.com/langflow-ai/langflow/issues/2698

**Comment by anovazzi1** [comment]
@AtmehEsraa I believe there's a misunderstanding about the retriever. One of the outputs is the retriever itself, and the other is the search result. Therefore, you don't need a separate vectorStore Retriever, as the retriever is already included as one of the outputs.
