### ISSUE TITLE
Accessibility of Projects created by Non-Admin users

### ISSUE THREAD

**Issue by pranjala3** [langflow-ai/langflow#2585]
**Describe the bug**
The projects that the non-admin users create, do not show up in their workspace. Instead, it shows in the Admin's workspace only. It's as if no projects have been created by those users.
Those projects that show up in Admin's workspace, when the Admin tries to Click to open, nothing happens. It's just a Blank click.

**Browser and Version**
 - Browser [e.g. chrome, safari] - Chrome+Safari
 - Version [e.g. 22] - Chrome version - 126.0.6478.127

**To Reproduce**
1. Setup Langflow with Authentication
2. Create Users
3. Login as the non-admin user, and create project
4. Login as the admin user on same or another browser, and you'll find the project in there.
5. Try clicking the project to view the flow.

**Additional context**
Issue can be reproduced with latest & greatest at this time - v1.0.6

**Comment by Cristhianzl** [comment]
Hi @pranjala3,

Could you please review the following PR: [Langflow PR #2610](https://github.com/langflow-ai/langflow/pull/2610)? This should address and fix the issue you've been experiencing.

Thanks for your cooperation!
