### ISSUE TITLE
Problema ao importar .json no Primeiro desafio

### ISSUE THREAD

**Issue by almeida-guilherme** [langflow-ai/langflow#2596]
![error](https://github.com/langflow-ai/langflow/assets/96318988/fc57fce5-00e1-4d02-bdf9-04f9fdc2aa3b)
Ao tentar importar o arquivo json do primeiro desafio, obtive esse erro. Tentei tanto no firefox quanto no chrome

**Comment by solubien** [comment]
[AEpsrBblwSb6QZR0G6K463slRo.json](https://github.com/user-attachments/files/16136641/AEpsrBblwSb6QZR0G6K463slRo.json)
tb tive o mesmo erro

**Comment by massilva** [comment]
Eu também estou com esse error.

**Comment by almeida-guilherme** [comment]
Consegui ajuda nesse erro. Pelo fato de haver instabilidade na versão cloud do langflow, está ocorrendo esse erro. Para resolver, precisa instalar o langflow pelo pip e depois rodar o langflow. 
------------------
Instalação pelo pip: python -m pip install langflow -U
Executar langflow localmente: python -m langflow run
Para mais informações, segue a documentação:https://docs.langflow.org/getting-started/install-langflow
Espero que isso também te ajude, @massilva, como também me ajudou!

**Comment by carlosrcoelho** [comment]
Obrigado pela sua contribuição! Esta issue será fechada. Se você tiver qualquer dúvida ou encontrar outro problema, por favor, abra uma nova issue e estaremos prontos para ajudar.
