### ISSUE TITLE
Erro ao importar o json

### ISSUE THREAD

**Issue by solubien** [langflow-ai/langflow#2599]
[AEpsrBblwSb6QZR0G6K463slRo.json](https://github.com/user-attachments/files/16136553/AEpsrBblwSb6QZR0G6K463slRo.json)
Em Datastax ao importar o json do desafio da semana 1 foi apresentado um erro e a importação não foi possível. 
![Captura de tela 2024-07-08 235131](https://github.com/langflow-ai/langflow/assets/17445683/330f5042-9ad0-4283-b077-b37363bfde5a)

**Comment by carlosrcoelho** [comment]
@solubien a versão do Langflow no DataStax é mais antiga, o flow do desafio contém features e novas implementações que somente na versão pip é possível rodar.

Participe da comunidade do Discord do Langflow, temos um canal dedicado para a competição. 

Link oficial IA Devs Discord: https://discord.gg/ZGrjF4v2N6
