### ISSUE TITLE
Mac can not install psycopg-binary==3.2.1 (MAC 13.5.1 (22G90) M1)

### ISSUE THREAD

**Issue by xiaoqiangkx** [langflow-ai/langflow#2600]
**Describe the bug**
Hey Forks, I run `make backend`, it failed 

**Browser and Version**
 - MAC 13.5.1 (22G90) M1

**Code**
```
Package operations: 1 install, 0 updates, 0 removals

  - Installing psycopg-binary (3.2.1): Failed

  RuntimeError

  Unable to find installation candidates for psycopg-binary (3.2.1)

  at ~/Library/Application Support/pypoetry/venv/lib/python3.10/site-packages/poetry/installation/chooser.py:74 in choose_for
       70│ 
       71│             links.append(link)
       72│ 
       73│         if not links:
    →  74│             raise RuntimeError(f"Unable to find installation candidates for {package}")
       75│ 
       76│         # Get the best link
       77│         chosen = max(links, key=lambda link: self._sort_key(package, link))
       78│ 

Cannot install psycopg-binary.

make[1]: *** [install_backend] Error 1
make: *** [backend] Error 2
```

I can change `psycopg-binary` and `psycopg` == 3.1.19 and build a new `poetry lock` to run it.

Could you please use "~3.1.19" in `pyproject.toml` file?

```
psycopg = "~=3.1.19"
psycopg-binary = "~=3.1.19"
```

**Comment by carlosrcoelho** [comment]
@xiaoqiangkx Do you need any assistance with this case? If not, please let us know if this issue can be closed.

**Comment by ogabrielluiz** [comment]
Hey @xiaoqiangkx 

How are you? 

This is weird. We have 3.19 in the pyproject.toml
[psycopg-binary = "^3.1.9"](https://github.com/langflow-ai/langflow/blob/03811d2f82612eaf311eff7ec9793aa9ab8516f9/pyproject.toml#L53)

**Comment by rafrafek** [comment]
For M1 Macs the minimum MacOS version is 14:

```
psycopg_binary-3.2.1-cp312-cp312-macosx_12_0_x86_64.whl
psycopg_binary-3.2.1-cp312-cp312-macosx_14_0_arm64.whl
```

For Intel ones the minimum is MacOS 12.

**Comment by rafrafek** [comment]
See https://github.com/psycopg/psycopg/issues/858

**Comment by rafrafek** [comment]
> This is weird. We have 3.19 in the pyproject.toml [psycopg-binary = "^3.1.9"](https://github.com/langflow-ai/langflow/blob/03811d2f82612eaf311eff7ec9793aa9ab8516f9/pyproject.toml#L53)

There is:

```toml
psycopg = "^3.1.9"
psycopg-binary = "^3.1.9"
```

which means it's compatible with 3.2.1 and the lock file confirms that:

https://github.com/langflow-ai/langflow/blob/main/poetry.lock#L7287
https://github.com/langflow-ai/langflow/blob/main/poetry.lock#L7310

BTW it's better to define

```toml
psycopg = { extras = ["binary"], version = "^3.1.9" }
```

rather than

```toml
psycopg = "^3.1.9"
psycopg-binary = "^3.1.9"
```

**Comment by paulosalvatore** [comment]
Any news on this?

<img width="945" alt="image" src="https://github.com/user-attachments/assets/8ec284f9-ccb6-49dd-bede-ab61cf4557a6">

**Comment by tommyhe6** [comment]
Refer to https://github.com/psycopg/psycopg/issues/858 as well as the warning for MacOS ARM chips in https://www.psycopg.org/psycopg3/docs/basic/install.html#binary-installation.

The issue seems to be difficulty in builders targeting older versions of MacOS on ARM chips (https://github.com/psycopg/psycopg/issues/858#issuecomment-2217172495).

**Comment by jordanrfrazier** [comment]
Thank you all for digging into this issue. I've updated to lock to 3.1.19 for now, as >=3.1.20 will cause issues for users on macOS 11, 12, 13. 

See https://endoflife.date/macos for EOL for 11, 12, 13.

https://github.com/langflow-ai/langflow/pull/3292/files
