### ISSUE TITLE
There is a problem with the Create data component

### ISSUE THREAD

**Issue by alex-ge123** [langflow-ai/langflow#2618]
**Describe the bug**
There is a problem with the Create data component   

Add a Create data component and fill in the key and value, click Run, no output data

**Browser and Version**
 - Browser [chrome,]
 - Version [v1.0.7]

**To Reproduce**
![微信图片_20240710154806](https://github.com/langflow-ai/langflow/assets/71969995/2a184f21-a6d9-4016-bddc-37b03483cae6)

**Screenshots**

**Additional context**

**Comment by alex-ge123** [comment]
![Uploading 微信图片_20240710155303.png…]()

**Comment by alex-ge123** [comment]
![Uploading 微信图片_20240710155303.png…]()

**Comment by jordanrfrazier** [comment]
Hi @alex-ge123, @codenprogressive, can you please upgrade Langflow to 1.0.14 and try again? Plmk if you encounter any issues. 

I was able to successfully create and parse data: 
<img width="725" alt="Screenshot 2024-07-31 at 9 00 08 PM" src="https://github.com/user-attachments/assets/b304d37d-fce9-497f-8b31-f1c8db8842cf">
<img width="1175" alt="Screenshot 2024-07-31 at 9 00 12 PM" src="https://github.com/user-attachments/assets/b23a6e3b-8ec3-4cdb-9744-ca4ef6f37a56">
