### ISSUE TITLE
Add a thousand sails component

### ISSUE THREAD

**Issue by alex-ge123** [langflow-ai/langflow#2632]
**Describe the bug**

**Browser and Version**
 - Browser [ chrome,]
 - Version [v1.0.7]

**To Reproduce**

**Screenshots**

**Additional context**
![微信图片_20240711163928](https://github.com/langflow-ai/langflow/assets/71969995/e2c4b039-35d7-4e5d-8083-2807df451b61)
![微信图片_20240711163928](https://github.com/langflow-ai/langflow/assets/71969995/bf8a9a6e-edeb-4909-83b7-f76221210f57)

**Comment by carlosrcoelho** [comment]
@alex-ge123 

Try it with the new version of Langflow and let me know if the problem still happens.

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
