### ISSUE TITLE
Invalid Discord server invitation

### ISSUE THREAD

**Issue by hellmrf** [langflow-ai/langflow#2686]
**Describe the bug**
Link to Discord on all pages (https://discord.com/invite/EqksyE2EX9) is invalid.

**To Reproduce**
1. Try to join on Discord using the link https://discord.com/invite/EqksyE2EX9

**Screenshots**
![image](https://github.com/user-attachments/assets/5df3369f-ecdc-4341-98ec-7df50f57dd19)

**Comment by carlosrcoelho** [comment]
@hellmrf 

The link https://discord.com/invite/EqksyE2EX9 is working normally. If you're still having trouble, you can also access it through this one: https://discord.gg/ZGrjF4v2N6
