### ISSUE TITLE
i dragged an updated component which was avaiable from the website to my my  local flow now i cant even see my flow or access it. 

### ISSUE THREAD

**Issue by homanmirgolbabaee** [langflow-ai/langflow#2688]
i wanted to use "Vectara" examples from store ( on local )  , to use it on my flow , i downloaded the .json and dragged it to my main flow project. the flow has been broken and dosent even let me reverse anthing or have another look at it.

i have to re-do all the flow component because i cant re-visit my project. 

i tried re-running the envoirment still i get this error.

![Screenshot 2024-07-13 144421](https://github.com/user-attachments/assets/340754fe-c82a-4360-b085-6857bc0798a2)

**Comment by jcsacto** [comment]
I have this same problem, was just testing a component from the store (file loader), added it to my working flow to try it out and now I can't access that flow at all because I just keep getting that error shown above.  It appears whatever dependencies get installed when adding component to a flow are NOT removed when you delete that component.

**Comment by Cristhianzl** [comment]
on it

**Comment by Cristhianzl** [comment]
hi @jcsacto @homanmirgolbabaee,

Thanks for your messages.

I checked Vectara's components (both of them) and confirmed that the error no longer exists in the latest version of Langflow. However, these components are outdated, which might cause errors when you try to run or use them. You may need to rewrite part of the components or use the newer ones from the sidebar. See the image below for the warning about this issue.

![image](https://github.com/user-attachments/assets/4808b338-1164-4e48-8df6-b3e439bb8840)

I also checked both of the File Loader's components in the store, and the error does not occur (see images below). However, these components are outdated, so you might need to use the new ones from the sidebar or rewrite parts of them.

![image](https://github.com/user-attachments/assets/4ce6fdc4-8551-41f6-87f6-bfd2154b1396)

Any further questions feel free to contact us ^^
