### ISSUE TITLE
error when importing AI_ML_API json file

### ISSUE THREAD

**Issue by xyao7chen** [langflow-ai/langflow#2689]
[AI_ML API Component.json](https://github.com/user-attachments/files/16202808/AI_ML.API.Component.json)

**Comment by carlosrcoelho** [comment]
Hey @xyao7chen 

We redid this component. Update your Langflow to the latest version (1.0.12 as of today) and select it in the sidebar under Models. Let me know if it works, please.

<img width="405" alt="image" src="https://github.com/user-attachments/assets/61069694-6ffb-43bc-8814-c53efb8c9ee6">
