### ISSUE TITLE
update 1.0.9 error!

### ISSUE THREAD

**Issue by aiwenForGit** [langflow-ai/langflow#2692]
**Describe the bug**
my langflow is updated from 1.0.7 to 1.0.9 today ,found many flow can't run.for example I have download crewai flow.

**Screenshots**
![image](https://github.com/user-attachments/assets/5205a38b-b713-4b56-b5d4-fbe800d2d3b5)

I need you help!

**Comment by aiwenForGit** [comment]
reback to 1.0.7 is normal.so It may change something about function

**Comment by carlosrcoelho** [comment]
Hi @aiwenForGit 

Do you need any assistance with this case? If not, please let us know if this issue can be closed.
