### ISSUE TITLE
about sharing my flows to https://www.langflow.store/store/

### ISSUE THREAD

**Issue by zhengqianhe0** [langflow-ai/langflow#2693]
I have deployed langflow on my own laptop and shared a custom flow with the store on the official website. Can this operation be cancelled?

**Comment by carlosrcoelho** [comment]
@zhengqianhe0 

You need to go to the store's website, find your flows/components section, and remove it directly from there.

![image](https://github.com/user-attachments/assets/415d26d2-fff2-4822-a320-8686eb185b82)

Please, let me know if it works, please.

**Comment by carlosrcoelho** [comment]
This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
