### ISSUE TITLE
Store examples crash Langflow  v1.0.9

### ISSUE THREAD

**Issue by philflav** [langflow-ai/langflow#2695]
When loading store examples I get errors.

D:\AI_Projects\langflow\lib\site-packages\pydantic\main.py:1059: PydanticDeprecatedSince20: The `__fields__` attribute is deprecated, use `model_fields` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.8/migration/
  warnings.warn(

**Comment by Cristhianzl** [comment]
hi @philflav,

Could you please inform me which specific example you are trying to use?

I can say a few things for now. Our platform has undergone several serious updates, and some components of the examples in the store have not been updated yet (some of them are deprecated too).

So, I can advise you on some workarounds:

- Try getting the same component updated from the sidebar:

![image](https://github.com/user-attachments/assets/a60f1ecd-9467-4685-b152-198c8580e1f2)


- Try updating the component in the flow when possible (by clicking on the alert icon):

![image](https://github.com/user-attachments/assets/77126834-cd2e-4793-9b3c-668502de89ea)


Furthermore, I would say that the updates for several components/flows in the Store will come as soon as possible. Just stay connected with us on Discord/Github for news about it.

Thank you!

**Comment by carlosrcoelho** [comment]
@philflav 
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
