### ISSUE TITLE
Unable to see Vector Search Command.

### ISSUE THREAD

**Issue by usha2405** [langflow-ai/langflow#2698]
<img width="1093" alt="Screenshot 2024-07-14 at 7 01 56 PM" src="https://github.com/user-attachments/assets/41afc1b8-cc62-4732-ad10-078d5064ecd3">

I am getting this error while importing my file. I installed langflow on my system. But it doesn't have vector search component. Please help me resolve the issue.

**Comment by anovazzi1** [comment]
Hi @usha2405 , the vector search component is now deprecated; you only need to use the vector store component 😊. This change shouldn't break your application. If you don't have any sensitive data in your flow, could you share it with me so I can debug it for you?

**Comment by anovazzi1** [comment]
I'll go ahead and close this issue. If you need any further assistance, please feel free to create a new one—we're always happy to help.
