### ISSUE TITLE
endpoint_name

### ISSUE THREAD

**Issue by zhengqianhe0** [langflow-ai/langflow#2722]
Can you tell me the purpose of the 'endpoint_name' attribute in the local database table 'flow'? This attribute defaults to a null value, and when clicking 'share' to upload my flow to the store, the current flow's endpoint_name attribute was not uploaded in the http request? Now that I have the ID of the flow, can I uniquely identify a flow

**Comment by carlosrcoelho** [comment]
@zhengqianhe0 

Do you need any assistance with this case? If not, please let us know if this issue can be closed.
