### ISSUE TITLE
noob here, but i couldn't import asrta vector search from store

### ISSUE THREAD

**Issue by 6921min** [langflow-ai/langflow#2749]
what exactly i've expreienced, was that i couldn;t find out astra-vector-search component in locally installed langflow(maybe version issues), but only at stores. so i made choice to use it,  then i import and findout that it now could be seen at my project but only confronted sudden error happened. glad if floks provide some supports

**Comment by nicoloboschi** [comment]
@6921min what kind of environment were you using? 
could you try to run 
```
pip install langflow -U --force-reinstall
```
or use the docker image
```
docker run --rm -p 7860:7860 langflowai/langflow:latest
```

**Comment by 6921min** [comment]
i just found that in the lastest model, it such vector DB search fuction were been merged in to vector store components, coresponding to each single DBs.

And i got managed to sucessfully use as what i meant to do so.

anyway thx fir atention! ㅇㅅㅇ
