### ISSUE TITLE
Unable to Upload PDFs in LangFlow Playground

### ISSUE THREAD

**Issue by jjboy55** [langflow-ai/langflow#2750]
**Description:**
I am currently working on a project that involves uploading and processing PDF files using LangFlow Playground. However, I have encountered an issue where the system does not allow me to upload PDF files. This functionality is crucial for my project's requirements.

**Steps to Reproduce:**

Go to LangFlow Playground.
Attempt to upload a PDF file using the provided upload feature.
Observe the behavior and the error message (if any).

**Expected Behavior:**
The PDF file should be successfully uploaded and processed by LangFlow Playground.

**Actual Behavior:**
The system does not allow the upload of PDF files. System provides the following error; 

**Log**: Error uploading file
Please ensure your file has one of the following extensions:
png, jpg, jpeg

**Environment:**
Operating System: Mac OS
Browser: Arc Browser
LangFlow Version: Langflow version 1.0

**Additional Context:**
This issue is blocking the progress of my project, which involves a Retrieval-Augmented Generation (RAG) system that ingests PDF files to generate tailored responses. Your prompt assistance in resolving this issue would be greatly appreciated.

**Comment by carlosrcoelho** [comment]
Hey @jjboy55 

To use a PDF, you can use the File component located in the Data tab on the sidebar.

![image](https://github.com/user-attachments/assets/4d7a8b0d-2664-4037-860e-f67d1f89baf8)

Please let me know if it works.

**Comment by mazierovictor** [comment]
And how do I do it in the online version of LangFlow, so that it allows me to attach PDFs in the playground?

**Comment by anovazzi1** [comment]
@mazierovictor did you try jut drag and drop on the playground?

**Comment by mazierovictor** [comment]
> @mazierovictorrn o playground aceita apenas imagens, pdfs podem ser carregados usando o componente de arquivo

@anovazzi1 Does this mean that it is impossible to create a chatbot that interacts with PDF files? For each pdf file, will I have to open the langflow stream and change the file?

**Comment by anovazzi1** [comment]
@mazierovictor , it is not, you can update you flow or use tweaks to send you file path to your chatbot

**Comment by mazierovictor** [comment]
@anovazzi1 What I need is to create a PDF chat where I upload a PDF file and ask him questions. Given this and what you told me, would you have any suggestions?

**Comment by anovazzi1** [comment]
@mazierovictor do you need to have your own Ui or you plan to use langflow playground

**Comment by anovazzi1** [comment]
during the usage of the playground using a file component to upload the pdf is the way to go, when using your own ui just upload the file using the restAPI

**Comment by mazierovictor** [comment]
@anovazzi1 I'm trying to upload using RestAPI, but it keeps giving the error { "message": "'utf-8' codec can't decode byte 0xe2 in position 10: invalid continuation byte" }, I'm using python to create the script, But when I attach this error, this error persists. Any suggestions?

**Comment by WEFVTURA** [comment]
I'm having a similar issue, I'm trying to upload both pdf and docx files and nothing happens, no loading, no errors. Some suggestions? :)

**Comment by mazierovictor** [comment]
Se você estiver usando uma UI própria, verifica se o nome do arquivo está passando corretamente..

**Comment by WEFVTURA** [comment]
I'm actually still in the playground 😬
I've been trying with different files but nada
![image](https://github.com/user-attachments/assets/f0fa31a8-511d-4f9e-8f6f-d297f4b7aa11)
 here is a screen of the errors from the inspect console

**Comment by WEFVTURA** [comment]
Also this one 
![image](https://github.com/user-attachments/assets/f7d5ef6c-6aba-47ca-8ffd-3a54ec777eff)

**Comment by mazierovictor** [comment]
Você está executando diretamente pelo playground usando um módulo file, então você precisa anexar um arquivo nesse módulo para conseguir executar. 

Agora, se você vai fazer sua propria UI, sugiro que use o componente directory e passe via api o diretório completo para processmanto.

**Comment by WEFVTURA** [comment]
> Você está executando diretamente pelo playground usando um módulo file, então você precisa anexar um arquivo nesse módulo para conseguir executar.
> 
> Agora, se você vai fazer sua propria UI, sugiro que use o componente directory e passe via api o diretório completo para processmanto.

Many Thanks Victor. Problem solved, I also changed internet connection, from wifi to 5g and it changed the outcome. It might be that I had some firewall about file upload. Now is working :))

**Comment by ijodmusakh** [comment]
@mazierovictor did you find a solution to upload pdf to chat?

**Comment by flefevre** [comment]
yes it is strange that the playground do not accept any pdf word file ?
Can we have an update on it?
Thanks

**Comment by owgee** [comment]
I'm having the same issue, even customizing the Chat input with `FileInput(file_types=[
    "text/plain",
    "application/json",
    "application/xml",
    "text/csv",
    "application/pdf",
])` doesn't seem to work!
