### ISSUE TITLE
Flows are not visible in any of "Prototype" Components

### ISSUE THREAD

**Issue by burakcbdn** [langflow-ai/langflow#2752]
### Bug Description

I am trying to run one of my flows as a tool in my other flow, but when I try to import component, the options of component is empty, I tried all of them (Run Flow, Flow as Tool, Sub Flow.. etc) but in all of them, options to select flow name is empty. 

![Screenshot 2024-07-17 at 15 36 13](https://github.com/user-attachments/assets/c3ca7d30-055c-4b2f-a249-01d777dad81a)
![Screenshot 2024-07-17 at 15 36 07](https://github.com/user-attachments/assets/e446985e-75a7-4aa9-acc9-bd0455385e5a)

### Reproduction

1. Create a basic flow and save
2. Create a new flow
3. Add any prototype component to import other flow
4. Click on options
5. Options are empty

### Expected behavior

1. Create a basic flow and save
2. Create a new flow
3. Add any prototype component to import other flow
4. Click on options
5. Options should show the flow created before

### Who can help?

@anovazzi1 @italojohnny @ogabrielluiz 

### Operating System

Macos Sonoma 14.5

### Langflow Version

1.0.9

### Python Version

- [X] 3.12
- [ ] 3.11
- [ ] 3.10

**Comment by burakcbdn** [comment]
Thank you @dosu I checked with editing the component code, and it prints the flows that I created, and stores them in a list, but they are not visible at the ui. it could be because "update_build_config" method is not being called.

**Comment by h-arnold** [comment]
I can confirm I'm experiencing the same bug. I'm getting it on the v.1.0.9 official docker image with frontend and backend included.

**Comment by Cristhianzl** [comment]
hi @burakcbdn @h-arnold,

Some components inside the Experimental tab aren't updated with the new schemas. Some of them (as in your case) are on standby to receive a new update on the code. We will soon update these faulty components, but unfortunately, for now, I would advise you to be patient.

As a 'workaround', I suggest grouping components of a flow so they look like a single component on the canvas.

**Comment by burakcbdn** [comment]
Thanks for the answers, but as it is not working on my local development environment, it is working when I use it on datastax deployment.I just wondered, what's the reason behind this?

**Comment by Cristhianzl** [comment]
@burakcbdn did you checked if datastax environment version is the same as your develop local version?

**Comment by lucaseduoli** [comment]
Hello!

Flow as Tool and Subflow components are still broken on main. I'm fixing it in issue #2972, so, if you want, you can follow my progress through that issue. 

If there is an issue after #2972 is resolved, feel free to open this issue again.
