### ISSUE TITLE
Qdrant vectorisation from Word document error building component

### ISSUE THREAD

**Issue by peter-boucher** [langflow-ai/langflow#2753]
### Bug Description

```
TypeError: VectorStore.from_documents() missing 1 required positional argument:
                             'embedding'
```
![image](https://github.com/user-attachments/assets/ce75b6e9-47bb-4264-8fe8-7ecc723e0202)

### Reproduction

Pre requisite: Qdrant container running locally using docker
``` qdrant-docker-compose.yml
services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    volumes:
      - ./qdrant_data:/qdrant_data
```
2. Using the Vector Store RAG template as a base, create a new project.
3. Remove the 'OpenAI Embeddings' Components from both flows and replace with 'Azure OpenAI Embeddings'
4. Complete the 'Azure OpenAI Embeddings' components with your Azure OpenAI Studio deployment endpoint
5. Replace the AstraDB component in both flows with 'Qdrant' vector store
6. Complete the Qdrant component with the collection name, leave other settings as default for a locally running instance
7. In the ingestion flow (bottom centre canvas) select a .docx file as your file input in the File Data component
8. Click run on the File Data Component
Observe the error: "Error building component Qdrant: 
VectorStore.from_documents() missing 1 required positional argument:
                             'embedding'"

### Expected behavior

Successful build of the embedding flow

### Operating System

MacOS Sonoma 14.5 (23F79)

### Langflow Version

1.0.7

### Python Version

- [X] 3.12
- [ ] 3.11
- [ ] 3.10

**Comment by carlosrcoelho** [comment]
Hey @peter-boucher 

Please make sure before you run your flow, click on ⚠️ to update the required components, and then try to run your flow.

Please let me know if it works.

**Comment by carlosrcoelho** [comment]
Hi @peter-boucher 

Do you need any assistance with this case? If not, please let us know if this issue can be closed.

**Comment by peter-boucher** [comment]
> Hi @peter-boucher
> 
> Do you need any assistance with this case? If not, please let us know if this issue can be closed.

Thanks @carlosrcoelho I was able to diagnose this was an issue with the embedding model Azure OpenIA Embeddings that caused an exception in the Vector DB module for Qdrand. I have the same issue with other vectorDBs.

Close this, I'll check my embedding-ada-002 deployment and open a new issue if needed.
