### ISSUE TITLE
poetry.lock file is not updated

### ISSUE THREAD

**Issue by sharukiln** [langflow-ai/langflow#2780]
### Bug Description

when I run `poetry install` to start langflow locally, I get this error, in the dev branch

pyproject.toml changed significantly since poetry.lock was last generated. Run `poetry lock [--no-update]` to fix the lock file.

### Reproduction

at the root folder:
`python3 -m venv venv`
`poetry install` 

ubuntu 24.04
python 3.12.3

### Expected behavior

pyproject.toml changed significantly since poetry.lock was last generated. Run `poetry lock [--no-update]` to fix the lock file.

### Who can help?

@italojohnny  I have updated the poetry.lock file I would like to make a commit if that's alright.

### Operating System

ubuntu 24.04

### Langflow Version

1.0.9

### Python Version

- [X] 3.12
- [ ] 3.11
- [ ] 3.10

**Comment by sharukiln** [comment]
can I make a Pull Request to the langflow repository?

**Comment by italojohnny** [comment]
Hi, @sharukiln . How are you?

After the release of version 1.0.0, we stopped using the dev branch. We haven't updated all the repository documentation yet, but in any case where you want to contribute, please use the latest version of the main branch.

I believe this will resolve the issue you mentioned with the poetry.lock file. If it doesn't, feel free to create a PR, and we'll review it! :)

**Comment by sharukiln** [comment]
Got it. Thank you. I shall look for other issues to contribute.
I am in love with the design patterns followed here. ❤️ a graph, a node and a vertex and boom you got langflow.
