### ISSUE TITLE
Qdrant Search Error: Error building Component Qdrant: [SSL: WRONG_VERSION_NUMBER] wrong version number

### ISSUE THREAD

**Issue by cassianogr** [langflow-ai/langflow#2788]
### Bug Description

I'm trying use de the RAG template. But i've got this error

`Error building Component Qdrant: [SSL: WRONG_VERSION_NUMBER] wrong version number`

![image](https://github.com/user-attachments/assets/d333b07e-7724-401a-a4f1-3186949c95bc)

Langflow version: 1.0.10
Qdrant version: latest

Thanks!

### Reproduction

1. Install langflow in the 1.0.10 version, locally. Then, run langflow run command.
2. Install qdrant latest (using docker pull) - docker pull qdrant/qdrant. Then, run the docker image. [https://qdrant.tech/documentation/quick-start/](url)
3. Add a new project at LangFlow using the Vector Store RAG Template. See the image above.
4. Use any URL to run URL component.

### Expected behavior

I wish don't have any error to run the whole project.

### Operating System

Windows 11

### Langflow Version

1.0.10

### Python Version

- [X] 3.12
- [ ] 3.11
- [ ] 3.10

**Comment by cassianogr** [comment]
@dosu, I changed the parameter, but I got the same error.

### Changing the parameter
![image](https://github.com/user-attachments/assets/8d9da4dd-bd9b-43a9-9e20-70b920eeb05d)

### Edit
![image](https://github.com/user-attachments/assets/ca9e278a-b94b-4d3d-a6a5-f0c3cb0129b0)

## The error continues
![image](https://github.com/user-attachments/assets/afcb5c30-f58f-4b43-a7b3-0080ee060ebf)

Thanks!

**Comment by cassianogr** [comment]
It's done! It did work.

I had edited this file: ...AppData\Local\Programs\Python\Python312\Lib\site-packages\langflow\components\vectorstores\Qdrant.py

If we use a langflow's GitHub clone, you can edit in your own project

Btw, This problem could be fixed on framework, opening this option (https: True/False) in the visual component (Vector Store).
PR or RoadMap?

**Comment by buddhamangler-cbre** [comment]
> Note: I had to create a own component

Hi I am encountering this same issue of 'variable not found' and sometimes 'illegal request line'.  I have tried explicitly putting the https=False in the two places it would be possibly used and tried your code.  Neither works

Could you explain how you resolved this?  When you say you has to create your own component what do you mean by that?  Did you modify the base code or did you modify the qdrant component code in the editor?

**Comment by n0one42** [comment]
> > Note: I had to create a own component
> 
> Hi I am encountering this same issue of 'variable not found' and sometimes 'illegal request line'. I have tried explicitly putting the https=False in the two places it would be possibly used and tried your code. Neither works
> 
> Could you explain how you resolved this? When you say you has to create your own component what do you mean by that? Did you modify the codebase to edit or add something or did you modify the qdrant component code in the editor?

In your flow, bottom left, --> "New Custom Component" --> Code --> paste my code --> change the name of the Component by clicking into the name of "Custom Component" --> Name it what you want --> Save the component --> delete the component --> paste it again from the Sidebar under Saved. Should work now

**Comment by PrathameshRR** [comment]
@n0one42 Your Custom Node Idea worked!
Thank You

**Comment by jduardo2704** [comment]
In the original component you can make it work by simply leaving the “host” field blank in the advanced options and instead using the “URL” field with a value like ```http://ip_or_host:port``` so that it uses HTTP.

![Image](https://github.com/user-attachments/assets/a056cbe6-5df2-4baa-985e-98edf0bc0b42)

**Comment by hasanakhuy** [comment]
If you are running a local Qdrant instance in Docker without TLS, you can simply update server_kwargs to include _"https": False_ to ensure the client connects over plain HTTP and avoid SSL handshake errors.

![Image](https://github.com/user-attachments/assets/825e1bb1-4947-4152-87f0-acaf275fb6bc)
