### ISSUE TITLE
The Store API Key is not accepting the credential.

### ISSUE THREAD

**Issue by carlosrcoelho** [langflow-ai/langflow#2791]
### Bug Description

When accessing the store and generating a new API key, and then saving it in Store API Key in Langflow, the following error appears:
API key save error
Could not validate credentials

### Reproduction

1 - accessing the store
2 - generating a new API key
3 - save it in Store API Key in Langflow
4 - the following error appears:
API key save error
Could not validate credentials

### Expected behavior

When I enter the newly created API Key from the Store, it should work in the Store API Key field in Langflow.

### Who can help?

@ogabrielluiz  please check.

### Operating System

macOS 14.5

### Langflow Version

1.0.10

### Python Version

- [X] 3.12
- [ ] 3.11
- [ ] 3.10

**Comment by sgt-Script** [comment]
i have the same problem. I am running it in Anaconda, are you?

**Comment by Darwinium** [comment]
Same issue, used Docker to launch langflow

**Comment by RxDBA** [comment]
Same issue. Using Windows, different versions of Python,  used WSL, and even docker image.  Same results.  Can't save API key, can't save profile pic.  Got a segment error

**Comment by mhkafadar** [comment]
Same issue.

**Comment by danilofalcao** [comment]
same here. my solution was to use 1.0.9 meanwhile

**Comment by RxDBA** [comment]
> same here. my solution was to use 1.0.9 meanwhile

How did you install 1.0.9?

**Comment by danilofalcao** [comment]
> > same here. my solution was to use 1.0.9 meanwhile
> 
> How did you install 1.0.9?

pip install langflow==1.0.9

**Comment by RxDBA** [comment]
> > > same here. my solution was to use 1.0.9 meanwhile
> > 
> > 
> > How did you install 1.0.9?
> 
> pip install langflow==1.0.9

AH yes of course.  Thank you!  Yes, 1.0.9 is working great now.  No more errors.

**Comment by sgt-Script** [comment]
i installed that, and it accepts the key, but when i go back to the store, it tells me i need to enter a valid api key.

**Comment by sgt-Script** [comment]
ahh, so i thought it wasnt working but i created a new api key and it started working. Thanks @danilofalcao

**Comment by nizzep** [comment]
## Version 1.0.9 - OK
# Version 1.0.11 - Error 
- [07/21/24 21:36:16] ERROR    2024-07-21 21:36:16 - ERROR    - store  store.py:48 - Failed to decrypt API key:
---
The error message indicates that there is a problem decoding a JWT (JSON Web Token) in your langflow application. Specifically, the "Insufficient Segments" error suggests that the JWT token provided is not in the correct format.

**Comment by carlosrcoelho** [comment]
Hey everyone!

Can you guys test it on version 1.0.12?

Let me know if it worked.

**Comment by RxDBA** [comment]
> Hey everyone!
> 
> Can you guys test it on version 1.0.12?
> 
> Let me know if it worked.

1.0.12 works for me!

**Comment by ckambler** [comment]
> Hey everyone!
> 
> Can you guys test it on version 1.0.12?
> 
> Let me know if it worked.

i am still getting an "API key save error" pop up. any thoughts on other causes? i used the docker compose example you gave, with the exception that i'm using bind mounts for the volumes.

**Comment by mattcam** [comment]
Was having same issue on 1.0.11, updated to 1.0.12 and then after a couple of refreshes it worked.

Initially getting the following message in the console.log chrome

```
Failed to load resource: the server responded with a status of 401 (Unauthorized)
```

**Comment by Cristhianzl** [comment]
Hi,

We've resolved the issue with the store API key. Could you please check if everything is working correctly now?
Thank you!

[https://github.com/langflow-ai/langflow/issues/2458]
