### ISSUE TITLE
OpenAI component doesn't build in Langflow 1.0.10

### ISSUE THREAD

**Issue by vertgo** [langflow-ai/langflow#2797]
### Bug Description

Trying to build a basic prompting hello world example, the OpenAI component fails on build:

```
Error Building Component
Error building Component OpenAI: 1 validation error for ChatOpenAI __root__ Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter. (type=value_error)
```

### Reproduction

1. python -m pip install langflow -U #install langflow
2. python -m langflow run 
3. Click "new project"
4. Choose basic prompting "hello world"
5. click the build button (play arrow) on the openAI component

<img width="869" alt="image" src="https://github.com/user-attachments/assets/18475a1a-6ec6-4437-834c-2ed532217400">

### Expected behavior

It should build

### Who can help?

@ogabrielluiz 

### Operating System

macOS

### Langflow Version

1.0.10

### Python Version

- [X] 3.12
- [ ] 3.11
- [ ] 3.10

**Comment by matthias** [comment]
Same here:

How I solved it:
Line 96: should be removed
`# model_kwargs["seed"] = seed`

Line 102ff: directly add seed as a parameter
```
output = ChatOpenAI(
            max_tokens=max_tokens or None,
            model_kwargs=model_kwargs,
            model=model_name,
            base_url=openai_api_base,
            api_key=api_key,
            temperature=temperature or 0.1,
            seed=seed
        )
```

https://api.python.langchain.com/en/latest/chat_models/langchain_openai.chat_models.base.ChatOpenAI.html

**Comment by vertgo** [comment]
Yeah, so that should be pulled into the main branch. So I'm assuming that was a change in the langchain dependency?

I also am recommending to change "input" and "system message" to MultiLineInput so they can be wired in from other sources

**Comment by ogabrielluiz** [comment]
Hey @vertgo 
How are you? 


This PR fixes this #2779

**Comment by taylorbayouth** [comment]
I'm still having this issue, even after making the changes recommended above.

**Comment by FabioTolentino19** [comment]
> Same here:
> 
> How I solved it: Line 96: should be removed `# model_kwargs["seed"] = seed`
> 
> Line 102ff: directly add seed as a parameter
> 
> ```
> output = ChatOpenAI(
>             max_tokens=max_tokens or None,
>             model_kwargs=model_kwargs,
>             model=model_name,
>             base_url=openai_api_base,
>             api_key=api_key,
>             temperature=temperature or 0.1,
>             seed=seed
>         )
> ```
> 
> https://api.python.langchain.com/en/latest/chat_models/langchain_openai.chat_models.base.ChatOpenAI.html

It´s working the API access for me but, not working because it´s telling that I have to pay... Is not possible to use it with the Free account ?

**Comment by nicoloboschi** [comment]
@taylorbayouth did you refresh the component after the upgrade?

**Comment by taylorbayouth** [comment]
more detail in this thread: https://github.com/langflow-ai/langflow/discussions/2865
