### ISSUE TITLE
Python API code for uploading file is incorrect

### ISSUE THREAD

**Issue by vertgo** [langflow-ai/langflow#2799]
### Bug Description

When getting the API code for a flow, the Python window shows code to execute. It doesn't work if you want to upload a file

There are several problems:
1. the code is templated in get-python-api-code.tsx and it is not correct
it specifies the base_api_url to include /api/v1/run
`BASE_API_URL = "${window.location.protocol}//${window.location.host}/api/v1/run"`
and then it calls upload_file (in load/utils.py) which appends /api/v1/upload so the full path to the upload endpoint is wrong, which results in a 405 error when you try to upload

2. In upload it checks if the response from the server is 200, and throws an error if it isn't. If error 1 is fixed, the server actually responds with code 201, which is fine, but the code still thinks it's an error and throws an exception

if that is corrected to allow code 201:

3.the component is passed in as a string from command line argument, and yet when it assigns the returned file path from the  json response, it assigns it to each letter in the component (so instead of adding a tweaks key of "FILE-ABCD" it does "F", "I", "L", "E" each with its own tweak, and the tweaks for FILE-ABCD is untouched)

 if that is fixed by turning the components into a list before calling upload_file
4. it assigns the returned path from the response to the key "file_path" in the tweaks, but the key is now just "path" so it does not load the correct file still
5.Also if endpoint is "" it weirdly doesn't evaluate to false, so you have to specify the endpoint and the flowId or make the endpoint None. (or just hardcode the flowid in)

### Reproduction

1. Make a flow with a file component
2. hit API button
3. choose python API
4. copy code into a python file 
5. run code with the same virtualEnv activated for the langflow
6. it errors (405)
![image](https://github.com/user-attachments/assets/cac9a0b2-0844-40c3-8f8e-4363f9e27b68)
![image](https://github.com/user-attachments/assets/1fedae9e-97f1-4bf8-9eca-c43575313e1c)

### Expected behavior

It should upload a file and set that file to the path of the component passed in via args

### Who can help?

@anovazzi1 
@ogabrielluiz 

### Operating System

macOS

### Langflow Version

1.0.7, 1.0.9, 1.0.10

### Python Version

- [X] 3.12
- [ ] 3.11
- [ ] 3.10

**Comment by ogabrielluiz** [comment]
Hey @vertgo 

Good catch. I'll fix that ASAP. 

Thank you!

**Comment by vertgo** [comment]
@ogabrielluiz sorry, the upload code is still checking for 200 and not 201, and the upload code still sets the file_path instead of path, (i think, unless that was in a different commit)

**Comment by vertgo** [comment]
@ogabrielluiz made a PR here:
https://github.com/langflow-ai/langflow/pull/2815
