### ISSUE TITLE
Perda do flow

### ISSUE THREAD

**Issue by cwgbittencourt** [langflow-ai/langflow#2819]
Após a atualização, ao arrastar um componente que foi criado na versão anterior (estou com a versão 1.0.10) , recebo a mensagem da imagem
![image](https://github.com/user-attachments/assets/f27d884d-7607-453d-93b5-033b658119b0)
O Flow não abre mais.
Fiz a instalação sugerida abaixo mais o problema persisitiu.
![image](https://github.com/user-attachments/assets/1b21b62b-7b85-4925-b1d2-5610fd0867b2)

**Comment by igorrCarvalho** [comment]
Opa, tudo certo?

Testei seguindo os passos dados, mas não consegui reproduzir o bug. Você ainda está enfrentando esse problema? Se sim, poderia enviar um componente de exemplo e/ou prints dos erros do console do navegador para que possamos investigar mais detalhadamente?

Obrigado!

**Comment by cwgbittencourt** [comment]
Olá Igor, depois que atualizou para versão 1.0.13. Não tenho enfrentado
mais este problema. Obrigado por entrar em contato.

Em seg., 29 de jul. de 2024 às 15:42, Igor Carvalho <
***@***.***> escreveu:
