### ISSUE TITLE
Component for interacting with LangSmith Prompt Hub

### ISSUE THREAD

**Issue by zee229** [langflow-ai/langflow#2822]
### Feature Request

It would be cool to create a component (like a regular prompt), only that uses the ChatPromptTemplate class and interacts with the Prompt Storage Environment - LangSmith Prompt Hub
You could input langchain_api_key, the name of the prompt.
And also that there should be some kind of button to load input fields (it is possible to make another solution, which will be better).

### Motivation

My motivation is that our team has been using LangSmith in production for a long time. And prompt hub has become an integral part of our development, it is incredibly convenient and functional

### Your Contribution

I can help with everything except updating fields in the frontend node template

**Comment by XavierElon** [comment]
Second this request

**Comment by ogabrielluiz** [comment]
Hey @erichare  How are you? 

Could you help @zee229 out on this one?

**Comment by erichare** [comment]
@ogabrielluiz absolutely. This sounds like a great idea.

@zee229 Still getting my feet wet on Langflow components but would be happy to collaborate with you on this. I'll investigate it a bit more closely and get back to you.

**Comment by zee229** [comment]
Okay, sounds nice. Waiting on you @erichare

**Comment by erichare** [comment]
@zee229 I have a very preliminary version. The idea is it uses langchain.hub to pull a provided prompt:

```
        StrInput(
            name="langsmith_prompt",
            display_name="LangSmith Prompt",
            info="The LangSmith prompt to use.",
            value="efriis/my-first-prompt",
        ),
```

```
        # Pull a public prompt from LangChain Hub
        public_prompt = hub.pull(self.langsmith_prompt)
```

We then return a tool_calling_agent which uses the given langsmith prompt. I probably have some of the details wrong, but @zee229 i'll open a PR for you to take a peek later today

**Comment by erichare** [comment]
https://github.com/langflow-ai/langflow/pull/2990

**Comment by zee229** [comment]
> @zee229 I have a very preliminary version. The idea is it uses langchain.hub to pull a provided prompt:
> 
> ```
>         StrInput(
>             name="langsmith_prompt",
>             display_name="LangSmith Prompt",
>             info="The LangSmith prompt to use.",
>             value="efriis/my-first-prompt",
>         ),
> ```
> 
> ```
>         # Pull a public prompt from LangChain Hub
>         public_prompt = hub.pull(self.langsmith_prompt)
> ```
> 
> We then return a tool_calling_agent which uses the given langsmith prompt. I probably have some of the details wrong, but @zee229 i'll open a PR for you to take a peek later today at your convenience

okay, sure

**Comment by zee229** [comment]
I went through your PR and the main problem with the concept of this approach is that in LangSmith PromptHub we can have all kinds of messages in one prompt (system, AI, human, tool, function etc, placeholder etc)

So I would suggest making another prompt component that will return not just text, but a ChatPromptTemplate object at once (this is exactly what the langsmith prompt hub returns). Add some button for pull prompt to update the frontend node template (get all fields for data input), and then already use an agent that will accept ChatPromptTemplate immediately on input to itself.

![CleanShot 2024-07-27 at 7  53 23@2x](https://github.com/user-attachments/assets/1b394d26-1c59-4a97-bb7c-5545151d3325)
![CleanShot 2024-07-27 at 7  53 45@2x](https://github.com/user-attachments/assets/14901f80-da19-4943-9de2-698a9097a632)

**Comment by zee229** [comment]
hi @erichare, why did you close the pull request?

**Comment by erichare** [comment]
@zee229 sorry, it was a mistake, I will reopen it today! I finally made some progress.

**Comment by erichare** [comment]
@zee229 i am going to update the PR shortly. One question for you - it seems to me that if we're dynamically updating the frontend template, which i got working, then we can fill in the parameter values at once for the ChatPromptTemplate, and get a ChatPromptValue object directly from this component. https://python.langchain.com/v0.2/api_reference/core/prompt_values/langchain_core.prompt_values.ChatPromptValue.html

Then downstream components can use the list of messages that have already had their input parameters provided. does that make sense?

**Comment by erichare** [comment]
<img width="1015" alt="Screenshot 2024-08-21 at 11 32 22 AM" src="https://github.com/user-attachments/assets/dbc69970-5568-456f-8af0-42e30e7cfcf9">

**Comment by pward17** [comment]
> @zee229 i am going to update the PR shortly. One question for you - it seems to me that if we're dynamically updating the frontend template, which i got working, then we can fill in the parameter values at once for the ChatPromptTemplate, and get a ChatPromptValue object directly from this component. https://python.langchain.com/v0.2/api_reference/core/prompt_values/langchain_core.prompt_values.ChatPromptValue.html
> 
> Then downstream components can use the list of messages that have already had their input parameters provided. does that make sense?

Yes that makes sense, I see ChatPromptValue has a to_messages and a to_string methods so that should work great.

**Comment by pward17** [comment]
> <img alt="Screenshot 2024-08-21 at 11 32 22 AM" width="1015" src="https://private-user-images.githubusercontent.com/700235/360053793-dbc69970-5568-456f-8af0-42e30e7cfcf9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNzIwOTMsIm5iZiI6MTcyNDI3MTc5MywicGF0aCI6Ii83MDAyMzUvMzYwMDUzNzkzLWRiYzY5OTcwLTU1NjgtNDU2Zi04YWYwLTQyZTMwZTdjZmNmOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMVQyMDIzMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZWU3NDRlNmEzNDFmYWRiMGM4MTU0MzljMmVlZDM1YjZkNTNhMjE2MThjM2IwZWU4ODUyYjRiM2E3NTRmZDUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.l0hL6UNcwxZtwcJ1PsX7pAhqiG5yFAZ6ZYZTM07-NLk">

I see the first component outputs a build config, then does the second component pull and create the ChatPromptValue?

**Comment by erichare** [comment]
Hey @pward17 , so i slightly changed it... see here:

https://github.com/langflow-ai/langflow/pull/2990/files

Basically, the component does this:

```python
        # Get the parameters that
        template = self._fetch_langchain_hub_template()  # TODO: doing this twice
        prompt_value = template.invoke(self._attributes)

        # Now build the ChatPromptTemplate back
        prompt_messages = prompt_value.to_messages()
        prompt_template = ChatPromptTemplate.from_messages(prompt_messages)
```

It fetches the prompt template, then fills in the values that the user provided in the inputs (giving us the ChatPromptValue). It then reconstructs a ChatPromptTemplate, with all parameters filled in. The reason for that was because a lot of the other components take in the template rather than the value. Does this make sense?

**Comment by pward17** [comment]
> Hey @pward17 , so i slightly changed it... see here:
> 
> https://github.com/langflow-ai/langflow/pull/2990/files
> 
> Basically, the component does this:
> 
> ```python
>         # Get the parameters that
>         template = self._fetch_langchain_hub_template()  # TODO: doing this twice
>         prompt_value = template.invoke(self._attributes)
> 
>         # Now build the ChatPromptTemplate back
>         prompt_messages = prompt_value.to_messages()
>         prompt_template = ChatPromptTemplate.from_messages(prompt_messages)
> ```
> 
> It fetches the prompt template, then fills in the values that the user provided in the inputs (giving us the ChatPromptValue). It then reconstructs a ChatPromptTemplate, with all parameters filled in. The reason for that was because a lot of the other components take in the template rather than the value. Does this make sense?

That makes perfect sense, I wasn't familiar with ChatPromptValue. To create a ChatPromptValue you need to supply all the input_variables except partial_variables like the agent_scratchpad can remain not supplied and are dropped from the ChatPromptValue.
