### ISSUE TITLE
Global variables bug

### ISSUE THREAD

**Issue by carlosrcoelho** [langflow-ai/langflow#2827]
### Bug Description

`make backend` does not update the .env when we change its values.

### Reproduction

The bug is might on the database. Some database updates made the old env variables useless.

### Expected behavior

The expected behavior when you update values in the .env file and run make backend should be as follows:

Loading Environment Variables: The updated values in the .env file should be correctly loaded into the environment when the backend service starts.
Database Configuration: The backend should use these updated environment variables to configure the database connection and any other settings that rely on environment variables.
Service Restart: The backend service should restart or reload with the new environment variables, ensuring that the changes are applied.

### Who can help?

@ogabrielluiz 

### Operating System

Ubuntu Linux 22.04

### Langflow Version

1.0.9

### Python Version

- [ ] 3.12
- [ ] 3.11
- [X] 3.10

**Comment by rodgermoore** [comment]
🥇 Ran into this one.

**Comment by sangdth** [comment]
I think I have similar issue. When I upgrade and redeploy my langflow app (for example to the newer version 1.0.12), all the global variables are gone, I have to delete and set them up again.
![Uploading Screenshot 2024-07-23 at 22.09.19.png…]()

**Comment by severfire** [comment]
With new version of langflow I have issue editing fields. i have no idea how to edit those fields using UI. its like there is no edit button nor nothing like clicking it twice works...

**Comment by sangdth** [comment]
@severfire Usually we do not allow editing secret variables items.

**Comment by nicoloboschi** [comment]
Will be fixed by #2971
