### ISSUE TITLE
Persistent Build State Bug

### ISSUE THREAD

**Issue by carlosrcoelho** [langflow-ai/langflow#2829]
### Bug Description

The "building" bug has returned in the latest versions (it even happened during the live session). Occasionally, when you run a component, it stays in the Building state, even if it's a super simple component like ChatInput. If you stop the building process, the state changes to Saving and stays there for a while as well.

### Reproduction

Currently, I'm running directly on the main branch, and this issue is happening quite frequently. If I don't use Langflow for a few minutes, I hit play on something, and it gets stuck in the building state. After the first instance, everything works normally until I leave Langflow minimized or something, and then it happens again.

### Expected behavior

Initiation: When you run a component, the building process should initiate immediately without unnecessary delays.
Progress Feedback: While the component is being built, the system should provide real-time feedback on the progress, potentially with a progress bar or status updates.
Completion: Once the building process is complete, the state should transition from "Building" to "Completed" or "Ready" almost instantaneously.

### Who can help?

@ogabrielluiz 

### Operating System

Ubuntu Linux 22.04

### Langflow Version

1.0.9

### Python Version

- [ ] 3.12
- [ ] 3.11
- [X] 3.10

**Comment by rodgermoore** [comment]
@ogabrielluiz @carlosrcoelho Does anyone know in what version it was (re)introduced? We want to run a backend implementation and we are running into this bug too. Thanks!
