### ISSUE TITLE
Multi-Flow Export Fails

### ISSUE THREAD

**Issue by carlosrcoelho** [langflow-ai/langflow#2834]
### Bug Description

When selecting multiple flows to export, it only exports a single flow.

Also, when exporting flows from the home page, there is no option to select the "Export with my API Keys"

### Reproduction

selecting multiple flows to export

no option to select the "Export with my API Keys"

### Expected behavior

Exporting Multiple Flows
Selection: Users should be able to select multiple flows for export easily, using checkboxes or a multi-select interface.
Export Confirmation: Once multiple flows are selected, the system should clearly indicate that multiple flows will be exported

Exporting with API Keys
Option Availability: When exporting flows from any part of the application (including the home page), there should be an option to include API keys in the export

### Who can help?

@Cristhianzl 

### Operating System

Ubuntu Linux

### Langflow Version

1.0.10

### Python Version

- [ ] 3.12
- [ ] 3.11
- [X] 3.10

**Comment by Cristhianzl** [comment]
@carlosrcoelho,
can you please check if you allowed on your browser to download multiple files from Langflow application?
here's a step by step how to enable this behave on Chrome:
```

To allow multiple file downloads in Chrome, follow these steps:

Method 1: Change Settings in Chrome
Open Chrome Settings:

Click on the three dots (menu) in the top-right corner of Chrome.
Select "Settings".
Privacy and Security:

Scroll down and click on "Privacy and security" in the left sidebar.
Site Settings:

Click on "Site Settings".
Additional Permissions:

Scroll down and click on "Automatic downloads".
Allow Multiple Downloads:

Here you will see the option "Do not allow any site to download multiple files automatically". Change it to "Ask when a site tries to download files automatically after the first file (recommended)".
```

**Comment by carlosrcoelho** [comment]
@Cristhianzl 
It is allowed, and not working, I'm using Vivaldi as a browser.
Switched to Chrome and this works as intended. So it is a bug only on Vivaldi.

Maybe we could zip the flows and avoid this behavior in different browsers?  Not sure how good this approach would be.

**Comment by Cristhianzl** [comment]
fixed
