### ISSUE TITLE
Flow returning to my project

### ISSUE THREAD

**Issue by anovazzi1** [langflow-ai/langflow#2841]
### Bug Description

a flow is added to a folder, after that the flow returns to my projects folder

### Reproduction

add a flow to a folder, it returns by itself to the my projects folder

### Expected behavior

the flow returns to my projects folder

### Who can help?

@Cristhianzl 

### Operating System

windows + wsl

### Langflow Version

1.0.9

### Python Version

None

**Comment by Cristhianzl** [comment]
Hi @anovazzi1,

Could you please check the PR: https://github.com/langflow-ai/langflow/pull/2844

Thanks!
