### ISSUE TITLE
No Vector Search Components in my Langflow

### ISSUE THREAD

**Issue by Ak-github-dev** [langflow-ai/langflow#2851]
### Bug Description

Hi,

I wanted to build a basic RAG in langflow, that required Vector Search Components like Astra DB Search, etc following a tutorial online. But i could not find this list of vector Search components at all in langflow. 

Would like to know if it’s related to version, if yes then what can be done from my end. If some other issue, how can I build my own component and place it in components that can be alternative for this vector search component, or else if someone can see the components in their langflow, It would be great if someone share the .py file of lets say Astra DB Search so that i can add that in my components.

I am new to this, so any inputs will be a great progress for me.

My langflow release version v 1.0.11

Thanks

### Reproduction

1. Langflow run
2. Open http://127.0.0.1:7860/all
3. Open blank project
4. In left panel with list of all components along with Inputs, outputs, etc no vector search components

### Expected behavior

I should be able to see list of all Vector search components
![IMG_0950](https://github.com/user-attachments/assets/829954cb-1a2b-4c6e-92e1-b1bd47490622)

### Who can help?

@anovazzi1 
@Cristhianzl 
@ita

### Operating System

Windows 10

### Langflow Version

1.0.11

### Python Version

3.12

**Comment by Ak-github-dev** [comment]
I downgraded my python version to 3.11.9, but still of no use.

Also, there are obviously other components path like ../components/inputs, .../components/vectorestores, etc but i do not see any path .../components/vector search in my system.

Can you provide .py code for all the vector search components so that i can create a folder in the components folder named vector search and add those in the init, and also do let me know any extra step i need to do to get this done.

**Comment by Ak-github-dev** [comment]
@dosu

Can you give me a .py code for prompt component in langflow as I see there might be some issue I guess with the prompt component in the version i am using.

**Comment by carlosrcoelho** [comment]
HI @Ak-github-dev 

The Vector Search components tab is no longer available.

You can check out the Rag experience in the initial examples of Langflow.

Just go to New Project and pick Vector Store RAG.

<img width="1096" alt="image" src="https://github.com/user-attachments/assets/7f1495a1-85da-447d-8726-4c11d2c449f3">
