### ISSUE TITLE
File content 'utf-8' codec can't decode 

### ISSUE THREAD

**Issue by vuxuancan** [langflow-ai/langflow#2856]
### Bug Description

Dear sir
My document content UTF-8 (vietnamese)
When embeding then 
Error building Component File: Error loading file FAQ.txt: 'utf-8' codec can't decode byte 0x90 in position 5: invalid start byte

Please help me to fix and support utf8 encoding
Thanks
Regard

### Reproduction

<img width="1062" alt="Screenshot 2024-07-21 at 11 09 35" src="https://github.com/user-attachments/assets/e4bd3e9f-dea0-4fce-b739-356119531523">

### Expected behavior

Please support utf8 encoding

### Operating System

Ubuntu 22.04

### Langflow Version

1.0.11

### Python Version

3.11

**Comment by vuxuancan** [comment]
After edit by your comment  then Langflow not start
and error
python -m langflow run
Starting Langflow v1.0.11...
[07/21/24 18:10:43] ERROR    2024-07-21 18:10:43 - ERROR    - __init__ - Worker (pid:1390605) was sent code 139!                                           __init__.py:1706
Starting Langflow v1.0.11...
[07/21/24 18:10:44] ERROR    2024-07-21 18:10:44 - ERROR    - __init__ - Worker (pid:1390622) was sent code 139!                                           __init__.py:1706
Starting Langflow v1.0.11...
                    ERROR    2024-07-21 18:10:44 - ERROR    - __init__ - Worker (pid:1390644) was sent code 139!                                           __init__.py:1706
Starting Langflow v1.0.11...
                    ERROR    2024-07-21 18:10:44 - ERROR    - __init__ - Worker (pid:1390661) was sent code 139!                                           __init__.py:1706
Starting Langflow v1.0.11...
                    ERROR    2024-07-21 18:10:44 - ERROR    - __init__ - Worker (pid:1390678) was sent code 139!                                           __init__.py:1706
Starting Langflow v1.0.11...
[07/21/24 18:10:45] ERROR    2024-07-21 18:10:45 - ERROR    - __init__ - Worker (pid:1390695) was sent code 139!                                           __init__.py:1706
Starting Langflow v1.0.11...
                    ERROR    2024-07-21 18:10:45 - ERROR    - __init__ - Worker (pid:1390712) was sent code 139!                                           __init__.py:1706
Starting Langflow v1.0.11...
free(): invalid pointer
                    ERROR    2024-07-21 18:10:45 - ERROR    - __init__ - Worker (pid:1390729) was sent code 139!                                           __init__.py:1706
Starting Langflow v1.0.11...
                    ERROR    2024-07-21 18:10:45 - ERROR    - __init__ - Worker (pid:1390746) was sent code 139!                                           __init__.py:1706
Starting Langflow v1.0.11...

**Comment by jackiemoo** [comment]
Hi,
Can you upload a sample of your file?

**Comment by jackiemoo** [comment]
Hi @vuxuancan ,
I deployed on Docker (based on Debian 12 (Bookworm), langflow v1.0.11) and tested using the text sample you provided.
I couldn't reproduce the issue you mentioned. 
Here is my temporary demonstration environment: http://103.97.177.31:8001/.
You can have a try.

**Comment by vuxuancan** [comment]
:(( I can't run langflow yet even though I have updated the latest langflow (Langflow v1.0.12)
after run command python -m pip install langflow --pre -U --force-reinstall
Can you help me to fix the problem ?
OS ubuntu 22.04
python 3.11.9

python -m langflow run
Starting Langflow v1.0.12...
[07/23/24 20:15:04] ERROR    2024-07-23 20:15:04 - ERROR    - __init__ - Worker (pid:1499779) was sent code 139!                                           __init__.py:1706
Starting Langflow v1.0.12...
free(): invalid pointer
                    ERROR    2024-07-23 20:15:04 - ERROR    - __init__ - Worker (pid:1499797) was sent code 139!                                           __init__.py:1706
Starting Langflow v1.0.12...
                    ERROR    2024-07-23 20:15:04 - ERROR    - __init__ - Worker (pid:1499814) was sent code 139!                                           __init__.py:1706
Starting Langflow v1.0.12...
                    ERROR    2024-07-23 20:15:04 - ERROR    - __init__ - Worker (pid:1499831) was sent code 139!                                           __init__.py:1706
Starting Langflow v1.0.12...
[07/23/24 20:15:05] ERROR    2024-07-23 20:15:05 - ERROR    - __init__ - Worker (pid:1499848) was sent code 139!                                           __init__.py:1706
Starting Langflow v1.0.12...
                    ERROR    2024-07-23 20:15:05 - ERROR    - __init__ - Worker (pid:1499865) was sent code 139!                                           __init__.py:1706
Starting Langflow v1.0.12...
                    ERROR    2024-07-23 20:15:05 - ERROR    - __init__ - Worker (pid:1499882) was sent code 139!                                           __init__.py:1706
Starting Langflow v1.0.12...
                    ERROR    2024-07-23 20:15:05 - ERROR    - __init__ - Worker (pid:1499899) was sent code 139!                                           __init__.py:1706
Starting Langflow v1.0.12...
                    ERROR    2024-07-23 20:15:05 - ERROR    - __init__ - Worker (pid:1499916) was sent code 139!                                           __init__.py:1706
Starting Langflow v1.0.12...
[07/23/24 20:15:06] ERROR    2024-07-23 20:15:06 - ERROR    - __init__ - Worker (pid:1499933) was sent code 139!                                           __init__.py:1706
Starting Langflow v1.0.12...
                    ERROR    2024-07-23 20:15:06 - ERROR    - __init__ - Worker (pid:1499950) was sent code 139!                                           __init__.py:1706
Starting Langflow v1.0.12...
free(): invalid pointer
                    ERROR    2024-07-23 20:15:06 - ERROR    - __init__ - Worker (pid:1499967) was sent code 139!                                           __init__.py:1706
Starting Langflow v1.0.12...
free(): invalid pointer
                    ERROR    2024-07-23 20:15:06 - ERROR    - __init__ - Worker (pid:1499984) was sent code 139!                                           __init__.py:1706
Starting Langflow v1.0.12...
[07/23/24 20:15:07] ERROR    2024-07-23 20:15:07 - ERROR    - __init__ - Worker (pid:1500001) was sent code 139!                                           __init__.py:1706
Starting Langflow v1.0.12...
                    ERROR    2024-07-23 20:15:07 - ERROR    - __init__ - Worker (pid:1500018) was sent code 139!                                           __init__.py:1706
Starting Langflow v1.0.12...
free(): invalid pointer
                    ERROR    2024-07-23 20:15:07 - ERROR    - __init__ - Worker (pid:1500035) was sent code 139!                                           __init__.py:1706
Starting Langflow v1.0.12...
                    ERROR    2024-07-23 20:15:07 - ERROR    - __init__ - Worker (pid:1500052) was sent code 139!                                           __init__.py:1706
Starting Langflow v1.0.12...
[07/23/24 20:15:08] ERROR    2024-07-23 20:15:08 - ERROR    - __init__ - Worker (pid:1500069) was sent code 139!                                           __init__.py:1706
Starting Langflow v1.0.12...
                    ERROR    2024-07-23 20:15:08 - ERROR    - __init__ - Worker (pid:1500086) was sent code 139!                                           __init__.py:1706
Starting Langflow v1.0.12...
^C                    ERROR    2024-07-23 20:15:08 - ERROR    - __init__ - Worker (pid:1500103) was sent code 139!                                           __init__.py:17

**Comment by carlosrcoelho** [comment]
Hi @vuxuancan 

Do you need any assistance with this case? If not, please let us know if this issue can be closed.

**Comment by vuxuancan** [comment]
Ok this utf-8 issue can be closed
Thank you so much
