### ISSUE TITLE
Float input can't be None

### ISSUE THREAD

**Issue by nicoloboschi** [langflow-ai/langflow#2862]
### Bug Description

All int inputs can be none and fallback to default behaviours of the component. For floats, it should be the same; however currently it's always required

### Reproduction

Any float input

### Expected behavior

To leave it empty and let the component computes a default

### Operating System

any

### Langflow Version

any

### Python Version

3.12

**Comment by Cristhianzl** [comment]
hi @nicoloboschi 

It was a frontend treatment that was different on the FloatComponent and the IntComponent.

 #3953
