### ISSUE TITLE
Crew component giving error message

### ISSUE THREAD

**Issue by Aerdor1998** [langflow-ai/langflow#2873]
Every component bellow 1.0 version is not running correctly

**Comment by carlosrcoelho** [comment]
Hi @Aerdor1998 

Could you explain the problem in more detail?

**Comment by AdrianoDBA** [comment]
I dont know!!!!Error in login password Invite my iPhoneEm 23 de jul. de 2024, à(s) 17:40, Carlos Coelho ***@***.***> escreveu:﻿
Hi @Aerdor1998
Could you explain the problem in more detail?

**Comment by juboyy** [comment]
![evv](https://github.com/user-attachments/assets/dd86d2b0-3ad8-41bf-a59e-0c9ba32e5ea2)
 
for me its like this

**Comment by carlosrcoelho** [comment]
@juboyy 

This is related to LLM, something seems not right there.

**Comment by carlosrcoelho** [comment]
@AdrianoDBA 

Could you share a screenshot of the problem?

**Comment by carlosrcoelho** [comment]
@Aerdor1998 
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.

**Comment by santhu932** [comment]
<img width="1497" alt="Screenshot 2024-08-22 at 6 50 51 PM" src="https://github.com/user-attachments/assets/3bd724ed-bdce-4b05-b1fd-3f966bc89d05">

I'm facing a issue at Crew Sequential Component, when trying to build a simple multi-agent assistant workflow

<img width="1276" alt="Screenshot 2024-08-22 at 6 52 49 PM" src="https://github.com/user-attachments/assets/0cc8e0f4-e53d-4c24-a160-de8454a23ef4">
