### ISSUE TITLE
Flow returns cached output from playground

### ISSUE THREAD

**Issue by sangdth** [langflow-ai/langflow#2886]
### Bug Description

After making the flow, and use Playground to test, the API calling will return the last respond from Playground.

### Reproduction

1. Create the flow.
2. Run test in playground.
3. Use the API link
4. Still see the old output.

<img width="1535" alt="Screenshot 2024-07-23 at 13 24 54" src="https://github.com/user-attachments/assets/653f407e-3ded-49b1-8746-58ee2437b906">

<img width="1111" alt="Screenshot 2024-07-23 at 13 25 13" src="https://github.com/user-attachments/assets/f72c3ddf-d10e-492e-8b34-45535deb1007">

[Extract links (1).json](https://github.com/user-attachments/files/16347352/Extract.links.1.json)

### Expected behavior

Expect to see the correct output.

### Operating System

Ubuntu

### Langflow Version

1.0.11

### Python Version

None

**Comment by anovazzi1** [comment]
Hi @sangdth,

Could you please share your flow? If you are using any components with caching mechanisms (such as a LLM), that might be causing the issue. If not, it could be a bug. Your flow will help us address this asap.

Thank you!

**Comment by sangdth** [comment]
Hi @anovazzi1, I attached the json in the issue, you can scroll up a bit and see. Or I can re-upload here: 
[Extract links (1).json](https://github.com/user-attachments/files/16371398/Extract.links.1.json)

Is there a way to disable the cache? Our system use it internally so we do not have high number of requests.

**Comment by anovazzi1** [comment]
I apologize for the delay. I have identified the root cause of the issue. It appears that the problem does not lie with the cache but with our API code. The input type you are using is a Text Input, not a chat Input. Therefore, the value for `"input_type": "chat"` is incorrect and should be `"input_type": "text"`. I will fix this in our generated code. Thank you for bringing this to our attention.

**Comment by sangdth** [comment]
Thanks @anovazzi1, I specified the `"input_type": "text"` and it works well now!
