### ISSUE TITLE
Video not showing up on docs 

### ISSUE THREAD

**Issue by nicoloboschi** [langflow-ai/langflow#2893]
### Bug Description

In the docs videos are not showing up
https://docs.langflow.org/workspace-api

### Reproduction

https://docs.langflow.org/workspace-api

### Expected behavior

To see the video

### Operating System

none

### Langflow Version

none

### Python Version

3.12

**Comment by lucaseduoli** [comment]
https://github.com/sillsdev/docu-notion/issues/110

This is an issue with the docu-notion library. Temporary fix is to upload all of the videos to YouTube and embed them.
