### ISSUE TITLE
Incorrect import does not raise an error even though it returns status 400

### ISSUE THREAD

**Issue by ogabrielluiz** [langflow-ai/langflow#2895]
### Bug Description

Whenever there's an error in the code, the backend raises an HTTPException with status 400. This error gets to the client but the api interceptor is not raising the error which causes the `.catch` to not be called. 

### Reproduction

Drop a CustomComponent on screen, add the line `import pytorch` at the top of the component's code which should raise an error. Nothing happens when you click on the `Check & Save` button.

### Expected behavior

An error message explaining the error should appear.

### Who can help?

@anovazzi1 , @Cristhianzl 

### Operating System

MacOS

### Langflow Version

1.0.12

### Python Version

3.12

**Comment by Cristhianzl** [comment]
on it
