### ISSUE TITLE
Terminal Stuck on "Starting Langflow v1.0.12..." for Over 15 Minutes

### ISSUE THREAD

**Issue by c0pper** [langflow-ai/langflow#2912]
### Bug Description

Issue Description:
After following the installation instructions provided in the documentation and running the python -m langflow run command, my terminal remains stuck on the message "Starting Langflow v1.0.12..." without any further progress. It has been in this state for at least 15 minutes.

Steps to Reproduce:

Expected Behavior:
Langflow should start successfully, or provide meaningful output/error messages if something goes wrong.

Actual Behavior:
The terminal remains stuck on:

Starting Langflow v1.0.12...
![image](https://github.com/user-attachments/assets/28724a4a-341b-4d5e-827a-676db4ced301)

Questions:

    Is there a way to check what is going on behind the scenes since there's no error message being displayed?
    Are there any logs or debug modes that can be enabled to diagnose the issue further? the langflow.log file is empty

System Information:

    OS: Windows 11
    Python Version: 3.11.0
    Langflow Version: v1.0.12

### Reproduction

    Ensure Python >=3.10 is installed.
    Install Langflow using python -m pip install langflow -U.

Run Langflow with:
    python -m langflow run

### Expected behavior

Langflow should start successfully, or provide meaningful output/error messages if something goes wrong.

### Who can help?

- @ogabrielluiz
- @nicoloboschi
- @zzzming
- @jordanrfrazier
- @mfortman11
- @NadirJ

### Operating System

Windows 11

### Langflow Version

1.0.12

### Python Version

3.11

**Comment by lucaseduoli** [comment]
Hello! I'm closing the issue since you got that figured out, but if that happens again, could you please start Langflow with this command?
`python -m langflow run --log-level DEBUG`
With that, we can see which part of the initialization gets stuck.
Thanks!
