### ISSUE TITLE
Unable to import library

### ISSUE THREAD

**Issue by silwaltz** [langflow-ai/langflow#2916]
### Bug Description

```
from ibm_watsonx_ai.metanames import GenTextParamsMetaNames as GenParams
from ibm_watsonx_ai.foundation_models.utils.enums import DecodingMethods
from langchain_ibm import WatsonxLLM, ChatWatsonx
```
None of the above import would work. Clicking "check and save" with no respond.

```
import ibm_watsonx_ai
import langchain_ibm
```
The above import could pass "check and save" but if I use any class or method in it will not work again.

Is this a bug?

### Reproduction

Try copy below import statement in any of the component could could reproduce the issue.
```
from ibm_watsonx_ai.metanames import GenTextParamsMetaNames as GenParams
from ibm_watsonx_ai.foundation_models.utils.enums import DecodingMethods
from langchain_ibm import WatsonxLLM, ChatWatsonx
```

### Expected behavior

I need to import those library in order to make a custom component using IBM watsonx

### Operating System

macOS 14.5

### Langflow Version

1.0.12

### Python Version

3.11

**Comment by ogabrielluiz** [comment]
Hey @silwaltz  
How are you? 
Thanks for the report.
This issue is the same as #2895 which should be in our next release.
Closing this one. 
Take care.

**Comment by silwaltz** [comment]
Hi @ogabrielluiz 
I am good, thanks for the quick reply.
I have a follow up question about importing library.
I see you posted on #2895 saying import pytouch should raise an error.
Did you mean if your env haven't install pytouch it will raise an error or you mean even you have pytouch installed it still should raise an error?
