### ISSUE TITLE
Freeze isn't working in version 1.0.12.

### ISSUE THREAD

**Issue by carlosrcoelho** [langflow-ai/langflow#2918]
### Bug Description

When activating the freeze, components that were supposed to be stopped are still running.
In this case, the file loader and the text split run every time I hit play on the Chroma DB.

### Reproduction

Use the freeze feature in a component
The component still run

### Expected behavior

The component that is selected to be frozen, should not be running.

### Who can help?

@ano

### Operating System

Ubuntu Linux 22.04

### Langflow Version

1.0.12

### Python Version

3.10

**Comment by anovazzi1** [comment]
just tried on latest main version and it seems to work properly
