### ISSUE TITLE
Just install v1.0.12 and cannot open any workflows, receiving "Unexpected Error" 

### ISSUE THREAD

**Issue by melienherrera** [langflow-ai/langflow#2927]
Just updated my Langflow locally from 1.0.7 to 1.0.12. Install seemed to go fine, but when I try to click into any of my existing flows / create a new flow, I receive the following error:

<img width="793" alt="Screenshot 2024-07-24 at 11 21 19 AM" src="https://github.com/user-attachments/assets/ca73a8f8-ad38-465a-87f8-8f5ae03c3555">

Anything that I could be missing here?

**Comment by melienherrera** [comment]
Tried all of the above, and still receiving the same error

**Comment by lucaseduoli** [comment]
Hello! Could you please press F12 on your browser and send me a screenshot of the Console errors?

**Comment by melienherrera** [comment]
@lucaseduoli HI there. As I was about to obtain the screenshot for you, it looks like my flows are now loading 😅 Thanks for your help and apologies for the noise I might have caused!

**Comment by lucaseduoli** [comment]
No problem! I'm just going to mark this as closed then, but if it ever happens again, just reopen it and I'll have a look!
