### ISSUE TITLE
Iteration component

### ISSUE THREAD

**Issue by SVyusti** [langflow-ai/langflow#2946]
### Feature Request

A new feature to run entire workflows in iteration should be supported. This would enable batch processing of documents.

### Motivation

workflows which read files from a directory, need to be sent individually instead of running the workflow in a  loop.
https://docs.dify.ai/guides/workflow/node/iteration

**Comment by granton-song** [comment]
+1

**Comment by sohamchatterjee50** [comment]
Is this still in process ?

**Comment by dingvarson** [comment]
+1
