### ISSUE TITLE
Python code editor: support multiple switch case options

### ISSUE THREAD

**Issue by dsldsl** [langflow-ai/langflow#2949]
### Bug Description

This is valid python but wont save in the component python editor because of multuple cases grouped together:

```
    def switch_test(self):
        match self.input_text:
            case "CASE1":
            case "":
            case None:
                pass
            case "CASE2":
                pass
            case "CASE3":
                pass
```

### Reproduction

try to code with multiple case optoins!

### Expected behavior

it works

### Operating System

mac os

### Langflow Version

1.0.12

### Python Version

None

**Comment by lucaseduoli** [comment]
Hello!
Is this feature supported in Python 3.10? If it is not, maybe that is the reason why it does not work in the editor.
Thanks!

**Comment by italojohnny** [comment]
Hello, @dsldsl .
Your code has an error, see:

<img width="951" alt="Screenshot 2024-07-29 at 14 37 18" src="https://github.com/user-attachments/assets/f8be1e3c-9707-4226-8063-16ae7f60a838">

Please try to fix it, and if the error persists, reopen the issue.
