### ISSUE TITLE
Can't import Spacy in custom components

### ISSUE THREAD

**Issue by c0pper** [langflow-ai/langflow#2952]
### Bug Description

Hi, I was wondering if it's possible at all to import other python libraries such as spacy to build custom components that use them, for example to get the nlp analysis of a text. 

So far I have tried the following:
```
# from langflow.field_typing import Data
from langflow.custom import Component
from langflow.io import MessageTextInput, Output
from langflow.schema import Data
import spacy

print(spacy.__version__)
nlp = spacy.load("en_core_web_sm")


class CustomComponent(Component):
    display_name = "Custom Component"
    description = "Use as a template to create your own component."
    documentation: str = "http://docs.langflow.org/components/custom"
    icon = "custom_components"
    name = "CustomComponent"

    inputs = [
        MessageTextInput(name="input_value", display_name="Input Value", value="Hello, World!"),
    ]

    outputs = [
        Output(display_name="Output", name="output", method="build_output"),
    ]

    def build_output(self) -> Data:
        doc = nlp(self.input_value)
        tokens = []
        
        for token in doc:
            tokens.append(f"({token.text}, {token.pos_})")
        data = Data(value="; ".join(tokens))
        self.status = data
        return data

```

but on execution I'm getting 
```
Error Building Component

    Error building Component Custom Component: name 'nlp' is not defined
```

### Reproduction

Create custom component
Copy the code I've tried

### Expected behavior

Spacy loads and the nlp analysis is provided in output

### Operating System

Windows 11

### Langflow Version

1.0.12

### Python Version

3.11

**Comment by c0pper** [comment]
That code doesn't work, it won't event let me check and save the component. I just click the button to save and it does nothing.

**Comment by c0pper** [comment]
@dosu Where am i supposed to find my custom components from your script in the gui? I only see the normal custom component

**Comment by carlosrcoelho** [comment]
Hey!

You can try to create your custom component with the help of: https://chatgpt.com/g/g-rCodu5oaW-langflow-component-helper

**Comment by Dimesio** [comment]
Why was this closed? this is not fixed. I'm using the docker version of langflow, and cannot import the spacy library with a custom module. I accessed the /app/.venv environment and ran the install in the container, but it still isn't available to the custom component. what is the fix here?
