### ISSUE TITLE
401 Error and Missing Flows After Server Restart

### ISSUE THREAD

**Issue by carlosrcoelho** [langflow-ai/langflow#2968]
### Bug Description

401 error after restarting the server and navigating back to Langflow. Upon refreshing the home page, none of the flows were available. The flows only became visible after logging out and logging in again.

### Reproduction

1. Restart the server.
2. Navigate back to Langflow.
3. Encounter error 401.
4. Refresh the home page.
5. Observe that none of the flows are available.
6. Log out and log in again.
7. Observe that the flows are now visible.

### Expected behavior

After restarting the server and navigating back to Langflow, the user should not encounter a 401 error, and all flows should be available without needing to log out and log in again.

### Operating System

Ubuntu Linux 22.04

### Langflow Version

main

### Python Version

3.10

### Flow File

https://jam.dev/c/1e57645d-4f3e-4503-937b-a35749a43832

**Comment by Cristhianzl** [comment]
on it
