### ISSUE TITLE
Features change when langflow is run from the Env Variables

### ISSUE THREAD

**Issue by edwinjosechittilappilly** [langflow-ai/langflow#2969]
### Bug Description

Open AI models available in default mode is not available when langflow was loaded with .env file with admin login

example. earlier gtp4o mini was available but when i loaded langflow with env variable file it is missing

### Reproduction

1. run langlfow in basic mode: load open ai component: you can see gpt4o mini available.
2. langflow run --env-file /Users/edwin.jose/Documents/GitHub/amelia/langflowcreds/.env
3. login with username and cred
4.load OpenAI component : gpt4o mini is missing.

### Expected behavior

Both run should have same models.
When I check source code too its the same model names being loaded.
Suggestion: I would manually edit to get gpt4o mini.

### Operating System

Mac OS

### Langflow Version

1.0.12

### Python Version

3.11

### Screenshot

<img width="380" alt="Screenshot 2024-07-25 at 8 05 30 PM" src="https://github.com/user-attachments/assets/f2d62c6c-8ba7-4227-bd33-05232fd752af">
<img width="321" alt="Screenshot 2024-07-25 at 8 05 10 PM" src="https://github.com/user-attachments/assets/e1f95bc8-ac82-4ff8-8138-ddd9af15d924">

**Comment by carlosrcoelho** [comment]
@edwinjosechittilappilly 

Hey, could you try using the new version and let me know if the issue is still there? Thanks!

**Comment by edwinjosechittilappilly** [comment]
Sure

**Comment by carlosrcoelho** [comment]
@edwinjosechittilappilly 
Do you need any assistance with this case? If not, please let us know if this issue can be closed.

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
