### ISSUE TITLE
Messages Stored With Same Timestamp

### ISSUE THREAD

**Issue by carlosrcoelho** [langflow-ai/langflow#2982]
### Bug Description

Every message is stored with the same timestamp. Note the actual time when I will send some of them.

### Reproduction

get the memory starter example
interact with chat a couple of times
go to default session and check the timestamp

### Expected behavior

The timestamp should match the time the user is interacting.

### Who can help?

@anovazzi1 

### Operating System

Mac

### Langflow Version

1.0.12

### Python Version

3.12

### Screenshot

<img width="1349" alt="image" src="https://github.com/user-attachments/assets/7e1cbdd5-c567-4126-823d-740779e10cfe">

### Flow File

[Memory Chatbot (1).json](https://github.com/user-attachments/files/16392403/Memory.Chatbot.1.json)

**Comment by sameersheikh22** [comment]
same issue in the latest version 1.3.4. Can anyone please help me out? 

<img width="330" alt="Image" src="https://github.com/user-attachments/assets/6dbf6e39-5cbf-47ed-a4e6-40a2f78ab15f" />

<img width="1381" alt="Image" src="https://github.com/user-attachments/assets/5df4ebd4-754b-41ac-96fe-abbf97b50c09" />

<img width="1066" alt="Image" src="https://github.com/user-attachments/assets/957d2c27-f7b7-4788-b81a-08ccd61a3fa6" />

**Comment by sameersheikh22** [comment]
## I modified two files to fix this issue:
1. Added timestamp_to_iso_format to langflow/schema/validators.py
Added a new function to properly convert various timestamp formats to ISO 8601 format with millisecond precision:
```
def timestamp_to_iso_format(timestamp: datetime | str) -> str:
    """Convert timestamp to ISO 8601 format for database compatibility.
    
    Returns in format: YYYY-MM-DDTHH:MM:SS.mmm+00:00
    """
    if isinstance(timestamp, str):
        # Try to parse the string to a datetime
        for fmt in [
            "%Y-%m-%d %H:%M:%S.%f %Z",
            "%Y-%m-%d %H:%M:%S %Z",
            "%Y-%m-%d %H:%M:%S.%f",
            "%Y-%m-%d %H:%M:%S",
        ]:
            try:
                dt = datetime.strptime(timestamp.strip(), fmt)
                if dt.tzinfo is None:
                    dt = dt.replace(tzinfo=timezone.utc)
                return dt.isoformat()
            except ValueError:
                continue
        
        # If it's already in ISO format, return as is
        try:
            datetime.fromisoformat(timestamp)
            return timestamp
        except ValueError:
            pass
            
        msg = f"Invalid timestamp format: {timestamp}"
        raise ValueError(msg)
    
    # Handle datetime object
    if timestamp.tzinfo is None:
        timestamp = timestamp.replace(tzinfo=timezone.utc)
    return timestamp.isoformat()

# Added validator
timestamp_to_iso_format_validator = BeforeValidator(timestamp_to_iso_format)
```


2. Updated Message class in  langflow/schema/message.py
Modified the Message class to use the ISO format for timestamps and to handle both string and datetime inputs:

Changed the timestamp field definition:
```
pythontimestamp: str = Field(
    default_factory=lambda: timestamp_to_iso_format(datetime.now(timezone.utc))
)

Updated the timestamp serializer:
python@field_serializer("timestamp")
def serialize_timestamp(self, value):
    # Return ISO format for database compatibility
    return timestamp_to_iso_format(value)
```

Updated the create method to handle datetime objects:
python@classmethod
```
async def create(cls, **kwargs):
    """If files are present, create the message in a separate thread as is_image_file is blocking."""
    # Convert timestamp to ISO format if it's a datetime object
    if "timestamp" in kwargs and isinstance(kwargs["timestamp"], datetime):
        kwargs["timestamp"] = timestamp_to_iso_format(kwargs["timestamp"])
    
    if "files" in kwargs:
        return await asyncio.to_thread(cls, **kwargs)
    return cls(**kwargs)
```

Also updated MessageResponse class to use the new format.

**Comment by sameersheikh22** [comment]
![Image](https://github.com/user-attachments/assets/6093345a-000d-435b-a615-37cff3ea7c90)

**Comment by sameersheikh22** [comment]
@ogabrielluiz
