### ISSUE TITLE
Unable to add global variables in application deployed on GCP

### ISSUE THREAD

**Issue by emilwojtaszek** [langflow-ai/langflow#2988]
### Bug Description

I'd like to define global variable, but getting 500 error on endpoint 
POST /api/v1/variables/ 

not sure how to debug it more

### Reproduction

1. Go to Settings
2. Go to Global Variables
3. Add new variable 
4. Try to add new variable 

Same issue when trying to define Store API Key, but I guess it use variables under the hood 

### Expected behavior

I should be able to define global variable 

### Operating System

Using langflowai/langflow docker image 

### Langflow Version

v1.0.12

### Python Version

None

### Screenshot

![CleanShot 2024-07-26 at 16 46 46@2x](https://github.com/user-attachments/assets/ec9e6b7b-4a25-4ac9-878e-db7bd5892397)

![CleanShot 2024-07-26 at 16 38 58@2x](https://github.com/user-attachments/assets/01951dc6-e5f4-4c5a-9c71-bb291007edcc)

**Comment by rodgermoore** [comment]
I have the same problem on Azure Container Instances. While creating a Global Variable I get the error:
```
Error creating variable
Fernet key must be 32 url-safe base64-encoded bytes.
```

**Comment by severfire** [comment]
I am getting same error.

Additionally, getting error in JS console. May be related?

```
`DialogContent` requires a `DialogTitle` for the component to be accessible for screen reader users.

If you want to hide the `DialogTitle`, you can wrap it with our VisuallyHidden component.

For more information, see https://radix-ui.com/primitives/docs/components/dialog [index-BMduUo-e.js:3231:165](http://127.0.0.1:7860/assets/index-BMduUo-e.js)
    TitleWarning http://127.0.0.1:7860/assets/index-BMduUo-e.js:3231
    Qj http://127.0.0.1:7860/assets/index-BMduUo-e.js:984
    Hk http://127.0.0.1:7860/assets/index-BMduUo-e.js:984
    Wk http://127.0.0.1:7860/assets/index-BMduUo-e.js:984
    Pk http://127.0.0.1:7860/assets/index-BMduUo-e.js:984
    Ek http://127.0.0.1:7860/assets/index-BMduUo-e.js:984
    jg http://127.0.0.1:7860/assets/index-BMduUo-e.js:982
    Wk http://127.0.0.1:7860/assets/index-BMduUo-e.js:984
    Pk http://127.0.0.1:7860/assets/index-BMduUo-e.js:984
    Gk http://127.0.0.1:7860/assets/index-BMduUo-e.js:984
    Ct http://127.0.0.1:7860/assets/index-BMduUo-e.js:969
    xt http://127.0.0.1:7860/assets/index-BMduUo-e.js:969

```

**Comment by italojohnny** [comment]
Hi, @emilwojtaszek . How are you?

I set up an instance on GCP with the latest Langflow image, and creating global variables worked for me. See the image:

<img width="1725" alt="Screenshot 2024-07-30 at 13 49 58" src="https://github.com/user-attachments/assets/a52f8a37-b26d-40ff-8837-e59a708dc48c">

Could you try again using the latest available image? I'll close the issue, but if the error persists for you, please create a new issue or reopen this one.

**Comment by emilwojtaszek** [comment]
it looks like it works! sorry for radio silence and thank you for your support
