### ISSUE TITLE
Component-Order-Issue

### ISSUE THREAD

**Issue by carlosrcoelho** [langflow-ai/langflow#2994]
### Bug Description

Flow works perfectly without the Store Message component, but doesn't work when adding it back. The component itself works fine in other flows.
I think it's ordering... rearranged and everything works
The original flow also works if called played from the Chat Output component. When sending messages in the Chat nothing comes out.

### Reproduction

Take out the Store Message from the flow.
Insert it again
chat doesn`t work.
The original flow also works if called played from Chat Output component. When sending messages in the Chat nothing comes out

### Expected behavior

The flow works fine no matter if you add or remove the component, or where you put it.

### Who can help?

@ogabrielluiz 

### Operating System

macOS 14.5

### Langflow Version

1.0.12

### Python Version

3.12

### Screenshot

![image (7)](https://github.com/user-attachments/assets/0a04cee1-b744-4b2b-885b-a8da60a8bc72)
![image (8)](https://github.com/user-attachments/assets/7cc791d6-1563-49d6-a317-35d16b0ccd03)

### Flow File
[Yes or No (3).json](https://github.com/user-attachments/files/16395837/Yes.or.No.3.json)

**Comment by ogabrielluiz** [comment]
This is not a bug. 

Messages in the playground come from ChatInput and ChatOutput, not StoreMessage component.
