### ISSUE TITLE
Problem with Global Variables Setting Page

### ISSUE THREAD

**Issue by severfire** [langflow-ai/langflow#3004]
### Bug Description

When  entering http://127.0.0.1:7860/settings/global-variables

I am getting error in JS console.
```
`DialogContent` requires a `DialogTitle` for the component to be accessible for screen reader users.

If you want to hide the `DialogTitle`, you can wrap it with our VisuallyHidden component.

For more information, see https://radix-ui.com/primitives/docs/components/dialog [index-BMduUo-e.js:3231:165](http://127.0.0.1:7860/assets/index-BMduUo-e.js)
    TitleWarning http://127.0.0.1:7860/assets/index-BMduUo-e.js:3231
    Qj http://127.0.0.1:7860/assets/index-BMduUo-e.js:984
    Hk http://127.0.0.1:7860/assets/index-BMduUo-e.js:984
    Wk http://127.0.0.1:7860/assets/index-BMduUo-e.js:984
    Pk http://127.0.0.1:7860/assets/index-BMduUo-e.js:984
    Ek http://127.0.0.1:7860/assets/index-BMduUo-e.js:984
    jg http://127.0.0.1:7860/assets/index-BMduUo-e.js:982
    Wk http://127.0.0.1:7860/assets/index-BMduUo-e.js:984
    Pk http://127.0.0.1:7860/assets/index-BMduUo-e.js:984
    Gk http://127.0.0.1:7860/assets/index-BMduUo-e.js:984
    Ct http://127.0.0.1:7860/assets/index-BMduUo-e.js:969
    xt http://127.0.0.1:7860/assets/index-BMduUo-e.js:969
```

I am also getting error when adding again earlier deleted variable:
"Sorry, we found an unexpected error!
Please report errors with detailed tracebacks on the [GitHub Issues](https://github.com/langflow-ai/langflow/issues) page.
Thank you!"

So as asked, I am kindly reporting it.

Also, There is no feature to edit fields.

### Reproduction

JS error:
1. Just enter the page

Saving Error:
1. saving new variable
2. deleting this new variable
3. adding it again with same name

### Expected behavior

It should work without error

### Operating System

Windows 11 pro

### Langflow Version

1.13

### Python Version

None

**Comment by rodgermoore** [comment]
Duplicate? https://github.com/langflow-ai/langflow/issues/2988#issue-2432400546

**Comment by severfire** [comment]
@rodgermoore - Just tested. Yes, it is. I will close it and add info to other bug report regarding js error.
