### ISSUE TITLE
Weird messages in cmd while running crewai agents in Langflow

### ISSUE THREAD

**Issue by Swephoenix** [langflow-ai/langflow#3005]
### Bug Description

Weird messages in cmd while running crewai agents and the sequential task/crew functions in Langflow? It also takes forever to get an output. What is causing this? 
![image](https://github.com/user-attachments/assets/59c6c11f-572b-4e23-8ef9-38364ab0dbf0)

![image](https://github.com/user-attachments/assets/d1d222d5-5558-4e9a-b3cd-b2d1c8e69ae1)

### Reproduction

![image](https://github.com/user-attachments/assets/f554308a-bd21-4c3a-bea7-b5c3d05a63c3)

### Expected behavior

I would expect to get an output to my question what is 2+2 and then a 3 should be added, but instead it takes forever.

### Operating System

Windows

### Langflow Version

Latest

### Python Version

3.12

### Flow File

[Error.json](https://github.com/user-attachments/files/16401364/Error.json)
![image](https://github.com/user-attachments/assets/59c6c11f-572b-4e23-8ef9-38364ab0dbf0)
![image](https://github.com/user-attachments/assets/d1d222d5-5558-4e9a-b3cd-b2d1c8e69ae1)
![image](https://github.com/user-attachments/assets/f554308a-bd21-4c3a-bea7-b5c3d05a63c3)

**Comment by Swephoenix** [comment]
Thanks. Should this code go in the Sequential task function or Sequential Crew or in the agents themselves?
![image](https://github.com/user-attachments/assets/433cad09-d0a7-4d0e-a0a0-57e05976f5bb)

**Comment by carlosrcoelho** [comment]
@Swephoenix 

Could you test it on the new version 1.0.16? Let me know if anything comes up.

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
