### ISSUE TITLE
frontend npm install gives warnings

### ISSUE THREAD

**Issue by severfire** [langflow-ai/langflow#3008]
### Bug Description

Hi,

Slowly boarding into this project... while installing dependencies I got information regarding '2 high severity vulnerabilities'

I wonder if its something that should be taken care of?

```
(venv) PS C:\Users\arek\Desktop\LLM\langflow\src\frontend> npm install
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
(...)
added 1159 packages, and audited 1161 packages in 48s

294 packages are looking for funding
  run `npm fund` for details

2 high severity vulnerabilities
```

### Reproduction

\src\frontend> npm install

### Expected behavior

no warnings

### Operating System

Windows 11 pro

### Langflow Version

1.0.13

### Python Version

None

**Comment by anovazzi1** [comment]
Hi @severfire,

I don't believe this warning is related to langflow core; it seems to be associated with shadcn-ui. We will monitor their repository, and once the issue is resolved, we will update it as soon as possible.
[track the issue here](https://github.com/shadcn-ui/ui/issues/3978)
