### ISSUE TITLE
Langflow API slow compared to Playground.

### ISSUE THREAD

**Issue by Frenz86** [langflow-ai/langflow#3012]
### Bug Description

I'm running langflow-1.0.12 as a docker container, the playground seems much faster than using the webhook. I thought Langsmith was the cause of the problem but, although the playground without Langsmith is much faster, via API the problem still persist.

### Reproduction

Try to use any flow by playground and then by webjook.

### Expected behavior

The inference time is 3 time slow on webhook

### Operating System

Ubuntu 22.04

### Langflow Version

1.0.12

### Python Version

3.12

**Comment by carlosrcoelho** [comment]
@Frenz86 

Do you need any assistance with this case? If not, please let us know if this issue can be closed.

Try the new version 1.0.15

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
