### ISSUE TITLE
Add alert of old components when an error pop up

### ISSUE THREAD

**Issue by carlosrcoelho** [langflow-ai/langflow#3027]
### Title

Add alert of old components when an error pop up

### Type

Improvement

### Description

When an error occurs in the system, an alert will now be displayed indicating if any components involved in the error are outdated. This will help users to quickly identify and update old components that may be causing issues, improving overall system stability and performance.

### Use Case

As a user, I want to receive alerts about outdated components when an error occurs so that I can update them promptly and prevent future errors.

### Implementation Plan

Identify the components involved in the error.
Check the version of each component against the latest available version.
If any components are outdated, trigger an alert to inform the user.
Display the alert with information on which components are outdated and instructions on how to update them.

**Comment by anovazzi1** [comment]
#3051
