### ISSUE TITLE
Delete messages on Playground chat isn't working

### ISSUE THREAD

**Issue by Cristhianzl** [langflow-ai/langflow#3036]
### Bug Description

When deleting messages from the chat, the action is only reflected on the UI and does not persist in the backend. Here’s a quick way to see this issue:

### Reproduction

1. Add a random flow.

2. Run the flow.

3. Interact with the chat in the playground.

4. Click the erase button to delete some messages.

5. Send new messages in the chat.

### Expected behavior

You'll notice that the last messages you sent before deleting will reappear.

### Who can help?

@Cristhianzl 

### Operating System

MacOS

### Langflow Version

1.0.13

### Python Version

None

**Comment by nicoloboschi** [comment]
@Cristhianzl isn't this supposed to work in this way? I thought to actually delete the history you need to open the memory (on the left) and select the messages you want to be deleted

**Comment by Cristhianzl** [comment]
Hi @nicoloboschi,

Sorry, I have already fixed this error and forgot to link the fix here and close the issue.
Thank you!!
