### ISSUE TITLE
Selection of selected components not much visible

### ISSUE THREAD

**Issue by severfire** [langflow-ai/langflow#3038]
### Feature Request

On dark mode selection is not much visible against dark background. 
Same goes on light mode. 

I suggest changing .border-ring on dark and light mode to:

.border-ring {
    border-color: hsl(78.81deg 100% 46.27%) !important;
    border-width: 2px !important;
}

Edit: 
Seems this class is also for selecting, not only grouping
I need to find other class responsible for grouping or it should be added

### Motivation

better UI

### Your Contribution

I can edit the code

**Comment by severfire** [comment]
Note: 
var(--status-green) may be much better color for both dark and light mode. 
Looks nice as well as simple selection without grouping.

**Comment by anovazzi1** [comment]
#3556
