### ISSUE TITLE
Error: URL File Component Fails with Multiple Comma-Separated Links

### ISSUE THREAD

**Issue by carlosrcoelho** [langflow-ai/langflow#3041]
### Bug Description

URL file component give me an error when i run it with two or more links with commas

### Reproduction

Get file component
add two separate links by comma

### Expected behavior

According to the component's message, it should work.

Component message: Enter one or more URLs, separated by commas.

### Operating System

macOS 14.5

### Langflow Version

1.0.13

### Python Version

3.12

### Screenshot

<img width="634" alt="image" src="https://github.com/user-attachments/assets/8e34836e-a1d1-4cc6-be52-000b1be39e56">

**Comment by lucaseduoli** [comment]
Hey, 

The component description is actually wrong by now. The correct way of inserting more than one URL is by pressing the "+" button on the right of the field, and inserting each URL inside each field.

Sorry for that, the description is going to be changed as soon as possible.

Thanks!
