### ISSUE TITLE
Text input jumps to the end of the text after writing one letter

### ISSUE THREAD

**Issue by ogabrielluiz** [langflow-ai/langflow#3058]
### Bug Description

Whenever you are writing text in a field and you select a place in the middle of the text to edit, the first letter writes where you clicked then the cursos jumps to the end of the text.

### Reproduction

Open a component like the ToolCallingAgent, click on the input, write something, click somewhere in the middle of the text and try writing or editing something.

### Expected behavior

Text should be editable from wherever the cursor is.

### Who can help?

@anovazzi1
@lucaseduoli
@cri

### Operating System

MacOS

### Langflow Version

1.0.14

### Python Version

3.12

### Screenshot

![CleanShot 2024-07-29 at 22 37 14@2x](https://github.com/user-attachments/assets/5090cc0f-1710-4d00-b19a-f15fa0df83fe)

**Comment by severfire** [comment]
yes, i noticed it as well, very frustrating
