### ISSUE TITLE
Langsmith tracing latencies don't add up

### ISSUE THREAD

**Issue by nicoloboschi** [langflow-ai/langflow#3064]
### Bug Description

If you run a flow enabling langsmith tracing, the total time of a run is mostly correct. However each component shows a very short time (milliseconds).
![Screenshot 2024-07-30 at 11 39 50](https://github.com/user-attachments/assets/713c5709-0450-4a63-8c1a-e6c7493f0137)

After checking the code, I've realized that for each component we only trace the build output part, without considering the init of the class which normally is the operation that takes longer (.e.g init http clients and connect to servers)

### Reproduction

Run any flow with langsmith enabled.

### Expected behavior

All the components sub-times should add up to the total time

### Operating System

macos

### Langflow Version

1.0.13

### Python Version

None

**Comment by ogabrielluiz** [comment]
Maybe the trace time is set only once when the component starts.
