### ISSUE TITLE
All user Langflow data is lost with (most) of upgrades

### ISSUE THREAD

**Issue by V1999B** [langflow-ai/langflow#3066]
### Bug Description

Running pip install --upgrade langflow 
when it actually upgrades to the next release, like to 1.013 in this case, all the previous data is lost - all flows, components, global variables. however had several upgrades, when data remained. 

that is quite inconvenient obviously, as any keys are lost, any flows in work are lost etc. 

First question - is there a way to restore the info that was lost in such an upgrade? 

Second, proposal to solve this issue for the next upgrades.

### Reproduction

Run pip install --upgrade langflow  
- like for the latest upgrade to 1.013 

### Expected behavior

All global variables, user flows and components shall remain intact in every upgrade. 

### Operating System

MacOS

### Langflow Version

1.012-013

### Python Version

3.11

**Comment by nicoloboschi** [comment]
Hey, Langflow stores the database on the langflow installation directory. 

e.g. 
/Users/xx/.pyenv/versions/3.11.7/envs/langflow/lib/python3.11/site-packages/langflow/langflow.db

is it possible that you changed the py env or wiped it out or reinstalled from scratch?

I'd suggest to set the db path to a known place next time

export LANGFLOW_DATABASE_URL=sqlite:////Users/<myhome>/langflow.db

On docker, if you don't mount the volume you will lose all the files there

an alternative is to use a local PG instance
