### ISSUE TITLE
AttributeError: module 'langflow.base.models.openai_constants' has no attribute 'MODEL_NAMES'

### ISSUE THREAD

**Issue by telebash** [langflow-ai/langflow#3075]
### Bug Description

AttributeError: module 'langflow.base.models.openai_constants' has no attribute 'MODEL_NAMES'

### Reproduction

Run Basic Hello flow on local Langflow
<img width="1512" alt="Снимок экрана 2024-07-30 в 20 28 27" src="https://github.com/user-attachments/assets/f8b13d63-678a-4ad2-b3bb-6fa1c257bc3c">

### Expected behavior

Solution

### Operating System

MacOS

### Langflow Version

1.0.13

### Python Version

3.10

**Comment by anovazzi1** [comment]
Hey @telebash, did you try update the component and/or update the langflow?

**Comment by telebash** [comment]
@anovazzi1 
Hey, Yes, I've tried installing different versions. There are always some mistakes

**Comment by anovazzi1** [comment]
I'm sorry to hear that. Unfortunately, we have no perfect version, but this issue you addressed should be fixed on the v1.0.14

**Comment by carlosrcoelho** [comment]
@telebash 

I just tried on 1.0.14, and it worked. When the component has a warning mark ⚠️, click on it to update before running the flow.

Let me know if anything comes up.

**Comment by telebash** [comment]
@anovazzi1 @carlosrcoelho Thanks!
