### ISSUE TITLE
Ollama issue

### ISSUE THREAD

**Issue by jasinskp** [langflow-ai/langflow#3079]
### Bug Description

When try to run Ollama model getting an "Error building Component Ollama: Unsupported message type: <class 'dict'>"

### Reproduction

![image](https://github.com/user-attachments/assets/205cc184-baa3-4528-a8f5-eba7e4ff084b)

### Expected behavior

Want to run Ollama component

### Operating System

Windows 11

### Langflow Version

1.13

### Python Version

None

**Comment by ogabrielluiz** [comment]
Hey @jasinskp 

How are you? 

This issue is related to #3022 which should be fixed in 1.0.14. 
If you are using a previous version, downgrading langchain-core to 0.2.23 fixes this (e.g `python -m pip install langchain-core==0.2.23`)

**Comment by jasinskp** [comment]
Hi,

Thank you for the info.
Do you know when 1.0.14 will be ready?

Have a good day
Pawel
