### ISSUE TITLE
Fine tuning 

### ISSUE THREAD

**Issue by gamercoder153** [langflow-ai/langflow#3080]
How do I use the finetuning from csv feature mentioned on the website https://www.langflow.org/

**Comment by gamercoder153** [comment]
@dosu it giving out this error when I build it : 

Error Building Component
Error building Component CSVAgent: This agent relies on access to a python repl tool which can execute arbitrary code. This can be dangerous and requires a specially sandboxed environment to be safely used. Please read the security notice in the doc-string of this function. You must o

**Comment by gamercoder153** [comment]
@dosu can u assign this issue to anyone?

**Comment by carlosrcoelho** [comment]
@gamercoder153 

A user made this custom component a while back, but it was discontinued after updates and new versions.
