### ISSUE TITLE
Implement LangfuseTracer

### ISSUE THREAD

**Issue by ogabrielluiz** [langflow-ai/langflow#3081]
### Feature Request

We should clean up langfuse related code and add a LangfuseTracer implementation. 

We need to check their data structure to make sure Langflow data is displayed correctly. 

### Motivation

Langfuse is a popular tracing and observability tool.

### Your Contribution

Steps:
1. Implement LangfuseTracer based off of BaseTracer (similar to LangsmithTracer or LangwatchTracer)
2. Make sure all data types are displayed as best as possible
3. Make sure imports are not called outside the tracer class

**Comment by idnotbe** [comment]
Please~! I need it.

**Comment by Elksninsh** [comment]
I'm really looking forward to this feature too!

**Comment by pionix-ai** [comment]
I need it too!

**Comment by icherepanov** [comment]
Great feature! Please make it.
