### ISSUE TITLE
"you cannot pass a tweak with the same name" & send message via api

### ISSUE THREAD

**Issue by lpcoutinho** [langflow-ai/langflow#3098]
### Bug Description

I updated a model available in the store for chat with memory. In the playground it worked perfectly.

However, when I tried to integrate it with an API using the post request available on the platform, this return appeared:

{
"detail": "If you pass an input_value to the chat input, you cannot pass a tweak with the same name."
}

I would like to know how I can configure a call via http request to my flow and that in this call the memory remains so that when making a new request the flow will maintain the history of the conversation.

![new](https://github.com/user-attachments/assets/1e90a0d8-6fc8-49b6-9888-24baf0ffb6f3)

### Reproduction

curl -X POST \
    "https://langflow.atendimagico.com.br/api/v1/run/teste?stream=false" \
    -H 'Content-Type: application/json'\
  -H 'x-api-key: <your api key>'\
    -d '{"input_value": "message",
    "output_type": "chat",
    "input_type": "chat",
    "tweaks": {
  "GroqModel-FeKKx": {
    "groq_api_base": "https://api.groq.com",
    "groq_api_key": "gsk_XHBRhbmBkKJmRddadY2VnnWGadXzbJWIIavUO7dsR4bwhvsdvsMsvsdsEj",
    "input_value": "",
    "max_tokens": null,
    "model_name": "llama-3.1-70b-versatile",
    "n": null,
    "stream": false,
    "system_message": "",
    "temperature": 0.1
  },
  "Prompt-NyzDE": {
    "template": "{contexto}\n\nUser: {mensagem_usuario}\nAI:",
    "contexto": "",
    "mensagem_usuario": ""
  },
  "ChatInput-vOmw6": {
    "files": "",
    "input_value": "oi",
    "sender": "User",
    "sender_name": "User",
    "session_id": "MySessionID",
    "should_store_message": false
  },
  "Memory-UBrUr": {
    "n_messages": 8,
    "order": "Ascending",
    "sender": "Machine and User",
    "sender_name": "",
    "session_id": "MySessionID",
    "template": "{sender_name}: {text}"
  },
  "TextOutput-9Uh9a": {
    "input_value": ""
  },
  "ChatOutput-rIcoQ": {
    "data_template": "{text}",
    "input_value": "",
    "sender": "Machine",
    "sender_name": "AI",
    "session_id": "MySessionID",
    "should_store_message": false
  }
}}'
    

### Expected behavior

I hope to be able to interact with the flow via external APIs

### Operating System

Ubuntu Linux 20.04

### Langflow Version

1.0.14

### Python Version

None

### Screenshot

![new](https://github.com/user-attachments/assets/8425d748-c425-44b8-bdaf-a33adb666c1b)
![new2](https://github.com/user-attachments/assets/3ee17c55-2c0d-4740-8c4d-8c783f82134a)

**Comment by anovazzi1** [comment]
Hello @lpcoutinho,

Thanks for the feedback! The issue arises because you're attempting to modify the same value in two different ways simultaneously. You can't use the tweak object to update the value inside the chat input while also passing an input value in the API. Both methods essentially do the same thing, but using them together creates a conflict about which one the application should prioritize. To resolve this, you should choose either the tweak object or the input value, but not both. It's up to you :)
