### ISSUE TITLE
Embedding isse

### ISSUE THREAD

**Issue by jasinskp** [langflow-ai/langflow#3099]
### Bug Description

Trying to use Ollama embeddings with ChromaDB, Unfortunately whole Langflow is going down on the end
![image](https://github.com/user-attachments/assets/b75adbff-ff58-4511-a621-aa4f9adc7aa9)
![image](https://github.com/user-attachments/assets/8e635b80-7ead-4c87-a810-229821ef0280)

### Reproduction

Use Ollama embeddings
Use ChromaDB

### Expected behavior

![image](https://github.com/user-attachments/assets/ef7eafe4-c372-429a-bfba-bc5a11cda2b3)

### Operating System

Windows 11

### Langflow Version

1.0.14

### Python Version

None

**Comment by jasinskp** [comment]
I check all of that an unfortunately problem persists 
![image](https://github.com/user-attachments/assets/4cbe8759-d718-4664-a9c1-d1d336601fd9)
![image](https://github.com/user-attachments/assets/fe3628eb-cf5d-4110-8134-9d166c58bbc8)
![image](https://github.com/user-attachments/assets/7efa59af-caf3-4ead-a34f-5a82cdeb7e3b)

**Comment by jasinskp** [comment]
@dosu
I've added try/except with print method (for embedding and ChromaDB
components) but unfortunately nothing was catch. Only, what additionally
noticed is screen below.
More over for some of "txt" files I've been able to successfully prepare
embeddings and store them into ChromaDB, but for other "Langflow" is going
down at all.

 [image: image.png]


czw., 1 sie 2024 o 15:26 dosubot[bot] ***@***.***> napisał(a):

**Comment by jasinskp** [comment]
Finally I found the issue, somehow model itself was the problem. I used
llama3.1:8b and as I wrote before for few "txt" files it works, but for
other "langflow" went down.
now i changed model to "mxbai-embed-large:latest" and it works.

PS. Crazy thing and I'm not sure where is the real problem, model itself,
Ollama or Langflow, but finally after few days of crashing Langflow and
loosing hope now it works. Currently I need to find better model to embed
Polish lang. Do you have any ideas why this wasn't work?

Have a good weekend,
Pawel

pt., 2 sie 2024 o 17:08 dosubot[bot] ***@***.***> napisał(a):

**Comment by jasinskp** [comment]
@dosu

Could you explain me what is the difference between models you listed and
llama3.1 in case of  embedding in Langflow. I thought when the model is
supported by Ollama it will work as well with Langflow

**Comment by carlosrcoelho** [comment]
@jasinskp 
Looks like you had some connection issue that caused an error, judging by the screenshot.

I tested it on version 1.0.14 and it worked fine. Are you still having this problem?

<img width="862" alt="image" src="https://github.com/user-attachments/assets/4f429f42-3b8f-40ac-85b7-8deb16fa824e">

**Comment by saikolasani** [comment]
@jasinskp Just wanted to check in again to see if you are still experiencing the issue.

**Comment by jasinskp** [comment]
Using model as llama3.1 - yes.

**Comment by jordanrfrazier** [comment]
> I used llama3.1:8b and as I wrote before for few "txt" files it works, but for other "langflow" went down.

Hi @jasinskp Can you please clarify this statement? Using llama3.1:8b, the embeddings worked for _some_ files, but for others it caused langflow to crash? If so, can you please provide an example of a text file that caused the crash?

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you
