### ISSUE TITLE
The height of the output window when a build fails is too small

### ISSUE THREAD

**Issue by YeKelvin** [langflow-ai/langflow#3100]
### Bug Description

<img width="1421" alt="image" src="https://github.com/user-attachments/assets/2bbaefd7-e2db-4204-a3cf-fe3f8a92b992">

### Reproduction

<img width="892" alt="image" src="https://github.com/user-attachments/assets/4e24e6e9-bd55-45ff-8210-ae9fa83bc07e">

### Expected behavior

Adaptive according to height

### Operating System

macos

### Langflow Version

1.0.14

### Python Version

3.12

**Comment by YeKelvin** [comment]
<img width="1469" alt="image" src="https://github.com/user-attachments/assets/8f06cac2-49f6-4f35-bc1a-6d1d62c4f4b9">

**Comment by anovazzi1** [comment]
Hello @YeKelvin, thanks for the feedback! We've already fixed this issue on the main branch, and the fix will be available in the next release.
