### ISSUE TITLE
Deploy from blueprints on railway and render finish with status failed.

### ISSUE THREAD

**Issue by SapphireX** [langflow-ai/langflow#3106]
### Bug Description

it is not possible do deploy on render or railway service.
Deploy end with error : network healthcheck - healthcheck failure.
Please investigate

### Reproduction

1.Go to : https://github.com/langflow-ai/langflow
2.click "deploy to render"
3.fill blueprint name and click deploy on render/
4.See status of deployment.

### Expected behavior

App is deployend on render and can be accessed via URL address od render.

### Operating System

Reder subsystem

### Langflow Version

v1.0.14

### Python Version

None

### Screenshot

![image](https://github.com/user-attachments/assets/cbb8765a-d507-467d-b9c5-434b4e5f3d8a)

**Comment by nicoloboschi** [comment]
@SapphireX can you share the logs? 
Which docker image is getting pulled in with latest ? (please check in the logs)

What are the machine resources ? I'd recommend to run with 1G of memory

**Comment by SapphireX** [comment]
sure. Here are the logs:
![image](https://github.com/user-attachments/assets/2857de2e-ce71-4eb8-b416-4134b04388c6)
[logs.txt](https://github.com/user-attachments/files/16442820/logs.txt)

**Comment by SapphireX** [comment]
okey so the issue was with memory (512 instead 1GB) . After changin for faster machine deploy was succesful

**Comment by TzurV** [comment]
Is there an updated [render.yaml](https://github.com/langflow-ai/langflow/blob/main/render.yaml) that can be used as a blueprint?
