### ISSUE TITLE
Session Loss on Tab Switch in Langflow

### ISSUE THREAD

**Issue by carlosrcoelho** [langflow-ai/langflow#3130]
### Bug Description

I'm still losing sessions from time to time in langflow.
This is happening constantly when I switch tabs;

### Reproduction

https://jam.dev/c/03826c9f-dde7-4c2d-a9b3-cefac0c396df

Using the default values for the token auth

### Expected behavior

Keep in the session,

### Who can help?

@Cristhianzl

### Operating System

Ubuntu Linux 22.04

### Langflow Version

1.0.14

### Python Version

3.10

**Comment by Cristhianzl** [comment]
Hi,

Please check if the error occurs after this PR: #3076
