### ISSUE TITLE
python API

### ISSUE THREAD

**Issue by zhengqianhe0** [langflow-ai/langflow#3140]
### Bug Description

I encounter errors when calling flow through Python API
{
"detail": "Invalid or missing API key"
}
What does this API key refer to? Is it the Langflow API

### Reproduction

I encounter errors when calling flow through Python API
{
"detail": "Invalid or missing API key"
}
What does this API key refer to? Is it the Langflow API

### Expected behavior

I encounter errors when calling flow through Python API
{
"detail": "Invalid or missing API key"
}
What does this API key refer to? Is it the Langflow API

### Operating System

windows 10

### Langflow Version

1.0.9

### Python Version

None

**Comment by anovazzi1** [comment]
same problem reported in #3143 and #3172
