### ISSUE TITLE
python API

### ISSUE THREAD

**Issue by zhengqianhe0** [langflow-ai/langflow#3143]
### Bug Description

I have already executed it locally
python -m langflow api-key
Obtained the key.
Then I saved the code in tweaks mode as a Python file and executed the command as follows
python run_flow.py "hello" --api_key "my key"
Still reporting errors
{
"detail": "Invalid or missing API key"
}
Is it because the local flow cannot be called by code?
Look at the variables in my code:

BASE_API_URL = "http://localhost:3000/api/v1/run"
FLOW_ID = "f76fe3"

### Reproduction

import argparse
import json
from argparse import RawTextHelpFormatter
import requests
from typing import Optional
import warnings
try:
    from langflow.load import upload_file
except ImportError:
    warnings.warn("Langflow provides a function to help you upload files to the flow. Please install langflow to use it.")
    upload_file = None

BASE_API_URL = "http://localhost:3000/api/v1/run"
FLOW_ID = "f76f"
ENDPOINT = "" # You can set a specific endpoint name in the flow settings

# You can tweak the flow by adding a tweaks dictionary
# e.g {"OpenAI-XXXXX": {"model_name": "gpt-4"}}
TWEAKS = {
  "Prompt-3cx6O": {
    "template": "speak。\n{input}",
    "input": ""
  },
  "ChatOutput-KitBa": {
    "data_template": "{text}",
    "input_value": "",
    "sender": "Machine",
    "sender_name": "AI",
    "session_id": ""
  },
  "ChatInput-6DUob": {
    "files": "",
    "input_value": "1",
    "sender": "User",
    "sender_name": "User",
    "session_id": ""
  },
  "TongyiQwenChatModel-x5n47": {
    "input_value": "",
    "model": "qwen-turbo",
    "stream": False,
    "system_message": "",
    "temperature": 0.95,
    "tongyi_api_key": "sk-",
    "top_p": 0.8
  }
}

def run_flow(message: str,
  endpoint: str,
  output_type: str = "chat",
  input_type: str = "chat",
  tweaks: Optional[dict] = None,
  api_key: Optional[str] = None) -> dict:
    """
    Run a flow with a given message and optional tweaks.

    :param message: The message to send to the flow
    :param endpoint: The ID or the endpoint name of the flow
    :param tweaks: Optional tweaks to customize the flow
    :return: The JSON response from the flow
    """
    api_url = f"{BASE_API_URL}/{endpoint}"

    payload = {
        "input_value": message,
        "output_type": output_type,
        "input_type": input_type,
    }
    headers = None
    if tweaks:
        payload["tweaks"] = tweaks
    if api_key:
        headers = {"x-api-key": api_key}
    response = requests.post(api_url, json=payload, headers=headers)
    return response.json()

def main():
    parser = argparse.ArgumentParser(description="""Run a flow with a given message and optional tweaks.
Run it like: python <your file>.py "your message here" --endpoint "your_endpoint" --tweaks '{"key": "value"}'""",
        formatter_class=RawTextHelpFormatter)
    parser.add_argument("message", type=str, help="The message to send to the flow")
    parser.add_argument("--endpoint", type=str, default=ENDPOINT or FLOW_ID, help="The ID or the endpoint name of the flow")
    parser.add_argument("--tweaks", type=str, help="JSON string representing the tweaks to customize the flow", default=json.dumps(TWEAKS))
    parser.add_argument("--api_key", type=str, help="API key for authentication", default=None)
    parser.add_argument("--output_type", type=str, default="chat", help="The output type")
    parser.add_argument("--input_type", type=str, default="chat", help="The input type")
    parser.add_argument("--upload_file", type=str, help="Path to the file to upload", default=None)
    parser.add_argument("--components", type=str, help="Components to upload the file to", default=None)

    args = parser.parse_args()
    try:
      tweaks = json.loads(args.tweaks)
    except json.JSONDecodeError:
      raise ValueError("Invalid tweaks JSON string")

    if args.upload_file:
        if not upload_file:
            raise ImportError("Langflow is not installed. Please install it to use the upload_file function.")
        elif not args.components:
            raise ValueError("You need to provide the components to upload the file to.")
        tweaks = upload_file(file_path=args.upload_file, host=BASE_API_URL, flow_id=ENDPOINT, components=args.components, tweaks=tweaks)

    response = run_flow(
        message=args.message,
        endpoint=args.endpoint,
        output_type=args.output_type,
        input_type=args.input_type,
        tweaks=tweaks,
        api_key=args.api_key
    )

    print(json.dumps(response, indent=2))

if __name__ == "__main__":
    main()

'''
python run_flow.py "" --api_key ""

'''

### Expected behavior

{
  "detail": "Invalid or missing API key"
}

### Operating System

windows 10

### Langflow Version

1.0.7

### Python Version

None

**Comment by anovazzi1** [comment]
maybe your issue is related to #3172
