### ISSUE TITLE
Can i use OpenSerach custom component as vector store in langflow 1.0 ,  it not show in document.

### ISSUE THREAD

**Issue by weily2** [langflow-ai/langflow#3154]
### Feature Request

Can i use OpenSerach custom component as vector store in langflow 1.0 ,  it not show in document.

### Motivation

Can i use OpenSerach custom component as vector store in langflow 1.0 ,  it not show in document.

**Comment by anovazzi1** [comment]
Hello @weily2, absolutely! While we don't have it as a default component, you can build it yourself using [custom components](https://docs.langflow.org/components-custom-components).

**Comment by weily2** [comment]
@anovazzi1 Thanks
