### ISSUE TITLE
/api/v1/custom_component/update 400 bad request

### ISSUE THREAD

**Issue by artemus717** [langflow-ai/langflow#3155]
### Bug Description

{
    "detail": "1 validation error for MessageInput\nvalue\n  Value error, Invalid value type <class 'dict'> [type=value_error, input_value={'text_key': 'text', 'dat...: '2024-07-31 05:41:44'}, input_type=dict]\n    For further information visit https://errors.pydantic.dev/2.8/v/value_error"
}

DropdownInput(
            name="model_name",
            display_name="Model Name",
            value="llama3",
            info="Refer to https://ollama.ai/library for more models.",
            refresh_button=True,
        ),

Is it becacuse ollama.ai changed to ollama.com ? So this plugin can not get module name correctly ?

### Reproduction

In Ollama Plugin, click module name refesh

### Expected behavior

show module names

### Operating System

docker image 1.0.14

### Langflow Version

1.0.14

### Python Version

None

**Comment by artemus717** [comment]
And if I added a custom LLM in Ollama, then Ollama plugin get LLM names from ollama.com, so I will not able to choose what I added in Ollama ?

**Comment by saikolasani** [comment]
Hi @artemus717  Thank you so much for reporting the issue. Just to make sure I understand exactly what is happening. Is the error occurring when you initially load or after running it previously? Furthermore, if you are able to send a screen recording of what causes the issue, that would help greatly. Looking forward to your response.

**Comment by saikolasani** [comment]
@artemus717 We have updated the component with the correct URL. This will be reflected in the next release. Please let us know if you are still dealing with the issues.

**Comment by artemus717** [comment]
> @artemus717 We have updated the component with the correct URL. This will be reflected in the next release. Please let us know if you are still dealing with the issues.

fixed in 1.0.15 ?

**Comment by saikolasani** [comment]
@artemus717 If you could provide a screenshot of how the component is running/being refreshed, and what the url is set to, that will allow us to dig deeper into the issue. For your initial error, its likely that the input value is incompatible, If you could provide a screenshot of the input, we can dig deeper.

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you
