### ISSUE TITLE
does not work split 

### ISSUE THREAD

**Issue by juanjoza10** [langflow-ai/langflow#3187]
does not work

**Comment by carlosrcoelho** [comment]
@juanjoza10 
Could you explain the problem in more detail, step by step? If possible, can you share a screenshot of your flow? Thanks!

**Comment by carlosrcoelho** [comment]
@juanjoza10 
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
