### ISSUE TITLE
Escape closes code editing window without asking and without saving changes

### ISSUE THREAD

**Issue by tsdaemon** [langflow-ai/langflow#3188]
### Bug Description

When I open Edit Code modal, it can be closed by accidentally pressing Esc, and there is no prompt to save changes or anything to prevent loosing changes. And I use Esc in IDEs to close intellisense suggestions, so its super inconvenient that it closes the modal.

### Reproduction

1. Start a flow
2. Create custom component
3. Start editing code, make some changes
4. Press Esc

### Expected behavior

Changes are either preserved, or Esc does not close the modal, or there is a prompt asking if I want to save changes before closing.

### Operating System

Ubuntu

### Langflow Version

1.0.14

### Python Version

None

**Comment by carlosrcoelho** [comment]
Fixed:
https://github.com/langflow-ai/langflow/pull/3232
