### ISSUE TITLE
Trying to import a flow or component exported directly from folders view do not work

### ISSUE THREAD

**Issue by appoks** [langflow-ai/langflow#3189]
### Bug Description

When you try to download the flow directly from the 'folders' / 'projects' visualization, the flow can no be imported. The same flow when exported from inside the flow works as expected. See attached video for clarification.

I noticed this bug while migrating the flows and components from my local pip install to a dockerized install of langflow.

#iadevs

### Reproduction

1. Open your langflow application
2. Choose any flow or component to export. Select it (do not open, just select it)
3. Click on download/export.
4. Try to load the exported result in the langflow. I tried in a brand new and fresh instance using docker but it'll crash even if you try to load on the same instance.

obs: don't know which python version i'm using, but this is the 'latest' langflow docker image available;

### Expected behavior

The flow should be imported as expected. I would also expect that when i click the export, the option to export with the global variables/api keys are presented, so I can mass export my flows and components to another langflow instance.

### Operating System

Manjaro, using Docker official image.

### Langflow Version

1.0.14

### Python Version

None

### Screenshot

https://github.com/user-attachments/assets/cfe90b6a-c2c5-4240-9c5a-51c41087e444

**Comment by anovazzi1** [comment]
Hey @appoks, thanks for the feedback! The issue is that our UI currently suggests that this upload is for flows instead of folders. We'll work on improving the UI as soon as possible.
if you want to upload flows and components just drag and drop ;)

**Comment by lucaseduoli** [comment]
Hello! We will fix it as soon as possible. The issue is with the export function. Thanks for the feedback!
