### ISSUE TITLE
When `self.status` is defined, the output is not presented on component 'inspect output'

### ISSUE THREAD

**Issue by appoks** [langflow-ai/langflow#3192]
### Bug Description

**NOTE:** I'm not sure if this one is a bug or I don't know how the langflow should behave, so sorry if this was only a 'user misuse'.

When you use the `self.status` on a custom component, the data you return is not visible on the output preview.
As I said, i'm not sure this is the expected behaviour but it took me several hours to find out. The data is returned as expected, so you can use it afterwards. Only the preview is affected.

#iadevs

### Reproduction

1. Create a custom component or use an already defined one
2. Place the self.status before the 'data' return
3. The flow now misses the data from the preview.
4. If you use the "Parse data" you can see that the data is there, but the preview is not available on the inspect output.

### Expected behavior

I would expect the status to be a message presented on the preview only, but the data should be presented just as if the status is not visible.

### Operating System

Manjaro, using Docker official image.

### Langflow Version

1.0.14

### Python Version

None

### Screenshot

https://github.com/user-attachments/assets/52912cbc-55f5-4fcd-845a-0b664bf0479d

### Flow File

If needed, the redis component is on langflow store

**Comment by lucaseduoli** [comment]
Hello!

If I'm not mistaken, the Status variable is exactly what appears at the Output tab. It defaults to the data displayed when you don't set it. That's why it does not appear when you define the status.

**Comment by appoks** [comment]
> Hello!
> 
> If I'm not mistaken, the Status variable is exactly what appears at the Output tab. It defaults to the data displayed when you don't set it. That's why it does not appear when you define the status.

It makes sense, so I should assume that the status is the data that will be displayed on the output inspector, and the data that is really present on the output is the data we return from the function?

**Comment by anovazzi1** [comment]
@appoks, you're right. We handle it this way because sometimes your output is in a data format that we can't easily display. Therefore, you can use the status to show content that is both useful to the user and easy to display.

**Comment by appoks** [comment]
> @appoks, you're right. We handle it this way because sometimes your output is in a data format that we can't easily display. Therefore, you can use the status to show content that is both useful to the user and easy to display.

Great, thanks :)

**Comment by liu3238** [comment]
When a component is used as a tool, it is not possible to view the state of its output through the Component Output. Is there any way to check it?
