### ISSUE TITLE
崩溃重启

### ISSUE THREAD

**Issue by iopa788** [langflow-ai/langflow#3194]
只要是成功创建好的产品 退出后下一次启动项目 比崩溃  非代码部署

**Comment by lucaseduoli** [comment]
Hello!

Could you please provide a screenshot of what happens, and the version of your langflow?

Thanks

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
