### ISSUE TITLE
Multimodais não funcionam mais

### ISSUE THREAD

**Issue by amiartint** [langflow-ai/langflow#3209]
### Bug Description

Pessoal, desde as novas versões 1.x os fluxos com as as multimodais (uso Gemini 1.5 flash, GPT 4o e GPT 4o mini) não funcionam mais, olhem o print. Meu fluxo de teste é super simples (print também), parou de funcionar quando tive que atualizar alguns  componentes dele.

Por favor ajuda aê, tem alguns bons dias isto e não sou o único, vi outras pessoas com o mesmo problema no Dircord.

![ScreenShot_20240805205526](https://github.com/user-attachments/assets/60051ed3-0320-4cd9-aa1b-de5dffad4ce1)

![ScreenShot_20240805201419](https://github.com/user-attachments/assets/379a3ee7-93ac-47ef-b70d-a4c8a1454607)

### Reproduction

Envio imagem no Playground, o erro aparece. Quando também escrevo alguma coisa ou não escrevo nada.
![ScreenShot_20240805201419](https://github.com/user-attachments/assets/84ea6337-a1d2-4984-8a26-1343dd41f257)
![ScreenShot_20240805205526](https://github.com/user-attachments/assets/4e4d6ece-9a74-42e8-9743-67fe026c3f2f)

### Expected behavior

Multimodais funcionando

### Operating System

Windows 10

### Langflow Version

1.0.14

### Python Version

3.12

### Screenshot

![ScreenShot_20240805201419](https://github.com/user-attachments/assets/9146974d-bc30-4dcb-98e7-55fc787ef482)
![ScreenShot_20240805205526](https://github.com/user-attachments/assets/57780b1d-d85c-4031-8ea6-83a499c73720)

**Comment by amiartint** [comment]
Olá @Dosu

Já usei o GPT do Langflow para analisar esta mensagem de erro e encontrei estas respostas também. Os componentes do fluxo estão atualizados, o que gostaria de saber é se preciso mudar a estrutura do fluxo, trocando componentes por outros, por exemplo. Ou adicionando novos, o que seja.

Sou novato no Langflow e estou em busca de uma ferramenta para utilizar multimodais em chatbots e outros app, encontrando esta ferramenta será a que vou usar junto aos meus clientes. Vocês tem outras pessoas enfrentando o mesmo problema que eu, ontem mesmo encontrei outro usuario na mesma situação no Discord, começamos a conversar e trocar experiências sobre a questão. Me parece que se vocês nos disserem o que fazer em um fluxo simples como o meu, por exemplo, ou se for um problema no framework que ele seja acertado o mais rápido possível (tem mais de semana que venho relatando o problema no Discord), será bom para todos nós, vocês e seus usuários. 

Sou brasileiro, orgulhoso do trabalho dos meus compatriotas, mas preciso prestar serviços e ganhar dinheiro. Quero muito, mas muito mesmo, virar o usuário número 1 do Langflow no Brasil, tenho clientes na Europa e na América do Sul esperando minha resposta sobre a ferramenta que vamos utilizar.

**Comment by amiartint** [comment]
Não entendi nada. É para fazer o que? Não sou programador, se eu tiver que ter este conhecimento, vou desistir do Langflow.

**Comment by amiartint** [comment]
@ogabrielluiz, tudo bem? Estamos eu e muitos usuários do Langflow com um grande problema. Olha acima, por favor.

**Comment by carlosrcoelho** [comment]
@amiartint 

Estou tentando replicar seu problema, mas sem sucesso. Consegue me informar se esse problema persiste na atua versão 1.0.15?

Se estiver persistindo pra você, consegue compartilhar o flow?

**Comment by amiartint** [comment]
Persiste, ontem pelo menos persistia, dia 13/08. Fluxo absolutamente simplório, básico. 
![image](https://github.com/user-attachments/assets/86d165ce-186b-47b9-b509-e2db5b081b84)
![image](https://github.com/user-attachments/assets/98292651-d85d-413d-a9f3-e2e43701b5b0)

**Comment by amiartint** [comment]
Persiste hoje também, acabei de rodá-lo (print).

**Comment by amiartint** [comment]
Onde o erro aparece no fluxo.
![image](https://github.com/user-attachments/assets/8571bc6e-f662-4cae-9d9e-f8ad09857a23)

**Comment by carlosrcoelho** [comment]
@amiartint 

Consegue me enviar o seu flow?

**Comment by amiartint** [comment]
@carlosrcoelho , acima o flow

**Comment by amiartint** [comment]
Oi Carlos, enviei lá

Carlos Coelho ***@***.***> escreveu (quarta, 14/08/2024 à(s)
16:17):

**Comment by carlosrcoelho** [comment]
@amiartint 

Testei seu flow e deu certo. Estou usando a versao 1.0.15.

Segue o video:

https://github.com/user-attachments/assets/e5193122-f182-4a8a-b1e0-2719062d1eb6

**Comment by amiartint** [comment]
Também, versão 1.0.15, no VSCODE, Python 3.12.2. Tem alguma ideia do que
pode estar errado? Tentei inclusive trocar o prompt por um novo, como no
print, mesmo erro.

[image: image.png]

[image: image.png]

[image: image.png]

[image: image.png]

Carlos Coelho ***@***.***> escreveu (sexta, 16/08/2024 à(s)
09:32):

**Comment by carlosrcoelho** [comment]
O que você  quer dizer usando VSCODE?

Eu usei a versão `main` do Langflow. Se puder gravar um pequeno video do processo que está realizando, me ajuda.

E também mandar um print dos logs do backend apontando o erro.

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.

**Comment by McCalebTheSecond** [comment]
I had the same issue on Windows 11 and resolved it.  It seems to be an issue with slashes being different between linux and windows.  Anyway, I simply replaced a line in the image.py file.  

From: `flow_id, file_name = file.split("/")`

To: `flow_id, file_name = re.split(r"[\\/]", file, maxsplit=1)`

I added `import re` to the file as well.

FYI, I'm not a real developer.  I just poked around and used ChatGPT.
