### ISSUE TITLE
Unable to Delete Flows

### ISSUE THREAD

**Issue by mbbyn** [langflow-ai/langflow#3213]
### Bug Description

Whenever I try to delete a flow, there is an exception and I am unable to delete the flow.

### Reproduction

Create a flow, add some components to it, run it a few times (send data using playground). Try to delete it.

### Expected behavior

It should be deletable.

### Who can help?

@italojohnny 

### Operating System

RHEL 8 Langflow Docker image

### Langflow Version

1.0.14

### Python Version

None

**Comment by mbbyn** [comment]
The logs are not being printed properly for some reason, but here is the most relevant part:

```
NotNullViolation: null value in column
                              "flow_id" of relation "transaction"
                              violates not-null constraint
                              DETAIL:  Failing row contains
                              (2024-08-06 10:28:46.131792,
                              CustomComponent-OBvDV,
                              ChatOutput-rzfAn, {"code": "# from
                              langflow.field_typing import
                              Data\nfrom langflo..., {"results": {},
                              "artifacts": {"success_result":
                              {"repr": "{\n   ..., success, null,
                              null,
                              059c084a-51c5-4465-9e41-a34cef3e1a0e).
```

**Comment by w3XeWIRpuND** [comment]
Same issue for me..
![image](https://github.com/user-attachments/assets/3c1b380e-0b0f-4db2-ab1c-6cbd81a61459)

Any solutions?

**Comment by mieslep** [comment]
I've worked around this by stopping Langflow, going into the sqlite database command line, and deleting:

```
delete from 'transaction' where flow_id = 'e57cdc407439432cb448d7b4a5f1eb59';
delete from flow where id = 'e57cdc407439432cb448d7b4a5f1eb59';
```

But it definitely looks to be a problem in 1.0.14 (not sure what other versions affected)

**Comment by mieslep** [comment]
This issue does not reproduce on v1.0.15 (just released).

**Comment by w3XeWIRpuND** [comment]
Yes, my issue is gone in the latest release. Thank you!
