### ISSUE TITLE
unable to install Langflow on macOS

### ISSUE THREAD

**Issue by Knight7561** [langflow-ai/langflow#3214]
### Bug Description

Unable to complete pip install langflow due to incomplete installation of chroma-hnswlib.
Also, I tried to install chroma-hnswlib using pip successfully.nevertheless, langflow install fails

Error:
Using cached pluggy-1.5.0-py3-none-any.whl (20 kB)
Using cached ratelimiter-1.2.0.post0-py3-none-any.whl (6.6 kB)
Using cached semver-3.0.2-py3-none-any.whl (17 kB)
Using cached trio-0.26.1-py3-none-any.whl (475 kB)
Using cached trio_websocket-0.11.1-py3-none-any.whl (17 kB)
Using cached iniconfig-2.0.0-py3-none-any.whl (5.9 kB)
Using cached pycparser-2.22-py3-none-any.whl (117 kB)
Using cached geomet-0.2.1.post1-py3-none-any.whl (18 kB)
Using cached PySocks-1.7.1-py3-none-any.whl (16 kB)
Using cached wsproto-1.2.0-py3-none-any.whl (24 kB)
Using cached outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Using cached sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Building wheels for collected packages: chroma-hnswlib
  Building wheel for chroma-hnswlib (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for chroma-hnswlib (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      running bdist_wheel
      running build
      running build_ext
      creating var
      creating var/folders
      creating var/folders/pb
      creating var/folders/pb/mpbt28916txgg2qpg8w58lgc0000gn
      creating var/folders/pb/mpbt28916txgg2qpg8w58lgc0000gn/T
      clang -fno-strict-overflow -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -O3 -Wall -arch arm64 -arch x86_64 -g -I/Library/Frameworks/Python.framework/Versions/3.12/include/python3.12 -c /var/folders/pb/mpbt28916txgg2qpg8w58lgc0000gn/T/tmpt6iqy6mj.cpp -o var/folders/pb/mpbt28916txgg2qpg8w58lgc0000gn/T/tmpt6iqy6mj.o -std=c++14
      clang -fno-strict-overflow -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -O3 -Wall -arch arm64 -arch x86_64 -g -I/Library/Frameworks/Python.framework/Versions/3.12/include/python3.12 -c /var/folders/pb/mpbt28916txgg2qpg8w58lgc0000gn/T/tmpmfeiq5yz.cpp -o var/folders/pb/mpbt28916txgg2qpg8w58lgc0000gn/T/tmpmfeiq5yz.o -fvisibility=hidden
      building 'hnswlib' extension
      creating build
      creating build/temp.macosx-10.9-universal2-cpython-312
      creating build/temp.macosx-10.9-universal2-cpython-312/python_bindings
      clang -fno-strict-overflow -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -O3 -Wall -arch arm64 -arch x86_64 -g -I/private/var/folders/pb/mpbt28916txgg2qpg8w58lgc0000gn/T/pip-build-env-50enl01x/overlay/lib/python3.12/site-packages/pybind11/include -I/private/var/folders/pb/mpbt28916txgg2qpg8w58lgc0000gn/T/pip-build-env-50enl01x/overlay/lib/python3.12/site-packages/numpy/_core/include -I./hnswlib/ -I/Library/Frameworks/Python.framework/Versions/3.12/include/python3.12 -c ./python_bindings/bindings.cpp -o build/temp.macosx-10.9-universal2-cpython-312/./python_bindings/bindings.o -O3 -march=native -stdlib=libc++ -mmacosx-version-min=10.7 -DVERSION_INFO=\"0.7.3\" -std=c++14 -fvisibility=hidden
      clang: error: unsupported argument 'native' to option '-march='
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for chroma-hnswlib
Failed to build chroma-hnswlib
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (chroma-hnswlib)

### Reproduction

Tried the debug steps in previous issues, 
Currently using Python 3.12
Reproduction Steps:
1. python -m pip install langflow  -U --pre --force-reinstall
Output:
<Using cached versions of deps>

Using cached uuid6-2024.1.12-py3-none-any.whl (6.4 kB)
Using cached uvloop-0.19.0-cp312-cp312-macosx_10_9_x86_64.whl (745 kB)
Using cached watchfiles-0.22.0-cp312-cp312-macosx_10_12_x86_64.whl (394 kB)
Using cached XlsxWriter-3.2.0-py3-none-any.whl (159 kB)
Using cached yarl-1.9.4-cp312-cp312-macosx_10_9_x86_64.whl (81 kB)
Using cached zipp-3.19.2-py3-none-any.whl (9.0 kB)
Using cached coloredlogs-15.0.1-py2.py3-none-any.whl (46 kB)
Using cached colorlog-6.8.2-py3-none-any.whl (11 kB)
Using cached flatbuffers-24.3.25-py2.py3-none-any.whl (26 kB)
Using cached Mako-1.3.5-py3-none-any.whl (78 kB)
Using cached pyarrow_hotfix-0.6-py3-none-any.whl (7.9 kB)
Using cached pyproject_hooks-1.1.0-py3-none-any.whl (9.2 kB)
Using cached sympy-1.13.1-py3-none-any.whl (6.2 MB)
Using cached wcwidth-0.2.13-py2.py3-none-any.whl (34 kB)
Using cached webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Using cached xxhash-3.4.1-cp312-cp312-macosx_10_9_x86_64.whl (31 kB)
Using cached asgiref-3.8.1-py3-none-any.whl (23 kB)
Using cached cassandra_driver-3.29.1-cp312-cp312-macosx_10_9_x86_64.whl (3.6 MB)
Using cached greenlet-3.0.3-cp312-cp312-macosx_11_0_universal2.whl (273 kB)
Using cached grpc_google_iam_v1-0.13.1-py2.py3-none-any.whl (24 kB)
Using cached grpcio_status-1.63.0rc1-py3-none-any.whl (14 kB)
Using cached hpack-4.0.0-py3-none-any.whl (32 kB)
Using cached humanfriendly-10.0-py2.py3-none-any.whl (86 kB)
Using cached hyperframe-6.0.1-py3-none-any.whl (12 kB)
Using cached jsonpointer-3.0.0-py2.py3-none-any.whl (7.6 kB)
Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Using cached nodeenv-1.9.1-py2.py3-none-any.whl (22 kB)
Using cached ordered_set-4.1.0-py3-none-any.whl (7.6 kB)
Using cached pluggy-1.5.0-py3-none-any.whl (20 kB)
Using cached ratelimiter-1.2.0.post0-py3-none-any.whl (6.6 kB)
Using cached semver-3.0.2-py3-none-any.whl (17 kB)
Using cached trio-0.26.1-py3-none-any.whl (475 kB)
Using cached trio_websocket-0.11.1-py3-none-any.whl (17 kB)
Using cached iniconfig-2.0.0-py3-none-any.whl (5.9 kB)
Using cached pycparser-2.22-py3-none-any.whl (117 kB)
Using cached geomet-0.2.1.post1-py3-none-any.whl (18 kB)
Using cached PySocks-1.7.1-py3-none-any.whl (16 kB)
Using cached wsproto-1.2.0-py3-none-any.whl (24 kB)
Using cached outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Using cached sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Building wheels for collected packages: chroma-hnswlib
  Building wheel for chroma-hnswlib (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for chroma-hnswlib (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      running bdist_wheel
      running build
      running build_ext
      creating var
      creating var/folders
      creating var/folders/pb
      creating var/folders/pb/mpbt28916txgg2qpg8w58lgc0000gn
      creating var/folders/pb/mpbt28916txgg2qpg8w58lgc0000gn/T
      clang -fno-strict-overflow -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -O3 -Wall -arch arm64 -arch x86_64 -g -I/Library/Frameworks/Python.framework/Versions/3.12/include/python3.12 -c /var/folders/pb/mpbt28916txgg2qpg8w58lgc0000gn/T/tmpt6iqy6mj.cpp -o var/folders/pb/mpbt28916txgg2qpg8w58lgc0000gn/T/tmpt6iqy6mj.o -std=c++14
      clang -fno-strict-overflow -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -O3 -Wall -arch arm64 -arch x86_64 -g -I/Library/Frameworks/Python.framework/Versions/3.12/include/python3.12 -c /var/folders/pb/mpbt28916txgg2qpg8w58lgc0000gn/T/tmpmfeiq5yz.cpp -o var/folders/pb/mpbt28916txgg2qpg8w58lgc0000gn/T/tmpmfeiq5yz.o -fvisibility=hidden
      building 'hnswlib' extension
      creating build
      creating build/temp.macosx-10.9-universal2-cpython-312
      creating build/temp.macosx-10.9-universal2-cpython-312/python_bindings
      clang -fno-strict-overflow -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -O3 -Wall -arch arm64 -arch x86_64 -g -I/private/var/folders/pb/mpbt28916txgg2qpg8w58lgc0000gn/T/pip-build-env-50enl01x/overlay/lib/python3.12/site-packages/pybind11/include -I/private/var/folders/pb/mpbt28916txgg2qpg8w58lgc0000gn/T/pip-build-env-50enl01x/overlay/lib/python3.12/site-packages/numpy/_core/include -I./hnswlib/ -I/Library/Frameworks/Python.framework/Versions/3.12/include/python3.12 -c ./python_bindings/bindings.cpp -o build/temp.macosx-10.9-universal2-cpython-312/./python_bindings/bindings.o -O3 -march=native -stdlib=libc++ -mmacosx-version-min=10.7 -DVERSION_INFO=\"0.7.3\" -std=c++14 -fvisibility=hidden
      clang: error: unsupported argument 'native' to option '-march='
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for chroma-hnswlib
Failed to build chroma-hnswlib
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (chroma-hnswlib)

### Expected behavior

Clean installation of langflow 

### Who can help?

- @ogabrielluiz
- @nicoloboschi
- @zzzming
- @NadirJ

### Operating System

macOS Sonoma 14.6 (23G80)

### Langflow Version

1.0.14

### Python Version

3.12

### Screenshot

<img width="960" alt="Screenshot 2024-08-06 at 09 58 01" src="https://github.com/user-attachments/assets/107b155b-e731-429e-b590-9e85f1cfba08">

**Comment by carlosrcoelho** [comment]
@Knight7561 

Please try as follows:

Steps to Install Langflow:
- Ensure you have Python 3.10 or higher
- Create a virtual environment: `python3 -m venv installation-test`
- Activate the virtual environment: `source installation-test/bin/activate`
- Run: `python3 -m pip install langflow`
- Use the command: `langflow run`

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.

**Comment by fandaxian** [comment]
使用以上方法还未解决此问题

**Comment by Knight7561** [comment]
Opening a new issue for reopening this.
New issue #3359
