### ISSUE TITLE
'Flow as a Tool' is raising a `ToolException: Missing required arguments: chat_input`.

### ISSUE THREAD

**Issue by appoks** [langflow-ai/langflow#3234]
### Bug Description

Trying to use the Flow as a Tool, langflow raises a `ToolException: Missing required arguments: chat_input` exception.
My flow that is used as a tool is working as expected.

I'm using the branch main (Flow as a Tool was not working for me on 1.0.14)
Repo cloned around ~17:45 I guess, today.

It would be really great to have this working so I can try to participate on this week IAdev challenge. :pleading_face: 
#iadevs

### Reproduction

1. Create a flow to be used as a tool
2. Create a new flow using Tool Calling Agent. Give this agent a Flow as Tool tool that will use the tool previously created.
3. When asking a question to Tool Calling agent, an error is raised

### Expected behavior

I expect the tool calling agent to receive the repsonse from the Flow as a Tool and output it to Playground's chat output.

### Operating System

Manjaro

### Langflow Version

main

### Python Version

3.12

### Screenshot

https://github.com/user-attachments/assets/02821f57-37ea-4bfc-bb69-985d2dbcc9d3

**Comment by carlosrcoelho** [comment]
@appoks 

I just followed the steps you mentioned and got it to work.

Try swapping out your Chat Input in the flow that's being called by the Tool Calling Agent with a new sidebar.

![image](https://github.com/user-attachments/assets/867c1982-48fd-4d05-9aea-81086d32a940)

![image](https://github.com/user-attachments/assets/4c506372-db73-4e59-89b5-b1f7b4d1e33c)

**Comment by appoks** [comment]
@carlosrcoelho it's weird, not working for me even with the latest code from main. Maybe another thing is broken in my local install. I've tried replacing the Chat Input, Chat Output and LLMs from both files.
I've asked cezar to try this yesterday on live and it also worked, seems something is wrong here...

I will wait for the release so I can use the latest version on my dockerized env, so closing this issue for now. Sorry.
