### ISSUE TITLE
The text area that displays the model output has insufficient height and is unreadable.  

### ISSUE THREAD

**Issue by unoriginalscreenname** [langflow-ai/langflow#3237]
### Bug Description

It seems like all the text areas that are supposed to display output are so small that you can only read one line at a time.  if you manually inspect the elements and add a style height to them it fixes it.  But you clearly have some problem with your css.

### Reproduction

Any text area that displays output seems to suffer from this.

### Expected behavior

the text area should be minimally large enough to read more than one line at a time.  maybe a min of 600px.  or flex to be as high as the content.  

### Operating System

windows11

### Langflow Version

1.0.4

### Python Version

3.11

**Comment by carlosrcoelho** [comment]
@unoriginalscreenname 

Can you send a screenshot of what you're talking about? You mentioned you're on version 1.0.4. Try it with version 1.0.14.

**Comment by codenprogressive** [comment]
Yes, I'm seeing the same issue in 1.0.14

**Comment by codenprogressive** [comment]
@carlosrcoelho when you click inspect any component Output (text datatype), you cannot expand the text area height. it is locked. I'm on version 1.0.14
![image](https://github.com/user-attachments/assets/50e23f73-e1e6-4e78-bcaa-0e07025531d2)

**Comment by carlosrcoelho** [comment]
The correction for this will be in the new release soon. You can test it on the main branch; make sure to pull first.
