### ISSUE TITLE
While importing data into chroma, the langchain backend POD failed to respond to /health, and got killed.

### ISSUE THREAD

**Issue by maxpaynebupt** [langflow-ai/langflow#3243]
### Bug Description

While importing data into chroma, the langchain backend POD failed to respond to /health, and got killed.

### Reproduction

Deployment: use helm to deploy a ide release from "https://langflow-ai.github.io/langflow-helm-charts"
1. draw a pipeline which uses chroma as vector db.
2. try to load data into it, while loading, I can see that, even in the POD, I can not curl the 127.0.0.1/heath anymore.
3. after it reaches the deadline, got killed.
```
102s Warning Unhealthy pod/langflow-0 Liveness probe failed: Get "http://10.42.0.152:7860/health": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
102s Normal Killing pod/langflow-0 Container langflow-ide failed liveness probe, will be restarted```

### Expected behavior

Is the langflow working in async mode? It should spare some time to respond the health probe request.

### Who can help?

_No response_

### Operating System

ubuntu 24.04

### Langflow Version

langflow-ide-0.1.0 

### Python Version

None

### Screenshot

_No response_

### Flow File

_No response_

**Comment by maxpaynebupt** [comment]
> @maxpaynebupt Hello! I'm here to assist you with any issues or questions you have related to the langflow repository. Feel free to ask for help!
> 
> Yes, Langflow can operate in async mode using the `sync` flag set to `false` in the API request payload. This allows the system to handle tasks asynchronously, freeing up resources for other operations, including responding to health probe requests. Additionally, Langflow includes a health check endpoint (`/health`) that is designed to respond quickly, ensuring that the system can efficiently handle health probe requests even when operating in async mode [[1]](https://github.com/logspace-ai/langflow/blob/dev/docs/docs/guidelines/async-api.mdx)[[2]](https://github.com/langflow-ai/langflow/blob/main/src/backend/base/langflow/main.py).
> 
> To address the issue of the backend POD failing to respond to the health check during data import into Chroma, you might want to ensure that the `sync` flag is set to `false` for asynchronous processing. This can help in managing the load more effectively and keeping the health check responsive.
> 
> If the problem persists, you may also want to monitor specific logs and metrics to preemptively detect and mitigate issues with the Langflow backend POD. Key metrics include run metrics, shutdown metrics, version metrics, playground metrics, and component metrics [[3]](https://github.com/langflow-ai/langflow/blob/dev/docs/docs/contributing/telemetry.mdx)[[4]](https://github.com/logspace-ai/langflow/blob/dev/src/backend/base/langflow/services/monitor/utils.py).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

Thanks for your reply, but, how can I do that? Should I add some flag to the container's startup command?

**Comment by maxpaynebupt** [comment]
> To set the `sync` flag to `false` for asynchronous processing, you need to include it in your API request payload. Here's how you can do it:
> 
> ```shell
> curl -X POST \
>   http://localhost:3000/api/v1/process/<your_flow_id> \
>   -H 'Content-Type: application/json' \
>   -H 'x-api-key: <your_api_key>' \
>   -d '{"inputs": {"text": ""}, "tweaks": {}, "sync": false}'
> ```
> 
> This will initiate an asynchronous task instead of processing the flow synchronously [[1]](https://github.com/logspace-ai/langflow/blob/dev/docs/docs/guidelines/async-api.mdx).
> 
> If you want to modify the Langflow backend POD's startup command to include custom flags or environment variables, you can edit the `values.yaml` file used by the Helm chart for Langflow. For example, to add a custom environment variable `CUSTOM_ENV_VAR`, you can modify the `values.yaml` file as follows:
> 
> ```yaml
> langflow:
>   backend:
>     env:
>       - name: CUSTOM_ENV_VAR
>         value: "your_custom_value"
> ```
> 
> Additionally, you can configure various options using environment variables, which can be set in the `values.yaml` file under the `env` section:
> 
> ```yaml
> langflow:
>   backend:
>     env:
>       - name: LANGFLOW_HOST
>         value: "0.0.0.0"
>       - name: LANGFLOW_WORKERS
>         value: "2"
>       - name: LANGFLOW_PORT
>         value: "7860"
>       - name: LANGFLOW_LOG_LEVEL
>         value: "info"
>       - name: LANGFLOW_BACKEND_ONLY
>         value: "true"
> ```
> 
> This approach ensures that your custom flags and environment variables are correctly set when deploying Langflow in a Kubernetes cluster using Helm [[2]](https://github.com/logspace-ai/langflow/blob/dev/deploy/startup-backend.sh)[[3]](https://github.com/langflow-ai/langflow/blob/main/docs/docs/deployment/kubernetes.md).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

oh, Mr bot, I think we may need to add "--loop asyncio" to the startup command?

**Comment by maxpaynebupt** [comment]
> To add `--loop asyncio` to the startup command for the Langflow backend POD, you need to modify the `values.yaml` file used by the Helm chart for Langflow. Here is how you can do it:
> 
> ```yaml
> # values.yaml
> 
> langflow:
>   backend:
>     image:
>       repository: your-docker-repo/langflow
>       tag: latest
>     container:
>       command: ["uvicorn", "--factory", "langflow.main:create_app", "--host", "0.0.0.0", "--port", "7860", "--reload", "--log-level", "debug", "--loop", "asyncio"]
> ```
> 
> This configuration sets the command for the Langflow backend container to include the `--loop asyncio` option [[1]](https://github.com/langflow-ai/langflow/blob/dev/docker/container-cmd-cdk.sh)[[2]](https://github.com/langflow-ai/langflow/blob/main/docs/docs/deployment/kubernetes.md).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

Frustrating, this can not work, even when I added workers to 4, while loading data into chroma, the backend failed to respond, so the task will be marked failure at the backend.

**Comment by maxpaynebupt** [comment]
The conclusion is "Langflow is not ready to run in container".

**Comment by conradchu** [comment]
A similar problems happens when Langflow is running in Render.  /health check fails and the app is taken offline for a minute.

**Comment by conradchu** [comment]
@cbornet I check on this ticket every day.  We basically cannot run Langflow on Render because the health check fails too often when there's even a little load on it.  Render runs k8s behind the scenes.

**Comment by cbornet** [comment]
@conradchu do you reproduce the issue on a local deployment ?

**Comment by carlosrcoelho** [comment]
@maxpaynebupt 

Do you need any assistance with this case? If not, please let us know if this issue can be closed.

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to help you.
