### ISSUE TITLE
Nearly impossible to make it work behind a proxy

### ISSUE THREAD

**Issue by maxpaynebupt** [langflow-ai/langflow#3252]
### Bug Description

I am working behind a proxy server.
If I disable the proxy setting, when starting up langflow, it will try to fetch some pypi langflow json data, if it fails, it crash.
If setup the proxy setting, when I try to use our internal LLM service, it seems langflow can not recognize the NO_PROXY setting, it will try to access the local LLM service via proxy, that will fail for sure. Dilemma.

### Reproduction

Windows 11.
1. If I disable the proxy setting, when starting up langflow, it will try to fetch some pypi langflow json data, if it fails, it crash.
2. If setup the proxy setting, when I try to use our internal LLM service, it seems langflow can not recognize the NO_PROXY setting, it will try to access the local LLM service via proxy, that will fail for sure. Dilemma.

### Expected behavior

Langflow recognize the NO_PROXY settings.

### Operating System

Windows 11

### Langflow Version

v1.0.14

### Python Version

None

**Comment by maxpaynebupt** [comment]
> To address the issues you're facing with Langflow behind a proxy on Windows 11, you can take the following steps:
> 
> 1. **Configure the `NO_PROXY` Setting:**
>    Ensure that the `NO_PROXY` environment variable is set correctly to bypass the proxy for your internal services. You can set this environment variable in your system or within your application settings.
>    Here is how you can set the `NO_PROXY` environment variable in Python:
>    ```python
>    import os
>    
>    # Set the NO_PROXY environment variable
>    os.environ['NO_PROXY'] = 'localhost,127.0.0.1,.yourdomain.com'
>    
>    # Now you can initialize your settings
>    settings = Settings()
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    In the context of Langflow, you can add this configuration in the `base.py` file where the settings are initialized. Ensure that this environment variable is set before any network operations are performed [[1]](https://github.com/logspace-ai/langflow/blob/dev/src/backend/langflow/services/settings/base.py).
> 2. **Bypass PyPI Data Fetching:**
>    To prevent Langflow from fetching PyPI data during startup, you can use the `--no-store` parameter in the CLI options or set the `LANGFLOW_STORE` environment variable to `False`.
>    ```shell
>    langflow run --no-store
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    Or set the environment variable:
>    ```shell
>    export LANGFLOW_STORE=False
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    This will disable the store features and prevent Langflow from attempting to fetch PyPI data during startup [[2]](https://github.com/langflow-ai/langflow/blob/dev/README.md).
> 
> By following these steps, you should be able to configure Langflow to properly recognize the `NO_PROXY` setting and avoid issues with accessing internal services and fetching PyPI data behind a proxy.
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

tried with --no-store it still try to fetch https://pypi.org/pypi/langflow/json

**Comment by nicoloboschi** [comment]
@maxpaynebupt 
Could you elaborate more on your deployment architecture (bare metal, k8s, pypi package, docker, single container...)? 

> it will try to fetch some pypi langflow json data
what does it mean?

**Comment by maxpaynebupt** [comment]
> @maxpaynebupt Could you elaborate more on your deployment architecture (bare metal, k8s, pypi package, docker, single container...)?
> 
> > it will try to fetch some pypi langflow json data
> > what does it mean?

just pypi package installed on windows 11
