### ISSUE TITLE
How to use sqlDataBase

### ISSUE THREAD

**Issue by alex-ge123** [langflow-ai/langflow#3255]
### Bug Description

How   to  use   sqlDataBase  

### Reproduction

Look at the screenshot below

### Expected behavior

How to use sqlDataBase

### Operating System

windows 

### Langflow Version

1.0.14

### Python Version

None

### Screenshot

![微信图片_20240809170430](https://github.com/user-attachments/assets/f6ba323e-8ac7-490e-8b61-84af26b1543d)
![微信图片_20240809170450](https://github.com/user-attachments/assets/111799f0-ef85-48e9-b0e5-17c8ca7cf77b)

**Comment by alex-ge123** [comment]
![Uploading 微信图片_20240809171555.png…]()

**Comment by alex-ge123** [comment]
![微信图片_20240809171642](https://github.com/user-attachments/assets/3aa95594-f363-4a9a-b019-865f9711768a)

**Comment by alex-ge123** [comment]
![Uploading 微信图片_20240809171555.png…]()

**Comment by Alperemrehas** [comment]
> ### Bug Description
> How to use sqlDataBase
> 
> ### Reproduction
> Look at the screenshot below
> 
> ### Expected behavior
> How to use sqlDataBase
> 
> ### Who can help?
> _No response_
> 
> ### Operating System
> windows
> 
> ### Langflow Version
> 1.0.14
> 
> ### Python Version
> None
> 
> ### Screenshot
> ![微信图片_20240809170430](https://private-user-images.githubusercontent.com/71969995/356534429-f6ba323e-8ac7-490e-8b61-84af26b1543d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0OTc4NjcsIm5iZiI6MTcyMzQ5NzU2NywicGF0aCI6Ii83MTk2OTk5NS8zNTY1MzQ0MjktZjZiYTMyM2UtOGFjNy00OTBlLThiNjEtODRhZjI2YjE1NDNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDIxMTkyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3YzQ0NWUyOTk1YThmN2Q4ODEzYWFkNzg4M2ViYWE4OTE2MDdhZWM2MWE4M2U5ZjNlZTE0NzU1N2I3MGE2MjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pzk7i3_xraxYXtUGF4BorK0zOMFe1C9WTbJYMZ9zh6k) ![微信图片_20240809170450](https://private-user-images.githubusercontent.com/71969995/356534444-111799f0-ef85-48e9-b0e5-17c8ca7cf77b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0OTc4NjcsIm5iZiI6MTcyMzQ5NzU2NywicGF0aCI6Ii83MTk2OTk5NS8zNTY1MzQ0NDQtMTExNzk5ZjAtZWY4NS00OGU5LWIwZTUtMTdjOGNhN2NmNzdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDIxMTkyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlMTlmZDQ4OTBkNDliMDg5YjY2NWQyMjQxZjc0MDk1Y2VkNzdkYTczOGFlZmEwYzgzNDJlOTk3YWM0OTlkNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D_2oSnCZ_rawtUhEbuODpGtZAB95YSPFghpDpXdawb0)
> 
> ### Flow File
> _No response_

Hi, do you have special characters in your password?

**Comment by alex-ge123** [comment]
There are no special characters in the password

**Comment by alex-ge123** [comment]
> > ### Bug Description
> > How to use sqlDataBase
> > ### Reproduction
> > Look at the screenshot below
> > ### Expected behavior
> > How to use sqlDataBase
> > ### Who can help?
> > _No response_
> > ### Operating System
> > windows
> > ### Langflow Version
> > 1.0.14
> > ### Python Version
> > None
> > ### Screenshot
> > ![微信图片_20240809170430](https://private-user-images.githubusercontent.com/71969995/356534429-f6ba323e-8ac7-490e-8b61-84af26b1543d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0OTc4NjcsIm5iZiI6MTcyMzQ5NzU2NywicGF0aCI6Ii83MTk2OTk5NS8zNTY1MzQ0MjktZjZiYTMyM2UtOGFjNy00OTBlLThiNjEtODRhZjI2YjE1NDNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDIxMTkyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3YzQ0NWUyOTk1YThmN2Q4ODEzYWFkNzg4M2ViYWE4OTE2MDdhZWM2MWE4M2U5ZjNlZTE0NzU1N2I3MGE2MjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pzk7i3_xraxYXtUGF4BorK0zOMFe1C9WTbJYMZ9zh6k) ![微信图片_20240809170450](https://private-user-images.githubusercontent.com/71969995/356534444-111799f0-ef85-48e9-b0e5-17c8ca7cf77b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0OTc4NjcsIm5iZiI6MTcyMzQ5NzU2NywicGF0aCI6Ii83MTk2OTk5NS8zNTY1MzQ0NDQtMTExNzk5ZjAtZWY4NS00OGU5LWIwZTUtMTdjOGNhN2NmNzdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDIxMTkyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlMTlmZDQ4OTBkNDliMDg5YjY2NWQyMjQxZjc0MDk1Y2VkNzdkYTczOGFlZmEwYzgzNDJlOTk3YWM0OTlkNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D_2oSnCZ_rawtUhEbuODpGtZAB95YSPFghpDpXdawb0)
> > ### Flow File
> > _No response_
> 
> Hi, do you have special characters in your password?

There are no special characters in the password

**Comment by rajeshK88** [comment]
SQLDatabase use SQLAlachemy to connect to sql database and SQLAlchemy needs mysql dialect/driver to connect to mysql db which needs to be installed in langflow itself. 

https://docs.sqlalchemy.org/en/20/dialects/mysql.html#dialect-mysql

you can add [pymysql](https://docs.sqlalchemy.org/en/20/dialects/mysql.html#module-sqlalchemy.dialects.mysql.pymysql) in [pyproject.toml](https://github.com/langflow-ai/langflow/blob/main/pyproject.toml)

**Comment by carlosrcoelho** [comment]
#3291 

For example:
You can try to create via docker:
`docker run --name langflow-db -e POSTGRES_USER=admin -e POSTGRES_PASSWORD=admin -e POSTGRES_DB=test -p 5432:5432 -d postgres:latest && echo 'PostgreSQL URI: postgresql://admin:admin@localhost:5432/test'`

In the component, insert the URI:

postgresql://admin:admin@localhost:5432/test

**Comment by alex-ge123** [comment]
> #3291
> 
> For example: You can try to create via docker: `docker run --name langflow-db -e POSTGRES_USER=admin -e POSTGRES_PASSWORD=admin -e POSTGRES_DB=test -p 5432:5432 -d postgres:latest && echo 'PostgreSQL URI: postgresql://admin:admin@localhost:5432/test'`
> 
> In the component, insert the URI:
> 
> postgresql://admin:admin@localhost:5432/test

thank you ！    Have a chance to visit Xi 'an, China

**Comment by rickysut** [comment]
how to. insttal mysql client at docker ?
