### ISSUE TITLE
How  to  use  redis

### ISSUE THREAD

**Issue by alex-ge123** [langflow-ai/langflow#3256]
### Bug Description

How   to  use   redis

### Reproduction

Look at the screenshot below

### Expected behavior

How to use redis

### Operating System

windows 

### Langflow Version

1.0.14

### Python Version

3.11

### Screenshot

![微信图片_20240809170857](https://github.com/user-attachments/assets/09a7ef00-2202-4879-a703-56e31db3b347)
![微信图片_20240809170934](https://github.com/user-attachments/assets/001a69c1-8055-4163-90c0-e87d2cf095d6)

**Comment by alex-ge123** [comment]
![Uploading 微信图片_20240809170857.png…]()

**Comment by italojohnny** [comment]
Hi, @alex-ge123 . I'm sorry for taking so long to respond.

You can test this component by spinning up a Redis Docker container with the following command:

`docker run -p 6379:6379 redis/redis-stack-server:latest`

After that, you can configure the component as shown in the image:


<img width="793" alt="Screenshot 2024-08-28 at 16 55 06" src="https://github.com/user-attachments/assets/c1dbca91-63ac-4154-b4da-0aeec9169555">



Please let me know if this works for you.

**Comment by italojohnny** [comment]
Hi, @alex-ge123 . I hope you were able to resolve it.
If you still have any questions, please feel free to create a new issue

**Comment by alex-ge123** [comment]
> Hi, @alex-ge123 . I hope you were able to resolve it. If you still have any questions, please feel free to create a new issue


https://github.com/user-attachments/assets/7667fbff-887e-4ef2-a2b9-7ecc863b290d

@italojohnny
