### ISSUE TITLE
Playground does not fully clear chat history

### ISSUE THREAD

**Issue by unoriginalscreenname** [langflow-ai/langflow#3264]
### Bug Description

This is a tough one to explain, so maybe someone else is seeing this too.  I have a chat input at the start of my flow, and then a message to chat output at the end.  When i open up the playground, it will add all of the chat messages in there as expected.  However, if i hit the eraser button to clear out the chat, it will at first get rid of all the previous chat... but then if i close the playground and re-open it ALL of the previous chat history will appear and it will auto scroll me down to the bottom.  

additionally, this happens even if i go over to the memories section and fully delete all the previous chat history from there.  It's as if it's being cached somewhere.  

### Reproduction

Try and clear/delete the chat history, then close the playground, run the flow again, and see if it all appears.  

### Expected behavior

I would expect that the eraser button in 

### Operating System

windows11

### Langflow Version

1.0.14

### Python Version

3.11

**Comment by codenprogressive** [comment]
I confirm! I'm facing the same behavior

**Comment by anovazzi1** [comment]
Hello @unoriginalscreenname, I have just tested it on version v1.0.15 and it's working as expected, can you try on the latest version pls?
