### ISSUE TITLE
fix:The "No suitable component" error is appearing on the OpenAI component and other components due to a missing check.

### ISSUE THREAD

**Issue by deekshanee** [langflow-ai/langflow#3272]
Issue has been fixed here  - https://github.com/langflow-ai/langflow/pull/3273

### Bug Description

We have noticed that a check is missing when displaying edge dots on the left side of the component. As a result, an unnecessary dot is appearing, causing confusion for users.

https://github.com/user-attachments/assets/e9eee00d-51ad-4e69-bd80-dac3394bd813

### Reproduction

1. Open Langflow.
2. Click on "Add New Project."
3. Select the "Basic Prompting" template.
4. You'll notice that the OpenAI node displays an unused edge dot on the left side.

### Expected behavior

There shouldn't be any dot on the left side, as there isn't a suitable component for this node.

### Who can help?

@anovazzi1  @Cristhianzl  @lucaseduoli  @igorrCarvalho 

### Operating System

Mac , Windows

### Langflow Version

latest

### Python Version

None

**Comment by construindosites** [comment]
Também achei esse bug hoje e fiz um vídeo, mas é só deletar o componente openAI e adicionar outro no lugar que funciona. 

(I also found this bug today and made a video, but just delete the openAI component and add another one in its place and it works.)

**Comment by construindosites** [comment]
[Langflow-bug.webm](https://github.com/user-attachments/assets/c6cb4e7a-a44b-49df-9420-3c3d880dda54)

**Comment by deekshanee** [comment]
> Também achei esse bug hoje e fiz um vídeo, mas é só deletar o componente openAI e adicionar outro no lugar que funciona.
> 
> (I also found this bug today and made a video, but just delete the openAI component and add another one in its place and it works.)

I have fixed this issue in general so that it will not be the problem

**Comment by deekshanee** [comment]
thanks @lucaseduoli  It was my first contribution :)

**Comment by lucaseduoli** [comment]
You're welcome! Feel free to contribute anytime! If you need any help understanding the code, you can message me and I'll be more than glad to help.

**Comment by deekshanee** [comment]
> You're welcome @deekshanee ! Feel free to contribute anytime! If you need any help understanding the code, you can message me and I'll be more than glad to help.

Thanks @lucaseduoli  , It will be my pleasure to connect with you on LinkedIn?
