### ISSUE TITLE
langflow 1.0.15 import problem

### ISSUE THREAD

**Issue by severfire** [langflow-ai/langflow#3276]
### Bug Description

Hello,

Installed and started langflow in dev mode - 

but when I am importing flows, even the ones that i create in 1.0.15 I get error in js console
"index-DnQl3Zy0.js:1 Uncaught (in promise) DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at o.onchange (http://127.0.0.1:7860/assets/index-DnQl3Zy0.js:1:4767)"

and the importing flow is not imported

### Reproduction

1. installing all the required libs on windows wls, setting up right
2. running poetry install
3. running make init
4. the welcome message shows
5. going to http://127.0.0.1:7860  
6. importing flow
7. getting error in js console
8. import failed, no uploaded flow in the lib

A. same goes for environment for make frontend / make backend

### Expected behavior

it should add the flow

### Operating System

Windows 11 pro with WLS

### Langflow Version

1.0.15

### Python Version

3.11

### Flow File

Memory chatbot from starting template or others

**Comment by ogabrielluiz** [comment]
Hey, @severfire ! 

Good catch! Thank god we didn’t release it yet haha 

Should be fixed asap.

**Comment by severfire** [comment]
@ogabrielluiz was it bug or was it something wrong with my env? :-/

**Comment by ogabrielluiz** [comment]
We've released it yesterday. Could you try again? We have some big changes yesterday

**Comment by severfire** [comment]
@ogabrielluiz 
Tested it further. 
Seems like it is the problem with Brave browser. 

Tested with:
- newly built dev 1.0.15 (make init) 
- pipx version of langflow 1.0.15 (langflow run) 
with brave and firefox. 

Seems like Brave browser had problems.  

Looks then it is not critical. 
Next time I will test with both browsers.

**Comment by anovazzi1** [comment]
hey @severfire, just tested on brave and did not saw this warning on console, I will close the issue for now, if it happens again we can re-open :)
