### ISSUE TITLE
سلام 

### ISSUE THREAD

**Issue by Erfan5673** [langflow-ai/langflow#3301]
من قسط دارم به شما کمک کنم لطفاً بیشتر مرا راهنمایی کنید

**Comment by carlosrcoelho** [comment]
@Erfan5673 

Can you give me more details about the issue?

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
