### ISSUE TITLE
The createData component is unavailable

### ISSUE THREAD

**Issue by alex-ge123** [langflow-ai/langflow#3303]
### Bug Description

![微信图片_20240813155629](https://github.com/user-attachments/assets/c23df1e9-29e9-494e-82f3-d40eeec699c6)
![微信图片_20240813155713](https://github.com/user-attachments/assets/b597d491-e395-4d3d-8dfd-090837f044b0)

### Reproduction

Add a createData component and click Debug

### Expected behavior

1

### Operating System

windows 

### Langflow Version

1.0.15

### Python Version

3.11

**Comment by alex-ge123** [comment]
This problem is very important to me, please kindly solve this problem quickly. Thank you  @dosu

**Comment by asananddevsingh** [comment]
@carlosrcoelho, @saikolasani Issue fixed here: https://github.com/langflow-ai/langflow/pull/3363, please review.

**Comment by saikolasani** [comment]
@asananddevsingh Thanks for this, approved changes and merged. @alex-ge123 Thanks for your patience, the fix should be out in the next release. Please feel free to create another issue if it fails again. Closing this for now.
