### ISSUE TITLE
"Sorry, we found an unexpected error! " message 

### ISSUE THREAD

**Issue by TzurV** [langflow-ai/langflow#3305]
getting the following new error deploying langflow based docker that worked yesterday.

![image](https://github.com/user-attachments/assets/9a4bf640-2261-4ee8-9ffd-397c3707dc22)

logs link:
https://dashboard.render.com/web/srv-cqls9pqj1k6c739qp300/deploys/dep-cqtj7prv2p9s73dhgts0

and screenshot:
![image](https://github.com/user-attachments/assets/8d3566a3-48ff-42d0-8c27-68cde2a31efa)

**Comment by TzurV** [comment]
Yesterday, it worked and I've suspended the service.
This morning, it stopped working and I haven't changed anything.

The problem is that this morning I've tried a few things, which didn't
help, but I'm unsure I've returned to the starting point.
It has to do with langflow. Can it do to some code/version update ?

What would you like me to share with you?

Tzur

**Comment by Gluepower** [comment]
I have the same issue. Installed new version and everything worked earlier today. Just got back from work and had that message. Tried to rebuild and redeploy but no help.
![image](https://github.com/user-attachments/assets/f4dc2a65-ef0c-42fa-a811-8f34bfe4b3d1)

**Comment by Gluepower** [comment]
OK, so it works again even that I didn't change anything. Just kept trying to access and at first had 50% success rate and not it seems to be working again. Not sure what log to share. From screenshot above seems error is related to starter projects templates.

**Comment by carlosrcoelho** [comment]
@TzurV 

Do you need any assistance with this case? If not, please let us know if this issue can be closed.

@Gluepower 

Please give it a try on the latest version 1.0.16.

**Comment by Gluepower** [comment]
This one can be closed. Didn't had this showing up recently. It was got gone by itself.

**Comment by TzurV** [comment]
Ok, thanks.
