### ISSUE TITLE
Missing transformers

### ISSUE THREAD

**Issue by simwai** [langflow-ai/langflow#3307]
### Bug Description

Hello, I tried out this awesome project today and straight got into the problem that transformers lib is not being installed. 
Can you please add the transformers to the requirements and make a new docker build? That would be very nice of you thanks.

### Reproduction

I tried out a classic HuggingFace RAG pipeline of the templates.

### Expected behavior

- Transformers installed
- HuggingFace just working without problems

### Who can help?

@zzzming
@NadirJ
@ogabrielluiz 

### Operating System

Ubuntu Linux 22.04

### Langflow Version

1.0.15

### Python Version

3.10

**Comment by saikolasani** [comment]
@simwai Thanks for the suggestion. Ive handled it in #3374. The next release should resolve the issue that your are describing. Closing this issue for now.

**Comment by simwai** [comment]
Thanks a bunch. 👌
