### ISSUE TITLE
Error - Edge between CrewAIAgentComponent

### ISSUE THREAD

**Issue by unoriginalscreenname** [langflow-ai/langflow#3310]
### Bug Description

Starting Langflow v1.0.15...
[08/13/24 13:18:55] ERROR    2024-08-13 13:18:55 - ERROR    - setup - Edge between Component and            setup.py:580
                             CrewAIAgentComponent has invalid handles

I'm seeing this in the console when I start up and none of the agent flows seem to work.  This error shows up in the UI as well when I try to run anything.  

### Reproduction

Try to run any of the default workflows with agents.  look at the console when it loads up.

### Expected behavior

It should not have this error.

### Operating System

windows11

### Langflow Version

1.0.15

### Python Version

3.12

**Comment by konradbjk** [comment]
Same happens for me in when using docker deployment

**Comment by Cristhianzl** [comment]
Hey @konradbjk, @unoriginalscreenname,

Hope you're both doing well.

I’ve run all the agent flows, and everything is working fine on my end using the latest updates from the main branch. I suggest we release version 1.0.16 tomorrow, which should resolve this issue.

![image](https://github.com/user-attachments/assets/4f11fb9f-e431-4611-89d2-e5171edae963)

![image](https://github.com/user-attachments/assets/82153f53-ce61-4f03-be89-57febb7b3370)

![image](https://github.com/user-attachments/assets/bfab0c35-02e7-484a-aaea-2f010eff212d)


Please let me know if the error persists after updating.

Thanks!

**Comment by konradbjk** [comment]
I am not sure if it is related to flows. In my case, the error occurs on flows that do not have crewAI components
