### ISSUE TITLE
Low level of contrast between text and background while editing - IA Devs

### ISSUE THREAD

**Issue by Vigtu** [langflow-ai/langflow#3312]
### Bug Description

When opening the text editing window and clicking on the text field to edit a prompt in 'dark mode,' a low contrast issue arises. The background of the editing area becomes excessively bright, making the text difficult to read. This issue only occurs while actively editing; if the user clicks outside the editing area, the background returns to its normal color. However, the bug reappears each time the user clicks to edit the text.

### Reproduction

1. Enable Dark Mode in Langflow
2. Open a 'Prompt' Component
3. Click to Edit the Text in the Pop-up Window:
- Click on the 'Prompt' component to open the pop-up text editing window. Click inside the text field within the pop-up to start editing. Observe that the background of the text field becomes excessively bright, causing a low contrast with the text.
4. Click Outside the Pop-up:
- Click anywhere outside the pop-up window to close or deselect the text field. The background returns to the normal dark color. The issue will repeat if you click to edit the text again in the pop-up window or similar components with text editing.

### Expected behavior

When editing text in the pop-up window of a 'Prompt' component (or any similar text editing component) in Dark Mode, the background color should remain consistent with the dark theme. The text should be clearly visible with appropriate contrast, ensuring readability throughout the editing process. The background should not change to an excessively bright color when the text field is clicked, and the interface should maintain the intended dark appearance to avoid straining the user's eyes.

### Who can help?

@anovazzi1
@Cristhianzl

### Operating System

Windows 11

### Langflow Version

v1.0.15

### Python Version

3.12

### Screenshot

![image](https://github.com/user-attachments/assets/8223e0ef-db33-44da-91bb-823cd0fd8f77)

**Comment by anovazzi1** [comment]
Thanks for the feedback, it will be fixed in the next release
