### ISSUE TITLE
v1.0.15 - Not able to Sign Up new users

### ISSUE THREAD

**Issue by codenprogressive** [langflow-ai/langflow#3313]
### Bug Description

I'm disabling Auto_login and setting up superuser.

LANGFLOW_AUTO_LOGIN=false
LANGFLOW_SUPERUSER="admin"
LANGFLOW_SUPERUSER_PASSWORD="dummypasword"
LANGFLOW_NEW_USER_IS_ACTIVE=false
LANGFLOW_SECRET_KEY="randomly_generated_secure_key"

when a new user is trying to sign up, an error will pop up (see screenshot)

![image](https://github.com/user-attachments/assets/bdab5d62-fc9f-4560-88ea-849f6996b627)

### Reproduction

1. pip install langflow==1.0.15
2. python -m langflow run --env-file ./env
3. on the login screen, click on sign up

### Expected behavior

new user is supposed to be successfully signed up, and admin should be able to receive the new user form to activate it.

### Operating System

Ubuntu

### Langflow Version

1.0.15

### Python Version

3.10

**Comment by codenprogressive** [comment]
Yes, it's a bug that I start facing in v1.0.15. When I downgrade to v1.0.14, signing Up users works fine!

**Comment by codenprogressive** [comment]
Hey @italojohnny any chance you can reproduce the bug? Just wanted to confirm it is not something wrong with my configs! 

To the community, anyone else can reproduce this bug in v1.0.15?

**Comment by rezpablo** [comment]
I just went through the same problem, it occurred when signing up and also when accessing with admin and creating a new user.

**Comment by detodavide** [comment]
Yes, I have the same problem, and even with the latest version I can't log in using the login feature, while with version 1.0.14 I don't have these problems using the same .env.

ENV:
LANGFLOW_DATABASE_URL=postgresql://langflow:langflow@langflow_db:5432/langflow
DO_NOT_TRACK=true
LANGFLOW_AUTO_LOGIN=false
LANGFLOW_SUPERUSER="admin"
LANGFLOW_SUPERUSER_PASSWORD="securepassword"
LANGFLOW_SECRET_KEY="eandom_keyss"
AUTH_ACCESS_TOKEN_EXPIRE_MINUTES=-1
AUTH_REFRESH_TOKEN_EXPIRE_DAYS=-1
PYTHONUNBUFFERED=true

**Comment by codenprogressive** [comment]
@anovazzi1 any chance you can take a look at this issue?

**Comment by konradbjk** [comment]
Just leaving my ticket too :D https://github.com/langflow-ai/langflow/issues/3438

**Comment by carlosrcoelho** [comment]
#3471

**Comment by saheljalal** [comment]
How do you enable auth if deploying from the official docker images? I set these env vars but don't think they get picked up.
