### ISSUE TITLE
Cannot enlarge LLM output blocks in UI

### ISSUE THREAD

**Issue by konradbjk** [langflow-ai/langflow#3318]
### Bug Description

When I get a response from the LLM I cannot enrage the window to see the whole response

### Reproduction

Use some LLm output block

### Expected behavior

I am able to enlarge LLM output rsponse preview to see it in full

### Who can help?

 @anovazzi1  @Cristhianzl  @lucaseduoli @igorrCarvalho 

### Operating System

Ubuntu 24 LTS on Azure VM

### Langflow Version

1.0.15

### Python Version

3.12

### Screenshot

<img width="2196" alt="Screenshot 2024-08-14 at 01 22 44" src="https://github.com/user-attachments/assets/d46bf11b-7254-4936-96b6-120e650edf38">

**Comment by anovazzi1** [comment]
hello @konradbjk, thanks for the feedback, are you sure you are using the v1.0.15? I just tried this release on my linux machine with chrome and it worked:
![image](https://github.com/user-attachments/assets/3603950a-d150-42bb-8a73-3a932cc1674e)

**Comment by konradbjk** [comment]
I had to downgrade from v1.0.15 to v1.0.14 due to not working authentication in v1.0.15. My langflow instance has a public IP. I trust you will fix the authentication issue with 1.0.16 and then I can test the fix

**Comment by konradbjk** [comment]
I do not have 1.0.15 running anymore. I thought someone already would raise it

**Comment by anovazzi1** [comment]
ok, I will close this issue because it's already fixed. We will track the auth related issue on it's own issue

**Comment by codenprogressive** [comment]
@anovazzi1 there is an issue related to not be able to sign up new users. it is open here: [https://github.com/langflow-ai/langflow/issues/3313](https://github.com/langflow-ai/langflow/issues/3313)
can you please take a look?

**Comment by konradbjk** [comment]
https://github.com/langflow-ai/langflow/issues/3438 - in my case it is superuser
