### ISSUE TITLE
Langflow API error

### ISSUE THREAD

**Issue by carlosrcoelho** [langflow-ai/langflow#3320]
### Bug Description

`    "detail": "{\"message\":\"Error running graph: Error building Component OpenAI: \\n\\nError code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A**_KEY. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}\",\"traceback\":null,\"description\":null,\"code\":null,\"suggestion\":null}"`

`{
  "detail": "{\"message\":\"Error running graph: Error building Component OpenAI: \\n\\n1 validation error for SecretStrInput\\nvalue\\n  Value error, Invalid value type `<class 'NoneType'>` for input `api_key` [type=value_error, input_value=None, input_type=NoneType]\\n    For further information visit https://errors.pydantic.dev/2.8/v/value_error\",\"traceback\":null,\"description\":null,\"code\":null,\"suggestion\":null}"
}`

the error occurs regardless of if OPEN_AI_API_KEY is set—I've tried both ways

### Reproduction

Build Basic Prompting (Hello, World) 
Get the API

### Expected behavior

API code should work properly.

### Who can help?

@italojohnny

### Operating System

macOS 14.5

### Langflow Version

1.0.15

### Python Version

3.12

**Comment by italojohnny** [comment]
```
{
    "detail": "{"message":"Error running graph: Error building Component OpenAI:
        Error code: 401 - {
            'error': {
             'message': 'Incorrect API key provided: OPENAI_A**_KEY. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'
            }
        }
        ","traceback":null,"description":null,"code":null,"suggestion":null}"
}
```
In the first case, it seems that everything went well, however, the user appears to have provided an invalid API key for OpenAI.

...
```
{
  "detail": {
      "message":"Error running graph: Error building Component OpenAI: 1 validation error for SecretStrInput value
      Value error, Invalid value type `<class 'NoneType'>` for input `api_key` [type=value_error, input_value=None, input_type=NoneType]
      For further information visit https://errors.pydantic.dev/2.8/v/value_error","traceback":null,"description":null,"code":null,"suggestion":null}"
}
```
In the second case, it seems to be a more serious issue... apparently, the API key value is empty. I was able to reproduce the problem by manually deleting the value of the OPENAI_API_KEY using update variable set value = '';. This is clearly a misuse of the system. I would venture to say that the user tried to work around the problem by attempting various things and ended up leaving the value blank or something similar.

**Comment by italojohnny** [comment]
Additionally, there is a minor bug in the generation of the curl command that PR #3337 fixes. With this correction, everything worked perfectly in my tests
