### ISSUE TITLE
Wrong docker hub version tag

### ISSUE THREAD

**Issue by hakan-77** [langflow-ai/langflow#3321]
### Bug Description

The latest deployment uses version tag 0.0.93 instead of 1.0.15
https://hub.docker.com/r/langflowai/langflow-backend/tags
https://hub.docker.com/r/langflowai/langflow-frontend/tags

### Reproduction

Visit 
https://hub.docker.com/r/langflowai/langflow-backend/tags
https://hub.docker.com/r/langflowai/langflow-frontend/tags

### Expected behavior

tag is 1.0.15

### Who can help?

@ogabrielluiz 

### Operating System

Not relevant

### Langflow Version

1.0.15

### Python Version

None

**Comment by timoa** [comment]
I confirm that the images have the wrong tags. An easy fix will be to rename the Docker image tags to avoid confusion.

In the meantime, you can use the Docker images by changing the tag name on your Docker Compose or Helm Chart:

For `1.0.15` => `base-1.0.15` or `latest`
For `base-0.0.93` => `0.0.93` or `base-latest`

Using the `latest`/`base-latest` is a better option if the team rename the Docker image tags.

**Comment by konradbjk** [comment]
@timoa what is the difference between those two images? I can see a significant change in storage used

**Comment by italojohnny** [comment]
PR #3455 resolves this issue
