### ISSUE TITLE
Permanent loading login page after one day from the first deployment also in the last version 1.0.15

### ISSUE THREAD

**Issue by Frenz86** [langflow-ai/langflow#3325]
### Bug Description

permanet remain in loading.

I use this docker configurations file:
FROM langflowai/langflow:latest
USER root
RUN apt-get update && apt-get install -y 

# Set environment variables
# LANGFLOW_DATABASE_URL=postgresql://postgres:postgres@localhost:5432/langflow
ENV LANGFLOW_DATABASE_URL=sqlite:///./langflow.db
ENV PYTHONUNBUFFERED True
ENV PORT 80
ENV LANGFLOW_AUTO_LOGIN=false
ENV LANGFLOW_SUPERUSER=admin
ENV LANGFLOW_SUPERUSER_PASSWORD=password

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt
RUN pip install google-cloud-storage

USER user
WORKDIR /app

CMD python -m langflow run --host 0.0.0.0 --port $PORT

### Reproduction

At the begginning it works for one day, then I must to reboot the docker in order to make it works...

### Expected behavior

I expect the login works,
Many thanks

### Operating System

Ubuntu 22.04

### Langflow Version

1.0.15

### Python Version

3.11

### Screenshot

![loading](https://github.com/user-attachments/assets/f4928c82-ef0a-44eb-8e98-e0a5c5f14090)

**Comment by severfire** [comment]
did you test all browsers?
