### ISSUE TITLE
Langflow UI stuck on loading page while running flows

### ISSUE THREAD

**Issue by Warit314** [langflow-ai/langflow#3355]
### Bug Description

I'm using langflow with sqlite db and when i run other flows simutaneously (around 4-5 flows). The UI stuck on the loading page
![image](https://github.com/user-attachments/assets/3a9ac564-effd-408f-9dc3-dcb4676da65c)
****

### Reproduction

1. Run 4-5 flows
2. Got stuck on the loading page

### Expected behavior

I expect the langflow would be able to run flows simutaneously

### Who can help?

@italojohnny 

### Operating System

Linux

### Langflow Version

1.0.5

### Python Version

3.10

### Screenshot

![image](https://github.com/user-attachments/assets/a33175f6-ccf6-42ec-bb18-583cf6b1c6aa)

**Comment by Warit314** [comment]
@dosu can i config these in the .env file . Do i need to restart langflow after config?

**Comment by Warit314** [comment]
i still can't run other flow in paralell? is it because of sqlite? is there a solution to this?

**Comment by carlosrcoelho** [comment]
@Warit314 

Could you please share your flow?

**Comment by Warit314** [comment]
@carlosrcoelho 
[355_Llama3.1_Demo.json](https://github.com/user-attachments/files/16671296/355_Llama3.1_Demo.json)
It is a just a LLama 3.1 flows that make api calls to VLLM that's all. And i've been running this flow via langflow backend api

**Comment by Warit314** [comment]
@carlosrcoelho 
[355_Llama3.1_Demo.json](https://github.com/user-attachments/files/16671373/355_Llama3.1_Demo.json)

It is a just a LLama 3.1 flows that make api calls to VLLM that's all. And i've been running this flow via langflow backend api

**Comment by ogabrielluiz** [comment]
Hi @Warit314 

How are you? 

You should try using a more robust databse like PostgreSQL. SQLite might be locking the connection with this many workers

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
