### ISSUE TITLE
In the component code, I imported openai, but it does not work.

### ISSUE THREAD

**Issue by maxpaynebupt** [langflow-ai/langflow#3360]
### Bug Description

In the component code, I imported openai, but it does not work.
when I try to build it, an error "openai is not defined" appears.
![image](https://github.com/user-attachments/assets/d9ec1d3a-750f-4972-9399-2043bdf79f9b)
![image](https://github.com/user-attachments/assets/5c99d55e-4413-4fe1-ae57-e671b4ec44d8)

### Reproduction

1. In the code, import openai, and use it.
2. try to build it.

### Expected behavior

should build successfully.

### Operating System

Docker image v1.0.15

### Langflow Version

v1.0.15

### Python Version

None

**Comment by maxpaynebupt** [comment]
> To resolve the "openai is not defined" error, ensure that the `openai` module is properly imported in your code. It seems like you might need to import the `ChatOpenAI` class from the `langchain_openai` package instead. Here's an example of how to do it:
> 
> ```python
> import operator
> from functools import reduce
> from langchain_openai import ChatOpenAI  # Ensure this import is added
> from pydantic.v1 import SecretStr
> 
> from langflow.base.constants import STREAM_INFO_TEXT
> from langflow.base.models.model import LCModelComponent
> from langflow.base.models.openai_constants import MODEL_NAMES
> from langflow.field_typing import LanguageModel
> from langflow.inputs import (
>     BoolInput,
>     DictInput,
>     DropdownInput,
>     FloatInput,
>     IntInput,
>     MessageInput,
>     SecretStrInput,
>     StrInput,
> )
> from langflow.schema.message import Message
> from langflow.template import Output
> 
> 
> class OpenAIModelComponent(LCModelComponent):
>     display_name = "OpenAI"
>     description = "Generates text using OpenAI LLMs."
>     icon = "OpenAI"
> 
>     inputs = [
>         MessageInput(name="input_value", display_name="Input"),
>         IntInput(
>             name="max_tokens",
>             display_name="Max Tokens",
>             advanced=True,
>             info="The maximum number of tokens to generate. Set to 0 for unlimited tokens.",
>         ),
>         DictInput(name="model_kwargs", display_name="Model Kwargs", advanced=True),
>         DictInput(
>             name="output_schema",
>             is_list=True,
>             display_name="Schema",
>             advanced=True,
>             info="The schema for the Output of the model. You must pass the word JSON in the prompt. If left blank, JSON mode will be disabled.",
>         ),
>         DropdownInput(
>             name="model_name", display_name="Model Name", advanced=False, options=MODEL_NAMES, value=MODEL_NAMES[0]
>         ),
>         StrInput(
>             name="openai_api_base",
>             display_name="OpenAI API Base",
>             advanced=True,
>             info="The base URL of the OpenAI API. Defaults to https://api.openai.com/v1. You can change this to use other APIs like JinaChat, LocalAI and Prem.",
>         ),
>         SecretStrInput(
>             name="openai_api_key",
>             display_name="OpenAI API Key",
>             info="The OpenAI API Key to use for the OpenAI model.",
>             advanced=False,
>             value="OPENAI_API_KEY",
>         ),
>         FloatInput(name="temperature", display_name="Temperature", value=0.1),
>         BoolInput(name="stream", display_name="Stream", info=STREAM_INFO_TEXT, advanced=True),
>         StrInput(
>             name="system_message",
>             display_name="System Message",
>             info="System message to pass to the model.",
>             advanced=True,
>         ),
>         IntInput(
>             name="seed",
>             display_name="Seed",
>             info="The seed controls the reproducibility of the job.",
>             advanced=True,
>             value=1,
>         ),
>     ]
>     outputs = [
>         Output(display_name="Text", name="text_output", method="text_response"),
>         Output(display_name="Language Model", name="model_output", method="build_model"),
>     ]
> 
>     def text_response(self) -> Message:
>         input_value = self.input_value
>         stream = self.stream
>         system_message = self.system_message
>         output = self.build_model()
>         result = self.get_chat_result(output, stream, input_value, system_message)
>         self.status = result
>         return result
> 
>     def build_model(self) -> LanguageModel:
>         # self.output_schema is a list of dictionaries
>         # let's convert it to a dictionary
>         output_schema_dict = reduce(operator.ior, self.output_schema or {}, {})
>         openai_api_key = self.openai_api_key
>         temperature = self.temperature
>         model_name = self.model_name
>         max_tokens = self.max_tokens
>         model_kwargs = self.model_kwargs
>         openai_api_base = self.openai_api_base or "https://api.openai.com/v1"
>         json_mode = bool(output_schema_dict)
>         seed = self.seed
>         if openai_api_key:
>             api_key = SecretStr(openai_api_key)
>         else:
>             api_key = None
>         output = ChatOpenAI(
>             max_tokens=max_tokens or None,
>             model_kwargs=model_kwargs or {},
>             model=model_name,
>             base_url=openai_api_base,
>             api_key=api_key,
>             temperature=temperature or 0.1,
>             seed=seed,
>         )
>         if json_mode:
>             output = output.with_structured_output(schema=output_schema_dict, method="json_mode")
> 
>         return output
> ```
> 
> Make sure to install the `langchain_openai` package if you haven't already:
> 
> ```shell
> pip install langchain_openai
> ```
> 
> This should resolve the "openai is not defined" error [[1]](https://github.com/langflow-ai/langflow/blob/dev/src/backend/base/langflow/initial_setup/starter_projects/VectorStore-RAG-Flows.json).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

I just want to use openai package directly.

**Comment by maxpaynebupt** [comment]
> To resolve the "openai is not defined" error while using the `openai` package directly, ensure that the `openai` package is installed and properly imported in your code. Here is how you can modify your Dockerfile and Python code:
> 
> 1. **Update your Dockerfile to install the `openai` package:**
> 
> ```dockerfile
> FROM python:3.9-slim
> 
> # Install necessary packages
> RUN pip install openai
> 
> # Copy your application code
> COPY . /app
> 
> # Set the working directory
> WORKDIR /app
> 
> # Run your application
> CMD ["python", "your_script.py"]
> ```
> 
> 2. **Update your Python code to import and use the `openai` package:**
> 
> ```python
> import openai
> 
> # Your OpenAI API key
> api_key = "your_openai_api_key"
> 
> # Initialize the OpenAI API client
> openai.api_key = api_key
> 
> # Example function to use OpenAI API
> def get_openai_response(prompt):
>     response = openai.Completion.create(
>         engine="davinci",
>         prompt=prompt,
>         max_tokens=150
>     )
>     return response.choices[0].text.strip()
> 
> # Example usage
> prompt = "What is the capital of France?"
> response = get_openai_response(prompt)
> print(response)
> ```
> 
> Make sure to replace `"your_openai_api_key"` with your actual OpenAI API key and `"your_script.py"` with the name of your Python script. This should resolve the "openai is not defined" error and allow you to use the `openai` package directly in your project [[1]](https://github.com/logspace-ai/langflow/blob/dev/src/backend/base/langflow/initial_setup/starter_projects/Langflow Document QA.json).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

this openai package is already installed in the image, if I change it to some nonsense package, 'openai2', when I am trying to 'check&save', it can find that, 'Module openai2 not found.'

**Comment by carlosrcoelho** [comment]
@maxpaynebupt 
Do you need any assistance with this case? 

Are you making a custom component?

**Comment by maxpaynebupt** [comment]
> @maxpaynebupt Do you need any assistance with this case?
> 
> Are you making a custom component?

Finally, I made a custom embedding class and injected into the langchain_community dir.
