### ISSUE TITLE
cURL command in API section is not accurate

### ISSUE THREAD

**Issue by maxpaynebupt** [langflow-ai/langflow#3377]
### Bug Description

the example's output_type value should be quoted.

![image](https://github.com/user-attachments/assets/fd7a7598-662e-47ee-8d16-39c2680b6a57)

### Reproduction

setup a flow , and try to call it.

### Expected behavior

copy the command and paste it should be OK to run.

### Operating System

Docker image v1.0.15

### Langflow Version

v1.0.15

### Python Version

None

**Comment by uladkaminski** [comment]
Issue was recently fixed by https://github.com/langflow-ai/langflow/pull/3337

**Comment by carlosrcoelho** [comment]
#3337
