### ISSUE TITLE
outputs get mixed up

### ISSUE THREAD

**Issue by mieslep** [langflow-ai/langflow#3380]
### Bug Description

A CustomComponent has two input parameters and two output parameters that are "pass-through". They connect to another component but the output values do not correspond with the inputs. 
![image](https://github.com/user-attachments/assets/6cc89876-11c4-45af-b184-21cd03611b74)

### Reproduction

Create a custom component like this:

```
    inputs = [
        MessageTextInput(name="param1_in", display_name="Param 1"),
        MessageTextInput(name="param2_in", display_name="Param 2"),
    ]

    outputs = [
        Output(display_name="Param 1", name="param1_out", method="get_param1"),
        Output(display_name="Param 2", name="param2_out", method="get_param2"),
    ]

    def get_param1(self) -> Message:
        return self.param1_in

    def get_param2(self) -> Message:
        return self.param2_in
```

and duplicate that component. Connect the outputs of the first component to the corresponding inputs of the second component. 

Run the flow. The outputs of the second component are incorrect.

### Expected behavior

Param 1 input on first component should be the Param 1 output on the second component, and Param 2 input on the first component should be the Param 2 output on the second component. 

### Operating System

Windows 11

### Langflow Version

1.0.14

### Python Version

3.11

### Flow File

[Param Mixup.json](https://github.com/user-attachments/files/16637750/Param.Mixup.json)

**Comment by mieslep** [comment]
@dosu no I am finding this happens with a component with multiple inputs, For example:

```
    inputs = [
        MessageTextInput(name="base64_string", display_name="Base64 Encoded File", required=True, placeholder="Enter base64 encoded file string here..."),
        MessageTextInput(name="filename", display_name="Filename", required=True, placeholder="Enter filename with extension..."),
]

    outputs = [
        Output(display_name="Data", name="data", method="decode_and_load_file"),
    ]

    def decode_and_load_file(self) -> Data:

        if not self.base64_string:
            raise ValueError("Base64 string is empty. Please provide a valid base64 encoded file.")
        if not self.filename:
            raise ValueError("Filename is required.")

        base64_val = self.base64_string
        filename_val = self.filename 
```

The self.filename has the same value as self.base64_string, and if I reverse the input positions the base64_string has the filename value.

**Comment by severfire** [comment]
i had similar problem, but in my case, those custom components for all gave same message in output, only proxy (via Conversation component) helped me with that.
