### ISSUE TITLE
Unable to login langflow store. "Email already exists"

### ISSUE THREAD

**Issue by FellowTraveler** [langflow-ai/langflow#3390]
### Bug Description

I go to langflow store, and then I click to login with GITHUB.

Instead of logging me in, it says "email already exists."

No shit.

<img width="626" alt="image" src="https://github.com/user-attachments/assets/59055763-1574-4cef-a0dc-deb1841ee911">

### Reproduction

1. Go to langflow store
2. Click "Github"

### Expected behavior

I expected to be logged in.

### Operating System

MacOS Sonoma

### Langflow Version

1.0.15

### Python Version

3.12

### Screenshot

<img width="626" alt="image" src="https://github.com/user-attachments/assets/61557f83-0617-45d1-8b8d-a07a78c8b14a">

**Comment by FellowTraveler** [comment]
Okay I went ahead and logged in using the email / password directly. Just to make sure I had the password right, I changed the password.
But I still can't login, I get this message:

<img width="591" alt="image" src="https://github.com/user-attachments/assets/d39091e3-51a1-4631-b616-5168f08c6636">

**Comment by FellowTraveler** [comment]
Hmm I'm not running langflow locally currently. All I did was try to login to langflow.store
Are you saying I have to have langflow running locally before I can login to the store?

**Comment by anovazzi1** [comment]
@FellowTraveler how are you? Can you please check if you have not already used the google provider with this email before?

**Comment by carlosrcoelho** [comment]
@FellowTraveler 

Do you need any assistance with this case? If not, please let us know if this issue can be closed.
