### ISSUE TITLE
Error building Component Astra DB:   Error initializing AstraDBVectorStore: {"errors":[{"message":"Request invalid: field 'command.name' value `null` not valid. Problem: must not be null.","errorCode":"COMMAND_FIELD_INVALID"}]}

### ISSUE THREAD

**Issue by Nkurayijahubert** [langflow-ai/langflow#3393]
### Bug Description

This error is happening when I export the flow JSON trying to run it on my application.

### Reproduction

from langflow.load import run_flow_from_json
TWEAKS = {
  "ChatInput-UuJgn": {},
  "AstraVectorStoreComponent-2mwWS": {},
  "ParseData-M3W6Z": {},
  "Prompt-dt6pd": {},
  "ChatOutput-R5l9b": {},
  "SplitText-PbqQD": {},
  "File-N0Za6": {},
  "OpenAIModel-LYQTz": {},
  "Memory-u45lJ": {},
  "OpenAIEmbeddings-ZAXxT": {}
}

result = run_flow_from_json(flow="Vector_Store_RAG.json",
                            input_value="message",
                            fallback_to_env_vars=True, # False by default
                            tweaks=TWEAKS)

### Expected behavior

I would expect to run the flow in my Django external application.

### Operating System

Macbook Sonoma 14.2

### Langflow Version

1.0.14

### Python Version

3.10

**Comment by Nkurayijahubert** [comment]
@dosu There many places with "template": {}

**Comment by Nkurayijahubert** [comment]
@dosu the error persist

**Comment by jordanrfrazier** [comment]
Hi @Nkurayijahubert, can you please share the exact steps you took? 

I just tested that I was able to export the `Vector Store RAG` example and run it locally on my machine via the `run_flow_from_json` function. Attached is the json I used, and the code to run it. Plmk if that works for you, then we can figure out if anything is different in your environment.

```
from langflow.load import run_flow_from_json
TWEAKS = {
  "ChatInput-iaJtf": {},
  "AstraVectorStoreComponent-rd8LL": {
      "token": "<insert token>",
      "api_endpoint": "<insert endpoint>"
      },
  "ParseData-aybR0": {},
  "Prompt-jCJmL": {},
  "ChatOutput-JP4os": {},
  "SplitText-CQxrN": {},
  "File-IlhlA": {},
  "AstraVectorStoreComponent-7hUKp": {},
  "OpenAIEmbeddings-l7Jz2": {},
  "OpenAIEmbeddings-6YrUm": {},
  "OpenAIModel-W43IT": {}
}
# and I just exported `OPENAI_API_KEY` in the terminal I was running this from

result = run_flow_from_json(flow="test_rag.json",
                            input_value="message",
                            fallback_to_env_vars=True, # False by default
                            tweaks=TWEAKS)

print(result)
```

[test_rag.json](https://github.com/user-attachments/files/16669842/test_rag.json)

**Comment by Nkurayijahubert** [comment]
Hi @jordanrfrazier these are the steps I am taking:

# Load the flow from a JSON file
flow_file = "vector_store.json"

TWEAKS = {
  "File-x63LT": {},
  "SplitText-fRVmN": {},
  "OpenAIEmbeddings-rU5oN": {
    "openai_api_key": os.getenv("OPENAI_API_KEY"),
  },
  "AstraDB-305Eo": {
      "api_endpoint": os.getenv("ASTRA_DB_API_ENDPOINT"),
      "token": os.getenv("ASTRA_DB_APPLICATION_TOKEN"),
  },
  "ChatInput-bLV8x": {},
  "ParseData-7oE65": {},
  "Prompt-z6UsK": {},
  "Memory-re2mi": {},
  "OpenAIModel-ul65C": {
      "api_key": os.getenv("OPENAI_API_KEY"),
  },
  "ChatOutput-4YOYF": {},
}

flow = run_flow_from_json(flow=flow_file,
                            input_value="Hello, what is the capital of France?",
                            fallback_to_env_vars=True, # False by default
                            tweaks=TWEAKS)

**Comment by jordanrfrazier** [comment]
@Nkurayijahubert can you please attach your flow json file here, and I'll try running and debugging on my end tomorrow

**Comment by Nkurayijahubert** [comment]
Here it is @jordanrfrazier 

[vector_store.json](https://github.com/user-attachments/files/16670835/vector_store.json)

**Comment by jordanrfrazier** [comment]
Hi @Nkurayijahubert sorry for the late response. I was able to download and run your given JSON file, though I did re-upload the flow into a locally running langflow in order to verify the ID's of the components were correct for the TWEAKS. 

Can you please try to
* Run the latest langflow
* Upload your json file 
* Verify your `TWEAKS` component IDs are correct, taken from the `</> API` button 
* Re-download your json and try running locally again.

**Comment by carlosrcoelho** [comment]
@Nkurayijahubert 
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.

**Comment by pascal-maker** [comment]
@dosu i'm trying to run a query in langflow and i receive the following error: Error details:
ValueError
Details: Error initializing AstraDBVectorStore: Server internal error: Missing/Invalid authentication credentials provided for type: astra

**Comment by jordanrfrazier** [comment]
![Image](https://github.com/user-attachments/assets/60c16138-9a97-43eb-8f17-a9f6ee444af8)

Hi @pascal-maker, please make sure that the AstraCS Token you are using has the necessary permissions. You may want to just try creating a token with Administrator User permissions to ensure it is being used correctly.
