### ISSUE TITLE
Only one output of custom component works, it will overwrite the others.

### ISSUE THREAD

**Issue by maxpaynebupt** [langflow-ai/langflow#3406]
### Bug Description

I set up a custom component to extract the input JSON to two fields, one is the 'question' , the other is 'schema', in the GUI, when I try to build it, I can see the two output data , but if I try to use it at some other nodes, the two value become the same.

### Reproduction

1. setup a custom component, which output two fields.
2.  use the output data in the prompt template.
3. try to send the prompted msg to llm
4.  the msg is wrongly constructed.

### Expected behavior

two values should be different.

### Operating System

Windows 11

### Langflow Version

v1.0.14

### Python Version

3.10

### Screenshot

![image](https://github.com/user-attachments/assets/8f40b2be-db40-435e-882d-5aaaf4745941)
question:
![image](https://github.com/user-attachments/assets/d6833acb-0183-4387-9722-053b027c7fe1)
schema:
![image](https://github.com/user-attachments/assets/e2837efb-8eb3-4e74-afa1-6373b0342080)
prompt template:
![image](https://github.com/user-attachments/assets/762e4e00-e2a7-4559-98bc-1445fcad61f0)
prompted msg:
![image](https://github.com/user-attachments/assets/bdf0ae6f-d63f-4518-9bb3-1d514a04951a)

**Comment by severfire** [comment]
oh, my old issue, try passing it through 'proxy', funny thing will happen :-) through this proxy you should get normal content, i hope

`from langflow.custom import Component
from langflow.inputs import MultilineInput
from langflow.template import Output, Input
from langflow.io import MessageTextInput, Output

from langflow.schema.message import Message

class ProxyComponent(Component):
    display_name = "Proxy"
    description = "Text Proxy Component"
    icon = "text"
    name = "ProxyComponent"
        
    inputs = [
        MultilineInput(
            name="text_proxy",
            display_name="Text",
            required=True,
        )
    ]

    outputs = [
        Output(display_name="Result", name="result", method="process_inputs"),
    ]

    def process_inputs(self) -> Message:
        message = Message(
            text=self.text_proxy,
        )
        return message`

**Comment by carlosrcoelho** [comment]
@maxpaynebupt 

Do you need any assistance with this case? If not, please let us know if this issue can be closed.

**Comment by maxpaynebupt** [comment]
> @maxpaynebupt
> 
> Do you need any assistance with this case? If not, please let us know if this issue can be closed.

Now, I made a copy of the extractor, I think this is a bug, I should be fixed, and , if we can output the text to some chat level variable, that would be much more better.

**Comment by carlosrcoelho** [comment]
@maxpaynebupt @severfire 

Hey, the new version 1.0.16 is out. Please test it and let me know if there's any issue.

**Comment by maxpaynebupt** [comment]
> @maxpaynebupt @severfire
> 
> Hey, the new version 1.0.16 is out. Please test it and let me know if there's any issue.

start to try the new version, found that, in the 1.0.16 backend docker image, the package psycopg2-binary is not installed, this caused the service failed to start, after I installed it, the service can start now.

**Comment by maxpaynebupt** [comment]
> @maxpaynebupt @severfire
> 
> Hey, the new version 1.0.16 is out. Please test it and let me know if there's any issue.

And, the output variable overwrite issue is fixed,👍
