### ISSUE TITLE
Flow works in Playground but fails when called from Webhook

### ISSUE THREAD

**Issue by Gluepower** [langflow-ai/langflow#3407]
### Bug Description

Flow works great when run in playground. However, when called from HTTP POST Request from n8n it fails. n8n gives this message that is successful
![image](https://github.com/user-attachments/assets/f004adc9-8d35-45c2-b209-248e99869e35)

### Reproduction

[Untitled document (1).txt](https://github.com/user-attachments/files/16645649/Untitled.document.1.txt)
Log is too large to copy here so attaching as file.

### Expected behavior

If flow can be executed in playground, why calling the same flow via HTTP post creates all these problems?

### Operating System

Render

### Langflow Version

1.0.15

### Python Version

3.12

**Comment by Gluepower** [comment]
@anovazzi1 I figured from those logs that most of the errors are because I am using subflow. For some reason subflow is not executing correctly when flow is called from webhook. I tried to put everything into a single flow without any subflows, however there is one issue remaining. In other words, still not working. Subflow errors are gone as I am not using subflow , but this one with OpenAI secret string being null value is still here. I have updated to 1.0.16

![image](https://github.com/user-attachments/assets/019d8a1a-bb58-49cb-9ab6-3c2c08651fb8)

**Comment by anovazzi1** [comment]
hey @Gluepower, sorry for the delay, did you manage to fix that? can you provide the flow for local debugging? I think it's related to langchain dependencie version, but it's a initial guess. About the subflow we are working on fix it, but i  would say to avoid use it in production rn

**Comment by ogabrielluiz** [comment]
This is related to the global variables
