### ISSUE TITLE
Cannot delete a flow with message history on Postgresql due to ForeignKeyViolation

### ISSUE THREAD

**Issue by hakan-77** [langflow-ai/langflow#3415]
### Bug Description

Cannot delete a flow with message history on Postgresql due to ForeignKeyViolation

### Reproduction

1- Use langflow with postgresql
2- Create a flow
3- Use playground
4- Delete flow gets a generic error. Javascript console prints:

{"message":"(psycopg2.errors.ForeignKeyViolation) update or delete on table \"flow\" violates foreign key constraint \"message_flow_id_fkey\" on table \"message\"\nDETAIL:  Key (id)=(33e0480a-77b8-4636-b08f-ab4f40eb1284) is still referenced from table \"message\".\n\n[SQL: DELETE FROM flow WHERE flow.id = %(id_1)s::UUID]\n[parameters: {'id_1': '33e0480a-77b8-4636-b08f-ab4f40eb1284'}]\n(Background on this error at: https://sqlalche.me/e/20/gkpj)"}

### Expected behavior

Option 1) Cascading delete: deleting a flow deletes all related rows on all related history tables (ideal)
Option 2) Notify to user to manually delete all related content first.

### Operating System

Ubuntu 22.04

### Langflow Version

1.0.14

### Python Version

3.10

**Comment by carlosrcoelho** [comment]
@hakan-77 

Could you try on version 1.0.15 and check if persists?
