### ISSUE TITLE
Issue: Pydantic - Portainer - Docker Swarm (PydanticDeprecatedSince20)

### ISSUE THREAD

**Issue by MarecoX** [langflow-ai/langflow#3417]
### Bug Description

Obs: I'm using Python 3.10.0

I'm trying to install Langflow on a portainer with docker swarm, however an error is appearing in the log that doesn't allow me to open the system.

### Reproduction

1. My Stack
```
version: "3.8"

services:
  langflow:
    image: langflowai/langflow:latest
    user: root
    depends_on:
      - postgres # Dependência no seu banco de dados existente
    volumes:
      - langflow_data:/var/lib/langflow
    networks:
      -  minha_rede
    environment:
      # Altere os dados do Banco de dados
      - LANGFLOW_DATABASE_URL=postgresql://postgres:xxxxxxxxxxx@postgres:5432/langflow
      # Segurança
      - LANGFLOW_SUPERUSER=xxxxxxxxx #crie o usuário de acesso
      - LANGFLOW_SUPERUSER_PASSWORD=xxxxxxxx #crie a senha de acesso
      - LANGFLOW_NEW_USER_IS_ACTIVE=true # Mude para false após o primeiro login
      - LANGFLOW_AUTO_LOGIN=false
      # Outros
      - LANGFLOW_CONFIG_DIR=/var/lib/langflow
      - BACKEND_URL=langflow.domain.com.br 
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
        #analise os limites porque o Langflow consome bastante
          cpus: "1" 
          memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.langflow.rule=Host(langflow.domain.com.br)
        - traefik.http.routers.langflow.entrypoints=websecure
        - traefik.http.routers.langflow.tls.certresolver=letsencryptresolver
        - traefik.http.routers.langflow.service=langflow
        - traefik.http.services.langflow.loadbalancer.server.port=7860

volumes:
  langflow_data:
    external: true

networks:
  minha_rede:
    external: true
```

2. Log
```
Starting Langflow v1.0.15...
/app/.venv/lib/python3.12/site-packages/pysbd/segmenter.py:66: SyntaxWarning: invalid escape sequence '\s'
  for match in re.finditer('{0}\s*'.format(re.escape(sent)), self.original_text):
/app/.venv/lib/python3.12/site-packages/pysbd/lang/arabic.py:29: SyntaxWarning: invalid escape sequence '\.'
  txt = re.sub('(?<={0})\.'.format(am), '∯', txt)
/app/.venv/lib/python3.12/site-packages/pysbd/lang/persian.py:29: SyntaxWarning: invalid escape sequence '\.'
  txt = re.sub('(?<={0})\.'.format(am), '∯', txt)
/app/.venv/lib/python3.12/site-packages/pydantic/_internal/_config.py:291: PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.8/migration/
  warnings.warn(DEPRECATION_MESSAGE, DeprecationWarning)
/app/.venv/lib/python3.12/site-packages/pydantic/_internal/_config.py:291: PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.8/migration/
  warnings.warn(DEPRECATION_MESSAGE, DeprecationWarning)
/app/.venv/lib/python3.12/site-packages/litellm/utils.py:107: DeprecationWarning: open_text is deprecated. Use files() instead. Refer to https://importlib-resources.readthedocs.io/en/latest/using.html#migrating-from-legacy for migration advice.
  with resources.open_text("litellm.llms.tokenizers", "anthropic_tokenizer.json") as f:
[08/19/24 00:09:28] ERROR    2024-08-19 00:09:28 - ERROR    - setup setup.py:580
                             - Edge between Component and                       
                             CrewAIAgentComponent has invalid                   
                             handles                                            
[08/19/24 00:09:28] ERROR    2024-08-19 00:09:28 - ERROR    - setup setup.py:580
                             - Edge between Component and                       
                             CrewAIAgentComponent has invalid                   
                             handles                                            
[08/19/24 00:09:28] ERROR    2024-08-19 00:09:28 - ERROR    - setup setup.py:580
                             - Edge between Component and                       
                             CrewAIAgentComponent has invalid                   
                             handles                                            
╭───────────────────────────────────────────────────────────────────╮
│ Welcome to ⛓ Langflow                                             │
│                                                                   │
│                                                                   │
│ Collaborate, and contribute at our GitHub Repo 🌟                 │
│                                                                   │
│ We collect anonymous usage data to improve Langflow.              │
│ You can opt-out by setting DO_NOT_TRACK=true in your environment. │
│                                                                   │
│ Access http://0.0.0.0:7860                                        │
╰───────────────────────────────────────────────────────────────────╯
```
### Expected behavior

Access granted to the service

### Who can help?

@italojohnny

### Operating System

Ubuntu Linux 20.04.06

### Langflow Version

v1.0.15

### Python Version

3.10

### Screenshot

![image](https://github.com/user-attachments/assets/8ddfc8dd-43d6-4064-a6b3-c798c59a7f6b)

**Comment by MarecoX** [comment]
I managed to create the dockerfile (marsllator/langflow:latest), now this is showing in the log:

Starting Langflow v1.0.15...
[08/19/24 03:24:32] ERROR    2024-08-19 03:24:32 - ERROR    - main - main.py:103
                             No module named 'psycopg2'                         
[08/19/24 03:24:33] ERROR    2024-08-19 03:24:33 - ERROR    -   __init__.py:1762
                             __init__ - Traceback (most recent                  
                             call last):                                        
                               File                                             
                             "/app/.venv/lib/python3.12/site-pa                 
                             ckages/starlette/routing.py", line                 
                             732, in lifespan                                   
                                 async with                                     
                             self.lifespan_context(app) as                      
                             maybe_state:                                       
                               File                                             
                             "/usr/local/lib/python3.12/context                 
                             lib.py", line 210, in __aenter__                   
                                 return await anext(self.gen)                   
                                        ^^^^^^^^^^^^^^^^^^^^^                   
                               File                                             
                             "/app/.venv/lib/python3.12/site-pa                 
                             ckages/langflow/main.py", line 92,                 
                             in lifespan                                        
                                 initialize_services(fix_migrat                 
                             ion=fix_migration,                                 
                             socketio_server=socketio_server)                   
                               File                                             
                             "/app/.venv/lib/python3.12/site-pa                 
                             ckages/langflow/services/utils.py"                 
                             , line 167, in initialize_services                 
                                 raise exc                                      
                               File                                             
                             "/app/.venv/lib/python3.12/site-pa                 
                             ckages/langflow/services/utils.py"                 
                             , line 165, in initialize_services                 
                                 initialize_database(fix_migrat                 
                             ion=fix_migration)                                 
                               File                                             
                             "/app/.venv/lib/python3.12/site-pa                 
                             ckages/langflow/services/database/                 
                             utils.py", line 93, in                             
                             initialize_database                                
                                 database_service:                              
                             "DatabaseService" =                                
                             get_db_service()                                   
                                                                                
                                     ^^^^^^^^^^^^^^^^                           
                               File                                             
                             "/app/.venv/lib/python3.12/site-pa                 
                             ckages/langflow/services/deps.py",                 
                              line 154, in get_db_service                       
                                 return                                         
                             get_service(ServiceType.DATABASE_S                 
                             ERVICE, DatabaseServiceFactory())                  
                             # type: ignore                                     
                                        ^^^^^^^^^^^^^^^^^^^^^^^                 
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                 
                             ^^^^^^^^^^                                         
                               File                                             
                             "/app/.venv/lib/python3.12/site-pa                 
                             ckages/langflow/services/deps.py",                 
                              line 43, in get_service                           
                                 return                                         
                             service_manager.get(service_type,                  
                             default)  # type: ignore                           
                                        ^^^^^^^^^^^^^^^^^^^^^^^                 
                             ^^^^^^^^^^^^^^^^^^^                                
                               File                                             
                             "/app/.venv/lib/python3.12/site-pa                 
                             ckages/langflow/services/manager.p                 
                             y", line 57, in get                                
                                 self._create_service(service_n                 
                             ame, default)                                      
                               File                                             
                             "/app/.venv/lib/python3.12/site-pa                 
                             ckages/langflow/services/manager.p                 
                             y", line 81, in _create_service                    
                                 self.services =                                
                             self.factories.create(**dependent_                 
                             services)                                          
                                                                                
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                 
                             ^^^^^^^^^^^^^^^^^^^^^^^                            
                               File                                             
                             "/app/.venv/lib/python3.12/site-pa                 
                             ckages/langflow/services/database/                 
                             factory.py", line 18, in create                    
                                 return                                         
                             DatabaseService(settings_service)                  
                                        ^^^^^^^^^^^^^^^^^^^^^^^                 
                             ^^^^^^^^^^                                         
                               File                                             
                             "/app/.venv/lib/python3.12/site-pa                 
                             ckages/langflow/services/database/                 
                             service.py", line 46, in __init__                  
                                 self.engine =                                  
                             self._create_engine()                              
                                               ^^^^^^^^^^^^^^^^                 
                             ^^^^^                                              
                               File                                             
                             "/app/.venv/lib/python3.12/site-pa                 
                             ckages/langflow/services/database/                 
                             service.py", line 61, in                           
                             _create_engine                                     
                                 return create_engine(                          
                                        ^^^^^^^^^^^^^^                          
                               File "<string>", line 2, in                      
                             create_engine                                      
                               File                                             
                             "/app/.venv/lib/python3.12/site-pa                 
                             ckages/sqlalchemy/util/deprecation                 
                             s.py", line 281, in warned                         
                                 return fn(*args, **kwargs)  #                  
                             type: ignore                                       
                                        ^^^^^^^^^^^^^^^^^^^                     
                               File                                             
                             "/app/.venv/lib/python3.12/site-pa                 
                             ckages/sqlalchemy/engine/create.py                 
                             ", line 599, in create_engine                      
                                 dbapi =                                        
                             dbapi_meth(**dbapi_args)                           
                                         ^^^^^^^^^^^^^^^^^^^^^^                 
                             ^^                                                 
                               File                                             
                             "/app/.venv/lib/python3.12/site-pa                 
                             ckages/sqlalchemy/dialects/postgre                 
                             sql/psycopg2.py", line 690, in                     
                             import_dbapi                                       
                                 import psycopg2                                
                             ModuleNotFoundError: No module                     
                             named 'psycopg2'                                   
                                                                                
                    ERROR    2024-08-19 03:24:33 - ERROR    -   __init__.py:1762
                             __init__ - Application startup                     
                             failed. Exiting.                                   
[08/19/24 03:24:33] ERROR    2024-08-19 03:24:33 - ERROR    -   __init__.py:1762
                             __init__ - Worker (pid:17) exited                  
                             with code 3                                        
                    ERROR    2024-08-19 03:24:33 - ERROR    -   __init__.py:1762
                             __init__ - Shutting down: Master                   
                    ERROR    2024-08-19 03:24:33 - ERROR    -   __init__.py:1762
                             __init__ - Reason: Worker failed                   
                             to boot.

**Comment by italojohnny** [comment]
Hi, my friend.

As I mentioned in Issue #3416, these warning messages, although annoying, are not actually the problem.

In your case, I made some modifications to the docker-compose.yml, and it worked for me. Could you test it and let me know if it works for you?

Here’s the content of the file:
```
services:
  langflow:
    container_name: langflow
    image: langflowai/langflow:latest
    user: root
    depends_on:
      - postgres # Dependência no seu banco de dados existente
    ports:
      - "7860:7860"
    volumes:
      - langflow_data:/var/lib/langflow
    networks:
      -  minha_rede
    environment:
      # Altere os dados do Banco de dados
      - LANGFLOW_DATABASE_URL=postgresql://langflow:langflow@postgres:5432/langflow
      # Segurança
      - LANGFLOW_SUPERUSER=langflow #crie o usuário de acesso
      - LANGFLOW_SUPERUSER_PASSWORD=langflow #crie a senha de acesso
      - LANGFLOW_NEW_USER_IS_ACTIVE=true # Mude para false após o primeiro login
      - LANGFLOW_AUTO_LOGIN=false
      # Outros
      - LANGFLOW_CONFIG_DIR=/var/lib/langflow
      - BACKEND_URL=langflow.domain.com.br
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
        #analise os limites porque o Langflow consome bastante
          cpus: "1"
          memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.langflow.rule=Host(langflow.domain.com.br)
        - traefik.http.routers.langflow.entrypoints=websecure
        - traefik.http.routers.langflow.tls.certresolver=letsencryptresolver
        - traefik.http.routers.langflow.service=langflow
        - traefik.http.services.langflow.loadbalancer.server.port=7860

  postgres:
    container_name: postgres
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: langflow
      POSTGRES_PASSWORD: langflow
      POSTGRES_DB: langflow
    ports:
      - "5432:5432"
    volumes:
      - langflow_data:/var/lib/postgresql/data
    networks:
      -  minha_rede

volumes:
  langflow_data:
    external: true

networks:
  minha_rede:
    external: true
```

**Comment by MarecoX** [comment]
It returned the same thing:

![image](https://github.com/user-attachments/assets/72ec6287-dccf-4d1e-9211-238c4f1c72fd)


     
Starting Langflow v1.0.15...
/app/.venv/lib/python3.12/site-packages/pysbd/segmenter.py:66: SyntaxWarning: invalid escape sequence '\s'
  for match in re.finditer('{0}\s*'.format(re.escape(sent)), self.original_text):
/app/.venv/lib/python3.12/site-packages/pysbd/lang/arabic.py:29: SyntaxWarning: invalid escape sequence '\.'
  txt = re.sub('(?<={0})\.'.format(am), '∯', txt)
/app/.venv/lib/python3.12/site-packages/pysbd/lang/persian.py:29: SyntaxWarning: invalid escape sequence '\.'
  txt = re.sub('(?<={0})\.'.format(am), '∯', txt)
/app/.venv/lib/python3.12/site-packages/pydantic/_internal/_config.py:291: PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.8/migration/
  warnings.warn(DEPRECATION_MESSAGE, DeprecationWarning)
/app/.venv/lib/python3.12/site-packages/pydantic/_internal/_config.py:291: PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.8/migration/
  warnings.warn(DEPRECATION_MESSAGE, DeprecationWarning)
/app/.venv/lib/python3.12/site-packages/litellm/utils.py:107: DeprecationWarning: open_text is deprecated. Use files() instead. Refer to https://importlib-resources.readthedocs.io/en/latest/using.html#migrating-from-legacy for migration advice.
  with resources.open_text("litellm.llms.tokenizers", "anthropic_tokenizer.json") as f:
[08/22/24 08:41:46] ERROR    2024-08-22 08:41:46 - ERROR    - setup setup.py:580
                             - Edge between Component and                       
                             CrewAIAgentComponent has invalid                   
                             handles                                            
[08/22/24 08:41:46] ERROR    2024-08-22 08:41:46 - ERROR    - setup setup.py:580
                             - Edge between Component and                       
                             CrewAIAgentComponent has invalid                   
                             handles                                            
[08/22/24 08:41:46] ERROR    2024-08-22 08:41:46 - ERROR    - setup setup.py:580
                             - Edge between Component and                       
                             CrewAIAgentComponent has invalid                   
                             handles                                            
╭───────────────────────────────────────────────────────────────────╮
│ Welcome to ⛓ Langflow                                             │
│                                                                   │
│                                                                   │
│ Collaborate, and contribute at our GitHub Repo 🌟                 │
│                                                                   │
│ We collect anonymous usage data to improve Langflow.              │
│ You can opt-out by setting DO_NOT_TRACK=true in your environment. │
│                                                                   │
│ Access http://0.0.0.0:7860                                        │
╰───────────────────────────────────────────────────────────────────╯

**Comment by italojohnny** [comment]
Despite the messages, are you able to run your flows?

**Comment by MarecoX** [comment]
I can't, error 404

**Comment by MarecoX** [comment]
![image](https://github.com/user-attachments/assets/b37e0d40-9bcf-4d8a-a693-f0c5e44e93fc)
![image](https://github.com/user-attachments/assets/e9cbfcdc-7aa4-45de-92be-6e1513013dab)

There are only these logs:

![image](https://github.com/user-attachments/assets/20d1a733-65d2-4ca4-9a92-aa9cebf56c0c)

Starting Langflow v1.0.16...
[08/23/24 06:46:25] ERROR    2024-08-23 06:46:25 - ERROR    - main - main.py:103
                             No module named 'psycopg2'                         
                    ERROR    2024-08-23 06:46:25 - ERROR    -   __init__.py:1762
                             __init__ - Traceback (most recent                  
                             call last):                                        
                               File                                             
                             "/app/.venv/lib/python3.12/site-pa                 
                             ckages/starlette/routing.py", line                 
                             732, in lifespan                                   
                                 async with                                     
                             self.lifespan_context(app) as                      
                             maybe_state:                                       
                               File                                             
                             "/usr/local/lib/python3.12/context                 
                             lib.py", line 210, in __aenter__                   
                                 return await anext(self.gen)                   
                                        ^^^^^^^^^^^^^^^^^^^^^                   
                               File                                             
                             "/app/.venv/lib/python3.12/site-pa                 
                             ckages/langflow/main.py", line 92,                 
                             in lifespan                                        
                                 initialize_services(fix_migrat                 
                             ion=fix_migration,                                 
                             socketio_server=socketio_server)                   
                               File                                             
                             "/app/.venv/lib/python3.12/site-pa                 
                             ckages/langflow/services/utils.py"                 
                             , line 167, in initialize_services                 
                                 raise exc                                      
                               File                                             
                             "/app/.venv/lib/python3.12/site-pa                 
                             ckages/langflow/services/utils.py"                 
                             , line 165, in initialize_services                 
                                 initialize_database(fix_migrat                 
                             ion=fix_migration)                                 
                               File                                             
                             "/app/.venv/lib/python3.12/site-pa                 
                             ckages/langflow/services/database/                 
                             utils.py", line 93, in                             
                             initialize_database                                
                                 database_service:                              
                             "DatabaseService" =                                
                             get_db_service()                                   
                                                                                
                                     ^^^^^^^^^^^^^^^^                           
                               File                                             
                             "/app/.venv/lib/python3.12/site-pa                 
                             ckages/langflow/services/deps.py",                 
                              line 154, in get_db_service                       
                                 return                                         
                             get_service(ServiceType.DATABASE_S                 
                             ERVICE, DatabaseServiceFactory())                  
                             # type: ignore                                     
                                        ^^^^^^^^^^^^^^^^^^^^^^^                 
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                 
                             ^^^^^^^^^^                                         
                               File                                             
                             "/app/.venv/lib/python3.12/site-pa                 
                             ckages/langflow/services/deps.py",                 
                              line 43, in get_service                           
                                 return                                         
                             service_manager.get(service_type,                  
                             default)  # type: ignore                           
                                        ^^^^^^^^^^^^^^^^^^^^^^^                 
                             ^^^^^^^^^^^^^^^^^^^                                
                               File                                             
                             "/app/.venv/lib/python3.12/site-pa                 
                             ckages/langflow/services/manager.p                 
                             y", line 57, in get                                
                                 self._create_service(service_n                 
                             ame, default)                                      
                               File                                             
                             "/app/.venv/lib/python3.12/site-pa                 
                             ckages/langflow/services/manager.p                 
                             y", line 81, in _create_service                    
                                 self.services =                                
                             self.factories.create(**dependent_                 
                             services)                                          
                                                                                
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                 
                             ^^^^^^^^^^^^^^^^^^^^^^^                            
                               File                                             
                             "/app/.venv/lib/python3.12/site-pa                 
                             ckages/langflow/services/database/                 
                             factory.py", line 18, in create                    
                                 return                                         
                             DatabaseService(settings_service)                  
                                        ^^^^^^^^^^^^^^^^^^^^^^^                 
                             ^^^^^^^^^^                                         
                               File                                             
                             "/app/.venv/lib/python3.12/site-pa                 
                             ckages/langflow/services/database/                 
                             service.py", line 46, in __init__                  
                                 self.engine =                                  
                             self._create_engine()                              
                                               ^^^^^^^^^^^^^^^^                 
                             ^^^^^                                              
                               File                                             
                             "/app/.venv/lib/python3.12/site-pa                 
                             ckages/langflow/services/database/                 
                             service.py", line 64, in                           
                             _create_engine                                     
                                 return create_engine(                          
                                        ^^^^^^^^^^^^^^                          
                               File "<string>", line 2, in                      
                             create_engine                                      
                               File                                             
                             "/app/.venv/lib/python3.12/site-pa                 
                             ckages/sqlalchemy/util/deprecation                 
                             s.py", line 281, in warned                         
                                 return fn(*args, **kwargs)  #                  
                             type: ignore                                       
                                        ^^^^^^^^^^^^^^^^^^^                     
                               File                                             
                             "/app/.venv/lib/python3.12/site-pa                 
                             ckages/sqlalchemy/engine/create.py                 
                             ", line 599, in create_engine                      
                                 dbapi =                                        
                             dbapi_meth(**dbapi_args)                           
                                         ^^^^^^^^^^^^^^^^^^^^^^                 
                             ^^                                                 
                               File                                             
                             "/app/.venv/lib/python3.12/site-pa                 
                             ckages/sqlalchemy/dialects/postgre                 
                             sql/psycopg2.py", line 690, in                     
                             import_dbapi                                       
                                 import psycopg2                                
                             ModuleNotFoundError: No module                     
                             named 'psycopg2'                                   
                                                                                
                    ERROR    2024-08-23 06:46:25 - ERROR    -   __init__.py:1762
                             __init__ - Application startup                     
                             failed. Exiting.                                   
[08/23/24 06:46:25] ERROR    2024-08-23 06:46:25 - ERROR    -   __init__.py:1762
                             __init__ - Worker (pid:17) exited                  
                             with code 3                                        
                    ERROR    2024-08-23 06:46:25 - ERROR    -   __init__.py:1762
                             __init__ - Shutting down: Master                   
                    ERROR    2024-08-23 06:46:25 - ERROR    -   __init__.py:1762
                             __init__ - Reason: Worker failed                   
                             to boot.

**Comment by MarecoX** [comment]
It keeps giving the same error:

    
Starting Langflow v1.0.16...
[08/23/24 20:26:29] ERROR    2024-08-23 20:26:29 - ERROR    - main - main.py:103
                             No module named 'psycopg2'                         
                    ERROR    2024-08-23 20:26:29 - ERROR    -   __init__.py:1762
                             __init__ - Traceback (most recent                  
                             call last):                                        
                               File                                             
                             "/app/.venv/lib/python3.12/site-pa                 
                             ckages/starlette/routing.py", line                 
                             732, in lifespan                                   
                                 async with                                     
                             self.lifespan_context(app) as                      
                             maybe_state:                                       
                               File                                             
                             "/usr/local/lib/python3.12/context                 
                             lib.py", line 210, in __aenter__                   
                                 return await anext(self.gen)                   
                                        ^^^^^^^^^^^^^^^^^^^^^                   
                               File                                             
                             "/app/.venv/lib/python3.12/site-pa                 
                             ckages/langflow/main.py", line 92,                 
                             in lifespan                                        
                                 initialize_services(fix_migrat                 
                             ion=fix_migration,                                 
                             socketio_server=socketio_server)                   
                               File                                             
                             "/app/.venv/lib/python3.12/site-pa                 
                             ckages/langflow/services/utils.py"                 
                             , line 167, in initialize_services                 
                                 raise exc                                      
                               File                                             
                             "/app/.venv/lib/python3.12/site-pa                 
                             ckages/langflow/services/utils.py"                 
                             , line 165, in initialize_services                 
                                 initialize_database(fix_migrat                 
                             ion=fix_migration)                                 
                               File                                             
                             "/app/.venv/lib/python3.12/site-pa                 
                             ckages/langflow/services/database/                 
                             utils.py", line 93, in                             
                             initialize_database                                
                                 database_service:                              
                             "DatabaseService" =                                
                             get_db_service()                                   
                                                                                
                                     ^^^^^^^^^^^^^^^^                           
                               File                                             
                             "/app/.venv/lib/python3.12/site-pa                 
                             ckages/langflow/services/deps.py",                 
                              line 154, in get_db_service                       
                                 return                                         
                             get_service(ServiceType.DATABASE_S                 
                             ERVICE, DatabaseServiceFactory())                  
                             # type: ignore                                     
                                        ^^^^^^^^^^^^^^^^^^^^^^^                 
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                 
                             ^^^^^^^^^^                                         
                               File                                             
                             "/app/.venv/lib/python3.12/site-pa                 
                             ckages/langflow/services/deps.py",                 
                              line 43, in get_service                           
                                 return                                         
                             service_manager.get(service_type,                  
                             default)  # type: ignore                           
                                        ^^^^^^^^^^^^^^^^^^^^^^^                 
                             ^^^^^^^^^^^^^^^^^^^                                
                               File                                             
                             "/app/.venv/lib/python3.12/site-pa                 
                             ckages/langflow/services/manager.p                 
                             y", line 57, in get                                
                                 self._create_service(service_n                 
                             ame, default)                                      
                               File                                             
                             "/app/.venv/lib/python3.12/site-pa                 
                             ckages/langflow/services/manager.p                 
                             y", line 81, in _create_service                    
                                 self.services =                                
                             self.factories.create(**dependent_                 
                             services)                                          
                                                                                
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                 
                             ^^^^^^^^^^^^^^^^^^^^^^^                            
                               File                                             
                             "/app/.venv/lib/python3.12/site-pa                 
                             ckages/langflow/services/database/                 
                             factory.py", line 18, in create                    
                                 return                                         
                             DatabaseService(settings_service)                  
                                        ^^^^^^^^^^^^^^^^^^^^^^^                 
                             ^^^^^^^^^^                                         
                               File                                             
                             "/app/.venv/lib/python3.12/site-pa                 
                             ckages/langflow/services/database/                 
                             service.py", line 46, in __init__                  
                                 self.engine =                                  
                             self._create_engine()                              
                                               ^^^^^^^^^^^^^^^^                 
                             ^^^^^                                              
                               File                                             
                             "/app/.venv/lib/python3.12/site-pa                 
                             ckages/langflow/services/database/                 
                             service.py", line 64, in                           
                             _create_engine                                     
                                 return create_engine(                          
                                        ^^^^^^^^^^^^^^                          
                               File "<string>", line 2, in                      
                             create_engine                                      
                               File                                             
                             "/app/.venv/lib/python3.12/site-pa                 
                             ckages/sqlalchemy/util/deprecation                 
                             s.py", line 281, in warned                         
                                 return fn(*args, **kwargs)  #                  
                             type: ignore                                       
                                        ^^^^^^^^^^^^^^^^^^^                     
                               File                                             
                             "/app/.venv/lib/python3.12/site-pa                 
                             ckages/sqlalchemy/engine/create.py                 
                             ", line 599, in create_engine                      
                                 dbapi =                                        
                             dbapi_meth(**dbapi_args)                           
                                         ^^^^^^^^^^^^^^^^^^^^^^                 
                             ^^                                                 
                               File                                             
                             "/app/.venv/lib/python3.12/site-pa                 
                             ckages/sqlalchemy/dialects/postgre                 
                             sql/psycopg2.py", line 690, in                     
                             import_dbapi                                       
                                 import psycopg2                                
                             ModuleNotFoundError: No module                     
                             named 'psycopg2'                                   
                                                                                
                    ERROR    2024-08-23 20:26:29 - ERROR    -   __init__.py:1762
                             __init__ - Application startup                     
                             failed. Exiting.                                   
[08/23/24 20:26:29] ERROR    2024-08-23 20:26:29 - ERROR    -   __init__.py:1762
                             __init__ - Worker (pid:17) exited                  
                             with code 3                                        
                    ERROR    2024-08-23 20:26:29 - ERROR    -   __init__.py:1762
                             __init__ - Shutting down: Master                   
                    ERROR    2024-08-23 20:26:29 - ERROR    -   __init__.py:1762
                             __init__ - Reason: Worker failed                   
                             to boot.

**Comment by MarecoX** [comment]
```
version: "3.8"

services:
  langflow:
    image: langflowai/langflow:latest
    user: root
    volumes:
      - langflow_data:/var/lib/langflow
    networks:
      - minha_rede
    environment:

      # Segurança
      - LANGFLOW_SUPERUSER=xxxxxxxxx # Crie o usuário de acesso
      - LANGFLOW_SUPERUSER_PASSWORD=xxxxxxxLangflow # 
      - LANGFLOW_NEW_USER_IS_ACTIVE=true # 
      - LANGFLOW_AUTO_LOGIN=false
      # Outros
      - LANGFLOW_CONFIG_DIR=/var/lib/langflow
      - BACKEND_URL=langflow.neosites.com.br 
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:

          cpus: "1" 
          memory: 2G
      labels:
        - traefik.enable=true
        - traefik.http.routers.langflow.rule=Host(langflow.xxxxxx.com.br)
        - traefik.http.routers.langflow.entrypoints=websecure
        - traefik.http.routers.langflow.tls.certresolver=letsencryptresolver
        - traefik.http.routers.langflow.service=langflow
        - traefik.http.services.langflow.loadbalancer.server.port=7860

volumes:
  langflow_data:
    external: true

networks:
  minha_rede:
    external: true
```


If I understood correctly, now you have to remove Postgres from the stack, then this happens:

```

Starting Langflow v1.0.16...
/app/.venv/lib/python3.12/site-packages/pysbd/segmenter.py:66: SyntaxWarning: invalid escape sequence '\s'
  for match in re.finditer('{0}\s*'.format(re.escape(sent)), self.original_text):
/app/.venv/lib/python3.12/site-packages/pysbd/lang/arabic.py:29: SyntaxWarning: invalid escape sequence '\.'
  txt = re.sub('(?<={0})\.'.format(am), '∯', txt)
/app/.venv/lib/python3.12/site-packages/pysbd/lang/persian.py:29: SyntaxWarning: invalid escape sequence '\.'
  txt = re.sub('(?<={0})\.'.format(am), '∯', txt)
/app/.venv/lib/python3.12/site-packages/pydantic/_internal/_config.py:291: PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.8/migration/
  warnings.warn(DEPRECATION_MESSAGE, DeprecationWarning)
/app/.venv/lib/python3.12/site-packages/pydantic/_internal/_config.py:291: PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.8/migration/
  warnings.warn(DEPRECATION_MESSAGE, DeprecationWarning)
/app/.venv/lib/python3.12/site-packages/litellm/utils.py:113: DeprecationWarning: open_text is deprecated. Use files() instead. Refer to https://importlib-resources.readthedocs.io/en/latest/using.html#migrating-from-legacy for migration advice.
  with resources.open_text("litellm.llms.tokenizers", "anthropic_tokenizer.json") as f:
╭───────────────────────────────────────────────────────────────────╮
│ Welcome to ⛓ Langflow                                             │
│                                                                   │
│                                                                   │
│ Collaborate, and contribute at our GitHub Repo 🌟                 │
│                                                                   │
│ We collect anonymous usage data to improve Langflow.              │
│ You can opt-out by setting DO_NOT_TRACK=true in your environment. │
│                                                                   │
│ Access http://0.0.0.0:7860                                        │
╰───────────────────────────────────────────────────────────────────╯

```
