### ISSUE TITLE
LANGFLOW_AUTO_SAVE is not work in 1.0.15

### ISSUE THREAD

**Issue by songjinu** [langflow-ai/langflow#3418]
### Bug Description

LANGFLOW_AUTO_SAVE is not work in 1.0.15
it seems to bug at >> const shouldAutosave = process.env.LANGFLOW_AUTO_SAVE !== "false";
it worked when i update to 
const shouldAutosave = process.env.LANGFLOW_AUTO_SAVE !== "False";

### Reproduction

1. set LANGFLOW_AUTO_SAVE=False in .env
2. not work on frontend

### Expected behavior

we update set about process.env.LANGFLOW_AUTO_SAVE 
or 
const shouldAutosave = process.env.LANGFLOW_AUTO_SAVE !== "False";

### Operating System

windows 11

### Langflow Version

1.0.15

### Python Version

3.10

### Screenshot

![image](https://github.com/user-attachments/assets/c607caf1-7053-4786-90a3-8a87739c33b9)

**Comment by songjinu** [comment]
> The issue with `LANGFLOW_AUTO_SAVE` not working in version 1.0.15 is likely due to a typo in the environment variable name. The correct environment variable should be `LANGFLOW_AUTO_SAVING` (with an "ING" at the end).
> 
> To fix this, ensure that your `.env` file contains the following line:
> 
> ```dotenv
> LANGFLOW_AUTO_SAVING=false
> ```
> 
> Additionally, make sure that the `auto_saving` attribute in the `Settings` class is correctly set to `False` by the environment variable. The `Settings` class in `src/backend/base/langflow/services/settings/base.py` defines the `auto_saving` attribute, which should be set by the environment variable `LANGFLOW_AUTO_SAVING` [[1]](https://github.com/langflow-ai/langflow/blob/main/docs/docs/Configuration/configuration-auto-saving.md)[[2]](https://github.com/langflow-ai/langflow/blob/main/src/backend/base/langflow/__main__.py)[[3]](https://github.com/langflow-ai/langflow/blob/main/src/backend/base/langflow/services/settings/base.py).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

it not work but documents.

**Comment by lucaseduoli** [comment]
Hello!
The bug should be fixed in 1.0.16, that is being released shortly.
Thanks!
