### ISSUE TITLE
cant connect to tool calling agent

### ISSUE THREAD

**Issue by anshulyadav1976** [langflow-ai/langflow#3422]
### Bug Description

@dosu_bot when i try to connect a tool to tool calling agent , it doesnt connect

### Reproduction

dragging seearch api or firecrawl api node to tool calling agent 

### Expected behavior

it would connect

### Operating System

windows

### Langflow Version

s

### Python Version

None

**Comment by anshulyadav1976** [comment]
@dosu_bot @Eliotdoesprogramming 

> Hello, @anshulyadav1976! I'm here to help you with any bugs, questions, or contributions you may have. Let's work together to resolve your issue.
> 
> To connect a tool to the Tool Calling Agent when dragging the Search API or Firecrawl API node to it on Windows, you need to create an edge between the nodes. Here is an example of how to create such an edge in the JSON configuration:
> 
> ```json
> {
>   "data": {
>     "edges": [
>       {
>         "className": "",
>         "data": {
>           "sourceHandle": {
>             "dataType": "SearchAPI",
>             "id": "SearchAPI-nLBPg",
>             "name": "api_run_model",
>             "output_types": [
>               "Data",
>               "list"
>             ]
>           },
>           "targetHandle": {
>             "fieldName": "input_value",
>             "id": "ToolCallingAgent-ID",
>             "inputTypes": [
>               "Data",
>               "list"
>             ],
>             "type": "str"
>           }
>         },
>         "id": "reactflow__edge-SearchAPI-nLBPg{œdataTypeœ:œSearchAPIœ,œidœ:œSearchAPI-nLBPgœ,œnameœ:œapi_run_modelœ,œoutput_typesœ:[œDataœ,œlistœ]}-ToolCallingAgent-ID{œfieldNameœ:œinput_valueœ,œidœ:œToolCallingAgent-IDœ,œinputTypesœ:[œDataœ,œlistœ],œtypeœ:œstrœ}",
>         "selected": false,
>         "source": "SearchAPI-nLBPg",
>         "sourceHandle": "{œdataTypeœ: œSearchAPIœ, œidœ: œSearchAPI-nLBPgœ, œnameœ: œapi_run_modelœ, œoutput_typesœ: [œDataœ, œlistœ]}",
>         "target": "ToolCallingAgent-ID",
>         "targetHandle": "{œfieldNameœ: œinput_valueœ, œidœ: œToolCallingAgent-IDœ, œinputTypesœ: [œDataœ, œlistœ], œtypeœ: œstrœ}"
>       }
>     ]
>   }
> }
> ```
> 
> This JSON snippet creates an edge connecting the `SearchAPI` node's `api_run_model` output to the `ToolCallingAgent` node's `input_value` field. Adjust the `id` and `fieldName` values as necessary to match your specific node configurations [[1]](https://github.com/langflow-ai/langflow/blob/main/src/backend/base/langflow/initial_setup/starter_projects/Hierarchical Agent.json)[[2]](https://github.com/langflow-ai/langflow/blob/main/src/backend/base/langflow/initial_setup/starter_projects/Complex Agent.json)[[3]](https://github.com/langflow-ai/langflow/blob/main/src/backend/base/langflow/initial_setup/starter_projects/Sequential Agent.json)[[4]](https://github.com/logspace-ai/langflow/blob/dev/docs/static/json_files/JSON_Agent.json).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._








where do i paste this json code

**Comment by anshulyadav1976** [comment]
doesnt work u @dosu do better bro

**Comment by anshulyadav1976** [comment]
@dosu thats okay man i got it , found the answer from another thread

**Comment by carlosrcoelho** [comment]
#3357
