### ISSUE TITLE
How can I set a variable and use it in other components?

### ISSUE THREAD

**Issue by maxpaynebupt** [langflow-ai/langflow#3426]
### Bug Description

Now, I found no way to set a variable, and cite it in the other component.
If I extracted a variable from the question, I need to connect it to any component may use it, like a spider web.

### Reproduction

Now, I found no way to set a variable, and cite it in the other component.
If I extracted a variable from the question, I need to connect it to any component may use it, like a spider web.

### Expected behavior

There should be a component or we can just set the output of a text node to variable.

### Operating System

Windows 11

### Langflow Version

v1.0.15

### Python Version

3.10

**Comment by konradbjk** [comment]
You can do this, though need to build a custom component. I use Text inputs as variables in API requests

**Comment by maxpaynebupt** [comment]
> You can do this, though need to build a custom component. I use Text inputs as variables in API requests

Yes, we can use custom component to do it, but we still need to make many connections.

**Comment by maxpaynebupt** [comment]
> Hi @maxpaynebupt , how are you? If you want to use variables that you define before runtime, you can do as @konradbjk suggested. If you want to use variables that you will obtain during runtime, you can pass them through the edges.
> 
> An alternative in both cases, to avoid multiple connections between components, would be to use environment variables. You can set and read these variables in the component code using Python's `os` library. The downside of this approach is that you would be exposing these variables to other users of your Langflow instance.


The best way is , there is a chat level context having a dict, it will make the work much much more flexible.

**Comment by konradbjk** [comment]
Yeah, if you build this component please share the json/python xd

**Comment by maxpaynebupt** [comment]
> Yeah, if you build this component please share the json/python xd

this may need to modify the base component, I am new to langflow, may try it later.

**Comment by konradbjk** [comment]
I did the hard work guys :D but it is super ugly
https://github.com/konradbjk/vigilant-memory/blob/master/langflow-custom-components/onboarding_details.py

**Comment by maxpaynebupt** [comment]
> I did the hard work guys :D but it is super ugly https://github.com/konradbjk/vigilant-memory/blob/master/langflow-custom-components/onboarding_details.py

Took a quick glance, still need to connect the output to other component's input’?

**Comment by konradbjk** [comment]
Exactly, one to many

**Comment by maxpaynebupt** [comment]
> Exactly, one to many

oh, there is a scenario, I rewrite a question, and then I want to use it in all the latter components, now, I need make huge connections, this is why , I want to use variables.
