### ISSUE TITLE
Method Not Allowed While Creating New Users

### ISSUE THREAD

**Issue by carlosrcoelho** [langflow-ai/langflow#3427]
### Bug Description

A "method not allowed" error is encountered when trying to create a new user.

- The issue was encountered while using version 1.0.15 of pip.
- The user provided a link for further context: https://jam.dev/c/51ef7d3a-5f04-4b12-b19c-19ecb5954638

### Reproduction

1. Attempt to create a new user.
2. Observe the method not allowed error.

### Expected behavior

The user should be successfully created without any errors.

### Operating System

Mac Sonoma Version 14.6.1

### Langflow Version

3.12

### Python Version

None

### Screenshot

https://jam.dev/c/51ef7d3a-5f04-4b12-b19c-19ecb5954638

**Comment by codenprogressive** [comment]
#3313

**Comment by Cristhianzl** [comment]
Hi @codenprogressive and @carlosrcoelho,

Could you please follow up on PR #3471? This PR should resolve any issues related to adding or editing new users.

The fix will be included in version 1.0.16 of Langflow, so if you're using pip, I recommend waiting for the new release before updating to see if the issue persists. Alternatively, you can fork our main branch and use it locally.

Thank you!

**Comment by carlosrcoelho** [comment]
#3471

**Comment by suggsadc** [comment]
sorry... still unable to create users in v1.0.16
https://github.com/langflow-ai/langflow/issues/3519
