### ISSUE TITLE
how to add Gemini API  models/text-embedding-004 for RAG

### ISSUE THREAD

**Issue by Abrammun** [langflow-ai/langflow#3439]
### Feature Request

how to add Gemini API  models/text-embedding-004 for RAG

### Motivation

problem

**Comment by carlosrcoelho** [comment]
@Abrammun 

To use it, you need to have the API key and connect to the flow.

<img width="507" alt="image" src="https://github.com/user-attachments/assets/b2479566-2b1d-49a0-a976-c4e1ddb81b72">
