### ISSUE TITLE
Nowhere to edit the variables?

### ISSUE THREAD

**Issue by maxpaynebupt** [langflow-ai/langflow#3462]
### Bug Description

Nowhere to edit the variables. 
In docutment, it says:
TIP
You can also create global variables in Settings > Variables and Secrets.
![image](https://github.com/user-attachments/assets/43b6cbf0-4f3c-4257-8478-f2aef26678fb)

But, actually, there is no such "Variables and Secrets" section.

![image](https://github.com/user-attachments/assets/0ee96c8d-d701-433e-bba6-bc4d019d3cba)

### Reproduction

1. Create a flow.
2. Check the Settings.

### Expected behavior

There should be a "Variables and Secrets" section in Settings

### Operating System

Docker image v1.0.15

### Langflow Version

v1.0.15

### Python Version

None

**Comment by maxpaynebupt** [comment]
I found that these variable exists in the langflow software's settings, this is a bit little weird.
And, still it's not editable. There is no value field.
![image](https://github.com/user-attachments/assets/9b823b39-50c9-43ff-b104-a865fe314abb)

How can I set a project level variable which can be exported with the project and modified when the project is imported somewhere else?

**Comment by italojohnny** [comment]
Currently, you can edit the global variables directly through the API. I believe that the frontend will soon support editing global variables as well.
![Untitled](https://github.com/user-attachments/assets/c4e83392-25d0-439b-95dd-c3e27fc5498f)
