### ISSUE TITLE
Running LLM Data Iterator lead to WORKER TIMEOUT and sent code 134!

### ISSUE THREAD

**Issue by DDT-scrip** [langflow-ai/langflow#3466]
### Bug Description

While iterating through a CSV file using NamastexLabs LLM Data Iterator, if the iteration count accessed a certain threshold
after a few successful iterates, errors will suddenly appear

CRITICAL 2024-08-21 11:28:46 - CRITICAL - glogging - WORKER TIMEOUT (pid:50230)                       glogging.py:269
ERROR    2024-08-21 11:28:46 - ERROR    - glogging - Worker (pid:50230) was sent code 134!            glogging.py:272

while the UI show error message:
Error Building Component
Component Ollama has not been built yet

or
Error Building Component
Component CSV Loader has not been built yet

increasing the langflow run --timeout setting didn't solve the problemshows

### Reproduction

[LLM Iteration error recreation.json](https://github.com/user-attachments/files/16688482/LLM.Iteration.error.recreation.json)
upload a CSV with over 20 rows, and a long paragraph in each row
set the Iteration Count to a large number or 0 to go through all row
save the output CSV file to a path

### Expected behavior

The flow can Iterate through a large amount of rows without errors appear 

### Operating System

Ubuntu 22.04.4 LTS

### Langflow Version

1.0.5

### Python Version

3.10

### Flow File

[LLM Iteration error recreation.json](https://github.com/user-attachments/files/16688582/LLM.Iteration.error.recreation.json)

**Comment by DDT-scrip** [comment]
please explain the code 134 errors dosubot

**Comment by DDT-scrip** [comment]
will code 134 cause WORKER TIMEOUT error? @dosu

**Comment by vasconceloscezar** [comment]
Hey, I made this flow a while ago and had these issues. That's why there is the start index to process in batches. 

However you can try to set another .env variable like this: 


```
LANGFLOW_FRONTEND_TIMEOUT=6000
```

Try this and check if it works

**Comment by DDT-scrip** [comment]
@vasconceloscezar 
I tried the variable setting and didn't find any significant change, even when I increased the setting to 60000
The flow might be too heavy for my bad hardware
Although I wondered where is the bottleneck, it was not the system memory, but more likely the graphics memory?
But the loop starts up just fine, and the amount of data in each row is roughly the same.

Maybe the unloading of the LLM isn't clean, so each invoke eats up more and more memory?

If you have any insight on this I would really like to know.
PS: would setting up langwatch help debug these kinds of errors?

**Comment by DDT-scrip** [comment]
@dosu explain what is timeout and frontend timeout, and how to change these setting

**Comment by vasconceloscezar** [comment]
Is this still happening in the latest langflow version? 

I just iterated through a CSV with 30 rows, and everything worked as expected.

Can you please test it at the main branch?

**Comment by DDT-scrip** [comment]
@vasconceloscezar
Currently, I'm on
langflow: 1.0.17
ollama: 0.3.9

I tried to increase the --timeout setting in CLI to 180 and increase the LANGFLOW_FRONTEND_TIMEOUT=6000 in the env file, 
, but it makes the situation worse (15-20 rows down to less than 10)

I tried updating Ollama to the newest version and changing different models (llama3, 3.1, mistral-nemo, phi3)
no matter whether the model is big or small it all stops iterating at around 15-20 row

I am suspicious it may be caused by ollama, as some other user also experience similar issue

There is no crash, it just stops generating and hangs, without error code:
 9月 04 08:55:22 llmserver ollama[221701]: [GIN] 2024/09/04 - 08:55:22 | 200 | 21.357729469s |       127.0.0.1 | POST     "/api/chat"
 9月 04 08:55:42 llmserver ollama[221701]: [GIN] 2024/09/04 - 08:55:42 | 200 | 20.279408554s |       127.0.0.1 | POST     "/api/chat"
 9月 04 08:55:51 llmserver ollama[221701]: [GIN] 2024/09/04 - 08:55:51 | 200 |  8.569732642s |       127.0.0.1 | POST     "/api/chat"

then langflow pop out the code 134 error:
[08/21/24 11:28:46] CRITICAL 2024-08-21 11:28:46 - CRITICAL - glogging - WORKER TIMEOUT (pid:50230)                       glogging.py:269
                    ERROR    2024-08-21 11:28:46 - ERROR    - glogging - Worker (pid:50230) was sent code 134!            glogging.py:272
                    INFO     2024-08-21 11:28:46 - INFO     - glogging - Booting worker with pid: 52582                   glogging.py:278

but changing the timeout and frontend timeout also affect the performance, so currently I'm not sure what's the problem

**Comment by vasconceloscezar** [comment]
This could be an issue with ollama indeed, I'll try to setup ollama here and give it a try.

Could you test with a cheaper model like gpt 4 mini? Just to see if it works?

**Comment by DDT-scrip** [comment]
Due to limited hardware, all my models (llama3, 3.1, mistral-nemo, phi3) are the smaller ones
phi3:3.8b 2.2GB, llama3:8b 4.7GB,  mistral-nemo 23b 7.1GB

all quite cheap models
my setup is 2 X 1060 6GB, so the model won't exceed the memory of a single card, and definitely won't exceed both cards
the model response time of my CSV iterate prompt averages around 20 seconds in successful iteration
when it suddenly stops it usually stop under 10s of proccess

**Comment by carlosrcoelho** [comment]
@DDT-scrip 

Do you need any assistance with this case? If not, please let us know if this issue can be closed.

**Comment by DDT-scrip** [comment]
@carlosrcoelho 
I currently move the loop out of the Langflow system, using API to solve the issue
the loop still stops but not after hundreds of iterations hours of running 
(still the WORKER TIMEOUT (pid:249640), Worker (pid:) was sent code 134! issue thought)
so the issue still exists, but moving the loop out to an exterior python script it's much better

and it makes me suspect more it's caused by ollama

I think this issue can be closed, and thanks for your help
