### ISSUE TITLE
Streaming URL is not unique in multi-user environment

### ISSUE THREAD

**Issue by mieslep** [langflow-ai/langflow#3468]
### Bug Description

When `stream=true` is passed, the resulting `stream_url` is always the same, no matter what `session_id` is passed. Possibly related to #2563 , that stream is completely open so any session can consume tokens from the stream.

### Reproduction

1. Invoke any flow via API with `stream=true`
2. Inspect the response `init_response["outputs"][0]["outputs"][0]["artifacts"]["stream_url"]` : no matter what browser / session ID is passed, this value is always the same.

### Expected behavior

1, A unique stream should be created for each API call. 
2. Ideally some sort of "authentication" of the caller (even if just expecting the same `session_id` on the request) is present

### Operating System

Windows 11

### Langflow Version

1.0.14

### Python Version

3.12

**Comment by mieslep** [comment]
@dosu passing in different values for `session_id` does not change the `stream_url` in any way, nor is it required to pass in `session_id` on the `GET` to consume stream tokens.

**Comment by therockerline** [comment]
Hello, is there any update on this issue? It would be nice if by calling the flow with the `stream=true` parameter you could send a response directly as a stream, avoiding using the `stream_url`  afterwards. 
This way you could directly use the session logic that has already been implemented on the flow

**Comment by guojingfeng1994** [comment]
我也有同样的问题。在web应用程序中，让每个请求拥有自己独立的处理线程和作用域来提高并发太常见了。我在使用stream流式输出时，返回的stream url都是固定的，这导致我同时发起两个回话请求时，stream url输出的总是最后一个会话请求的数据，而不是分别返回各自会话请求的回答。我不知道该如何解决这个问题，如果要使用串行化，那样对web应用来说处理效率实在是太低了。如果有人知道如何解决这个问题，麻烦方便告知下，谢谢

**Comment by anovazzi1** [comment]
@egerszu we are updating the streaming logic, it should be available soon

**Comment by devinbost** [comment]
There also needs to be a way to authenticate the request. Just having a session ID is not enough.

**Comment by anovazzi1** [comment]
the stream right now does not use the stream url anymore since 1.0

**Comment by yangxikun** [comment]
> the stream right now does not use the stream url anymore since 1.0

@anovazzi1 Hi, how to use streaming API in multi-user environment now?

**Comment by anovazzi1** [comment]
hey @yangxikun to use stream you can run langflow using the same endpoint as the ui, and handle the streaming directly in the build response. now our build post is basically an SSE that receives multiple events and tokens, that way we can stream without a stream url

**Comment by yangxikun** [comment]
@anovazzi1 Do you mean call this api?

```
curl 'http://localhost:3000/api/v1/build/f99e2ba4-5550-4a30-9d88-39ad1134ac39/flow?&start_component_id=ChatInput-QH6jh&log_builds=true' \
-X 'POST' \
-H 'Content-Type: application/json' \
-H 'Accept: */*' \
-H 'x-api-key: sk-xxxxxxxxxx' \
--data-binary $'{"inputs":{"input_value":"你是谁","session":"Session Dec 20 at 06:30:38"}}'
```

**Comment by anovazzi1** [comment]
yes, the response body of this api is async, so it can stream the model response

**Comment by yangxikun** [comment]
@anovazzi1 How can I pass extra fields(MetaData) in `Chat Input` through `/api/v1/build/{flow_Id}/flow`?

The `InputValueRequest` just allow a fixed field `input_value`.

<img width="394" alt="Clipboard_Screenshot_1735025846" src="https://github.com/user-attachments/assets/00e7c451-d33e-4d89-8151-d1bee16b9712" />

**Comment by anovazzi1** [comment]
Unfortunately you can't right now with this component. But you can update the component or create a custom component that generates a message as output and has the extra fields you need
