### ISSUE TITLE
Langflow fails to start without Internet due to attempting to send data via telemetry

### ISSUE THREAD

**Issue by viniciossilva3** [langflow-ai/langflow#3477]
### Error description

Langflow does not start without Internet due to the attempt to send data via telemetry. When running Langflow on a computer without an Internet connection, the application fails to launch and generates an error. This issue prevents the application from launching correctly.
I tried to correct it manually in the code but for some reason the do_not_track variable always had a false value.

### Reproduction

1. Launch Langflow on a computer without an Internet connection.
2. Observe the error message generated during the initialization process.
3. The application will not initialize
4. To test the correction, simply set the DO_NOT_TRACK variable in the .env file to true or comment the print_banner function on run_on_mac_or_linux in venv/lib64/python3.12/site-packages/langflow/__main__.py 

### Expected behavior

Langflow must be able to start and boot without an internet connection. The DO_NOT_TRACK variable must be set to True if there is no internet available.

### Who can help?

@italojohnny

### Operating System

Arch Linux x86_64 Linux 6.10.4-arch2-1

### Langflow Version

1.0.15

### Python Version

3.12

### Screenshot

Start of error
![Screenshot from 2024-08-21 13-54-37](https://github.com/user-attachments/assets/363b5302-9eac-47e4-b752-6732a4fdd370)

![Screenshot from 2024-08-21 13-55-18](https://github.com/user-attachments/assets/1ae2d59c-f49d-40f2-8e3c-c74f09c1a3df)
End Error

**Comment by italojohnny** [comment]
Hi, Fulano. How are you?
This issue was resolved in PR #3527. It will be available in the next release
