### ISSUE TITLE
basic components are missing in the langflow 1.0.15

### ISSUE THREAD

**Issue by HAL9KKK** [langflow-ai/langflow#3479]
### Feature Request

In the new langflow 1.0.15 are miossing the basic component to create some basic agent, like AgentInitializer and calculator, in the previose release < 1.0 they were available, I do not know why these basic component are missing in the new UI.
Also, all the examples how to learn langflow are based on the previouse release < 1.0 and importing them in the new release there are many errors as the components are missing....also for the examples please update them with the new component added otherwise people cannot understand how to use the suite

### Motivation

I am new in langflow and with the current component I am really frustrate how to create basic agent, also when you delete some component please write somewhere why and how it/them are replaced

### Your Contribution

I have already asked to dosubot and it suggest to create a new component, but why I need to create basic component if they can be part of the standard suite?

**Comment by carlosrcoelho** [comment]
We've gone through major changes since 1.0, and today we're on version v1.0.19.post2.

If you have any questions regarding the new version, please open a new issue and we'll support you.
