### ISSUE TITLE
Flows 1.0.15 Falls over after a few days

### ISSUE THREAD

**Issue by zdql** [langflow-ai/langflow#3481]
### Bug Description

Running in an ec2, was working fine for several days and then when we attempted to reach the service: 

 "[TypeError(\"'ModelField' object is not iterable\"), TypeError('vars() argument must have __dict__ attribute')]"
 
 This was returned along with a 500 error from the service. 
 
 Restarting the service fixed it and allowed us to restart the service. Looks like a FastAPI error? 
 
 
 

### Reproduction

Host a langflow instance in EC2 for several days and hope to see  "[TypeError(\"'ModelField' object is not iterable\"), TypeError('vars() argument must have __dict__ attribute')]"

### Expected behavior

 "[TypeError(\"'ModelField' object is not iterable\"), TypeError('vars() argument must have __dict__ attribute')]"
 
 Should not be returned. 

### Operating System

Amazon Linux 

### Langflow Version

1.0.15

### Python Version

None

**Comment by italojohnny** [comment]
Hi, @zdql . How are you?
Since your issue is based on v1.0.15, there’s a good chance that commit https://github.com/langflow-ai/langflow/commit/742e8a5d3166da6867f89163b29a821be3bb1862 has fixed it. Could you check if it works in version v1.0.16  or v1.0.17 (if it has been released)?

**Comment by nicoloboschi** [comment]
@zdql Also posting the entire stacktrace would help us to understand the actual problem.

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
