### ISSUE TITLE
custom component display name never changes

### ISSUE THREAD

**Issue by mieslep** [langflow-ai/langflow#3496]
### Bug Description

If I set the following in a custom component:

```
class Base64FileLoader(Component):
    display_name = "Base64FileLoader"
    name = "Base64FileLoader"
    description = "Loads a file from a base64 encoded string, temporarily stores it, and processes similar to FileComponent."
    icon = "file-text"    
```

The UI continues to show:
![image](https://github.com/user-attachments/assets/11fb1d6b-a88c-43a0-81df-afeda96580af)

And if I save the component (to the list of components) it remains as "Custom Component". 

### Reproduction

1. Create a Custom Component
2. Within the code, set `display_name` and `name` and the class name itself to some other value
3. Close the code , and even the flow, go back into the flow.
4. The displayed component name remains "Custom Component"

### Expected behavior

The component should be displayed as the value in `display_name`. 

### Operating System

Windows 11

### Langflow Version

1.0.14

### Python Version

3.12

**Comment by mieslep** [comment]
@dosu it might be a display issue, sure, but if I update the flow name in the database:

```
update flow set name = 'Base64FileComponent' where id = '1a66f7a7-22ed-4abc-9f19-1b734c38d31c';
```

and restart Langflow, the component is correctly named (though instances of the component within flows do not change).

**Comment by mieslep** [comment]
@carlosrcoelho suggested workaround that seems to sort out the database and component name. The ID is still not terribly consistent (for me at least, shows as `CustomComponent-`), though if I "save" the component and then drag it into the flow the ID is as I'd expect.

**Comment by Cristhianzl** [comment]
Hi @mieslep,

We understand your concern. We've encountered some issues with directly changing the display_name through the code. For now, if you want to change the Custom Component name, please use the UI as shown in the image below:

![image](https://github.com/user-attachments/assets/7bcdade0-ec10-4d2b-9c3d-75aa8827c760)

We might reintroduce this feature in the future.

Thank you for your message!
