### ISSUE TITLE
error while updating component

### ISSUE THREAD

**Issue by Stella12121** [langflow-ai/langflow#3497]
### Bug Description

When I try to use ollama, I got the error shown below:
![f82819e3bf1a59b3f9e4ac012e7ed5f](https://github.com/user-attachments/assets/01b42941-ac87-4ebe-b31f-a39c2d1fd76e)

### Reproduction

Drag the ollama option from the model into the flow

### Expected behavior

fix this error

### Operating System

windows

### Langflow Version

1.0.9

### Python Version

None

**Comment by carlosrcoelho** [comment]
@Stella12121 

Hey, I see you're using version 1.0.9. Can you update the latest version, 1.0.16, and test it again? Let me know when you get a chance. Thanks!

**Comment by Stella12121** [comment]
> @Stella12121
> 
> Hey, I see you're using version 1.0.9. Can you update the latest version, 1.0.16, and test it again? Let me know when you get a chance. Thanks!

Hi, thanks for your kind reply! Actually, I get started with Langflow through the DataStax Cloud Service. I've tried refreshing and re-login, but that still didn't work :(

**Comment by carlosrcoelho** [comment]
DataStax is actually on version 1.0.14.
<img width="229" alt="image" src="https://github.com/user-attachments/assets/6e8b6ea3-854c-4f09-9c2d-48631070d8cc">

Hey, @jordanrfrazier could you please take a look at this?

**Comment by 0rakul0** [comment]
![image](https://github.com/user-attachments/assets/e2dc1da3-e188-406f-aa5f-06f51c46ff20)

```python
 else (
  int(value_dict.get("value")) if value_dict.get("value").strip() else 0  # type: ignore
  if value_dict.get("_input_type") != "FloatInput"
  else float(value_dict.get("value"))  # type: ignore
 )
```
start again langflow

**Comment by carlosrcoelho** [comment]
@0rakul0 

We are aware of this issue. The fix has already been made in this PR (https://github.com/langflow-ai/langflow/pull/3514). For now, you can either use the development version on the main branch or wait for the new release, version 1.0.17, which will be available soon.
