### ISSUE TITLE
Docker 1.0.16 image does not work with Postgres

### ISSUE THREAD

**Issue by mieslep** [langflow-ai/langflow#3524]
### Bug Description

Running `docker run -d langflowai/langflow:1.0.16` works just fine, but if you specify `-e LANGFLOW_DATABASE_URL=postgres://...` 

you get errors:
```sqlalchemy.exc.NoSuchModuleError: 
Can't load plugin:                
sqlalchemy.dialects:postgres      

import_dbapi                      
    import psycopg2               
ModuleNotFoundError: No module    
named 'psycopg2'                  
```

### Reproduction

Start a Docker instance for v1.0.16 that connects to a Postgres database using the `LANGFLOW_DATABASE_URL` environment vairable.

### Expected behavior

Container starts and Langflow service runs as normal :)

### Operating System

Langflow Docker image

### Langflow Version

1.0.16

### Python Version

3.12

**Comment by italojohnny** [comment]
It seems the issue is related to PR #3292.

For now, if you can manually install the psycopg2 dependency in your container, I believe you should be able to continue your work until the problem is resolved
