### ISSUE TITLE
The promt component not visible on version 1.0.16

### ISSUE THREAD

**Issue by cankanatt** [langflow-ai/langflow#3525]
### Bug Description

The Prompt component is not visible in the current version. It was present in the previous version. I'm wondering if this component was removed intentionally. Due to its absence, the older flows that I developed are not working as expected.

### Reproduction

The Prompt component is not visible in the current version. It was present in the previous version.

### Expected behavior

The Prompt component should be visible, as it was in the previous version.

### Operating System

macos sonoma 14.0

### Langflow Version

1.0.16

### Python Version

3.10

### Screenshot

This is version 1.0.15

![image](https://github.com/user-attachments/assets/4d86c380-f3af-48ae-ab10-1bdb19a5e504)

**Comment by carlosrcoelho** [comment]
@cankanatt 
I just tested it, and it's working. Try updating again; if you're using the `main` branch, do a `git pull`. If you're using `pip`, run `python -m pip install langflow -U`.
<img width="299" alt="image" src="https://github.com/user-attachments/assets/7feb7e7e-57a9-44b9-b264-589e4b6866b2">
