### ISSUE TITLE
multimodality

### ISSUE THREAD

**Issue by zhengqianhe0** [langflow-ai/langflow#3530]
### Bug Description

I found that all input and output before langflow are text. I would like to know if there is currently a function to upload and parse images? This refers to multimodality, which means directly understanding the content of images or audio/video, rather than extracting text from images and processing it with large models. Does the current version 1.0.16 have this feature? Do you have any plans to integrate multimodal large models?

### Reproduction

I can't find how to use components with multimodal capabilities。How can I use this

### Expected behavior

Upload JPG image and parse it

### Operating System

windows 10

### Langflow Version

1.0.16

### Python Version

None

**Comment by anovazzi1** [comment]
you can use multimodality with the chat input component, uploading images and files in general
