### ISSUE TITLE
Prompt component does not pass variables correctly

### ISSUE THREAD

**Issue by Gluepower** [langflow-ai/langflow#3536]
### Bug Description

I have prompt with two variables. 
{image_url}  Value of image is https://oaidalleapiprodscus.blob.core.windows.net/private/org-N0bzhj17kGCdvkPCuGgpUuhO/user-RwGFQKsTTGw8hOO1ResFbpwQ/img-GH9Zkmf4RabhW48gVeZslvyb.png?st=2024-08-23T19%3A00%3A31Z&se=2024-08-23T21%3A00%3A31Z&sp=r&sv=2024-08-04&sr=b&rscd=inline&rsct=image/png&skoid=d505667d-d6c1-4a0a-bac7-5c84a87759f8&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2024-08-23T18%3A20%3A28Z&ske=2024-08-24T18%3A20%3A28Z&sks=b&skv=2024-08-04&sig=HXgLmH4hDFvbuV/rPEX//ifP0PLXUUlCYP9ZDpFEAHM%3D
{post_id} Value of Post ID is 11620

Prompt is 
Task: Upload the image from the provided URL to WordPress and set it as the featured image for the specified post.
Image URL: {image_url}
Post ID: {post_id}

This worked on 1.0.15, but after I upgraded to 1.0.16 the second variable is not passed on, it repeats the image one.

Component output
Task: Upload the image from the provided URL to WordPress and set it as the featured image for the specified post.
Image URL: https://oaidalleapiprodscus.blob.core.windows.net/private/org-N0bzhj17kGCdvkPCuGgpUuhO/user-RwGFQKsTTGw8hOO1ResFbpwQ/img-GH9Zkmf4RabhW48gVeZslvyb.png?st=2024-08-23T19%3A00%3A31Z&se=2024-08-23T21%3A00%3A31Z&sp=r&sv=2024-08-04&sr=b&rscd=inline&rsct=image/png&skoid=d505667d-d6c1-4a0a-bac7-5c84a87759f8&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2024-08-23T18%3A20%3A28Z&ske=2024-08-24T18%3A20%3A28Z&sks=b&skv=2024-08-04&sig=HXgLmH4hDFvbuV/rPEX//ifP0PLXUUlCYP9ZDpFEAHM%3D
Post ID: https://oaidalleapiprodscus.blob.core.windows.net/private/org-N0bzhj17kGCdvkPCuGgpUuhO/user-RwGFQKsTTGw8hOO1ResFbpwQ/img-GH9Zkmf4RabhW48gVeZslvyb.png?st=2024-08-23T19%3A00%3A31Z&se=2024-08-23T21%3A00%3A31Z&sp=r&sv=2024-08-04&sr=b&rscd=inline&rsct=image/png&skoid=d505667d-d6c1-4a0a-bac7-5c84a87759f8&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2024-08-23T18%3A20%3A28Z&ske=2024-08-24T18%3A20%3A28Z&sks=b&skv=2024-08-04&sig=HXgLmH4hDFvbuV/rPEX//ifP0PLXUUlCYP9ZDpFEAHM%3D

### Reproduction

Create prompt with multiple variables.
Add value in each.
Try to build prompt and you will find that only first variable is being pulled.
![image](https://github.com/user-attachments/assets/cc478377-6c3d-4a71-ba13-ab6e1773413e)

![image](https://github.com/user-attachments/assets/fad07891-e9d1-474f-b7a9-efb3084c4caf)

### Expected behavior

multiple variables should work

### Operating System

Render

### Langflow Version

1.0.16

### Python Version

3.12

**Comment by edwinjosechittilappilly** [comment]
Hi @Gluepower,

Thanks for your feedback! It looks like the scenario might be working as expected in the latest version of Langflow (v1.0.17).

Would you be able to try updating your Langflow installation to see if that resolves the issue?

For reference, I've attached the screenshots you previously sent and a sample flow that you mentioned (in case they're helpful).

Please let me know if updating Langflow resolves the issue, or if you encounter any problems during the update process.

<img width="1686" alt="Screenshot 2024-08-28 at 1 45 20 PM" src="https://github.com/user-attachments/assets/866d1d2c-316a-4366-b49e-146c12eee6da">
<img width="1917" alt="Screenshot 2024-08-28 at 1 45 06 PM" src="https://github.com/user-attachments/assets/cd02aff9-f28c-4bb4-ade7-8fcef38076cc">
[Testing#3536.json](https://github.com/user-attachments/files/16787157/Testing.3536.json)

**Comment by Gluepower** [comment]
Hi @edwinjosechittilappilly 

It is intermittent. If I freeze path most of the time will do well. However, when I run complete flow it will show this error. I never had this issue with 1.0.15 and before. It showed up with 1.0.16 and with 1.0.17 is the same. Here is short video going through the flow to show components. At the end is running full flow and it shows this error.

https://youtu.be/w-MRWgnR114

**Comment by edwinjosechittilappilly** [comment]
Yes It might be related.
Based on further investigation, I believe this issue is not related to the Prompt component but rather to the LLM component and/or the data sending functions in downstream of LLM components as mentioned in #3619.

Closing this issue. Please refer to #3619 for further discussion
