### ISSUE TITLE
Hackathon

### ISSUE THREAD

**Issue by useEffects** [langflow-ai/langflow#3540]
### Bug Description

https://www.langflow.org/aidevs-india
is this legit? I was told to star the repo to get enter hackathon but then no update on what to do next

### Reproduction

lorem ipsum

### Expected behavior

lorem ipsum

### Operating System

arch linux

### Langflow Version

1.0.9

### Python Version

None

**Comment by useEffects** [comment]
https://www.langflow.org/aidevs-india/challenges

![image](https://github.com/user-attachments/assets/990bbc31-6909-4dbd-87fa-a6f3f4695714)

**Comment by viniciossilva3** [comment]
Yes is correct!
1 - Star the repo
2 - Sign up with the github email you used to star the repository.
Do this and you will be ready to participate, just wait for the challenges.

**Comment by pulkit21aug** [comment]
That is correct . You just need to wait for timeline to start.

**Comment by useEffects** [comment]
Not sure why you ask to star the repo, but ok!

**Comment by varadhanx** [comment]
when will it start , where will it start ,

**Comment by kappek** [comment]
Why are y'all marketing this so heavily and this is so poorly planned? Definitely looks scammy, but can't figure out your endgame. Was it just to get more stars on your repo?
