### ISSUE TITLE
"ValueError ao converter string vazia para int em endpoints.py"

### ISSUE THREAD

**Issue by 0rakul0** [langflow-ai/langflow#3541]
## Descrição do Problema

Ocorre um erro `ValueError` ao tentar converter uma string vazia para um número inteiro na função `custom_component_update` no arquivo `endpoints.py`.

### Linha Problemática

A linha de código problemática é:

```python
int(value_dict.get("value"))  # type: ignore
```

### Reproduction

Passos para Reproduzir
Use um input que resulta em value_dict.get("value") sendo uma string vazia.
Execute o código que chama a função custom_component_update.
ou 
componente Ollama 

### Expected behavior
```
int(value_dict.get("value")) if value_dict.get("value") and value_dict.get("value").strip() else 0  # type: ignore
```
or
```
try:
    converted_value = int(value_dict.get("value"))
except ValueError:
    converted_value = 0
```

### Operating System

Windows 11

### Langflow Version

1.0.16

### Python Version

3.12

**Comment by italojohnny** [comment]
This issue was fixed in PR #3514
