### ISSUE TITLE
Error Docker Compose

### ISSUE THREAD

**Issue by alvarolucasno** [langflow-ai/langflow#3546]
### Bug Description

When deploying the stack in Portainer, I received the following error.

### Reproduction

Stack:

version: "3.8"

services:
  langflow:
    image: langflowai/langflow:latest
    ports:
      - "7860:7860"
    depends_on:
      - postgres
    environment:
      - LANGFLOW_DATABASE_URL=postgresql://langflow:langflow@postgres:5432/langflow
    volumes:
      - langflow-data:/app/langflow

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: langflow
      POSTGRES_PASSWORD: langflow
      POSTGRES_DB: langflow
    ports:
      - "5432:5432"
    volumes:
      - langflow-postgres:/var/lib/postgresql/data

volumes:
  langflow-postgres:
  langflow-data:
  
  Erro:      
         
                             "DatabaseService" =                                
                             get_db_service()                                   
                                                                                
                                     ^^^^^^^^^^^^^^^^                           
                               File                                             
                             "/app/.venv/lib/python3.12/site-pa                 
                             ckages/langflow/services/deps.py",                 
                              line 154, in get_db_service                       
                                 return                                         
                             get_service(ServiceType.DATABASE_S                 
                             ERVICE, DatabaseServiceFactory())                  
                             # type: ignore                                     
                                        ^^^^^^^^^^^^^^^^^^^^^^^                 
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                 
                             ^^^^^^^^^^                                         
                               File                                             
                             "/app/.venv/lib/python3.12/site-pa                 
                             ckages/langflow/services/deps.py",                 
                              line 43, in get_service                           
                                 return                                         
                             service_manager.get(service_type,                  
                             default)  # type: ignore                           
                                        ^^^^^^^^^^^^^^^^^^^^^^^                 
                             ^^^^^^^^^^^^^^^^^^^                                
                               File                                             
                             "/app/.venv/lib/python3.12/site-pa                 
                             ckages/langflow/services/manager.p                 
                             y", line 57, in get                                
                                 self._create_service(service_n                 
                             ame, default)                                      
                               File                                             
                             "/app/.venv/lib/python3.12/site-pa                 
                             ckages/langflow/services/manager.p                 
                             y", line 81, in _create_service                    
                                 self.services =                                
                             self.factories.create(**dependent_                 
                             services)                                          
                                                                                
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                 
                             ^^^^^^^^^^^^^^^^^^^^^^^                            
                               File                                             
                             "/app/.venv/lib/python3.12/site-pa                 
                             ckages/langflow/services/database/                 
                             factory.py", line 18, in create                    
                                 return                                         
                             DatabaseService(settings_service)                  
                                        ^^^^^^^^^^^^^^^^^^^^^^^                 
                             ^^^^^^^^^^                                         
                               File                                             
                             "/app/.venv/lib/python3.12/site-pa                 
                             ckages/langflow/services/database/                 
                             service.py", line 46, in __init__                  
                                 self.engine =                                  
                             self._create_engine()                              
                                               ^^^^^^^^^^^^^^^^                 
                             ^^^^^                                              
                               File                                             
                             "/app/.venv/lib/python3.12/site-pa                 
                             ckages/langflow/services/database/                 
                             service.py", line 64, in                           
                             _create_engine                                     
                                 return create_engine(                          
                                        ^^^^^^^^^^^^^^                          
                               File "<string>", line 2, in                      
                             create_engine                                      
                               File                                             
                             "/app/.venv/lib/python3.12/site-pa                 
                             ckages/sqlalchemy/util/deprecation                 
                             s.py", line 281, in warned                         
                                 return fn(*args, **kwargs)  #                  
                             type: ignore                                       
                                        ^^^^^^^^^^^^^^^^^^^                     
                               File                                             
                             "/app/.venv/lib/python3.12/site-pa                 
                             ckages/sqlalchemy/engine/create.py                 
                             ", line 599, in create_engine                      
                                 dbapi =                                        
                             dbapi_meth(**dbapi_args)                           
                                         ^^^^^^^^^^^^^^^^^^^^^^                 
                             ^^                                                 
                               File                                             
                             "/app/.venv/lib/python3.12/site-pa                 
                             ckages/sqlalchemy/dialects/postgre                 
                             sql/psycopg2.py", line 690, in                     
                             import_dbapi                                       
                                 import psycopg2                                
                             ModuleNotFoundError: No module                     
                             named 'psycopg2'                                   
                                                                                
                    ERROR    2024-08-26 10:57:08 - ERROR    -   __init__.py:1762
                             __init__ - Application startup                     
                             failed. Exiting.                                   
[08/26/24 10:57:08] ERROR    2024-08-26 10:57:08 - ERROR    -   __init__.py:1762
                             __init__ - Worker (pid:19) exited                  
                             with code 3                                        
                    ERROR    2024-08-26 10:57:08 - ERROR    -   __init__.py:1762
                             __init__ - Shutting down: Master                   
                    ERROR    2024-08-26 10:57:08 - ERROR    -   __init__.py:1762
                             __init__ - Reason: Worker failed                   
                             to boot.                  

### Expected behavior

Service execution and application start.

### Who can help?

@italojohnny 

### Operating System

Docker Swarm

### Langflow Version

latest

### Python Version

None

**Comment by italojohnny** [comment]
Hi, @alvarolucasno . I hope you're doing well.
The issue you're facing has been resolved in PR #3526. In the next release, you won't have to deal with this problem anymore.
