### ISSUE TITLE
Cannot find langflow backend version 1.0.15.

### ISSUE THREAD

**Issue by tkdguq05** [langflow-ai/langflow#3565]
I wanted to roll back langflow version to 1.0.15, but there is no version 1.0.15.
All versions are available but 1.0.15.

You can check in langflowai/langflow-backend dockerhub
- https://hub.docker.com/r/langflowai/langflow-backend/tags?page=&page_size=&ordering=&name=

**Comment by italojohnny** [comment]
Hi, @tkdguq05 . I hope you're doing well.

As you pointed out, v1.0.16 does have this issue. We've already fixed it, and v1.0.17 with the correction will be available soon.

Alternatively, you can clone the repository and build the images locally with the latest changes from the main branch

**Comment by carlosrcoelho** [comment]
Hey
@tkdguq05 

Try to run `docker run --rm -p 7860:7860 langflowai/langflow:1.0.15`

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
