### ISSUE TITLE
langflow installation fails with python 3.12 but works fine with 3.11

### ISSUE THREAD

**Issue by pulkit21aug** [langflow-ai/langflow#3571]
### Bug Description

langflow installation fails with python 3.12 but works fine with 3.11

### Reproduction

install pip install langflow -U
langflow installation fails with python 3.12 but works fine with 3.11

### Expected behavior

installation should work fine with 3.12 . windows 11 machine

### Operating System

Windows 11

### Langflow Version

1.0.16

### Python Version

3.12

### Screenshot

langflow installation fails with python 3.12 but works fine with 3.11

### Flow File

langflow installation fails with python 3.12 but works fine with 3.11

**Comment by italojohnny** [comment]
https://github.com/user-attachments/assets/53121180-3d33-429a-a5aa-ec789879e966

Hi there, I hope you're doing well.

I tested it on my end, and it's working fine.

I believe the issue might be related to a dependency on your operating system (Windows). You should provide more details about the error so we can help you out.

Could you please send the full error traceback?

**Comment by italojohnny** [comment]
Hi, @pulkit21aug . I hope you managed to install it. If you're still having issues, please open a new issue
