### ISSUE TITLE
Azure OpenA - MessageTextInput value Value error

### ISSUE THREAD

**Issue by HAL9KKK** [langflow-ai/langflow#3578]
### Bug Description

Error building Component Azure OpenAI: 1 validation error for MessageTextInput value Value error, Invalid value type <class 'NoneType'> [type=value_error, input_value=None, input_type=NoneType] For further information visit https://errors.pydantic.dev/2.8/v/value_error

### Reproduction

![image](https://github.com/user-attachments/assets/dac4879a-aa71-4660-b3d9-a598b036ee25)

### Expected behavior

Component validated

### Operating System

wiindows

### Langflow Version

1.0.17

### Python Version

None

**Comment by edwinjosechittilappilly** [comment]
HI @konradbjk,
Thank you for the feedback!

Can you select the API version to any date from year 2023, like  2023-03-15-preview ?

**Comment by konradbjk** [comment]
> HI @konradbjk,
> Thank you for the feedback!
> 
> Can you select the API version to any date from year 2023, like  2023-03-15-preview ?
> 
> 

Well yes, you can modify the value there as one desires. It is by default a drop-down, but one can modify the value available. You can also convert it into a hard coded value

**Comment by edwinjosechittilappilly** [comment]
Hi @HAL9KKK,

Can you select the API version to any date from year 2023, like 2023-03-15-preview ?
I hope that would solve the issue for time being. I am investigating in to why it gives error for API versions >=2024.
Will keep you posted with the further updates.

**Comment by HAL9KKK** [comment]
Thanks for your reply, I fixed the problem, it was the endpoint string not correctly reported. Unfortunately with AzureOpenAI there severeral way to insert the parameters, resource name/endpoint/deployment model....

**Comment by edwinjosechittilappilly** [comment]
Closing the issue. If any further problems please feel free to raise/ reopen the issue.
Thank you!
