### ISSUE TITLE
ValueError: No cache found for  

### ISSUE THREAD

**Issue by xzqxnet0990** [langflow-ai/langflow#3587]
### Bug Description

I'm using a Openai compontent to run the playground, the problem will be happen.
If the stream is closed, the chatbot will return the correct answer. 

But, When I changed the stream to open, the problem will be happen.
<img width="1293" alt="image" src="https://github.com/user-attachments/assets/ef65657d-e4ef-42ab-a0e7-fd4b63d5c40a">
<img width="1267" alt="image" src="https://github.com/user-attachments/assets/a9a13dc1-04a9-4a99-895e-7c070bde41e6">

![image](https://github.com/user-attachments/assets/900ec6eb-081f-4b63-8ee9-26770e840491)

I am using the async cache mode.

>  langflow/api/v1                 
                             /chat.py", line 639, in                            
                             stream_vertex
                             raise ValueError(f"No cache                    
                             found for {flow_id_str}.")
                             ->                                        
                             'c2b085ae-fc2a-4e7d-ab36-a0902ac11                 
                             1c5'
                             ValueError: No cache found for                     
                             c2b085ae-fc2a-4e7d-ab36-a0902ac111                 
                             c5.

### Reproduction

1.use /docker-examples/docker-compose up -d ;
2. change use default openai components stream to open;

### Expected behavior

I just want to see the stream return.

### Operating System

macos 

### Langflow Version

1.0.15

### Python Version

3.12

### Flow File

Untitled document.json
[Untitled document.json](https://github.com/user-attachments/files/16781026/Untitled.document.json)

**Comment by BCeZn** [comment]
change langflow version to 1.0.14 or 1.0.16

**Comment by xzqxnet0990** [comment]
> change langflow version to 1.0.14 or 1.0.16

1.0.14 works ！！！

**Comment by xzqxnet0990** [comment]
> change langflow version to 1.0.14 or 1.0.16

1.0.14 works ！！！

**Comment by zcasanova** [comment]
I'm using  1.0.16 and I get this problem still
