### ISSUE TITLE
Langflow v1.0.17 - error when starting the new or old flow.

### ISSUE THREAD

**Issue by RomualdoGobbo** [langflow-ai/langflow#3588]
Hi All,
I've updated the LangFlow to version v.1.0.17 from v.1.0.16 as suggested:
```
(langflow) root@Romualdo-PC:/home/romua# langflow run
Starting Langflow v1.0.17...
╭───────────────────────────────────────────────────────────────────╮
│ Welcome to ⛓ Langflow                                             │
│                                                                   │
│                                                                   │
│ Collaborate, and contribute at our GitHub Repo 🌟                 │
│                                                                   │
│ We collect anonymous usage data to improve Langflow.              │
│ You can opt-out by setting DO_NOT_TRACK=true in your environment. │
│                                                                   │
│ Access http://127.0.0.1:7861                                      │
╰───────────────────────────────────────────────────────────────────
```
But I've received the following error either if I select a new flow or an old one:

![image](https://github.com/user-attachments/assets/48beef14-297f-4ea7-bd70-89d0e3d92c78)

**Comment by RomualdoGobbo** [comment]
Hi All,
re-traying many times and with the button "Reset Application" and clearing the cache the error was solved.
Now the system works fine!
Thank you a lot.

Ciao Romualdo

**Comment by carlosrcoelho** [comment]
@RomualdoGobbo 


Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
