### ISSUE TITLE
Error building Component CSVAgent

### ISSUE THREAD

**Issue by eemirtekin** [langflow-ai/langflow#3589]
### Bug Description

I am getting the error below. 

Error Building Component
Error building Component CSVAgent: langchain.agents.agent.AgentExecutor() got multiple values for keyword argument 'max_iterations'

### Reproduction
```
from langchain_experimental.agents.agent_toolkits.csv.base import create_csv_agent

from langflow.base.agents.agent import LCAgentComponent
from langflow.field_typing import AgentExecutor
from langflow.inputs import HandleInput, FileInput, DropdownInput


class CSVAgentComponent(LCAgentComponent):
    display_name = "CSVAgent"
    description = "Construct a CSV agent from a CSV and tools."
    documentation = "https://python.langchain.com/docs/modules/agents/toolkits/csv"
    name = "CSVAgent"

    inputs = LCAgentComponent._base_inputs + [
        HandleInput(name="llm", display_name="Language Model", input_types=["LanguageModel"], required=True),
        FileInput(name="path", display_name="File Path", file_types=["csv"], required=True),
        DropdownInput(
            name="agent_type",
            display_name="Agent Type",
            advanced=True,
            options=["zero-shot-react-description", "openai-functions", "openai-tools"],
            value="openai-tools",
        ),
    ]

    def build_agent(self) -> AgentExecutor:
        return create_csv_agent(llm=self.llm, path=self.path, agent_type=self.agent_type, **self.get_agent_kwargs())

```
### Expected behavior

I want to have a conversation with the CSV file.

### Operating System

Ubuntu 22.04.4 LTS

### Langflow Version

1.0.17

### Python Version

3.10

### Screenshot

![Screenshot 2024-08-28 at 14 02 30](https://github.com/user-attachments/assets/21260913-7edb-410a-9013-37034a575bf6)

**Comment by eemirtekin** [comment]
It doesn't work.

**Comment by carlosrcoelho** [comment]
@eemirtekin 

Please try to use this component:
[CSV Agent.json](https://github.com/user-attachments/files/16799595/CSV.Agent.json)

Please let me know if it works for you.

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
