### ISSUE TITLE
Running Langflow on local server

### ISSUE THREAD

**Issue by tejaspatil0407** [langflow-ai/langflow#3609]
### Bug Description

I am running langflow on an Ubuntu SSH server, and on running the docker it is hosting langflow on 0.0.0.0/7860 how can I change this so it runs on the IP address of the ubuntu machine?

### Reproduction

...

### Expected behavior

...

### Operating System

ubuntu linux 22.04.4

### Langflow Version

1.09

### Python Version

None

**Comment by tejaspatil0407** [comment]
@dosu can you give me the all the instructions to do this? which folder do i docker compose up from? docker_compose_example or deployment?

**Comment by tejaspatil0407** [comment]
it is still running at 0.0.0.0:7860

**Comment by tejaspatil0407** [comment]
@dosu it is still running on 0.0.0.0:7860

**Comment by edwinjosechittilappilly** [comment]
@tejaspatil0407  Do you still face the same issue after updating the .env file?

If you port 7860 is open to public I believe you should be able to get access.
Please let me know if you need any support.

Also It would be great if you could provide the step by step process that you took, so I could assist you better.

**Comment by edwinjosechittilappilly** [comment]
Closing the issue. Please reopen it if you face any further problems.
