### ISSUE TITLE
Cannot build Conditional Router Component

### ISSUE THREAD

**Issue by httplups** [langflow-ai/langflow#3611]
### Bug Description

![Screenshot from 2024-08-29 08-24-02](https://github.com/user-attachments/assets/f837483b-82b1-4256-b0ec-4d965a295762)
Hello. I cannot build this component here. It was working before, but now it gets stuck on building for many hours. The problem seems to be related to the input message be sent from a prompt template. When I type the input message directly it builds the component correctly.

### Reproduction

1. Create a prompt template with some text
2. Create the conditional router - with the input text as 'Yes' and the Match text as 'Yes', so it will be True (this is optional)
3. Input the prompt template as the message to be forwarded
4. Try to build the component

### Expected behavior

You could not build the component, it will get stuck on building

### Who can help?

@italojohnny @ogabrielluiz @nic

### Operating System

Ubuntu 20.04.6 LTS

### Langflow Version

1.0.17

### Python Version

3.11

### Flow File

[Conditional Router problem.json](https://github.com/user-attachments/files/16798332/Conditional.Router.problem.json)

**Comment by Cristhianzl** [comment]
on it

**Comment by Cristhianzl** [comment]
Hey @httplups,

I was speaking with my colleagues, and we are concerned about the situation with this component. We are working to ensure it works in all scenarios on Langflow.

For now, this component works when used in combination with different workflows. I’m attaching a flow example that uses this component, so you can check how it works and see if it fits your needs.

Please take a look at the advanced information on the components if you have any doubts, and refer to our [documentation](https://docs.langflow.org/).

Thanks!

<img width="321" alt="image" src="https://github.com/user-attachments/assets/f08fa78b-8026-4746-a743-2766e6955db3">

Component using Conditional Router ->
[Decision Flow - Conditional Router Component.json](https://github.com/user-attachments/files/16898448/Decision.Flow.-.Conditional.Router.Component.json)

**Comment by httplups** [comment]
Hi, I am also having trouble to using this component when I have a true and false route and just want that one of them to be executed. The problem is that the output message feeds a prompt template, that is, I want to choose between two prompt templates. But the prompt template does not seems to stop. actually it works even those the router is false.

**Comment by cristian473** [comment]
i have the same problem as httplups said
any found a solution?

**Comment by Cristhianzl** [comment]
hey @httplups @cristian473 

Thank you for your patience. Please see my response below. While we hope to address this issue in future releases to ensure the component functions as expected, for now, it will only work under the conditions listed below. 

Apologies for the inconvenience.

> Hey @httplups,
> 
> I was speaking with my colleagues, and we are concerned about the situation with this component. We are working to ensure it works in all scenarios on Langflow.
> 
> For now, this component works when used in combination with different workflows. I’m attaching a flow example that uses this component, so you can check how it works and see if it fits your needs.
> 
> Please take a look at the advanced information on the components if you have any doubts, and refer to our [documentation](https://docs.langflow.org/).
> 
> <img alt="image" width="321" src="https://private-user-images.githubusercontent.com/72977554/364892361-f08fa78b-8026-4746-a743-2766e6955db3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1Nzc1MjcsIm5iZiI6MTcyNjU3NzIyNywicGF0aCI6Ii83Mjk3NzU1NC8zNjQ4OTIzNjEtZjA4ZmE3OGItODAyNi00NzQ2LWE3NDMtMjc2NmU2OTU1ZGIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDEyNDcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkZjJlNzRkZTEwZDU3YTZmZjU2MWUzNWU3YmVlZTE4Zjg0ZjYzNTA0NDI0ZjllMGYzMmQ4MzVkMWEwZGFiZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DYcY8ZFlcBLY7u7-FHlLszGwp9qba13I5qZflYA4qF4">
> Component using Conditional Router -> [Decision Flow - Conditional Router Component.json](https://github.com/user-attachments/files/16898448/Decision.Flow.-.Conditional.Router.Component.json)
> 
> Thanks!
