### ISSUE TITLE
Can I create a Folder field?

### ISSUE THREAD

**Issue by SAIL-Fang** [langflow-ai/langflow#3625]
### Feature Request

In langflow, we can use fields (or buttons?) from the file component. Select the file to upload from the local path. But now I want to select a local path instead of a file, where should I change it (so I can get this selected folder path internally)?

![image](https://github.com/user-attachments/assets/67a55b08-1ee4-4e0d-bdf1-d8a9e34f0db4)
![image](https://github.com/user-attachments/assets/0f9cf824-8362-4bad-a15f-60ac89cd04b8)

### Motivation

When I need to copy the absolute path from local every time I change the path, it doesn't feel very elegant, wish I could provide a Folder field. If possible, please tell me where to add this field in the source code before submitting it so that I can use it right away. Thank you very much!

**Comment by Cristhianzl** [comment]
Hi @SAIL-Fang,

We have a component that recursively loads files from a path. Please take a look to see if it fits your needs.

For the file component you are using, it’s currently not possible to directly enter the path. First, you need to call another upload endpoint to upload the file.

We can consider an improvement for this in the future, but for now, please check out the Directory Component.

![image](https://github.com/user-attachments/assets/c4388e8b-c81b-489b-a5ea-b84293e19e57)

Thanks!

**Comment by pseudo-usama** [comment]
@Cristhianzl The `Directory` component functions smoothly on a local machine. However, when Langflow is hosted on a server, an issue arises since the folder is located on the local machine rather than the server. It would be ideal if it featured the same folder picker dialog as the file component.

**Comment by pseudo-usama** [comment]
@SAIL-Fang Have you found a workaround?
