### ISSUE TITLE
Create List faz perder todo o flow

### ISSUE THREAD

**Issue by cwgbittencourt** [langflow-ai/langflow#3638]
![image](https://github.com/user-attachments/assets/b319cfe3-0349-49ee-86fb-04d442944a09)
Ao arrastar o componente Create List para o flow recebo a mensagem de erro abaixo e o flow esta perdido pois não abre mais.
![image](https://github.com/user-attachments/assets/b9fe79ce-cb4d-4d1d-afcd-aa51db2bb010)

**Comment by carlosrcoelho** [comment]
@cwgbittencourt 
Estou rodando o Langflow local, versao 1.0.17. Testei e funcionou normal.

https://github.com/user-attachments/assets/1005c508-af37-4aee-978a-37d8b9a09c27
