### ISSUE TITLE
[FEATURE] Show Crew AI messages during Sequential work. Promising platform. 

### ISSUE THREAD

**Issue by blissiraDC** [langflow-ai/langflow#3640]
### Feature Request

AS per the title will there be a way to show Crew AI agent messages as they complete there work then the final output

### Motivation

Or is this possible now? I am a long term Flowise user, the Crew AI feature interests me but while no agent messages are displayed its still quite a way off from Flowise (AgentFlows, Sequential Agents) But I can see huge potential with Crew AI

**Comment by shanmu-raoyunfei** [comment]
Dynamic output of agent process work records will help user experience

**Comment by konradbjk** [comment]
true to that! though you can modify the code of the agent to display it on the console logs
