### ISSUE TITLE
[#IADevsIndia] Incorrect status message on incomplete/cancelled upload action

### ISSUE THREAD

**Issue by vvtrip** [langflow-ai/langflow#3642]
### Bug Description

'Uploaded Successfully' incorrectly pops up while choosing to upload file and pressing cancel button on the file up load dialog. 
It is a cosmetic issue but might be having underlying unexpected behavior in other cases not visible upfront. Please check attachment.

### Reproduction

In the langflow landing patch dashboard, click on upload icon in the left side bar in folder section. Upon pop up of file upload dialogbox, click cancel.

### Expected behavior

There should not be any message in case of incomplete/cancelled upload attempt

### Operating System

Windows 11

### Langflow Version

1.0.17

### Python Version

3.10

### Screenshot

![image](https://github.com/user-attachments/assets/62e264ae-6fe3-4361-ae93-228ddeed56d9)

**Comment by Cristhianzl** [comment]
hey @vvtrip hope you are doing fine.

Please follow up this PR: #3659

Thanks for your feedback.

**Comment by vvtrip** [comment]
Thanks @Cristhianzl for taking this up. Happy to see this change in newer version!
