### ISSUE TITLE
Create Data and Update Data do not work

### ISSUE THREAD

**Issue by Banbury** [langflow-ai/langflow#3644]
### Bug Description

The input nodes of Create Data do not accept any input from any text output. Looking into the code, the inputs of Create Data accept "Text" and "Data". But text outputs from other nodes have the type Message. The same goes for the text input on Update Data.

Connecting a Create Data node with an Update Data node produces the error `Component  field 'data'  might not be a valid input.`, if you press the play button on either node.

### Reproduction

See description.

### Expected behavior

Since the API Request node requires data as input, I would like those nodes to work.

### Operating System

Windows 11

### Langflow Version

v1.0.17

### Python Version

3.12

**Comment by carlosrcoelho** [comment]
@Banbury 

Correct me if I'm wrong, is that what you're trying to do?

Please share the flow that you're trying to create.

<img width="1358" alt="image" src="https://github.com/user-attachments/assets/8b12b1a4-8910-4648-8429-31d44bab250f">

**Comment by maxpaynebupt** [comment]
> @Banbury
> 
> Correct me if I'm wrong, is that what you're trying to do?
> 
> Please share the flow that you're trying to create.
> 
> <img alt="image" width="1358" src="https://private-user-images.githubusercontent.com/80289056/363718798-8b12b1a4-8910-4648-8429-31d44bab250f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNTg0NzEsIm5iZiI6MTcyNTM1ODE3MSwicGF0aCI6Ii84MDI4OTA1Ni8zNjM3MTg3OTgtOGIxMmIxYTQtODkxMC00NjQ4LTg0MjktMzFkNDRiYWIyNTBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDEwMDkzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwNWIzZWMwZWFjNmUzY2ViNWM3ZTU4MWEzMzkxZjFiN2JmMDcyMjVjM2Q4N2I4MzIyNDQzOTU4NGRmMDQ1ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FwJw_Ebbb8EnqFGxSTKrrwUPiQHNxnzMHz5_K-GtCRo">

how to update data, the 'update data' component's 'New Data' input type is not text.

**Comment by carlosrcoelho** [comment]
The Update Data component seems to be outdated. I will direct the team to perform a new update on it soon.
