### ISSUE TITLE
langflow suddenly crashed

### ISSUE THREAD

**Issue by alex-ge123** [langflow-ai/langflow#3646]
### Bug Description

langflow suddenly crashed
![微信图片_20240902143057](https://github.com/user-attachments/assets/130b8415-a9f6-4e2e-bfc0-cb4adc5e3bbd)

### Reproduction

langflow suddenly crashed
![Uploading 微信图片_20240902143057.png…]()

### Expected behavior

langflow suddenly crashed
![Uploading 微信图片_20240902143057.png…]()

### Operating System

windows 

### Langflow Version

1.0.15

### Python Version

3.11

**Comment by carlosrcoelho** [comment]
@alex-ge123 

Could you please share your flow?

**Comment by carlosrcoelho** [comment]
Hey @alex-ge123 
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
