### ISSUE TITLE
Why the global variable of Generic type is encryted?

### ISSUE THREAD

**Issue by songjinu** [langflow-ai/langflow#3648]
Why the global variable of Generic type is encryted?
I wanna update value of the global variable of Generic type.
I can not update value of the global variable of Generic type on DB.

**Comment by italojohnny** [comment]
Hi, @songjinu . How are you?

All values are encrypted to protect them in the database. You might then wonder, 'What's the difference between a generic type and a credential?'

In the code, we take extra care with credential-type variables to ensure they are never exposed while being handled.

Regarding your need to update the value, please follow issue #3462, which will address the problem. However, if you feel confident, you can edit it directly through the backend API, which already supports this operation. If not, as a temporary solution, try deleting and recreating the value.

If you still have any questions or encounter any issues, please open a new issue
