### ISSUE TITLE
Error Building Component Chroma DB

### ISSUE THREAD

**Issue by EdilsonPs** [langflow-ai/langflow#3650]
### Bug Description

When I use Chroma DB on Langflow, I receive this return :Error building Component Chroma DB: 

HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000027D24358890>: Failed to establish a new connection: [WinError 10061], 

Hello everyone, I'm new here. I've already disabled the firewall, allowed access to port 8080 in the control panel and it didn't work, I also tested AstraDB and the same error occurs, what else should I configure on my machine, pls?

### Reproduction

I can't reproduce this error, but sent a print   
![image](https://github.com/user-attachments/assets/c2131a69-01ab-4e17-af4d-4b3e0929b1ca)

### Expected behavior

The connection with Chromadb should occur normally according to the tutorials

### Who can help?

@ogabrielluiz, @nicoloboschi

### Operating System

Windows 10

### Langflow Version

1.0.17

### Python Version

None

### Screenshot

3.11.9

### Flow File

![image](https://github.com/user-attachments/assets/2e5a3f39-c5c6-44bd-9be4-1445b9ab2747)

**Comment by Cristhianzl** [comment]
Hi @EdilsonPs,

I hope you're doing well.

It appears that your firewall may be blocking write access to the directory where you're trying to create your database.

If you're running Langflow locally on the main branch, please try the following:

1. Open Visual Studio Code as an administrator.
2. Create a simple directory named langflow in the root folder of your project.
3. Ensure that the application running Langflow has the necessary permissions.

 ![image](https://github.com/user-attachments/assets/20138970-4641-4480-a00f-bf9a92a0a2fb)

![image](https://github.com/user-attachments/assets/494f6f6d-6e12-4c23-ab40-694376411bdf)



- If you're using Docker, make sure to grant admin privileges to the Docker application.

- For those using Langflow with pip and another package manager (like Conda), create and activate your virtual environment. Additionally, open your terminal with administrator permissions when installing Langflow.

Please try these steps and let me know if you can run ChromaDB successfully.

Thank you!

**Comment by EdilsonPs** [comment]
Thanks for your answer @Cristhianzl, it worked here!

**Comment by Cheangys** [comment]
Hi, would appreciate some help here. I encounter the exact same error as EdilsonPs earlier. I am running on Windows 11, Langflow v1.0.17. The Langflow is running in a virtual environment with python 3.12.
![image](https://github.com/user-attachments/assets/017fd44f-e723-40c7-af9e-ea30d08e7f94)

I have tried to troubleshoot to run the command to check whether the chroma-server is running but to no avail as I am not sure how to run this. I have also tried to run the conda and VS Code and terminal in administrator mode but the error still persist. I have also tried to disable the firewall.

Thanks in advanced.

**Comment by Cristhianzl** [comment]
hi @Cheangys 
You are experiencing the same issue.
The "Persist Directory" field should not be a 'C:/...' directory. This can results on some Windows errors blocking the action.
Try to tip just a random name on the "Persist Directory" like "Langflow" instead of the full directory path.

Thanks!

**Comment by Cheangys** [comment]
> hi @Cheangys You are experiencing the same issue. The "Persist Directory" field should not be a 'C:/...' directory. This can results on some Windows errors blocking the action. Try to tip just a random name on the "Persist Directory" like "Langflow" instead of the full directory path.
> 
> Thanks!

Hi @Cristhianzl, thanks for the suggestion. Unfortunately the error persisted. I even tried to even leaving the "Persist Directory" blank but the error still persisted. Just wondering if you have any idea how to resolve this? Thanks
