### ISSUE TITLE
Is there a way to convert a LLM output text to data then we can parse it?

### ISSUE THREAD

**Issue by maxpaynebupt** [langflow-ai/langflow#3665]
### Bug Description

It seems , there is no way to convert a LLM's output JSON string to JSON object and store it to some place and reuse it in some component later.

### Reproduction

It seems , there is no way to convert a LLM's output JSON string to JSON object and store it to some place and reuse it in some component later.

### Expected behavior

There should be some component to parse the text to data and then we can update and visit it just like a dict.

### Operating System

Docker image v1.0.16

### Langflow Version

v1.0.16

### Python Version

None

**Comment by maxpaynebupt** [comment]
> Langflow provides functionality to convert LLM output text to data structures like JSON objects. The `JSONCleaner` component includes a method `_validate_json` that uses `json.loads` to validate and parse JSON strings [[1]](https://github.com/langflow-ai/langflow/blob/main/src/backend/base/langflow/components/prototypes/JSONCleaner.py). Additionally, the `ParseDataComponent` can convert data into plain text following a specified template, which can be useful for handling JSON data [[2]](https://github.com/langflow-ai/langflow/blob/main/src/backend/base/langflow/initial_setup/starter_projects/Document QA.json).
> 
> For storing and reusing data, Langflow's memory management feature allows every chat message to be stored, and a single flow can have multiple memory sessions. This enables the creation of multiple “memories” for agents to store and recall specific information as needed [[3]](https://github.com/langflow-ai/langflow/blob/main/docs/docs/What%E2%80%99s-New/whats-new-a-new-chapter-langflow.md).
> 
> You can use these components to parse the LLM's output JSON string into a JSON object and store it for later use.
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

the output of "JSON Cleaner' is text, it can not be handled by "Parse Data'

**Comment by maxpaynebupt** [comment]
> Langflow provides functionality to convert LLM output text to data structures like JSON objects. The `JSONCleaner` component includes a method `_validate_json` that uses `json.loads` to validate and parse JSON strings [[1]](https://github.com/langflow-ai/langflow/blob/main/src/backend/base/langflow/components/prototypes/JSONCleaner.py). Additionally, the `ParseDataComponent` can convert data into plain text following a specified template, which can be useful for handling JSON data [[2]](https://github.com/langflow-ai/langflow/blob/main/src/backend/base/langflow/initial_setup/starter_projects/Document QA.json).
> 
> For storing and reusing data, Langflow's memory management feature allows every chat message to be stored, and a single flow can have multiple memory sessions. This enables the creation of multiple “memories” for agents to store and recall specific information as needed [[3]](https://github.com/langflow-ai/langflow/blob/main/docs/docs/What%E2%80%99s-New/whats-new-a-new-chapter-langflow.md).
> 
> You can use these components to parse the LLM's output JSON string into a JSON object and store it for later use.
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

the output of "JSON Cleaner' is text, it can not be handled by "Parse Data' . @dosu

**Comment by maxpaynebupt** [comment]
> If the text output of the `JSONCleaner` component cannot be processed by the `ParseDataComponent`, you can handle it by catching the exception and logging the error or taking alternative actions. Here is an example of how you might handle this situation:
> 
> ```python
> try:
>     cleaned_json_message = json_cleaner.clean_json()
>     cleaned_json_str = cleaned_json_message.text
>     # Attempt to process the cleaned JSON string with ParseDataComponent
>     parsed_data = parse_data_component.parse(cleaned_json_str)
> except ValueError as e:
>     # Handle the error if JSONCleaner fails
>     print(f"Error cleaning JSON string: {e}")
>     # Take alternative actions, such as logging the error or using a default value
>     # For example:
>     # log_error(e)
>     # parsed_data = default_value
> except Exception as e:
>     # Handle any other exceptions that may occur
>     print(f"An unexpected error occurred: {e}")
>     # Take alternative actions
>     # For example:
>     # log_error(e)
>     # parsed_data = default_value
> ```
> 
> In this code, `json_cleaner` is an instance of the `JSONCleaner` component, and `parse_data_component` is an instance of the `ParseDataComponent`. The `try` block attempts to clean the JSON string and then process it. If an error occurs during the cleaning process, it is caught, and alternative actions can be taken.
> 
> Additionally, ensure that the data types and connections between components are correctly configured. For instance, the `ParseDataComponent` expects input of type `Data` and outputs a `Message`. Make sure the data flow aligns with these expectations to avoid processing errors [[1]](https://github.com/langflow-ai/langflow/blob/main/src/backend/base/langflow/components/prototypes/JSONCleaner.py)[[2]](https://github.com/langflow-ai/langflow/blob/main/src/backend/base/langflow/initial_setup/starter_projects/Blog Writer.json)[[3]](https://github.com/langflow-ai/langflow/blob/main/src/backend/base/langflow/initial_setup/starter_projects/Document QA.json).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

Really very frustrating, If there is a variable setter and getter, things can be much more easier.

**Comment by cristian473** [comment]
hi maxpaynebupt!
i solved this creating a custom component that takes a text and returns a data object
with the key that you wish (value in my case) and the text as value

my code below:

```
# from langflow.field_typing import Data
from langflow.custom import Component
from langflow.io import MessageTextInput, Output
from langflow.schema import Data


class TextToData(Component):
    display_name = "Text to data object"
    description = "This component takes a MessageTextInput and parse it into a data object"
    icon = "custom_components"
    name = "TextToData"

    inputs = [
        MessageTextInput(name="input_value", display_name="Input Value", value="Hello, World!"),
    ]

    outputs = [
        Output(display_name="Output", name="output", method="build_output"),
    ]

    def build_output(self) -> Data:
        data = Data(value=self.input_value)
        self.status = data
        return data
```


<img width="563" alt="Captura de pantalla 2024-09-16 a la(s) 10 15 08 a  m" src="https://github.com/user-attachments/assets/6b436366-3106-4527-a529-d2031eeba01b">

good luck!
