### ISSUE TITLE
Stop button not working on backend.

### ISSUE THREAD

**Issue by lucaseduoli** [langflow-ai/langflow#3670]
### Bug Description

The stop button only stops the request on the frontend.

### Reproduction

1. Create a flow
2. Create a custom component
3. Add a time.sleep(1000) into the build function of the component
4. Run the component
5. Stop the build
6. Check that the backend is still running the flow, preventing other calls to be made.

### Expected behavior

The backend should stop the build so that we can make other calls to the backend.

### Who can help?

@italojohnny 

### Operating System

Macbook M3 Pro

### Langflow Version

main

### Python Version

3.10

**Comment by italojohnny** [comment]
This issue is already resolved!
