### ISSUE TITLE
Langflow docker não conecta com Qdrant

### ISSUE THREAD

**Issue by lucas0usa** [langflow-ai/langflow#3682]
### Bug Description

O Langflow quando rodado a partir da Imagem Docker não consegue se conectar com o container do Qdrant, recebo o seguinte erro: "Error building Component Qdrant: [Errno 111] Conection refused".
Percebi que rodando o Langflow local e com a instancia do Qdrant via docker, Langflow produz os resultados esperados. Porém Rodando o langflow via Docker ele não consegue se conectar.

### Reproduction

Error building Component Qdrant: [Errno 111] Conection refused

### Expected behavior

ok

### Operating System

windows 11

### Langflow Version

1.0.17

### Python Version

None

**Comment by lucas0usa** [comment]
Testei, mas ainda persiste o erro

**Comment by Biskwit** [comment]
same problem here

**Comment by carlosrcoelho** [comment]
It seems the problem is more related to docker than to Langflow itself, for you to connect with qdrant, the langflow network needs to have access to it, it means you need to configure your deployment as a bridge deployment, then refer to the qdrant container using your docker namespace.

`version: "3.8"

services:
  langflow:
    image: langflowai/langflow:latest # or another version tag on https://hub.docker.com/r/langflowai/langflow 
    pull_policy: always               # set to 'always' when using 'latest' image
    ports:
      - "7860:7860"
    depends_on:
      - postgres
      - qdrant
    environment:
      - LANGFLOW_DATABASE_URL=postgresql://langflow:langflow@postgres:5432/langflow
      - QDRANT_URL=http://qdrant:6333 # URL to connect to Qdrant service
      # Add any additional environment variables as needed
    volumes:
      - langflow-data:/app/langflow
    networks:
      - app-network

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: langflow
      POSTGRES_PASSWORD: langflow
      POSTGRES_DB: langflow
    ports:
      - "5432:5432"
    volumes:
      - langflow-postgres:/var/lib/postgresql/data
    networks:
      - app-network

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"  # HTTP API
      - "6334:6334"  # gRPC API (optional)
    volumes:
      - qdrant-data:/qdrant/storage
    environment:
      QDRANT__SERVICE__GRPC_PORT: 6334
      QDRANT__LOG__LEVEL: info
      # You can add more Qdrant-specific environment variables here
    networks:
      - app-network

volumes:
  langflow-postgres:
  langflow-data:
  qdrant-data:

networks:
  app-network:
    driver: bridge`
