### ISSUE TITLE
Error building Component Chroma DB: 'data'

### ISSUE THREAD

**Issue by LcsCarlim** [langflow-ai/langflow#3700]
### Bug Description

Hello guys. 
I've been facing a problem for days, but I never resolve it. Could anyone help me?

### Reproduction

![imagem_2024-09-05_140510483](https://github.com/user-attachments/assets/1a75d0ce-3028-4b24-b944-3f49ec79cb74)

### Expected behavior

Is there a character limit in txt?

### Operating System

Windows

### Langflow Version

Last

### Python Version

None

**Comment by LcsCarlim** [comment]
I keep getting the same error...

**Comment by carlosrcoelho** [comment]
Hey @LcsCarlim 

I tried to replicate your process and it seems there is an issue with Mistral Embedding. If you try with another Embedding (like OpenAI), it should work. We need to take some time to debug the problem.

**Comment by LcsCarlim** [comment]
Obrigado por me responder, @carlosrcoelho! Mas o Embedding do OpenAI é pago ou tem alguma forma de ser gratuito?

**Comment by carlosrcoelho** [comment]
Sim, o OpenAI é pago. Você pode usar Ollama Embeddings que roda localmente. 

Antes te rodar o componente, tenha certeza que ele esteja rodando na sua máquina.

Espero ter te ajudado.
