### ISSUE TITLE
Standardize Bubble Colors and Merge Incompatible Text Connectors

### ISSUE THREAD

**Issue by edwinjosechittilappilly** [langflow-ai/langflow#3701]
### Bug Description

Description:
When loading 4 different components with text input (either as input or output), I noticed that the identification is displayed using a dark blue bubble for text types. However, different components have varying supported connectors despite these inputs all being identified as “Text.”

Upon reviewing the code, I found that both “message input” and “string” are treated as text types, but these connectors are often incompatible, even though they should be similar.

### Reproduction

1. Load basic prompting flow
2. Turn on session id in chat input
3. Load id generator component
4. Load Text input component
5. Load Listen component.

Try connecting the blue bubbles.

### Expected behavior

- Components with “Text” inputs/outputs have dark blue bubbles.
- Despite having the same bubble color, some components are not able to connect due to differing connector compatibility (e.g., “String” type vs “Message Text” type).

### Operating System

Mac os

### Langflow Version

1.0.17

### Python Version

3.12

**Comment by edwinjosechittilappilly** [comment]
https://github.com/user-attachments/assets/5507783a-793d-4916-9914-f9c608f8ffaf

**Comment by lucaseduoli** [comment]
Hello! The types should be fixed now. If you find any more problems, feel free to reopen this issue.
