### ISSUE TITLE
Disabling autologin so I can use authentication methods.

### ISSUE THREAD

**Issue by bohemiancode-x** [langflow-ai/langflow#3707]
### Bug Description

The docs on this seems to be outdated. Any help please?

### Reproduction

Disable autologin on the frontend?

### Expected behavior

Signout button should show up and login page should be accessible.

### Operating System

Windows

### Langflow Version

1.0.17

### Python Version

None

**Comment by bohemiancode-x** [comment]
@dosu is the .env file in the frontend or backend directory?

**Comment by bohemiancode-x** [comment]
@dosu the command " langflow run --env-file .env " should be run in what directory?

**Comment by bohemiancode-x** [comment]
@dosu does that mean the langflow cli has to be installed in my root directory? otherwise the command won't be recognized

**Comment by bohemiancode-x** [comment]
okay great. while I have you, is there a reason for this console error "use-get-autologin.ts:13  GET http://localhost:3000/api/v1/auto_login 400 (Bad Request) " ?

**Comment by bohemiancode-x** [comment]
@dosu okay great. while I have you, is there a reason for this console error "use-get-autologin.ts:13 GET http://localhost:3000/api/v1/auto_login 400 (Bad Request) " ?

**Comment by bohemiancode-x** [comment]
@dosu okay back to the LANGFLOW_AUTO_LOGIN variable. does placing it in the environment variables section of docker compose yml also work?

**Comment by carlosrcoelho** [comment]
@bohemiancode-x 

Do you need any assistance with this case? If not, please let us know if this issue can be closed.

**Comment by bohemiancode-x** [comment]
@dosu using langflow run, will changes made to the backend code reflect on reload?

**Comment by bohemiancode-x** [comment]
what is the full command to activate reload

**Comment by bohemiancode-x** [comment]
@dosu what is the full command to activate reload

**Comment by bohemiancode-x** [comment]
@dosu throws error: no such option --reload

**Comment by bohemiancode-x** [comment]
@dosu this command should be run in what directory? and how do i use the env file?

**Comment by bohemiancode-x** [comment]
@dosu how do i make sure or confirm the reload function is working?

**Comment by bohemiancode-x** [comment]
@dosu how should the frontend be run to make it responsive to the backend changes?

**Comment by bohemiancode-x** [comment]
@dosu pulled the latest update from main and the app keeps crashing from this error: Uncaught TypeError: examples.find is not a function
    at GetStartedComponent (index.tsx:25:22)

**Comment by bohemiancode-x** [comment]
@dosu I checked the network tab and the flows/basic_examples endpoint returns an html page instead of the a flowType[].

**Comment by adrianlasota** [comment]
@dosu what about kubernetes deployment? how to set variables?
