### ISSUE TITLE
OpenAI Embedding Block usage with AstraDB block throws an error even with valid keys

### ISSUE THREAD

**Issue by orchadev** [langflow-ai/langflow#3717]
### Bug Description

The error thrown when the flow was run with valid openai keys is as follows

```
ValueError: Error initializing AstraDBVectorStore: Error code: 403 - {'error':
                             {'message': 'Project proj_ does not have access to
                             model text-embedding-ada-002', 'type': 'invalid_request_error', 'param':
                             None, 'code': 'model_not_found'}
```
  
  There is a code line in AstraDB block component  
  ```
 HandleInput(
            name="embedding",
            display_name="Embedding or Astra Vectorize",
            input_types=["Embeddings", "dict"],
            info="Allows either an embedding model or an Astra Vectorize configuration.",   # TODO: This should be optional, but need to refactor langchain-astradb first.  
) 
```
with a todo line 
 _TODO: This should be optional but need to refactor langchain-astradb first._              
as in the statement assumed that embeddings are optional and uses astradb embeddings which is still in preview mode

##TRACE OUTPUT

langflow\graph\verte │
                             │ x\base.py:690 in _build_results                                             │
                             │                                                                             │
                             │   687 │                                                                     │
                             │   688 │   async def _build_results(self, custom_component, custom_params,   │
                             │       fallback_to_env_vars=False):                                          │
                             │   689 │   │   try:                                                          │
                             │ ❱ 690 │   │   │   result = await initialize.loading.get_instance_results(   │
                             │   691 │   │   │   │   custom_component=custom_component,                    │
                             │   692 │   │   │   │   custom_params=custom_params,                          │
                             │   693 │   │   │   │   vertex=self,                                          │
                             │                                                                             │
                             │ C:\Users\datao\anaconda3\envs\opencv\Lib\site-packages\langflow\interface\i │
                             │ nitialize\loading.py:60 in get_instance_results                             │
                             │                                                                             │
                             │    57 │   │   if base_type == "custom_components":                          │
                             │    58 │   │   │   return await build_custom_component(params=custom_params, │
                             │       custom_component=custom_component)                                    │
                             │    59 │   │   elif base_type == "component":                                │
                             │ ❱  60 │   │   │   return await build_component(params=custom_params,        │
                             │       custom_component=custom_component)                                    │
                             │    61 │   │   else:                                                         │
                             │    62 │   │   │   raise ValueError(f"Base type {base_type} not found.")     │
                             │    63                                                                       │
                             │                                                                             │
                             │ C:\Users\datao\anaconda3\envs\opencv\Lib\site-packages\langflow\interface\i │
                             │ nitialize\loading.py:147 in build_component                                 │
                             │                                                                             │
                             │   144 ):                                                                    │
                             │   145 │   # Now set the params as attributes of the custom_component        │
                             │   146 │   custom_component.set_attributes(params)                           │
                             │ ❱ 147 │   build_results, artifacts = await custom_component.build_results() │
                             │   148 │                                                                     │
                             │   149 │   return custom_component, build_results, artifacts                 │
                             │   150                                                                       │
                             │                                                                             │
                             │ C:\Users\datao\anaconda3\envs\opencv\Lib\site-packages\langflow\custom\cust │
                             │ om_component\component.py:570 in build_results                              │
                             │                                                                             │
                             │   567 │                                                                     │
                             │   568 │   async def build_results(self):                                    │
                             │   569 │   │   if self._tracing_service:                                     │
                             │ ❱ 570 │   │   │   return await self._build_with_tracing()                   │
                             │   571 │   │   return await self._build_without_tracing()                    │
                             │   572 │                                                                     │
                             │   573 │   async def _build_results(self):                                   │
                             │                                                                             │
                             │ C:\Users\datao\anaconda3\envs\opencv\Lib\site-packages\langflow\custom\cust │
                             │ om_component\component.py:560 in _build_with_tracing                        │
                             │                                                                             │
                             │   557 │   │   inputs = self.get_trace_as_inputs()                           │
                             │   558 │   │   metadata = self.get_trace_as_metadata()                       │
                             │   559 │   │   async with self._tracing_service.trace_context(self, self.tra │
                             │       metadata):                                                            │
                             │ ❱ 560 │   │   │   _results, _artifacts = await self._build_results()        │
                             │   561 │   │   │   self._tracing_service.set_outputs(self.trace_name, _resul │
                             │   562 │   │                                                                 │
                             │   563 │   │   return _results, _artifacts                                   │
                             │                                                                             │
                             │ C:\Users\datao\anaconda3\envs\opencv\Lib\site-packages\langflow\custom\cust │
                             │ om_component\component.py:592 in _build_results                             │
                             │                                                                             │
                             │   589 │   │   │   │   │   │   _results[output.name] = output.value          │
                             │   590 │   │   │   │   │   │   result = output.value                         │
                             │   591 │   │   │   │   │   else:                                             │
                             │ ❱ 592 │   │   │   │   │   │   result = method()                             │
                             │   593 │   │   │   │   │   │   # If the method is asynchronous, we need to a │
                             │   594 │   │   │   │   │   │   if inspect.iscoroutinefunction(method):       │
                             │   595 │   │   │   │   │   │   │   result = await result                     │
                             │                                                                             │
                             │ C:\Users\datao\anaconda3\envs\opencv\Lib\site-packages\langflow\base\vector │
                             │ stores\model.py:132 in build_base_retriever                                 │
                             │                                                                             │
                             │   129 │   │   if self._cached_vector_store is not None:                     │
                             │   130 │   │   │   vector_store = self._cached_vector_store                  │
                             │   131 │   │   else:                                                         │
                             │ ❱ 132 │   │   │   vector_store = self.build_vector_store()                  │
                             │   133 │   │   │   self._cached_vector_store = vector_store                  │
                             │   134 │   │                                                                 │
                             │   135 │   │   if hasattr(vector_store, "as_retriever"):                     │
                             │                                                                             │
                             │ C:\Users\datao\anaconda3\envs\opencv\Lib\site-packages\langflow\base\vector │
                             │ stores\model.py:25 in check_cached                                          │
                             │                                                                             │
                             │    22 │   │   if self._cached_vector_store is not None:                     │
                             │    23 │   │   │   return self._cached_vector_store                          │
                             │    24 │   │                                                                 │
                             │ ❱  25 │   │   result = f(self, *args, **kwargs)                             │
                             │    26 │   │   self._cached_vector_store = result                            │
                             │    27 │   │   return result                                                 │
                             │    28                                                                       │
                             │ in build_vector_store:223  

                     

### Reproduction

Steps to reproduce 

1. Add AstraDB  block component to the flow 
2. Add endpoint and keys also mention the collection name with namespace if required
3. Attach OpenAI embeddings block component to the AstraDB
4. Select text-embedding-ada-002 in the dropdown or any of the first two options as well
5. Run the flow with proper inputs to AstraDB text input from TextParsing component 

### Expected behavior

Should vectorize and store the output in the vectorize collection of the AstraDB but it fails but when the same is run using ollama it works fine

### Operating System

Windows 11

### Langflow Version

v1.0.17.

### Python Version

3.12

### Screenshot

![image](https://github.com/user-attachments/assets/0d969e4a-ac9e-48c7-af9e-0bd5d25cdcc2)

**Comment by edwinjosechittilappilly** [comment]
Hi @orchadev,

Could you please ensure that you have created a collection in AstraDB with vector support and an embedding size of 1536 dimensions? You can refer to the documentation for detailed instructions on how to create a collection: [Create Collection in AstraDB](https://docs.datastax.com/en/astra-db-serverless/databases/manage-collections.html#create-collection).

I’ve attached a sample image showing the setup:
<img width="755" alt="Screenshot 2024-09-11 at 2 52 17 PM" src="https://github.com/user-attachments/assets/b505adb0-d1e6-434d-80b4-8001708156f9">


Additionally, here is a screenshot of the ingest flow using the text-embedding-ada-002 embeddings. The flow was built successfully, and the data was verified in the AstraDB portal:
<img width="1098" alt="Screenshot 2024-09-11 at 3 00 27 PM" src="https://github.com/user-attachments/assets/2e6b8bdc-c678-4867-bc2e-ef739a6a0a9e">

Thank you!

Please let us know if you face any further issues. I’m happy to help. If not, I will be closing this issue in a couple of days.

**Comment by edwinjosechittilappilly** [comment]
Also please make sure the OpenAI API key have access to the embeddings model: text-embedding-ada-002
