### ISSUE TITLE
Mouse on the canvas does not show 

### ISSUE THREAD

**Issue by pulkit21aug** [langflow-ai/langflow#3720]
### Bug Description

When as end user I try  to drag and drop components and select. The mouse selector is in white color and so is the mouse cursor. 
You need to fix this so that mouse pointer shows on your canvas correctly. Due to this ease of use is not good experience for developers. 

### Reproduction

Just open any project on windows laptop. It is hard to see pointer on canvas while editing components 

### Expected behavior

Mouse should be seen correctly 

### Who can help?

@ogabrielluiz 

### Operating System

Windows 11

### Langflow Version

1.0.16

### Python Version

3.10

**Comment by anovazzi1** [comment]
hey @pulkit21aug I just tried in a windows machine and could not see the behavior you are describing, which browser are you using? can you provide screenshots?

**Comment by pulkit21aug** [comment]
@anovazzi1  the issue is first you see the hand icon , go to another tab do something come back to tab where langflow is running you will not see hand icon on mouse color changes to white which is hardly visible on canvas. I hope  I am able to explain.

**Comment by pulkit21aug** [comment]
@anovazzi1  see the attached screenshot , mouse hand icon is not visible as the color is same as background. 
![Uploading IMG20240918213126.jpg…]()

**Comment by anovazzi1** [comment]
hey @pulkit21aug unfortunally your image was not uploaded right:
![image](https://github.com/user-attachments/assets/0651b1f7-98b1-4639-9d43-812d796bc845)
but if I understood correctly just a ping effect whith a color change when the canvas is visible is enough to solve the problem?

**Comment by PATILYASHH** [comment]
Please assign me to this issue

**Comment by anovazzi1** [comment]
hey @PATILYASHH, thanks for your help, can't wait for your contribution
