### ISSUE TITLE
Your active is not active, please check your billing Error code 429

### ISSUE THREAD

**Issue by scheung38** [langflow-ai/langflow#3726]
### Bug Description

Is Langflow no longer open sourced?

![Screenshot 2024-09-08 at 20 36 04](https://github.com/user-attachments/assets/633719fe-c2fa-4aac-a18d-14754e21dd4c)

### Reproduction

python -m langflow run

Starting Langflow v1.0.17...

Without reading from any .env file

Clicked Playground and says check your billing on our website 

### Expected behavior

After clicking playground I expect to see answer in simple Hello Prompt Example

### Operating System

Mac 12.7.4

### Langflow Version

1.0.17

### Python Version

3.12

### Screenshot

![Screenshot 2024-09-08 at 20 44 05](https://github.com/user-attachments/assets/ef414b8e-a84a-4865-9f0c-397f2ff04f7a)

**Comment by carlosrcoelho** [comment]
Hey @scheung38 

Langflow is open-source, but this error indicates that the model you're running, OpenAI, is paid and requires an active account with credits to run it. You can use local models, like Ollama, by installing it locally and running it in the terminal. When you open Langflow, just drag the Ollama model and start using it. Make sure to pay attention to the version of Ollama to input in the appropriate field of the component. Hope this helps!
