### ISSUE TITLE
Docker tag latest na verdade está baixando a versão 0.0.95

### ISSUE THREAD

**Issue by moiraphill** [langflow-ai/langflow#3731]
### Bug Description

Ao iniciar o docker pela versão da tag langflowai/langflow:latest ele baixa a versão 0.0.95 e gera o erro:

/usr/local/bin/python: No module named langflow

### Reproduction

Ao iniciar o docker pela versão da tag latest

/usr/local/bin/python: No module named langflow

### Expected behavior

O langflow não será iniciado

### Who can help?

@ital

### Operating System

Ubuntu 22.04

### Langflow Version

latest (0.0.95?)

### Python Version

None

**Comment by konradbjk** [comment]
I can confirm running 
```bash
docker pull langflowai/langflow:1.0.17.dev5
```
then when starting it
```bash
$ docker logs app-langflow-1 -f
Starting Langflow v0.0.95...
```

**Comment by italojohnny** [comment]
Apologies for the delay in providing an update or response to this issue. Verifying the current version, this problem no longer occurs. Thank you for your patience and for bringing this to our attention. If you encounter any further issues, please don’t hesitate to let us know
