### ISSUE TITLE
Cannot access to Langflow

### ISSUE THREAD

**Issue by lnthanh** [langflow-ai/langflow#3781]
### Bug Description

I'm installing Langflow version 1.0.18 (the latest one follwing the tutorial [https://docs.langflow.org/getting-started-installation](url) on Ubuntu 22.04.4 LTS. 

I however cannot access to Langflow once I launched `python -m langflow run`.  It showed the "Server is busy" message during several second then redirect me to the /login page which doesn't work at all.

![image](https://github.com/user-attachments/assets/069c5357-dc23-415c-b91b-42ea1a0560ba)

I tried following the docker deployment in [https://docs.langflow.org/deployment-docker](url). It shows a different error message:

![image](https://github.com/user-attachments/assets/62475a4a-b0f7-4b09-be99-4cf4255180f8)

### Reproduction

python -m pip install langflow -U
python -m langflow run

### Expected behavior

The quickstart tutorial and docker deployment should work seamlessly. 

### Operating System

Ubuntu 22.04.4 LTS

### Langflow Version

1.0.18

### Python Version

3.12

**Comment by maces** [comment]
Docker deployment works with version 1.0.17 but not with 1.0.18 as suggested. (The latest and 1.0.18 tag have the same digest currently)

**Comment by italojohnny** [comment]
This is quite odd. I built the 1.0.18 image locally, and it ran successfully... we might be facing issues when generating the image through the release process. I'm investigating this further.

Here are the steps I followed to get it working locally:
1. Cloned the repo
2. In the root of the repo, I ran the command `make docker_build`
3. Once the image was built, I ran `docker run --rm -p 7860:7860 langflow:1.0.18`
4. The container started, and Langflow worked as expected.

**Comment by codenprogressive** [comment]
I'm getting similar `server busy` issue. I noticed this coming up every time I open a new Flow.
I'm deploying Langflow in GCP Cloud Run service.

**Comment by jordanrfrazier** [comment]
I was able to pip install v1.0.18 and run successfully, but I see the issue using the latest Docker build. Re-running the docker push workflow - I'm hoping that a partial deployment resulted in only the main package deployed and not the components.

**Comment by jordanrfrazier** [comment]
Hi all, apologies for the delay. The latest image has been updated - please try to pull and run with 
```
docker pull langflowai/langflow
docker run -it --rm -p 7860:7860 langflowai/langflow:latest
```

**Comment by lnthanh** [comment]
The new docker image works, thank you.
