### ISSUE TITLE
Getting frequent Server is busy messages 

### ISSUE THREAD

**Issue by codenprogressive** [langflow-ai/langflow#3812]
### Bug Description

I have a simple flow, it takes a chat input do some processing (to reproduce the issue, time.sleep 15sec), then output the message. While the flow is building I get the popup message `server is busy` . not sure how to increase triggering the timeout message.

![image](https://github.com/user-attachments/assets/f2c176de-4288-4aa3-934c-12df7674fe8c)

![image](https://github.com/user-attachments/assets/fd93edc5-34a5-4043-9ca3-7981c9ac2097)

### Reproduction

use the attached flow to reproduce the issue.

### Expected behavior

the flow builds without poping up the server busy message.

### Who can help?

@Cristhianzl @lucaseduoli 

### Operating System

Ubuntu

### Langflow Version

1.0.17

### Python Version

3.10

### Flow File

[timeout_server_busy.json](https://github.com/user-attachments/files/17003547/timeout_server_busy.json)

**Comment by codenprogressive** [comment]
I'm already putting worker --timeout to 300. this is not avoiding the server is busy to pop up!

**Comment by carlosrcoelho** [comment]
@codenprogressive 

Have you tried using the version 1.0.18? 

We had this problem in version .17, which was fixed in .18.

**Comment by codenprogressive** [comment]
yes I upgraded to 1.0.18 and this bug was fixed. thank you!
