### ISSUE TITLE
langflow not respecting env file.

### ISSUE THREAD

**Issue by jtoy** [langflow-ai/langflow#3820]
### Bug Description

I start langflow like this:
python3 -m langflow  run  --env-file .langflow.env
it doesn't respect the env file.

Here is the env file I am using:
LANGFLOW_SUPERUSER=admin
LANGFLOW_SUPERUSER_PASSWORD=password
LANGFLOW_AUTO_LOGIN=false
LANGFLOW_HOST=0.0.0.0

### Reproduction

1. pip install langlow

### Expected behavior

it should respect the .env file.

### Operating System

Ubuntu 20.04.4 LTS

### Langflow Version

1.0.18

### Python Version

3.10

**Comment by italojohnny** [comment]
Hi there! How’s it going?
I followed the steps you described, and everything worked perfectly for me. I had to log in using 'admin' and 'password'. I also tried using a different password, and it worked as expected.
Could you be more specific about the error or behavior you're encountering?
