### ISSUE TITLE
Issue with tracing service reinitializing the tracers for nested workflows

### ISSUE THREAD

**Issue by rogeriochaves** [langflow-ai/langflow#3831]
### Bug Description

The `tracing/service.py` service is a singleton, responsible for starting the tracers (langwatch, langsmith, langfuse) whenever a run happens. The problem is, when using a nested workflow, for example with "Flow as a Tool", this service gets reinitialized with a different run id, overriding the last one. As a result, the parent run is stop being tracked (unless for langchain callbacks that go on), and children runs each become new traces, with no run id connection to their parents

Moreover, when two flows are run in parallel, the last one to start sets the runId, so components executed in the first one might also end up being tracked there, as visible on the screenshot on this PR: https://github.com/langflow-ai/langflow/pull/3830

As a solution, the tracing service should probably either stop being a singleton, at least not a global one (could be per run thread) and keep the parent reference OR it could stay a singleton but components during execution would inform their run id during tracing service calls and the singleton would keep the relation of parent and children runs to be passed for the tracing services to correct assemble the tree of calls, either on the same trace or separate tracers per child

### Reproduction

1. Create a simple flow, just input/output, maybe an LLM call in the middle
2. Create another flow and use Flow as a Tool for the first one, tell the tool calling agent to call the tool twice, exactly and only twice
3. You can add print statements on the `def initialize_tracers`, `def _start_traces`, `def _end_traces` and `def _end_all_traces` for the `self.run_id` to see that it always changes to the last one to be executed

### Expected behavior

`_start_traces` should know which run_id it is starting a trace for, so they don't get all tangled up together

### Operating System

Mac OS

### Langflow Version

1.0.18

### Python Version

3.11

### Flow File

[20240917120814097_langflow_flows.zip](https://github.com/user-attachments/files/17027912/20240917120814097_langflow_flows.zip)

**Comment by carlosrcoelho** [comment]
@rogeriochaves 

Thank you for the feedback. Can you check if the issue persists in the latest version of langflow version 1.1.1 ?
Happy to help if the issue still occurs.
