### ISSUE TITLE
Problema com Conectores de Saída ao Criar Text Splitters no Módulo Experimental

### ISSUE THREAD

**Issue by moiraphill** [langflow-ai/langflow#3833]
### Bug Description

Recentemente, identifiquei um erro ao criar text splitters utilizando o módulo Experimental do Langflow. Esse problema afeta os conectores de saída, onde apenas os conectores existentes em versões anteriores do Langflow continuam funcionando corretamente. Os conectores recém-criados exibem comportamento alterado e não conseguem se conectar com outros componentes. Especificamente, o conector de saída (Data) fica com a cor rosa e exibe a mensagem de que não há componentes compatíveis disponíveis.

### Exemplo Visual:

![image](https://github.com/user-attachments/assets/56c9db7f-c005-4c66-97a9-010ee75c3a8f)

Na imagem acima:

Conector Superior: Criado em versões anteriores do Langflow, funcionando normalmente.
Conector Inferior: Criado na versão mais recente (1.0.18), não consegue se conectar com nenhum outro componente na saída "Data".

### Informações Adicionais:

Versão do Langflow: 1.0.18

Ambiente: 
*  Ubuntu 24.04.1 LTS (GNU/Linux 6.8.0-44-generic x86_64)
*  Docker version 27.2.1, build 9e34c9b
*  Docker Compose version v2.29.1
*  Imagens Docker: 
    * python:3.12-slim (pip install langflow) - Python Version: 3.12.3
    * postgres:16

### Reproduction

1. Acesse o módulo Experimental do Langflow.
2. Crie um novo text splitter.
3. Tente conectar a saída (Data) desse text splitter a outro conector existente.

### Expected behavior

Comportamento Esperado: Os conectores recém-criados devem se comportar de maneira semelhante aos conectores de versões anteriores, permitindo conexões com outros componentes sem apresentar erros visuais ou mensagens de incompatibilidade.

Comportamento Atual: Os conectores novos apresentam a saída (Data) na cor rosa e indicam que não há componentes compatíveis, impedindo a conexão com outros conectores.

### Operating System

Ubuntu 24.04.1 LTS (GNU/Linux 6.8.0-44-generic x86_64)

### Langflow Version

1.0.18

### Python Version

3.12

**Comment by carlosrcoelho** [comment]
@moiraphill 

Realizei o teste na versão 1.0.18 e está conectando e funcionando conforme esperado.

<img width="1703" alt="image" src="https://github.com/user-attachments/assets/640ee121-efef-4540-a30e-db41b0f3a320">

Consegue realizar novo teste?

**Comment by anovazzi1** [comment]
stale

**Comment by moiraphill** [comment]
> @moiraphill
> 
> Realizei o teste na versão 1.0.18 e está conectando e funcionando conforme esperado.
> 
> <img alt="image" width="1703" src="https://private-user-images.githubusercontent.com/80289056/370441592-640ee121-efef-4540-a30e-db41b0f3a320.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3OTcxNzcsIm5iZiI6MTcyNzc5Njg3NywicGF0aCI6Ii84MDI4OTA1Ni8zNzA0NDE1OTItNjQwZWUxMjEtZWZlZi00NTQwLWEzMGUtZGI0MWIwZjNhMzIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAxVDE1MzQzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwZjU3ZGNkNTI4ZDA1Mjk5MTkzNDFkOWUwOGE2MTBmZmQ4M2E5MTBkM2RiN2M2NmEzZjA5OTc3ZjFkNDA0ZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5_0EfXIlIv0RaLbvutmQmjYJD1EPnvHWNZqNtKW_Fus">
> Consegue realizar novo teste?

Olá, realizei novo teste instalando diretamente com pip em um ambiente virtual python e eu continuo com o mesmo erro. 
No seu caso, você criou um novo workflow ou usou um workflow já criado ?

**Comment by carlosrcoelho** [comment]
@moiraphill 

Eu fiz o teste diretamente na branch 'main'.

Agora fiz o teste via 'pip' e realmente não está conectando. 

Em breve sairá um novo release que irá corrigir isso no 'pip'.

**Comment by Banbury** [comment]
In v1.0.18 I can't connect the character splitters with any vector store either. No error message. The color of the outputs is purple instead of red.

**Comment by carlosrcoelho** [comment]
Hey @Banbury @moiraphill 

The new version 1.0.19 has been released, and the issue has been fixed.
