### ISSUE TITLE
Error When Using Chat Input Node with Image File in Flow

### ISSUE THREAD

**Issue by adielgur** [langflow-ai/langflow#3836]
### Bug Description

 I'm trying to test a flow that utilizes GPT-4o to analyze an image, specifically by using the Chat Input node with an image file. However, I’m encountering the following error when trying to pass the image:
 ![image](https://github.com/user-attachments/assets/b3447348-f141-4c59-be9f-738aea3a4374)

> Error building Component Chat Input: 
```

(builtins.TypeError) Object of type Image is not JSON serializable
[SQL: INSERT INTO message (timestamp, sender, sender_name, session_id, text, id, flow_id, files) VALUES (%(timestamp)s, %(sender)s, %(sender_name)s, %(session_id)s, %(text)s, %(id)s::UUID, %(flow_id)s::UUID, %(files)s)]
[parameters: [{'id': UUID('4b2ccb05-19f6-4f90-9bd8-51a3c6b4c411'), 'flow_id': '7e2ed8c2-47ea-4961-ad3b-b750f7872e6d', 'sender': 'User', 'files': [Image(path='/app/d ... )], 'session_id': '7e2ed8c2-47ea-4961-ad3b-b750f7872e6d', 'sender_name': 'User', 'timestamp': datetime.datetime(2024, 9, 17, 17:32:32), 'text': ''}]]

```

### Reproduction

1. Set up a flow to analyze images using the Chat Input node.
2. Attempt to pass an image file through the Chat Input node.
3. The error occurs during this process, preventing the image analysis flow from proceeding.

### Expected behavior

Hit "Play" when attaching a file, without an error

### Operating System

Docker / Local python installation both don't work

### Langflow Version

latest

### Python Version

3.12

### Screenshot

![chatinput](https://github.com/user-attachments/assets/13b87986-e829-415b-897f-8fc5fd9c4c14)

**Comment by adielgur** [comment]
Doesn't work, I also tried to uncheck "store messages" and getting a different error still.

**Comment by h-arnold** [comment]
I've experienced the same bug via the Chat Input component in the UI and when passing a file (.png image files) via the API.

The issue is the same running on a vanilla x86 docker instance and on Google Cloud run. 

Interestingly, passing an image in the playground *does* work so I'm guessing there must be a difference between how images are handled in the playground chat interface than the Chat Input component or the API.

I've had the issue on 1.017 but haven't tested it on 1.018 yet.

**Comment by Cristhianzl** [comment]
on it

**Comment by Cristhianzl** [comment]
Hey @adielgur,

Please check the fix in the next Langflow release version, or you can review it in the latest main branch/nightly build.

Thanks!
