### ISSUE TITLE
Suggest to upgrade astra-assistants client to 2.1.1 to fix OpenAI async functions

### ISSUE THREAD

**Issue by sa411022** [langflow-ai/langflow#3840]
### Bug Description

langflow backend has a dependency, astra-assistants client, which [replaces the openai.AsyncOpenAI class by astra_assistants.AsyncOpenAIWithDefaultKey](https://github.com/datastax/astra-assistants-api/blob/33c3b2f037a95c56ddbc03218d756eca67dd722e/client/astra_assistants/__init__.py#L13).

However, in astra-assistants client 2.1.0.26, the AsyncOpenAIWithDefaultKey has an incorrect inheritance, which causes OpenAI async functions such as ainvoke/astream to be not able to work correctly, as described in https://github.com/datastax/astra-assistants-api/issues/72.

This problem has been fix by astra-assistants client 2.1.1, so it is suggested to upgrade astra-assistants client to 2.1.1

### Reproduction

With astra-assistants client 2.1.0.26, calling OpenAI ainvoke will produce the error below.
TypeError: object ChatCompletion can't be used in 'await' expression

### Expected behavior

Successfully execute OpenAI ainvoke without error.

### Operating System

Debian 12 (langflow-backend docker image)

### Langflow Version

1.0.18

### Python Version

3.12

**Comment by phact** [comment]
fixed by https://github.com/langflow-ai/langflow/pull/3841
