### ISSUE TITLE
`tracing_service` is not required for Graph.initialize_run

### ISSUE THREAD

**Issue by 9n** [langflow-ai/langflow#3854]
https://github.com/langflow-ai/langflow/blob/98c1f0e8aa99f44d09e6b90dba73021b8ebce5d5/src/backend/base/langflow/graph/graph/base.py#L558

`initialize_run` function should check `None` of `tracing_service` for better compatibility:
```python
    async def initialize_run(self):
        if not self.tracing_service:
            return
        await self.tracing_service.initialize_tracers()
```

**Comment by wardahub-design** [comment]
install this

https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ
If you don't have the c compliator, install it.(gcc or clang)
