### ISSUE TITLE
How to use components to invoke Qwen models

### ISSUE THREAD

**Issue by alex-ge123** [langflow-ai/langflow#3864]
### Bug Description

How to use components to invoke Qwen models
![微信图片_20240920151229](https://github.com/user-attachments/assets/004cd2c0-c8ea-4412-865d-f226fe0cafe0)

### Reproduction

![image](https://github.com/user-attachments/assets/4ea56051-4d1f-43bc-8bd7-dab97857f839)

### Expected behavior

![image](https://github.com/user-attachments/assets/75cc89d6-6ca3-44e0-bbc8-4d38b032fa88)

### Operating System

windows 

### Langflow Version

1.0.18

### Python Version

3.11

**Comment by alex-ge123** [comment]
![微信图片_20240920151229](https://github.com/user-attachments/assets/54981f22-e3e6-4526-93c8-e9994b7c0362)

**Comment by carlosrcoelho** [comment]
@alex-ge123 

Sorry for the delayed response.

Do you still need support with this issue?

**Comment by alex-ge123** [comment]
> @alex-ge123
> 
> Sorry for the delayed response.
> 
> Do you still need support with this issue?

Can you develop a component for an Alibaba Qianwen model or a model from Baidu, which is suitable for the Chinese market?

**Comment by carlosrcoelho** [comment]
@alex-ge123 
That's a great request! You can open a feature request issue, and then I will add it to our pipeline for new components for Langflow. Thank you very much for your suggestion.

**Comment by jiangjianghong** [comment]
We hope to be able to directly integrate Alibaba Cloud’s Qwen (Tongyi Qianwen) model into LangFlow. Currently, the system only supports a few preset providers and lacks a custom or REST API interface. It would be helpful to add official support or provide an example so users can easily integrate the Qwen model.
