### ISSUE TITLE
An error occurs when calling flowasTool using ToolCallAagent

### ISSUE THREAD

**Issue by alex-ge123** [langflow-ai/langflow#3865]
### Bug Description

![微信图片_20240920151735](https://github.com/user-attachments/assets/f94b4406-e842-4558-b2c5-400d54efe73a)
![微信图片_20240920151803](https://github.com/user-attachments/assets/3df125a0-b1a1-48fe-9539-bf23a7f6433b)

### Reproduction

An error occurs when calling flowasTool using ToolCallAagent

### Expected behavior

An error occurs when calling flowasTool using ToolCallAagent

### Operating System

windows 

### Langflow Version

1.0.18

### Python Version

3.11

**Comment by alex-ge123** [comment]
I'm sure I added {input} to the ToolCallAgent component promnt

**Comment by Cristhianzl** [comment]
hi @alex-ge123,

can you please provide the JSON file with your flows (the main flow you want to run and the others you want to use as a Tool).

this way I can debug here to understand what can be causing the error for you.

thanks!

**Comment by carlosrcoelho** [comment]
@alex-ge123 
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to help you.
