### ISSUE TITLE
Unable to handle session ID properly in Run Flow from JSON and certain components

### ISSUE THREAD

**Issue by edwinjosechittilappilly** [langflow-ai/langflow#3873]
### Bug Description

We are experiencing issues with handling session IDs in the Run Flow from JSON feature and certain components like Store Message. The current implementation has limitations that affect functionality and user experience.

### Specific Issues

1. **Session ID input in components:**
   - Components like Store Message have a session ID field as a text input.
   - These components cannot take the session ID value as input from other components.

2. **Run Flow from JSON limitation:**
   - While we can provide a session ID in CURL commands, there's no way to provide a session ID when using the Run Flow from JSON feature.

### Impact

These limitations restrict the flexibility and functionality of our system, particularly in scenarios where dynamic session handling is crucial.

### Reproduction

1. Create a basic flow with Store Message component
2. Download and attempt to run the flow from JSON
<img width="1392" alt="Screenshot 2024-09-20 at 1 00 23 PM" src="https://github.com/user-attachments/assets/1895c64f-3cd8-47c8-baa3-6bbf61fbe8df">

### Expected behavior

1. Components should be able to accept session ID values from other components dynamically.
2. Run Flow from JSON should have an option to provide or specify a session ID.

### Current Behavior

1. Session ID fields in components are isolated and can't receive input from other parts of the flow, example Store message component.
2. Run Flow from JSON lacks the ability to specify a session ID, unlike CURL commands.

### Possible Solutions

1. Implement a mechanism for components to accept session ID inputs from other components.
2. Add a session ID field or parameter in the Run Flow from JSON feature.

### Operating System

Mac Os

### Langflow Version

1.0.18

### Python Version

None

### Screenshot

<img width="594" alt="Screenshot 2024-09-20 at 12 57 32 PM" src="https://github.com/user-attachments/assets/12cd5e71-3edb-4bc7-8ff2-e88f09dbf23c">

### Flow File

[AstraDB Chat Memory ChatBot (1).json](https://github.com/user-attachments/files/17078330/AstraDB.Chat.Memory.ChatBot.1.json)

**Comment by cristian473** [comment]
hi, this was working on version 1.0.17, try downgrade and provide session_id like this

body: JSON.stringify({
          input_value: text,
          output_type: "chat",
          input_type: "chat",
          session_id: userId, <--
          tweaks: {
          ....

**Comment by Cristhianzl** [comment]
Hi @edwinjosechittilappilly,

I’ve made a small adjustment to the code for the component. It looks like it wasn’t updated during the recent major types update.

To fix this on your end, you’ll need to modify the component’s code. Specifically, update the types shown here:

<img width="492" alt="image" src="https://github.com/user-attachments/assets/ab4e6d11-83b6-478a-9b42-f3d0204faa75">
Replace them with the new MessageInput types:

<img width="1074" alt="image" src="https://github.com/user-attachments/assets/057c1ba5-be40-4cfb-9232-6d5f250ed9f8">
Once you’ve made this change, you should be able to see the handles and connect components as expected:


<img width="1097" alt="image" src="https://github.com/user-attachments/assets/fc9e537d-7d30-40ad-9685-62312ae5a7a9">

<img width="264" alt="image" src="https://github.com/user-attachments/assets/d9653f9f-9a21-4696-8fd1-83dbe5e052a0">
I’ll also open a PR to update this in future versions of Langflow.

Thanks again for reaching out!

#3950

**Comment by edwinjosechittilappilly** [comment]
Hi @Cristhianzl 
I did try to solve the issue in the component by changing the type.
Thank you for the feedback.

But can you also look into the issue with run flow from JSON and session id.

This issue was reported in community also.

**Comment by Cristhianzl** [comment]
hi @edwinjosechittilappilly @cristian473,

Please follow up on this PR with a proper fix for these inputs.
The type now must be: `MessageTextInput`

#4162 

Thanks!
