### ISSUE TITLE
Why do the same prompt component have different input and output interfaces?

### ISSUE THREAD

**Issue by shanmu-raoyunfei** [langflow-ai/langflow#3877]
### Bug Description

Why do the same prompt component have different input and output interfaces?

### Reproduction

Open the memory chatbot project.The input and output interfaces for the existing prompt in the workflow and the prompt that is always dragged from the toolbar are inconsistent.

### Expected behavior

It should be consistent

### Operating System

cloud

### Langflow Version

lasted

### Python Version

3.12

### Screenshot

<img width="355" alt="image" src="https://github.com/user-attachments/assets/17c71965-3623-4bb8-bea7-9145b1353e40">

**Comment by ishanmitra** [comment]
In the Prompt component that is loaded from the Memory Chatbot project, notice that the Template text field has `{context} User: {user_message} AI:` written in it.
Words in the `{}` are considered as variables, and so the component has two nodes.

When you drag a fresh Prompt component the text template is blank, so no variables are decalred. That is why your Prompt component is different.

Do refer to this documentation: https://docs.langflow.org/starter-projects-basic-prompting

Here is a screenshot of a component with three variables:
![image](https://github.com/user-attachments/assets/c016331c-3878-41f9-a161-29fc0fd31e96)

**Comment by shanmu-raoyunfei** [comment]
Problem solved, thank you
