### ISSUE TITLE
Langflow Crashes after creating Vector Store RAG

### ISSUE THREAD

**Issue by samistax** [langflow-ai/langflow#3879]
After creating a new Vector Store RAG project using template. It opens the flow but immediately crashes. No visible errors or logs visible in terminal console. 

<img width="698" alt="Screenshot 2024-09-22 at 14 41 18" src="https://github.com/user-attachments/assets/68b877ef-5bb9-4cbd-b4b6-b61c01551676">

**Comment by samistax** [comment]
This is with Langflow v1.0.18

**Comment by samistax** [comment]
The crash seems to be occurring when SplitText component drag and dropped into the flow.

**Comment by ishanmitra** [comment]
Hey there! If I followed the steps correctly, I can only say that when I created this new project with the Vector Store RAG template, it loaded for me without any crashes.

Did you try running langflow with debug enabled in the terminal?
`python -m langflow run --log-level debug`

Could you see if the terminal provides any tracebacks?

**Comment by samistax** [comment]
Seems weird but when I added Langfuse env variables and restarted then I go the flow to work with the SplitText as well. 
Works now as expected. Not sure what was to root cause for crashes.

**Comment by carlosrcoelho** [comment]
@samistax 

I tried to reproduce the reported issue, but I didn't encounter the same problem; it ran as expected. If you experience any other issues, please open a new ticket, and we will look into it. Thank you.
