### ISSUE TITLE
redis.exceptions.ResponseError: unknown command 'module'

### ISSUE THREAD

**Issue by alex-ge123** [langflow-ai/langflow#3896]
### Bug Description

redis.exceptions.ResponseError: unknown command 'module'

https://github.com/user-attachments/assets/32ea6046-d5f1-4d85-96b5-41d381776986

### Reproduction

Add a redis click run error, see the video

### Expected behavior

ResponseError: unknown command 'MODULE'

### Operating System

windows 

### Langflow Version

1.0.18

### Python Version

3.11

**Comment by carlosrcoelho** [comment]
@alex-ge123 

To run Redis, follow these steps:

- Create an instance using Docker:
  ```shell
  docker run -p 6379:6379 redis/redis-stack-server:latest
  ```

- Redis Server Connection String:
  ```shell
  redis://localhost:6379
  ```

- Specify the Redis Index:
  In my case, I set it as 'index'

- Schema:
  I set it as 'schema'

- Search query:
  I set it as 'docs'

https://github.com/user-attachments/assets/095342d4-716d-4ac2-a6f6-7b67bcb358dc

I hope this helps you.

**Comment by alex-ge123** [comment]
@carlosrcoelho  I checked the possible reasons and found that the low version of Redis on my local machine, version 3.2.100, was causing the issue.
