### ISSUE TITLE
Conflict with pymongo and bson packages in MongoDB VectorStore Component

### ISSUE THREAD

**Issue by joaoguilhermeS** [langflow-ai/langflow#3912]
### Bug Description

There is a problem when trying to run the **MongoDB Vectorstore component**, it trows an exception of: "Please install **pymongo** to use MongoDB Atlas Vector Store" . But the actual problem is **"ImportError: cannot import name '_get_object_size' from 'bson' (/home/joao/YAITEC/langflow/langflow-3-12/env/lib/python3.12/site-packages/bson/__init__.py)"**, so my guess is that there is a conflict between the internal bson of pymongo and the bson package itself set in the poetry environment.

Checking the code I think this might be related with #3607

### Reproduction

1. Get a simple RAG template
2. Place the MongoDB Vectorstore as the Vectorstore
3. Set some configuration parameters (connection string, etc)
4. Run the Flow and check the error

### Expected behavior

The Data should be ingested in the MongoDB Atlas environment as new documents in the choose collection.
Here is an example that I did with Langflow some time ago: ![image](https://github.com/user-attachments/assets/b2bdb5b0-77be-49c3-984e-f59ef8a16447).

### Operating System

Ubuntu Linux 22.04

### Langflow Version

1.0.18

### Python Version

3.12

### Screenshot

![image](https://github.com/user-attachments/assets/817504b5-7e57-4b2c-9df1-c779ef402a06)

### Flow File

[Vector Store RAG - MongoDB.json](https://github.com/user-attachments/files/17132366/Vector.Store.RAG.-.MongoDB.json)

**Comment by thibaultchazal** [comment]
+1

**Comment by jordanrfrazier** [comment]
Thanks @joaoguilhermeS for the catch, you are correct on all counts. PR has been created, will merge and get this in the next release. 

A nightly build exists as well, which should pick up the change once merged - https://pypi.org/project/langflow-nightly/.

**Comment by AlexTo** [comment]
nice, my work around now is to down grade pymongo from 4.9.1 to 4.8.0

**Comment by thibaultchazal** [comment]
Still having the error on my side. Do I need to do something on Langflow?
