### ISSUE TITLE
Problem in the remove_example_flows query parameter in the /api/v1/flows/ API Route

### ISSUE THREAD

**Issue by joaoguilhermeS** [langflow-ai/langflow#3918]
### Bug Description

The query parameter **remove_example_flows** seems not be working  in the **/api/v1/flows/** API Route, which does not let the user to remove the example flows when listing it flows. This came from a discord discussion [discord_link](https://discord.com/channels/1116803230643527710/1288574057985343521). 

### Reproduction

1. Launch Langflow
2. make a GET request to http://localhost:7860/api/v1/flows/?remove_example_flows=false 
3. check http://localhost:7860/api/v1/flows/?remove_example_flows=true 
4. Check that both returns the same Flows.

### Expected behavior

It is expected that when doing http://localhost:7860/api/v1/flows/?remove_example_flows=true, the API just returns Flows that are not default example ones.

### Operating System

Ubuntu Linux 22.04

### Langflow Version

1.0.18

### Python Version

3.12

### Screenshot

![image](https://github.com/user-attachments/assets/8ccb077c-8e22-4963-811e-63ab0d617393)

**Comment by Cristhianzl** [comment]
hi @joaoguilhermeS 

please check the following PR with the fix: #3967

thank you!
