### ISSUE TITLE
Log to the file specified in .env does not work / getting permission denied error on startup

### ISSUE THREAD

**Issue by whispertante** [langflow-ai/langflow#3943]
### Bug Description

I set the LANGFLOW_LOG_FILE in my .env file, however there is no logging in this file. 
Instead, I am getting an error when starting langflow: 
`PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.10/dist-packages/langflow/alembic/alembic.log'`

This should be logged in my log file. 

### Reproduction

1. Go to the project folder and create .env file with this content: 
```
# Config directory
LANGFLOW_CONFIG_DIR=config


# Save database in the config directory
LANGFLOW_SAVE_DB_IN_CONFIG_DIR=true

# Alternatively, you can directly set the database URL
# LANGFLOW_DATABASE_URL=sqlite:////<PATH>/langflow/langflow.db

LANGFLOW_LOG_FILE=langflow.log
```

2. Start langflow: `python3 -m langflow --env-file .env`
3. Error comes up

### Expected behavior

Errors should be logged into the specified log file (where write access is available). 

### Operating System

Ubuntu 22.04.5

### Langflow Version

1.0.18

### Python Version

3.10

**Comment by carlosrcoelho** [comment]
Hey @whispertante 
Did you try it with the new version of Langflow 1.1.1?

Do you need any assistance with this case? If not, please let us know if this issue can be closed.

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to help you.
