### ISSUE TITLE
Support for LMStudio

### ISSUE THREAD

**Issue by EDLLT** [langflow-ai/langflow#3973]
### Feature Request

https://lmstudio.ai/

Could LM Studio support be added. LM Studio is much more versatile than ollama and allows you to download and run GGUF models directly from Hugging Face

### Motivation

Ollama simply doesn't work with my Nvidia GPU. It utilizes the CPU only so it's extremely slow.

### Your Contribution

Perhaps we could look at how [AnythingLLM](https://github.com/Mintplex-Labs/anything-llm) integrates with LM Studio

**Comment by EDLLT** [comment]
Relevant messages I found from LM Studio's discord

![image](https://github.com/user-attachments/assets/368e212a-fb1f-4ada-bac5-c0a58824d714)

![image](https://github.com/user-attachments/assets/300499b4-de5a-4b6c-b7e0-962364c46eef)

**Comment by ogabrielluiz** [comment]
Hey @EDLLT 

How are you? 

If I understand correctly, all you have to do is update the base url in the OpenAI component. I set it to `http://localhost:1234/v1` and it worked first try.

**Comment by EDLLT** [comment]
> Hey @EDLLT
> 
> How are you?
> 
> If I understand correctly, all you have to do is update the base url in the OpenAI component. I set it to `http://localhost:1234/v1` and it worked first try.

Oh. Apologies, I had tried setting it before but not setting the API key was the causing it to not work.
Thanks for your help!

**Comment by EDLLT** [comment]
> Hey @EDLLT
> 
> How are you?
> 
> If I understand correctly, all you have to do is update the base url in the OpenAI component. I set it to `http://localhost:1234/v1` and it worked first try.

Hey, so I managed to get the LM Studio's LLMs working but what about embedding models?
Unlike the OpenAI LLM component, the OpenAI embeddings don't allow me to change the base url

**Comment by EDLLT** [comment]
@duso 
Hello, are you there

**Comment by EDLLT** [comment]
@dosu 
Hello, are you there?

**Comment by EDLLT** [comment]
@dosu 

Why am I getting a CI error?

CI error doesn't make sense to me
```
Error: src/backend/base/langflow/components/models/LMStudioModel.py:57:14: RUF005 Consider iterable unpacking instead of concatenation
Error: Process completed with exit code 1.
```

Line it's complaining about
```
57    inputs = LCModelComponent._base_inputs + [
58        IntInput(
59            name="max_tokens",
60            display_name="Max Tokens",
61            advanced=True,
62            info="The maximum number of tokens to generate. Set to 0 for unlimited tokens.",
63            range_spec=RangeSpec(min=0, max=128000),
64        ),
...
```

Every other component I'd seen(OpenAIModel.py, OllamaModel.py) are structured like that but they don't get errors..?

**Comment by EDLLT** [comment]
@dosu
[src/backend/base/langflow/components/models/LMStudioModel.py](https://github.com/langflow-ai/langflow/pull/4021/files/24335a9c55d182df3624569f39c64fd8a9771ac1#diff-dd37cd56d92a76d2ebded4db628ae16c3d54e965efc2e4505426015c617fc2ad)
Comment on lines +139 to +140
            if output_schema_dict:
                output = output.with_structured_output(schema=output_schema_dict, method="json_mode")  # type: ignore
Contributor
@[ogabrielluiz](https://github.com/ogabrielluiz) ogabrielluiz [2 hours ago](https://github.com/langflow-ai/langflow/pull/4021#discussion_r1787846704)
I'm using it today (loving it, btw) and it seems it has to be json_schema. We need to update this (and the OpenAI component) to make this work better with BaseModel

What did ogabrielluiz mean by that comment? What should be changed?
