### ISSUE TITLE
Upload PDF playground

### ISSUE THREAD

**Issue by mazierovictor** [langflow-ai/langflow#3982]
### Bug Description

I am using the DataStax Langflow version and I already have the entire chatbot configured, however, as I created a chatbot that interacts with PDF files, I am unable to upload the PDF files to the playground. Can someone help me with how I configure it so that it is possible to upload PDF files to the playground?

### Reproduction

I am trying to upload a pdf file to the playground, however I get the error "Error uploading file
Please ensure your file has one of the following extensions:
png, jpg, jpeg"

### Expected behavior

N/A

### Operating System

Windows 11

### Langflow Version

1.0.18

### Python Version

3.12

### Screenshot

![image](https://github.com/user-attachments/assets/9f6963d8-c990-4d8e-82a8-2154db4fa59d)

**Comment by mazierovictor** [comment]
and where can I change this file within the Langflow version of DataStax

**Comment by mazierovictor** [comment]
But I don't have access to the DataStax Langflow installation files

**Comment by carlosrcoelho** [comment]
@mazierovictor 
Today, it's not possible to send a PDF file via Playground. To upload the file in Langflow's Canvas, drag the File component to upload the file.

**Comment by mazierovictor** [comment]
@carlosrcoelho Isso significa que é impossível criar um chatbot que interaja com arquivos PDF? Para cada arquivo PDF, terei que abrir o fluxo do Langflow e alterar o arquivo?

**Comment by mazierovictor** [comment]
@carlosrcoelho What I need is to create a PDF chat where I upload a PDF file and ask him questions. Given this and what you told me, would you have any suggestions?

**Comment by carlosrcoelho** [comment]
You can use the Get Started example Vector Store RAG
<img width="1260" alt="image" src="https://github.com/user-attachments/assets/ec788697-1bbe-41ee-b709-14535f32ea56">

We also have a YouTube channel with some cool tutorials videos:
https://www.youtube.com/@Langflow
