### ISSUE TITLE
NPM install fails

### ISSUE THREAD

**Issue by suyashkumar2409** [langflow-ai/langflow#4000]
### Bug Description

```make install_frontend``` fails

I tried it for both main and v1.0.18. 

I am using 
842 verbose os Darwin 23.4.0
843 verbose node v22.9.0
844 verbose npm  v10.8.3
845 verbose exit 1
846 verbose code 1

I have attached the full error log for npm install.
[npm failure.txt](https://github.com/user-attachments/files/17242183/npm.failure.txt)

I just want to quickly start developing on top of langflow. Whats the fastest way to do this?

### Reproduction

1. clone a new repository
2. On intellij, poetry automatically installs dependencies
3. run make init
4. see that frontend installation fails
5. check logs... not very useful

### Expected behavior

Project should get installed correctly

### Who can help?

@anovazzi1 @Cristhianzl 

### Operating System

Mac OS Darwin 23.4.0

### Langflow Version

1.0.18

### Python Version

3.12

### Screenshot

![Screenshot 2024-10-03 at 2 40 08 AM](https://github.com/user-attachments/assets/fa83dabf-0265-4cb4-b127-3979e11d82e2)

**Comment by anovazzi1** [comment]
hey @suyashkumar2409 try the make frontendc command.
also, what version of node are you using?

**Comment by Owe1n** [comment]
What version of node is advised ?

**Comment by Owe1n** [comment]
> hey @suyashkumar2409 try the make frontendc command. also, what version of node are you using?

What version of node is advised ? I'm facing similar error when using : node v21.2.0

Make frontendc is also returning error 1

**Comment by suyashkumar2409** [comment]
@anovazzi1 I did try make install_frontend, but it fails

node -v `v22.9.0`
npm -v `10.8.3`

My logs are, like before, a series of package GETs and then a failure

```
875 verbose os Darwin 23.4.0
876 verbose node v22.9.0
877 verbose npm  v10.8.3
878 verbose exit 1
879 verbose code 1
880 error A complete log of this run can be found in: /Users/suyashkr/.npm/_logs/2024-10-03T15_20_52_409Z-debug-0.log
```

**Comment by anovazzi1** [comment]
try running make frontendc in your project, it will make a clean install

**Comment by anovazzi1** [comment]
hey @suyashkumar2409 did it work?

**Comment by anovazzi1** [comment]
closed as stale
