### ISSUE TITLE
Flows imported via LANGFLOW_LOAD_FLOWS_PATH don't show up in the Langflow UI

### ISSUE THREAD

**Issue by jblang** [langflow-ai/langflow#4010]
### Bug Description

Flows imported using the LANGFLOW_LOAD_FLOWS_PATH environment variable do not show up in the Langflow UI.  Debug logs show the files being imported, but they do not appear in the UI.

### Reproduction

1. Use the example from https://github.com/DataStax-Examples/langflow-demo-prod
2. Apply the following diff:
    ```
    diff --git a/Dockerfile b/Dockerfile
    index 9fa635e..741872d 100644
    --- a/Dockerfile
    +++ b/Dockerfile
    @@ -20,14 +20,15 @@
     # OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
     # SOFTWARE.**
    
    -FROM langflowai/langflow:1.0.14
    +FROM langflowai/langflow:1.0.16
    
     WORKDIR /app
    
     COPY flows /app/flows
    
     ENV LANGFLOW_LOAD_FLOWS_PATH=/app/flows
    +ENV LANGFLOW_LOG_LEVEL=debug
    
     EXPOSE 7860
    
    -CMD ["langflow", "run", "--backend-only", "--host", "0.0.0.0", "--port", "7860"]
    +CMD ["langflow", "run", "--host", "0.0.0.0", "--port", "7860"]
    ```
3. Build the image: `docker build -t mylangflow:latest -f Dockerfile .`
4. Run the container: `docker run -p 7860:7860 mylangflow:latest`
5. Notice that the log shows the flows being loaded:
    ```
    INFO     2024-10-03 16:58:11 - INFO     - setup setup.py:512
             - Loading flow from file:
             BasicMemoryChatbot.json
    INFO     2024-10-03 16:58:11 - INFO     - setup setup.py:533
             - Creating new flow:
             84e55d35-ffd9-4f02-8e63-d33d25cb65d3
             with endpoint name
             basic-memory-chatbot
    /app/.venv/lib/python3.12/site-packages/langflow/initial_setup/setup.py:536: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
    flow.updated_at = datetime.utcnow()
    INFO     2024-10-03 16:58:11 - INFO     - setup setup.py:512
             - Loading flow from file:
             ResearchPaperDigest.json
    INFO     2024-10-03 16:58:11 - INFO     - setup setup.py:533
             - Creating new flow:
             cc90bbe5-2ac0-46d2-b5f5-2c92a07d87ef
             with endpoint name
             research-paper-digest
    INFO     2024-10-03 16:58:11 - INFO     - setup setup.py:512
             - Loading flow from file:
             PiratePrompt.json
    INFO     2024-10-03 16:58:11 - INFO     - setup setup.py:533
             - Creating new flow:
             ebc064b8-24a0-42bc-82d7-052ff8494566
             with endpoint name pirate-prompt
    INFO     2024-10-03 16:58:11 - INFO     - setup setup.py:512
             - Loading flow from file:
             AstraMemoryChatbot.json
    INFO     2024-10-03 16:58:11 - INFO     - setup setup.py:533
             - Creating new flow:
             b82a60f2-ca42-42ff-a61a-fde2f9d32375
             with endpoint name
             astra-memory-chatbot
    ```
6. Browse to the UI at http://localhost:7860/all
7. Notice that the flows that were imported are not visible in the UI
8. Manually upload one of the flows through the UI
9. Notice that the flow name has a (1) appended to it, suggesting that a flow with the same name already exists but for some reason is not being shown in the UI.

### Expected behavior

Imported flows should be visible in the UI.

### Who can help?

@jordanrfrazier 

### Operating System

Docker image on macOS 14.6.1

### Langflow Version

1.0.16

### Python Version

3.12

### Screenshot

![image](https://github.com/user-attachments/assets/f9c4b180-e2ca-4365-b659-4c1b8e2b95d9)
![image](https://github.com/user-attachments/assets/24bfa4a5-db05-4b37-959a-bda93198c5f1)

### Flow File

https://github.com/DataStax-Examples/langflow-demo-prod

**Comment by jordanrfrazier** [comment]
Confirmed this still exists on 1.0.18. I do see the correct flows being returned from the `api/v1/flows` request though. Going to go see what's going on in the FE.

**Comment by codenprogressive** [comment]
@jordanrfrazier question for you... I'm wondering if there is a way to pass `user_id` and/or `folder_id` where we wanted to load flows.
here are two scenarios:
1- you wanted to load few flows to all users of the platform say under a folder called 'Templates' in their profiles
2- you wanted to load flows to one specific user say under one folder called 'Templates'

**Comment by jordanrfrazier** [comment]
Currently, no. Though, as I look into a solution for the above, I'll take these suggestions into consideration. 

One option: 

* Specify `LANGFLOW_LOAD_FLOWS_PATH=flows`
* Create `flows/folders/<folder>` directory 
* Place flows in `flows/folders/<folder>/my_flow_N.json`
-> <folder> is created (if not existing) and flows are placed there (for all users)

Similarly, for specific users:
* `flows/users/<user>/<folder>/my_flow_N.json`
-> my_flow_N.json is placed in <folder> only for <user>.

**Comment by jordanrfrazier** [comment]
For now, I'll merge the above PR and release with v1.0.19, which will fix the immediate issue of flows being created without a parent folder to live in. Flows will only be able to be imported into the default `My Projects` folder with this change, though we'll do a follow-up and allow users to define options for the above. 

Closing this issue, and opening a feature request for @codenprogressive's suggestion https://github.com/langflow-ai/langflow/issues/4023
