### ISSUE TITLE
Upload file API

### ISSUE THREAD

**Issue by mazierovictor** [langflow-ai/langflow#4014]
### Bug Description

I'm trying to integrate my flow's API, but I'm not able to upload the file. I'm using Python to create my own UI, but as I said above I'm not able to pass the file to the API for processing.

### Reproduction

I created the file field, and I'm trying to use streamlit python to create my UI, but I'm not able to upload (PDF) the file for the API to process. 

### Expected behavior

I need some code suggestion in python that allows me to upload the pdf and txt files that I need to send to API

### Operating System

Windows 11

### Langflow Version

1.0.18

### Python Version

3.12

### Flow File

https://api.langflow.astra.datastax.com/lf/06781aff-5b2e-4247-96f5-96b497a34cca/api/v1/run/540efd99-4e5e-444c-ba08-5e6f3837158e?stream=false

**Comment by mazierovictor** [comment]
@dosubot Is it possible to do this using requests?

**Comment by cystema** [comment]
I think the issue might be due using the same endpoint for both chat input and file upload. It might work by creating a separate endpoint for the file ingestion flow to call from the frontend when uploading a file.

**Comment by anovazzi1** [comment]
hey @cystema and @mazierovictor there is already an endpoint for file upload, it's the `api\v1\upload\{flow_id}`

**Comment by mazierovictor** [comment]
I tried to use the option that the chat bot suggested to me, but it keeps giving errors 400, 401 and 500 and I can't adjust it in any way, including using this link, but I couldn't figure it out.

**Comment by mazierovictor** [comment]
![image](https://github.com/user-attachments/assets/64a65b2c-9e9f-4e8c-90a0-0a5b893055d0)

This is my current flow, where the playground works satisfactorily, but I am not able to upload it through my UI in any way

**Comment by mazierovictor** [comment]
My code that I'm working on is this:

`import requests
import streamlit as st
from langflow.load import upload_file
import os

# Defina o token de autenticação e o link da API do Langflow
APPLICATION_TOKEN = "AstraCS:FMDulUvDvfDZeWFtbITUCrsZ:a502bfbbf2024298649ec3223717a76cbed5893642262875a7af86a992678a7c"
API_URL = "https://api.langflow.astra.datastax.com/lf/06781aff-5b2e-4247-96f5-96b497a34cca/api/v1/run/540efd99-4e5e-444c-ba08-5e6f3837158e?stream=false"

# Função para enviar uma consulta para a API do Langflow e obter a resposta
def query_langflow(messages, tweaks=None):
    headers = {
        "Authorization": f"Bearer {APPLICATION_TOKEN}",
        "Content-Type": "application/json",
    }
    
    # Formato de payload ajustado
    prompt = "\n".join([f"{msg['role']}: {msg['content']}" for msg in messages])
    
    payload = {
        "input_value": prompt,
        "output_type": "chat",
        "input_type": "chat",
        "tweaks": tweaks if tweaks else {
            "ChatInput-Q0MId": {},
            "GroqModel-572xX": {},
            "ChatOutput-7kVfU": {}
        }
    }
    
    # Envia a solicitação à API e captura a resposta
    response = requests.post(API_URL, headers=headers, json=payload)

    # Verifica o código de status HTTP
    if response.status_code == 200:
        try:
            response_data = response.json()
            return response_data["outputs"][0]["outputs"][0]["results"]["message"]["data"].get("text", "Nenhuma resposta disponível.")
        except Exception as e:
            return "Erro ao processar a resposta da API."
    else:
        return f"Erro: {response.status_code} - {response.text}"

# Função para processar o upload de arquivos
def process_file_upload(uploaded_file, tweaks):
    try:
        if uploaded_file is not None:
            # Salva o arquivo em um diretório temporário
            temp_file_path = os.path.join(os.getcwd(), uploaded_file.name)
            
            with open(temp_file_path, 'wb') as f:
                f.write(uploaded_file.getbuffer())

            # Chama a função upload_file da langflow
            tweaks = upload_file(
                file_path=temp_file_path,
                host="https://api.langflow.astra.datastax.com",
                flow_id="540efd99-4e5e-444c-ba08-5e6f3837158e",  # Verifique se esse flow_id está correto
                components="File-NzpIx",  # Verifique se esse componente está correto
                tweaks=tweaks
            )
            
            # Opcional: Remover o arquivo temporário após o upload
            os.remove(temp_file_path)
            
        return tweaks
    except Exception as e:
        st.error(f"Erro ao fazer upload do arquivo: {e}")
        return tweaks

# Configuração da página Streamlit
st.set_page_config(
    page_title='Langflow Chatbot',
    page_icon='🤖',
)

# Menu superior
menu = st.sidebar.selectbox("Menu", ("Página Inicial", "Chatbot"))

if menu == "Página Inicial":
    st.header("🤖 Bem-vindo ao Chatbot com Langflow!")
    st.write("Este é um chatbot alimentado por uma API que pode responder suas perguntas.")
    st.write("Selecione 'Chatbot' no menu para começar a conversar.")
    
elif menu == "Chatbot":
    st.header('🤖 Chatbot com API Langflow')

    # Interface de chat com o usuário
    if 'messages' not in st.session_state:
        st.session_state['messages'] = []

    # Botão para nova conversa
    if st.button('Nova Conversa'):
        st.session_state['messages'] = []
        st.success('Histórico da conversa limpo. Você pode começar uma nova interação!')

    # Upload de arquivo
    uploaded_file = st.file_uploader("Envie um arquivo (PDF, JPEG, PNG, TXT, DOCX)", type=['pdf', 'jpeg', 'png', 'txt', 'docx'])
    
    # Processar o upload e atualizar os tweaks
    tweaks = {
        "ChatInput-Q0MId": {},
        "GroqModel-572xX": {},
        "ChatOutput-7kVfU": {}
    }
    
    if uploaded_file is not None:
        tweaks = process_file_upload(uploaded_file, tweaks)
    
    # Caixa de entrada do chat
    question = st.chat_input('Como posso ajudar?')

    if question and question.strip():  # Certifica-se de que a pergunta não está vazia
        st.session_state['messages'].append({'role': 'user', 'content': question})
        
        with st.spinner('Buscando resposta...'):
            # Chama a API do Langflow para obter a resposta, incluindo o histórico
            response = query_langflow(st.session_state['messages'], tweaks)

            # Verifica se a resposta é válida antes de armazená-la
            if response:
                st.session_state['messages'].append({'role': 'ai', 'content': response})

    # Exibe o histórico de mensagens
    for message in st.session_state['messages']:
        st.chat_message(message['role']).write(message['content'])
`

**Comment by mazierovictor** [comment]
@dosu
@anovazzi1 
@carlosrcoelho 

Even though I set my flow_id correctly as it is in langflow, it still shows the 404 error.

Below I leave my flow_id and the code used.


BASE_API_URL = "https://api.langflow.astra.datastax.com"
LANGFLOW_ID = "06781aff-5b2e-4247-96f5-96b497a34cca"
FLOW_ID = "540efd99-4e5e-444c-ba08-5e6f3837158e"
APPLICATION_TOKEN = "<YOUR_APPLICATION_TOKEN>"
ENDPOINT = ""


```
import requests

# Define the URL and the flow_id
url = "https://api.langflow.astra.datastax.com/api/v1/upload/{flow_id}"
flow_id = "540efd99-4e5e-444c-ba08-5e6f3837158e"  # Replace with your actual flow ID

# Open the file you want to upload
file_path = r"c:\mypdf.pdf"  # or "path/to/your/file.txt"
with open(file_path, 'rb') as file:
    # Make the POST request to upload the file
    response = requests.post(url.format(flow_id=flow_id), files={'file': file})

# Check the response
if response.status_code in [200, 201]:
    print("File uploaded successfully:", response.json())
else:
    print("Failed to upload file:", response.status_code, response.text)
```

**Comment by mazierovictor** [comment]
@dosu

I created my LangFlow API and the 404 error still remained, and the code looked like this:

import requests

# Define the URL and the flow_id
url = "https://api.langflow.astra.datastax.com/api/v1/upload/{flow_id}"
flow_id = "540efd99-4e5e-444c-ba08-5e6f3837158e"  # Replace with your actual flow ID
api_key = "sk-Z1WTrrkrGCIgLBGMkqaTItTjPXcWaZNOUE8MuoVCpoY"

# Open the file you want to upload
file_path = r"C:\Users\mazie\OneDrive\Pericias - Nomeações\Assistencia Técnica\15 - Layra - Caminhão\FICHA 7.pdf"  # or "path/to/your/file.txt"
with open(file_path, 'rb') as file:
    headers = {'x-api-key': api_key}
    # Make the POST request to upload the file
    response = requests.post(url.format(flow_id=flow_id), files={'file': file}, headers=headers)

# Check the response
if response.status_code in [200, 201]:
    print("File uploaded successfully:", response.json())
else:
    print("Failed to upload file:", response.status_code, response.text)

**Comment by mazierovictor** [comment]
@dosu

If I access the link https://api.langflow.astra.datastax.com/api/v1/upload/ directly through the browser, it shows a 404 error.

![image](https://github.com/user-attachments/assets/50599c85-7313-46cd-8485-d0d7ef0ca3cb)

**Comment by mazierovictor** [comment]
@dosu

When making post requests through postman using the link, the 404 error still remains.

There is something wrong with the API link.

![image](https://github.com/user-attachments/assets/153753e5-046a-4eb5-9126-0845ac7a7c88)

**Comment by mazierovictor** [comment]
@dosu

Even after changing the link as mentioned, the 404 error remains.

Therefore, the suggested link is that there are problems that are not accepting the shipment.

![image](https://github.com/user-attachments/assets/680d3331-567c-47f4-9673-1aa72552677a)

**Comment by mazierovictor** [comment]
@dosu
I am having this error when uploading files
Failed to upload file: 500 {"message":"'utf-8' codec can't decode byte 0xa1 in position 130: invalid start byte"}

**Comment by mazierovictor** [comment]
@dosu

My code is the one below, what would the complete code look like?

import requests

# Define the URL and the flow_id
url = "https://langflow-langflow.carfce.easypanel.host/api/v1/run/{flow_id}"
flow_id = "2e08b3d4-7aca-4fe4-b02d-f668c937daa6"  # Replace with your actual flow ID
api_key = "mykey"

# Open the file you want to upload
file_path = r"Extrato Renegociado.pdf"  # or "path/to/your/file.txt"
with open(file_path, 'rb') as file:
    
    # Make the POST request to upload the file
    headers = {'x-api-key': api_key}
    response = requests.post(url.format(flow_id=flow_id), files={'file': file}, headers=headers)

# Check the response
if response.status_code in [200, 201]:
    print("Sucesso:", response.json())
else:
    print("Failed to upload file:", response.status_code, response.text)

**Comment by alejandroacho** [comment]
Im using something like this:

```
       payload = {
            "ChatInput-sBmkW": {'input_value': 'Some chat input},
            "TextInput-20169": {"input_value":  'Some text input'},
            "AstraDB-ar3yg": {"collection_name": collection_name},
        }
        tweaks = upload_file(
            file_path, LANGFLOW_API_URL, LANGFLOW_FLOW_ID, [f"{file_component_id}"], payload
        )
        response = requests.post(api_url, json=tweaks)
```

And im getting this 500:

`{'detail': '{"message":"Error running graph: Error building Component File: \\n\\nPlease, upload a file to use this component.","traceback":null,"description":null,"code":null,"suggestion":null}'}`

**Comment by alejandroacho** [comment]
Im using something like this:

```
       payload = {
            "ChatInput": {'input_value': 'Some chat input},
            "TextInput": {"input_value":  'Some text input'},
            "AstraDB": {"collection_name": collection_name},
        }
        tweaks = upload_file(
            file_path, LANGFLOW_API_URL, LANGFLOW_FLOW_ID, [f"{file_component_id}"], payload
        )
        response = requests.post(api_url, json=tweaks)
```
And im getting this 500:
`
{'detail': '{"message":"Error running graph: Error building Component File: \\n\\nPlease, upload a file to use this component.","traceback":null,"description":null,"code":null,"suggestion":null}'}`

**Comment by alejandroacho** [comment]
Finally as a workaround I ended up uploading the file to the FlowID and using the Directory Component pointing to that folder in order to get the file data.

```
    @staticmethod
    def upload_file(file_path):
        try:
            url = f"{LANGFLOW_API_URL}/api/v1/files/upload/{YOUR_FLOW_ID}"
            with open(file_path, "rb") as file:
                response = httpx.post(url, files={"file": file})
                if response.status_code in [200, 201]:
                    print(response.json())
                    return response.json()
                raise Exception(f"Error uploading file: {response.status_code}")
        except Exception as e:
            raise Exception(f"Error uploading file: {e}") from e
```

```
    @classmethod
    def run_flow(file_path: str) -> None:
        flow_id = YOUR_FLOW_ID
        api_url = f"{LANGFLOW_API_URL}/api/v1/run/{ENDPOINT}"
        uploaded_file = cls.upload_file(file_path)
        payload = {
            "TextInput-COMPONENT-ID": {"input_value": f"/app/data/.cache/langflow/{YOUR_FLOW_ID}"},
        }
        response = requests.post(api_url, json=payload)
```

![CleanShot 2024-10-06 at 21 55 58@2x](https://github.com/user-attachments/assets/885104b4-e4d0-497e-8db9-3344ff463dd5)

**Comment by mazierovictor** [comment]
@alejandroacho 

Do you pass the directory only or do you pass the directory and file name?

Because I think that if you only pass the directory, it will process all the files that are there, which would not be interesting to happen.

**Comment by alejandroacho** [comment]
@mazierovictor I upload the file to the directory using the upload function:

```
    @staticmethod
    def upload_file(flow_id: str, file_path: str):
        try:
            url = f"{settings.LANGFLOW_API_URL}/api/v1/files/upload/{flow_id}"
            headers = {}
            with open(file_path, "rb") as file:
                response = httpx.post(url, files={"file": file}, headers=headers)
                if response.status_code in [200, 201]:
                    print(response.json())
                    return response.json()
                raise Exception(f"Error uploading file: {response.status_code}")
        except Exception as e:
            raise Exception(f"Error uploading file: {e}") from e
```

Then I used the component with the directory it was uploaded and it worked

**Comment by alejandroacho** [comment]
@mazierovictor btw, I managed to upload the file directly to the file component. Just as a reminder, you have to put the tweaks dict in a tweak json attribute:

```
payload = {
    "input_value": message,
    "tweaks": {
        "TextInput-ID": {"input_value": "Hello world"},
    },
}
headers = {"Content-Type": "application/json"}
response = requests.post(f"{LANGFLOW_API_URL}/api/v1/run/{ENDPOINT}", json=payload, headers=headers)
```


But anyways. How I managed to upload the file:

```
from langflow.load import upload_file

payload: dict = {"TextInput-ID": {"input_value": "Hello world"}}
payload_with_file = upload_file(
    file_path=FILE_PATH,
    host=LANGFLOW_API_URL,
    flow_id=FLOW_ID,
    components=["File-ID"],  # Your component file id
    tweaks=payload,
)
headers = {"Content-Type": "application/json"}
response = requests.post(
    f"{LANGFLOW_API_URL}/api/v1/run/{ENDPOINT}",
    json={"tweaks": payload_with_file},  # It is important to put your tweaks in the tweak attribute of the payload
    headers=headers
)
```

**Comment by carlosrcoelho** [comment]
@mazierovictor 

Do you need any assistance with this case? If not, please let us know if this issue can be closed.
