### ISSUE TITLE
AstraDB tweak not working using API

### ISSUE THREAD

**Issue by alejandroacho** [langflow-ai/langflow#4034]
### Bug Description

When I pass the collection name through tweaks, it doesn't change it.

### Reproduction

1. Create flow with AstraDB component
2. Using API with tweaks to set the collection name

```
  api_url = f"{LANGFLOW_API_URL}/api/v1/run/{ENDPOINT}"
  payload = {
      "AstraDB-COMPONENT-ID": {"collection_name": COLLECTION-NAME-STR},
  }
  response = requests.post(api_url, json=payload)
```
  
`response.json() = {'detail': '{"message":"Error running graph: Error building Component Astra DB: \\n\\nError initializing AstraDBVectorStore: Must provide a collection name","traceback":null,"description":null,"code":null,"suggestion":null}'}`

### Expected behavior

AstraDB component should get collection_name tweak in order to initialize

### Operating System

Mac OS Sequoia 15.0 (using docker image)

### Langflow Version

1.0.18

### Python Version

None

### Screenshot

![CleanShot 2024-10-06 at 22 00 47](https://github.com/user-attachments/assets/b75a9373-f602-43ba-ad32-7ec9995e65c4)

**Comment by edwinjosechittilappilly** [comment]
Hi @alejandroacho 

Happy to help! Could you please share the details of the flow as well as the complete payload (excluding any sensitive information)? This would allow me to debug the issue more effectively.

Looking forward to your response!

**Comment by alejandroacho** [comment]
Solved. I had to put the tweaks dict in a tweak json attribute:

```
payload = {
    "input_value": message,
    "tweaks": {
        "TextInput-ID": {"input_value": "Hello world"},
    },
}
headers = {"Content-Type": "application/json"}
response = requests.post(f"{LANGFLOW_API_URL}/api/v1/run/{ENDPOINT}", json=payload, headers=headers)
```

**Comment by alejandroacho** [comment]
Solved. I had to put the tweaks dict in a tweak json attribute:

```
payload = {
    "input_value": message,
    "tweaks": {
        "TextInput-ID": {"input_value": "Hello world"},
    },
}
headers = {"Content-Type": "application/json"}
response = requests.post(f"{LANGFLOW_API_URL}/api/v1/run/{ENDPOINT}", json=payload, headers=headers)
```
