### ISSUE TITLE
Groq component not showing models 

### ISSUE THREAD

**Issue by SavvySupport** [langflow-ai/langflow#4064]
### Bug Description

When I pull in the component, it has the following issues: 
- Shows error.. Invalid literal for int() with base 10: "" when I pull in the component. 
- Doesn't show the models to select from. Says "No parameters are available for display."

### Reproduction

1. Select the Groq component and drag it onto the flow configuration  

### Expected behavior

It should show a dropdown with the LLM models to select from. 

### Operating System

MacOS Ventura 13.5.1

### Langflow Version

1.0.16

### Python Version

3.10

### Screenshot

https://prnt.sc/fxFxV9h1V3QP, https://prnt.sc/fMMdgnXBS_J4

**Comment by carlosrcoelho** [comment]
Hey @SavvySupport 

I noticed you used version 1.0.16. Please try it with the current version, 1.0.18.

**Comment by SavvySupport** [comment]
> Hey @SavvySupport
> 
> I noticed you used version 1.0.16. Please try it with the current version, 1.0.18.

Thanks Carlos - will give it a shot.

**Comment by carlosrcoelho** [comment]
@SavvySupport 

Please let me know it it is working.

**Comment by SavvySupport** [comment]
yes its working now
