### ISSUE TITLE
Import feature broken?

### ISSUE THREAD

**Issue by gitck-scch** [langflow-ai/langflow#4070]
### Bug Description

For me the import of json files (flows or components) does not work over the user interface of langflow. The system claims that upload was successful in the Notification dialog, but imported flows and components are not available/visible at the UI.

I tried to investigate the reasons for that and there seems to be some timing or focus issues when trying to import existing flows or components (I tried it with different browsers - same behavior, I tried direct installation of langflow and running as docker container - same behavior). 

If I set the breakpoints as in the image below the probability that the import is available in the UI after selecting the file via the file explorer is much higher (it works at least sometimes).

![image](https://github.com/user-attachments/assets/69a5967a-8c6e-4817-85e6-a96db1f99de4)

### Reproduction

I think it is not possible to reproduce this issue, if you do not have this behavior already.

I'm running langflow on:
Windows 10 Enterprise build 19045

1. Clicking on the **Upload Folder** icon opens file explorer to select a *.json file (and yes, I also tried it with different files). 
![image](https://github.com/user-attachments/assets/d94b6cde-b49e-4696-8881-d003d4274616)
3. Selecting a file and selection 'Open' closes file explorer.
4. Notification "Uploaded successfully" is show 
5. But there is no 'flow' (or component) added to the UI, and also not persisted in the database

### Expected behavior

The import feature should work realiable, or at least do not claim that upload was successful as long as it is not saved with a project sucessfully.

### Operating System

Windows 10

### Langflow Version

1.0.18

### Python Version

3.12

### Flow File

any flow or component file (does not depend on a specific file)

**Comment by Cristhianzl** [comment]
hi @gitck-scch, hope you are doing well!

I tested the upload functionality for Flows, Components, and Folders, both locally and in Docker Compose, and everything worked as expected.

Are you downloading the Flow and Folder from Langflow? The JSON file needs to follow the required structure for it to work properly.

Could you share the JSON file you're trying to upload? This will help me investigate further.

Thanks!

**Comment by gitck-scch** [comment]
Hi @Cristhianzl,
yes, I use the orginal image v1.0.18 pulled from https://hub.docker.com/r/langflowai/langflow.
And this problem doesn't have anything to do with the used json-file, because I have tried different ones. For example I'm also not able to import the unchanged "Basic Prompt" example previously exported (but this exported flow can be imported on another system without any problem).

I think this problem won't be reproducable on your machine. Therefore I propose that someone with deep understanding of the code should take a look into this asynchronous calls, whether there might be the possibility of a race condition. At least in my point of view this might me a valid cause for the observed behaviour. Why it's just affecting my system, that is the interesting question.

Thanks for your help!

**Comment by Cristhianzl** [comment]
hi @gitck-scch,

I understand, that sounds a bit tricky. Ideally, anyone should be able to reproduce the error locally. It’s possible that this might be an issue specific to your environment, don't you think?

I've taken a deeper look into the code and believe I might have found a potential improvement. If you're interested, you can review my changes here: [https://github.com/langflow-ai/langflow/commit/f4e4008be1380de07378af524a7ddc068ea3a61e](https://github.com/langflow-ai/langflow/commit/f4e4008be1380de07378af524a7ddc068ea3a61e). With your expertise, we could work together to ensure it follows best practices.

It would be really helpful if I could reproduce the error locally at least once, so I can be sure my solution addresses the issue. Could you assist me in reproducing it on my end?

I’ve already tried throttling my network to check if it’s an async issue, but I couldn’t replicate the behavior.

Thanks!

**Comment by nihirv** [comment]
I'm running into the same issue -- it's not unique to OP

**Comment by nihirv** [comment]
hey @Cristhianzl. Thanks, I saw this -- but doesn't really unblock me right now.

I downloaded the nightly version but am still met with the same error!
