### ISSUE TITLE
remove span from custom select

### ISSUE THREAD

**Issue by anovazzi1** [langflow-ai/langflow#4073]
### Bug Description

the custom select component wraps every select item inside an span preventing full width 

### Reproduction

create a custom select component
try to set the select item as w-full

### Expected behavior

no style inference from the select item component

### Operating System

mac os

### Langflow Version

1.0.18

### Python Version

3.12

**Comment by irshadmb** [comment]
@anovazzi1 please share the slow with screen shoot. It will be helpful.
