### ISSUE TITLE
Error when starting

### ISSUE THREAD

**Issue by alex-ge123** [langflow-ai/langflow#4106]
### Bug Description

Error when starting

### Reproduction

Error when starting

### Expected behavior

Error when starting

https://github.com/user-attachments/assets/dd4c7d16-72b8-4e87-b6a2-5c737340d7c8

### Operating System

windows 

### Langflow Version

1.0.19

### Python Version

3.11

**Comment by joaoguilhermeS** [comment]
Hey @alex-ge123, 

For a smoother experience using Langflow on Windows, I recommend installing WSL2 (Windows Subsystem for Linux 2). WSL2 allows you to run a Linux kernel directly inside your Windows environment, which helps to ensure compatibility with some of the dependency libraries that may not be directly supported on Windows. This way, your installation process will be much more reliable.

Alternatively, you can also install Langflow using Docker if you’re more comfortable with that approach.

Here are some useful links to get started:

- **Tutorial for installing WSL2:** [Install WSL on Windows](https://learn.microsoft.com/en-us/windows/wsl/install)
- **Langflow installation guide:** [Langflow Installation Guide](https://docs.langflow.org/getting-started-installation)

Feel free to reach out if you have any questions or run into any issues!
