### ISSUE TITLE
ConditionalRouter doesn't work as expect.

### ISSUE THREAD

**Issue by 9n** [langflow-ai/langflow#4112]
Here is my flow
![图片](https://github.com/user-attachments/assets/935df78f-42a2-449f-b71c-0dd935f3a616)

When I input `bye`, it works fine.
But when I input `hello` in the playground, I got `hi there` and a error message, which is caused by build the 2nd `Chat Output`, which I think should not be build.
![图片](https://github.com/user-attachments/assets/c2cc99ea-af98-4841-b3e0-af8a07c129a9)

Flow File
[Router Sample.json](https://github.com/user-attachments/files/17340674/Router.Sample.json)

**Comment by carlosrcoelho** [comment]
@9n 
The component received a fix in version 1.0.19.

Update your Langflow, and it should work.

I hope this helps.

<img width="1279" alt="image" src="https://github.com/user-attachments/assets/6fac3b73-3d04-498b-ae49-35565431556d">
<img width="1967" alt="image" src="https://github.com/user-attachments/assets/0ee05dd4-53d6-4636-9101-149cbcc3a1d1">

**Comment by 9n** [comment]
thx it works when upgrade to 1.0.19
