### ISSUE TITLE
[Docker] An error has occurred while fetching types

### ISSUE THREAD

**Issue by mariushosting** [langflow-ai/langflow#4117]
### Bug Description

image: logspace/langflow:latest

No issue in the container log, just can't open anymore Langflow.
![anymore](https://github.com/user-attachments/assets/0a542c85-8970-4c2d-a5ff-ddcb1cffab54)

### Reproduction

Install the latest image with DB
everything is installed OK no issue in the logs. 
When I try to open the page the error message appears.

### Expected behavior

It should work.

### Operating System

Docker

### Langflow Version

latest

### Python Version

None

**Comment by carlosrcoelho** [comment]
You’ll need to pull from the docker hub first, I would guess you have a previous image with that tag locally.

Then try the command `docker run -p 7860:7860 langflowai/langflow:latest.`

**Comment by mariushosting** [comment]
> You’ll need to pull from the docker hub first, I would guess you have a previous image with that tag locally.
> 
> Then try the command `docker run -p 7860:7860 langflowai/langflow:latest.`
Using the following image
logspace/langflow:latest

**Comment by mariushosting** [comment]
> @mariushosting You should use the command `docker run -p 7860:7860 langflowai/langflow:latest.`

Yes using the langflowai instead of logspace works as expected.
