### ISSUE TITLE
I can't upload a fille on DataStax Astra DataBase 

### ISSUE THREAD

**Issue by gbmbubble** [langflow-ai/langflow#4125]
### Bug Description

I have the prebuild Vector Store RAG, but it doesn't upload the fille on the Datastax Astra DataBase that I have created 

### Reproduction

open the prebuild Vector Store RAG, and put the required inputs 

### Expected behavior

To upload the document on the data base 
![Capture](https://github.com/user-attachments/assets/2f098164-6cd2-41ef-a14a-23a68e2ab8ba)

### Operating System

windows 7

### Langflow Version

v1.0..18

### Python Version

None

### Screenshot

![Capture](https://github.com/user-attachments/assets/ee4bf3f5-c2ad-4ba0-8411-9a4e832fac6f)

**Comment by gbmbubble** [comment]
It still doesn't work

**Comment by carlosrcoelho** [comment]
@gbmbubble 

Could you show the error that appears?

**Comment by Jeo-Jang** [comment]
Hugging face spaces also doesn't work.

Tried Both of Folder loader just incase I can do something, no luck.

**Comment by carlosrcoelho** [comment]
Hi @Jeo-Jang 

What do you mean Hugging Face not working?

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to help you.
