### ISSUE TITLE
LangFlow v1.0.19 CrewAI build stuck

### ISSUE THREAD

**Issue by djethino** [langflow-ai/langflow#4149]
### Bug Description

LangFlow Build is stuck on CrewAI Agent

Tested after upgrade of LangFlow from 1.0.18 to 1.0.19 in a conda env
Tested with a new installation in another conda env

I've the same problem if I try with "OpenAI Tool Agent"

I had no problems before with v1.0.18 and I haven't exported my flows before upgrading and now I can't reimport it on the previous version, my bad 👯 

Tested with Python 3.10 and 3.11

### Reproduction

1. Install LangFlow 1.0.19 with "pip install langflow"
2. Try to do a flow with CrewAI Agent

### Expected behavior

Build and run the flow

### Operating System

Windows 11

### Langflow Version

1.0.19

### Python Version

3.11

### Screenshot

![image](https://github.com/user-attachments/assets/6df15fa2-f5fa-46ef-b5a4-de5504260ab3)

### Flow File

[Travel Planning Agents.json](https://github.com/user-attachments/files/17370400/Travel.Planning.Agents.json)

**Comment by djethino** [comment]
I forgot to say that there is no error messages (tried with "python -m langflow run --log-level DEBUG"), it just stay stuck. And if you stop the build and restart, it is stuck at the firsts component (chat input, model component). Something append somewhere, but difficult to know what :)

**Comment by carlosrcoelho** [comment]
@djethino 
I tried to replicate it according to your previous flow, but didn't succeed using the LM Studio you implemented. I believe the error is coming from there. I tested it with the supported models from Langflow and was able to run it. Have you tried using the OpenAI model from Langflow?

**Comment by carlosrcoelho** [comment]
A new version v1.0.19.post1 is out!
https://github.com/langflow-ai/langflow/releases/tag/v1.0.19.post1

Some issues related to CrewAI were fixed. Please try it out.

**Comment by djethino** [comment]
Problem resolved on my side. I have some other new problems due to the way CrewAI manage the models now with litellm and custom local models (not a problem with langflow).
Thanks ! :)
