### ISSUE TITLE
issue with langflow 1.0.19

### ISSUE THREAD

**Issue by michelgirault** [langflow-ai/langflow#4160]
### Bug Description

the node agent: Sequential Crew does not recognize anymore my openai compatible llm (llama 3)
in previous version i did not face this issue, i tried a few other agent, same error message, now if i use the node openai with other node, i dont have any problems

![Screenshot from 2024-10-15 19-18-52](https://github.com/user-attachments/assets/998b7583-4a1a-46b0-9048-f460b40bd370)
the error message: 
Error building Component Sequential Crew: litellm.AuthenticationError: AuthenticationError: OpenAIException - Error code: 401 - {'error': {'message': 'Incorrect API key provided: dummy. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}

### Reproduction

1. create an empty flow
2. attach openai and setup the base url and api key
3. add a node : Sequential Task Agent and Sequential Crew

### Expected behavior

error message as provided with an issue about the api key used

### Operating System

ubuntu 22.04

### Langflow Version

1.19

### Python Version

3.10

**Comment by michelgirault** [comment]
as i said it was working in previous version with the exact setup and in other node i dont have any issue

**Comment by michelgirault** [comment]
thanks

**Comment by phact** [comment]
By the way I was able to reproduce this same scenario with langflow v1.0.18 and the sequential crew component with memory enabled.

The error message is the same except it says `fake` instead of `dummy`

**Comment by michelgirault** [comment]
Hi, thanks i think this is an issue with crewai and the memory component enabled, 
https://github.com/crewAIInc/crewAI/issues/447

**Comment by phact** [comment]
Yeah more specifically memory tries to use embeddings from openai and expects the api key to be set via env var.

**Comment by erichare** [comment]
This should now be addressed in the latest main. Could you confirm @michelgirault ? The credentials of the agents are auto-detected - with the catch being that we don't necessarily have a FULLY general solution to figure out the embedding model credentials and how it is referenced when it is passed to the agent. So this has been tested with OpenAI and other common models, but there may be more to do to better support less commonly use models.

**Comment by michelgirault** [comment]
i will check and get back to you, thanks for following up

**Comment by erichare** [comment]
Thanks @michelgirault !
