### ISSUE TITLE
Frontend crashes when new project modal is opened.

### ISSUE THREAD

**Issue by bohemiancode-x** [langflow-ai/langflow#4172]
Pulled the latest update from the main branch and the app crashes when I try to open the get started modal (that has starter projects). On further inspection, I found out the /flows/basic_examples endpoint returns an html page that is stored as in the examples store and triggers the typeError (examples.find() is not a funtion.)
<img width="1512" alt="Screenshot 2024-10-16 at 12 12 03 PM" src="https://github.com/user-attachments/assets/fa76e2b4-7d4e-4146-ae3b-1380ff855ea5">

**Comment by anovazzi1** [comment]
hey just tested the main branch and I couldn't reproduce, can you check again?

**Comment by bohemiancode-x** [comment]
> hey just tested the main branch and I couldn't reproduce, can you check again?

I'm still facing this issue. The /flows/basic_examples endpoint returns an html template which makes the examples.find() function throw an error. Is there a way to troubleshoot the api response? I either run the backend with docker or through the terminal with "langflow run"

**Comment by anovazzi1** [comment]
unfortunately I can't reproduce the bug, but I notice you are running on port 3001 and based with the endpoint response probably you have a problem related to your setup, can you double check the backend and the frontend are running properly in the right ports? how are you running the langflow?

**Comment by bohemiancode-x** [comment]
> Hey @bohemiancode-x, unfortunately I can't reproduce the bug, but I notice you are running on port 3001 and based with the endpoint response probably you have a problem related to your setup, can you double check the backend and the frontend are running properly in the right ports? how are you running the langflow?

I run langflow backend with docker and the frontend manually with npm run start. I also encountered the error while running on port 3000 for the frontend.

**Comment by anovazzi1** [comment]
does the issue still occur after 1.0

**Comment by anovazzi1** [comment]
close for inactivity
