### ISSUE TITLE
Error building Component HuggingFace: max_new_tokens not found in HuggingFaceEndpointsComponent

### ISSUE THREAD

**Issue by v-wei40680** [langflow-ai/langflow#4182]
### Bug Description

Error building Component HuggingFace: max_new_tokens not found in HuggingFaceEndpointsComponent
flow Component:
chat input -> HuggingFace -> chat output

### Reproduction

my step:
1. clone hugging face space:https://huggingface.co/spaces/Langflow/Langflow?duplicate=true
2. flow
- chat input
- HuggingFace
- input API Token(flow input)
- chat output
- playground(flow run)

### Expected behavior

chat at playground

### Operating System

hugging face Space cpu basic

### Langflow Version

langflowai/langflow:latest

### Python Version

None

**Comment by Bharath1510** [comment]
Getting the same error, Did you get any solution for that?

**Comment by edwinjosechittilappilly** [comment]
Yes, we found the solution.
There were some conflicting PR that led to the issue. I am in the process of creating a new PR to sort the issue. Thank you for your patience.

**Comment by Bharath1510** [comment]
hello @edwinjosechittilappilly, Still getting the issue while running it in huggingface space using dockerfile from github page.
"[Clone the space using this link]" using this link.

**Comment by edwinjosechittilappilly** [comment]
It's updated in the main branch, but not yet in releases.
Please use the updated component code (huggingface.py) from the main branch.
