### ISSUE TITLE
Custom Component Creation - Multiple Outputs Not Working in Versions 1.0.19 and Main

### ISSUE THREAD

**Issue by edwinjosechittilappilly** [langflow-ai/langflow#4185]
### Bug Description

Issue:
When creating a custom component using multiple outputs, the functionality is broken in both version 1.0.19 and the main branch of Langflow. This worked correctly in version 1.0.18.

Component Code Example:

```
from langflow.base.io.text import TextComponent
from langflow.io import MultilineInput, Output
from langflow.schema.message import Message

class MultiTextInputComponent(TextComponent):
    display_name = "Text Input"
    description = "Get text inputs from the Playground."
    icon = "type"
    name = "TextInput"

    inputs = [
        MultilineInput(
            name="user_input",
            display_name="Text",
            info="Text to be passed as input.",
        ),
        MultilineInput(
            name="person",
            display_name="Text",
            info="Persona in which the reply should be given.",
        ),
    ]
    outputs = [
        Output(display_name="user", name="text", method="user_response"),
        Output(display_name="person", name="text", method="person_response")
    ]

    def user_response(self) -> Message:
        return Message(
            text=self.user_input,
        )
    def person_response(self) -> Message:
        return Message(
            text=self.person,
        )

```

Additional Information:
This issue seems to have been introduced in version 1.0.19. The component works as expected in 1.0.18.

https://github.com/user-attachments/assets/c23a5cc2-1dfc-43a2-a35e-3e80ab109296

### Reproduction

Steps to Reproduce:

	1.	Create a custom component with multiple outputs as shown in the code above.
	2.	Attempt to run it in versions 1.0.19 or main.
	3.	Observe that multiple outputs are not generated.

### Expected behavior

Expected Behavior:
Both outputs (user_response and person_response) should be created and returned correctly.

Actual Behavior:
In versions 1.0.19 and main, only one output is created. The second output is not generated, breaking the expected functionality.

### Who can help?

@cris

### Operating System

Mac OS

### Langflow Version

Version Information:  	•	Langflow: 1.0.19 (also broken in main) 	•	Working Version: 1.0.18

### Python Version

3.12

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to help you.
