### ISSUE TITLE
Railway install: No ability to create global variables

### ISSUE THREAD

**Issue by MLorneSmith** [langflow-ai/langflow#4186]
### Bug Description

After the one-click install of Langflow on Railway (latest version), I can't seem to create any global variables. Getting the following error:
'Error creating variable
Fernet key must be 32 url-safe base64-encoded bytes'

### Reproduction

1. Install latest version of Langflow on railway
2. Attempt to create a global variable

### Expected behavior

I expect to be able to create a variable

### Operating System

Railway environment

### Langflow Version

1.0.19

### Python Version

None

**Comment by lgertel** [comment]
News on this one?

**Comment by jordanrfrazier** [comment]
Hi @lgertel, are you able to reproduce this issue on the newly released v1.1.0? https://pypi.org/project/langflow/

**Comment by lgertel** [comment]
Yes! Running on 1.1.0 railway

**Comment by jordanrfrazier** [comment]
@lgertel First time using railway, can you do me a favor and provide any Settings changes you made to build correctly?

**Comment by carlosrcoelho** [comment]
@lgertel 

Do you need any assistance with this case? If not, please let us know if this issue can be closed.

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to help you.
