### ISSUE TITLE
Inconsistent behavior after updating the name of a global variable

### ISSUE THREAD

**Issue by eric-schneider** [langflow-ai/langflow#4191]
### Bug Description

After updating the name of a global variable (not its value), references to that global variable in existing projects exhibit inconsistent behavior depending on the type of field the variable is referenced in. 

### Reproduction

1. Go to **Settings > Global Variables** and create a variable with name `VARIABLE1` and some value. (Variable type doesn't matter; the bug affects both Generic and Credential type variables.)
2. Create a new project and add an instance of the OpenAI model component.
3. Add the `VARIABLE1` global attribute to both the **Input** and **OpenAI API Key** fields.
4. Go back to **Settings > Global Variables** and change the name from ~`VARIABLE1`~ --> `VARIABLE2`.
5. Go back to your project and inspect the component. Notice that the **Input** field still references `VARIABLE1`, and the  **OpenAI API Key** field is empty.
6. Navigate away from the project (e.g. go to the dashboard), and then go back to the project again. Notice that both fields are now empty.

### Expected behavior

I expected one of two things to happen:

1. Both fields to be empty.
**_OR_**
2. Both fields to update to the new name.

So the only thing I can concretely say is a bug is the old variable name sticking around in the **Input** field. However, I think serious consideration should be given to number 2. It doesn't make much sense to me that you're allowed to change the name of a global variable if that action removes it from all your existing projects. That's effectively the same behavior as deleting the global variable. (Though, I guess you could could make an argument that it still allows you to persist a secret within Langflow without having to re-add it.)

### Who can help?

@anovazzi1, @Cristhianzl, @lucaseduoli 

### Operating System

macOS 14.7, Docker

### Langflow Version

1.0.19

### Python Version

3.11

### Screenshot

https://github.com/user-attachments/assets/21f9686d-4481-44c2-8076-5c76c1532837

**Comment by carlosrcoelho** [comment]
Hey @eric-schneider 
Did you get a chance to test it on the new version 1.1.1 of Langflow? Please let me know if the problem persists.

**Comment by eric-schneider** [comment]
Sorry I'm only seeing this now @carlosrcoelho. Unfortunately, I haven't had a chance to use Langflow 1.1.1 yet.

However, I see that @lucaseduoli and @mendonk are working on updates to the global variables docs in https://github.com/langflow-ai/langflow/pull/4878. Perhaps as part of that work they can try to reproduce the bug to see if it still persists.
