### ISSUE TITLE
Langflow traces are not well reflected in Langfuse

### ISSUE THREAD

**Issue by codenprogressive** [langflow-ai/langflow#4212]
### Bug Description

Not able to see Langflow components inputs and outputs in Langfuse tracing. 
For instance, for a given component, you will see the component python code instead of the input data. And the Output is completely empty. 

See screenshot below.

### Reproduction

1. create a simple flow with chat input, prompt, and a chat output! flow example [reproduce _error_langfuse (1).json](https://github.com/user-attachments/files/17446337/reproduce._error_langfuse.1.json)
2. connect to Langfuse, and see trace.
3. notice that components input are tracking the python code of the component and not the data inputted
4. notice that the component output is empty

see screenshow:
![image](https://github.com/user-attachments/assets/9461c3f1-cf90-430a-8d38-54ab61418e99)

### Expected behavior

I'm expecting to see input data (not the python code) and output data of each components.

### Who can help?

@italojohnny 

### Operating System

Ubuntu

### Langflow Version

1.0.19

### Python Version

3.10

### Screenshot

![image](https://github.com/user-attachments/assets/9461c3f1-cf90-430a-8d38-54ab61418e99)

### Flow File

[reproduce _error_langfuse (1).json](https://github.com/user-attachments/files/17446337/reproduce._error_langfuse.1.json)

**Comment by codenprogressive** [comment]
In version 1.0.18 traces were working fine. Looks like something was introduced in v19 resulted into breaking things. I see [tracing service](https://github.com/langflow-ai/langflow/blob/main/src/backend/base/langflow/services/tracing/service.py ) logic was slightly changed when introducing ruff rules.

**Comment by zcasanova** [comment]
> In version 1.0.18 traces were working fine. Looks like something was introduced in v19 resulted into breaking things. I see [tracing service](https://github.com/langflow-ai/langflow/blob/main/src/backend/base/langflow/services/tracing/service.py) logic was slightly changed when introducing ruff rules.

I spend a long time debugging this.  And you are right, it is a bug that was introduced in the latest version :-(.

**Comment by sunny6chen** [comment]
I found that the _end_and_reset function has an issue: self._reset_io() clears the outputs before the task is executed.

**Comment by sunny6chen** [comment]
I found that the _end_and_reset function has an issue: self._reset_io() clears the outputs before the task is executed.

**Comment by colecal** [comment]
Same issue here; is there an ETA on a patch?

**Comment by italojohnny** [comment]
The reported behavior was introduced specifically in commit 4221fa40e610df564971b328b3b0ee41178077a2 (PR #3694).

However, from my analysis, all trace data is still present. What changed is that the component’s Python code is now included as well, which is quite annoying.

**Comment by codenprogressive** [comment]
@italojohnny other than the python code is being added into the input. The output is not showing empty. See above screenshot. Were you able to reproduce the empty output?

**Comment by zcasanova** [comment]
> @italojohnny other than the python code is being added into the input. The output is not showing empty. See above screenshot. Were you able to reproduce the empty output?

Thanks for clarifying this.  I also saw that output was not being produced, which was how I noticed the bug in the first place.  My scoring code that needs to pull the observation results broke.

**Comment by italojohnny** [comment]
Hello, @codenprogressive , @sunny6chen, @colecal and @zcasanova 
I believe PR #4669 has addressed the issues reported here. Could you please check again?

**Comment by italojohnny** [comment]
Thank you for your response, @rors41 . In this case, I believe the issue might be specifically related to this component. Could you open a new issue to report it?

I’ll go ahead and close this issue. If you encounter any other problems, please don’t hesitate to open a new one.
