### ISSUE TITLE
Error in SQL Executor component: unexpected keyword argument 'code'

### ISSUE THREAD

**Issue by carlosrcoelho** [langflow-ai/langflow#4223]
### Bug Description

The SQL Executor component returns an error: 'Error Building Component'.

The error message specifically states: `Error building Component SQL Executor: SQLExecutorComponent.build() got an unexpected keyword argument 'code'`.

### Reproduction

1. Use the SQL Executor component in a flow.
2. Run the flow.

### Expected behavior

The SQL Executor component should execute without errors.

### Operating System

Any

### Langflow Version

1.0.19

### Python Version

None

### Screenshot

![1000032014](https://github.com/user-attachments/assets/a6130d09-f73a-4d9e-98bf-34cb6d6b0761)

**Comment by carlosrcoelho** [comment]
https://github.com/langflow-ai/langflow/pull/4200

**Comment by Cristhianzl** [comment]
#4223
