### ISSUE TITLE
Ollama Fails in Hierarchical Crew

### ISSUE THREAD

**Issue by jesst3r** [langflow-ai/langflow#4225]
### Bug Description

When trying to use the Ollama LLM as a replacement for OpenAI in the "Hierarchical Crew" dynamic agent, the workflow fails with an error. The error message states that an LLM provider was not provided:
```
Error building Component Hierarchical Crew: 

litellm.BadRequestError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. You passed model=metadata={} base_url='http://localhost:11434' model='gemma-2-9b_2:latest' mirostat=0 temperature=0.1 system='' template='' format=''
 Pass model as E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/starcoder',..)` Learn more: https://docs.litellm.ai/docs/providers

Traceback (most recent call last):
  File "C:\Users\jesse\AppData\Local\hatch\env\virtual\langflow\30eUVbqK\langflow\lib\site-packages\crewai\agent.py", line 228, in execute_task
    result = self.agent_executor.invoke(
  File "C:\Users\jesse\AppData\Local\hatch\env\virtual\langflow\30eUVbqK\langflow\lib\site-packages\crewai\agents\crew_agent_executor.py", line 92, in invoke
    formatted_answer = self._invoke_loop()
  File "C:\Users\jesse\AppData\Local\hatch\env\virtual\langflow\30eUVbqK\langflow\lib\site-packages\crewai\agents\crew_agent_executor.py", line 173, in _invoke_loop
    raise e
  File "C:\Users\jesse\AppData\Local\hatch\env\virtual\langflow\30eUVbqK\langflow\lib\site-packages\crewai\agents\crew_agent_executor.py", line 113, in _invoke_loop

```
The error suggests that the "model" or some related parameter was not correctly passed or recognized by the system. However, this issue only occurs when using Ollama as the LLM; replacing it with OpenAI works flawlessly. The specific error appears to indicate a missing "model" key or incorrectly set "metadata", "base_url", "template", or similar parameters.

### Reproduction

1. Create a new LangFlow flow with a Hierarchical Crew dynamic agent.
2. Replace OpenAI with Ollama as the LLM provider.
3. Configure the connection appropriately with a base URL like http://localhost:11434 (and seletct model)
4. Execute the flow.

### Expected behavior

The Hierarchical Crew agent should invoke Ollama based crews successfully and generate responses, just as it does with OpenAI.

### Operating System

Windows 11

### Langflow Version

1.0.19

### Python Version

3.10

**Comment by scofano** [comment]
Hi @jesst3r how did you got this fixed? I'm having the same issue.

**Comment by scofano** [comment]
@dosu where is the provider field?

**Comment by austin-duff-prft** [comment]
@jesst3r Resolution please?
