### ISSUE TITLE
Adjust API Default Body for Enabled Tweaks

### ISSUE THREAD

**Issue by joaoguilhermeS** [langflow-ai/langflow#4226]
### Feature Request

**Issue Description:**

When the tweaks flag is enabled in the Langflow API UI, the default request body often fails to work correctly, especially when multiple Text Inputs are involved. This leads to an error message like:

`{"detail": "If you pass an input_value to the chat input, you cannot pass a tweak with the same name."}`

**Steps to Reproduce:**

1. Enable the tweaks flag in the Langflow API UI.
2. Attempt to send a request with the following body (chat memory start template):

```bash
curl -X POST \
    "http://127.0.0.1:7860/api/v1/run/b36fc7f6-61e7-4886-bc9d-9b24c8eb11ee?stream=false" \
    -H 'Content-Type: application/json' \
    -d '{
        "input_value": "message",
        "output_type": "chat",
        "input_type": "chat",
        "tweaks": {
            "Prompt-5aOMc": {
                "context": "",
                "template": "{context}\n\nUser: {user_message}\nAI: ",
                "user_message": ""
            },
            "ChatInput-HAuS5": {
                "files": "",
                "input_value": "",
                "sender": "User",
                "sender_name": "User",
                "session_id": "",
                "should_store_message": true
            },
            "OpenAIModel-RsQXM": {
                "api_key": "OPENAI_API_KEY",
                "input_value": "",
                "json_mode": false,
                "max_tokens": null,
                "model_kwargs": {},
                "model_name": "gpt-4o",
                "openai_api_base": "",
                "output_schema": {},
                "seed": 1,
                "stream": false,
                "system_message": "",
                "temperature": 0.1
            },
            "ChatOutput-NHkfn": {
                "data_template": "{text}",
                "input_value": "",
                "sender": "Machine",
                "sender_name": "AI",
                "session_id": "",
                "should_store_message": true
            },
            "Memory-AZIsb": {
                "n_messages": 100,
                "order": "Ascending",
                "sender": "Machine and User",
                "sender_name": "",
                "session_id": "",
                "template": "{sender_name}: {text}"
            }
        }
    }'
```

**Expected Behavior:**

The request should process correctly without conflicting input values, allowing for proper handling of multiple Text Inputs.

**Actual Behavior:**

The request fails with the error message:

`{"detail": "If you pass an input_value to the chat input, you cannot pass a tweak with the same name."}`

**Additional Information:**

It seems that the default body generated when tweaks are enabled is incompatible in certain scenarios, especially when more than one Text Input is used. Adjustments to the default body structure are needed to prevent these conflicts.

### Motivation

I've noticed that some Langflow users experience frustration when trying to use the API, particularly when working with multiple tweaks. The current setup can be confusing when you have not a single task to make your app deployable. A clearer disclaimer or more detailed guidance about how tweaks interact with API requests could significantly improve the user experience, making it easier for users to configure their setups and avoid common pitfalls.

**Comment by edwinjosechittilappilly** [comment]
https://github.com/langflow-ai/langflow/issues/4148
