### ISSUE TITLE
Error building Component Hierarchical Crew

### ISSUE THREAD

**Issue by Arron-Clague** [langflow-ai/langflow#4264]
### Bug Description

This component does not work for me no matter what I use as LLM provider : for example : Error building Component Hierarchical Crew: litellm.AuthenticationError: AuthenticationError: OpenAIException - Error code: 401 - {'error': {'message': 'Incorrect API key provided: dummy. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}

I have tried it with multiple providers, and it looks like an issue with the LLM model name is passed ? 

### Reproduction

Try to run the Default Workflow for Dynamic Agents

### Expected behavior

For the component to access and LLM provider

### Who can help?

@ogabrielluiz @italojohnny

### Operating System

Ubuntu Linux 24.04

### Langflow Version

1.0.19post1

### Python Version

3.11

**Comment by carlosrcoelho** [comment]
Hey @Arron-Clague 

<img width="2053" alt="image" src="https://github.com/user-attachments/assets/8a765b37-f114-4707-b90e-8526e40d8829">

<img width="1937" alt="image" src="https://github.com/user-attachments/assets/2c28fcac-2628-4883-8f37-d5c665b04abb">

I just ran a test using the Get Started - Dynamic Agent example, and the component worked as expected. I used OpenAI's LLM. I'm on version v1.0.19.post1.

Can you share your flow so I can take a look?

**Comment by Arron-Clague** [comment]
Hi : that’s interesting : actually I was just using the example flow from the wizard.On 24 Oct 2024, at 14:48, Carlos Coelho ***@***.***> wrote:﻿
Hey @Arron-Clague
image.png (view on web)
image.png (view on web)
I just ran a test using the Get Started - Dynamic Agent example, and the component worked as expected. I used OpenAI's LLM. I'm on version v1.0.19.post1.
Can you share your flow so I can take a look?

**Comment by carlosrcoelho** [comment]
From the wizard, what do you mean? Could you share it?

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to help you.
