### ISSUE TITLE
problem in conditional router

### ISSUE THREAD

**Issue by sunilgiri7** [langflow-ai/langflow#4271]
when iam try to drag and drop conditional router card it is crashing everytime and giving me error "Sorry, we found an unexpected error!" look onto it

**Comment by sunilgiri7** [comment]
iam using langflow in website where iam trying to use conditional Router
which I am not able to use it is crashing and asking for restart

**Comment by sunilgiri7** [comment]
issue resolved when i logged out and again login the website, fix your
session issue in website it needs logout automatically or ask for login
again when my session is over

**Comment by carlosrcoelho** [comment]
What version are you using? Try on v1.0.19.post1.


https://github.com/user-attachments/assets/e9179d1b-8a2d-4c03-a25d-e1cfa6613f45
