### ISSUE TITLE
ImportError: cannot import name 'CodeInterpreter' from 'e2b_code_interpreter'

### ISSUE THREAD

**Issue by Geo99pro** [langflow-ai/langflow#4295]
### Bug Description

**Hi everyone,**

First of all, I would like to congratulate the whole team for their hard work in making Langflow available.

I’m encountering an issue after installing Langflow in a conda environment. When I run `python -m langflow run`, I receive the following error: 

``ImportError: cannot import name 'CodeInterpreter' from 'e2b_code_interpreter'``.

I’ve attached a screenshot below to illustrate the problem.

I did some investigation on my side to understand the cause. It appears that the `pip install e2b` method available [here](https://pypi.org/project/e2b/) only calls the `Sandbox` method directly from `e2b_code_interpreter`. It seems that `CodeInterpreter` no longer exists in the `e2b_code_interpreter` package.

Could you please provide guidance on how to resolve this issue?

Thanks in advance for your help!

### Reproduction

1.  conda create -n langflow_world python==3.10
2.  python -m pip install langflow -U
3.  python -m langflow run

### Expected behavior

Langflow running at http://127.0.0.1:7860

### Who can help?

@Cristhianzl  @igorrCarvalho @italojohnny 

### Operating System

Windows 11

### Langflow Version

v1.0.19.post2

### Python Version

3.10

### Screenshot

![image](https://github.com/user-attachments/assets/033288bf-ef66-4675-92ef-a88b67b143b6)

**Comment by sirmax672** [comment]
I have the same issue

**Comment by Geo99pro** [comment]
> I have the same issue

may be this help you @sirmax672

**Comment by italojohnny** [comment]
This issue is related to #4164

**Comment by Geo99pro** [comment]
> Thanks i'll have a look!

**Thank you, Sir.** 

I was able to identify the issue by reviewing the documentation and code in the [DataStax Astra Assistants API repository](https://github.com/datastax/astra-assistants-api). I've submitted a pull request to address this, which can be found [here](https://github.com/datastax/astra-assistants-api/pull/77).
