### ISSUE TITLE
Flow disappears 

### ISSUE THREAD

**Issue by Gluepower** [langflow-ai/langflow#4345]
### Bug Description

Today again flow simply disappeared. I do regular exports because this happens every few days, but today its irritating because I worked few hours on fine tuning the prompts and all that work is gone. 
Yesterday when I wanted to export I accidentally clicked share to store. This is often mistake because in order to download flow you have to click share and then go left click download and then confirm right. Its designed in a way to do accidental share and I understand that, but issue is as soon I clicked share its in the store but got deleted from my instance. I uploaded that flow again from my computer, did some work few hours spent probably $30 on prompting and few hours later I got back its gone again. This time it seems there was some small update got synced with github and during restart of instance its just gone again. Its so tiring that 30% of the time I am just redoing same work because flow randomly disappearing. 

### Reproduction

Its random

### Expected behavior

There should be some safeguard so flow can't disappear. 

### Operating System

Render

### Langflow Version

1.0.19.post2

### Python Version

3.12

### Flow File

Search for "PostHumanPulse Article Writing". There are four uploads all accidentally shared and can't find a way to delete them.

**Comment by Cristhianzl** [comment]
Hi @Gluepower,

I’m sorry to hear about the trouble you're having with Langflow. I'll do my best to help debug this issue with you.

**To delete the accidentally shared flow**
Please visit [Langflow Store](https://www.langflow.store/) to manage it. Our store functions similarly to a GitHub for flows and components, so if you've added a Store API Key, you can share flows directly from your Langflow application. However, to manage or delete flows, you'll need to do so on the Store website.

**Regarding the disappearing flow**
I attempted to reproduce this issue locally but wasn't able to replicate it. I'd be glad to help you investigate further to see if the flow exists in your database.

**Accessing Your Database:** You can locate your database by following the instructions in our [settings documentation](https://docs.langflow.org/settings-global-variables).


![image](https://github.com/user-attachments/assets/79b79fb7-1b0f-4fc5-a2b8-aef15f7e5657)


Verifying Flow Existence: Once you have access, check if your flow is saved in the database. This will help us determine if the database is properly saving your flow or if something is causing it to be deleted, possibly during instance restarts.

Let me know what you find, and we can continue troubleshooting from there!
