### ISSUE TITLE
Split Text Component Causes LangFlow to crash 

### ISSUE THREAD

**Issue by RETR0-OS** [langflow-ai/langflow#4371]
Hello.
I am trying to use LangFlow to develop a RAG-based application. When I try to drag in the Split Text component, LangFlow crashes.

![image](https://github.com/user-attachments/assets/f64534ca-8b0a-429f-b316-683dcaab123d)

Here is the exact error message I see (not very helpful, I know). Even the console outputs no errors for me to paste in. 

https://github.com/user-attachments/assets/3239cf25-d61a-4cf1-962d-d69fb92a0fc0

Here is a video that displays the error being recreated.

(I am sorry if this issue is not very professionally written. This is my first time opening up a GitHub issue. I would love some constructive criticism. Thank you for your kind consideration. Please let me know if you require any additional information. Thank you.)

**Comment by joaoguilhermeS** [comment]
Hi @RETR0-OS , which version of Langflow are you using? This issue is uncommon and should not occur. Since you’re running it on Localhost, please share your terminal logs.

Ensure you’re using Python 3.10–3.12 and have installed Langflow in a separate virtual environment. You can set it up like this:

```
python3 -m venv env
source env/bin/activate
pip install -U langflow
python -m langflow run
```

**Comment by RETR0-OS** [comment]
Hello, @joaoguilhermeS 
Thanks for your response. For some reason, it is no longer an issue. I have no idea about what changed. Anyways, The issue is resolved now. Thank you for your time.

**Comment by RETR0-OS** [comment]
I feel like I should still provide the info you requested so here it is:

```
langflow==1.0.19.post2
langflow-base==0.0.99
```

And sorry, I can't provide the terminal output any longer. That issue is no longer arising. Thank you for your help.
