### ISSUE TITLE
Dynamic Agent template: OpenAI key error

### ISSUE THREAD

**Issue by L-Huber** [langflow-ai/langflow#4395]
### Bug Description

I currently want to expand the [Dymanic Agent](https://docs.langflow.org/Starter-Projects/starter-projects-dynamic-agent) of langflow. However, I get the following error:
AuthenticationError: litellm.AuthenticationError: AuthenticationError: OpenAIException - Error code: 401 - {'error':
{'message': 'Incorrect API key provided: dummy. You can find your API key at
https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code':
'invalid_api_key'}}

### Reproduction

1. Choose the Dynamic Agent template as a new project in langflow
2. Add your openAI KI
3. Run the flow

### Expected behavior

There should not be an error and the flow should be working

### Who can help?

@ogabrielluiz @nicoloboschi @zzzming @jo

### Operating System

MacOS 

### Langflow Version

1.3.5

### Python Version

3.11

### Screenshot

<img width="983" alt="Bildschirmfoto 2024-11-05 um 10 06 21" src="https://github.com/user-attachments/assets/4b932226-4bd7-4e8d-a163-bfb09ce6f061">

**Comment by carlosrcoelho** [comment]
Hey @L-Huber 

What version are you using?

I just tried on the latest version 1.0.19.post2 and worked as expected.

<img width="1989" alt="image" src="https://github.com/user-attachments/assets/14eb29ff-fd90-4e04-a794-3b7a52504e15">

**Comment by carlosrcoelho** [comment]
@L-Huber 

Can you share your flow?

**Comment by L-Huber** [comment]
[Dynamic Agent (3) - not working.json](https://github.com/user-attachments/files/17652961/Dynamic.Agent.3.-.not.working.json)
sure!

**Comment by carlosrcoelho** [comment]
@L-Huber 
Make sure all the OpenAI components have the API Key.

I tried to replicate it, but I didn't get the error.
<img width="1362" alt="image" src="https://github.com/user-attachments/assets/f0b316b3-f0df-43c0-9578-4fa567d224f5">

However, if I forget to add an API Key to a component, the error appears.
<img width="1557" alt="image" src="https://github.com/user-attachments/assets/9ed36de5-d9a7-4fe9-9de0-a5b919e81060">

**Comment by L-Huber** [comment]
@carlosrcoelho that is the funny thing: all previous steps until "Hierarchical Crew" work: 
<img width="759" alt="Bildschirmfoto 2024-11-06 um 23 17 58" src="https://github.com/user-attachments/assets/402f0af1-be49-44be-8e56-1c146b8bb4b3">
so the API key should be correct.

**Comment by SavvySupport** [comment]
I have the same issue. I think it's an error with "Hierarchical Crew" component. I tried using Groq as the LLM, and there's an issue with that too. 

Error building Component Hierarchical Crew: 

litellm.BadRequestError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. You passed model=llama-3.2-1b-preview
 Pass model as E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/starcoder',..)` Learn more: https://docs.litellm.ai/docs/providers

**Comment by L-Huber** [comment]
@SavvySupport Do you have any solution to this?

**Comment by yannisTr** [comment]
Hello, 

Same error here with sequential crew and custom base url for the llm (to use with openrouter). All previous steps work fine, llm works with other types of components (like chains).

**Comment by austin-duff-prft** [comment]
Same issue.

**Comment by guilegarcia** [comment]
I'm experiencing the same issue. Has anyone found a solution? I believe it might be a bug.

**Comment by carlosrcoelho** [comment]
Hey @L-Huber 

Did you try using the new version 1.1.1? Test it out and let me know.

**Comment by L-Huber** [comment]
@carlosrcoelho I will try it out with the new version and let you know. I might actually be a version issue.

**Comment by carlosrcoelho** [comment]
@L-Huber 

Do you need any assistance with this case? If not, please let us know if this issue can be closed.

**Comment by L-Huber** [comment]
@carlosrcoelho I currently cannot even upgrade my langflow version. Is this is known issue?

**Comment by carlosrcoelho** [comment]
@L-Huber 

Sorry to hear that.

Please give a try using `uv`.

Doc: https://docs.langflow.org/get-started-installation

**Comment by exs-xgg** [comment]
running on 1.3.2, also getting the error. 
We have saved the openai key to the global variable and it seems like it is randomly resetting to "dummy". We have tried to isolate the specific cause of this but to no avail.

**Comment by exs-xgg** [comment]
Following up on this -  i can successfully recreate the bug. When logging out, the OPENAI_API_KEY resets to "dummy"

**Comment by logandeal** [comment]
Experiencing the same issue as @exs-xgg

**Comment by sarafandee** [comment]
Has this been fixed? I still get the same error, it is resetting it to dummy after logging out or restarting the container
