### ISSUE TITLE
Nothing displayed in logs tab of Component Output

### ISSUE THREAD

**Issue by linnie98** [langflow-ai/langflow#4397]
### Bug Description

Hi I'm using langflow version 1.0.19 and there is a logs tab in Component Output but displays nothing. Is this behavior normal ? If not, how can I see the logs? If it's normal, when will logs section ready to use?

![Snipaste_2024-11-05_16-44-11](https://github.com/user-attachments/assets/674d637a-0a5c-4091-b96b-f5ebbdc124ee)

### Reproduction

1. use langflow 1.0.19
2. create a custom component and paste the code 
```python
# from langflow.field_typing import Data
from langflow.custom import Component
from langflow.io import MessageTextInput, Output
from langflow.schema import Data

from loguru import logger

class CustomComponent(Component):
    display_name = "Custom Component"
    description = "Use as a template to create your own component."
    documentation: str = "http://docs.agione.org/components/custom"
    icon = "custom_components"
    name = "CustomComponent"

    inputs = [
        MessageTextInput(name="input_value", display_name="Input Value", value="Hello, World!"),
    ]

    outputs = [
        Output(display_name="Output", name="output", method="build_output"),
    ]

    def build_output(self) -> Data:
        data = Data(value=self.input_value)
        

        logger.debug("That's it, beautiful and simple logging!")

        self.status = data
        return data
``` 
3. run the component 
4. open component output and go to logs section

### Expected behavior

No Data Available
Oops! It seems there's no data to display right now. Please check back later.

### Operating System

Amazon Linux

### Langflow Version

1.0.19

### Python Version

None

**Comment by carlosrcoelho** [comment]
@linnie98 

Can you check if the issue persists in the latest version of langflow version 1.1.1 ?

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to help you.
