### ISSUE TITLE
adding schema in openAI component causes ValueError

### ISSUE THREAD

**Issue by vertgo** [langflow-ai/langflow#4426]
### Bug Description

If adding a schema, it fails. There's no documentation to how that schema should be formatted either (do I add a key and a type like number,"boolean" or "bool," or the actual value like "true" or "10"?

No matter what I add, when I build it, it causes the valueerror
ValueError: Error Building Component
Error building Component OpenAI: dictionary update sequence element #0 has length 1; 2 is required

### Reproduction

1. Add openAI model component
2. turn on json and schema in the advanced settings
3. add key value pair/s to the schema
4. add your openAI key
5. hit build

### Expected behavior

it builds and outputs structed JSON

### Who can help?

@ogabrielluiz @italojohnny

### Operating System

macOS 14.6.1

### Langflow Version

1.0.19post1

### Python Version

None

### Screenshot

![image](https://github.com/user-attachments/assets/a7df82d1-4d9a-4686-9913-655235e0d746)
![image](https://github.com/user-attachments/assets/6a7a5e55-66f5-4c02-b1c0-8a0ffcff2bef)

### Flow File

[schema error.json](https://github.com/user-attachments/files/17651307/schema.error.json)

**Comment by edwinjosechittilappilly** [comment]
Hi @vertgo ,
Can you check if the issue persists in the latest version of langflow version 1.1.1  ?

Happy to help if the issue still occurs.

**Comment by edwinjosechittilappilly** [comment]
We are currently closing this issue. If you encounter any further problems, please reopen the issue and let us know. We are happy to help.
