### ISSUE TITLE
New Store Message component in the latest DataStax Langflow (11/6/24) errors on Chat Output messages

### ISSUE THREAD

**Issue by SonicDMG** [langflow-ai/langflow#4432]
### Bug Description

After updating to the latest Store Message component my flow breaks with the error in the attached image
"Error building Component Store Message: Object of type Message is not JSON serializable"

### Reproduction

1. Connect a Chat Output (Message) to the Messages Input (Message) of the new Store Message component
2. Attempt to execute a flow with some chat output

I included my flow *.json for troubleshooting

### Expected behavior

The updated Store Message component correctly stores message output from the Chat Output component

### Other details
I also tried pulling in the component from the left hand menu with no luck.
Looking a bit more deeply I see that the new component uses MessageInput as compared to StrInput for all of the inputs. 

### Operating System

DataStax Langflow

### Langflow Version

1.0.19.post1???

### Python Version

None

### Screenshot

![Screenshot 2024-11-06 at 4 47 18 PM](https://github.com/user-attachments/assets/9504b810-6265-4f65-9038-78296956f580)

### Flow File

[Zoom _ Astra_ERROR.json](https://github.com/user-attachments/files/17653615/Zoom._.Astra_ERROR.json)

**Comment by erichare** [comment]
@SonicDMG On latest Main, i can't seem to reproduce - see the screenshot attached. I tried to create the simplest example based on your steps for reproducing. Anything im missing?

<img width="1062" alt="Screenshot 2024-11-07 at 8 40 19 AM" src="https://github.com/user-attachments/assets/dd10b3c9-4935-4b17-8442-163473327fb8">
