### ISSUE TITLE
New Store Message component (11/6/24) doesn't work without external memory

### ISSUE THREAD

**Issue by SonicDMG** [langflow-ai/langflow#4433]
### Bug Description

When attempting to use the new Store Message component in DS Langflow without external memory I see the following error:

Error building Component Store Message: (sqlite3.ProgrammingError) Error binding parameter 2: type 'Message' is not supported [SQL: INSERT INTO message (timestamp, sender, sender_name, session_id, text, id, flow_id, files) VALUES (?, ?, ?, ?, ?, ?, ?, ?)] [parameters: ('2024-11-06 22:15:27.000000', Message(text_key='text', data={'text': '', 'files': [], 'timestamp': '2024-11-06 22:15:28'}, default_value='', text='', sender=None, sender_name=None, files=[], session_id='', timestamp='2024-11-06 22:15:28', flow_id=None), Message(text_key='text', data={'text': '', 'files': [], 'timestamp': '2024-11-06 22:15:28'}, default_value='', text='', sender=None, sender_name=None, files=[], session_id='', timestamp='2024-11-06 22:15:28', flow_id=None), Message(text_key='text', data={'text': '01418a0a-be42-4773-ad3e-a009819fb8c5', 'files': [], 'timestamp': '2024-11-06 22:15:28'}, default_value='', text='01418a0a-be42-4773-ad3e-a009819fb8c5', sender=None, sender_name=None, files=[], session_id='', timestamp='2024-11-06 22:15:28', flow_id=None), 'Yes, streaming works effectively, allowing for realistic video and audio streams in real-time during meetings.', '10754203627848a2b81c6388e3fd50a1', '01418a0abe424773ad3ea009819fb8c5', '[]')] (Background on this error at: https://sqlalche.me/e/20/f405)

The previous version of this component seems to work fine using the same scenario.

### Reproduction

1. Create a Store Message component
2. Wire up an input
3. Execute without external memory attached

### Expected behavior

The component should work with or without external memory attached

### Operating System

DataStax Langflow

### Langflow Version

1.0.19.post1???

### Python Version

None

### Screenshot

![Screenshot 2024-11-06 at 5 17 28 PM](https://github.com/user-attachments/assets/367a3e27-cd58-4e12-a612-174dc9652ebc)

### Flow File

[Zoom _ Astra_ERROR.json](https://github.com/user-attachments/files/17653694/Zoom._.Astra_ERROR.json)

**Comment by edwinjosechittilappilly** [comment]
@erichare  Please consult with @ogabrielluiz  regarding this issue.
I believe this is fixed in one of the agent branches.
if its an issue related to datetime not JSON serializable

**Comment by erichare** [comment]
Thanks for the heads up @edwinjosechittilappilly .  @ogabrielluiz would love your comments before diving further

**Comment by carlosrcoelho** [comment]
@SonicDMG 

Do you need any assistance with this case? If not, please let us know if this issue can be closed.

Give a try on version 1.1.1
