### ISSUE TITLE
Unclosed event loop error when running langflow 

### ISSUE THREAD

**Issue by SavvySupport** [langflow-ai/langflow#4436]
### Bug Description

When I run langflow (version .19.post2), it gives me this error message.

### Reproduction

1. langflow run 
2. langflow runs as per usual however there is this error message:
/usr/lib/python3.10/asyncio/base_events.py:688: ResourceWarning: unclosed event loop <_UnixSelectorEventLoop running=False closed=False debug=False>
  _warn(f"unclosed event loop {self!r}", ResourceWarning, source=self)
ResourceWarning: Enable tracemalloc to get the object allocation traceback

### Expected behavior

Should not show the error message. 

### Operating System

Mac

### Langflow Version

1.0.19.post2

### Python Version

3.10

### Screenshot

https://prnt.sc/oxA7HXe2xMk0

**Comment by kkjinping** [comment]
ubuntu same error

**Comment by romeuow** [comment]
@Cristhianzl version v1.1. is with [this issue](https://github.com/langflow-ai/langflow/issues/4698)

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to help you.
