### ISSUE TITLE
Error running graph: list index out of range

### ISSUE THREAD

**Issue by Chander88** [langflow-ai/langflow#4441]
### Bug Description

When I submit the request to on server. I got the response from **API Error running graph: list index out of range**.

### Reproduction

Attached the screenshot.

### Expected behavior

Please review screenshot.

### Who can help?

@italojohnny 

### Operating System

ubuntu 22.04.1

### Langflow Version

langflow   1.0.19.   and langflow-base   0.0.99

### Python Version

3.10

### Screenshot

![Screenshot from 2024-11-07 14-33-38](https://github.com/user-attachments/assets/0119adf7-de95-4989-a7b4-5acf9770ccb1)

**Comment by italojohnny** [comment]
Hello, @Chander88 8. How are you?

To help you effectively, I first need to reproduce the issue on my end. Could you provide your flow and any additional information on the conditions I should set to encounter the same problem you’re experiencing?

**Comment by Chander88** [comment]
Hello @italojohnny,

Thankyou  for helping.
I am running two server one is Node and another is the Langflow.
Basically it is the AI application and when I hitting the request to langflow server with some audio message.
Langflow throws the error Error running graph: list index out of range.
I use the flow Id that I got form the Python API when I dashboard of server.

Please let me know if any further details required.

**Comment by italojohnny** [comment]
I sincerely apologize for the delay in responding, but I was unable to reproduce your issue.

In the meantime, we have released version 1.1.1. Could you check if the issue still occurs with this new version?

If it does, could you share a copy of your flow and/or the complete error log? This would greatly help me identify the problem.

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to help you.
