### ISSUE TITLE
How to increase API timeout more then 60 sec

### ISSUE THREAD

**Issue by buntys2010** [langflow-ai/langflow#4442]
### Bug Description

The API responds very slow, if the workflow is too long or call LLM multiple times the API fail to respond due to timeout error with 504.

How to increase the API timeout limit?

### Reproduction

The API responds very slow, if the workflow is too long or call LLM multiple times the API fail to respond due to timeout error with 504.

How to increase the API timeout limit?

### Expected behavior

The API should have timeout parameter to set the API timeout issues.

### Operating System

ubuntu 22.04

### Langflow Version

1.0.17

### Python Version

3.10

**Comment by italojohnny** [comment]
You can adjust the Langflow API timeout by using the --worker-timeout parameter in the command line as shown below:
```
langflow run --worker-timeout 30
```
Alternatively, you can set this parameter through an environment variable:
```
LANGFLOW_WORKER_TIMEOUT=30 langflow run
```
