### ISSUE TITLE
Azure OpenAI Embeddings not accepted by Astra DB component

### ISSUE THREAD

**Issue by josefpolach** [langflow-ai/langflow#4462]
### Bug Description

I am trying to ingest data from PDF file to Astra DB using Azure OpenAI embeddings, but no matter if I use LangFlow on-line from datastax domain or via docker-compose the result is the same

docker:
![image](https://github.com/user-attachments/assets/c17bee8f-3daf-4352-8992-9424d5469c98)

datastax online: 
![image](https://github.com/user-attachments/assets/4cfc15dc-1995-4d44-a976-f137adb0bfe2)

### Reproduction

1. open RAG flow from LangFlow template
2. focus on the ingestion part at the bottom
3. replace OpenAI Embeddings by Azure OpenAI Embeddings
4. run the flow
5. you encounter an error: Error building Component Astra DB: Error initializing AstraDBVectorStore: Unsupported data type

I checked the docker Logs but it's nothing there except: 

```
ValueError: Error initializing
AstraDBVectorStore: Unsupported data type
```

### Expected behavior

The flow builds successfully and the content is sent to Astra DB.

### Operating System

Docker Compose 

### Langflow Version

image: langflowai/langflow:latest

### Python Version

None

### Flow File

https://astra.datastax.com/langflow/ebf1ade5-1471-4ecb-948c-1055de0f9e9a/flow/be5c72e1-802f-4be8-959c-404f5ccb3055/folder/469dd6bc-8ac4-4bc3-8cea-756c61cedb09

[OpenAI Astra Ingestion (1).json](https://github.com/user-attachments/files/17672264/OpenAI.Astra.Ingestion.1.json)

**Comment by edwinjosechittilappilly** [comment]
Hi @josefpolach 
Thank you for the feedback.
Can you check if the issue persists in the latest version of langflow version 1.1.1  ?

Happy to help if the issue still occurs.

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to help you.

**Comment by mh2016tr** [comment]
Ciao @edwinjosechittilappilly  I have the same problem currently using Langflow. I don't understand how to check if I m running on 1.1.1. Currently the source code of the Astra DB component (if I open in the editor) is 1.1.0 looking to github. How can I move to 1.1.1?

**Comment by ChunJen** [comment]
@carlosrcoelho @edwinjosechittilappilly , Same problem happened in langflow version 1.1.1, is there any other method to fix this?
![image](https://github.com/user-attachments/assets/db896b7b-f902-4cd2-9883-59a57a2cbdaf)

![image](https://github.com/user-attachments/assets/f51b3012-aa97-43aa-940d-9240f537699b)
