### ISSUE TITLE
Can't add packages to use for custom components

### ISSUE THREAD

**Issue by dylanwe** [langflow-ai/langflow#4473]
### Bug Description

I'm trying to make an azure ai search component but langflow doesn't come with the `azure-search-documents` package.
I've tried to put the following in my Dockerfile: 
```dockerfile
FROM langflowai/langflow:1.0.19
COPY ./custom_components/components langflow/components
RUN pip install azure-search-documents
CMD ["langflow", "run"]
```

But it still throws the error 
```
ModuleNotFoundError: Module                        
                             azure.search.documents not                         
                             found. Please install it                           
                             and try again     
```

Is this something that would be possible to do or would I need another approach?

### Reproduction

Use the above dockerfile.

### Expected behavior

Installed the azure-search-documents package.

### Who can help?

@ogabrielluiz

### Operating System

MacOS

### Langflow Version

1.0.19

### Python Version

3.12

**Comment by devinbost** [comment]
I had to install packages like this:

RUN python3 -m venv /app/.venv && \
    /bin/bash -c "source /app/.venv/bin/activate && pip install -U langchain-huggingface mysql-connector-python langchain pydantic"


to ensure they were available in the venv
