### ISSUE TITLE
BerriAI crashes LangFlow upon startup in airgapped environment

### ISSUE THREAD

**Issue by devinbost** [langflow-ai/langflow#4498]
### Bug Description

I'm getting this exception when LangFlow starts on a VM without internet access:

> [11/11/24 16:43:13] ERROR - Error while getting output types from code
> Traceback (most recent call last):
>   File "/app/.venv/lib/python3.12/site-packages/urllib3/connection.py", line 196, in _new_conn
>     sock = connection.create_connection()
>   File "/app/.venv/lib/python3.12/site-packages/urllib3/util/connection.py", line 85, in create_connection
>     raise err
>   File "/app/.venv/lib/python3.12/site-packages/urllib3/util/connection.py", line 73, in create_connection
>     sock.connect(sa)
>   OSError: [Errno 101] Network is unreachable
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/app/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
>     response = self._make_request()
>   File "/app/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 490, in _make_request
>     raise new_e
>   File "/app/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 466, in _make_request
>     self._validate_conn(conn)
>   File "/app/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
>     conn.connect()
>   File "/app/.venv/lib/python3.12/site-packages/urllib3/connection.py", line 615, in connect
>     self.sock = sock = self._new_conn()
>   File "/app/.venv/lib/python3.12/site-packages/urllib3/connection.py", line 211, in _new_conn
>     raise NewConnectionError(
> urllib3.exceptions.NewConnectionError: Failed to establish a new connection: [Errno 101] Network is unreachable
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/app/.venv/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
>     resp = conn.urlopen()
>   File "/app/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 843, in urlopen
>     retries = retries.increment()
>   File "/app/.venv/lib/python3.12/site-packages/urllib3/util/retry.py", line 519, in increment
>     raise MaxRetryError("Max retries exceeded")
> urllib3.exceptions.MaxRetryError: Max retries exceeded with url: /BerriAI/litellm/refs/heads/main/model_prices_and_context_window.json (Caused by NewConnectionError: Failed to establish a new connection: [Errno 101] Network is unreachable)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/app/.venv/lib/python3.12/site-packages/langflow/custom/directory_reader/directory_reader.py", line 348, in abuild_component_menu_list
>     output_types = await self.get_output_types_from_code_async(result_content)
>   File "/app/.venv/lib/python3.12/site-packages/langflow/custom/directory_reader/directory_reader.py", line 317, in get_output_types_from_code_async
>     return await asyncio.to_thread(self.get_output_types_from_code, code)
>   File "/app/.venv/lib/python3.12/site-packages/langflow/custom/directory_reader/directory_reader.py", line 317, in get_output_types_from_code_async
>     return await asyncio.to_thread(self.get_output_types_from_code, code)
>   File "/usr/local/lib/python3.12/asyncio/threads.py", line 25, in to_thread
>     return await loop.run_in_executor(None, func_call)
>   File "/usr/local/lib/python3.12/asyncio/futures.py", line 287, in __await__
>     yield self
>   File "/usr/local/lib/python3.12/asyncio/tasks.py", line 385, in __wakeup
>     future.result()
>   File "/usr/local/lib/python3.12/asyncio/futures.py", line 203, in result
>     raise self._exception.with_traceback(self._exception_tb)
> ConnectionError: MaxRetryError("Max retries exceeded with url: /BerriAI/litellm/refs/heads/main/model_prices_and_context_window.json (Caused by NewConnectionError: Failed to establish a new connection: [Errno 101] Network is unreachable")
> 
> Further traceback:
>   - DirectoryReader.abuild_component_menu_list
>   - DirectoryReader.get_output_types_from_code_async
>   - asyncio.to_thread
>   - requests.get() call
>   - requests.exceptions.ConnectionError

### Reproduction

Start Langflow v1.0.19.post2 on VM without internet

### Expected behavior

LangFlow should start normally

### Who can help?

@phact @italojohnny 

### Operating System

RHEL 8.10

### Langflow Version

1.0.19.post2

### Python Version

None

**Comment by phact** [comment]
Thanks for the big report, will fix asap!

**Comment by phact** [comment]
fix here -- https://github.com/langflow-ai/langflow/pull/4536

Note you still have to pass `DO_NOT_TRACK=true` to disable telemetry.

**Comment by phact** [comment]
Merged
