### ISSUE TITLE
Can't make simple tool agent (google api) : "Too many arguments to single-input tool google_search"

### ISSUE THREAD

**Issue by yannisTr** [langflow-ai/langflow#4518]
Hi,

### Bug Description

**When trying to make a simple tool calling agent that searches the web through google search api it return the following error :**

> ToolException: Too many arguments to single-input tool google_search. Consider using StructuredTool instead. Args: [['social ontology definition', 'what is social ontology'], {'tags': ['ontology', 'social science'], 'max_concurrency': 1}]                                                                                                        

### Reproduction

1. Build a simple tool agent calling flow that calls google search api
2. Run agains any query 
3. See error 

### Expected behavior

Agent answer user's question using google api tool

### Operating System

Mac OS

### Langflow Version

1.0.19

### Python Version

3.12

### Screenshot

<img width="786" alt="image" src="https://github.com/user-attachments/assets/0d43f747-09e6-4a79-ae49-f3d869d248a8">

### Flow File

[flow bug report.json](https://github.com/user-attachments/files/17712981/flow.bug.report.json)

**Comment by yannisTr** [comment]
> Hey @yannisTr! 👋 I'm here to assist you with any bugs, questions, or contributions. Let's work together to resolve this issue.
> 
> The error "Too many arguments to single-input tool google_search" suggests that the `google_search` tool is being provided with more arguments than it expects. The `google_search` tool in Langflow requires specific inputs: `google_api_key`, `google_cse_id`, `input_value`, and `k` (the number of results to return) [[1]](https://github.com/langflow-ai/langflow/blob/main/src/backend/base/langflow/components/tools/google_search_api.py).
> 
> To resolve this issue, ensure that you are passing the correct number of arguments and that they are formatted as expected. If you need to pass multiple inputs or more complex data, consider using a `StructuredTool`, which can handle multiple inputs and outputs with a defined schema [[2]](https://github.com/langflow-ai/langflow/blob/main/src/backend/base/langflow/components/tools/python_code_structured_tool.py).
> 
> Check your flow configuration to ensure that the arguments are correctly mapped to the expected inputs of the `google_search` tool. If you are using keyword arguments, make sure they match the required input names.
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

This is the llm that passes the arguments to the tool. Tried to explicitely prompt "only one argument" or "only one string", didn't work.

**Comment by edwinjosechittilappilly** [comment]
Hi @yannisTr, 

Thank you for your feedback! We have released an enhanced component called the Agent Component, which improves agent capabilities. Please try using the Agent Component in Langflow 1.1. I hope this resolves the issue.

If you continue to experience any problems, please let us know. We’re happy to help!

**Comment by edwinjosechittilappilly** [comment]
We will be closing this issue. If you encounter any further problems, please let us know.
