### ISSUE TITLE
Can't access flow directly by link

### ISSUE THREAD

**Issue by amomra** [langflow-ai/langflow#4528]
### Bug Description

When you try to access a flow using it's URL (ex. http://localhost:55650/flow/0b95342f-6ce4-43d0-9d60-c28bf66a3781), the page doesn't load and in the browser's console is shown the following message: ``Uncaught SyntaxError: Unexpected token '<' (at index-DK9323ab.js:1:1)``. I think that this problem is related to #1182 .

Navegating through the main page to access this flow works fine. If I reload the page, it doesn't load as described before.

### Reproduction

1. Run the Docker image langflowui/langflow
2. Open the langflow main page
3. Creates a new flow
4. Copy the flow link into a new tab or just reload the page

### Expected behavior

To open the flow editor page.

### Operating System

Docker image (langflowai/langflow) running in K8s

### Langflow Version

1.0.19

### Python Version

None

### Screenshot

Instead of loading the JS file, is loaded the HTML file as shown in the following picture:

![image](https://github.com/user-attachments/assets/4a192a11-5389-497f-8898-fd0598684ca1)

All requests in this image loads the same HTML.

**Comment by irshadmb** [comment]
Looks Like it has been fixed in latest. I cross checked latest build its working.

**Comment by irshadmb** [comment]
@amomra I am referring to latest code base. It will be available in upcoming release.

**Comment by irshadmb** [comment]
@amomra today v1.1.0 is released. Please cross check and let us know.

**Comment by amomra** [comment]
@irshadmb thanks for the info. I can't test because I'm having the problem related in #4572.

**Comment by carlosrcoelho** [comment]
@amomra 

Do you need any assistance with this case? If not, please let us know if this issue can be closed.

**Comment by joaoguilhermeS** [comment]
Hi @amomra, this was fixed in the latest langflow docker images, you can refer to them by using the nightly tag, for example: `langflowai/langflow-nightly:v1.1.0.dev5` (I have tested with this one, and it seems to be working just fine).
