### ISSUE TITLE
Memory not clearing

### ISSUE THREAD

**Issue by SavvySupport** [langflow-ai/langflow#4631]
### Bug Description

Memory is not clearing even though I clear it.. 

### Reproduction

1. Click on Playground
2. Delete memory
3. Run "Prompt" component that is connected to "Chat Memory" component 
4. Click on "Prompt Message" to see that chat memory has not been cleared. In fact, it contains memory from other flows. 

See reproduction process here https://www.loom.com/share/799406c9b05c4aa7a2a6095e037d2ff1

### Expected behavior

Expected to see no chat history in Prompt Message. Especially not from other flows. 

### Operating System

Mac OS

### Langflow Version

1.0.19.post2

### Python Version

3.10

### Screenshot

https://www.loom.com/share/799406c9b05c4aa7a2a6095e037d2ff1

**Comment by carlosrcoelho** [comment]
@SavvySupport 
Did you try using version v1.1.0?

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to help you.
