### ISSUE TITLE
Ollama Embedding issue

### ISSUE THREAD

**Issue by Donixon** [langflow-ai/langflow#4633]
### Bug Description

Im trying out the RAG-flow and instead of OpenAI embedding and generation, im using Ollama. The Ollama-embedding part keeps giving the error:
```
Error Building Component

    Error building Component Ollama Embeddings: Could not connect to Ollama API.
```

Ollama text-generation is working just fine.

### Reproduction

I just used the template 'Vector Store RAG' and changed the OpenAI components for the Ollama components. I pulled 'nomic-embed-text' with Ollama and put it in the embedding model name. 

### Expected behavior

To not give erros (?)

### Operating System

Windows 11 + install in a venv

### Langflow Version

1.1.0

### Python Version

3.10

### Screenshot

![image](https://github.com/user-attachments/assets/f66d8a7a-2fba-4984-b92e-dee54f68e243)

**Comment by Donixon** [comment]
The error given by the CLI. It's talking about 'temperature' not permitted, but there is no way to turn this off?

`           ValidationError: 1 validation error for OllamaEmbeddings
                             temperature
                               Extra inputs are not permitted [type=extra_forbidden, input_value=0.1, input_type=float]
                                 For further information visit https://errors.pydantic.dev/2.9/v/extra_forbidden

                             The above exception was the direct cause of the following exception:

                             ╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮ 
                             │ C:\ollama\.venv\lib\site-packages\langflow\graph\vertex\base.py:708 in _build_results            │ 
                             │                                                                                                  │ 
                             │   705 │   │   self, custom_component, custom_params, base_type: str, *,                          │ 
                             │       fallback_to_env_vars=False                                                                 │ 
                             │   706 │   ) -> None:                                                                             │ 
                             │   707 │   │   try:                                                                               │ 
                             │ ❱ 708 │   │   │   result = await initialize.loading.get_instance_results(                        │ 
                             │   709 │   │   │   │   custom_component=custom_component,                                         │ 
                             │   710 │   │   │   │   custom_params=custom_params,                                               │ 
                             │   711 │   │   │   │   vertex=self,                                                               │ 
                             │                                                                                                  │ 
                             │ C:\ollama\.venv\lib\site-packages\langflow\interface\initialize\loading.py:68 in                 │ 
                             │ get_instance_results                                                                             │ 
                             │                                                                                                  │ 
                             │    65 │   │   if base_type == "custom_components":                                               │ 
                             │    66 │   │   │   return await build_custom_component(params=custom_params,                      │ 
                             │       custom_component=custom_component)                                                         │ 
                             │    67 │   │   if base_type == "component":                                                       │ 
                             │ ❱  68 │   │   │   return await build_component(params=custom_params,                             │ 
                             │       custom_component=custom_component)                                                         │ 
                             │    69 │   │   msg = f"Base type {base_type} not found."                                          │ 
                             │    70 │   │   raise ValueError(msg)                                                              │ 
                             │    71                                                                                            │ 
                             │                                                                                                  │ 
                             │ C:\ollama\.venv\lib\site-packages\langflow\interface\initialize\loading.py:145 in                │ 
                             │ build_component                                                                                  │ 
                             │                                                                                                  │ 
                             │   142 ):                                                                                         │ 
                             │   143 │   # Now set the params as attributes of the custom_component                             │ 
                             │   144 │   custom_component.set_attributes(params)                                                │ 
                             │ ❱ 145 │   build_results, artifacts = await custom_component.build_results()                      │ 
                             │   146 │                                                                                          │ 
                             │   147 │   return custom_component, build_results, artifacts                                      │ 
                             │   148                                                                                            │ 
                             │                                                                                                  │ 
                             │ C:\ollama\.venv\lib\site-packages\langflow\custom\custom_component\component.py:837 in           │ 
                             │ build_results                                                                                    │ 
                             │                                                                                                  │ 
                             │    834 │   │   │   session_id = None                                                             │ 
                             │    835 │   │   try:                                                                              │ 
                             │    836 │   │   │   if self._tracing_service:                                                     │ 
                             │ ❱  837 │   │   │   │   return await self._build_with_tracing()                                   │ 
                             │    838 │   │   │   return await self._build_without_tracing()                                    │ 
                             │    839 │   │   except StreamingError as e:                                                       │ 
                             │    840 │   │   │   self.send_error(                                                              │ 
                             │                                                                                                  │ 
                             │ C:\ollama\.venv\lib\site-packages\langflow\custom\custom_component\component.py:819 in           │ 
                             │ _build_with_tracing                                                                              │ 
                             │                                                                                                  │ 
                             │    816 │   │   inputs = self.get_trace_as_inputs()                                               │ 
                             │    817 │   │   metadata = self.get_trace_as_metadata()                                           │ 
                             │    818 │   │   async with self._tracing_service.trace_context(self, self.trace_name, inputs,     │ 
                             │        metadata):                                                                                │ 
                             │ ❱  819 │   │   │   _results, _artifacts = await self._build_results()                            │ 
                             │    820 │   │   │   self._tracing_service.set_outputs(self.trace_name, _results)                  │ 
                             │    821 │   │                                                                                     │ 
                             │    822 │   │   return _results, _artifacts                                                       │ 
                             │                                                                                                  │ 
                             │ C:\ollama\.venv\lib\site-packages\langflow\custom\custom_component\component.py:885 in           │ 
                             │ _build_results                                                                                   │ 
                             │                                                                                                  │ 
                             │    882 │   │   │   │   │   │   if inspect.iscoroutinefunction(method):                           │ 
                             │    883 │   │   │   │   │   │   │   result = await method()                                       │ 
                             │    884 │   │   │   │   │   │   else:                                                             │ 
                             │ ❱  885 │   │   │   │   │   │   │   result = await asyncio.to_thread(method)                      │ 
                             │    886 │   │   │   │   │   │   if (                                                              │ 
                             │    887 │   │   │   │   │   │   │   self._vertex is not None                                      │ 
                             │    888 │   │   │   │   │   │   │   and isinstance(result, Message)                               │ 
                             │                                                                                                  │ 
                             │ C:\Users\Donixon\AppData\Local\Programs\Python\Python310\lib\asyncio\threads.py:25 in to_thread  │ 
                             │                                                                                                  │ 
                             │   22 │   loop = events.get_running_loop()                                                        │ 
                             │   23 │   ctx = contextvars.copy_context()                                                        │ 
                             │   24 │   func_call = functools.partial(ctx.run, func, *args, **kwargs)                           │ 
                             │ ❱ 25 │   return await loop.run_in_executor(None, func_call)                                      │ 
                             │   26                                                                                             │ 
                             │                                                                                                  │ 
                             │ C:\Users\Donixon\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py:58 in  │ 
                             │ run                                                                                              │ 
                             │                                                                                                  │ 
                             │    55 │   │   │   return                                                                         │ 
                             │    56 │   │                                                                                      │ 
                             │    57 │   │   try:                                                                               │ 
                             │ ❱  58 │   │   │   result = self.fn(*self.args, **self.kwargs)                                    │ 
                             │    59 │   │   except BaseException as exc:                                                       │ 
                             │    60 │   │   │   self.future.set_exception(exc)                                                 │ 
                             │    61 │   │   │   # Break a reference cycle with the exception 'exc'                             │ 
                             │ in build_embeddings:47                                                                           │ 
                             ╰──────────────────────────────────────────────────────────────────────────────────────────────────╯ 
                             ValueError: Could not connect to Ollama API.`

**Comment by KlebersonCollab** [comment]
Enter the code of the Ollama Embeddings component and comment out the temperature variable as the Ollama embeddings do not use this variable:

![image](https://github.com/user-attachments/assets/916d4787-bf18-4665-a9b2-17b232c99a23)

**Comment by Donixon** [comment]
> Enter the code of the Ollama Embeddings component and comment out the temperature variable as the Ollama embeddings do not use this variable:
> 
> ![image](https://private-user-images.githubusercontent.com/54902335/388952298-916d4787-bf18-4665-a9b2-17b232c99a23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyODMzNDgsIm5iZiI6MTczMjI4MzA0OCwicGF0aCI6Ii81NDkwMjMzNS8zODg5NTIyOTgtOTE2ZDQ3ODctYmYxOC00NjY1LWE5YjItMTdiMjMyYzk5YTIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDEzNDQwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyMzNkODQ2ODVhMDM0MjAzNjlkNGFmMmQyMDA4NjQ3Y2YyZDAwMzkwZTg2YjcwMmUxNDgzYmVmZDUxZjhkNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Wkeh3xP3fcVJqq2JZwYlFeuN_hd3R5nl_Jmr4dktHTQ)

not sure if you missed it, but >>> https://github.com/langflow-ai/langflow/issues/4633#issuecomment-2478269814

:^)

**Comment by gemini-mouse** [comment]
> Enter the code of the Ollama Embeddings component and comment out the temperature variable as the Ollama embeddings do not use this variable:輸入 Ollama 嵌入式元件的程式碼，並註解掉溫度變數，因為 Ollama 嵌入式不使用此變數。
> 
> ![image](https://private-user-images.githubusercontent.com/54902335/388952298-916d4787-bf18-4665-a9b2-17b232c99a23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzMzIwNzQsIm5iZiI6MTczMjMzMTc3NCwicGF0aCI6Ii81NDkwMjMzNS8zODg5NTIyOTgtOTE2ZDQ3ODctYmYxOC00NjY1LWE5YjItMTdiMjMyYzk5YTIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDAzMTYxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2ZWM3YWQzY2FkM2JkZmMyNTk2ZDZjOThlZDgxM2FiY2ZjYzI3ZDAwMTEzOWIzMDY3N2M0ZTZjODk5NGZiMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0zxoaNFALIFiPx2gfnm7Dgfiqb6XyVIXVuCJqpDrnxU)

awesome, the problem solved, thank you so much
