### ISSUE TITLE
Error in switching between to v1.1.0 from v1.0.19post2

### ISSUE THREAD

**Issue by pietro1996** [langflow-ai/langflow#4637]
### Bug Description

Hi all, switching from v1.0.19post2 to v1.1.0 I got the following error in docker, any bugs or am I doing something wrong?![image](https://github.com/user-attachments/assets/53a3b700-161e-4857-8b74-7d4cfdc36aa8)
I 

### Reproduction

I launch langflow inside a docker compose where I changed the version manually to v1.1.0 from v1.0.19post2

The previous version worked correctly

### Expected behavior

Launch the docker correctly

### Operating System

Ubuntu 

### Langflow Version

v1.1.0

### Python Version

None

**Comment by italojohnny** [comment]
This issue is related to #4593
