### ISSUE TITLE
Docker Compose Fails

### ISSUE THREAD

**Issue by JadTawil77** [langflow-ai/langflow#4647]
### Bug Description

AttributeError: module                             
docker_example-langflow-1  |                              'sqlalchemy.dialects' has no attribute             
docker_example-langflow-1  |                              'sqlite'

### Reproduction

cd ../docker_example/
docker compose up
 

### Expected behavior

I expect it to not throw errors

### Operating System

Ubuntu Linux 

### Langflow Version

latest

### Python Version

None

**Comment by JadTawil77** [comment]
@dosu Since we are running a docker container, the docker image should have all the necessary packages and their compatibilities, not my native machine.

**Comment by JadTawil77** [comment]
Indeed the problem does persist with the latest image.

**Comment by Vaviloff** [comment]
We also observe this error after updating from the previous Docker container with an existing database.
Previously Langflow was working nicely.

**Comment by desenvolvedor-guibson-lizardo** [comment]
e agora como podemos resolver isso? estou a horas aqui nisso

**Comment by desenvolvedor-guibson-lizardo** [comment]
@JadTawil77 encontrou alguma resposta?

**Comment by JadTawil77** [comment]
@desenvolvedor-guibson-lizardo Not yet.

We shouldn't have to use an old version of langchain to make the docker work. The docker image should be up to date with latest.
I will await a fix :)

**Comment by pasha-codefresh** [comment]
Build a Docker image from the main branch and push it to your own registry. This solved the problem for me.

Issue was fixed in this PR https://github.com/langflow-ai/langflow/pull/4599

**Comment by Mavlarn** [comment]
Waiting for a quick update in docker hub.

**Comment by alireza-dhp** [comment]
I am also waiting to run an instance!
