### ISSUE TITLE
Error building component FILE: bad offset for central directory

### ISSUE THREAD

**Issue by fanimali** [langflow-ai/langflow#4695]
### Bug Description

it does happen kind of randomly, when loading files using the File component.
I am loading txt files. 

It happened to me quite a few times repeatedly. 

Langflow on Astra (I thinit's version1.1)

### Reproduction

steps to reproduce:
load one file, build the component, all is good, 
then load another one, build, all is good
then load another one, build and it fails with that error, preventing the build 
then change the file, build and it loads correctly...

### Expected behavior

The File component should not show any error when loading a file, or show a meaningful error if needed.

This error seems to resolve on its own, but then it comes back. 
It's not blocking though.

### Operating System

Astra

### Langflow Version

1.1

### Python Version

None

### Screenshot

![image](https://github.com/user-attachments/assets/dd91dafc-6531-4c2e-9900-dedaacbc4869)

**Comment by erichare** [comment]
@fanimali Just to confirm, this was happening when uploading regular files (.txt, etc) not zip files, right?

Zip file support is new, and the references im seeing show that this error occurs when involving zip files... but that doesn't seem to be what you experienced. I'm going to see if i can reproduce it. Possibly it could be related to DS LF specifically, as the testing of the file component has primarily been done on the OSS version. But any more details you could provide would be much appreciated!
