### ISSUE TITLE
Ollama Embeddings is faulty in v1.1 :  Error building Component Ollama Embeddings: Could not connect to Ollama API.

### ISSUE THREAD

**Issue by rivalscope** [langflow-ai/langflow#4728]
### Bug Description

- It does not connect to API at all ( not working even hardcoded )

- Workaround : Use LMStudio Embeddings component and route to /v1 ( work just fine with ollama even load available models)

For refference please see the image attached.

<img width="716" alt="Screenshot 2024-11-19 at 23 57 56" src="https://github.com/user-attachments/assets/d7b13af2-631d-419e-860e-91b4c36dc7fb">

### Reproduction

Try
- Fill as usual the model name and base url. 
- Hardcode the model name and base url.

### Expected behavior

1 Connect to ollama server
2 Execute the embedding function 
3 Respond with the enbedding vectors

### Operating System

ubuntu 22.04?! (langflow docker image)

### Langflow Version

1.1

### Python Version

None

**Comment by greenmotion** [comment]
I am experiencing this as well and someone else posted a similar issue with a potential fix, by removing the temperature setting from the "code" function on the component.

**Comment by milljm** [comment]
This is still an issue. I too cannot use Ollama Embeddings. But I can use Ollama for the LLM, at the same address. The workaround described above also works for me (use LM Studio Embeddings component, and adjust the address to match e.g. `http://localhost:11434/v1`

**Comment by faisalusuf** [comment]
I am facing the same issue the problem with Flowise ollama embeddings is its making GET request to the API endpoint while it should have been a POST request.

**Comment by milljm** [comment]
My guess is that Ollama Server does not yet support OpenAI API calls to embedding (see very last entry about it here: https://ollama.com/blog/openai-compatibility)
