### ISSUE TITLE
Groq in the Agent component is not loading models 

### ISSUE THREAD

**Issue by SavvySupport** [langflow-ai/langflow#4729]
### Bug Description

I'm trying to use Groq within the Agent component, however even after I enter in the API Key, it won't show me any models to select. 

### Reproduction

1. Select the Agent component 
2. Select Groq as the model provider
3. Enter in Groq API key
4. Click on "refresh" under "Model" 
5. The message reads "No parameters are available for display." 

### Expected behavior

Expecting to see list of models to select from, just as we do with the Groq component. 

### Operating System

MacOS

### Langflow Version

1.1

### Python Version

3.10

### Screenshot

<img width="196" alt="Screenshot 2024-11-20 at 12 55 38 pm" src="https://github.com/user-attachments/assets/124e43ee-e55c-4577-b906-dbd008dda249">

**Comment by carlosrcoelho** [comment]
Hey @SavvySupport 

Groq is working fine on version 1.1.1. Please give a try. 

https://github.com/user-attachments/assets/0784ec17-8336-4162-b69f-9deb9fa58033
