### ISSUE TITLE
LangFlow suddenly crashed and can no longer be started

### ISSUE THREAD

**Issue by tzengshinfu** [langflow-ai/langflow#4730]
### Bug Description

Yesterday, I started LangFlow inside a container and created two Vector Store RAG workflows:
flow_1: Vectorized Markdown documents and wrote them into PGVector.
flow_2: Matched user queries with PGVector to retrieve answers.
Both workflows ran smoothly yesterday.

This morning, I discovered that LangFlow had suddenly crashed, and the log is as follows:
[langflow-crash.log](https://github.com/user-attachments/files/17824375/langflow-crash.log)(As seen at [11/20/24 09:39:20])

Even after deleting the vectorization records in PGVector, it still couldn't start successfully.
Ultimately, I had to delete all the tables storing the vectorized document data to get it to start properly.

### Reproduction

1. Start LangFlow and PGVector (container settings are as shown in the attachment: [docker-compose.yml.txt](https://github.com/user-attachments/files/17824361/docker-compose.yml.txt)).
2. Execute [flow_1](https://github.com/user-attachments/files/17824294/flow_1.json) to vectorize the file: [2024-11-19_07-29-59_20221117_edited.md](https://github.com/user-attachments/files/17824322/2024-11-19_07-29-59_20221117_edited.md)
 and write it into PGVector.
3. Execute [flow_2](https://github.com/user-attachments/files/17824301/flow_2.json) to ask a question; everything worked fine at this stage.
4. After a while, LangFlow crashed on its own and could not be restarted properly.
5. The memory usage of the host at the time was not significantly increasing but rather decreasing (as shown in the attachment: [Memory_usage](https://github.com/user-attachments/assets/7ca1f9cc-9b6a-471f-8d02-01ee44f15ada))

### Expected behavior

Continues to run normally.

### Operating System

Ubuntu 22.04.5

### Langflow Version

1.0.19 (docker)

### Python Version

None

### Screenshot

![image_20241120_103531](https://github.com/user-attachments/assets/71a5bd8a-ae18-4276-b121-4953144156ea)

### Flow File

[flow_1.json](https://github.com/user-attachments/files/17824294/flow_1.json)
[flow_2.json](https://github.com/user-attachments/files/17824301/flow_2.json)
[2024-11-19_07-29-59_20221117_edited.md](https://github.com/user-attachments/files/17824322/2024-11-19_07-29-59_20221117_edited.md)
[docker-compose.yml.txt](https://github.com/user-attachments/files/17824361/docker-compose.yml.txt)
[langflow-crash.log](https://github.com/user-attachments/files/17824375/langflow-crash.log)
[Memory_usage](https://github.com/user-attachments/assets/7ca1f9cc-9b6a-471f-8d02-01ee44f15ada)

**Comment by italojohnny** [comment]
Hello, my friend. How are you?
Could you let me know which version of Langflow you are using?

**Comment by tzengshinfu** [comment]
I have updated the image version of LangFlow to v1.1.1. It is currently working properly, so I will close this issue for now.
