### ISSUE TITLE
After upgrade to version 1.1.0, the old flows fail to build because components are out of date

### ISSUE THREAD

**Issue by fanimali** [langflow-ai/langflow#4735]
### Bug Description

The problem here is that quite a few components have been upgraded in the new version, but there isn't a way to simply upgrade the old components. 
The old flows will not build anymore and the user must delete and recreate manually those components that are failing the build, one by one.

Possible enhancement would be to handle the upgrades in a better way for a neater customer experience.

### Reproduction

upgrade LF to version 1.1
verify that old components are not building anymore and need to be upgraded to new version of the same components.

### Expected behavior

a version upgrade should be backward compatible or the user should be presented with a question as to automatically upgrade the components in the existing flows.

### Operating System

Ubuntu 22.04

### Langflow Version

1.1.0

### Python Version

None

**Comment by lucaseduoli** [comment]
Hello! Could you please provide us with the specific components which are causing this issue? If possible, could you send us your Flow by exporting it? Thanks!

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to help you.
