### ISSUE TITLE
RetrieverTool not workin

### ISSUE THREAD

**Issue by Owe1n** [langflow-ai/langflow#4740]
### Bug Description

When trying to use RetrieverTool to have an agent connected to a VectorStore Getting the following error : 
```python
RetrieverToolComponent' object has no attribute 'set_event_manager'

Traceback (most recent call last):
  File "/Users/d/miniconda3/envs/iagentflow-cookbook/lib/python3.10/site-packages/langflow/api/v1/chat.py", line 227, in _build_vertex
    vertex_build_result = await graph.build_vertex(
  File "/Users/d/miniconda3/envs/iagentflow-cookbook/lib/python3.10/site-packages/langflow/graph/graph/base.py", line 1419, in build_vertex
    await vertex.build(
  File "/Users/d/miniconda3/envs/iagentflow-cookbook/lib/python3.10/site-packages/langflow/graph/vertex/base.py", line 818, in build
    await step(user_id=user_id, event_manager=event_manager, **kwargs)
  File "/Users/d/miniconda3/envs/iagentflow-cookbook/lib/python3.10/site-packages/langflow/graph/vertex/base.py", line 493, in _build
    self.custom_component.set_event_manager(event_manager)
AttributeError: 'RetrieverToolComponent' object has no attribute 'set_event_manager'
```

### Reproduction

Connect a vectore store to a RetrieverTool and execute it.

### Expected behavior

Compile the tool

### Operating System

Mac OS

### Langflow Version

1.1

### Python Version

3.10

### Screenshot

![image](https://github.com/user-attachments/assets/0cac87cc-b4eb-48e9-9a72-ca7724c5a18b)

### Flow File

[Vector Store RAG (1).json](https://github.com/user-attachments/files/17837325/Vector.Store.RAG.1.json)

**Comment by edwinjosechittilappilly** [comment]
https://github.com/langflow-ai/langflow/issues/4640
Similar Issue!
We are working on it!

**Comment by dividor** [comment]
@edwinjosechittilappilly I notice this issue prevents using agents with tools in the online version. Might you know please when it will be released?

**Comment by edwinjosechittilappilly** [comment]
This issue is fixed and will be available in upcoming release.
We have a release scheduled for this week,mostly today.

**Comment by cpizetta** [comment]
looking forward to have the fix. thank you...I'm facing the same issue.

**Comment by cpizetta** [comment]
did someone try to fix it mannualy like @dosubot suggested? it worked?

**Comment by zeeiyerWork** [comment]
> did someone try to fix it mannualy like @dosubot suggested? it worked?
No you can't just add the method to your Retriever Component  -> it errors out when trying to save.
