### ISSUE TITLE
Error Run langflow 1.1 locally

### ISSUE THREAD

**Issue by chaerulilmi** [langflow-ai/langflow#4747]
### Bug Description

I have got some issue, when i'am running langflow in local server, i run "python -m install langflow==1.1" and i run 'langflow run' but, actually it does'nt going very well. I got some error like this

![Cuplikan layar 2024-11-21 112149](https://github.com/user-attachments/assets/6b6f240a-c479-44bf-b6a6-8693fd1f658b)

Any solutions? Thank you

### Reproduction

-

### Expected behavior

run perfectly when i run langflow version 1.1.0 locally

### Who can help?

@italojohnny 
@ogabrielluiz 
@nicoloboschi 

### Operating System

Windows 11

### Langflow Version

1.1.0

### Python Version

3.12

**Comment by shaxiaozz** [comment]
@chaerulilmi 
I encountered the same problem yesterday. This issue https://github.com/langflow-ai/langflow/issues/4698 should be the real cause and solution
![image](https://github.com/user-attachments/assets/7f253c4b-62b2-42b5-b034-ec5b8033a838)

**Comment by italojohnny** [comment]
PR  #4755 fixes this issue
