### ISSUE TITLE
Plugins not picked up

### ISSUE THREAD

**Issue by ar-or** [langflow-ai/langflow#4776]
### Bug Description

Plugins in `services/plugins` are ignored

### Reproduction

1. Create a file `my_plugin.py` with the content below (or in fact any content)
2. Put it into services/plugins/
3. Start the application
4. Observe the code in the plugin not being executed. Neither global code in the file, nor class instantiated

### Expected behavior

Plugin code executed

### Who can help?

@italojohnny 

### Operating System

ubuntu docker

### Langflow Version

1.1.0

### Python Version

3.12

### Flow File

```
from loguru import logger
from langflow.services.plugins.base import BasePlugin, CallbackPlugin

logger.info("plugin loaded")

class MyPlugin(BasePlugin):
    def initialize(self) -> None:
        logger.info('initialize')
        

    def teardown(self) -> None:
        logger.info('teardown')

    def get(self):
        logger.info('get')

    def get_callback(self, _id: str | None = None):
        logger.debug("Initializing callback")
        return None
```

**Comment by italojohnny** [comment]
Hello friend, how are you?

The plugin concept became obsolete as Langflow evolved, and we stopped using it.
To prevent others from mistakenly attempting to use the plugin service, I created this PR #4826 to remove all the code related to it.

**Comment by ar-or** [comment]
That's actually disappointing, because there is no other way to expand langflow's global functionality without building it from source code, and even that wouldn't guarantee forward compatibility.

**Comment by italojohnny** [comment]
Could you describe how you used this feature? Maybe I can help you find other ways to achieve your goals or even brainstorm new features for Langflow.

**Comment by ar-or** [comment]
For instance, I wanted to connect it to our own on-premise open telemetry collector,
the plugin would act as injection point for the instrumentation code. Otherwise there is no many places where one can inject their own code.

Just replacing "telemetry_base_url" doesn't seem to be worknig, due to api incompatibility.

**Comment by italojohnny** [comment]
Langflow offers a tracing service, which we've used to build tracings for Langsmith, Langwatch, and, more recently, Langfuse. You could create your own class following these definitions.

Do you think this would meet your needs?

**Comment by ar-or** [comment]
Thanks for the suggestion. Very likely yes.
What I don't know, is how to inject it into the application. The list of services to be loaded is pretty much hardcoded. There is no config or dynamically loaded plugins any more.
What I don't want, is to clone the entire project and maintain my own copy, constantly merging changes.
