### ISSUE TITLE
Chat session in Playground does not refresh.

### ISSUE THREAD

**Issue by greenmotion** [langflow-ai/langflow#4780]
### Bug Description

The chat session in the playground does not automatically refresh. I can submit a question to the chatbot and hit send, but the chat session will not show me the response, until I switch to another window and switch back and/or close playground and re-open it. In other words, it seems it only refreshes when the browser window gets refocused.  Tried this on Mozilla and Brave (chrome)

### Reproduction

1. In a chatbot workflow, open playground
2. type a question, hit send
3. one the send button stops showing "stop", no response is displayed in the chat.
4. Navigate away and go back to your browser window and/or leave playground and go back in, and now you can see the response.

### Expected behavior

Upon hitting send, a response should automatically be displayed in the chat session.

### Operating System

Ubuntu LTS 20.24

### Langflow Version

1.1.0

### Python Version

3.12

**Comment by anovazzi1** [comment]
hey @greenmotion, I've tried the main branch and couldn't reproduce the issue, how are you running langflow exactly? are you using docker or something similar?

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to help you.

**Comment by quic-zhanweiw** [comment]
I met the same issue with langflow 1.2.0, but langflow 1.1.1 doesn't have this issue.
