### ISSUE TITLE
Google Vertex AI gives error about SafetySetting

### ISSUE THREAD

**Issue by mieslep** [langflow-ai/langflow#4797]
### Bug Description

Changes in LangChain have broken the `langchain-google-vertexai` package, resulting in  error:

    "name": "PydanticUndefinedAnnotation",
    "message": "name 'SafetySetting' is not defined

This is related to https://github.com/langchain-ai/langchain-google/issues/610#issuecomment-2493831993  and https://github.com/langchain-ai/langchain-google/issues/613 , so presumably Langflow simply has a bad dependency.

### Reproduction

[project]
name = "test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.5",
    "python-dotenv>=1.0.1",
    "pypdf>=5.1.0",
    "langchain-core>=0.3.20",
    "langchain-google-vertexai>=2.0.7",
]

from langchain_google_vertexai import VertexAI
model = VertexAI(model_name="gemini-1.5-flash-001")

### Expected behavior

There should be no error. 

### Operating System

Windows

### Langflow Version

1.1.0

### Python Version

None

**Comment by edwinjosechittilappilly** [comment]
ref: https://github.com/langchain-ai/langchain-google/issues/610#issuecomment-2493831993

**Comment by edwinjosechittilappilly** [comment]
Thank you for your feedback. Testing is complete on main. The fix will be available in the upcoming release.

**Comment by sahilgupta2105** [comment]
I see the same error when trying to run [the example notebook](https://colab.research.google.com/github/GoogleCloudPlatform/generative-ai/blob/main/gemini/prompts/examples/chain_of_thought_react.ipynb) from GCP Gen-AI.

**Comment by NuniTelo** [comment]
@sahilgupta2105 did you manage to have a fix for this?
