### ISSUE TITLE
Ollama component error in langflow version 1.0.9

### ISSUE THREAD

**Issue by Tang2024-cloud** [langflow-ai/langflow#4806]
### Bug Description

Ollama unsupported message type: <'class=dict'> issue with langflow 1.0.9 version.

### Reproduction

error code:
---------------
Failed to multipart ingest runs: langsmith.utils.LangSmithAuthError: Authentication failed for https://api.smith.langchain.com/runs/multipar
t. HTTPError('401 Client Error: Unauthorized for url: https://api.smith.langchain.com/runs/multipart', '{"detail":"Invalid token"}')trace=fb
413d32-b390-4296-b570-56a4efc23650,id=fb413d32-b390-4296-b570-56a4efc23650
E:\Jey\Lang_Chat\.venv\lib\site-packages\langsmith\client.py:241: LangSmithMissingAPIKeyWarning: API key must be provided when using hosted
LangSmith API
  warnings.warn(
E:\Jey\Lang_Chat\.venv\lib\site-packages\langsmith\client.py:241: LangSmithMissingAPIKeyWarning: API key must be provided when using hosted
LangSmith API
  warnings.warn(
[11/25/24 06:08:13] ERROR    2024-11-25 06:08:13 - ERROR    - service - Error ending trace Ollama Embeddings                  service.py:132

### Expected behavior

Traceback (most recent call last) ───────────────────────────────╮
                             │ E:\Jey\Lang_Chat\.venv\lib\site-packages\langflow\graph\vertex\base.py:640 in                   │
                             │ _get_and_instantiate_class                                                                      │
                             │                                                                                                 │
                             │   637 │   │   if self.base_type is None:                                                        │
                             │   638 │   │   │   raise ValueError(f"Base type for vertex {self.display_name} not found")       │
                             │   639 │   │   try:                                                                              │
                             │ ❱ 640 │   │   │   result = await loading.instantiate_class(                                     │
                             │   641 │   │   │   │   user_id=user_id,                                                          │
                             │   642 │   │   │   │   fallback_to_env_vars=fallback_to_env_vars,                                │
                             │   643 │   │   │   │   vertex=self,                                                              │
                             │                                                                                                 │
                             │ E:\Jey\Lang_Chat\.venv\lib\site-packages\langflow\interface\initialize\loading.py:38 in         │
                             │ instantiate_class                                                                               │
                             │                                                                                                 │
                             │    35 │   if not base_type:                                                                     │
                             │    36 │   │   raise ValueError("No base type provided for vertex")                              │
                             │    37 │                                                                                         │
                             │ ❱  38 │   custom_component, build_results, artifacts = await build_component_and_get_results(   │
                             │    39 │   │   params=params,                                                                    │
                             │    40 │   │   vertex=vertex,                                                                    │
                             │    41 │   │   user_id=user_id,                                                                  │
                             │                                                                                                 │
                             │ E:\Jey\Lang_Chat\.venv\lib\site-packages\langflow\interface\initialize\loading.py:74 in         │
                             │ build_component_and_get_results                                                                 │
                             │                                                                                                 │
                             │    71 │   │   if base_type == "custom_components" and isinstance(custom_component,              │
                             │       CustomComponent):                                                                         │
                             │    72 │   │   │   return await build_custom_component(params=params_copy,                       │
                             │       custom_component=custom_component)                                                        │
                             │    73 │   │   elif base_type == "component" and isinstance(custom_component, Component):        │
                             │ ❱  74 │   │   │   return await build_component(params=params_copy,                              │
                             │       custom_component=custom_component)                                                        │
                             │    75 │   │   else:                                                                             │
                             │    76 │   │   │   raise ValueError(f"Base type {base_type} not found.")                         │
                             │    77                                                                                           │
                             │                                                                                                 │
                             │ E:\Jey\Lang_Chat\.venv\lib\site-packages\langflow\interface\initialize\loading.py:154 in        │
                             │ build_component                                                                                 │
                             │                                                                                                 │
                             │   151 ):                                                                                        │
                             │   152 │   # Now set the params as attributes of the custom_component                            │
                             │   153 │   custom_component.set_attributes(params)                                               │
                             │ ❱ 154 │   build_results, artifacts = await custom_component.build_results()                     │
                             │   155 │                                                                                         │
                             │   156 │   return custom_component, build_results, artifacts                                     │
                             │   157                                                                                           │
                             │                                                                                                 │
                             │ E:\Jey\Lang_Chat\.venv\lib\site-packages\langflow\custom\custom_component\component.py:136 in   │
                             │ build_results                                                                                   │
                             │                                                                                                 │
                             │   133 │                                                                                         │
                             │   134 │   async def build_results(self):                                                        │
                             │   135 │   │   if self.tracing_service:                                                          │
                             │ ❱ 136 │   │   │   return await self._build_with_tracing()                                       │
                             │   137 │   │   return await self._build_without_tracing()                                        │
                             │   138 │                                                                                         │
                             │   139 │   async def _build_results(self):                                                       │
                             │                                                                                                 │
                             │ E:\Jey\Lang_Chat\.venv\lib\site-packages\langflow\custom\custom_component\component.py:125 in   │
                             │ _build_with_tracing                                                                             │
                             │                                                                                                 │
                             │   122 │   │   inputs = self.get_trace_as_inputs()                                               │
                             │   123 │   │   metadata = self.get_trace_as_metadata()                                           │
                             │   124 │   │   async with self.tracing_service.trace_context(self.trace_name, self.trace_type,   │
                             │       inputs, metadata):                                                                        │
                             │ ❱ 125 │   │   │   _results, _artifacts = await self._build_results()                            │
                             │   126 │   │   │   trace_name = self.tracing_service.run_name                                    │
                             │   127 │   │   │   self.tracing_service.set_outputs(trace_name, _results)                        │
                             │   128                                                                                           │
                             │                                                                                                 │
                             │ E:\Jey\Lang_Chat\.venv\lib\site-packages\langflow\custom\custom_component\component.py:154 in   │
                             │ _build_results                                                                                  │
                             │                                                                                                 │
                             │   151 │   │   │   │   │   if output.cache and output.value != UNDEFINED:                        │
                             │   152 │   │   │   │   │   │   _results[output.name] = output.value                              │
                             │   153 │   │   │   │   │   else:                                                                 │
                             │ ❱ 154 │   │   │   │   │   │   result = method()                                                 │
                             │   155 │   │   │   │   │   │   # If the method is asynchronous, we need to await it              │
                             │   156 │   │   │   │   │   │   if inspect.iscoroutinefunction(method):                           │
                             │   157 │   │   │   │   │   │   │   result = await result                                         │
                             │                                                                                                 │
                             │ E:\Jey\Lang_Chat\.venv\lib\site-packages\langflow\base\models\model.py:43 in text_response      │
                             │                                                                                                 │
                             │    40 │   │   stream = self.stream                                                              │
                             │    41 │   │   system_message = self.system_message                                              │
                             │    42 │   │   output = self.build_model()                                                       │
                             │ ❱  43 │   │   result = self.get_chat_result(output, stream, input_value, system_message)        │
                             │    44 │   │   self.status = result                                                              │
                             │    45 │   │   return result                                                                     │
                             │    46                                                                                           │
                             │                                                                                                 │
                             │ E:\Jey\Lang_Chat\.venv\lib\site-packages\langflow\base\models\model.py:139 in get_chat_result   │
                             │                                                                                                 │
                             │   136 │   │   │   │   with warnings.catch_warnings():                                           │
                             │   137 │   │   │   │   │   warnings.simplefilter("ignore")                                       │
                             │   138 │   │   │   │   │   if "prompt" in input_value:                                           │
                             │ ❱ 139 │   │   │   │   │   │   prompt = input_value.load_lc_prompt()                             │
                             │   140 │   │   │   │   │   │   runnable = prompt | runnable                                      │
                             │   141 │   │   │   │   │   else:                                                                 │
                             │   142 │   │   │   │   │   │   messages.append(input_value.to_lc_message())                      │
                             │                                                                                                 │
                             │ E:\Jey\Lang_Chat\.venv\lib\site-packages\langflow\schema\message.py:164 in load_lc_prompt       │
                             │                                                                                                 │
                             │   161 │   def load_lc_prompt(self):                                                             │
                             │   162 │   │   if "prompt" not in self:                                                          │
                             │   163 │   │   │   raise ValueError("Prompt is required.")                                       │
                             │ ❱ 164 │   │   loaded_prompt = load(self.prompt)                                                 │
                             │   165 │   │   # Rebuild HumanMessages if they are instance of BaseMessage                       │
                             │   166 │   │   if isinstance(loaded_prompt, ChatPromptTemplate):                                 │
                             │   167 │   │   │   messages = []                                                                 │
                             │                                                                                                 │
                             │ E:\Jey\Lang_Chat\.venv\lib\site-packages\langchain_core\_api\beta_decorator.py:110 in           │
                             │ warning_emitting_wrapper                                                                        │
                             │                                                                                                 │
                             │   107 │   │   │   if not warned and not is_caller_internal():                                   │
                             │   108 │   │   │   │   warned = True                                                             │
                             │   109 │   │   │   │   emit_warning()                                                            │
                             │ ❱ 110 │   │   │   return wrapped(*args, **kwargs)                                               │
                             │   111 │   │                                                                                     │
                             │   112 │   │   async def awarning_emitting_wrapper(*args: Any, **kwargs: Any) -> Any:            │
                             │   113 │   │   │   """Same as warning_emitting_wrapper, but for async functions."""              │
                             │                                                                                                 │
                             │ E:\Jey\Lang_Chat\.venv\lib\site-packages\langchain_core\load\load.py:230 in load                │
                             │                                                                                                 │
                             │   227 │   │   │   return [_load(o) for o in obj]                                                │
                             │   228 │   │   return obj                                                                        │
                             │   229 │                                                                                         │
                             │ ❱ 230 │   return _load(obj)                                                                     │
                             │   231                                                                                           │
                             │                                                                                                 │
                             │ E:\Jey\Lang_Chat\.venv\lib\site-packages\langchain_core\load\load.py:225 in _load               │
                             │                                                                                                 │
                             │   222 │   │   if isinstance(obj, dict):                                                         │
                             │   223 │   │   │   # Need to revive leaf nodes before reviving this node                         │
                             │   224 │   │   │   loaded_obj = {k: _load(v) for k, v in obj.items()}                            │
                             │ ❱ 225 │   │   │   return reviver(loaded_obj)                                                    │
                             │   226 │   │   if isinstance(obj, list):                                                         │
                             │   227 │   │   │   return [_load(o) for o in obj]                                                │
                             │   228 │   │   return obj                                                                        │
                             │                                                                                                 │
                             │ E:\Jey\Lang_Chat\.venv\lib\site-packages\langchain_core\load\load.py:148 in __call__            │
                             │                                                                                                 │
                             │   145 │   │   │   # We don't need to recurse on kwargs                                          │
                             │   146 │   │   │   # as json.loads will do that for us.                                          │
                             │   147 │   │   │   kwargs = value.get("kwargs", dict())                                          │
                             │ ❱ 148 │   │   │   return cls(**kwargs)                                                          │
                             │   149 │   │                                                                                     │
                             │   150 │   │   return value                                                                      │
                             │   151                                                                                           │
                             │                                                                                                 │
                             │ E:\Jey\Lang_Chat\.venv\lib\site-packages\langchain_core\prompts\chat.py:984 in __init__         │
                             │                                                                                                 │
                             │    981 │   │   │   │   ])                                                                       │
                             │    982 │   │                                                                                    │
                             │    983 │   │   """                                                                              │
                             │ ❱  984 │   │   _messages = [                                                                    │
                             │    985 │   │   │   _convert_to_message(message, template_format) for message in messages        │
                             │    986 │   │   ]                                                                                │
                             │    987                                                                                          │
                             │                                                                                                 │
                             │ E:\Jey\Lang_Chat\.venv\lib\site-packages\langchain_core\prompts\chat.py:985 in <listcomp>       │
                             │                                                                                                 │
                             │    982 │   │                                                                                    │
                             │    983 │   │   """                                                                              │
                             │    984 │   │   _messages = [                                                                    │
                             │ ❱  985 │   │   │   _convert_to_message(message, template_format) for message in messages        │
                             │    986 │   │   ]                                                                                │
                             │    987 │   │                                                                                    │
                             │    988 │   │   # Automatically infer input variables from messages                              │
                             │                                                                                                 │
                             │ E:\Jey\Lang_Chat\.venv\lib\site-packages\langchain_core\prompts\chat.py:1457 in                 │
                             │ _convert_to_message                                                                             │
                             │                                                                                                 │
                             │   1454 │   │   │   │   )                                                                        │
                             │   1455 │   │   │   )                                                                            │
                             │   1456 │   else:                                                                                │
                             │ ❱ 1457 │   │   raise NotImplementedError(f"Unsupported message type: {type(message)}")          │
                             │   1458 │                                                                                        │
                             │   1459 │   return _message                                                                      │
                             │   1460                                                                                          │
                             

Can anyone please help me on this. Thanks

### Operating System

Windows

### Langflow Version

Langflow version 1.0.9

### Python Version

3.10

### Screenshot

![Ollama_Issue](https://github.com/user-attachments/assets/3fb33aea-20af-45d5-9e0d-d697e3ff80b4)

**Comment by Tang2024-cloud** [comment]
The access token issue is solved, I generated new.
But that ollama unsupported message type issue only i need to solve. Give me the solution for this.

**Comment by kiracyc** [comment]
I also have the same problem. Once I add Ollama LLms component in new project, it already cannot update the models.

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to help you.

Please test it on new version 1.1.1.
