### ISSUE TITLE
After the latest update, the store stopped working (1.1.1)

### ISSUE THREAD

**Issue by scofano** [langflow-ai/langflow#4832]
### Bug Description

After update I get an error when trying to get to the store.

### Reproduction

![image](https://github.com/user-attachments/assets/39b9305d-bf83-454c-8686-8dacc49dd185)

### Expected behavior

It should work

### Operating System

Windows 11

### Langflow Version

1.1.1

### Python Version

3.10

### Screenshot

![image](https://github.com/user-attachments/assets/c8990a6b-8c64-4559-8b2c-fa2887433df7)

**Comment by carlosrcoelho** [comment]
Hey @scofano 

I just tried and it is working as expected.

https://github.com/user-attachments/assets/814e567d-287f-4438-9406-a9882d1457d3

Are you still having problem?

**Comment by scofano** [comment]
@carlosrcoelho I'm sorry I didn't close this one. I guess 500 (Internal Server Error) meant that THAT TIME, it wasn't working but not it was. Thanks again
