### ISSUE TITLE
Text Input Missing in Playground

### ISSUE THREAD

**Issue by cpolanish** [langflow-ai/langflow#4839]
### Bug Description

Since the 1.1.0 update the Text Input does not seem to show an input field in the playground as it used to in the past.

Just a real basic example:
![image](https://github.com/user-attachments/assets/4a553925-54c1-4186-8a60-caface00a557)

![image](https://github.com/user-attachments/assets/b11ef68e-2256-4a2d-a1ed-45e97d972975)

I checked in the newly released 1.1.1 and am seeing the same behavior.

### Reproduction

1. Create a workflow with a text input
2. Run playground
3. No text input available

### Expected behavior

Text Input should be available in playground

### Operating System

Windows 11

### Langflow Version

1.1.1

### Python Version

3.12

**Comment by SavvySupport** [comment]
Apparently this is fixed in the new release 1.1.1.

**Comment by cpolanish** [comment]
I actually installed 1.1.1 yesterday before posting this and I'm seeing the same thing, the input box is missing.

**Comment by anovazzi1** [comment]
hey @cpolanish how are you? Because of the new playground we have disabled the text input interaction on it for now, but we plan to add it back in the future
