### ISSUE TITLE
[Ollama Component Error] "model "llama3.1" not found" error in langflow 1.1.0 

### ISSUE THREAD

**Issue by reachsriharsha** [langflow-ai/langflow#4861]
### Bug Description

Hi Langflow team, 
         I am getting below error when I use the Ollama Component, and its pretty consistent. 

![image](https://github.com/user-attachments/assets/6452a293-8d2d-426d-a150-f906c86d2b2f)

Please find the blew details and the steps to reproduce:

 Version used: Langflow version 1.1.0
Steps:
1. Open "Memory Chatbot" (or any other application which has LLM )
2. Replace existing OpenAI LLM with "Ollama"
3. Provide the "Base URL"
4. **_DO NOT Provide_** the  "Model Name"
5.  Then click playground. 
We get above error. 
Please note this is expected, when we execute without choosing any model, may be the default model is set to llama3.1

6. But later when we choose the existing model and set the "Model Name". Example llama3.2:1b
7. Then click on the Playground, we get same error again. 

When we set new value and try playground, it should take latest model, instead value of llama3.1 is not replaced with newly entered value in "Model Name"

   

### Reproduction

Steps:
1. Open "Memory Chatbot" (or any other application which has LLM )
2. Replace existing OpenAI LLM with "Ollama"
3. Provide the "Base URL"
4. **_DO NOT Provide_** the  "Model Name"
5.  Then click playground. 
We get above error. 
Please note this is expected, when we execute without choosing any model, may be the default model is set to llama3.1

6. But later when we choose the existing model and set the "Model Name". Example llama3.2:1b
7. Then click on the Playground, we get same error again. 

When we set new value and try playground, it should take latest model, instead value of llama3.1 is not replaced with newly entered value in "Model Name"

Even after replacing existing ollama component and set the "Model Name" with new one gives same error.

### Expected behavior

When we set new value and try playground, it should take latest model, instead value of llama3.1 is not replaced with newly entered value in "Model Name"

### Operating System

Ubuntu 22.04.4 LTS

### Langflow Version

1.1.0

### Python Version

None

### Screenshot

![image](https://github.com/user-attachments/assets/f83c3558-b74f-4256-9365-4557df227cce)

**Comment by carlosrcoelho** [comment]
@reachsriharsha 

Make sure you're running Ollama on your local machine. Once it's running on your local machine, click the refresh button located on the Model Name.

**Comment by reachsriharsha** [comment]
On further digging just saw this code , its self explanatory as the tool by default provides the "llama3.1", but fails to update this value when we choose. May be that is the reason for this bug.
```python
        DropdownInput(
            name="model_name",
            display_name="Model Name",
            value="llama3.1",
            info="Refer to https://ollama.com/library for more models.",
            refresh_button=True,
        ),

```

**Comment by carlosrcoelho** [comment]
@reachsriharsha 

I'm running Langflow locally on the latest released version, v1.1.1. I tried to reproduce your issue below, but without success.

https://github.com/user-attachments/assets/28165649-417f-49f2-8eb0-32bbb5b3b901

**Comment by reachsriharsha** [comment]
Hi Carlos,
  Thanks that is much faster communication.  I have recorded the issue. You can see the error. 

One thing which started working is step #6 and #7(mentioned in Reproduction) error is not seen now. 

https://github.com/user-attachments/assets/40e51568-d239-45f0-a77f-754dda08f9a9

Here is what I suggest. The error message given by tool is still useful. Suggest below things. 

1. Make choosing "Model Name" as mandatory. Which is no brainer but needed steps. 
2. Change error message, you have not chosen model. 
With those fixes please go ahead and close this issue. Or let me know when available, happy to test for you. I am available in discord(harsha8976/Sri Harsha) as well for quicker responses. 
Appreciate your time and co ordination.

**Comment by carlosrcoelho** [comment]
@reachsriharsha 
You need to click the refresh button on the Model Name and then click on the model you want to use.

https://github.com/user-attachments/assets/35fe7875-0a79-465b-900b-2d066ffa52ef

**Comment by reachsriharsha** [comment]
ok thanks
