### ISSUE TITLE
Installation Freezes for Langflow 1.1.1

### ISSUE THREAD

**Issue by romerey-savvysme** [langflow-ai/langflow#4866]
### Bug Description

Attempting to install the latest version of Langflow (1.1.1) takes an unusually long time and eventually freezes during the installation process. The installation does not proceed even after waiting for an extended period, forcing me to cancel the process.

### Reproduction

Steps to Reproduce

Create a new directory:
mkdir langflow1.1.1 && cd langflow1.1.1

Create a new Python virtual environment:
python -m venv ./venv1.1.1

Activate the virtual environment:
source venv1.1.1/bin/activate

Attempt to install Langflow:
python -m pip install langflow

Observe that the installation process takes an excessively long time and eventually freezes.

### Expected behavior

The installation of Langflow (version 1.1.1) should complete successfully within a reasonable amount of time when using the provided installation instructions. Specifically:

1. After running python -m pip install langflow, the package and its dependencies should be downloaded, installed, and set up without any interruptions or delays.
2. The process should not freeze or require manual intervention.
3. Once completed, the package should be ready for use, and running langflow or other commands should work as expected.

### Operating System

Ubuntu 22.04.4 LTS

### Langflow Version

1.1.1

### Python Version

3.10

### Screenshot

![Screenshot 2024-11-26 at 9 59 15 PM](https://github.com/user-attachments/assets/46ccd874-b39d-45eb-a72c-22e21a3ef183)

**Comment by ogabrielluiz** [comment]
Hey @romerey-savvysme 

Could you try installing it with `uv` (https://docs.astral.sh/uv/getting-started/installation/)

**Comment by mzakhama** [comment]
Hi, 
I got the same issue as romerey-savvysme. the installation process get stuck at the step below and end up generating an error. 
Flashed the cach and got the same result.
-------------------------
Collecting groq<1,>=0.4.1 (from langchain-groq<1.0.0,>=0.1.9->langflow==1.1.1)
  Downloading groq-0.11.0-py3-none-any.whl.metadata (13 kB)
  Downloading groq-0.10.0-py3-none-any.whl.metadata (13 kB)
  Downloading groq-0.9.0-py3-none-any.whl.metadata (13 kB)
  Downloading groq-0.8.0-py3-none-any.whl.metadata (13 kB)
  Downloading groq-0.7.0-py3-none-any.whl.metadata (13 kB)
  Downloading groq-0.6.0-py3-none-any.whl.metadata (13 kB)
  Downloading groq-0.5.0-py3-none-any.whl.metadata (12 kB)
  Downloading groq-0.4.2-py3-none-any.whl.metadata (12 kB)
  Downloading groq-0.4.1-py3-none-any.whl.metadata (12 kB)
Collecting gotrue<3.0,>=1.3 (from supabase~=2.6.0->langflow==1.1.1)
  Downloading gotrue-2.10.0-py3-none-any.whl.metadata (6.0 kB)
..
ERROR: Exception:
Traceback (most recent call last):
  File ".pyenv/versions/3.10.15/envs/LF1.1/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 105, in _run_wrapper
    status = _inner_run()
  File ".pyenv/versions/3.10.15/envs/LF1.1/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 96, in _inner_run
    return self.run(options, args)
  File ".pyenv/versions/3.10.15/envs/LF1.1/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 67, in wrapper
    return func(self, options, args)
  File ".pyenv/versions/3.10.15/envs/LF1.1/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 379, in run
    requirement_set = resolver.resolve(
  File ".pyenv/versions/3.10.15/envs/LF1.1/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
  File ".pyenv/versions/3.10.15/envs/LF1.1/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File ".pyenv/versions/3.10.15/envs/LF1.1/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 457, in resolve
    raise ResolutionTooDeep(max_rounds)
pip._vendor.resolvelib.resolvers.ResolutionTooDeep: 200000

**Comment by SavvySupport** [comment]
> Hey @romerey-savvysme
> 
> Could you try installing it with `uv` (https://docs.astral.sh/uv/getting-started/installation/)

This worked, thanks!

**Comment by romerey-savvysme** [comment]
> Hey @romerey-savvysme
> 
> Could you try installing it with `uv` (https://docs.astral.sh/uv/getting-started/installation/)

This worked fine. Thanks!

**Comment by coderlania** [comment]
> ## Hi,
> I got the same issue as romerey-savvysme. the installation process get stuck at the step below and end up generating an error.
> Flashed the cach and got the same result.
> Collecting groq<1,>=0.4.1 (from langchain-groq<1.0.0,>=0.1.9->langflow==1.1.1) Downloading groq-0.11.0-py3-none-any.whl.metadata (13 kB) Downloading groq-0.10.0-py3-none-any.whl.metadata (13 kB) Downloading groq-0.9.0-py3-none-any.whl.metadata (13 kB) Downloading groq-0.8.0-py3-none-any.whl.metadata (13 kB) Downloading groq-0.7.0-py3-none-any.whl.metadata (13 kB) Downloading groq-0.6.0-py3-none-any.whl.metadata (13 kB) Downloading groq-0.5.0-py3-none-any.whl.metadata (12 kB) Downloading groq-0.4.2-py3-none-any.whl.metadata (12 kB) Downloading groq-0.4.1-py3-none-any.whl.metadata (12 kB) Collecting gotrue<3.0,>=1.3 (from supabase~=2.6.0->langflow==1.1.1) Downloading gotrue-2.10.0-py3-none-any.whl.metadata (6.0 kB) .. ERROR: Exception: Traceback (most recent call last): File ".pyenv/versions/3.10.15/envs/LF1.1/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 105, in _run_wrapper status = _inner_run() File ".pyenv/versions/3.10.15/envs/LF1.1/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 96, in _inner_run return self.run(options, args) File ".pyenv/versions/3.10.15/envs/LF1.1/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 67, in wrapper return func(self, options, args) File ".pyenv/versions/3.10.15/envs/LF1.1/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 379, in run requirement_set = resolver.resolve( File ".pyenv/versions/3.10.15/envs/LF1.1/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve result = self._result = resolver.resolve( File ".pyenv/versions/3.10.15/envs/LF1.1/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve state = resolution.resolve(requirements, max_rounds=max_rounds) File ".pyenv/versions/3.10.15/envs/LF1.1/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 457, in resolve raise ResolutionTooDeep(max_rounds) pip._vendor.resolvelib.resolvers.ResolutionTooDeep: 200000

Hey mzakhama, I have the same error with you: `ResolutionTooDeep `, have you ever solved this problem?
I'm using python3.12 inside a docker container, langflow version is 1.1.0

**Comment by Lionnn107** [comment]
Same problem on Windows 11

**Comment by zcasanova** [comment]
> Hey @romerey-savvysme
> 
> Could you try installing it with `uv` (https://docs.astral.sh/uv/getting-started/installation/)

I had the same issue, your suggestion worked, but for those who, like me, are unfamiliar with uv, here's what you do:
```
pip install uv
uv pip install --upgrade langflow
```

**Comment by severfire** [comment]
just side note:
if anyone will have problems with db errors...
its worth to remove from ~/.venv/lib/python3.x/site-packages/langflow files:
langfloe.db, langflow.db-shm, langflow.db-wal from 

and rerun uv run langflow  migration --fix

a.
