### ISSUE TITLE
CrewAI Ollama Model Not Found

### ISSUE THREAD

**Issue by projetosfsi** [langflow-ai/langflow#4879]
### Bug Description

When we select ollama to create an agent crew we get an error indicating that the llm model is not selected.

I tested it with the agent lanchain and it works perfectly

I tested only the llm component of ollama in a simple chat and it works perfectly.

The problem seems to be related to the CrewAI component, specifically in the convert_llm function that is used to process the LLM model passed as input. This error occurs because the CrewAI component expects the LLM model (ChatOllama instance) to have a model_name attribute, but this attribute does not exist in the ChatOllama class.

### Reproduction

- Install Langflow 1.1.1 in Docker or via ENV in python

- Use CrewAI Component with Ollama LLM

As Said Before, This Workflow Works on Previous Versions.

**Langflow Docker v 1.0.19.post2**

![image](https://github.com/user-attachments/assets/d9a48e8f-4810-4fb4-9621-3f43db8cd8fb)

![image](https://github.com/user-attachments/assets/6dab615e-9aed-4fe7-934b-5400c27aa7e6)

**Langflow Docker v 1.1.1**

![image](https://github.com/user-attachments/assets/8d2ab2cd-76e1-47e4-bf41-f03816d7bf33)

![image](https://github.com/user-attachments/assets/5baa0c3b-9563-4857-8a27-ecf8eeccf8b2)

### Expected behavior

CrewAI Agent Response

### Who can help?

@italojohnny

### Operating System

Ubuntu Linux 24.04

### Langflow Version

1.1.1

### Python Version

3.12

### Flow File

[Ollama CrewAI.json](https://github.com/user-attachments/files/17925102/Ollama.CrewAI.json)

**Comment by erichare** [comment]
@projetosfsi a PR is up to address this. This is an unfortunate consequence of the fact that the latest CrewAI updates have their own LLM object and you correctly diagnosed the problem - we were assuming a `model_name` parameter in the Langchain object.

We'll have a fix to handle this and other cases, but longer term we'll probably want something more general to fit with the Langflow framework (it's fantastic to be able to take our model components and chain them to CrewAI, but then we do have to be able to map the parameters to what CrewAI expects.... if you have any thoughts on how to handle that more generally, totally open to it!)

But for now, keep an eye on: https://github.com/langflow-ai/langflow/pull/4899 which will have this fix. Just trying to work around some CI issues.

**Comment by carlosrcoelho** [comment]
Adding another PR https://github.com/langflow-ai/langflow/pull/4936

**Comment by shailquick** [comment]
Hey - I'm trying this same exact flow with CrewAI Agents & Ollama and getting this same error. I see that a fix was merged on this already and i'm running the latest version (1.1.1.1). How do I fix this?

**Comment by sermtech** [comment]
Same Here. Issue is not fixed for me. NOt able to use Ollama for agent workflow.

**Comment by projetosfsi** [comment]
> Same Here. Issue is not fixed for me. NOt able to use Ollama for agent workflow.

If you are in a development environment, you can use the docker image

https://hub.docker.com/r/langflowai/langflow-nightly

It already has the fix applied, but it is not recommended for production, as it is updated daily with changes from the repository

**Comment by Dosdrvanya** [comment]
I'm running the web-ui operator, which uses Langchain and I ran into the same problem when trying to run it with Ollama.  Got the same error message - so to fix it I went into the web-ui files and under web-ui/src/agent/custom_agent.py, I changed line 92 from "model_name" to simply "model" it it worked.

92        "if self.llm.model in ["deepseek-reasoner"]:"

Don't know why it worked, but it did.
