### ISSUE TITLE
[Question]How to make a prompt component have [input: memory]?

### ISSUE THREAD

**Issue by tzengshinfu** [langflow-ai/langflow#4885]
### Bug Description

The prompt component of [Template: Memory Chatbot] has [input: memory], but the prompt component created by dragging does not.

### Reproduction

1. Create a new flow from the [Template: Memory Chatbot].
2. Drag the prompt component into the flow.
3. Observe that the existing prompt component in the flow has [input: memory], but the prompt component created by dragging does not.

### Expected behavior

Find a way to configure the input for the prompt component created by dragging.

### Operating System

Ubuntu Linux 20.04

### Langflow Version

1.1.1

### Python Version

None

### Screenshot

The prompt component of [Template: Memory Chatbot]
![image_20241127_131721-2](https://github.com/user-attachments/assets/82a1e524-fae1-484b-a32e-cb0866aa91e2)

The prompt component created by dragging
![image_20241127_131721](https://github.com/user-attachments/assets/a33924d2-fb2d-40c1-9469-d30cd6b064f0)

**Comment by carlosrcoelho** [comment]
@tzengshinfu 
Create a Prompt Variables like this:
<img width="957" alt="image" src="https://github.com/user-attachments/assets/fcf123e0-400c-4e1c-ac6b-4a08228949ed">

After that you can connect the components like this:
<img width="1022" alt="image" src="https://github.com/user-attachments/assets/15281b7b-4770-4078-8805-b912fe0af7cb">

**Comment by tzengshinfu** [comment]
@carlosrcoelho
Thank you for your reply.
The prompt component has been set up successfully.
