### ISSUE TITLE
langflow API Request, Body not able to pass array.

### ISSUE THREAD

**Issue by irshadmb** [langflow-ai/langflow#4886]
### Bug Description

langflow API Request, Body not able to pass array.

### Reproduction

1. Not able to pass array, example ["Ball", "Bat"]

### Expected behavior

Need to pass JSON key, value as well as array.

### Operating System

Docker

### Langflow Version

1.1

### Python Version

None

**Comment by anovazzi1** [comment]
hey @irshadmb thanks for the feedback, can you please explain exactly what are you trying to do?

**Comment by anovazzi1** [comment]
which endpoint are you using?

**Comment by irshadmb** [comment]
I have my own api endpoint which will accept json array in body and return some json which I want to use in Langflow to push to a vector db.

**Comment by irshadmb** [comment]
![image](https://github.com/user-attachments/assets/debcc67d-7885-4da3-998c-0b7f43e825d9)
Sample postman

**Comment by anovazzi1** [comment]
@irshadmb now I understood, that's really a bug, we will fix it, thanks for the feedback

**Comment by anovazzi1** [comment]
fixed in #5122

**Comment by irshadmb** [comment]
Thanks @anovazzi1
