### ISSUE TITLE
Could not connect to Ollama API

### ISSUE THREAD

**Issue by samgit17** [langflow-ai/langflow#4895]
### Bug Description

After updating to Langflow 1.1.1 Ollama embeddings component is erroring out while building the component with : Error building Component Ollama Embeddings: Could not connect to Ollama API. This worked with earlier

![image](https://github.com/user-attachments/assets/c9196276-58bc-44f1-8096-cdb45389c845)

### Reproduction

Press run button on Ollama Embeddings Component

### Expected behavior

Component build successful

### Operating System

Windows

### Langflow Version

1.1.1

### Python Version

None

### Screenshot

![image](https://github.com/user-attachments/assets/dd3f67c8-102f-4637-976f-89942c2a4526)

**Comment by carlosrcoelho** [comment]
Hey @samgit17 

I just tried to reproduce your case and it worked as expected.

https://github.com/user-attachments/assets/db45ca52-0f7f-4072-9c16-0a860e85f85f

Make sure you have the embedding installed.
https://ollama.com/library/mxbai-embed-large

**Comment by samgit17** [comment]
I am having the issue still. Verified that the embed model is returning a response with curl cmd : curl http://localhost:11434/api/embed -d "{\"model\": \"nomic-embed-text:latest\", \"input\": \"Why is the sky blue?\"}". That means the model and the api on ollama is working. But the Ollama Embedding Component  build fails repeatedly with Could not  connect to Ollama API

**Comment by samgit17** [comment]
Will try an update on langflow

**Comment by samgit17** [comment]
update too didnt work.

**Comment by samgit17** [comment]
> Hey @samgit17! I'm here to help you with any bugs, questions, or contributions. Let's squash this bug together!
> 
> I found a similar issue that was reported and resolved. The problem with the Ollama Embeddings component not connecting to the Ollama API after updating to Langflow 1.1.1 is likely due to the `base_url` being set to "http://localhost:11434". If the Ollama API is not running on this URL or port, the connection will fail. You should ensure that the Ollama API is running and accessible at the specified `base_url`. If the API has moved to a different URL or port, update the `base_url` accordingly in the component's configuration [[1]](https://github.com/langflow-ai/langflow/blob/main/src/backend/base/langflow/components/embeddings/ollama.py).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

@dosu - Yes Ollama server is running at the port 11434 on localhost, I was able to get a response using curl.

**Comment by carlosrcoelho** [comment]
Which vector store are you using?

**Comment by KevinMichaelSchindler** [comment]
@samgit17 I had the same error. The issue for me was that there was a "temperature" argument which you need to delete:
 
 src\backend\base\langflow\components\embeddings\ollama.py
![image](https://github.com/user-attachments/assets/6e1f6320-a84d-4d3a-b7a7-1837c332e8dc)

**Comment by samgit17** [comment]
> @samgit17 I had the same error. The issue for me was that there was a "temperature" argument which you need to delete:
> 
> src\backend\base\langflow\components\embeddings\ollama.py ![image](https://private-user-images.githubusercontent.com/43708715/391133696-6e1f6320-a84d-4d3a-b7a7-1837c332e8dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5MDY2MjcsIm5iZiI6MTczMjkwNjMyNywicGF0aCI6Ii80MzcwODcxNS8zOTExMzM2OTYtNmUxZjYzMjAtYTg0ZC00ZDNhLWI3YTctMTgzN2MzMzJlOGRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDE4NTIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5Yjk5NjEyZmJhMTc0MjQ4YTc3YzRkODBiZDlmN2UwNjY3MzBkNDNhNjE4OWI1OTY5MzIxMTNmYmVkOTdlOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.f4NkSugY2sX2jVHtTARgluAWERlfPjgzusixm28McL8)

@KevinMichaelSchindler - You are absolutely right, deleted the temperature argument and presto, that worked like a charm. Can this be fixed in a future release, I banged my head on this issue for the last few days since updating to 1.1.1.

**Comment by KevinMichaelSchindler** [comment]
Ahh, ye no worries that happens. Just one tip, when you run langflow
locally, copy paste the stack trace into chatGPT/Claude and ask what the
issue is. The stacktrace is very long and the "temperature" stuff was
mentioned way at the beginning of the trace and was overshadowed but the
other exceptions. But an LLM can scan much better and can find it :)
