### ISSUE TITLE
Error building Component Message History

### ISSUE THREAD

**Issue by tzengshinfu** [langflow-ai/langflow#4911]
### Bug Description

There is an existing RAG workflow, with the component arrangement roughly as follows:
[Chat Input]─►[Ollama Embedding]─►[PGVector]─►[Parse Data]─►[Prompt]─►[Ollama]─►[Chat Output]

Now, I want to add the ability to remember the previous conversation.
So, in
[Chat Input]─►[Ollama Embedding]─►[PGVector]─►[Parse Data]─►[Prompt]─►[Ollama]─►[Chat Output]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;▲
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;│(System Message)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; **(added)** [Message History]─►[Prompt2]─┘

I found that the [Message History] component encountered a compilation error.

### Reproduction

1. Import the workflow file [search_helper.json](https://github.com/user-attachments/files/17943124/search_helper.json).
2. Add the [Message History] and [Prompt] components.
3. Edit the [Prompt] component to include the {memory} variable.
4. Connect the [Message History] and [Prompt] components to [Ollama](Input:System Message).
5. Start the Playground, and an error is displayed as shown in [error.log](https://github.com/user-attachments/files/17943200/Error.building.Component.Message.History.log).

### Expected behavior

The Playground feature works properly.

### Operating System

Ubuntu Linux 20.04

### Langflow Version

1.1.1

### Python Version

None

### Screenshot

playground_error
![error](https://github.com/user-attachments/assets/c9a8cb82-e48d-4cb7-9e83-a1517597a075)

flow_layout
![flow_layout](https://github.com/user-attachments/assets/2485f52a-2084-4cdf-81e1-d6aa8105272e)

### Flow File

flow_file
[search_helper.json](https://github.com/user-attachments/files/17943124/search_helper.json)

error.log
[error.log](https://github.com/user-attachments/files/17943200/Error.building.Component.Message.History.log)

**Comment by tzengshinfu** [comment]
Hi, although it’s already working fine, it feels strange because there shouldn’t be a need to duplicate the flow and then add a new component.
Considering that LangFlow is constantly being updated, I think [this](https://github.com/langflow-ai/langflow/issues/4911#issuecomment-2505564588) can be used as a workaround, and this issue can be closed.

**Comment by edwinjosechittilappilly** [comment]
Hi @tzengshinfu,

You can try the sample flow provided in the documentation:
[Langflow Guide - Store Chat Memory in an External Database](https://docs.langflow.org/guides-chat-memory#store-chat-memory-in-an-external-database).

If you prefer to use the internal database for memory, there’s no need to integrate with an external one. Simply use the chat memory and connect it with the message storage components in your RAG setup.

I hope this sample flow proves useful to you!

**Comment by edwinjosechittilappilly** [comment]
Hi @tzengshinfu,

You can try the sample flow provided in the documentation:
[Langflow Guide - Store Chat Memory in an External Database](https://docs.langflow.org/guides-chat-memory#store-chat-memory-in-an-external-database).

If you prefer to use the internal database for memory, there’s no need to integrate with an external one. Simply use the chat memory and connect it with the message storage components in your RAG setup.

I hope this sample flow proves useful to you!

**Comment by tzengshinfu** [comment]
@edwinjosechittilappilly
Thank you for providing the example. I will study it further. For now, I will close this issue.

**Comment by orinciog** [comment]
I had the same problem and I resolved it by updating the Message History component with the following code:

```
    async def retrieve_messages_dataframe(self) -> DataFrame:
        """Convert the retrieved messages into a DataFrame.

        Returns:
            DataFrame: A DataFrame containing the message data.
        """
        messages = await self.retrieve_messages()
        # Extra code: Ensure each message has required fields properly initialized
        for msg in messages:
            if not hasattr(msg, 'properties') or msg.properties is None:
                msg.properties = {}
            if not hasattr(msg, 'content_blocks') or msg.content_blocks is None:
                msg.content_blocks = []
        return DataFrame(messages)
```
