### ISSUE TITLE
To send Header/Body from a text component to API Request component

### ISSUE THREAD

**Issue by stsfaroz** [langflow-ai/langflow#4921]
### Feature Request

It didn't work when the header / body have been tried to be sent to the api request component. 
![Screenshot (63)](https://github.com/user-attachments/assets/0285297d-aa6d-41bf-b7ac-794862284ba2)

### Motivation

Sending the data to the api request component will be helpful.

**Comment by stsfaroz** [comment]
Answering my question:
Extract the text from headers and utilize it.

API component : 
.....
headers= {'Content-Type': 'application/json' ,"authorization": headers["text"]}

try:
    response = await client.request(method, url, headers=headers, json=data, timeout=timeout)
    try:
        result = response.json()
    except Exception:  # noqa: BLE001
        logger.opt(exception=True).debug("Error decoding JSON response")
        result = response.text
    return Data(
        data={
            "source": url,
            "headers": headers,
            "status_code": response.status_code,
            "result": result,
        },
    )
 ....

**Comment by AbylleAllen** [comment]
Hey man, im actually facing an issue with this, i want to pass the a token as the authorization to the api request, im not able to, can you give an indepth answer as to how to do it?

**Comment by qviuqh** [comment]
```python
    def _process_headers(self, headers: Any) -> dict:
        """Process the headers input into a valid dictionary."""
        if headers is None:
            return {}
        if isinstance(headers, dict):
            return headers
        if isinstance(headers, list):
            return {item["key"]: item["value"] for item in headers if self._is_valid_key_value_item(item)}
        return {}
```
In the _process_headers function given above, you can easily see that this function only processes your input headers, which have a _dict_ or _list_ datatype. However, the API component declares a _List of Data object_ for the input headers (We can see in the source code below)

```python
        TableInput(
            name="headers",
            display_name="Headers",
            info="The headers to send with the request",
            table_schema=[
                {
                    "name": "key",
                    "display_name": "Header",
                    "type": "str",
                    "description": "Header name",
                },
                {
                    "name": "value",
                    "display_name": "Value",
                    "type": "str",
                    "description": "Header value",
                },
            ],
            value=[{"key": "User-Agent", "value": "Langflow/1.0"}],
            advanced=True,
            input_types=["Data"],
            real_time_refresh=True,
```

As a result, we can solve this issue by adding a process that can handle the _List of Data type_ into the **_process_headers function** like this:

```pthon
    # Handle list of Data objects hoặc list of dicts
    if isinstance(headers, list):
        result = {}
        for item in headers:
            # Case: Data object với .data là dict {"Authorization": "Bearer ..."}
            if hasattr(item, "data") and isinstance(item.data, dict):
                result.update(item.data)
            # Case: key-value table format {"key": "...", "value": "..."}
            elif self._is_valid_key_value_item(item):
                result[item["key"]] = item["value"]
        return result
```

<img width="1113" height="642" alt="Image" src="https://github.com/user-attachments/assets/b88dae85-24e8-4d68-8aca-35313b073ce9" />
