### ISSUE TITLE
Error building Component Parse Data:   'question'

### ISSUE THREAD

**Issue by giridharg96** [langflow-ai/langflow#4941]
### Bug Description

<img width="1167" alt="image" src="https://github.com/user-attachments/assets/b7961dc0-99c3-4565-8926-5d5bfee42b4e">

I am using json data as input, then parsing it to convert to text, via :

Question : answer format in the template option.

My data is in below json format:

[{"question":"Hello","answer":"Hi! How can I help you today"},{"question":"What are the main services offered by xxx ?","answer":"The main services offered by xxx include Innovation, yyy,zzz ."}

I am using the template:
Q: {question} 
A: {answer}

But this is throwing the mentioned error.

### Reproduction

Not  a code.

Flow :: File(upload json)  >>> Parse data (error area) (data ) >>>> input to Prompt .

### Expected behavior

Should parse the data and must connect as text input in question, answer format to context of prompt

### Operating System

Mac os 

### Langflow Version

Q: {question}  A: {answer}

### Python Version

3.10

### Screenshot

<img width="1167" alt="image" src="https://github.com/user-attachments/assets/b7961dc0-99c3-4565-8926-5d5bfee42b4e">

**Comment by Cristhianzl** [comment]
Hi @giridharg96,
Could you please provide more details about the issue? Based on your explanation, I created a test flow to replicate the error you're encountering, but everything worked as expected on my end.

Have you tried updating LangFlow to the latest version?
[DOCS](https://docs.langflow.org/get-started-installation#manage-langflow-versions)

![image](https://github.com/user-attachments/assets/6fbb2b1f-df8e-48a1-aa56-ed352f145fda)

Thanks!
