### ISSUE TITLE
File component doesn't load file

### ISSUE THREAD

**Issue by dsolito** [langflow-ai/langflow#4970]
### Bug Description

When I try to load a file, the file is not loaded.
The field stay empty.

log:

Error building Component File: 

Please upload a file for processing.

Traceback (most recent call last):
  File "/Users/dsolito/Library/r-miniconda/envs/langflow/lib/python3.12/site-packages/langflow/graph/vertex/base.py", line 709, in _build_results
    result = await initialize.loading.get_instance_results(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dsolito/Library/r-miniconda/envs/langflow/lib/python3.12/site-packages/langflow/interface/initialize/loading.py", line 68, in get_instance_results
    return await build_component(params=custom_params, custom_component=custom_component)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dsolito/Library/r-miniconda/envs/langflow/lib/python3.12/site-packages/langflow/interface/initialize/loading.py", line 145, in build_component
    build_results, artifacts = await custom_component.build_results()
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dsolito/Library/r-miniconda/envs/langflow/lib/python3.12/site-packages/langflow/custom/custom_component/component.py", line 837, in build_results
    return await self._build_with_tracing()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dsolito/Library/r-miniconda/envs/langflow/lib/python3.12/site-packages/langflow/custom/custom_component/component.py", line 819, in _build_with_tracing
    _results, _artifacts = await self._build_results()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dsolito/Library/r-miniconda/envs/langflow/lib/python3.12/site-packages/langflow/custom/custom_component/component.py", line 885, in _build_results
    result = await asyncio.to_thread(method)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dsolito/Library/r-miniconda/envs/langflow/lib/python3.12/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dsolito/Library/r-miniconda/envs/langflow/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 74, in load_file
ValueError: Please upload a file for processing.

### Reproduction

1. place a new file input component
2. select a file
3. run the component

### Expected behavior

file should be parsed and found

### Operating System

Mac OS

### Langflow Version

1.1.1

### Python Version

3.12

**Comment by dsolito** [comment]
BTW, I have the same problem on Datastax. I was curious if this was linked with my env, but no.

**Comment by dsolito** [comment]
I found that it works when I am on little Arc and not on Arc. Don't know if it's related to Arc or not.

**Comment by adrianlasota** [comment]
@dosu any advice?

**Comment by adrianlasota** [comment]
@dosu how to check Environment-Specific Configurations on Kubernetes ?

**Comment by adrianlasota** [comment]
@dosu my backend logs

```shell
100.64.4.161 - - [04/Dec/2024:08:44:11 +0000] "GET /api/v1/folders/ HTTP/1.1" 200 255 "http://url/flow/4f7a300f-abd8-4251-8090-38f0d18ba821/folder/ecf50476-8950-4f49-aa8a-f9a74fcc0ab3" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0" "10.184.70.1"
2024/12/04 08:44:11 [warn] 11#11: *137 an upstream response is buffered to a temporary file /tmp/proxy_temp/0000000011 while reading upstream, client: 100.64.7.215, server: , request: "GET /api/v1/flows/basic_examples/ HTTP/1.1", upstream: "http://100.65.172.189:7860/api/v1/flows/basic_examples/", host: "url", referrer: "http://url/flow/4f7a300f-abd8-4251-8090-38f0d18ba821/folder/ecf50476-8950-4f49-aa8a-f9a74fcc0ab3"
100.64.7.215 - - [04/Dec/2024:08:44:11 +0000] "GET /api/v1/flows/basic_examples/ HTTP/1.1" 200 1308686 "http://url/flow/4f7a300f-abd8-4251-8090-38f0d18ba821/folder/ecf50476-8950-4f49-aa8a-f9a74fcc0ab3" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0" "10.184.70.1"
100.64.4.161 - - [04/Dec/2024:08:44:11 +0000] "GET /api/v1/flows/?get_all=true&header_flows=true HTTP/1.1" 200 550 "http://url/flow/4f7a300f-abd8-4251-8090-38f0d18ba821/folder/ecf50476-8950-4f49-aa8a-f9a74fcc0ab3" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0" "10.184.70.1"
100.64.4.161 - - [04/Dec/2024:08:44:11 +0000] "GET /api/v1/flows/?components_only=true&get_all=true HTTP/1.1" 200 2 "http://url/flow/4f7a300f-abd8-4251-8090-38f0d18ba821/folder/ecf50476-8950-4f49-aa8a-f9a74fcc0ab3" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0" "10.184.70.1"
10.167.23.196 - - [04/Dec/2024:08:44:15 +0000] "GET /index.html HTTP/1.1" 200 1111 "-" "kube-probe/1.23" "-"
10.167.23.196 - - [04/Dec/2024:08:44:15 +0000] "GET /index.html HTTP/1.1" 200 1111 "-" "kube-probe/1.23" "-"
10.167.23.196 - - [04/Dec/2024:08:44:25 +0000] "GET /index.html HTTP/1.1" 200 1111 "-" "kube-probe/1.23" "-"
10.167.23.196 - - [04/Dec/2024:08:44:25 +0000] "GET /index.html HTTP/1.1" 200 1111 "-" "kube-probe/1.23" "-"
10.167.23.196 - - [04/Dec/2024:08:44:35 +0000] "GET /index.html HTTP/1.1" 200 1111 "-" "kube-probe/1.23" "-"
10.167.23.196 - - [04/Dec/2024:08:44:35 +0000] "GET /index.html HTTP/1.1" 200 1111 "-" "kube-probe/1.23" "-"
100.64.0.111 - - [04/Dec/2024:08:44:41 +0000] "GET /api/v1/store/tags HTTP/1.1" 500 13 "http://url/flow/4f7a300f-abd8-4251-8090-38f0d18ba821/folder/ecf50476-8950-4f49-aa8a-f9a74fcc0ab3" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0" "10.184.70.1"
10.167.23.196 - - [04/Dec/2024:08:44:45 +0000] "GET /index.html HTTP/1.1" 200 1111 "-" "kube-probe/1.23" "-"
10.167.23.196 - - [04/Dec/2024:08:44:45 +0000] "GET /index.html HTTP/1.1" 200 1111 "-" "kube-probe/1.23" "-"
```

**Comment by adrianlasota** [comment]
@dosu it doesn't work on MS Edge browser.

**Comment by erichare** [comment]
@adrianlasota do you have access to Chrome or another browser? Can you confirm it works there in the same environment, but not with Edge?

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to help you.

**Comment by adrianlasota** [comment]
sorry, I lost mail notification. Not sure what changed, but it's working fine on MS Edge and Chrome today.
