### ISSUE TITLE
[Bug] When a component's status is inactive/Execution blocked the tooltip isn't visible properly in both light & dark theme

### ISSUE THREAD

**Issue by msmygit** [langflow-ai/langflow#5063]
### Bug Description

Hi,
When a component's status is inactive/Execution blocked the tooltip isn't visible properly in both light & dark theme

https://github.com/langflow-ai/langflow/blob/main/src/frontend/src/CustomNodes/GenericNode/components/NodeStatus/index.tsx#L205

![image](https://github.com/user-attachments/assets/65b53c57-9a87-4b90-b5bc-0c6132d27927)
![image](https://github.com/user-attachments/assets/ef64826f-4f4b-4a2b-af54-991c79d1aeb7)

This was found in the cloud hosted version as of this afternoon.

### Reproduction

I don't know how to get a component to an inactive/execution blocked state, but one of my flow (with `Combine Text` component) was in that state.

### Expected behavior

When mouse overing the 🚫 sign on the component, it needs to display the `Execution blocked` clearly in both light as well as in dark theme modes.

### Who can help?

@anovazzi1 @Cristhianzl @lucaseduoli @igorrCarvalho 

### Operating System

macOS Sonoma 14.7

### Langflow Version

DS LF as of 04-Dec-2024 1330 US ET

### Python Version

None

### Screenshot

See above in description

### Flow File

[my_testing.json](https://github.com/user-attachments/files/18012697/my_testing.json)

**Comment by Cristhianzl** [comment]
Hi @msmygit 

Thanks for your feedback.
Have a nice week.

Fix: #5162
