### ISSUE TITLE
Loading... spins forever using docker image 1.1.1

### ISSUE THREAD

**Issue by blazux** [langflow-ai/langflow#5085]
### Bug Description

Hi,

I've upgraded langflow to version 1.1.1 pulling the latest docker image, I can log in, see the flows I've created on earlier version, but each time I try to edit one, I just got a loading screen.

I've tried to flush everything to have a fresh new install, deleted both langflow and postgres container and volumes, restarted everything, and I still got the same problem. I've also tried to use docker image v1.1.0 but it's even worth, with 1.1.0 I got a bunch of "table creation error" when langflow tries to start.

I don't see any error in the browser console, I've tried Brave and Firefox private browsing/normal, always the same.

Is there any way to get debug logs to see what's going on ?

### Reproduction

1. Set Langflow up using docker
2. Create a new flow
3. Wait forever

### Expected behavior

A blank flow appear, with components on the side and everything.

### Operating System

Debian 12

### Langflow Version

1.1.1

### Python Version

None

### Screenshot

![image](https://github.com/user-attachments/assets/538da203-b8fc-429e-813f-614c93c39b78)

**Comment by blazux** [comment]
I've been fiddling with things since this morning, and BAM 12 flows appeared all of a  sudden and now it works. I can't really tell what did the trick.

But it works fine now !!!!

**Comment by greenmotion** [comment]
I have the same issue, but I am running Langflow i1.1.1 n a Python venv; NOT via docker image.

It is sporadic and when it happens and I see /api/v1/refresh return an authentication error, even though I had just logged in a minute prior. Doing a browser reload often clears the issue.
