### ISSUE TITLE
@italojohnny

### ISSUE THREAD

**Issue by AQK99** [langflow-ai/langflow#5196]
@italojohnny 
I'm facing the same issue when connecting postgres with ORM. 
can we reopen this ticket? I don't see the issue was fixed here

@vertgo can you confirm if you found a work around or got this fixed?

I'm running it on a Mac OS M3

_Originally posted by @AQK99 in https://github.com/langflow-ai/langflow/issues/3111#issuecomment-2533143777_

**Comment by italojohnny** [comment]
If you need assistance, please open an issue describing your problem.
