### ISSUE TITLE
question: Should the bson package be re-added to the project?

### ISSUE THREAD

**Issue by italojohnny** [langflow-ai/langflow#5246]
### Bug Description

Hello team,

While running the unit tests locally, I encountered the following error:
```
.venv/lib/python3.10/site-packages/astrapy/ids.py:19: in <module>
    from bson.objectid import ObjectId  # noqa: F401
ModuleNotFoundError: No module named 'bson.objectid'
```
It seems the code still requires the bson package, specifically for bson.objectid.ObjectId. However, I noticed that PR #3924 was created to remove it.

Could you clarify if bson should be re-added as a dependency, or if there’s an alternative approach to address this issue?

Thank you!

### Reproduction

make unit_tests

### Expected behavior

I hope the unit tests run without errors.

### Who can help?

@ogabrielluiz 
@jordanrfrazier 

### Operating System

macos

### Langflow Version

1.1.1

### Python Version

3.12

### Screenshot

![Screenshot 2024-12-13 at 10 41 31](https://github.com/user-attachments/assets/4b47388c-f1ae-4be8-b3f8-c7d3f0dcfa95)

**Comment by ogabrielluiz** [comment]
I think so. I'd expect it to be installed if it is a dependency of Astrapy's.

**Comment by jordanrfrazier** [comment]
`bson` should be installed via `pymongo`, and it is explicitly recommended to not install `bson` from pypi:
```
Do not install the “bson” package from pypi. PyMongo comes with its own bson package; doing “pip install bson” or “easy_install bson” installs a third-party package that is incompatible with PyMongo.
```
https://pymongo.readthedocs.io/en/stable/installation.html

Maybe the import change I made is incorrect, let me check

**Comment by jordanrfrazier** [comment]
astrapy removed `bson` in favor of `pymongo` about four months ago - https://github.com/datastax/astrapy/pull/297

**Comment by italojohnny** [comment]
The issue does not occur on the latest main.
