### ISSUE TITLE
unable to pip install langflow

### ISSUE THREAD

**Issue by eladrave** [langflow-ai/langflow#5282]
### Bug Description

When I try to do pip install langflow, it takes hours and then fails, and I have to restart it.

For example, when it tries to install :

Collecting opentelemetry-proto==1.11.1

 Using cached opentelemetry_proto-1.11.1-py3-none-any.whl (66 kB)

INFO: pip is looking at multiple versions of overrides to determine which version is compatible with other requirements. This could take a while.

INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.

This is an example with opentelemetry, but this happens for other libraries..

It continues to "count down" on the versions untill it find it:

Collecting opentelemetry-exporter-otlp-proto-grpc>=1.2.0

 Using cached opentelemetry_exporter_otlp_proto_grpc-1.6.0-py3-none-any.whl (14 kB)

Collecting opentelemetry-proto==1.6.0

 Using cached opentelemetry_proto-1.6.0-py3-none-any.whl (54 kB)

Collecting opentelemetry-exporter-otlp-proto-grpc>=1.2.0

 Using cached opentelemetry_exporter_otlp_proto_grpc-1.5.0-py3-none-any.whl (14 kB)

Collecting opentelemetry-proto==1.5.0

 Using cached opentelemetry_proto-1.5.0-py3-none-any.whl (54 kB)

Collecting opentelemetry-exporter-otlp-proto-grpc>=1.2.0

 Using cached opentelemetry_exporter_otlp_proto_grpc-1.4.1-py3-none-any.whl (14 kB)

Collecting opentelemetry-proto==1.4.1

 Using cached opentelemetry_proto-1.4.1-py3-none-any.whl (54 kB)

Collecting opentelemetry-exporter-otlp-proto-grpc>=1.2.0

 Using cached opentelemetry_exporter_otlp_proto_grpc-1.4.0-py3-none-any.whl (14 kB)

Collecting opentelemetry-proto==1.4.0

 Using cached opentelemetry_proto-1.4.0-py3-none-any.whl (54 kB)

Collecting opentelemetry-exporter-otlp-proto-grpc>=1.2.0

 Using cached opentelemetry_exporter_otlp_proto_grpc-1.3.0-py3-none-any.whl (14 kB)

 Using cached opentelemetry_exporter_otlp_proto_grpc-1.2.0-py3-none-any.whl (14 kB)

******

Since this is the 4th time of me restarting the pip install langflow, it has some packages in the cache, but still, i was unable to complete the setup

For this reason, we cannot test langflow in python code

### Reproduction

1. clean machine (or devcontainer) 
2. pip install langflow
3. wait :)

### Expected behavior

Installed

### Who can help?

@ita

### Operating System

Any 

### Langflow Version

latest

### Python Version

3.11

**Comment by hfhfn** [comment]
I had the same problem

**Comment by rainmanp7** [comment]
The issue you're encountering with pip install langflow taking a long time and failing due to dependency resolution is a common one. This happens when pip tries to resolve a complex set of dependencies and finds multiple compatible versions, leading to a long process of backtracking to find a compatible set.

**Comment by meekhumor** [comment]
instead of `pip install langflow`, try installing it by uv `uv pip install langflow`

**Comment by Richa2112** [comment]
I am getting a below error while installing langflow :
Using Python 3.11.9 environment at:
⠙ Resolving dependencies...
error: Failed to fetch: `https://pypi.org/simple/langflow/`
  Caused by: Request failed after 3 retries
  Caused by: error sending request for url (https://pypi.org/simple/langflow/)
  Caused by: operation timed out
