### ISSUE TITLE
Unable install on mac

### ISSUE THREAD

**Issue by osoluche** [langflow-ai/langflow#5307]
### Bug Description

Starting a fresh install, i cant install via "pip install langflow", in the package  "gotrue*" returns this error => "  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /packages/b8/89/4b1dffdf9cef64f6253875983a8aed1a6e3f6c405cc958f9f315c9846e64/gotrue-2.9.3-py3-none-any.whl.metadata"

Trying to reinstall in same directory, receive different error =>

langflow/venv/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 457, in resolve
    raise ResolutionTooDeep(max_rounds)
pip._vendor.resolvelib.resolvers.ResolutionTooDeep: 200000

Then the installation fails, i'm using macos sonoma 14.7

### Reproduction

only "pip install langflow" in your virtualenv

### Expected behavior

just i wanna install the new version

### Operating System

MacOsx 14.7

### Langflow Version

v1.1.1

### Python Version

3.12

### Screenshot

![imagen](https://github.com/user-attachments/assets/9bce75c8-2e1d-4503-a009-6caa3d6ce5a7)

![imagen](https://github.com/user-attachments/assets/f3d0c8ee-7a55-42d4-be43-b4526e34b600)

**Comment by carlosrcoelho** [comment]
Hi @osoluche 

We are aware of the delay with installation via pip install, and we will have a new release with the fix soon.

In the meantime, we recommend installation via `uv`.

Below is the documentation:

https://docs.langflow.org/get-started-installation
