### ISSUE TITLE
Custom Component "display_name" from the code is not displayed in UI

### ISSUE THREAD

**Issue by rodolfo3** [langflow-ai/langflow#5361]
### Bug Description

Set "display_name" prop on python code does not show the component name on the UI

### Reproduction

1. create a new flow
2. click on "New Custom Component" on the bottom left
3. into the new component added to the flow, click "code"
4. Change the class attributes "display_name" and "name"
5. click "Check & Save" button

The UI keep showing the "Custom Component" as title

### Expected behavior

The UI should respect the "display_name" from the code (not only when it is changed by clicking on the title).

### Operating System

debian testing

### Langflow Version

1.1.1

### Python Version

None

**Comment by carlosrcoelho** [comment]
Hey @rodolfo3 

This has already been adjusted and will be available in the next release, around mid-January.

In the meantime, the option you can use is to double-click where it says Custom Component and change it to whatever name you want.

https://github.com/user-attachments/assets/594e15ca-9794-43f3-9f59-84ae095c4947
