### ISSUE TITLE
URL component lost imported urls in tool mode when refresh UI

### ISSUE THREAD

**Issue by tamdqa** [langflow-ai/langflow#5378]
### Bug Description

I have this issue when i build multi agent flow like import json below
- URL Component Before refresh UI:
![image](https://github.com/user-attachments/assets/f361501d-3d11-4e4a-b560-203faf8a4935)
![image](https://github.com/user-attachments/assets/4ee6c93f-914b-4efa-b0eb-5a13f5c404fa)

After refresh UI:
![image](https://github.com/user-attachments/assets/2224a76e-1dd7-42d4-8531-a5e86719653c)
![image](https://github.com/user-attachments/assets/3753754f-3a16-4bfc-a82e-1286c7504fe3)

I have check in normal mode of URL Component, and this bug does not appear.

### Reproduction

1. Create flow
2. Add URL component, change to Tool mode
3. Input Urls
4. Save flow
5. Reload UI (Press F5)

### Expected behavior

URL component has keep Urls has input. In Tool mode

### Operating System

Windows 11/Docker

### Langflow Version

v1.1.1

### Python Version

None

### Flow File

[Simple Agent (bug).json](https://github.com/user-attachments/files/18206463/Simple.Agent.bug.json)

**Comment by ZacharyLeahan** [comment]
Same issue here. Here's a GIF. 
![Animation](https://github.com/user-attachments/assets/caa8032a-6781-441e-8a78-abca6685f9ca)

**Comment by ZacharyLeahan** [comment]
@tamdqa Ok actually it dawned on me "receiving input" is what the user would input in the playground (not hardcoded in flow). So in the playground try asking to scrape a url and you'll see the agent choose to use the url tool.  
![Animationferns](https://github.com/user-attachments/assets/b7134e23-ceeb-4801-affa-882609e168fd)
So @lucaseduoli  This could be closed (or maybe consider a small UI enhancement so the + icon isn't there in tool mode when it isn't relevant during flow definition).

**Comment by lucaseduoli** [comment]
Hi! Thanks for the feedback! We'll make that change as soon as possible. Indeed the tool mode is made so that the Agent can scrape the URLs by itself. Thanks!
