### ISSUE TITLE
Error Building Component - Docker

### ISSUE THREAD

**Issue by Gabrieln18** [langflow-ai/langflow#5470]
### Bug Description

Hello, I'm having a issue with Langflow v1.1.1, I've been using the version with Docker normally, until after a while I noticed that the platform's AI models notify an unexpected error of the type: (**Error Component Error building Component OpenAI**), but when using other models such as Groq Component, HuggingFace or OpenAI, the same error appears - This applies to embedding models as well. Does anyone know if this can be resolved?

### Reproduction

Common Errors Messages:
- Error Building Component Error building Component (OpenAI, Groq or HuggingFace) - Models
- Erroar Building Component Error building Component HuggingFace - Embedding Models

### Expected behavior

I want you to discover the error behind the Error Component Error building Component Models.

### Operating System

Ubuntu Linux 22.04

### Langflow Version

1.1.1

### Python Version

3.10

### Screenshot

![Captura de tela de 2024-12-27 15-30-43](https://github.com/user-attachments/assets/ea468a6c-e4da-4aa6-a06b-da2aca207b2f)

**Comment by nabrgm** [comment]
You should click on this button below 
![Screenshot 2024-12-27 at 8 36 30 PM](https://github.com/user-attachments/assets/bb1107e9-f495-40a1-bed8-7f941f420324)
to get more info on this. What does it say?

**Comment by Gabrieln18** [comment]
Hi @nabrgm , sorry about that, I couldn't wait for an answer, so I tried several ways and came to a temporary conclusion. I restarted my docker and used `docker-compose start/stop` instead of `docker-compose up/down`, I realised it works (because docker preserves container states - or something). If the problem still persists, I'll report it again.

**Comment by nabrgm** [comment]
@Gabrieln18 glad you figured it out!

You should close this then :)
